taichi-dev/taichi

- python/taichi/visual/renderer.py
- python/taichi/visual/viewer.py
Removes the dependency on opencv from the renderer in favor of TKinter (which is included with Python) and adds a new dependency on Pillow.
The frame viewer automatically updates for each frame and can be disabled by invoking a script like `python bubbles.py --no-viewer`.
> Add a frame viewer

- examples/volume_renderer.py
Density array should be [density_res x density_res x density_res], not [res x res x res] (as `res` is the image resolution and `density_res` is the resolution of the density array).
> Fix density array size for volume rendering example

- cmake/TaichiCXXFlags.cmake
$ cmake ..  -DCMAKE_C_COMPILER=/usr/local/clang-8.0.1/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/clang-8.0.1/bin/clang++   -DPYTHON_EXECUTABLE=python3.6
Taichi Version 0.3.21
Commit efcb7657ed6796da2f6cd16abe03dbcc4d33bc48
Using C++ compiler: /usr/local/clang-8.0.1/bin/clang++
Clang compiler detected. Using std=c++17.
Building for processor aarch64
Using float32 (single) precision as real
Using python3.6 as python executable.
Python 3.6.9
version: 3.6
include: /usr/include/python3.6m
library: PYTHON_LIBRARY-NOTFOUND
numpy include: /usr/local/lib/python3.6/dist-packages/numpy/core/include
pybind11 include: /usr/local/include/python3.6;/home/jetson/.local/include/python3.6m
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - …
> cmake on NVIDIA Jetson 

- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- taichi/backends/codegen_llvm.h
- taichi/backends/codegen_llvm_ptx.cpp
- taichi/ir.h
- taichi/python_bindings.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_atomic.py
Issue #332 
I've finally got things working (only tested on CPU, sadly...). I had to make a few changes to IR passes to adapt to this change. Specifically:
1. Demote atomics should replace the demoted stmt with the **old value** loaded before add, as you've pointed out in https://github.com/taichi-dev/taichi/issues/332#issuecomment-573485416
1. `LocalStoreStmt` cannot be simplified in a few cases where atomic ops appeared
1. `IfStmt` cannot move certain `LocalStore` out of the branch clauses if the store depends on atomic operations. This one is somewhat nontrivial in this change, as it does two things
1. it no longer moves `LocalStore` that depend on atomics, for correctness reasons
1. it no longer moves `AllocaStmt` that is 1) in the clause, and 2) the dest of `LocalStore`. This is for …
> Make atomic_add() return value (should be ready to review...)

- taichi/ir.h
`SNodeOpStmt` can be either `append` or `length`, so its return type is `i32`. However, it seems that the current code is not causing a problem, because [its type is later set to `i32` in `type_check.cpp`](https://github.com/taichi-dev/taichi/blob/master/taichi/transforms/type_check.cpp#L93). So this PR just reduces confusion..?
> Fix how SNodeOpStmt's type is set

- taichi/cuda_utils.h
Due to the rule of C macros, when you write:
`check_cuda_errors(cudaAPI(233));`
You actually did `cudaAPI(233)` three times if it result in error.
Expanded:
```
if (int(cudaAPI(233))) {
TC_ERROR("Cuda Error {} {}", cudaAPI(233), cudaAPI(233));
}
```
You'll lose the infomation of first call to `cudaAPI(233)`.
Please use a temperate variable to save it.
Might be the cause of issue #356.
> check_cuda_errors: err evaluated three times

- python/taichi/lang/expr.py
There are two `__getitem__` defined for `Expr`. I believe only [the later one](https://github.com/taichi-dev/taichi/blob/master/python/taichi/lang/expr.py#L200) is used, so removing the first one...
> remove unused __getitem__ in Expr

- taichi/backends/llvm_codegen_utils.h
- taichi/backends/llvm_jit.h
I'm refactoring the Objective-C API and bumped into this problem. Without writing out the full name, there is a name conflict between `llvm::Moduel` and objc's `Module` type...
> Add llvm:: namespace qualifier

- cmake/TaichiCore.cmake
- taichi/common/util.h
- taichi/platform/mac/objc_api.cpp
- taichi/platform/mac/objc_api.h
- taichi/platform/metal/metal_api.cpp
- taichi/platform/metal/metal_api.h
Issue #396 
1. I put the Metal related code under `platform/metal`, but not sure if this is the best option. We can also put it under `platform/mac/metal`, but then it seems too deeply nested..?
1. I can confirm this works because I've rebase my Metal branch onto this. You can also find a minimal example here: https://github.com/k-ye/cpp-host-metal/blob/master/main.cpp. And of course, a lot of the code are borrowed from Halide's design: https://github.com/halide/Halide/blob/master/src/runtime/metal.cpp
1. Let me know if this breaks other platforms again...
> Add basic Metal APIs

- taichi/platform/metal/metal_data_types.cpp
- taichi/platform/metal/metal_data_types.h
Issue #396 
For binary operations, I just relied on the builtin Metal operators, instead of implementing our own as `runtime.cc` did. Because of this, a lot of the binary ops need to be emitted in infix order.
TEST
* `ti test` passed
* Rebased `metal` branch onto this and verified it's working
> Add Metal data types

- taichi/context.h
- taichi/platform/metal/metal_kernel_util.cpp
- taichi/platform/metal/metal_kernel_util.h
In the next PR, I plan to add `struct_metal.{h|cc}`. They will use some
of the data structures defined here.
> Add data structures necessary for Metal kernels compilation and launch

- taichi/backends/struct_metal.cpp
- taichi/backends/struct_metal.h
Issue #396 
This one produces the Metal source code for the corresponding SNodes. I mostly followed [how `struct.cc` generated these types](https://github.com/taichi-dev/taichi/blob/master/taichi/backends/struct.cpp#L135-L199). I.e. an interleaved chain of `S0 -> S0_ch -> S1 -> S1_ch ...`.
Example:
* Taichi
```py
x = ti.var(ti.i32)
y = ti.Vector(2, dt=ti.f32)
n = 128
@ti.layout
def place():
sn = ti.root.dense(ti.i, n)
sn.place(x)
sn.dense(ti.j, n).place(y)
```
* Metal
```cpp
namespace {
using byte = uchar;
struct S5 {
// place
constant static constexpr int stride = sizeof(float);
S5(device byte* v) : val((device float*)v) {}
device float* val;
};
struct S4 {
// place
constant static constexpr int stride = sizeof(float);
S4(device byte* v) : val((device float*)v) {}
device float* val;
}; …
```
> Add Metal SNode compiler

- docs/contributor_guide.rst
Hi @yuanming-hu , to easily navigate between python and cpp, I've just added support for taichi in [ffi-navigator](https://github.com/tqchen/ffi-navigator) tool in [this commit](https://github.com/tqchen/ffi-navigator/pull/32) (the large diff there comes from testing code for dummy repo, the actual implementation is only [30 lines](https://github.com/tqchen/ffi-navigator/blob/master/python/ffi_navigator/dialect/taichi.py#L7-L38)).
Their gif demos on their README (emacs one recorded by me!) should give you a good sense of what ffi-navigator can do. I happen to have a detailed knowledge of the project so I was able to add taichi support with minimum effort. 
Right now it can jump from python symbols such as
* `ti.core.global_var_expr_from_snode`
* `taichi_lang_core.expr_add`, …
> Mention ffi-navigator support in Python README

- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
Issue #396 
I left out the kernel launching part to the next PR in order to reduce the size of this one...
Metal runtime is integrated with the memory pool :)
> Add Metal runtime manager skeleton code

- taichi/arch.h
- taichi/memory_pool.cpp
- taichi/tlang_util.h
- taichi/unified_allocator.cpp
- taichi/unified_allocator.h
This change is to decouple the allocator from just `x86` or `cuda` archs. 
As part of the refactor, I also moved the Arch enum into its own file. Alternatively, we can just let `unified_allocator.h` depend on `tlang_util.h`, but I feel like it's better to decompose this into smaller modules?
> Refactor UnifiedAllocator to take in the kernel arch

- python/taichi/core/util.py
when a string is passed from python to C++, convert it into locale encoding, or it will fail if you try to pass it to OS API as file path.
> use locale_encode() for lib_dir #428

- python/taichi/misc/settings.py
Provide better message if non-developer user set TAICHI_REPO_DIR wrongly.
Might be the solution of @dodydharma's problem:
after linux restart, when running the python script with taichi, it is always failed like this:
```
File "fractal.py", line 1, in <module>
File "/usr/local/lib/python3.6/dist-packages/taichi/init.py", line 1, in <module>
from taichi.main import main
File "/usr/local/lib/python3.6/dist-packages/taichi/main.py", line 6, in <module>
from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
File "/usr/local/lib/python3.6/dist-packages/taichi/tools/video.py", line 3, in <module>
import taichi.core as core
File …
```
> raise error when TAICHI_REPO_DIR invalid

- taichi/backends/codegen_metal.cpp
- taichi/backends/codegen_metal.h
Issue #396 
Most of the implementation are copied from the legacy codegen.
* Each `OffloadedStmt` causes a metal kernel to be generated.
* `LoopIndexStmt`: We launch `n = end - begin` number of threads, so the thread ID `utid_`, given by Metal, is `0 <= utid_ < n`. The loop index is therefore `utid_ + begin`.
* `BinaryOpStmt`: special handling of `floordiv`. The impl is identical to [`ifloordiv()`](https://github.com/taichi-dev/taichi/blob/afc63bd1e714cddae55b9ddb61a1ba4993d91c4c/taichi/runtime/runtime.cpp#L77)
* `AtomicOpStmt`: Metal doesn't support atomic floating point number. As a workaround, we compute the result using plain `+`, then cast that value as an integer pointer and do CAS in a loop. This appears to work OK.
* `RandStmt` is not supported yet
> Add IR visiting methods for Metal codegen

- python/taichi/lang/__init__.py
- taichi/kernel.cpp
- taichi/platform/metal/metal_runtime.cpp
- taichi/program.cpp
- taichi/program.h
- taichi/snode.h
- taichi/tlang_util.cpp
Issue #396 
A few cleanups:
* As you've suggested in #448 , let me move `fatomic_add` (probably `ifloordiv()` as well) to a separate function.
* I think the codegen part doesn't have to be guarded by `TC_SUPPORTS_METAL`, only the runtime parts does. This isn't that important, though.
One question: I started to use `std::optional`, which is only available in C++17. Is Metal always compiled with C++17?
Also, I'd like to port all those tests that only use `dense` to Metal before we announce `ti.metal` is available. WDYT?
> Plugin in Metal backend to Taichi!

- python/taichi/lang/__init__.py
- taichi/extension.cpp
- taichi/extension.h
- taichi/inc/extensions.inc.h
- taichi/python/export_misc.cpp
- taichi/python_bindings.cpp
Also added the (informal) concept of Extension to define which set of features
an Arch can support.
For now, `extension` has two enums: `sparse` and `data64`. The later one is because Metal kernel doesn't support 64-bit buffers...
> Add ti.require() and ti.archs_excluding() decorators

- taichi/backends/codegen_metal.cpp
- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
- taichi/program.cpp
Issue #396 
* `union_cast` was not handled previously (found by `test_svd.py`)
* Flip the order of threadsPerGroup and threadgroups (found by `test_listgen.py`). Can't believe it actually worked before!
* Make sure all the buffers have a non-empty size, or some buffers may not get initialized (found by `test_empty.py`)
> Fix bugs found when porting tests to Metal

- python/taichi/lang/__init__.py
- python/taichi/lang/kernel.py
- tests/python/test_ad_basics.py
- tests/python/test_arg_load.py
- tests/python/test_cast.py
- tests/python/test_dynamic.py
- tests/python/test_internal_func.py
- tests/python/test_linalg.py
- tests/python/test_listgen.py
- tests/python/test_loops.py
- tests/python/test_numpy.py
- tests/python/test_numpy_io.py
- tests/python/test_parallel_range_for.py
- tests/python/test_print.py
- tests/python/test_random.py
- tests/python/test_sparse_basics.py
- tests/python/test_sparse_deactivate.py
- tests/python/test_sparse_parallel.py
- tests/python/test_struct_for_dynamic.py
- tests/python/test_svd.py
- tests/python/test_unary_ops.py
A few fixes
* Fixed kernel.py to set PyTorch tensor device to cuda only if arch == ti.cuda
* Fixed ti.all_archs_with to get fp/ip from |kwargs|
* Rename some variables in the decorators so that it is obvious which function should be the test
IMO, the `ti.all_archs_with()` is getting a bit complicated to set up now, especially if I passed in something that's a reference  (e.g. `arch=ti.cfg.arch`. It seems that `ti.cfg.arch` is a reference value, so `arch` could actually change after `ti.reset()`). I think it's better for taichi's `default_config()` to be an immutable config, and use `current_config()` as the one to be the mutable config. Also, to eliminate the by-reference problem,  the C++ side can provide `cfg`'s members' getter/setters, where getters return a copy of the value, as least …
> Port all the existing tests to Metal

- taichi/common/util.h
- taichi/platform/mac/objc_api.h
- taichi/platform/metal/metal_api.cpp
- taichi/platform/metal/metal_api.h
- taichi/platform/metal/metal_runtime.cpp
- taichi/program.cpp
- taichi/python/export_misc.cpp
Since we are likely need more time review #457 , I've separated out the Metal API detection to allow Travis CI to run successfully.
Note that this PR doesn't contain the Metal runtime fix around the number of threads, so it may still crash if you run locally..
> Fix Travis CI by detecting Metal API at runtime

- taichi/backends/codegen_metal.cpp
- taichi/backends/codegen_metal.h
- taichi/backends/struct_metal.cpp
- taichi/backends/struct_metal.h
- taichi/common/util.h
- taichi/platform/mac/objc_api.cpp
- taichi/platform/metal/metal_api.cpp
- taichi/platform/metal/metal_api.h
- taichi/platform/metal/metal_data_types.cpp
- taichi/platform/metal/metal_data_types.h
- taichi/platform/metal/metal_kernel_util.cpp
- taichi/platform/metal/metal_kernel_util.h
- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
- taichi/program.cpp
- taichi/program.h
Issue #396 
Sorry about the large size, I'm mostly moving `MetalRuntime`'s code to `cpp` file.
* Use Pimpl for MetalRuntime so that we don't have to check TC_PLATFORM_OSX
whereever it's been used.
* Correctly detects the Metal API availability at runtime
* If Metal API is not available, Program will automatically falls back to x86_64
> Major Metal compiler/runtime refactors

- taichi/backends/codegen_metal.cpp
- taichi/platform/metal/helpers.metal.h
Do you think this is a cleaner approach :D ? Why am I having a feeling that we will eventually be burned by such abuses of the macros...... 
BTW I tried to use the raw string literals but gave up after a few tries. The problem is that raw string literals evaluation priority seems higher than the macro defs. So for something like
```cpp
#define METAL_BEGIN_HELPERS_DEF constexpr auto kMetalHelpersSourceCode = R("
#define METAL_END_HELPERS_DEF )";
```
That actually evaluates to `kMetalHelpersSourceCode = R("#define METAL_END_HELPERS_DEF )";`!
With the current approach, `kMetalHelpersSourceCode` is a giant single-line string[1]. But it works fine since Metal compiler doesn't care...
1. In case you're interested, it's `template <typename T, typename G> T union_cast(G g) { …
> Move Metal helpers to helpers.metal.h

- taichi/io/io.h
It is no longer experimental in C++17, and it causes compile error in MSVC.
> Remove "experimental" in "<experimental/filesystem>"

- taichi/backends/struct_llvm.cpp
- taichi/taichi_llvm_context.h
I'm planning to use LLVM context and saw this method. I feel like it's a bit cleaner to just pass in the function type signature?
> Simplify lookup_function's template args by not passing std::function

- taichi/cuda_utils.h
> use do-while-0 for check_cuda_error*

- python/taichi/main.py
Example usage:
```
ti test_python test_abs.py test_basics.py
```
I think this simplifies the devs's work if they want to run a specific test file locally. I'd like to support these for `ti test` `ti test_verbose` as well, but then the CPP tests are already using `sys.args[2:]`... IMO it's better to rewrite this using [`argparse`](https://docs.python.org/3/library/argparse.html) 
No issue..
> Allow `ti test_python` to take in individual test files

- examples/mpm128.py
- taichi/gui/cocoa.cpp
Follow up of PR #459  by @archibate 
I think there are some opportunities for refactoring more:
1. All the key string constants (e.g. `"Shift"`) can be defined in a single place and shared by all platforms.
2. `MouseEvent` should probably include a button field to distinguish left, middle or right.
https://github.com/taichi-dev/taichi/blob/2097096488de7641c242b5274cd020ca1a1e5013/taichi/visual/gui.h#L495
3. For mouse events, we can do the `push_back` here:
https://github.com/taichi-dev/taichi/blob/2097096488de7641c242b5274cd020ca1a1e5013/taichi/visual/gui.h#L718
4. Actually,  I think `key_events` is a little bit abused for holding mouse events.  Maybe have `ti.has_input_event()` and `ti.get_input_event()`?  The item returned by `ti.get_input_event()` has a type to tell if it's a mouse or …
> Support GUI key/mouse events on Mac OS X

- appveyor.yml
This makes taichi.main can return exit code instead of always 0.
Btw, simply `ti test` fails because `cmd` doesn't support sh-bang, i.e. `#!/usr/bin/python`.
> python bin/taichi instead of python -m taichi, for exit code

- taichi/arithmetic.h
- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
- taichi/program.cpp
- taichi/runtime/runtime.cpp
Issue #396 
Pros:
1. we can launch SNode reader/write kernels on the host side.
1. Save some memory -- MetalRuntime now doesn't maintain the root buffer's memory (unless the LLVM runtime's memory is zero, in which we still had to allocate to make sure things don't break. This can be cleaned up later..)
Cons:
1. I think the host-side reader/writer kernels work because for dense nodes, the data layout produced by LLVM happen to be the same as how we interpret the memory in Metal. This can be fragile. But given that the dense nodes are really just a bunch of arrays of primitives, i feel that this can work just fine.
2. Because Metal requires both the **address** and the **size**  of its buffer memory to be page aligned ([doc](https://developer.apple.com/documentation/metal/mtldevice/1433382-n …
> Use Runtime::root as Metal root buffer's memory

- taichi/constants.h
- taichi/platform/metal/metal_runtime.cpp
- taichi/runtime/runtime.cpp
- tests/python/test_loops.py
Issue #396 
This is a follow up of #488. I think all this PR does is just to save a few pages...
> Use Runtime::temporaries to back Metal runtime's global tmps buffer

- taichi/transforms/alg_simp.cpp
- taichi/transforms/constant_fold.cpp
- tests/cpp/test_alg_simp.cpp
See https://github.com/taichi-dev/taichi/commit/ab1bfed008518c2dbe206e883d2dda81bfb8b587#r37342924.
Also add cast from i32 to f32 in constant_fold.cpp to write more comprehensive tests more conveniently (obviating the need of writing `TypedConstant(0.0f)` and just write `TypedConstant(0)`).
> Minor fix of alg_simp.cpp and add cast from i32 to f32 in constant_fold

- taichi/transforms/simplify.cpp
- tests/cpp/test_alg_simp.cpp
- tests/cpp/test_simplify.cpp
Related issue id = #464 
I'm confused with those `Stmt*`'s and `std::unique_ptr`'s. The code cannot pass the test now and I'm not sure if I'm writing bugs.
> Lower `linearized` into a series of adds and muls.

- taichi/runtime/node_dense.h
It seems like `num_elements` was miscomputed as `element_size` to me, so I'd like you to help verify if this fix is correct. BTW, I guess the canonical way to write this should be
```cpp
auto num_elements = meta->get_num_elements(meta, node);
```
But then it seems that `StructMeta::get_num_elements` just points to `Dense_get_num_elements` for `dense` SNodes?
(Sorry for the reduced works these days, I'm busy following the news on COVID-19 here in Tokyo 😂 )
> Fix how num_elements is computed in Dense node

- .travis.yml
- .travis/install.sh
- ci_setup.py
- python/build.py
- python/taichi/misc/util.py
> Taichi build on macOS with Python 3.6 to Python 3.8 covered #409

- python/taichi/lang/__init__.py
- python/taichi/misc/gui.py
- taichi/program.h
- taichi/python/export_visual.cpp
- taichi/python_bindings.cpp
- taichi/visual/gui.h
Issue #489 
This PR exposes the profiler methods to Taichi, so that users can profile their scripts:
```python
ti.profiler_start('heavy_work')
heavy_work(foo)
ti.profiler_stop()
```
It also passes the profiler to GUI
> Expose a few profiler methods so that it can be used in Python.

- taichi/gui/cocoa.cpp
- taichi/visual/gui.h
Related issue id: #489 
By assigning the image content to `NSView`'s `layer`, the rendering process improved a lot. We also need to use `updateLayer` instead of `drawRect:` to resolve the screen flickering. Some examples
Let me know if this improves on your end as well (or at least don't cause regression...), if you have time!  :-)
> Use NSView's layer to draw the rendered image

- python/taichi/lang/__init__.py
- taichi/platform/metal/metal_runtime.cpp
- taichi/program.cpp
- tests/python/test_types.py
Related issue id = #504 #396 
Hi @archibate 
Sorry i changed your tests quite a bit, in order to make it work for the Metal backend as well. The problem with Metal is that it doesn't support 64bit buffers, so we had to separate the tests into 64-bit vs the rest. 
I found a nice decorator `@pytest.mark.parametrize()` ([doc](http://doc.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize)) that can somewhat simplify the code. 
Also I saw that you got this "variables are expected to be declared before kernel invocation" problem,  therefore had to create another wrapper inside each test? IIUC, `ti.all_archs(_with)` resets the test case here:
https://github.com/taichi-dev/taichi/blob/57287cf0493f5719e0e8b021fe18cdfe0c20c718/python/taichi/lang/__init__.py#L224
So by putting …
> Make test_types.py work for the Metal backend

- python/taichi/lang/kernel.py
- tests/python/test_empty.py
> Make sure KernelTemplateMapper extractors's size is the same as the number of args

- taichi/kernel.cpp
- tests/python/test_sync.py
Related issue id = -1
I think kernel synchronization can be a bit smarter, i.e. a sync is needed only when a CPU kernel is run after a GPU one. With this change, I saw that `mpm99.py`'s initialization time was reduced from `15s` to `5s` with `quality = 2`. Basically, all those `[]` at startup won't result in a `synchronize()` any more.
However, this might be that Metal's sync has a relatively large overhead. What i'm not sure is that
* Does `cudaDeviceSynchronize()` also have a non-negligible overhead if a large number of `[]` is used?
* Is this still useful, or even correct, once the unified memory is removed?
> Mark sync bit only after running a kernel on GPU

- python/taichi/lang/__init__.py
- python/taichi/lang/kernel.py
- python/taichi/lang/transformer.py
- tests/python/test_oop.py
> fix cannot AST transform due to locals() not saving compile result #538 (2)

- docs/odop.rst
- python/taichi/lang/kernel.py
- python/taichi/lang/tape.py
- tests/python/test_complex_kernels.py
- tests/python/test_oop.py
Related issue id = #548 
Basically, we used the trick in https://stackoverflow.com/a/8793684/12003165 to detect if a function being decorated belongs to a class or not. Note that we cannot apply that trick as-is -- To support OOP, Taichi classes *must* be decorated by `@ti.data_oriented`. So instead of looking for `class `, we look for `@(\w+\.)?data_oriented`
Another thing being unified is `grad` on the wrapped kernel. There is no need for the special kwarg `_gradient: bool` on class kernels now. I made a small change to `DifferentiableMethod` (renamed to  `BoundedDifferentiableMethods`) so that it can get `adjoint` from the passed in wrapped function.
Also, both types of kernels' primal `Kernel` instance have a `grad` referencing the adjoint instance. In this way we are also able to …
> Convert `@classkernel` to `@kernel`

- taichi/codegen/codegen_metal.cpp
- taichi/platform/metal/metal_kernel_util.cpp
- taichi/platform/metal/metal_kernel_util.h
> [refactor] Construct `MetalKernelArgsAttribute` directly from `Kernel::Arg`s

- taichi/common/bit.h
- taichi/ir/snode.cpp
Test case:
```python
ti.root.dense(ti.i, -1)
```
> Add assertions to prevent infinite loop in `least_pot_bound` in case of negative snode size

- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
- taichi/program/program.cpp
Related issue id = #396 
This is basically a revert of what I did in #488 and #500 . I'm afraid having these two modules coupled would complicate your works on the refactoring.
After this PR, `operator[]` becomes slow again. (But i think it's the same for OpenGL and CUDA now, with unified memory disabled)
> [Metal] Decouple Metal's runtime from LLVM memory

- taichi/codegen/codegen_metal.cpp
- taichi/codegen/codegen_metal.h
- taichi/platform/metal/metal_kernel_util.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/struct/struct_metal.cpp
- taichi/struct/struct_metal.h
Related issue id = #396 
* `MetalStructCompiler` is no longer exposed. This is a prep step to support `bitmasked`
* `StructCompiledResult` is moved from `taichi/platform/metal/metal_kernel_util.h` to `taichi/struct/struct_metal.h`
*  Following #568 , we no longer need to `initialize_runtime_system()` inside `Program:: materialize_layout()`.
> [Refactor] Hide MetalStructCompiler to the cpp file

- examples/mgpcg.py
Converted your mgpcg example to to python. Interestingly, the profiler shows that the reduction kernels take the majority of the computational time. Perhaps some optimization work needs to go into these.
> add mgpcg example

- taichi/codegen/codegen_cpu.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/ir.h
- taichi/llvm/llvm_codegen_utils.cpp
- taichi/program/program.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/check_out_of_bound.cpp
- taichi/transforms/ir_printer.cpp
Related issue id = #561
Also extends `AssertStmt` from `(message, condition)` to also `(condition, format_str, values)`.
> Access out-of-bound checking on CPU backends (Stage 1)

- taichi/codegen/codegen_llvm.h
- taichi/runtime/llvm/runtime.cpp
Related issue id = #561
A continuation of #572
> Access out-of-bound checking on CPU backends (Stage 2)

- examples/opengl_range_for.py
- taichi/codegen/codegen_opengl.cpp
- taichi/platform/opengl/opengl_api.cpp
- taichi/platform/opengl/opengl_api.h
- taichi/platform/opengl/opengl_kernel.cpp
- taichi/platform/opengl/opengl_kernel.h
> OpenGL range_for support (stage 2.1.1)

- taichi/system/traceback.cpp
> Fixed print_traceback overflow on OS X

- taichi/codegen/codegen_metal.cpp
- taichi/platform/metal/shaders/atomic_stubs.h
- taichi/platform/metal/shaders/epilog.h
- taichi/platform/metal/shaders/helpers.metal.h
- taichi/platform/metal/shaders/prolog.h
Related issue id = #593 
I created the prolog and epilog code snippet for Metal shaders. They will be more useful when I add the runtime shaders.
We can also use the shader code on both the host and device sides now. This somewhat reduces the necessity of #604 :)
> [Metal] Move Metal shader code to shaders/ folder

- taichi/inc/constants.h
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/runtime/llvm/runtime.cpp
- taichi/system/traceback.cpp
- tests/python/test_assert.py
Related issue id = #591
A continuation of #582
> Testable Device-Side Assertion Failures on CPUs

- taichi/platform/metal/shaders/runtime_kernels.metal.h
- taichi/platform/metal/shaders/runtime_structs.metal.h
- taichi/platform/metal/shaders/runtime_utils.metal.h
Related issue id = #593 
This should look familiar, but not exactly identical to LLVM's runtime. Like `helpers.metal.h`, these are mostly used to generate Metal code, so there's not much documentation. I can add more when implementing the host side..
> [Metal] Add Runtime shaders to support sparse SNode

- .travis.yml
- appveyor.yml
- python/taichi/lang/__init__.py
- python/taichi/main.py
> Use argparse in taichi/main.py to implement #600

- python/taichi/core/util.py
> Make `ti format` cover all files from upstream/master to the working tree

- taichi/codegen/codegen_metal.cpp
- taichi/lang_util.cpp
- taichi/platform/metal/shaders/helpers.metal.h
Related issue id = #606
This is a follow up of #627 
I also found out that Metal's `pow` doesn't support integral types, which are used by the tests. Adding that support here as well.
> Support atomic min/max/bit_and/bit_or/bit_xor on Metal

- taichi/codegen/codegen_metal.cpp
- taichi/struct/struct_metal.cpp
- taichi/util/line_appender.h
Related issue id = N/A
This is mostly code cleanup. I've refactored out a `LineAppender` class, so that we don't have to duplicate the code emitting methods in the codegens.
@archibate  pls let me know if you want me to update this for the OpenGL backend (could accidentally break the tests..), or you prefer doing this yourself.
> Add LineAppender to dedupe code emitting methods

- cmake/TaichiCore.cmake
- taichi/analysis/detect_for_with_break.cpp
- taichi/analysis/gather_deactivations.cpp
- taichi/ir/ir.h
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
- tests/python/test_for_break.py
> Support break in non-parallel for statements by translate range-for into while #578

- taichi/platform/metal/shaders/runtime_utils.metal.h
> [Metal] Silence compile warning with [[maybe_unused]]

- README.md
Trying to separate visible changes from underlying development ("Full log"). Let me know if this makes sense to you guys. We should end up with a formal and consistent format for the release log.
Maybe every PR author should keep in mind that their PR titles will be potentially part of the release log.
> v0.5.8 README

- README.md
- examples/mgpcg_advanced.py
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/transforms/simplify.cpp
Related issue id = #656
I'm now using `test_ad_if_mutable` in `test_ad_if.py` for benchmarking. It already reduced the number of statements from 96 to 92 :)
> Introduce a temporary boolean constant for benchmarking

- python/taichi/lang/snode.py
- taichi/ir/ir.h
- taichi/platform/metal/metal_runtime.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_metal.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_bitmasked.py
Related issue id = #593 
Feel like the tests are pretty weak...
> [Metal] Changes to enable `bitmasked` on Metal!

- taichi/transforms/simplify.cpp
> [Opt] Dive into container statements to find local loads/stores for optimization, and optimize loads of new allocas to 0

- cmake/TaichiCore.cmake
- taichi/inc/statements.inc.h
- taichi/ir/ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
> [ir] Basic function definition/call instructions

- taichi/backends/metal/data_types.cpp
- taichi/backends/metal/data_types.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
- taichi/codegen/codegen_metal.cpp
- taichi/codegen/codegen_metal.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/struct/struct_metal.cpp
- taichi/struct/struct_metal.h
* Because these classes are already inside the `metal` namespace,
they do not need to start with `Metal`.
* Also renamed `metal::Runtime` to `metal::KernelManager`.
Related issue = #593 
> [metal] Simplify Metal backend's namings

- python/taichi/lang/transformer.py
- tests/python/test_grouped.py
- tests/python/test_syntax_errors.py
This is a special case that we should let pass. A more systematic solution is to defer the checking to the stage when the AST generating script is executed.
Related issue = #https://github.com/taichi-dev/taichi_elements/issues/13
> [Lang] Fix `ti.static(ti.grouped(ti.ndrange(...)))` syntax checker false positive

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/codegen/codegen_metal.cpp
- taichi/ir/ir.cpp
- taichi/ir/statements.h
- tests/python/test_bitmasked.py
Also added `KernelAttributes::debug_string()` method, making the PR a bit noisy. These are the files that deserve attention..
* `taichi/backends/metal/shaders/runtime_kernels.metal.h`
* `taichi/codegen/codegen_metal.cpp`
Note that I just put a limit of #threads to be `1024 x 1024`. Does this makes sense (i.e. is there a fancier way to decide this limit)?
---
I used `taichi_sparse.py` as a rough benchmark. The FPS went from `35` to `40`. I guess that's because each thread now only handles a few child slots. (Previously each thread had to handle all the slots.)
Related issue = #678 
> [metal] Use grid-stride loop to implement `listgen` kernels

- python/taichi/main.py
- taichi/common/serialization.h
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- tests/cpp/test_stmt_field_manager.cpp
> [IR] Statement Field Manager

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- tests/python/test_bitmasked.py
FYI, without this change, the added test could actually fail on Metal...
Related issue = #593 
> [metal] Fix bug in `listgen` where it goes beyond `ListManager`'s capacity

- examples/nbody_oscillator.py
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/shaders/random.glsl.h
- taichi/codegen/codegen_opengl.cpp
- tests/python/test_random.py
So that `examples/sdf_renderer.py` works.
Related issue = #492 
> [opengl] random use different seed in each launch

- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_context.h
- taichi/backends/cuda/runtime.cpp
- taichi/jit/jit_arch_cuda.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/system/unified_allocator.cpp
Related issue = #518 
- Removed `cuda_context` global var 
- Added comments on why `remove_useless_libdevice_functions` is needed
(`CUDAContext::get_instance().get_guard()` sometimes leads to deadlocks on CUDA - that's why they are commented for now until we figure out why.)
This PR should close #518 once merged.
> [refactor] CUDA-related infrastructure

- taichi/codegen/codegen_metal.cpp
`struct_for` also uses grid-loop stride now.
`taichi_sparse.py` went up by about another `4-5` FPS.
---
You can probably tell how similar this change is to https://github.com/taichi-dev/taichi/blob/40bf0c0a84b5ea77f483e11250d399c4fd72f50e/taichi/backends/metal/shaders/runtime_kernels.metal.h#L68-L98
I cannot think of a very good way to unify these for now. Since most of the duplicate code are procedures, it's difficult to wrap them into functions. We could use macros to solve this, although I'm not a very big fan of macros..
Related issue = #678 
> [metal] Skip `listgen` for leaf Snode

- docs/contributor_guide.rst
- taichi/codegen/codegen_llvm.cpp
- taichi/jit/jit_arch_cpu.cpp
- taichi/jit/jit_arch_cuda.cpp
- taichi/jit/jit_module.h
- taichi/jit/jit_session.h
- tests/python/test_struct_for.py
> [LLVM] Fix LLVM struct-for codegen crashing due to extra return #704

- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/struct/struct_llvm.cpp
- tests/cpp/test_same_statements.cpp
> [refactor] SNode now uses unique_ptr instead of shared_ptr for clearer children ownership

- taichi/backends/metal/constants.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/helpers.metal.h
- taichi/codegen/codegen_metal.cpp
- taichi/struct/struct_metal.cpp
- taichi/struct/struct_metal.h
Related issue = #396 
This has caused quite some headaches, so I'll document what I've found with Metal.
---
First of all, Metal's memory order seems, if not fundamentally broken, very restricted across threads, making it impossible to implement a SpinLock with atomics.
In the beginning, I tried to follow LLVM's rand state design, with 4 seeds guarded by 1 lock:
https://github.com/taichi-dev/taichi/blob/811f468a8bde4911815f540cbd9ba84e9e0578e8/taichi/runtime/llvm/locked_task.h#L19
However, it turned out that after a thread releases a lock (setting atomic to `0` again), it didn't get broadcasted to the rest of the threads. 
```cpp
// a Metal thread
// 1
while (compare_exchange_swap(&lock, /*desired=*/1, …
```
> [Metal] Support `ti.random()` on Metal

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/vector_split.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/656#issuecomment-610061036
With such an assertion, `LocalAddress` cannot have a default constructor, so other places like `LaneAttribute` should handle the case that `T = LocalAddress` doesn't have a default constructor.
Also continues #718 as I missed some functions in that PR.
> [ir] Add assertions of `Alloca`s in constructors of LocalAddress and LocalStoreStmt

- python/taichi/lang/transformer.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_metal.cpp
- taichi/codegen/codegen_opengl.cpp
- taichi/inc/statements.inc.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/make_adjoint.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/simplify.cpp
- tests/python/test_continue.py
- tests/python/test_syntax_errors.py
> [Lang] Support `continue` on all backends

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/codegen/codegen_opengl.cpp
I moved bunch of code around to get rid of `no_gc` in `codegen_opengl.cpp`. Now `GLSLLauncher` will keep all the `std::unique_ptr<CompiledProgram>`.
* `CompiledKernel` is now completely hidden inside `opengl_api.cpp`. We can also get rid of `CompiledGLSL` now.
* We have to expose the `CompileddProgram` so that `GSLSLauncher` knows about it.
* By using PIMPL on `CompiledProgram`, we don't have to expose `CompiledKernel` to the public.
I don't really have access to OpenGL, but I managed to make this compile with `TI_WITH_OPENGL` **enabled** (Had to mock out some portion of the code to do so). Could you fetch this to your local environment and run the tests (most likely they are broken)? Could you either tell me where the problem is, or even better, just fix them :)? Really appreciated! …
> [opengl] [refactor] Remove the global `no_gc` in `opengl_codegen.cpp`

- taichi/analysis/detect_for_with_break.cpp
- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/visitors.h
> [ir] [refactor] BasicStmtVisitor includes Frontend blocks

- taichi/codegen/codegen_metal.cpp
- taichi/struct/struct_metal.cpp
- taichi/struct/struct_metal.h
We will have `Headers`, `Structs`, `ConstantsDefs`, `KernelFuncs` and `Kernels` sections. Each
section has its own `LineAppender` instance. This offers much more flexibility.
For example, by defining all constants at the global scope in `ConstantsDef` section, we can work around #729. `KernelFuncs` means we generate a regular function for each offloaded task, then call that function from the Metal kernel/shader. This way we can reliably transform the top-level `continue`  as a simple `return` stmt (See #708).
---
@yuanming-hu  I'm not sending this for you to review, because it's all internal Metal refactoring without any new feature. I guess you are familiar with this multiple-section approach, as it's used in the legacy backends ;)
Related issue = #722 #729 
[[Click here for the format …
> [metal] Refactor the codegen to have multiple code sections

- taichi/transforms/offload.cpp
- tests/python/test_continue.py
Related issue = #729 
The logic is still a bit messy here...
> [ir] Fix out-of-scope operands during offloading

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/codegen/codegen_metal.cpp
- taichi/codegen/codegen_metal.h
- taichi/program/program.cpp
As promised.. :) Again, i don't think there's any new feature..
Related issue = #722 
> [metal][refactor] Use `compile_to_offloads()` in codegen

- taichi/gui/cocoa.cpp
- taichi/ir/visitors.h
Thanks to @archibate 's #741 , I discovered that `ti.GUI.SPACE` wasn't supported before..
> [GUI][Metal] Support SPACE key

- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
Related issue = #745 
@matyklug18 I'm not sure if this solves your issue since I can't reproduce that on my end. Could you have a try and let us know if everything is fixed? Thanks!
> [refactor] Remove `vprintf` in `runtime/llvm/runtime.cpp` to avoid name conflicts

- python/taichi/misc/gui.py
Related issue = https://github.com/taichi-dev/taichi_elements/pull/23
> [GUI] Fix blinking particles and random segmentation faults during ti.GUI.circles

- examples/regression.py
Otherwise it will raise AttributeError: module 'taichi' has no attribute 'pow'
> Replace ti.pow() by ** in examples/regression.py

- taichi/program/program.cpp
- taichi/runtime/llvm/runtime.cpp
Related issue = #https://github.com/taichi-dev/taichi_elements/pull/23
> [CUDA] Limit memory allocation chunk size to 128 MB

- python/taichi/lang/__init__.py
- python/taichi/main.py
> [cli] ti test --arch argument not work, fix it

- python/build.py
- taichi/analysis/has_load_or_atomic.cpp
- taichi/analysis/has_store_or_atomic.cpp
- taichi/analysis/last_store_or_atomic.cpp
- taichi/ir/ir.h
- taichi/transforms/simplify.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/656#issuecomment-612299909
> [refactor] [opt] Move LocalLoadSearcher and 2 other classes to irpass::analysis

- README.md
- docs/contributor_guide.rst
- taichi/codegen/codegen_llvm.cpp
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/program/program.cpp
- taichi/runtime/llvm/node_bitmasked.h
- taichi/transforms/offload.cpp
- tests/python/test_bitmasked.py
@kazimuth
Related issue = #778 
> [Bug] Insert gc task only for `pointer` and `dynamic` SNode

- cmake/TaichiCore.cmake
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/jit/jit_arch_cpu.cpp
- taichi/llvm/llvm_codegen_utils.h
- taichi/llvm/llvm_context.cpp
This PR is the first stage for LLVM 10.0. This PR makes taichi buildable with LLVM 10.0, but still keep all things about LLVM 8.0. The macro `LLVM_VERSION_MAJOR`, rather than `TI_LLVM_VERSION` since the former is more standard.
Everything should works with LLVM 10.0, and the next step is upgrade the `OrcJIT` part to the newer version in LLVM, and deprecate LLVM 8.0 support, but those part will be another PR.
Related issue = #655
> [LLVM] Upgrade to LLVM 10.0, and keep backwards compatibility with LLVM 8.0.

- docs/contributor_guide.rst
@k-ye I'm stealing a few great articles from Google so that we don't have to re-discover on our own these battle-tested code health practices. You are probably already very familiar with these - do you think of adopting these tips in the Taichi community?
> [doc] Include a few links to Google Code Health articles in contributor guidelines

- README.md
- taichi/backends/metal/kernel_manager.cpp
- taichi/codegen/codegen_metal.cpp
- tests/python/test_loops.py
With this change, we no longer need  a sync to figure out the number of threads to launch.
Related issue = #722 
Might be easier to see what's going on with an example... The following snippet is part of the output from https://github.com/taichi-dev/taichi/blob/f0d6bd70f90f51cf2aa39cb2ed716e8a7acf0f11/tests/python/test_loops.py#L143-L155
```cpp
void mtl_k0000_test_c4_0_1_func(
device byte* root_addr,
device byte* global_tmps_addr,
device byte* args_addr,
device byte* runtime_addr,
const int linear_loop_idx_) {
device Runtime *runtime_ = reinterpret_cast<device Runtime *>(runtime_addr);
mtl_k0000_test_c4_0_args args_ctx_(args_addr);
device RandState* rand_state_ = reinterpret_cast<device RandState*>(runtime_->rand_seeds …
```
> [metal] Implement range_for using grid stride loop

- taichi/common/dict.h
- taichi/common/interface.h
- taichi/common/task.h
- taichi/common/util.h
- taichi/math/scalar.h
- taichi/python/export_math.cpp
- taichi/system/profiler.h
- taichi/transforms/type_check.cpp
- taichi/util/image_buffer.cpp
No rush on reviewing this - just some random modifications while trying to fix #793 
> [misc] Improve type checking error messages

- taichi/analysis/verify.cpp
- taichi/transforms/ir_printer.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/788#issuecomment-614320136 https://github.com/taichi-dev/taichi/pull/788#issuecomment-613739361
Also fixes a bug introduced in #788 when calling `irpass::print`: we can't print `WhileControlStmt::mask->name()` if `WhileControlStmt::mask == nullptr`.
> [ir] Add checks for `loop_var`s and print names for loops

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- tests/cpp/test_parallel_executor.cpp
> [async] Add parallel task executor 

- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/demote_dense_struct_fors.cpp
- taichi/transforms/fix_block_parents.cpp
- taichi/transforms/offload.cpp
Fix #739.
All hotfixes are removed.
> [IR] Fix illegal intermediate IRs

- docs/contributor_guide.rst
- docs/internal.rst
@archibate I uploaded the PDFs of the code review articles, in case you don't have access to Google. I highly recommend spending some time reading these carefully: https://github.com/taichi-dev/taichi/blob/9366443224495ced352a5bddcf3d17b042eec105/docs/contributor_guide.rst#making-good-pull-requests
> [doc] Add Google code review article PDFs

- examples/euler.py
Here's a compressible Euler equation solver! Its just a simple finite volume scheme with a HLLC Riemann solver. It already creates some nice images, but needs to be polished up a bit. I'll work on that tomorrow night :)
Related issue = #776 
> [example] Add an Euler equation solver

- README.md
Related issue = #740 
[[**Preview**]](https://github.com/yuanming-hu/taichi/blob/readme2/README.md)
> [misc] Update `README.md`

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/offload.cpp
Related issue = #656 #729 
**Test case**: `test_local_atomics.py::test_implicit_local_atomic_or`
**before**:
```
kernel {
$0 = offloaded  {
<i32*x1> $1 = global tmp var (offset = 0 B)
<i32 x1> $2 = const [0]
<i32*x1> $3 : global store [$1 <- $2]
<i32*x1> $4 = global tmp var (offset = 4 B)
<i32*x1> $5 : global store [$4 <- $2]
<i32*x1> $6 = global tmp var (offset = 0 B)
<i32*x1> $7 = global tmp var (offset = 4 B)
<i32 x1> $8 = global load $7
<i32*x1> $9 : global store [$6 <- $8]
}
$10 = offloaded range_for(0, 10) block_dim=adaptive {
<i32 x1> $11 = const [2]
<i32 x1> $12 = loop index 0
<i32 x1> $13 = pow $11 $12
<i32*x1> $14 = global tmp var (offset = 0 B)
<i32 x1> $15 = atomic bit_or($14, $13)
}
$16 = offloaded  {
<i32*x1> $17 = global tmp var (offset = 0 B)
<i32 x1> $18 = global load $17 …
```
> [opt] Avoid storing constants across offloaded tasks

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/offload.cpp
> [ir] Fix compilation crash when offloading LocalStoreStmt and AtomicOpStmt

- examples/mpm128.py
Now it acts same as mpm99 if we don't press any key...
> [example] mpm128 gravity now init as [0, -1], become [0, 0] once key up

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/ir/snode.h
- taichi/llvm/llvm_codegen_utils.h
- taichi/llvm/llvm_context.h
- taichi/program/program.cpp
- taichi/struct/struct.h
- taichi/struct/struct_llvm.cpp
- taichi/struct/struct_llvm.h
> [refactor] Remove `SNodeAttr` and decouple `SNode` from LLVM

- taichi/transforms/alg_simp.cpp
I put it in `alg_simp.cpp` since there seem to be no better places.
I thought I found
```
<i32 x1> $5 = const [1]
$6 : while control nullptr, $5
```
in some files like `test_for_break.py`, but I can't find such IRs now... This PR doesn't reduce the number of statements for any tests in `test_for_break.py`.
> [opt] Eliminate WhileControlStmt with non-zero const conditions

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
I manually tested `taichi_sparse` and `sdf_render`, and found no performance difference..
Related issue = #722 
> [metal] Increment by thread grid size for the grid-strip loops

- examples/cornell_box.py
- examples/renderer_utils.py
Sorry I didn't make it super authentic, because I didn't want to bother computing the norms for ray-aabb hits...  I think this makes [a cool demo](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-837-computer-graphics-fall-2012/), but the value it adds on top of `sdf_renderer.py` is somewhat limited..
---
I'll try adding importance sampling to de-noise and adjust the weight.
> [Example] Add a cornell box scene

- tests/cpp/test_simplify.cpp
This is because `irpass::simplify(block.get());` won't lower `linearized` when `advanced_optimization` is `false`.
> [test] Fix test when `advanced_optimization == false`

- appveyor.yml
- examples/cornell_box.py
- examples/euler.py
- examples/fractal.py
- examples/game_of_life.py
- examples/laplace.py
- examples/mpm128.py
- examples/mpm88.py
- examples/mpm99.py
- examples/mpm_lagrangian_forces.py
- examples/nbody_oscillator.py
- examples/pbf2d.py
- examples/sdf_renderer.py
- examples/stable_fluid.py
- python/taichi/lang/__init__.py
> [Misc] enhance ti.init for ti.gpu

- examples/mpm99.py
- taichi/codegen/codegen_llvm.cpp
- taichi/jit/jit_session.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/program/program.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/whole_kernel_cse.cpp
LLVM context is not thread-safe. We are doing this for parallel compilation.
> [async] Each JIT thread now has its own LLVM context

- taichi/transforms/optimize_local_variable.cpp
- tests/python/test_optimization.py
Fix #847.
If we want to do store-forwarding to local loads inside loops, we should pass the last local store into the loop, rather than use an empty `AllocaOptimize loop`.
> [Bug] [Opt] Fix a bug in local variable optimization

- taichi/transforms/simplify.cpp
The geometric mean of optimization factor: 1.0683373262848908 -> 1.0746597390735222
Tests with significant optimization (> 1.5):
```
test_ad_if__test_ad_if : 1.5348837209302326
test_ad_if__test_ad_if_mutable : 2.0485436893203883
test_ad_if__test_ad_if_parallel : 1.9245283018867925
test_ad_if__test_ad_if_parallel_complex : 1.625
test_basics__test_if_global_load : 1.5441176470588236
test_continue__test_kernel_continue : 1.605263157894737
test_continue__test_unconditional_continue : 1.5106382978723405
```
Tests that become worse in the sense of the number of statements (< 0.85):
```
test_ndrange__test_static_grouped_static : 0.8333333333333334
test_struct_for__test_singleton : 0.8333333333333334
test_tensor_dimensionality__test_dimensionality : 0.7862595419847328 …
```
> [opt] Improve optimization for OffsetAndExtractBitsStmt

- taichi/codegen/codegen.cpp
- taichi/program/compile_config.cpp
- taichi/util/statistics.cpp
Related PR = #851
The geometric mean of optimization factor on kernels: 1.1146766978072276
Tests with significant optimization (> 1.5):
```
test_ad_basics__test_frac : 1.558139534883721
test_ad_basics__test_minmax : 1.5142857142857142
test_ad_basics__test_poly : 1.5714285714285714
test_ad_basics__test_unary : 1.5454545454545454
test_ad_if__test_ad_if : 1.8214285714285714
test_ad_if__test_ad_if_mutable : 2.5671641791044775
test_ad_if__test_ad_if_parallel : 2.357142857142857
test_ad_if__test_ad_if_parallel_complex : 1.82
test_ad_offload__test_offload_order : 1.532258064516129
test_atomic__test_atomic_sub_expr_evaled : 1.6470588235294117
test_basics__test_if_global_load : 1.6428571428571428
test_basics__test_while_global_load : 1.8666666666666667
test_continue__test_kernel_continue : …
```
> [misc] Split accessor and other kernels in statistics

- taichi/analysis/gather_used_atomics.cpp
- taichi/ir/ir.h
- taichi/transforms/optimize_local_variable.cpp
- tests/python/test_optimization.py
`gather_used_atomics` can be utilized in #857.
Benchmark:
**before**:
**after: nothing changed.**
**after adding a test**...:
> [opt] Eliminate useless local stores and atomics

- python/taichi/misc/image.py
- taichi/util/image_io.cpp
- tests/python/test_image_io.py
> [misc] Fix imread not reading properly when image is not equal in height and width

- python/taichi/lang/impl.py
By looking at `reset()`, it seems that using a mutable default is not intended.
But I might be wrong since I'm not yet a taichi user.
See: https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html about the antipattern.
> [misc] Avoid mutable defaults in `PyTaichi`

- appveyor.yml
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
Related issue = #664
As you mentioned in https://github.com/taichi-dev/taichi/pull/843#issuecomment-617544821.
We're on the edge of v0.6!
In this PR, I do `initialize_opengl` in `with_opengl` so that we can detect if driver available, and compute shaders are supported.
>  [opengl] Detect driver existance in with_opengl()

- cmake/TaichiCore.cmake
- python/taichi/lang/__init__.py
- python/taichi/main.py
- taichi/program/program.cpp
Related issue = #765
Sol. 1 in https://github.com/taichi-dev/taichi/issues/765#issuecomment-612942650
> [cuda] [test] Add TI_DEVICE_MEMORY_GB and TI_DEVICE_MEMORY_FRACTION environment variable

- python/taichi/lang/__init__.py
Related PR id = #769
I made an error in #769: there is no `ti.cfg.gdb_trigger` at all!
Now the problem is where should `gdb_trigger` be, `CompileConfig` or `CoreState`?
The first seems only accessible only by compiler parts. So `get_current_program().config` stand for only compiler configuations so it's not found anywhere in `logger.cpp`?
> [misc] Fix `ti.cfg.gdb_trigger` not found

- taichi/transforms/alg_simp.cpp
Thanks for @archibate 's idea!
Related PR = https://github.com/taichi-dev/taichi/pull/839#issuecomment-619482117
**Before**:
**After**:
WDYT if we optimize a kernel to 0 statements... I set it to 1 statement to avoid division by 0 here. But it's causing too much "improvement" to the geometric mean: nearly 1.02x.
> [opt] Eliminate assertions with non-zero const conditions

- taichi/backends/opengl/opengl_api.cpp
> [opengl] Tolerate all errors in with_opengl()

- taichi/program/kernel.cpp
- tests/python/test_debug.py
The reason is the 8-byte result buffer for the reader is overwritten by the error code of the runtime error checker. This is a temporary fix, at the cost that the access out-of-bounds will not be detected for SNode reader/writers... We should revisit this later for a more systematic solution. Maybe we need multiple buffers...
(Feel free to merge if you approve and CI passes)
Related issue = #886 
> [Bug] Fix CPU SNode reader in debug mode

- examples/cornell_box.py
I added MIS to the cornell box example so as to denoise the scene. Below are the comparisons, with each running for 1000 iterations.
* Reference (img variance=0.1455)
* New code with MIS (img variance=0.1094)
Here's a result after running 15K iterations:
---
The MIS is done by doing two samples per intersection. Note that this is carried out only when the ray hits a lambertian material (i.e. the boudaries)
* One ray that shoots toward a random point on the light source (`sample_area_light`)
* One ray that samples from a cosine hemisphere distribution (`sample_brdf`).
This is basically what the PBR book Chapter 15 has described. I didn't look much into the special handling of sampler on specular materials (delta functions), but the result looks fine..
A few useful references I've found:
* …
> [Example] Add Multiple Importance Sampling to the cornell box scene

- taichi/ir/statements.h
- tests/cpp/test_alg_simp.cpp
Related issue = #656 (maybe not directly related)
This PR sets `has_global_side_effect` to `false` for `LoopIndexStmt, GlobalTemporaryStmt, StackAllocaStmt, StackLoadTopStmt, StackLoadTopAdjStmt`.
Benchmark:
**Before**:
**After** (Notice that this also affect the numbers when `advanced_optimization = false`!):
> [opt] Set `has_global_side_effect` to `false` for some statements

- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/lower_access.cpp
- taichi/transforms/statement_replace.cpp
> [ir][refactor] Remove the global `current_block`

- taichi/inc/statements.inc.h
- taichi/ir/expr.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
I added `AtomicOpExpression` back in Jan, where we wanted to make `ti.atomic_*()` return the old value. Now I think it's a good time to merge `FrontendAtomicStmt` into `AtomicOpExpression`.
Related issue = #689 , #332 
> [ir] Deprecate `FrontendAtomicStmt`

- examples/mgpcg_advanced.py
- misc/test_async_weaken_access.py
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/flag_access.cpp
> [async] Avoid unnecessary list generations and activations

- taichi/ir/frontend.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
In this PR, I just moved `FrontendAllocaStmt` to a new file `frontend_ir.h`. If this looks OK, I will move all the other `Frontend*Stmt` (maybe `*Expression` as well ?)
> [ir][refactor] First step to move Frontend IR to its own file

- taichi/analysis/detect_fors_with_break.cpp
- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/expr.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/program/program.cpp
- taichi/transforms/re_id.cpp
- taichi/transforms/reverse_segments.cpp
This is a follow up of #914 . We move all `Frontend*Stmt` to `frontend_ir.h`. (Expressions will be handled separately)
> [ir][refactor] Move all frontend stmts to `frontend_ir.h`

- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
Legacy constructs:
* `If`
* `For`
* `While`
> [ir][refactor] Move legacy frontend constructs to frontend.h/cpp

- docs/dev_install.rst
- docs/index.rst
So that they install `clang-8` in `/usr/local/bin` instead of overwriting `/usr/bin` which breaks deps like `kdesktop`.
Related issue = #866
> [doc] Tell Arch users to build clang-8 from scratch

- .gitmodules
It's reported that taichi no longer works on their system since they don't have glibc 2.27. I took a look and realized the dependency was introduced by GLFW. So I have to patch GLFW to remove the dependency: https://github.com/taichi-dev/glfw/commit/8bc966bbae4967a008252f1ac9b625e4dc77ad64
> [OpenGL] Remove GLFW dependency on glibc 2.27 and improve portability

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
This is probably mentioned somewhere, but I think we should add a new `rets` in `Context` as well?
https://github.com/taichi-dev/taichi/blob/bbddaa10def6e2e9e566ec8f665daf480aab652e/taichi/runtime/llvm/context.h#L15-L18
Once we do that, OpenGL/Metal can copy the return values back to `Context::rets`, so that we don't have to overuse `Context::args` for holding return values:
https://github.com/taichi-dev/taichi/blob/bbddaa10def6e2e9e566ec8f665daf480aab652e/taichi/program/program.cpp#L500
Related issue = #909 
> [metal] Support `KernelReturnStmt`

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/type_check.cpp
Also removed some helpers that are unused now:
* `mark_arg_return_value()`
* `Kernel::Arg::is_return_value`
Related issue = #909 
> [ir][refactor] Deprecate `ArgStoreStmt` (both frontend and CHI)

- benchmarks/mpm2d.py
- docs/syntax.rst
- examples/mpm128.py
- examples/mpm88.py
- examples/mpm99.py
- examples/mpm_lagrangian_forces.py
- examples/particle_renderer.py
- examples/regression.py
- examples/waterwave.py
- misc/benchmark_parallel_compilation.py
- misc/test_poly_timed.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- tests/python/test_ad_atomic.py
- tests/python/test_ad_basics.py
- tests/python/test_mpm88.py
Related issue = #833 
People tend to think `sqr` means **square root** instead of **square** (https://forum.taichi.graphics/t/what-the-result-of-ti-sqr-x-x-is-a-vector-if-any-element-of-x-is-negative/125/3).
Fortunately, we have `** 2` now thanks to @archibate...
> [Lang] ti.sqr(x) is now deprecated: please use x ** 2 instead

- docs/odop.rst
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/python/export_lang.cpp
- taichi/struct/struct.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_complex_kernels.py
- tests/python/test_offset.py
- tests/python/test_oop.py
> [Lang][IR][refactor] Refactor SNode and support coordinate offsets 

- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/visitors.h
Looks like `BasicStmtVisitor::current_struct_for` is never used.
> [ir] Remove BasicStmtVisitor::current_struct_for

- taichi/backends/metal/api.h
- taichi/backends/metal/kernel_manager.cpp
This allows us to trace the system behavior more clearly. E.g.
Related issue = #935 
> [metal] Set labels on the command buffer/encoder

- docs/hello.rst
- docs/layout.rst
- docs/overview.rst
- docs/syntax.rst
- examples/fractal.py
I will try to update the Chinese version of `hello.rst` as well to learn about the Chinese translation process. (I'm setting up environment according to https://github.com/taichi-dev/taichi-docs-zh-cn/blob/master/README.md.)
> [doc] Improve `hello.rst`

- docs/syntax_sugars.rst
Change `assignement` to `assignment` in [docs/syntax_sugars.rst](https://github.com/taichi-dev/taichi/blob/master/docs/syntax_sugars.rst)
No related issue;
> [Doc] Fix in docs/syntax_sugars.po

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/ir/ir.h
- taichi/transforms/compile_to_offloads.cpp
> [opengl] Use `compile_to_offloads` for IR lowering

- taichi/ir/ir.cpp
- taichi/transforms/statement_replace.cpp
I realized that what caused #953 to fail is
https://github.com/taichi-dev/taichi/blob/e0ef399b2c2f053918e1013fea9850022c96bced/taichi/transforms/statement_replace.cpp#L27
calling `get_ir_root()`, not the exceptions...
> [ir][refactor] Avoid throwing exception in `replace_statements_with`

- taichi/backends/cuda/cuda_driver.cpp
- taichi/backends/metal/api.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/core/logging.cpp
- taichi/util/environ_config.h
Related issue = https://github.com/taichi-dev/taichi/issues/958#issuecomment-627432722
> [opengl] add TI_WITH_OPENGL env var to disable OpenGL

- docs/differentiable_programming.rst
- docs/external.rst
- docs/faq.rst
- docs/global_settings.rst
- docs/internal.rst
- docs/meta.rst
- docs/snode.rst
- docs/syntax.rst
- docs/type.rst
- Some reordering/reorganization. E.g. `Why Python frontend` moved to internal design
- more details on template metaprogramming in a later PR
Everyone is welcome to take a look :-)
> [doc] Update syntax.rst and related sections

- taichi/program/program.cpp
> [cuda] Improve kernel return value performance when unified memory is available

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/struct_metal.cpp
> [metal] Skip allocating Runtime::ListManager if no sparse SNode is used

- taichi/backends/metal/shaders/helpers.metal.h
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/runtime/llvm/runtime.cpp
> [Bug] [opengl] [llvm] [metal] Fix floordiv overflow when `lhs * rhs` is large

- README.md
Related issue = as I mentioned in WeChat..
> [misc] Add a link to taichi_elements in README.md

- docs/internal.rst
- misc/listgen_demo.py
Related issue = #709 #941 #986 
> [doc] Document list generation

- taichi/backends/opengl/codegen_opengl.cpp
> [opengl] Fix unwanted "used.int64_t = true" in KernelReturnStmt

- taichi/gui/cocoa.cpp
There was a conflict in class naming in Cocoa, let's rename our view class to `TaichiGuiView`.
Related issue = #998
> [Mac] [GUI] Fix bug due to View class name conflict

- docs/conf.py
- docs/differentiable_programming.rst
- docs/faq.rst
- docs/global_settings.rst
- docs/gui.rst
- docs/index.rst
- docs/install.rst
- docs/meta.rst
- docs/performance.rst
- docs/snode.rst
- docs/vector.rst
> [doc] Update install.rst and Misc.

- CMakeLists.txt
- cmake/TaichiCXXFlags.cmake
Related issue = #1017 
I'll just merge this after CI passes.
> [misc] Remove debug info in release mode

- taichi/backends/metal/api.h
- taichi/common/trait.h
- taichi/math/arithmetic.h
As you can see, this can be helpful for implementing the fallback branch of an `if constexpr`
WANT_LGTM=any
> [refactor] Add an always_false class trait

- taichi/ir/transforms.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/offload.cpp
Now that all backends are using the static global tmp buffer size
https://github.com/taichi-dev/taichi/blob/8efba16602bc8fe1e2700307dca3130899d1629d/taichi/inc/constants.h#L9
We can remove the unused `OffloadedResult` now.
WANT_LGTM=any
> [refactor] [ir] Deprecate the unused OffloadedResult

- docs/dev_install.rst
Tell (dev) user to explicitly assign clang as compiler, since in Linux the default is usually gcc.
use $(nproc) instead of 8 when make, safer for machines with fewer processors.
> [Doc] Improve a bit for developer build guidance

- python/taichi/lang/impl.py
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir.h
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/vector_split.cpp
- tests/python/test_print.py
Related issue = #923
<del>- [ ] print string + expr (iapr)</del>
<del>- [ ] print vector&matrix (iapr)</del>
note: iapr = in another pull request, no more note for this on core devs.
[[Click to format]](http://kun.csail.mit.edu:31415/1029)
> [Lang][ir] "print" now support multiple scalar arguments

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/struct_metal.cpp
- taichi/backends/metal/struct_metal.h
This is to fix https://github.com/taichi-dev/taichi/issues/975#issuecomment-628665115, where we didn't allocate the additional memory, but still wrote to it...
Related issue = #975 
> [metal] Initialize root ListManager's data only if there is sparse SNode

- docs/snode.rst
No related issue;
**alone** to **along** in `docs/snode.rst`:
```markdown
the size of tensor alone that axis
=>
the size of tensor along that axis
```
> [Doc] Fix typo in snode.rst

- taichi/transforms/offload.cpp
"One less global variable is a bit less evil in the world." -- *Nobody*  233 B.C.
As part of the refactor, I also:
* Reordered a few static function args so that they match the corresponding Constructor's order
* Added `const &` to a few `stmt_to_offloaded` maps.
WANT_LGTM = any
> [refactor] Remove the global begin_stmt and end_stmt

- docs/dev_install.rst
- docs/legacy_installation.rst
- As discussed in https://github.com/taichi-dev/taichi-docs-zh-cn/pull/58, it's probably better and more formal to use `build from source` across the documentation. (see [example](https://www.tensorflow.org/install/source) )
> [doc] Use build from source than scratch

- examples/cornell_box.py
- python/taichi/lang/matrix.py
So that we don't have to convert `np.array` to `list` first.. See the changes in the cornell box example.
Related issue = #1008 
> [Lang] Support passing numpy arrays to ti.Matrix constructor

- .github/workflows/persubmit.yml
Since it always return `check` after `[skip ci] enforce code format`, let's not making the previous one to show `cross` to get the real CI result.
> [workflow] Not to run code format check when @taichi-gardener is on

- python/taichi/lang/kernel.py
- python/taichi/lang/transformer.py
- tests/python/test_kernel_templates.py
This PR implements support for template arguments in ```ti.func```s. This just required skipping python AST transform for arguments type-hinted with ```ti.template()```. I also slightly refactored ASTTransformer by removing the ```is_classfunc``` argument.
The test I added doesn't work atm. For some reason it runs into a python sytnax error. This syntax error does not occur when the test is run as stand alone script. So I think its related some weird nested function syntax. If you have another idea for the test to get around that please let me know!
Related issue = #1042 
> [Lang] Support template arguments for ti.func

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/features.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
- tests/python/test_dynamic.py
- tests/python/test_struct_for_dynamic.py
This is an experimental support for `dynamic` SNode on Metal.
The PR is surprisingly small. Here, `dynamic` is simply `dense` + `8 bytes` to hold the the number of elements currently in it. I managed to port some of the tests I've found.
Other things I can think of:
* Add more tests
* Finer-grained `ti.extensions`. I think instead of `ti.extensions.sparse`, we need one tag for each sparse data types now.
* Use `dynamic` in `pbf2d.py`. (I expect this could hurt the performance because the sparsity runtime overhead could easily become dominant for this small example. Still, it at least tests the functionality.)
* I tried to port `particles_renderer.py`, but there were two problems.
1. Its predefined size is way too big for Metal, due to the lack of memory allocation.
1. It also uses …
> [Metal] [sparse] Experimental support for dynamic SNode

- taichi/backends/metal/codegen_metal.cpp
This was added back in #729 , because constants were optimized away across kernels. As a workaround, I defined all the constants at the namespace scope, which worked thanks to SSA.
However, this approach blocked me from merging multiple Metal kernels into one source code file, which was useful for profiling. So I'd like to revert this workaround now..
Related issue =  #729
> [metal] Remove global constant def section

- taichi/ir/ir.cpp
- taichi/ir/transforms.h
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/transforms/alg_simp.cpp
Related issue = #1059 #656 #505
The return value of `alg_simp` is "Is the IR modified in this pass?" and will be utilized in `full_simplify`.
> [Opt] [refactor] Avoid throwing exceptions in alg_simp and let it support more types

- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/transforms/alg_simp.cpp
Related issue = #944
This PR contains: 
- `a * 2 -> a + a, 2 * a -> a + a` (for all types, cast to the original result type)
- `a / const -> a * (1 / const)` (floating point only & fast_math only -- is this necessary?)
- `a ** 1 -> a` (for all types)
- `a ** 0 -> 1` (for all types & fast_math only, cast to the original result type)
- `a ** 2 -> a * a` (for all types, cast to the original result type)
Benchmark:
> [Opt] Add strength reduction optimizations

- taichi/runtime/llvm/internal_function.h
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_internal_func.py
> [llvm] [sparse] Fix a memory leak bug in GC's free list on CPU

- taichi/backends/cuda/codegen_cuda.cpp
- tests/python/test_print.py
> [bug] [test] Fix CUDA segmentation fault when printing more than 32 entries

- taichi/ir/ir.cpp
- taichi/transforms/lower_ast.cpp
Related issue = close #1071
Seems `replace_usage = true` not working when `new_statements.size() == 0`:
https://github.com/taichi-dev/taichi/blob/c193e4b431d52ffa4e875940ece589d5be9599f0/taichi/ir/ir.cpp#L760-L761
... where `new_statements.back() == nullptr`.
> [bug] [ir] Fix Block::replace_with segment faults when stmts.size() == 0

- taichi/runtime/llvm/internal_functions.h
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_internal_func.py
`call_internal` doesn't work on CUDA at this moment.
Related issue = #1076
> [CUDA] [test] Improve portability and remove GC tests on CUDA for now 

- taichi/gui/gui.h
Before this fix:
```
[20:54:21] vms=5940.1MB, rss=263.8MB
[20:54:21] vms=6102.1MB, rss=414.4MB
[20:54:22] vms=6422.1MB, rss=647.7MB
[20:54:23] vms=6422.1MB, rss=717.3MB
[20:54:24] vms=7062.1MB, rss=1106.3MB
[20:54:24] vms=7062.1MB, rss=1173.1MB
[20:54:25] vms=7060.1MB, rss=1239.8MB
```
With this fix:
```
[20:53:00] vms=5703.1MB, rss=148.7MB
[20:53:00] vms=5703.1MB, rss=149.8MB
[20:53:01] vms=5703.1MB, rss=153.1MB
[20:53:02] vms=5703.1MB, rss=153.1MB
[20:53:02] vms=5704.2MB, rss=154.1MB
[20:53:03] vms=5705.2MB, rss=154.8MB
[20:53:03] vms=5705.2MB, rss=154.8MB
[20:53:04] vms=5830.1MB, rss=158.5MB
[20:53:05] vms=5828.0MB, rss=158.4MB
[20:53:05] vms=5828.0MB, rss=158.4MB
[20:53:06] vms=5828.0MB, rss=158.4MB
```
Related issue = Fixes #1108 (if any)
[[Click here for the format …
> [gui] Fix memory leak as circles were not cleared

- taichi/lang_util.h
- taichi/transforms/alg_simp.cpp
Also simplifies `alg_simp.cpp`.
Benchmark (number of statements of unit tests): nothing changed.
Benchmark (running time):
```
C:\Users\xmk\Desktop\taichi>ti regression
[Taichi] <dev mode>, supported archs: [cpu only], commit f3559aab, python 3.7.
4
*******************************************
**     Taichi Programming Language       **
*******************************************
x64::sscal________________________________________________
time_avg                      ?[35m1.3e+02?[39m -> ?[36m1.3e+02 ?[31m    +0.4%
?[39m
x64::saxpy________________________________________________
time_avg                      ?[35m1.9e+02?[39m -> ?[36m1.9e+02 ?[31m    +0.0%
?[39m
x64::root_listgen_________________________________________
time_avg …
```
> [ir] [refactor] Add constructor TypedConstant(DataType, T)

- docs/install.rst
- python/taichi/core/util.py
- python/taichi/main.py
- taichi/system/traceback.cpp
Many GAMES 201 students complain about these issues on GitHub, so I put a link in the error message to make a quick response for them.
Link: https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
WANT_LGTM = any
> [misc] tell users to check troubleshooting page when error occurred

- python/taichi/core/util.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel.py
- python/taichi/lang/matrix.py
- python/taichi/lang/util.py
- python/taichi/misc/gui.py
Related issue = close #1130
More to be added? Where to be added? @yuanming-hu
> [Lang] [refactor] shows an error if not called from correct Taichi/Python-scope

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/transforms.h
- taichi/transforms/whole_kernel_cse.cpp
Related issue = #1059 
Fix a bug:
```
$1 = ...
$2 : if $1 {
$3 = const [0]
} else {
$4 = const [0]
}
```
This pass would move the first statements of both branches outside the clause and crash when checking if the last statements of both branches are the same.
> [opt] [refactor] [bug] Avoid throwing exceptions in whole_kernel_cse and fix a bug

- docs/global_settings.rst
- taichi/gui/win32.cpp
Related issue = close #1138
Win32 seems to return upper case for keys, while OS X and X11 uses lower case, let's unify them. Btw, @k-ye do you find ASWD keys working well on OS X? (just run `examples/keyboard.py`)
> [bug] [gui] Use lower case for Win32 key events to unify with X11

- taichi/transforms/check_out_of_bound.cpp
- tests/python/test_debug.py
> [Lang] [IR] Fix bound checks with coordinate offsets

- taichi/backends/metal/api.cpp
- taichi/backends/metal/api.h
- taichi/platform/mac/objc_api.cpp
- taichi/platform/mac/objc_api.h
When debugging #1128 , I find it useful to be able to select which GPU to run. This PR adds the necessary APIs for us to choose GPUs.
Related issue = #1128 
> [metal] Add APIs to list all the available Metal devices

- .travis.yml
- python/build.py
- python/taichi/main.py
- python/taichi/make_changelog.py
Related issue = #1153
---
CI is red since `build.py` cannot find `../CHANGELOG.md`, this PR tries to fix it.
> [misc] Generate changelog before trying to run build.py.

- taichi/gui/cocoa.cpp
- taichi/gui/gui.h
This is a follow up of #1152. Unlike the other platforms, Mac doesn't seem to provide a direct windows closed event that can be polled from the event loop. Instead, we need to register a `NSWindowsDelegate` object, and receive this event asynchronously. This is why I used an atomic bool, `window_received_closed`, to record this event.
Related issue = #1118
> [GUI] Support ti.GUI.EXIT on Mac

- docs/export_results.rst
- docs/gui.rst
- docs/index.rst
- docs/offset.rst
Related issue = Close #1116 
Hi all,
I finished this new tutorial that can help our beginners exporting results as images and videos.Feel free to point out **ANYTHING you would not like(or hate)** so that I can make it better then.
On Ubuntu 18.04 and macOS Mojave this tutorial works well. But currently I have no Windows available at hand, Would anyone be happy to test the install instructions of ffmpeg on windows?
Thank a lot!
Bests,
Xudong
> [Doc] Add export_result section on how to export images and videos

- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/transforms/alg_simp.cpp
Related issue = #1141 #944
Related PR = #1065
WANT_LGTM = any
> [Opt] Improve strength reduction optimization for "pow"

- docs/contributor_guide.rst
- python/taichi/make_changelog.py
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/lower_access.cpp
This brings the running time down from 5s to 6ms. Still a distance from 1.6ms.
> [Perf] Improve dynamic SNode performance

- python/taichi/misc/gui.py
- taichi/gui/cocoa.cpp
- taichi/gui/gui.h
I noticed that the Shift key didn't work on Mac in today's lecture. It's because these keys are modifier keys and had to be handled separately..
> [GUI] [Mac] Support modifier keys like Shift, Ctrl, etc

- docs/dev_install.rst
- misc/empty_pytest.py
- python/taichi/main.py
Related issue = (reported by GAMES 201 students)
> [test] Let pytest-rerunfailures pytest-xdist to be hard dependences

- .gitignore
- benchmarks/fill_dense.py
- benchmarks/fill_sparse.py
- benchmarks/mpm2d.py
- misc/baselines/Makefile
- misc/baselines/gpu_memory_bound.cu
> [misc] Remove usage of deprecated functions in benchmarks

- taichi/transforms/compile_to_offloads.cpp
Related PR = #1180
In order to achieve similar performance, I added some optimization passes.
> [IR] Move "lower_access" after "offload"

- taichi/transforms/simplify.cpp
A quick hack to bring down the test case in #1178 from 6ms back to 1.6ms.
This can be removed once the `WholeKernelCSE` pass is back. Note that without `WholeKernelCSE` `taichi_elements` is still very slow.
> [llvm] [opt] CSE for LoopIndexStmt

- python/taichi/lang/kernel.py
- tests/python/test_oop.py
It can sometimes be useful to call externally defined kernels from inside a data_oriented class (eg. a hook). To do this we just needed to allow python functions (not just methods) to be called from a data_oriented class. 
LGTM = anyone
> [Lang] Support taichi kernels as class members variables

- taichi/backends/cpu/jit_cpu.cpp
Related issue = #655 (if any)
This PR fix name mangling in JIT CPU backend to support LLVM 10 on macOS.
> [LLVM] Support LLVM 10 on macOS

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/atomic_stubs.h
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
- taichi/backends/metal/struct_metal.h
This PR has no functionality changes. It just reimplements Metal's `ListManager` via the dynamic memory allocator on the GPU. All the existing tests have passed, and `taichi_sparse.py` ran just fine.
The concrete design is listed in #1174  itself.
Related issue = #1174 
> [metal] Add kernel side memory allocator

- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/transforms/die.cpp
- taichi/transforms/whole_kernel_cse.cpp
Related PR = #1180 
Also modifies the `DIE` pass and removes `ExternalPtrStmt::activate`.
Benchmark:
> [Opt] Improve the whole kernel CSE pass (stage 2)

- taichi/transforms/offload.cpp
- tests/python/test_loops.py
Related issue = fix #1109
For LocalStoreStmt, we should consider not only `stmt->ptr` but also `stmt->data`. I think we can just use the generic visitor.
> [Bug] [ir] Fix a bug in "offload"

- taichi/ir/transforms.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/simplify.cpp
This PR offers shorter compilation time when `advanced_optimization=False` (by removing a `full_simplify` pass), and makes `full_simplify` more "full simplified".
Benchmark: the running time of a large program.
- advanced_optimization=True:
- Before: total running time = 6m51s, compilation time of a large kernel = 6m37s
```
codegen_accessor_statements: 148.00
codegen_evaluator_statements: 102.00
codegen_kernel_statements: 29020.00
codegen_offloaded_tasks: 53.00
codegen_statements  : 29270.00
```
- After: total running time = 6m51s, compilation time of a large kernel = 6m35s
```
codegen_accessor_statements: 148.00
codegen_evaluator_statements: 102.00
codegen_kernel_statements: 29020.00
codegen_offloaded_tasks: 53.00
codegen_statements  : 29270.00
```
- …
> [Opt] Make full_simplify iterative when advanced_optimization=True

- docs/global_settings.rst
- python/taichi/lang/__init__.py
---
Btw. is that possible to move `advanced_optimization` to `CompilerConfig`?
> [CLI] Add TI_ADVANCED_OPTIMIZATION config env var

- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/transforms/simplify.cpp
- taichi/util/bit.h
This PR does **not** solve the issue of strong access of dynamic SNodes. It only eliminates the OffsetAndExtractBitsStmt.
Test case:
```python
ti.init(print_ir=True, print_preprocessed=True)
a = ti.var(ti.i32)
ti.root.dynamic(ti.j, 16).dynamic(ti.i, 8).place(a)
@ti.kernel
def kern():
for I in ti.grouped(a):
a[I] = 1
for i in range(16):
for j in range(8):
a[i, j] = 0
kern()
for i in range(16):
for j in range(8):
assert a[i, j] == 1
```
Before:
```
kernel {
$0 = offloaded clear_list S1dynamic
$1 = offloaded listgen S0root->S1dynamic
$2 = offloaded clear_list S2dynamic
$3 = offloaded listgen S1dynamic->S2dynamic
$4 = offloaded struct_for(S2dynamic) block_dim=0 {
<i32 x1> $5 = loop $4 index 1
<i32 x1> $6 = loop $4 index 0
<i32 x1> $7 = const [1] …
```
> [Opt] Eliminate useless OffsetAndExtractBitsStmt of a LoopIndexStmt

- codecov.yml
- tests/python/test_matrix.py
----
According to https://docs.codecov.io/docs/commit-status.
> [test] Add coverage threshold to make codecov not fail so easily

- taichi/analysis/clone.cpp
- taichi/ir/ir.h
- taichi/ir/transforms.h
- taichi/transforms/alg_simp.cpp
- taichi/transforms/binary_op_simplify.cpp
- taichi/transforms/check_out_of_bound.cpp
- taichi/transforms/fix_root_block_kernel.cpp
- taichi/transforms/type_check.cpp
I've managed to fix all the `kernel == nullptr` problems that I've found so far. Note that this PR alone doesn't fix all the problems. In order to run `mpm99`, you would still need to disable kernel fusion and constant folding. What's more interesting is that, the main constant folding workflow is fine, the problem was around https://github.com/taichi-dev/taichi/blob/1402c4e5501984e765cacab566117dd07ede07cc/taichi/transforms/constant_fold.cpp#L213-L215
Honestly I think `IRNode::get_kernel()` is mostly broken in the async mode, since it depends on the assumption that root is a block.. 
Related issue = #1243 
----
> [ir] Set root block kernel after cloning

- taichi/ir/transforms.h
- taichi/transforms/check_out_of_bound.cpp
- taichi/transforms/constant_fold.cpp
> [Opt] [ir] [refactor] Remove exceptions from IR check_out_of_bound and constant_fold

- taichi/analysis/verify.cpp
- taichi/transforms/alg_simp.cpp
- taichi/transforms/binary_op_simplify.cpp
- taichi/transforms/cfg_optimization.cpp
- taichi/transforms/check_out_of_bound.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/die.cpp
- taichi/transforms/extract_constant.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/loop_vectorize.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/make_adjoint.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/reverse_segments.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
- taichi/transforms/variable_optimization.cpp
- taichi/transforms/vector_split.cpp
- taichi/transforms/whole_kernel_cse.cpp
Related issue = #926 
Usage: `ti.core.print_profile_info()`
Example:
taichi_elements/demo_2d.py
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[Profiler thread 5444]
1.674  s taichi::lang::TaichiLLVMContext::clone_runtime_module [1 x   1.674  s]
1.581  s 94.43%  taichi::lang::compile_runtime_bitcode [1 x   1.581  s]
0.033  s  1.95%  taichi::lang::module_from_bitcode_file [1 x  32.674 ms]
0.060  s  3.60%  clone module          [1 x  60.314 ms]
605.888 ms taichi::lang::StructCompilerLLVM::run [1 x 605.888 ms]
0.217 ms  0.04%  taichi::lang::StructCompilerLLVM::generate_types [33 x   6.576 us]
0.458 ms  0.08%  taichi::lang::StructCompilerLLVM::generate_child_accessors [1 x 458.000 us]
71.000 us 15.50% …
```
> [misc] Add auto-profiling to IR passes

- docs/internal.rst
- python/taichi/lang/snode.py
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- tests/python/test_indices.py
Related issue = #1178 #1229  
----
> [Bug] [opt] [doc] Fix OffsetAndExtractBitsStmt optimization and improve documentation on virtual/physical indices

- benchmarks/fill_dense.py
- benchmarks/fill_sparse.py
- examples/mgpcg.py
- examples/mgpcg_advanced.py
- misc/benchmark_parallel_compilation.py
- python/taichi/lang/__init__.py
- python/taichi/misc/gui.py
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/cuda_context.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/gui/gui.h
- taichi/jit/jit_module.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/kernel.cpp
- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/python/export_visual.cpp
- taichi/runtime/runtime.h
We have two independent profiling system:
- `ProfilerBase` that has flat records on kernel launches on devices
- `ScopedProfiler` that has a hierarchical structure for host tasks (JIT etc.)
In this PR,
- `ProfilerBase` now renamed to `KernelProfilerBase` to distinguish it from the scoped profiler (e.g. `TI_AUTO_PROF`)
- Removed `GUI::ProfilerBased *`. In the future if profiling is needed we should use the scoped profiler there.
- Restored CUDA event-based profiling
----
> [perf] Refactor kernel profiler

- .github/workflows/persubmit.yml
- misc/check_pr_title.py
Related issue = #1241
----
`[release] v0.6.10`, here `v` is lowercase, so error comes.
We only want to make other PRs to be uppercased like `[lang] Hello world` but not for `[release]`.
I tweaked PR title checker to make it support a separate checking logic for `[release]` PRs.
It also support semver bump checking in case we make wrong :) @FantasyVR 
e.g.: `v0.6.10 -> v0.6.12` ERROR! `v0.6.` ERROR!
> [workflow] Improve PR title checker for the release tag

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/shaders/ad_stack.metal.h
- taichi/program/extension.cpp
- tests/python/test_ad_if.py
I noticed that Metal hasn't supported this yet. It seems like all I need to do is adding a small stack to support the complex AD kernels? I guess OpenGL can do similar things by simulating a per-thread stack, with each entry being a `(primal, adjoint)` pair (@archibate )
Related issue = #581 
----
> [Metal] Add AD stack to support the local mutables when using AutoDiff

- taichi/ir/transforms.h
- taichi/transforms/die.cpp
Related issue = #1059 
This is the only pass remained that can be modified simply, the others would require making changes to `DelayedIRModifier`(adding functions like `replace_with`). I'll make them in another PR.
----
> [Opt] [ir] [refactor] Remove exceptions from DIE pass

- docs/global_settings.rst
- python/taichi/lang/expr.py
- python/taichi/lang/util.py
----
To reduce start up time by ~8x, and avoid possible compatibility issues.
I also find that `torch` also import `IPython` too???!! May cause compat issues in #1222.
----
Btw, I noticed that `torch` seems to be not installed in `misc/ci_setup.py`, this means **torch behavior is not tested** in CI, is this intentional?
TBH I install `torch` just for ensuring `ti test`.. my knowledge about torch is completely zero..
> [CLI] Toggle torch import by env var: TI_ENABLE_TORCH

- taichi/program/program.cpp
Related issue = close #1266 
----
> [cuda] [bug] Fix CUDA runtime crash

- misc/baselines/Makefile
- misc/baselines/ldg.cu
- python/taichi/lang/__init__.py
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/statements.h
- taichi/transforms/ir_printer.cpp
- taichi/transforms/offload.cpp
> [CUDA] Support "ti.cache_read_only"

- taichi/analysis/build_cfg.cpp
- taichi/analysis/data_source_analysis.cpp
- taichi/ir/control_flow_graph.cpp
A continuation of #1248
This PR creates an empty start node in the CFG, and let it be the data source of everything to be loaded in any `GlobalLoadStmt`s in the IR.
This PR also does this optimization https://github.com/taichi-dev/taichi/pull/1248#discussion_r441791450.
Benchmark on the number of statements: unchanged.
----
> [opt] Do not consider each GlobalPtrStmt as a data source in store forwarding

- .travis.yml
- appveyor.yml
- docs/syntax.rst
- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
Related issue = This PR is a broken down stage from #1214, which originally try to do both SNode + Matrix coverage improvement.
Let's try to merge this first since it's really trivial comparing to #1214.
----
> [lang] [test] Improve code coverage in Matrix

- taichi/ir/control_flow_graph.cpp
Related PR = #1248
This subtle bug may cause later constant folding pass to fail.
----
> [opt] Fix CFGNode::store_to_load_forwarding data type

- taichi/ir/statements.h
Related PR = #1218
We can't move the write operations to stacks out of if-clauses although they don't have "global" side effects.
----
> [Bug] [opt] Fix a bug causing gradients to be NaNs

- python/taichi/core/util.py
- taichi/common/core.cpp
- taichi/common/core.h
- taichi/python/export_lang.cpp
- taichi/transforms/auto_diff.cpp
Related issue = #1287 
----
Last [pr](https://github.com/taichi-dev/taichi/pull/1289) is closed because I overwrite the master branch accidentally. Sorry about that. 
@archibate , you are right. I shouldn't create pr using the master branch. Thanks for your reminder.
> [misc] Show LLVM version on startup

- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- taichi/backends/opengl/codegen_opengl.cpp
- tests/python/test_element_wise.py
- tests/python/test_linalg.py
Related issue = close #1288
----
**I know this will break DiffTaichi if I modify `ti.Vector.normalized()` to use `norm_inv`**, so could you tell me how to make autodiff work for rsqrt?
> [Std] [lang] Add ti.rsqrt() and ti.Vector.norm_inv()

- taichi/backends/metal/codegen_metal.cpp
- tests/python/test_ad_for.py
I forgot to declare the variable inside the codegen.
Related issue = #1285 
----
> [metal] [autodiff] Fix StackLoadTopStmt codegen in Metal

- misc/benchmark_reduce.py
- taichi/analysis/verify.cpp
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/constants.h
- taichi/inc/statements.inc.h
- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/ir/transforms.h
- taichi/program/kernel.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/die.cpp
- taichi/transforms/fix_block_parents.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/statement_usage_replace.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_oop.py
Related issue = #576 
Benchmark:
```python
ti.init(print_ir=True, kernel_profiler=True)
N = 1024 * 1024
a = ti.var(ti.i32, shape=N)
tot = ti.var(ti.i32, shape=())
@ti.kernel
def fill():
for i in a:
a[i] = i
@ti.kernel
def reduce():
for i in a:
tot[None] += a[i]
fill()
reduce()
ground_truth = 10 * N * (N - 1) / 2 % 2**32
assert tot[None] % 2**32 == ground_truth
ti.kernel_profiler_print()
```
Before: *17ms*
After: *0.48ms* (35x faster)
----
Design doc:
> [Perf] Thread local storage for range-for reductions on CPUs

- taichi/ir/control_flow_graph.h
- taichi/ir/ir.cpp
- taichi/transforms/cfg_optimization.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/simplify.cpp
- tests/python/test_continue.py
Related issue = fix #1297 
I moved the unreachable code elimination pass from `cfg_optimization` to `simplify` because the former can't eliminate container statements properly. I tried writing something like `std::vector<Stmt *> not_in_any_nodes` in the CFG, but it's hard to know whether a `ContinueStmt` can be eliminated in the CFG, so an `IfStmt` with only one `ContinueStmt` in it can't be eliminated easily too.
----
> [Bug] [opt] Fix compilation crash when there is a container statement after an unconditional continue

- taichi/backends/metal/shaders/print.metal.h
I've implemented the support for `print()` in Metal in my local branch https://github.com/k-ye/taichi/tree/print2. To reduce the size, this PR just adds the Metal kernel code. The idea is similar to what @archibate has done for OpenGL.
Each `PrintMsg` corresponds to one `print()` call. That is, all args in the print are packed in this msg. Its schema looks like the following:
* 1 `i32` to record how many args there are
* Followed by M `i32`s, which are the type masks. We only have three types for now: `I32`, `F32` and `Str`. Each type is configured to take `4` bits, therefore, a single `i32` mask can encode the types of `8` args.
* Followed by N `i32`s, one for each data. `F32` are encoded to `I32`. For strings, like OpenGL's impl, we have a string table on the host side, so that the …
> [metal] Add kernel side util to support print()

- python/taichi/lang/impl.py
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/codegen/codegen_llvm.cpp
- tests/python/test_print.py
I found that `print` would add a ` ` between every two args. This could be very useful in cases like `print(x, y, z)` --> `1 2 3`. However, for cases like `print('x[', i, ']=', x[i])`, it results in `x[ i ]= 42`. I think the expected outcome should be `x[i]=42`.
----
> [Lang] Support sep and end in print()

- taichi/transforms/constant_fold.cpp
- taichi/transforms/type_check.cpp
Related issue = #656 #510 close #1278
----
> [Opt] Constant folding for BitExtractStmt

- taichi/ir/transforms.h
- taichi/transforms/continue_stmt_optimization.cpp
- taichi/transforms/simplify.cpp
Related PR = #1299 
I did this refactoring because the optimization about `ContinueStmt` in `simplify` I added in #1299 probably made removing the exceptions (#1059) in that pass more difficult.
Although the function of this pass is similar to the `DIE` pass, the logic is completely different. So I put it in a separate pass. We can eliminate `ContinueStmt`s like the following in this PR:
```
$1 = for ... {
$2 = ...
$3 : if ... {
$4 = continue
}
}
```
I'm not sure about how this pass should be named, so feel free to propose better names.
----
> [Opt] [refactor] Move unreachable code elimination to a separate pass

- taichi/backends/cuda/codegen_cuda.cpp
- tests/python/test_numpy.py
- tests/python/test_torch_io.py
Clarification: passing a numpy array with 0 bytes will make cudaMalloc fail because it doesn't support allocating GPU buffers with 0 bytes.
Not sure if OpenGL or Metal needs similar patches.
----
> [cuda] Support numpy and torch tensors with zeros in shapes (e.g., (5, 0, 5))

- taichi/transforms/re_id.cpp
> [misc] Fix compilation warning

- taichi/gui/gui.cpp
Hi all,
One of our classmate in GAMES201 from Wechat found that ONLY when  [va, vb, vc] is in counterclockwise order can `ti.gui.triangle(va, vb, vc)` manage to display it. If the offered vertices are in clockwise, our `ti.GUI` simply ignore it.
For example, if I say
```
triangle=[(0.3,0.5),(0.4,0.7),(0.5,0.55)]
gui.triangle(*triangle,color=0xff0000)
```
This triangle won't be drawn.
If it is a designed feature, maybe we can try to doc it?
If not, here is one possible solution.
HDYT? Maybe we can have a better solution.
> [GUI] Fix issue with triangles not showing up when they are drawn clockwisely

- python/taichi/misc/util.py
Hi all,
When I am testing `ti.info`, I found that there is a literally typo in our `util.py`.
It will crash all logging APIs. :(
> [Misc] Fix a bug in util.py

- docs/export_results.rst
- docs/offset.rst
- examples/export_videos.py
Fix some typos in the doc `export_results.rst` as @archibate mentioned.
> [doc] Fix some typos in our document export_results.rst

- python/taichi/core/util.py
Related issue = close #958 close #1100 close #1106 close #1113 close #1325 
----
Specifying `RTLD_GLOBAL` will expose Taichi-customized LLVM symbols to other modules that may depends on other LLVM versions, e.g. GLX depends on LLVM and cause the issues above.
@Eydcao @TroyZhai This issue is finally solved systematically!!! Please confirm that if this PR works when you have time :)
> [Bug] [linux] [opengl] Use RTLD_LOCAL to prevent LLVM symbol conflict with GLX

- python/taichi/lang/ops.py
Related issue = https://github.com/taichi-dev/taichi/pull/1188#issuecomment-649578632
----
I removed ti.raw_pow and use pow directly instead, but seems the issue still exists? @k-ye Could you confirm that on your end?
> [lang] Deprecate ti.raw_pow

- docs/global_settings.rst
No Related issue;
Super minor typo in `docs/global_settings.rst`. 
Noticed there's an extra `.` while I was updating the CN version and it kept bugging me so thought I'd remove it lol.
The **last** line in the following photo: 
----
> [Doc] Remove duplicates in global settings

- taichi/analysis/build_cfg.cpp
- taichi/analysis/data_source_analysis.cpp
- taichi/ir/analysis.h
- taichi/ir/control_flow_graph.cpp
- taichi/ir/control_flow_graph.h
- taichi/transforms/cfg_optimization.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/variable_optimization.cpp
- tests/python/test_offload_cross.py
Related issue = #926 #656 
Related PR = #932 #1248 
Replaces #859 #857 
Change in `build_cfg`: 
- Add an empty `final_node`. Then assume there are reads to all global pointers after the final node (just like there are writes to all global pointers before the start node), for more convenient analysis on global pointers.
- Tell each `CFGNode` if they are parallel executed (i.e. in an offloaded range_for/struct_for's body).
Change in `CFGNode`:
- Add `replace_with`, deprecate `erase_entire_node`.
- Use `contain_variable` for both `reach_kill_variable` (https://en.wikipedia.org/wiki/Reaching_definition) and `live_kill_variable` (https://en.wikipedia.org/wiki/Live_variable_analysis). Keep the function `reach_kill_variable` because `reach_kill` should contain **definition**s instead of …
> [Opt] Dead store and stack-related operation elimination by control-flow graph

- python/taichi/lang/impl.py
- python/taichi/lang/snode.py
- tests/python/test_tensor_reflection.py
Seems like https://github.com/taichi-dev/taichi/pull/1214/files#r440768343 wasn't addressed. I'd suggest us not to make root circular and keep the parent chain linear. Following parent until null is a fairly common op, e.g. https://github.com/taichi-dev/taichi/blob/37976e750e1579ff9328f3d25f1a63cb3b3292e2/taichi/transforms/offload.cpp#L87-L95
This PR also handles the case where `n` exceeds the hierarchy depth.
Related issue = #1214
----
> [lang] Return None when parent() exceeds its maximum depth

- Jenkinsfile
- cmake/TaichiCore.cmake
- taichi/common/core.cpp
- taichi/common/core.h
Related issue = #1313 
Since the dependency is not introduced in Taichi, I had to use this trick: https://stackoverflow.com/questions/8823267/linking-against-older-symbol-version-in-a-so-file
----
> [linux] Remove glibc2.27 dependency (log2f@glibc2.27)

- misc/ci_setup.py
- python/taichi/lang/ops.py
- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/ir.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_sparse_activate.py
- tests/python/test_sparse_deactivate.py
Related issue = https://github.com/taichi-dev/taichi/pull/1256#discussion_r445026670
----
Would you write a test for me? I'm not super familiar with sparse.
> [Sparse] [lang] Add ti.activate support

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
Added `TaichiKernelAttribs` and `UsedFeatures` according to @archibate 's suggestion.
Related issue = #https://github.com/taichi-dev/taichi/pull/1310#discussion_r444901120
----
> [refactor] [metal] Add a TaichiKernelAttribs struct

- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/simplify.cpp
Related issue = #1059 #656 
Also modifies `constant_fold` because `codegen_llvm.cpp` can't handle casting a value to the same type properly. We didn't encounter this issue because `constant_fold` was always after `simplify`, which eliminates this case.
I'll remove the CSE part of `simplify` in another PR.
Benchmark:
**Before this PR**:
```
codegen_accessor_statements: 148.00
codegen_evaluator_statements: 102.00
codegen_kernel_statements: 28573.00
codegen_offloaded_tasks: 53.00
codegen_statements  : 28823.00
1.250  m taichi::lang::Program::compile [27 x   2.779  s]
1.191  m 95.27%  taichi::lang::irpass::compile_to_offloads [27 x   2.647  s]
0.353  m 29.62%  taichi::lang::irpass::lower [27 x 784.178 ms]
0.003  m  0.27%  taichi::lang::irpass::typecheck [108 x   1.781 ms]
0.002  m  0.17% …
```
> [Opt] Replace "simplify" with "full_simplify" in "Simplified I"

- cmake/TaichiCore.cmake
Related issue = #1332 
Jenkins crashes after #1348. We should turn it on by default only after it's mature.
----
> [misc] Exclude the C backend by default to fix Linux builds

- python/taichi/lang/impl.py
- python/taichi/lang/transformer.py
- taichi/transforms/simplify.cpp
- tests/python/test_for_group_mismatch.py
----
Before this PR, the following code won't raise any error at all:
```py
x = ti.var(ti.f32, (3, 4))
@ti.kernel
def func():
for i in x:  # either use `for i, j in x` or `for I in ti.grouped(x)` instead!
print(i)
func()
```
So I'm making struct-for mismatch raise `IndexError` now.
But I apply the same to ndrange-for, cause it seems `ti.ndrange` transformer needs refactoring anyway... IMO it should share the same error checker if we decide to do so.
I think just alerting mismatch struct-for and saying `maybe you want to use ti.grouped() instead` is good enough, since user can see range numbers if using ndrange-for.
---
Btw, I think we may default to `ti.grouped` at this case?
> [lang] Raise an error when struct-for indices number mismatch

- python/taichi/misc/gui.py
----
Since `img.shape()` in function `set_image` has been deprecated, changed to `img.shape` in order to get rid of DeprecationWarning.
> [misc][gui] Resolve deprecation warning (img.shape)

- taichi/analysis/build_cfg.cpp
- taichi/ir/control_flow_graph.cpp
`stmt->is<AllocaStmt>() || stmt->is<LocalStoreStmt>()` is not enough -- it didn't cover the local atomics' case.
Also considers range_for and struct_for as parallel for-loops before the `offload` pass.
----
> [bug] [opt] Fix CFG ignoring local atomics after lower_access

- taichi/backends/cc/cc_utils.h
- taichi/backends/cc/codegen_cc.cpp
- taichi/util/str.cpp
- taichi/util/str.h
Moving this to a common utils so that IR printer can also use it.
@archibate I don't have a way to test the C backend on Mac. Could you confirm this doesn't break?
Related issue = https://github.com/taichi-dev/taichi/pull/1350#discussion_r448384579
----
> [refactor] Move c_quoted into taichi/utils/

- taichi/transforms/compile_to_offloads.cpp
Related PR = #1285 
I believe this is fixed in #1299. @yuanming-hu Could you please double-check if the demos work now which didn't work without the pass?
----
> [ir] Remove a temporary "fix_block_parents"

- python/taichi/main.py
- taichi/analysis/verify.cpp
- tests/python/test_cli.py
Related issue = https://forum.taichi.graphics/t/internal-error-occurred/941
----
Some user consider `ti run` as running scripts, like `ti debug` does.
So I move it to `ti task` for runing task instead.
Also fixed the `FIXME` in `ti debug` as OFT.
> [cli] Use "ti task" for run task (legacy), and "ti run" to run script

- taichi/transforms/offload.cpp
- tests/python/test_offload_cross.py
Related issue = fix #1390 
Global atomic op should call the generic visitor instead of the overloaded one.
Added a test that fails before this PR.
----
> [Bug] [ir] Fix compilation crash when there's a cross-offload global atomic operation

- .github/workflows/persubmit.yml
- appveyor.yml
> [llvm] Use LLVM 10 for AppVeyor and GitHub actions

- Dockerfile
- docs/dev_install.rst
- taichi/analysis/build_cfg.cpp
- taichi/ir/control_flow_graph.cpp
(I recently wanted to use taichi through a ssh tunnel on a container cluster and realized the Dockerfile is outdated)
----
In order to test this out, please either build the image locally with: `docker build -t taichi:2b181a26 .`(this builds the image from source so may take up to 40 mins) OR pull the image I built and pushed with : `docker run -it rexwangcc/taichi:2b181a26`
- For a quick check, you could run `ti test` within the container. 
- For a more sophisticated test, with `docker`installed properly, please follow:
1. Make sure XQuartz and socat are installed:
```
brew cask install xquartz
brew install socat
```
2. Temporally disable the xhost access-control: `xhost +`
3. Run an example, such as …
> [Docker] Update the Dockerfile to use up-to-date instructions for Ubuntu

- tests/python/test_linalg.py
> [test] [std] Add matrix SSA violation regression test

- tests/python/test_tuple_assign.py
This is probably more of a workaround. I don't think the IR optimizer should change the semantics of the for loop. That means we need to preserve the top-level `if` if the compile time condition is true, or transform it to a serial kernel, like this PR does..
Maybe we should also have a dedicated method to instruct that the for loop is meant to be executed inside a serial kernel. Right now this `for _ in range(1):` seems hacky..
Related issue = https://github.com/taichi-dev/taichi/pull/1393#issuecomment-653854873
----
> [bug] Fix test_fibonacci

- misc/prtags.json
- python/taichi/lang/matrix.py
----
It seems that when pybind11 got an type mismatch, it will try to invoke `repr` to show the object...
So we have to make it happy with a dummy string in `Matrix.__repr__` instead of `cannot be called from Python-scope`.
```py
ti.init()
@ti.kernel
def func():
x = ti.Vector([2, 3])
if x:
pass
func()
```
Before:
```
File "w.py", line 12, in <module>
func()
File "/root/taichi/python/taichi/lang/kernel.py", line 553, in wrapped
return primal(*args, **kwargs)
File "/root/taichi/python/taichi/lang/kernel.py", line 483, in __call__
File "/root/taichi/python/taichi/lang/kernel.py", line …
```
> [error] Fix wrong error message when using vector as if condition

- taichi/gui/cocoa.cpp
Simpler than i thought..
Related issue = #1150
----
There's a possibility that the vertical scrolling direction of Mac's trackpad is the reverse of that of the mouse wheel.
> [GUI] Support mouse wheel event on Mac Cocoa

- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_context.h
- taichi/program/program.cpp
- taichi/runtime/llvm/runtime.cpp
Benchmark: `sdf_renderer.py` 
CUDA Before: 66 samples/s
CUDA After: 102 samples/s
OpenGL reference: 90 samples/s
----
> [CUDA] Improve random number generator performance

- python/taichi/lang/matrix.py
- tests/python/test_matrix.py
Related issue = https://forum.taichi.graphics/t/hw0-5-implicit-euler-method-on-mass-spring-system/961/5
----
They may thought Taichi matrix **doesn't support syntax like mat[i, j] at all**..
> [error] Instruct user to use static range when matrix accessed with non constant index

- misc/benchmark_reduction_tmps.py
- taichi/transforms/make_thread_local.cpp
- tests/python/test_reduction.py
> [Perf] Support TLS for GlobalTemporaryStmt

- taichi/backends/metal/api.cpp
- taichi/backends/metal/api.h
- taichi/backends/metal/kernel_manager.cpp
It turned out the current `.shared` storage mode has made things pretty slow. This PR switched to use the `.managed` storage mode for `MTLBuffer`s, see https://developer.apple.com/documentation/metal/setting_resource_storage_modes/choosing_a_resource_storage_mode_in_macos.
Benchmark result:
| example       | old FPS (.shared) | new FPS (.managed) |
|---------------|-------------------|--------------------|
| mpm88         | 21-22             | 25-28              |
| mpm_lag_force | 11                | 13                 |
| stable_fluid  | 23                | 50                 |
| vortex*        | 1.2               | 6                  |
* I shamelessly copied the vortex example from here https://forum.taichi.graphics/t/vortex-method-demo/775. Note that the original example's …
> [Metal] Use managed storage mode to improve performance

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_util.h
I hope this will make things easier?
Related issue = #1428
----
> [metal] Pass kernel name and is_evalutator to the runtime

- taichi/analysis/data_source_analysis.cpp
- taichi/ir/control_flow_graph.cpp
- taichi/ir/control_flow_graph.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- tests/python/test_ad_for.py
Related issue = #1324 https://github.com/taichi-dev/taichi/pull/1394#discussion_r449817354
----
> [Opt] [bug] Better aliasing analysis for dead store elimination

- .travis.yml
> [llvm] [mac] Update OS X build bots with prebuilt LLVM 10

- README.md
- docs/contributor_guide.rst
- docs/dev_install.rst
- taichi/llvm/llvm_context.cpp
Related issue = closes #416 (I think by now we have resolved all issues directly about docker)
----
- Update the docs about how to use `ti task` over `ti run`
- Add a build badge for Docker automation (🎉  the docker build trigger worked for both master branch and tagged releases [here](https://hub.docker.com/r/taichidev/taichi) thanks to the help from @yuanming-hu )
> [doc] [Docker] Some minor doc fixes and add a docker build badge

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
This PR just moves some util functions into `ListManager` as its member functions. This is a cleanup in prep for `NodeManager`.
Again, please ignore the formatter suggestion, if there is any. They tend to mess up these `.metal.h` files..
Related issue = #1174
----
> [metal] Refactor runtime ListManager utils

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
Related issue = fixes #1460 
----
Thank @gmh14 for reporting!
I made the test to use different size in rhs and lhs to prevent regression.
> [Bug] [lang] Fix outer_product output matrix shape

- python/taichi/lang/impl.py
- tests/python/test_numpy.py
----
Sorry about breaking master test :(
But what's the point of using `np.ndarray` in Taichi-scope?
IMO `ti.ext_arr()` is being **edged** and can be easily buggy.. e.g.: https://forum.taichi.graphics/t/hw0-5-implicit-euler-method-on-mass-spring-system/961/13
If we don't maintain `ti.ext_arr()`, how about just deprecate it and do some walk around for `to_numpy`?
> [test] [bug] Fix master test failure by #1437

- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/transforms/alg_simp.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/whole_kernel_cse.cpp
- tests/cpp/test_same_statements.cpp
- tests/cpp/test_simplify.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/1059#issuecomment-647181953
Notice that `advanced_optimization=False` may not function well after this PR because we assume some optimizations are done after some passes. For example, we assume there's no usage of the return value of atomic operations in `auto_diff`, there's no `GlobalPtrStmt` after the `die` after `lower_access`, and there's no typecast to the same type of the input operand when we generate the code to LLVM.
Update: also removes `SNodeLookupStmt::global_indices`.
----
> [Opt] [refactor] Remove the CSE part from the simplify pass

- python/taichi/lang/impl.py
- taichi/transforms/type_check.cpp
- tests/python/test_indices.py
Related issue = close #1360
----
IIUC the index to tensor should always be int32 no matter what default_ip is?
> [Lang] Make tensor indicing automatically cast to int32 and raise an warning

- python/taichi/main.py
----
e.g.:
`ti test bitmasked -k huge_bitmasked`
will only run the `test_bitmasked.py::test_huge_bitmasked`.
`ti test -x`
will exit immediately after first failure occured.
> [cli] [test] Add some useful pytest arguments

- examples/tree_gravity.py
- python/taichi/misc/gui.py
Related issue = close #814
----
Thanks to Taichi's lack of recursion, make tree method really hard to implement.
Currently this example only works on one single CPU thread so don't expect too much on FPS...
A paper on n-body parallelization: http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=82AC752BCA1CEDB59F0CA397E46F7452?doi=10.1.1.315.4896&rep=rep1&type=pdf
Hope this could attract many people in astrophysics. @yuanming-hu Could you update the README.md gallery for this?
<del>I'd like to write a zhihu post on this later when I've time.</del>
Done with an English post in: https://forum.taichi.graphics/t/hw-1-2-gravity-simulation-with-tree-method-in-o-n-log-n-2d-3d/980
> [Example] Add tree method n-body solver of O(n log n): tree_gravity.py

- docs/debugging.rst
- docs/meta.rst
- python/taichi/__init__.py
- python/taichi/lang/__init__.py
- python/taichi/lang/ops.py
- python/taichi/lang/util.py
- python/taichi/misc/error.py
- taichi/python/export_lang.cpp
> [Refactor] [lang] "ti.sqr(x)" is now fully deprecated

- taichi/backends/metal/api.cpp
- taichi/backends/metal/api.h
- taichi/backends/metal/kernel_manager.cpp
- tests/python/test_element_wise.py
* `fast_math` helped mostly with computation-bounded tasks. E.g. 
* sdf_renderer: 25 -> 43 sps
* cornell_box: 95 -> ~130 sps
* As you can tell, enabling `fast_math` broke a few tests. Given that these tests were doing a `3.0 / 3.0`, i'm not too surprised by that. But I had to turn off `fast_math`.
* @yuanming-hu IIUC, `saturating_grid_dims` can be used to limit the total number of threads? I'd like to do that once users can actually set it in `ti.init()`..
Related issue = #935
----
> [Metal] Support fast_math, preps for saturating_grid_dim

- docs/atomic.rst
- docs/install.rst
- docs/matrix.rst
- docs/vector.rst
- python/taichi/lang/matrix.py
> [doc] Add matrix method documentation including normalized()

- docs/gui.rst
- examples/gui_widgets.py
- python/taichi/misc/gui.py
- taichi/gui/gui.h
- taichi/python/export_visual.cpp
Related issue = close #484
----
Btw, I found the slider circle is not shown, is this intentional?
> [GUI] Support slider, label and button as widgets

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/jit_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
x86+CUDA test time reduced from 6min to 3.5min.
----
> [CUDA] [perf] Improve CUDA JIT compilation speed

- docs/debugging.rst
- python/taichi/lang/impl.py
Related issue = #1483
----
1. I made the `ti.sync()` section `note` -> `warning` for #1483.
2. I fixed the `.. code-block:: python` no newline causing render issue in browser (**all people who changed doc please run `ti doc` and see if rendering is correct, thanks :)**)
> [doc] Fix code-block render issue in debugging.rst

- python/taichi/lang/transformer.py
- tests/python/test_static.py
Related issue = close #1495
----
I added the concept of `control_scope` to detect if the current loop is a static loop, so that we can prevent translating the `break` there to be breaking the grandparent non-static loop.
> [Lang] Support "break" and "continue" in static-fors

- cmake/PythonNumpyPybind11.cmake
- python/build.py
- python/taichi/main.py
- setup.py
----
1. Remove the `tid` command:
We already have `ti debug` and the `debug` argument in `main` seems useless...
In fact, it's already not functional at all:
```
root@archlinux ~/taichi (git)-[remove-tid-useless-bin-hook] # tid
[Taichi] preparing sandbox at /tmp/taichi-6z2hiodm
[Taichi] <dev mode>, llvm 10.0.0, commit a93efc54, python 3.8.3
File "/root/taichi/bin/tid", line 4, in <module>
exit(taichi.main(debug=True))
TypeError: main() got an unexpected keyword argument 'debug'
```
2. Use `#!/usr/bin/env python3` instead of `#!${PYTHON_EXECUTABLE}`:
Well, what if one use anaconda python3?
The PYTHON_EXECUTABLE is determinated by the …
> [cli] Remove the never used 'tid' command

- python/taichi/main.py
Related issue = #1216 #1465 
`args` doesn't have these attributes on my end.
----
> [cli] Fix "AttributeError" of pytest arguments

- cmake/TaichiCore.cmake
- misc/linker.map
Related issue = fix #958
----
By using `libLLVM*.a`, we not only export `taichi::*` in our `libtaichi_core.so`, but also export `llvm::*`.
So that some symbols in `libLLVM-10.so` (also `llvm::*`) somehow gets replaced by those one in `libtaichi_core.so`, which is our **RTTI configured** LLVM, causing the conflict.
So, this PR uses a [LD version script](http://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_25.html), to **prevent symbols in `llvm::*` being exported to global symbol table**, therefore fix the leakage conflict, ultimately.
> [Linux] [llvm] Fix LLVM symbol leakage to prevent conflict with other libs using LLVM like GLX

- taichi/ir/ir.h
Related issue = https://github.com/taichi-dev/taichi/pull/1497#discussion_r455256790
----
> [opt] Enable dead instruction elimination for RangeAssumptionStmt

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/jit_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/inc/constants.h
- taichi/llvm/llvm_codegen_utils.cpp
- taichi/llvm/llvm_codegen_utils.h
- taichi/program/program.cpp
- taichi/runtime/llvm/internal_functions.h
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/check_out_of_bound.cpp
- `error_message_buffer` is renamed to `error_message_template` since it's no longer formatted on the backend device
Maybe it's time to think about unifying the `print`/`assert` functionalities on LLVM/Metal/OpenGL backends. https://github.com/taichi-dev/taichi/issues/1434 may worth considering when designing the shared infrastructure.
----
> [CUDA] [llvm] Format CUDA assertions and access out-of-bound errors on the host

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_field.py
Related issue = #1500:2.1
----
> [Refactor] [lang] Add "ti.field" and "ti.Matrix.field" for future deprecation of "ti.var"

- python/taichi/lang/matrix.py
- tests/python/test_field.py
Related PR = #1502 
Code formatting can often lead to a new commit that doesn't trigger CI, which may hide some test failures if we only look at the build state of the final commit.
I was getting
```
FAILED tests/python/test_field.py::test_vector_field[shape0-dtype1-2] - TypeError: _Vector_field() missing 1 required positional argument: 'dt'
FAILED tests/python/test_field.py::test_vector_field[8-dtype1-2] - TypeError: _Vector_field() missing 1 required positional argument: 'dt'
FAILED tests/python/test_field.py::test_vector_field[8-dtype1-3] - TypeError: _Vector_field() missing 1 required positional argument: 'dt'
FAILED tests/python/test_field.py::test_vector_field[shape2-dtype0-2] - TypeError: _Vector_field() missing 1 required positional argument: 'dt'
FAILED …
```
> [test] Fix test_field.py

- taichi/backends/metal/shaders/runtime_kernels.metal.h
- tests/python/test_bitmasked.py
This is another bug I discovered in the existing sparse runtime on Metal. Basically if the child has a non-zero offset in a `bitmasked` parent cell, then the offset to the bitmasked metadata is wrong. The test might illustrate the problem better..
Related issue = #1174
----
> [metal] Fix listgen when iterating over children of a bitmasked SNode

- python/taichi/lang/__init__.py
There's a minor issue: if the user sets `TI_USE_UNIFIED_MEMORY=0` and then use `ti.init(use_unified_memory=False)`, Taichi will report an error saying `use_unified_memory` is not recognized. This PR fixes that, and adds a warning in this case:
```
[W 07/17/20 00:15:41.272] ti.init argument "use_unified_memory" overridden by environment variable "TI_USE_UNIFIED_MEMORY"=0
```
----
> [misc] Fix ti.init argument parsing when corresponding environment variable presents

- tests/python/test_field.py
Maybe here is a typo in `test_field.py` ;-)
> [test] Fix a typo in test_field.py that caused the failure of CI

- taichi/backends/metal/shaders/runtime_utils.metal.h
This is another PR to make #1480 easier to review. I just added the `SNodeRep_*` structs for each type of SNode, *without* having the codegen using them. Eventually, each generated `S*` structs will contain an instance of these rep structs, which makes codegen a lot easier to deal with sparse operations. It's also a prep for the `pointer` SNode.
Related issue = #1480 
----
> [metal] Introduce SNodeRep_* to be used in the generated SNode structs

- examples/mpm128.py
- examples/mpm99.py
- python/taichi/lang/__init__.py
- tests/python/test_runtime.py
----
I found `TI_ARCH=opengl` results in an error so I'm fixing this.
OFT: Fix mpm99&mpm128 deprecation warning.
> [Bug] [cli] Fix environment variable TI_ARCH=xxx not work

- docs/compilation.rst
- docs/debugging.rst
- docs/export_results.rst
- docs/external.rst
- docs/gui.rst
- docs/hello.rst
- docs/internal.rst
- docs/layout.rst
- docs/matrix.rst
- docs/odop.rst
- docs/offset.rst
- docs/profiler.rst
- docs/scalar_tensor.rst
- docs/snode.rst
- docs/vector.rst
In this PR, documents are mainly updated  for `ti.var`->`ti.field`
TO-DO
----
> [Doc] Update our documents from ti.var to ti.field

- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
Before
```
[  0.18%] copy_dynamic_c24_1_kernel_83_listgen_S24dynamic    min   5.534 ms   avg   5.541 ms   max   5.553 ms   total   0.017 s [      3x]
[  0.01%] copy_dynamic_c24_1_kernel_84_struct_for     min   0.173 ms   avg   0.174 ms   max   0.176 ms   total   0.001 s [      3x]
[  0.00%] copy_dynamic_nd_c22_0_kernel_73_clear_list_S24dynamic    min   0.093 ms   avg   0.111 ms   max   0.133 ms   total   0.000 s [      3x]
[  0.18%] copy_dynamic_nd_c22_0_kernel_74_listgen_S24dynamic    min   5.470 ms   avg   5.524 ms   max   5.553 ms   total   0.017 s [      3x]
[  0.01%] copy_dynamic_nd_c22_0_kernel_75_struct_for    min   0.408 ms   avg   0.411 ms   max   0.417 ms   total   0.001 s [      3x]
[  0.00%] copy_dynamic_nd_c22_1_kernel_76_clear_list_S24dynamic    min   0.093 ms   avg   0.120 …
```
> [misc] Prettify KernelProfiler outputs

- taichi/ir/snode.cpp
- taichi/ir/snode.h
> [misc] Add is_path_all_dense to SNode

- docs/export_results.rst
- docs/external.rst
- docs/gui.rst
- docs/layout.rst
- docs/matrix.rst
- docs/offset.rst
- docs/tensor_matrix.rst
- docs/vector.rst
To keep a small change set, this PR simply **replaces all global tensor `ti.Vector` by `ti.Vector.field`.**
Though I try my best to replace all global tensors `ti.Vector`, there can still be some **slippery fish**. If you caught one, please tell me so that I can correct them.
In case of a waste of time, I want to double check these to-dos with you:
----
> [Doc] Update all global tensor ti.Vector to ti.Vector.field

- taichi/program/program.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/demote_dense_struct_fors.cpp
- taichi/transforms/offload.cpp
This PR widens the opportunity for BLS, and also makes fusion more robust. 
I think the only IR substitution we need is `LoopIndexStmt` -> `LocalLoad(Alloca)`, but even this is already handled in the existing implementation. Since this is a flip of the task type from `struct_for` to `range_for`, all the other IRs referencing this task shouldn't need to be modified? 
At last, I forgot to set Root's `is_path_all_dense` in #1538... Doing it here.
----
> [ir] Move struct-for demotion pass after offload pass

- python/taichi/core/util.py
- python/taichi/lang/matrix.py
Related PR = #1508
----
Why release mode use different code than `import_ti_core` in dev mode... and I found the glfw issue again in release mode.
> [linux] Fix LLVM symbol leakage in release mode by using RTLD_GLOBAL

- docs/export_results.rst
- docs/external.rst
- docs/gui.rst
- docs/matrix.rst
- docs/offset.rst
- docs/tensor_matrix.rst
Good news: this PR has a quite small changeset. 
I do the following stuff in it:
----
> [Doc] Replace ti.Matrix to ti.Matrix.field in the documents

- taichi/backends/cuda/jit_cuda.cpp
Related issue = #1557
----
since it seems to me doesn't affect executation at all.
> [cuda] [llvm] Module broken is TI_WARN instead of TI_ERROR

- python/taichi/lang/__init__.py
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/transforms.h
- taichi/program/async_engine.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/lower_access.cpp
- tests/python/test_no_activate.py
We now
-  use a special list generation kernel for very long `ti.root.dynamic` SNodes
- introduce a `ti.no_activate` hint to tell the compiler not to activate the `dynamic` node (or any other sparse SNode) on write, when you know it's already activated.
----
> [Perf] Improve dynamic listgen and access performance

- examples/taichi_logo.py
- taichi/backends/opengl/codegen_opengl.cpp
----
Before this PR:
```glsl
for (int F_ = E - F; 1_ >= D; F_ -= 1) {
```
Well, `1_`...
After this PR:
```glsl
for (int F_ = E - 1; F_ >= D; F_ -= 1) {
```
> [opengl] Fix reversed nested for loops error on OpenGL

- examples/mpm_lagrangian_forces.py
- python/taichi/lang/matrix.py
- tests/python/test_field.py
- tests/python/test_matrix.py
#1531 broke the example because it forgot to initialize `self.grad`. Adding the fix as well as updating `mpm_lagrangian_force.py` to use `field`.
Related issue = #1531
----
> [bug] Update mpm_lagrangian_force and fix Matrix constructor

- docs/matrix.rst
- docs/meta.rst
- docs/scalar_tensor.rst
- docs/vector.rst
In this issue: The definition of `ti.field`, `ti.Vector.field` and `ti.Matrix.field` are all maintained.
Also, I noticed that in `meta.rst` there are some new-added `ti.var`, so I replace them by `ti.field` as well. Hope this won't break the consistency.
----
> [Doc] Update new allocation APIs' definitions in the documents

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
This is mostly a refactoring of the SNode structs implementation on Metal, with no functional changes.
I added a `SNodeRep_*` for each snode type supported on Metal. It is very similar to the `node_*` files in https://github.com/taichi-dev/taichi/tree/master/taichi/runtime/llvm. Each generated SNode structs will own an `rep_` object.  These `SNodeRep_*` provides the interfaces for operations like checking activation, activating/deactivating and getting a child. 
Advantages:
* `SNodeRep`s make it much easier to implement `listgen` and `struct-for` kernels fo checking activation.
* For `SNodeOpStmt`, before this PR, we had to manually figure out the memory address of the specific cell, then call the global helper function. Now that these functions are implemented inside each `rep`, we can …
> [metal] Plug in the SNodeRep structs into codegen

- docs/compilation.rst
- docs/debugging.rst
- docs/differentiable_programming.rst
- docs/export_results.rst
- docs/external.rst
- docs/faq.rst
- docs/global_settings.rst
- docs/gui.rst
In this issue, I replace **all meaningful Taichi `tensor`** by `field`in the text of our document. The involved files are all beginning with "a" to "g" as shown below:
```
acknowledgments.rst
atomic.rst
cli_utilities.rst
compilation.rst
contributor_guide.rst
cpp_style.rst
debugging.rst
dev_install.rst
differentiable_programming.rst
export_results.rst
extension_libraries.rst
external.rst
faq.rst
global_settings.rst
gui.rst
```
----
> [Doc] Replace tensor -> field for docs starting with [a-g]

- appveyor.yml
- tests/python/test_mpm88.py
See if this lets us get away with Appveyor. If not, I will skip Win entirely for this test.
Related issue = #1530
----
> [test] Skip mpm88 async on Appveyor

- docs/tensor_matrix.rst
- docs/vector.rst
This PR tries to replace `tensor` by `feld` for files beginning with `t` to `z`
----
> [Doc] Replace tensor by field for files beginning with t to z

- taichi/program/program.cpp
- taichi/runtime/llvm/internal_functions.h
- taichi/runtime/llvm/locked_task.h
- taichi/runtime/llvm/node_dynamic.h
- taichi/runtime/llvm/node_pointer.h
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/demote_dense_struct_fors.cpp
> [llvm] Fix LLVM runtime sparse computation issues

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
Related PR = #1336
----
Running on my poor Intel card:
fem99: 4.6 -> 40 (!!!!)
fem128: 18 -> 26
mpm_lagrangian_forces: 3.8 -> 15.7
misc/benchmark_reduction.py: `GL_OUT_OF_MEMORY` :(
No performance difference observed on the NV card, seems NV's compiler is already capable of doing TLS optimization for us?
(Partial) OFT:
[cli] [opengl] [metal] TI_MAKE_THREAD_LOCAL=0 to disable TLS on OpenGL/Metal.
> [OpenGL] [perf] Support TLS to improve reduction performance

- taichi/ir/ir.h
> [ir] Make sure "StmtFieldManager" to be correct if we modify some fields after the ctor

- docs/offset.rst
- docs/scalar_tensor.rst
- docs/snode.rst
- docs/syntax_sugars.rst
This PR replaced `tensor` by `field` in the following files
----
> [Doc] Replace tensor by field for files beginning with o to s

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- tests/python/test_parallel_range_for.py
----
Applying `ti.block_dim` to P2G & G2P for-loops in `mpm99.py` with `quality = 2`:
blk_dim: mesa, nvidia
128: 12.5 fps, 19.4 fps
1024: 11.1 fps, 18.9 fps
none: 10.9 fps, 18.4 fps
Very tiny performance difference that I had to run many times to confirm it...
But I guess it would be useful in some cases other than mpm, any idea?
@k-ye How does Metal decide block_dim now? Would you add `ti.block_dim` support to Metal later iapr?
> [OpenGL] [perf] Support ti.block_dim as block size hint

- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- taichi/common/core.h
- taichi/ir/expr.cpp
- taichi/python/export_lang.cpp
- tests/python/test_lexical_scope.py
Related issue = https://forum.taichi.graphics/t/runtimeerror-ir-cpp-get-attribute-293-attribute-dim-not-found/1045
The main reason for these confusing errors are originated by the fact that we use `Expr` for both local variables and global fields.
----
```py
x = 0
print(x[0])
```
Before:
`RuntimeError: [ir.cpp:get_attribute@293] Attribute dim not found`
After:
`TypeError: Cannot subscript a scalar expression`
```py
x = 0
for i in x:
```
Before:
`RuntimeError: [expr.cpp:snode@81] is<GlobalVariableExpression>()`
After:
`TypeError: can only iterate through global variables/fields`
> [Error] Improve error message when using non-global variables in global operations

- docs/debugging.rst
- misc/test_print.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel.py
- python/taichi/lang/shell.py
- taichi/python/export_misc.cpp
- taichi/python/print_buffer.h
> [IPython] 'ti.sync()' is no longer needed for 'print()' in OpenGL and Metal backend

- taichi/transforms/unreachable_code_elimination.cpp
Related issue = fix #1604 
Introduced in #1393. 
```
kernel {
$1 : if 0 {
$2 : for ... {
$3 : ...
}
}
}
```
`$2->body->parent` is `$1->body`. When flattening the if, we automatically set `$2->parent` to top-level, but not `$2->body->parent`.
If `$2->body->parent` were `$2` (a container `Stmt`), there'll be no need to call `fix_block_parents`...
----
> [Bug] [opt] Fix compiler error when flattening if(0) and if(1)

- docs/gui.rst
- examples/pbf2d.py
- python/taichi/misc/gui.py
- python/taichi/misc/util.py
----
Since some beginners may confuse `ti.vec` as an alias for `ti.Vector`... like `taichi_glsl.vec` does.
Let's rename it to `core_vec` since it's a class exported from `libtaichi_core.so`, any suggestion on the name?
Let's remove it as soon as possible before v0.7.0, since our GUI system is already wrapped by Python and able to take tuple as input.
I used the `@deprecated` mark instead of fully deprecate it because, I see some DiffTaichi examples are still using them in GUI system. @yuanming-hu Could you upgrade DiffTaichi to new syntax (including this change and others)? I found most of them are not able to run now :confused:
OFT: doc `ti.rgb_to_hex`.
> [misc] [refactor] 'ti.vec' and 'ti.veci' is deprecated, directly use a tuple in GUI system instead

- taichi/analysis/clone.cpp
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/transforms/compile_to_offloads.cpp
To avoid having to clone the offloaded task upon every kernel launch, I've cached the cloned offloaded AST as well. The cached AST, along with its hash, is put inside a struct called `OffloadedCachedData`, and is used as a *read-only* template. This optimization works because for most of the times, we are just reading the offloaded task AST without any modification.
For places that do change the AST, the clone is done via a copy-on-write way. This clone is necessary so as to keep the template untouched. Please see `KernelLaunchRecord::clone_stmt_on_write()`.
For now, we only have two places that will modify the AST:
1. The first time an AST gets compiled in `compilation_workers`. Some IR passes will modify it.
2. When two ASTs are fused.
FPS improvement:
* `mpm88`: 6 -> 11
* `mpm99`: 12 …
> [async] Clone offloaded tasks lazily by caching the AST

- docs/type.rst
Related issue = break-down #1576 depends #1585
----
> [Doc] Improve type.rst readability

- docs/gui.rst
- python/taichi/misc/gui.py
- python/taichi/misc/image.py
----
This could be useful when visualizing a vector field, particle velocities and forces.
It's completely based on `gui.lines()`, so no C++ changes involved. It's just handy for users so they don't have to hand-write that much numpy ad-hoc operations on their own.
To test:
```py
import numpy as np
gui = ti.GUI()
orig = np.array([[0.5, 0.3], [0.3, 0.8]], dtype=np.float32)
dir = np.array([[-0.1, 0.4], [0.4, -0.2]], dtype=np.float32)
while gui.running and not gui.get_event(gui.ESCAPE):
gui.arrows(orig, dir, radius=2, angle=25, tip_scale=0.4)
#gui.arrow(orig[0], dir[0], radius=2)
gui.show()
```
OFT: I assigned a default value `title='Taichi'` for `ti.GUI` since thinking about a title …
> [GUI] Support gui.arrow() and gui.arrows()

- docs/faq.rst
No related issue;
In the current stable version of the documentation, [faq.html](https://taichi.readthedocs.io/en/stable/faq.html), two external links lack the underscore so cannot display properly. See picture below:
> [doc] Fix hyperlink display issue in faq.rst

- docs/gui.rst
- docs/matrix.rst
- docs/meta.rst
- docs/scalar_tensor.rst
- docs/snode.rst
- docs/tensor_matrix.rst
- docs/vector.rst
As we suggested, this PR tries to replace `field of vector/matrix/scalar` to `vector/matrix/scalar field`. 
During the replacement, I kept the first part of phrases as singular. In another word, always write `vector field/fields` but not `vectors field/fields`.
~~It is still drafted because some of its modifications can only be done after `PR1577` and `PR1578` are merged.~~
Here is a to do list,
Looking forward to your feedback! ;-)
> [Doc] Replace fields of xxx by xxx field

- docs/snode.rst
- examples/comet.py
- examples/quadtree.py
- python/taichi/lang/__init__.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/lang/snode.py
- tests/python/bls_test_template.py
- tests/python/test_indices.py
- tests/python/test_stop_grad.py
- tests/python/test_tensor_reflection.py
> [Refactor] "x.snode()" is deprecated, use "x.snode" instead

- python/taichi/lang/__init__.py
- python/taichi/testing.py
- taichi/python/export_misc.cpp
Related issue = WeChat group
Despite we still can't catch `Segmentation Fault` as `RuntimeError` for now, it's still a good step towards compatibility :)
----
```
(catch-runtime-error-when-detect) [bate@archit taichi]$ np examples/mpm88.py         
ninja: Entering directory `build'
[1/3] cd /mnt/steam/bate/taichi/build && pyth...e/Develop/taichi/misc/generate_commit_hash.py
Building commit 10789eeef42d488d66bff85968d068144a398751
[3/3] Linking CXX shared library /home/bate/Develop/taichi/build/libtaichi_core.so
[Taichi] preparing sandbox at /tmp/taichi-zk3i964u
[Taichi] <dev mode>, llvm 10.0.0, commit 10789eee, python 3.8.3
[E 08/05/20 22:30:54.019] [export_misc.cpp:is_cuda_api_available@84] …
```
> [Misc] [bug] Catch RuntimeError when detecting backends for better compatibility

- taichi/analysis/alias_analysis.cpp
- taichi/analysis/value_diff.cpp
- taichi/ir/analysis.h
Related issue = #1558 #656 
Replaces #1627
Benchmark(#stmts): unchanged.
----
> [Opt] Improve aliasing analysis for SNodes with trailing bits

- misc/linker.map
Related issue = https://zhuanlan.zhihu.com/p/172585527
----
> [llvm] [linux] Further improve misc/linker.map to prevent segementation fault when importing in Blender

- python/taichi/lang/ops.py
- python/taichi/lang/util.py
- python/taichi/misc/util.py
----
`fully_deprecated`:
- `ti.sqr`
`deprecated`:
- `x.dim()`
- `ti.outer_product`
- `ti.dot`
- `ti.veci`
- `@ti.classfunc`
- `@ti.classkernel`
- `x.shape()` (the bracket)
- `x.dim()`
- `@ti.layout`
commented to be `deprecated`:
- `ti.var`
- `ti.Matrix.var`
- `ti.Matrix` for global matrix fields
`fully_deprecated`:
- `ti.outer_product`
- `ti.dot`
- `ti.veci`
- `@ti.classfunc`
- `@ti.classkernel`
- `x.shape()` (the bracket)
- `x.dim()`
- `@ti.layout`
- ...
`deprecated`:
- `ti.var`
- `ti.Matrix.var`
- `ti.Matrix` for global matrix fields
`fully_deprecated`:
- `ti.var`
- `ti.Matrix.var`
- `ti.Matrix` for global matrix fields
> [misc] [refactor] Add fully_deprecated mark for future use

- Dockerfile
This flag enables the CC backend. See https://github.com/taichi-dev/taichi/issues/1644#issuecomment-671194626.
----
> [docker] [cc] Turn on the C backend in the Dockerfile

- python/taichi/lang/__init__.py
Related issue = #1667
----
Before: always segf on `ti.init(arch=xxx)`.
After: only segf on `ti.init(arch=ti.opengl)`.
```
(supported-archs-delay) [bate@archit taichi]$ bld
Read prefs: /home/bate/.config/blender/2.83/config/userpref.blend
/run/user/1000/gvfs/ non-existent directory
0  meshes freed
[I 08/08/20 23:25:30.389] [shell.py:_shell_pop_print@138] Graphical python shell detected, using wrapped sys.stdout
[E 08/08/20 23:25:34.110] Received signal 11 (Segmentation fault)
***********************************
* Taichi Compiler Stack Traceback *
***********************************
/tmp/taichi-4mneuoxo/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > …
```
> [misc] Prevent 'supported_archs()' invocation in 'adaptive_arch_select()' for better compatibility

- tests/python/test_random.py
- tests/python/test_reduction.py
- tests/python/test_return.py
- tests/python/test_runtime.py
- tests/python/test_scope_errors.py
- tests/python/test_sparse_activate.py
- tests/python/test_sparse_basics.py
- tests/python/test_sparse_deactivate.py
- tests/python/test_sparse_parallel.py
- tests/python/test_static.py
- tests/python/test_stencils.py
- tests/python/test_stop_grad.py
- tests/python/test_struct.py
- tests/python/test_struct_for.py
- tests/python/test_struct_for_dynamic.py
- tests/python/test_struct_for_intermediate.py
- tests/python/test_struct_for_non_pot.py
- tests/python/test_svd.py
- tests/python/test_sync.py
- tests/python/test_syntax_errors.py
- tests/python/test_tensor_reflection.py
- tests/python/test_torch_ad.py
- tests/python/test_torch_io.py
- tests/python/test_trailing_bits.py
- tests/python/test_tuple_assign.py
- tests/python/test_types.py
- tests/python/test_unary_ops.py
- tests/python/test_while.py
Related issue = #1663 
The same as #1681 
```
import os
import re
from multiprocessing import Pool
def work_on_test(name):
cmd = f"pytest {name} 1>/tmp/{name}.log 2>/tmp/{name}.err"
print(f"[log] begin to test {name}")
ret = os.system(cmd)
if ret != 0:
print(f"[error] error when testing {name}, return {ret}")
else:
print(f"[log] testing {name} succ")
if __name__ == '__main__':
all_files = os.listdir(".")
pattern = "^test_[r-z].*py$"
target_files = [name for name in all_files if re.search(
pattern, name) is not None]
pool = Pool()
pool.map(work_on_test, target_files)
```
```
[log] begin to test test_test.py
[log] begin to test test_torch_io.py
[log] begin to test test_return.py
[log] begin to test test_ssa.py
[log] begin to test test_stop_grad.py
[log] begin to test …
```
> [test] Replace ti.var by ti.field in tests starting with r-z

- python/taichi/lang/__init__.py
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
This reverts commit 11abc8a4478d890707f925bc2ed3d427fee6b0e9.
Related issue = revert #1676
----
> [misc] Revert "[Perf] [opengl] Support 'ti.thread_dim(x)' to change invocations per thread for OpenGL (#1676)"

- tests/python/test_classfunc.py
- tests/python/test_dynamic.py
- tests/python/test_element_wise.py
- tests/python/test_fill.py
- tests/python/test_linalg.py
- tests/python/test_matrix.py
- tests/python/test_mpm88.py
- tests/python/test_ndrange.py
- tests/python/test_new_allocator.py
- tests/python/test_numpy_io.py
- tests/python/test_offset.py
- tests/python/test_print.py
- tests/python/test_ptr_assign.py
- tests/python/test_ssa.py
- tests/python/test_static.py
- tests/python/test_svd.py
- tests/python/test_tensor_reflection.py
- tests/python/test_torch_io.py
In this PR, all global fields `ti.Matrix` or possible `ti.Matrix.var` is replaced to `ti.Matrix.field` in `tests/python/*`. Local-allocated `ti.Matrix` are kept the same as before.
```
import os
import re
from multiprocessing import Pool
def work_on_test(name):
cmd = f"pytest {name} 1>/tmp/{name}.log 2>/tmp/{name}.err"
print(f"[log] begin to test {name}")
ret = os.system(cmd)
if ret != 0:
print(f"[error] error when testing {name}, return {ret}")
else:
print(f"[log] testing {name} succ")
if __name__ == '__main__':
all_files = os.listdir(".")
target_files = os.popen(
"git diff --name-only master| awk -F \"/\" '{print $3}' ").read().strip().split("\n")
pool = Pool()
pool.map(work_on_test, target_files)
```
```
[log] begin to test test_static.py
[log] testing …
```
> [test] [refactor] Replace global field ti.Matrix or ti.Matrix.var -> ti.Matrix.field in python tests

- taichi/backends/metal/api.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/platform/mac/objc_api.cpp
- taichi/platform/mac/objc_api.h
When I worked on supporting async for Metal, it has turned out that each pthread has its own `autoreleasepool`. This has caused double-free upon thread exit (we call `[obj release]` via `~nsobj_unique_ptr()`, and the pool releases it twice). So we need to retain the objects created from the obj-c runtime. However, we only need to retain the objects that are created *without `alloc`, `new` in its creation method name*. From what I understand:
1. If you create the obj-c object like `[[Foo alloc] init]`, this is like `malloc` a raw-pointer, and the caller owns this object. In this case, we do **not** need to call an additional `retain`.
2. Otherwise, if you create the object like `bar = [foo getBar]`, then before `getBar` returns, the returned object is registered into an `autoreleasepool`, …
> [mac] Add NSAutoreleasePool to manage obj-c objects' lifetime

- docs/differentiable_programming.rst
- docs/offset.rst
- docs/type.rst
- docs/write_test.rst
- examples/ad_gravity.py
- examples/odop_solar.py
- examples/simple_uv.py
- python/taichi/lang/matrix.py
- tests/python/test_ad_basics.py
- tests/python/test_bitmasked.py
- tests/python/test_element_wise.py
----
Now `clear;grep -r ti\\.\\\(Matrix\\\|Vector\\\)\(\[0-9\];grep -r ti.\*\\.var\\\>`:
```
examples/tree_gravity.py:    display_image = ti.Vector(3, ti.f32, (kResolution, kResolution))
examples/export_ply.py:pos = ti.Vector(3, dt=ti.f32, shape=(10, 10, 10))
examples/export_ply.py:rgba = ti.Vector(4, dt=ti.f32, shape=(10, 10, 10))
examples/pbf2d.py:board_states = ti.Vector(2, dt=ti.f32)
examples/euler.py:Q = ti.Vector(4, dt=real,
examples/euler.py:Q_old = ti.Vector(4, dt=real, shape=(N, N))
examples/euler.py:W = ti.Vector(4, dt=real, shape=(N, N))  # [rho, u, v, p] cell avg
examples/euler.py:W_xl = ti.Vector(4, dt=real, shape=(N, N, 3))  # left side of x-face
examples/euler.py:W_xr = ti.Vector(4, …
```
> [refactor] Fix missed ti.var -> ti.field refactors in codebase

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/program/program.cpp
This allows us to decouple the return value from `Context`.
----
> [metal] Pass back return values via result_buffer

- examples/stable_fluid.py
Related issue = [数据删除]
----
The `pressure_jacobi` is highly memory-bound.
So I fuse two `pressure_jacobi` into one, resulting in 2x performance (FPS didn't change without `p_jacobi_iters //= 2`).
However, fusing 3 or 4 stencils did't yield anymore performance since it's becoming compute-bound, at lest on my end.
Not sure if we could provide an option to switch to `from mgpcg_advanced import MGPCG` iapr.
@KLozes Would you mind to make the cool `MGPCG` class more generic so that people could reuse it when necessary?
> [example] Make jacobi iteration 2x faster in stable_fluid.py

- examples/cornell_box.py
- examples/euler.py
- examples/export_ply.py
- examples/particle_renderer.py
- examples/pbf2d.py
- examples/quadtree.py
- examples/sdf2d.py
- examples/sdf_renderer.py
- examples/tree_gravity.py
This PR tries to replace all global field(tensor) `ti.Vector` to `ti.Vector.field`
1. Script testing is the same as #1712 
2. Then I watched the examples' result and played with them manually. They look good to me.
----
> [example] [refactor] Replace global field ti.Vector -> ti.Vector.field in examples

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
----
Local OpenGL test passed. Will merge once CI passed.
> [opengl] Cache GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS value to prevent glGetInteger per-launch

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/program/program.cpp
Related issue = #1722
----
@k-ye Is this what you want? Note that I don't make a `GLBufId::Resu` but still reusing `GLBufId::Args` is because some OpenGL 'implementations' have **limited number of SSBOs**, the limit is 8 on @Eydcao's machine for example. Not to say we need `args_i32` and `args_f32` for simulating union. Not to say my ultra-secret [数据删除] project with @yuanming-hu. We actually can't turn on all 7 SSBOs at the same time on these machines at all.
> [opengl] [refactor] Use result_buffer for return value

- python/taichi/lang/kernel.py
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- taichi/transforms/constant_fold.cpp
This is just a wrapper of of the singleton context owned by the program. However, hopefully it outlines the interface we need to resolve #1722?
I found that the generated function on CUDA has to further modify `Context`, since it has to create the host/device buffers. The manipulation there seems a bit brittle 😨 
Related issue = #1722
----
> [refactor] Add Kernel::LaunchContextBuilder skeleton code

- examples/waterwave.py
- misc/prtags.json
Related issue = https://github.com/taichi-dev/taichi/issues/1483#issuecomment-674958231
----
@EaryChow Does removing `exit()` fix the issue?
In fact, simply
```py
exit()
```
can cause Blender to crash.. see https://developer.blender.org/T44127.
> [blender] [example] Fix examples/waterwave.py memory leakage in Blender

- examples/mass_spring_3d.py
Related issue = https://github.com/taichi-dev/taichi_three
----
Thank @victoriacity and @DSaurus for their contribution, we can now control the camera in better ways in Taichi THREE:
1. LMB for orbiting the target.
2. RMB or mouse wheel for scaling distance to target.
3. MMB for moving target position.
Since API breaking change is made in v0.0.2 -> v0.0.3, so I'd like to update the mass_spring_3d.py in Taichi main repo too.
> [Example] Upgrade mass_spring_3d.py to Taichi THREE v0.0.3 API

- taichi/analysis/same_statements.cpp
- taichi/ir/analysis.h
- taichi/ir/control_flow_graph.cpp
Related issue = #1741 #1248 
Store-to-load forwarding needs to check if two statements (must) have the same value. `same_statements` may be incorrect when there are two statements loading the same `alloca`.
`value_diff` can do a better job than `same_value`, but it's too expensive (slow) for this usage, and I think `same_value` is enough if other optimizations like constant folding are done.
TODO: rename `common_statement_eliminable`.
----
> [opt] Add irpass::analysis::same_value

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/misc/util.py
----
Thanks for the extraordinary works of @Rullec, we can finally officially announce the deprecation.
@yuanming-hu We need you insight about whether to:
1. obsolete `ti.var` after v0.7.0
2. deprecate `ti.var` with an warning after v0.7.0
> [Refactor] [lang] 'ti.var' is deprecated, use 'ti.field' instead

- python/taichi/lang/kernel.py
Related issue = #677
----
After this calling `ti.classfunc` will result in an error.
> [Refactor] @ti.classfunc and @ti.classkernel are obsolete. Directly use @ti.func and @ti.kernel instead

- benchmarks/async_cases.py
- python/taichi/lang/__init__.py
- taichi/program/async_engine.cpp
- taichi/program/kernel.cpp
`after_lower_access=false` allows `cfg_optimization` to optimize for global variables.
Also removes evaluators and accessors from #kernel_launches in the statistics.
Also adds `ti.sync()` after each run when benchmarking, and adjust the `repeat` parameters in `async_cases` accordingly.
----
> [async] [benchmark] Enable optimization for global variables after fusion

- taichi/backends/metal/struct_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/struct_opengl.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/1678#issuecomment-680824646
----
> [error] [opengl] Better error message when int64 or sparse SNode not supported for OpenGL

- taichi/ir/control_flow_graph.cpp
Removes the warning introduced in #1741.
Benchmark (#statements): unchanged.
----
> [opt] Simplify identical load elimination

- python/taichi/testing.py
Related issue = Close #1679 
As @archibate adviced, I expand the approx value on metal platform.
Now `test_ad_basic.py` can work properly on my machine! 
----
> [test] Expand the tolerance for testing on metal backend

- examples/mpm3d.py
- examples/stable_fluid.py
Related issue = close #1757 replace #1764 break_down #1691
----
> [Example] Fix stable_fluid.py boundary broken: int -> ti.floor, and make mpm3d.py 3x faster on CUDA

- Dockerfile
- cmake/PythonNumpyPybind11.cmake
- taichi/transforms/auto_diff.cpp
Related issue = close #1781
----
> [ir] [autodiff] Initialize ADStack with a zero

- taichi/backends/cuda/jit_cuda.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/program/async_engine.h
- taichi/program/context.h
- taichi/program/program.h
- taichi/runtime/llvm/mem_request.h
- taichi/runtime/llvm/runtime.cpp
- taichi/system/memory_pool.h
> [refactor] Move Context to taichi/program

- python/taichi/testing.py
- tests/python/test_test.py
It turns out that #1779 doesn't play well on my device. Adding this to make the `allclose` tests pass again on Metal.
Related issue = #1779
----
> [Lang] [test] Add ti.get_rel_eps() for maximal relative error tolerance on current backend

- taichi/analysis/verify.cpp
(Possibly a bug in async?)
----
> [ir] Restore verification for OffloadedStmt

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/transforms/constant_fold.cpp
Finally..
Related issue = #1739
----
> [refactor] Remove the singleton Program::context

- python/taichi/diagnose.py
Related issue = closes #1792
----
This PR adds Python executable path to `ti diagnose`, as mention in #1792.
There is another change: I found that running `ti diagnose` in development mode will cause syntax errors on macOS because `python` still refers to Python 2.7.16, and current executable will always be the correct one with Taichi installed. So I replaced `'python'` with the executable path.
> [cli] Add path to Python executable to 'ti diagnose'

- python/taichi/code_format.py
----
In code_format.py, `sys` is used but not imported. This PR aims to fix this. The error happens when clang-format executable is not found.
https://github.com/taichi-dev/taichi/blob/1662fc52fa5eadeac1abd46e52f1303f6aa11e36/python/taichi/code_format.py#L50-L55
> [workflow] Import missing package sys in code_format.py

- python/taichi/lang/impl.py
- python/taichi/lang/ops.py
- taichi/python/export_lang.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_print.py
Related issue = #1787
----
The elements of list can be either `Expr`, `Matrix`, nested `list`, or any constant types.
This allows us to directly print `x.shape` in #1787.
> [Lang] Support printing lists and tuples in Taichi-scope

- docs/dev_install.rst
🙋‍♂️ Hi, I'm a [fish](https://fishshell.com/) user and encountered a small problem when I was adding environment variables. So I added this part to the documentation. Hope it helps other fish users.
> [Doc] Add how to set environment variables for fish users

- docs/arithmetics.rst
- docs/vector.rst
- python/taichi/lang/common_ops.py
- python/taichi/lang/impl.py
- python/taichi/lang/transformer.py
Related issue = #1064
----
Before:
```
File "a.py", line 11, in <module>
func()
File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 574, in wrapped
return primal(*args, **kwargs)
File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 501, in __call__
File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 370, in materialize
taichi_kernel = taichi_kernel.define(taichi_ast_generator)
File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 367, in taichi_ast_generator
compiled()
File "a.py", line 7, in func
if x == 0:
File …
```
> [error] Better error message when vector used as if's condition variable

- docs/arithmetics.rst
- docs/vector.rst
- python/taichi/lang/common_ops.py
- python/taichi/lang/impl.py
- python/taichi/lang/transformer.py
Reverts taichi-dev/taichi#1804.
I opened #1809 to prevent similar issues from happening again :-)
> [misc] Revert "Better error message when vector used as if's condition variable" (#1804)

- python/taichi/lang/impl.py
- python/taichi/lang/transformer.py
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_assert.py
This allows us to write 
```py
assert cond(), 'foo=%d bar=%f' % (foo, bar)
``` 
I think we can apply the same strategy to `print`, but let me focus on `assert` in this PR.
Related issue = #1434
----
> [Lang] Support formatted string with args in assert

- taichi/analysis/clone.cpp
> [ir] Fix irpass::analysis::clone on TLS/BLS prologue/epilogue

- taichi/transforms/simplify.cpp
> [misc] Remove unused code/comments in transforms/simpilfy.cpp

- python/taichi/lang/__init__.py
- taichi/program/kernel.cpp
Will rename `KernelLaunchRecord` separately to avoid conflict with #1815 ...
----
> [refactor] Rename 'launched_kernels*' stats to 'launched_tasks*'

- taichi/ir/frontend.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
* constructor args order will be `(cond, msg, args)`
* renamed `val` to `cond` for consistency
Related issue = #1434
----
> [ir] [refactor] Reorder FrontAssertStatement's constructor args

- python/taichi/lang/kernel.py
- tests/python/test_classfunc.py
- tests/python/test_complex_kernels.py
- tests/python/test_mpm_particle_list.py
- tests/python/test_oop.py
- tests/python/test_ptr_assign.py
----
As @yuanming-hu said in his final lecture in GAMES 201, *simplicity matters*.
I noticed that our ODOP implementation is getting too complicated that developers can hardly maintain them.
Although not found in Python Zen, I think I will add *serialized is better than parallelized* and *don't put things too tight together*.
Currently `is_classfunc` is embed into `Kernel` and `Func`, which is lossening the focus IMO.
The module `re` is actually completely unrelated to the rest part of `kernel.py`, but linked by our ODOP implementation.
I'm thinking if it's possible to move that outside of `Kernel` and `Func`, or even implement class inspection via an external package?
So I'd like to remove these codes …
> [refactor] Drop ODOP support temporary (rullecized)

- python/taichi/misc/gui.py
- taichi/gui/gui.h
- taichi/gui/win32.cpp
- taichi/gui/x11.cpp
- taichi/python/export_visual.cpp
- tests/python/test_gui.py
Fixes #1616. cc @archibate @yuanming-hu.
As mentioned in #1616 by @ehannigan, saving the screenshot of a GUI without an actual window will throw 
`"RuntimeError: [x11.cpp:create_window@139] Taichi fails to create a window. This is probably due to the lack of an X11 GUI environment. If you are using ssh, try ssh -XY."`
It is possible to do this with `matplotlib` however it would be better to have a native solution. This PR provides the functionality to save an image without showing a GUI as well as correcting instances of `idendity`.
1. Since I'm putting a `if` statement around `self.core.update()`, is it a concern that the internal `GUI` class has a different state from `ti.GUI` class?
Original version is shown here: https://github.com/taichi-dev/taichi/blob/6052a541bed7e2645110f21379a7266 …
> [GUI] Support saving image without GUI showing a window

- misc/visualize_state_flow_graph.py
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.h
- taichi/program/program.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
Running `misc/visualize_state_flow_graph.py` gives you
```
=== State Flow Graph ===
Node initial_state 0x561f94a55de0
Outputs:
S3place_i32_value: node foo_c4_0 @ 0x561f94aee000
Node foo_c4_0 0x561f94aedf40
Node foo_c4_0 0x561f94e94e70
Node foo_c4_0 0x561f94efb920
Node foo_c4_0 0x561f94c6dff0
Node foo_c4_0 0x561f94aee000
Inputs:
S3place_i32_value: node initial_state @ 0x561f94a55de0
Outputs:
S4place_i32_value: node bar_c6_0 @ 0x561f94c68900
Node foo_c4_0 0x561f94e354e0
Node foo_c4_0 0x561f94e53bf0
Node foo_c4_0 0x561f94aaf160
Node foo_c4_0 0x561f94e0cd50
Node bar_c6_0 0x561f94c68900
Inputs:
S4place_i32_value: node foo_c4_0 @ 0x561f94aee000
=======================
```
Note that we support value state for now. The nodes without any input/output states are clear list/list …
> [async] Implement basic StateFlowGraph

- python/taichi/lang/matrix.py
- tests/python/test_matrix.py
Related issue = #1188
----
Before this, the following code will result in a confusing error:
```py
a = ti.Vector.field(2, float, ())
a[None] = [2, 3]             # OK
a[None] = ti.Vector([2, 3])  # ERROR
```
```
[Taichi] preparing sandbox at /tmp/taichi-51ftg4mj
[Taichi] <dev mode>, llvm 10.0.0, commit 41708c5e, linux, python 3.8.3
[Taichi] materializing...
File "a.py", line 6, in <module>
a[None] = ti.Vector([2, 3])  # ERROR
File "/home/bate/Develop/taichi/python/taichi/lang/util.py", line 212, in wrapped
return func(*args, **kwargs)
File "/home/bate/Develop/taichi/python/taichi/lang/matrix.py", line 400, in __setitem__
item = [[i] for i …
```
> [Lang] Support __len__ and __iter__ on ti.Matrix

- .github/workflows/persubmit.yml
- misc/ci_check_previous_run.py
- taichi/transforms/lower_ast.cpp
Test test test
---
Adds a `check_previous_run` job to our presubmit workflow, so that when `skip ci` is enabled, the job will use the previous workflow run status. If the previous run hasn't finished, this job will poll the status every 15s, with a deadline of 1 hour.
The idea is described in https://github.com/taichi-dev/taichi/issues/1809#issuecomment-686538091. Basically:
1. Find the previous commit of this one in the current PR
2. Find the workflow run corresponding to the previous commit
3. Check the status of the run.
**Future TODOs**
* Now that we have the workflow run ID of the previous commit, we can actually instruct to cancel the run ([`cancel` doc](https://docs.github.com/en/rest/reference/actions#cancel-a-workflow-run)).
* Unfortunately, `[skip ci]` in the commit message is …
> [misc] Check the previous Github workflow run status if CI is skipped

- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/transformer.py
- taichi/ir/frontend_ir.h
- taichi/ir/ir.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/type_check.cpp
Because we know the kernel args and return types when constructing these arg load/kernel return stmts, we don't have to re-infer them inside `type_check()`. This PR removes the necessity of kernel in `type_check` (config is still not handled), so that IR is a bit more decoupled from Kernel.
Related issue = #689
----
> [ir] Remove the usage of kernel from type_check() pass

- .github/workflows/persubmit.yml
- misc/ci_check_previous_run.py
- taichi/program/program.cpp
* For authenticated requests on Github Actions, its rate limit is 1000 per hour: https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits
* Slowed down the periodical poll from 15s to 1min.
Intentionally mess up the cpp code to make taichi-gardener work.
Related issue = https://github.com/taichi-dev/taichi/pull/1844#issuecomment-687720574, #1837 
----
> [misc] Fix check previous run by using GITHUB_TOKEN to authenticate APIs

- misc/visualize_state_flow_graph.py
- python/taichi/misc/util.py
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
* The initial node is drawn as a box
* The latest state owners are drawn with double edges
Generated DOT graph for `misc/visualize_state_flow_graph.py`:
```
digraph {
n_initial_state_0 [label="[node: initial_state:0]",shape=box]
n_foo_c4_0_clear_list_0 [label="[node: foo_c4_0_clear_list:0]"]
n_foo_c4_0_listgen_0 [label="[node: foo_c4_0_listgen:0]"]
n_foo_c4_0_clear_list_1 [label="[node: foo_c4_0_clear_list:1]"]
n_foo_c4_0_listgen_1 [label="[node: foo_c4_0_listgen:1]"]
n_foo_c4_0_struct_for_0 [label="[node: foo_c4_0_struct_for:0]",peripheries=2]
n_foo_c4_0_clear_list_2 [label="[node: foo_c4_0_clear_list:2]"]
n_foo_c4_0_listgen_2 [label="[node: foo_c4_0_listgen:2]",peripheries=2]
n_foo_c4_0_clear_list_3 [label="[node: foo_c4_0_clear_list:3]"]
n_foo_c4_0_listgen_3 [label="[node: …
```
> [async] Generate DOT graph for StateFlowGraph

- python/taichi/lang/transformer.py
- tests/python/test_syntax_errors.py
Related issue = fix #1840
----
```py
ti.init(print_preprocessed=True)
@ti.func
def sign(x):
if x > 0:
return 1
else:
return -1
@ti.kernel
def main():
print(sign(-1))
main()
```
obtains:
```
(err-multiple-return) [bate@archit taichi]$ p a.py
[Taichi] preparing sandbox at /tmp/taichi-8c3ueytb
[Taichi] <dev mode>, llvm 10.0.0, commit 09d665f9, linux, python 3.8.3
[Taichi] Starting on arch=x64
[Taichi] materializing...
Initial AST:
def main():
print(sign(-1))
Preprocessed:
def main():
ti.ti_print(sign(-1))
Checked:
def main():
ti.ti_print(sign(-1))
Final AST:
def main():
ti.ti_print(sign(-1))
Initial AST:
def sign(x): …
```
> [Error] Raise TaichiSyntaxError when multiple return path detected

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
The only real change in this PR is to add `TaskLaunchRecord StateFlowGraph::Node::rec` and pass it into `sfg` in `AsyncEngine::enqueue(const TaskLaunchRecord &t)`.
In order to do this, I moved `IRHandle` and `TaskLaunchRecord` to `async_utils.h`.
----
> [async] Add TaskLaunchRecord StateFlowGraph::Node::rec

- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
This was https://bugs.llvm.org/show_bug.cgi?id=16747#c1
---
It seems like `std::unordered_multimap`, introduced in #1843, was way slower than expected, and became a major bottleneck in SFG (at least with clang's libc++ impl..). Profiling showed that ~74% of the time was spent here:
This PR switches to `std::unordered_map<AsyncState, std::unordered_set<Node*>>`, which restores the performance to its prior level on my device.
Off-the-topic change: since I removed `print_edges()`, I used `<-` when printing input nodes...
Related issue = #1843 
----
> [async] Stop using std::unordered_multimap as node edges type

- examples/mpm3d.py
- python/taichi/lang/impl.py
- tests/python/test_lang.py
- tests/python/test_reduction.py
Related issue = http://www.jlhub.com/julia/manual/en/function/zero
----
Yeah it's still using `x * 0` since we seems can't get the data type of an expr from python-scope.. maybe iapr, let's set up the API here imutating the Julia zero/one.
> [Lang] Support ti.zero(x) and ti.one(x) for making zero/one value for the same type with x

- .github/workflows/persubmit.yml
- misc/ci_setup.py
> [Workflow] Build and test the CUDA backend using GitHub actions

- python/taichi/misc/util.py
- taichi/program/async_engine.cpp
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
Example:
I'll look into more on how we can better represent the nodes/edges..
Related issue = #1855
----
> [async] Highlight user kernels in the DOT graph, allows configuring rankdir

- misc/visualize_state_flow_graph.py
- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
Changes:
1. Let `StateFlowGraph::replace_reference` also replace input edges by default
1. Fix `StateFlowGraph::topo_sort_nodes` not considering nodes without an edge from the initial node
1. Rebuild SFG after each call of `fuse()` if at least one pair of nodes is fused
1. Extract `StateFlowGraph::compute_transitive_closure()` from `StateFlowGraph::fuse()`
1. Use `compute_transitive_closure` to test if there is a path `node_a->node_c->node_b` in `StateFlowGraph::optimize_listgen()` (commented out)
1. Add `StateFlowGraph::verify()`
----
> [async] Improve fusion optimization and add StateFlowGraph::verify

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
Move a part of `StateFlowGraph::fuse()::do_fuse()` to `IRBank::fuse()`.
----
> [async] Cache fusion results

- python/taichi/misc/util.py
- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
Sorry to put additional burdens on you guys...  Thought you preferred the rectangular shape a bit more. I also allowed states to be embedded into the nodes, if the number of states is below a certain threshold (default to `0`).
* fusion_0000_initial
* fusion_0000_initial embedded
* fusion_0003_dse
* fusion_0003_dse embedded
----
> [async] Draw nodes as record shape, allow embedding states into nodes

- taichi/lang_util.cpp
- taichi/lang_util.h
Related issue = #1750
Hi, I tried refactoring function promoted_type by creating a class named TypePromotionMapping and use a global variable for initializing the type map. But I am not sure whether it is good method. Should I use a singleton mode？
> [refactor] Create class TypePromotionMapping for refactoring function promoted_type in lang_util.cpp

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/program/async_engine.cpp
- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
Changes: 
- Add `std::unordered_map<SNode *, bool> TaskMeta::element_wise`
- Refactor `AsyncStateHash` into `std::hash<AsyncState>` because I think we don't need other hashes of `AsyncState`
- Fix typo "fusable" -> "fusible"
Question:
- How does the element-wise info affect mask/list states?
----
> [async] Add element-wise info into TaskMeta for fusion

- misc/async_mgpcg.py
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/util/bit.cpp
- taichi/util/bit.h
Benchmark: async_mgpcg.py, `taichi::lang::StateFlowGraph::fuse`:
Before: `2.815  s`
At commit 691f706: `520.011 ms`
At commit 3c78343: `332.199 ms`
At commit 42da16c: `283.921 ms`
At commit 366af3d (buggy): `197.838 ms`
At commit 826d053: `241.768 ms`
After (at commit 6e6892f): `152.634 ms`
On kun: ~1.03s -> ~97ms (10.6x faster)
The following statistics may change even at the same commit...
Without fusion:
```
codegen_accessor_statements: 20.00
codegen_evaluator_statements: 79.00
codegen_kernel_statements: 4224.00
codegen_offloaded_tasks: 117.00
codegen_statements  : 4323.00
launched_tasks      : 5034.00
launched_tasks_compute: 4990.00
launched_tasks_list_gen: 44.00
launched_tasks_list_op: 44.00
launched_tasks_range_for: 1.00
launched_tasks_serial: 106.00 …
```
> [async] Classify tasks to make fusion 10.6x faster

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
This is to implement https://github.com/taichi-dev/taichi/pull/1888#pullrequestreview-494761275
Since each pass (stage) could run multiple times, I tweaked the debug filename a bit. It now looks like
`{prefix}_sync{04:d, sync_count}_{04:d, cur_sync_debugs_count}_{stage}{stage_count}?`
E.g.
```
foo_sync0001_0000_initial
foo_sync0001_0001_listgen
foo_sync0001_0002_fuse
foo_sync0001_0003_fuse1
foo_sync0001_0004_final
```
This way it's easier for us to see which graphs belong to the same sync...
----
> [async] Make optimization passes iterative

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
(Not sure if it's better to move `IRBank` to a separate file... This class is handling more and more stuff.)
----
> [async] Cache demote_activation

- python/taichi/misc/util.py
- taichi/python/export_misc.cpp
- taichi/util/statistics.cpp
- taichi/util/statistics.h
- tests/python/test_sfg.py
This allows us to ensure fusion does work and to detect possible regressions...
As a slightly off-the-topic change, i changed the tests to use `ti.pointer.dense.place()` as suggested in https://github.com/taichi-dev/taichi/pull/1888#discussion_r493668443. `dense(1)` is still pointless, but it eases the activated index computation.
----
> [misc] Expose kernel statistics to python

- misc/async_mgpcg.py
- taichi/backends/cuda/cuda_context.cpp
- taichi/program/async_engine.cpp
- taichi/program/async_utils.cpp
- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
- taichi/program/state_flow_graph.cpp
`StateFlowGraph::optimize_listgen` now does more job each iteration. Previously it very conservatively `break`s after modifying a single SFG node. This change also seems to eliminate more `ClearListStmt` for some reason. After this change `optimize_listgen` is ~2x faster on mgpcg.
Offtopic change: the CUDA profiler now returns a handle when calling `start_with_handle()`. We need the handle (which is essentially a CUDA event pointer) to mark the end of a kernel launch.
----
> [async] Optimize StateFlowGraph::optimize_listgen

- taichi/program/state_flow_graph.cpp
No point doing DFS if simply iterating over `nodes_` can get the work done..
----
> [refactor] Remove DFS in DOT generation

- .github/workflows/persubmit.yml
- misc/ci_check_previous_run.py
- taichi/backends/metal/data_types.cpp
When the previous CI run's code format check fails, two thing happens:
1. @taichi-gardener will do a `[skip ci] enforce code format` to automatically correct the things
2. The second commit would still fail because it runs "Check the previous CI workflow" job, which finds that the previous workflow... has failed --> this time it fails again :-/
"Persubmit Checks / Code Format (pull_request)" is triggered unconditionally now, because it is a required check. (Previously it is disabled for @taichi-gardener 's commits)
Related issue = #1809
----
> [misc] Make check previous CI run only check for Build-and-Test jobs

- python/taichi/lang/shell.py
- python/taichi/misc/gui.py
- taichi/gui/win32.cpp
----
Otherwise window doesn't get closed after the script execution in sth like Jupyter or Blender (TODO: confirm if this work)
> [gui] [ipython] Add GUI.__del__ to close on variable dereference

- docs/export_kernels.rst
- docs/install.rst
- python/taichi/cc_compose.py
- python/taichi/core/record.py
- taichi/python/export_lang.cpp
Related issue = #394
----
This would allows user to specify configuration direct-in-place in Python.
I need this for TaichiHub, an online playground, for customizable particle numbers & screen size.
Please merge this soon, idealy before next release.
> [export] Support exporting custom config variables

- examples/stable_fluid.py
Related issue = #1757 
In this PR I plan to fix the BFECC advection in `stable_fluid.py`. Seems that there are several problems tangled inside this one. So let's try to solve them one-by-one. I may need your @yuanming-hu  and @archibate help to review if the errors are from the BFECC or the PPE solving. Thanks a lot,
----
> [bug] Fix stable fluid BFECC advection

- python/taichi/lang/__init__.py
- python/taichi/lang/meta.py
Let me submit this part first. With this simple tweak MPM lagrangian force on my end already runs from 15fps to 24fps...
----
> [perf] Wrap clear loss/grad into a kernel

- docs/arithmetics.rst
- docs/write_test.rst
Related issue = #1816 
Modified  one "atan2(x, y)" in "docs/arithmetics.rst" and four "atan2(x, y)" in "docs/write_test.rst"
> [doc] Use "atan2(y, x)" instead of "atan2(x, y)" (#1816)

- examples/mpm_lagrangian_forces.py
Hopefully this simplifies benchmarking #1907 (I used `quality=16`)
----
> [example] Update mpm_lagrangian_forces.py

- examples/cornell_box.py
[fix]
fix rounding error artifact for cornell_box
----
> [Example] Fix rounding error for cornell_box.py

- appveyor.yml
- taichi/ir/control_flow_graph.cpp
- taichi/ir/control_flow_graph.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/ir/transforms.h
- taichi/program/async_utils.cpp
- taichi/program/ir_bank.cpp
- taichi/program/ir_bank.h
- taichi/program/state_flow_graph.cpp
- taichi/transforms/cfg_optimization.cpp
- tests/python/test_sfg.py
Sorry for this large change. It shouldn't be as complicated as the size implies.. The approach is basically to find out those **scalar** SNodes whose values are not read by the successor tasks. We then pass in these SNodes to the CFG pass, and instruct the live variable analysis **not to** add them into the final node's `live_gen`.
There are a few special handlings for scalar SNodes here:
1. Upon seeing a `GlobalStoreStmt` when constructing the task meta, we add the SNode to the input (reader) states, iff. it is *not* a scalar. https://github.com/taichi-dev/taichi/blob/3aeff7c01f1dff6def9602b7f4a0005fc54b4c22/taichi/program/async_utils.cpp#L127-L130
1. In `SFG::optimize_dead_store()`, if the state forms a flow edge, we also check if it's a scalar and if the successor task actually reads …
> [async] Support SFG-level DSE for scalar SNodes

- python/taichi/lang/impl.py
- tests/python/test_runtime.py
Related issue = https://github.com/taichi-dev/taichi_three
----
This would allow extension libraries initialize a field on declaration. For example, I have a `Camera` class, I want to initialize the transform matrix with identity matrix by default.
> [Lang] Add @ti.materialize_callback for functions to be called right after root materialization

- docs/gui.rst
The current description of parameter pos in gui.text doesn't explicitly show it's intended value range. 
Same issue exists for other objects. I can make a through chk and update if you think the change is valuable.
Thank you!
----
> [Doc] Improve description of the pos parameter in gui

- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
This PR keeps the latest state writers/readers in the SFG when all nodes are extracted to execute.
Most functions of the SFG need to be modified. This PR modifies
This PR doesn't modify
- print()
- dump_dot()
These functions don't need to be modified:
- demote_activation()
----
This PR also tried to modify `fuse()` so that only tasks that are "near" in the topological order (i.e., position in `nodes_` differ by `< 512`) are fused. This improves the complexity of a single invocation of `fuse()` from O(nm/64) to O(min(n, 512*4)*m/64 + nm/512)...
Benchmark: async_mgpcg.py, time of `fuse()` on kun: 0.746s (0.355s unaccounted) -> 1.334s (0.800s rebuild graph, 0.559s insert task)
(2.760s at commit c691248, 1.387s at commit da2a0f2 (0.920s rebuild graph), 1.243s at commit …
> [async] Partial SFG node GC (keep latest state writers/readers)

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/codegen_metal.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/extension.cpp
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- tests/python/test_fuse_dense.py
- tests/python/test_fuse_dynamic.py
- tests/python/test_sfg.py
Added `Program::compile_to_backend_executable()` to dispatch to each backend's codegen, so that it can be shared between sync/async mode.
While we should only benchmark on CUDA, let me include Metal so that I get a sense of what the performance looks like...
----
> [async] [metal] Support async mode on Metal

- taichi/lang_util.cpp
Related issue = #1871 
`binary_op_type_symbol` is used when printing initial (frontend) IR, and an IR with `bit_shr` will crash if that case is not supported :-)
----
> [ir] Add the case of bit_shr to binary_op_type_symbol

- taichi/analysis/cfg_analysis.cpp
- taichi/ir/analysis.h
- taichi/ir/control_flow_graph.cpp
- taichi/ir/control_flow_graph.h
- taichi/program/async_utils.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- tests/python/test_sfg.py
Changes:
- Analyze (with control flow graph) exactly which `SNode`s' original values before the `OffloadedStmt` are read inside the `OffloadedStmt`, and which `GlobalPtrStmt`s' original value is still reachable at the end of the `OffloadedStmt`. These two cases, together with `SNode`s that are not element-wise written, should be the set of input value states in the `TaskMeta`.
- If the above analysis is accurate, RAW should be the only flow edge -- WAW becomes a dependency edge.
- Fix a bug that broke state-flow chains.
----
> [async] [opt] Field value killing analysis

- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
According to #1927, `llvm::SmallVector<llvm::SmallSet>` seems to be the most performant.
Here's the profiling data for `async_mgpcg.py`:
* Before this change: `13.418 s + 18.605 s + 20.120 s`
```
54.404  s synchronize                   [8 x   6.800  s]
11.333  s 20.83%  optimize_listgen      [75 x 151.111 ms]
... ...
8.523  s 75.21%  rebuild_graph         [44 x 193.713 ms]
6.988  s 81.98%  insert_task           [397621 x  17.574 us]
0.180  s  2.57%  get_task_meta         [397621 x 451.757 ns]
2.874  s 41.14%  insert_task meta->input_states [1149493 x   2.501 us]
2.069  s 71.96%  insert_edge           [1149493 x   1.800 us]
0.806  s 28.04%  [unaccounted]
2.053  s 29.38%  insert_task meta->output_states [409654 x   5.011 us]
1.286  s 62.63%  insert_edge           [1063555 x   1.209 us] …
```
> [async] Switch to llvm::SmallVector<llvm::SmallSet> for edges

- tests/cpp/benchmark_sfg_edges.cpp
This adds the benchmark for five kind of map implementations:
```cpp
using UnorderedMapSet = std::unordered_map<int, std::unordered_set<int>>;
using LLVMVecSet = llvm::SmallVector<std::pair<int, llvm::SmallSet<int, 4>>, 4>;
using LLVMVecVec =
llvm::SmallVector<std::pair<int, llvm::SmallVector<int, 4>>, 4>;
using StlVecSet = std::vector<std::pair<int, std::unordered_set<int>>>;
using StlVecVec = std::vector<std::pair<int, std::vector<int>>>;
```
The test data might not be very representative of the actual use pattern, but it seems to indicate that `llvm::SmallVector<std::pair<Key, llvm::SmallSet<Value>>` is a pretty decent data structure? (I'm too lazy to implement the sorted `Vector<std::pair<Key, Value>>`. That data structure would require us to sort it for every single insert, otherwise …
> [test] Add a benchmark for SFG edges' two-level map

- README.md
- examples/ad_gravity.py
> [misc] Add a link to TaichiHub playground in README.md

- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/program/program.cpp
- taichi/program/program.h
> [type] Initial TypeFactory class

- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/transforms/make_block_local.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/test_alg_simp.cpp
- tests/cpp/test_same_statements.cpp
Making way for the real `VectorType` in the new type system.
----
> [refactor] VectorType -> LegacyVectorType

- taichi/program/state_flow_graph.cpp
There can be thousands of tasks reading a state.
IIRC we don't need the latest state readers in any of the SFG optimizations?
----
> [async] Do not keep latest state readers in SFG

- python/taichi/lang/expr.py
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/lang_util.cpp
----
To reproduce:
```py
import numpy as np
ti.init(print_preprocessed=True)
@ti.kernel
def func(b: ti.ext_arr()):
b.shape[0] + 4
func(np.array([1, 2]))
```
```py
[Taichi] mode=release
[Taichi] version 0.6.39, llvm 10.0.0, commit 12e02bec, win, python 3.8.5
[Taichi] Starting on arch=x64
[Taichi] materializing...
Initial AST:
def func(b: ti.ext_arr()):
b.shape[0] + 4
Preprocessed:
def func():
b = ti.decl_ext_arr_arg(ti.i32, 1)
ti.subscript(b.shape, 0) + 4
Checked:
def func():
b = ti.decl_ext_arr_arg(ti.i32, 1)
ti.subscript(b.shape, 0) + 4
Final AST:
def func():
b = ti.decl_ext_arr_arg(ti.i32, 1)
ti.subscript(b.shape, 0) + 4 …
```
> [Bug] [lang] "ext_arr.shape" should return "ti.Expr" instead of "ti.core.Expr"

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/lang_util.h
Changes:
- Added basic `VectorType` and `PointerType`
- Updated `TypeFactor` to support creating the two new types
- Removed `using namespace llvm` in `codegen_llvm.h` since now `taichi::lang::PointerType` conflicts with `llvm::PointerType`. Added some necessary `llvm::` prefixes to fix compilation.
- Moved `Stmt::is_ptr` to `ArgLoadStmt::is_ptr` since that's the only subclass that uses the member.
- Moved `Type-`related classes from `taichi/lang_util.h/cpp` to `taichi/ir/type.h/cpp`
----
> [type] Add basic implementations of VectorType and PointerType

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
* `range_for`: this defaults to 128 because of (`default_block_dim = 128` for GPU):
https://github.com/taichi-dev/taichi/blob/1b024a08027e5852c14390e512e69584586f8eb5/taichi/transforms/offload.cpp#L62
* `struct_for`: this defaults to `0` (`max_block_dim = 0`), so Metal picks the maximum threads per threadgroup allowed per kernel.
https://github.com/taichi-dev/taichi/blob/1b024a08027e5852c14390e512e69584586f8eb5/taichi/transforms/offload.cpp#L155-L156
----
> [Metal] Support ti.block_dim() and ti.cfg.saturating_grid_dim

- taichi/backends/metal/codegen_metal.cpp
This makes test_bitmasked.py pass..
Related issue = #1941
----
> [metal] Support TLS for struct-for tasks

- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
This is to address https://github.com/taichi-dev/taichi/pull/1936#pullrequestreview-506091734. But TBH, I saw no performance difference... Still good to keep the data structures consistent, though.
I feel like it's fine to keep `lastest_state_owners_` as is because it's not shown as a bottleneck, and it's not multi-leveled.
Related issue = https://github.com/taichi-dev/taichi/pull/1936#pullrequestreview-506091734
----
> [async] Use llvm::SmallVector/llvm:SmallSet for latest state readers

- taichi/program/program.cpp
- taichi/util/str.cpp
- taichi/util/str.h
This is just pulling out the error message formatting part used by LLVM backend into a separate function. This way we can share it on other backends :)
Related issue = #677
----
> [refactor] Add format_error_message() method

- .gitignore
- python/taichi/lang/impl.py
- python/taichi/lang/ndrange.py
A collection of several random yet trivial fixes.
----
```py
x = dict(a=1, b=2)
@ti.kernel
def func():
ti.static_print(x['a'])
func()
```
---
```
[Taichi] mode=release
[Taichi] version 0.6.40, llvm 10.0.0, commit 78231814, win, python 3.8.5
[Taichi] materializing...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-95603a473205> in <module>
7     ti.static_print(x['a'])
8 
----> 9 func()
~\AppData\Local\Programs\Python\Python38\lib\site-packages\taichi\lang\kernel.py in wrapped(*args, **kwargs)
572         def wrapped(*args, **kwargs):
573 …
```
> [Bug] [lang] Fix error when subscripting a dict

- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/control_flow_graph.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/state_machine.cpp
- taichi/ir/statements.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/transforms/alg_simp.cpp
- taichi/transforms/auto_diff.cpp
- taichi/transforms/binary_op_simplify.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
Related issue = #1905 #1957 
A continuation of #1957 
This removes `DataType::data_type`, which is a self-reference to the `DataType` itself.
Most changes are mechanical in this PR.
----
> [type] [refactor] Remove DataType::data_type

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_util.h
- taichi/backends/metal/shaders/print.metal.h
- taichi/program/extension.cpp
- tests/python/test_assert.py
Similar to how we've supported `print()`, I reserved a dedicated area in the Metal buffer to store assertion failure messages. The assertion message and print messages are placed in the same buffer for simplicity. Here's the buffer memory layout:
```cpp
// MetalPrintAssertBuffer memory view:
//
// +------------------------+ \
// | AssertRecorderData     | |
// +------------------------+ | -> for assert(), kMetalAssertBufferSize
// | PrintMsg for assert()  | |
// +------------------------+ /
// | PrintMsgAllocator      | \
// +------------------------+ |
// |                        | |
// |                        | |
// | a queue of PrintMsgs   | | -> for print()
// | for print()            | |
// | ... ...                | |
// |                        | |
// +------------------------+ / …
```
> [Metal] Support assert()

- taichi/ir/type.cpp
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/program/program.cpp
In this pr, we replace `Program::get_type_factory()` with `TypeFactory::get_instance()`. We currently reserve the former function which may be removed in the future.
----
> [Type] [refactor] Make TypeFactory Global

- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/python/export_lang.cpp
This PR renames `PrimitiveType::primitve_type` to `PrimitiveTypeID`, which is needed for a general function required by `Type` and also fixes the forward declaration issue.
----
> [Type] [refactor] Make PrimitiveTypeID a public enum

- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.h
- taichi/transforms/make_block_local.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/test_alg_simp.cpp
- tests/cpp/test_same_statements.cpp
In this pr, we remove the class `LegacyVectorType` and use a static function `TypeFactory::create_vector_or_scalar_type` instead.
----
> [Type] [refactor] Remove LegacyVectorType

- python/taichi/misc/util.py
Related issue = https://github.com/taichi-dev/taichi/issues/677#issuecomment-710742766
----
It seems that if I use IPython (`ti repl`), the warning is depressed. If I use raw Python shell (`python`), the warning is shown.
So IPython is setting `warnings.filterwarnings('ignore')` on their own? Anyway, the built-in warning system seems unreliable.
Let's switch to standard `print` for warning instead.
> [Error] [ipython] Use print directly instead of builtin warnings module to prevent being supressed

- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- tests/python/test_gc.py
https://github.com/taichi-dev/taichi/blob/ceea597141bd1f0f0b2a380e5dabd50fb6ed04a6/taichi/lang_util.cpp#L156-L158
Before this PR, `test_block_async()` would actually fail. Here's the SFG. Note that all GC tasks are floating (as expected):
With this PR, SFG:
Highlighting the `allocator` state:
----
> [async] Add allocator async state

- taichi/backends/metal/codegen_metal.cpp
Follow up on #1949 to clean up the code a bit..
Related issue = #1949
----
> [metal] Create helper methods for TLS codegen

- tests/cpp/benchmark_sfg_edges.cpp
Disabling these tests to reduce the noisy output.
----
> [test] Disable SFG benchmark tests

- python/taichi/lang/meta.py
- python/taichi/misc/gui.py
- taichi/gui/cocoa.cpp
Sorry for the delay! Fixes #1976 
Related issue = #1976
----
> [GUI] [mac] Support fast_gui on macOS

- python/taichi/lang/kernel.py
- setup.py
----
I found that ODOP is not working properly in Blender.
> [blender] Fix inspect.stack() not working in Blender with sourceinspect 0.0.4

- python/taichi/lang/impl.py
- python/taichi/lang/kernel.py
- taichi/python/export_lang.cpp
- tests/python/test_kernel_arg_errors.py
> [error] Improve kernel argument type mismatch error message

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/data_types.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
Hi,
This PR contains mostly refactors and tweaks needed for `pointer`.
* Make `NodeManagerData:: ElemIndex` a strong type instead of an alias for `int32_t`. This is because we have to shift the raw `int32_t` index allocated from `NodeManagerData`'s lists (aka `ListManager`s), in order for the spinning memory allocation (#1174) to work. Using a plain `int32_t` is dangerous, as I have forgotten about the shift in allocation or recycle previously...
* Pull out `ListgenElement::coords` into a separate type: `ElementCoords`. The generated struct-for kernel only needs to know the coordinates, but not other info inside `ListgenElement` (which will be expanded later).
Related issue = #1740, #1174 
----
> [metal] Refactor sparse shader impl in prep for pointer SNode

- examples/euler.py
----
Fix the misuse of `atomic_max` in the compressible flow example
> [Example] Fix euler.py example

- examples/stable_fluid.py
- misc/benchmark_reduction.py
- python/taichi/lang/__init__.py
- taichi/analysis/gather_snode_read_writes.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/analysis.h
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/transforms.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/detect_read_only.cpp
- taichi/transforms/insert_scratch_pad.cpp
- taichi/transforms/ir_printer.cpp
About read-only data cache on CUDA: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#ldg-function
Note that on newer GPUs the performance seems less pronounced compared to old ones. For example, on `stable_fluid.py`
- on RTX 3090, this optimization leads to no performance gain
- on GTX 1080, this optimization leads to a ~4% performance gain. Compared to the original `stable_fluid.py` with manual hints, the compiler-optimized version is 1% faster. (So I removed the manual hints.)
Also, note that the backend compiler may be able to do this optimization automatically once it finds a memory load is read-only. We are doing it just to enforce the use of `__ldg` instructions. Taichi is able to do this since the `SNode` system is very friendly to aliasing analysis.
Anyway, we can …
> [Perf] [cuda] Automatically use read-only data cache load

- taichi/program/state_flow_graph.cpp
Sorry for introducing the subtle bug... 
(It shouldn't cause undefined behavior as `has_path` is a square matrix. But it can make SFG malformed.)
Also adds some assert_info that may be useful during debugging.
----
> [async] [bug] Fix a bug in fusion and add some debug info

- taichi/backends/metal/shaders/runtime_utils.metal.h
`SNodeRep_pointer` is functionally equivalent to LLVM's https://github.com/taichi-dev/taichi/blob/master/taichi/runtime/llvm/node_pointer.h. There are a few implementation details specific to Metal, though:
* Like the LLVM backend, each cell of a `pointer` SNode stores only the *pointer* to the data, not the data itself. However, unlike LLVM, this is not a real pointer, but merely an `int32_t` that indexes into somewhere in the Metal buffer memory. The `NodeManager` instance passed to this Rep's `init()` knows how to recover the data address from this `int32_t`. See `child_or_ambient_addr()`.
* In #1994, I added `NodeManager::ElemIndex`, which has a notion of `raw` vs `index` value. They differ by `kIndexOffset`. 
https://github.com/taichi-dev/taichi/blob/16af509ad5d6d95a19ff217105e22f3cac …
> [metal] Add SNodeRep_pointer

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
It's turned out that #2000's approach didn't really work, due to Metal's weak memory order guarantee...
**Problem**
Previously, each `pointer` cell stores a `NodeManager::ElemIndex::raw_`. This is basically an index in the `data_list`. The index then gets mapped to a chunk in the list, then a slot within that chunk.
This design has involved two places that would require atomic operations:
1. Reading or allocating the cell's value.
2. Reading or allocating the chunk in `data_list`.
```py
def allocate():
while cell is not valid:
if atomic_cas(&cell, 1):  # <-- 1st atomic, `1` means lock
addr = atomically allocate from `data_list`  # <-- 2nd atomic
store `addr` into `cell`  # now `cell` is valid
def get():
idx = atomically read from cell
atomically load `addr` from `data_list` using `idx` …
```
> [metal] Revise NodeManager's implementation due to weak memory order

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
This teaches the Metal codegen how to use `SNodeRep_pointer` in the generated classes. For example:
```cpp
struct S1 {
// pointer
constant static constexpr int n = 4096;
constant static constexpr int elem_stride = /*pointer ElemIndex=*/4;
constant static constexpr int stride = elem_stride * n;
S1(device byte *addr, device Runtime *rtm, device MemoryAllocator *ma) {
NodeManager nm;
nm.nm_data = (rtm->snode_allocators + 1);  // 1 is the SNode ID
nm.mem_alloc = ma;
const auto amb_idx = rtm->ambient_indices[1];  // 1 is the SNode ID
rep_.init(addr, nm, amb_idx);
}
S1_ch children(int i) {
return {rep_.child_or_ambient_addr(i)};
}
inline bool is_active(int i) {
return rep_.is_active(i);
}
inline void activate(int i) {
rep_.activate(i);
}
inline void deactivate(int i) {
rep_.deactivate(i);
} …
```
> [metal] Support pointer SNode in codegen

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_kernel_util.h
----
The limit of SSBOs can be down to 8 for OpenGL core, or 4 for OpenGL ES.
So we want to reduce the number of SSBO used to improve compatibility on low-end machines.
This PR merges the `earg` SSBO with `args` SSBO.
> [opengl] [refactor] Reduce SSBO numbers: merge earg with args

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/backends/opengl/shaders/random.glsl.h
- taichi/backends/opengl/shaders/runtime.h
----
This further reduce 1 SSBO when `print` is not used.
I wonder if we could even demote `RandStmt` into `GtmpStmt` and a series of bit operations in the middle end so that random  generators are backend-independent?
> [opengl] [refactor] Move rand_state from runtime to gtmp to reduce SSBO numbers

- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_context.cpp
- taichi/program/kernel.cpp
- tests/python/test_bit_struct.py
Related issue = #1905 #1996 
In this pr, we tried to support reading/writing `bit_struct` in python scope.
The key change is : support `CustomIntType` in `get_data_type`, `get_ret_int` and `get_ret_int`
----
> [type] Support bit-level read and write in Python-scope

- taichi/program/async_engine.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/transforms/constant_fold.cpp
- tests/python/test_fuse_dense.py
Related issue = #954 #2032
`Kernel::Kernel()` does not support multi-threads unless we lock the following part with a mutex:
```C++
taichi::lang::context = std::make_unique<FrontendContext>();
ir = taichi::lang::context->get_root();
{
CurrentKernelGuard _(program, this);
program.start_function_definition(this);
func();
program.end_function_definition();
ir->as<Block>()->kernel = this;
}
```
This PR simply locks `get_jit_evaluator_kernel()` monolithically to prevent two threads from calling `Kernel::Kernel()` concurrently.
----
> [opt] [async] Fix constant folding in async mode

- taichi/transforms/constant_fold.cpp
This is a follow-up of #2034. Besides the `Kernel` constructor, running kernel in multiple threads could cause problems on device synchronization (at least on Metal, where `metal::KernelManager` isn't thread safe).
`jit_evaluator_cache_mut` also guards the `fetch_result` call. This is because we have to make sure the content of the global Program's result buffer is not written by two threads, too.
----
> [async] More fixes of constant folding in async mode

- .github/pull_request_template.md
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_random.py
Related issue = closes #2023
----
> [cuda] Fix ti.random(dtype=ti.f64)

- taichi/transforms/insert_scratch_pad.cpp
- taichi/transforms/make_block_local.cpp
Performance bug by the `read_only` detection pass (#1998)
----
> [perf] Fix block local storage transform performance

- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- tests/python/test_sfg.py
I've extended `AsyncNode::snode` to hold a `std::variant<SNode*, Kernel*>`, because global temporaries can be identified by its enclosing kernel. (I feel like this is more intuitive than having a `global_tmp` in the enum class. Otherwise, what should the SNode be?)
Related issue = #2024 
----
> [async] Support global temporaries value state

- python/taichi/lang/expr.py
- python/taichi/lang/transformer.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.h
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_custom_float.py
Sorry about the large changes.
- Add `CustomFloatType`
- Support global load/store of `CustomFloatType` (`atomid_add` will be done later.)
- `KernelReturnStmt`/`ArgLoadStmt` ctor no longer takes data type. Their return data types are inferred by `type_check` 
- `get_compute_type` is now part of `Type` API. Overriden in derived classes `CustomFloatType`, `CustomIntType`, `PrimitiveType`.
- Return type of `GlobalPtrStmt` is now a pointer type (used to be only the pointee type)
- Refactor/implement SNode reader/writer for `CustomFloat/IntType`
- Add `is_real(DataType)`
- `GlobalStoreStmt` no longer has a return data type
----
> [type] Add CustomFloatType

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
... for faster async optimizations
Benchmark on 2D MGPCG:
Before:
- `synchronize`: 7.907
- `rebuild_graph` in `optimize_listgen`: 2.225
After (33% faster):
- `synchronize`: 5.935
- `rebuild_graph` in `optimize_listgen`: 1.668
----
> [async] Filter list operations that are clearly redundant

- taichi/codegen/codegen_llvm.cpp
- tests/python/test_cast.py
Related issue = #1905 #1996
In this pr, I try to determine which extension instruction should be used when casting integers. According to my understanding, we should use `zext` for unsigned int, and `sext` for signed int.
Please note that, the original goal of this pr is to determine the instruction for `CustomIntType`.  One `CustomIntType` should be loaded through `GlobalLoadStmt` first before casting. After loading, the `CustomIntType` would be a "normal"
integer type (the same type as its `ComputeType`). That is to say, we can simply treat the `CustomIntType`  and primitive integer type equally here.
----
> [type] Use zext instruction to cast unsigned int

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- tests/python/test_bit_array.py
- tests/python/test_bit_struct.py
- tests/python/test_custom_float.py
In this pr, we want to support bit-level pointer on coda backend. 
For now, most test cases passed, but the CustomInt/Float type with 16-bits or 8-bits physical type would fail. The error occurs in JIT module, which I know very little about. @yuanming-hu could you please have a look? I will left the error message and reproducing code in JIRA. Thanks a lot! 
----
> [type] [cuda] Support bit-level pointer on cuda backend

- taichi/backends/cc/cc_program.cpp
- taichi/backends/cc/cc_program.h
- taichi/backends/cc/cc_runtime.h
- taichi/backends/cc/codegen_cc.cpp
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
Related issue = #1644
----
We will choose to `clang` by default, `gcc` as fallback.
mpm88:
cc gcc: 18 fps
cc clang: 24 fps
opengl mesa: 25 fps
Amazing! We're almost beating OpenGL on single core CPU! Maybe this's the power of clang's SIMD optimizer?
I also noticed that env option `TI_CC_COMPILER_CMD=xxx` doesn't work, will fix iapr.
Btw, @k-ye would you help me setup the C backend on OS X?
> [cc] [refactor] Automatically detect available compiler (clang or gcc)

- taichi/analysis/cfg_analysis.cpp
- taichi/ir/analysis.h
- taichi/program/async_engine.cpp
- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/ir_bank.cpp
- taichi/program/ir_bank.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
Before:
- `synchronize`: 4.281
- `rebuild_graph` in `optimize_listgen`: 0.799
After:
- `synchronize`: 3.996 (1.07x faster)
- `rebuild_graph` in `optimize_listgen`: 0.714 (1.12x faster)
Sorry about the potential conflict with #2070. Let's merge #2070 first and I'll fix the conflicts here on my own.
The design is probably not elegant yet at this point, but let's first get the desired performance and then aim for elegance.
----
> [async] Compact AsyncState id for faster SFG rebuilding

- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
Add a customized `StateToNodesMap` data structure for fast SFG edge insertion and lookup.
This PR probably would make the performance even worse for now, because deduping during the edge insertion is slow..
----
> [async] Add customized container for async state to node map

- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
This is a follow up of #2080. I've managed to pull out `sort_edges()` and only call it once in `rebuild_graph()`, so that the rest of the methods can just assume the data are sorted.
Unfortunately, to play along with partially GCed nodes, I had to add another `unsort_edges()`... So that upon the next launch (after synchronization in this round), it is possible to insert edges to these executed but retained nodes.
Issue= Follow up #2080 
----
> [async] Call sort_edges() once during graph rebuilding

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- tests/python/test_custom_type_atomics.py
Related issue = #1905 #2078
We try to support atomic add on `CustomFloatType` following the implementation of `CustomIntType` in this pr. 
----
> [type] Support atomic add on CustomFloatType

- python/taichi/lang/impl.py
- tests/python/test_types.py
I believe the problem is that `pybind11` has strict checks on its input args. Without the constant value knowing the type of the LHS, let's just clamp the constant to its valid range (while keeping the bits same)
Related issue = #2060 
----
> [lang] [bug] Clamp int constant to its native range

- taichi/program/async_engine.cpp
- taichi/program/async_utils.cpp
- taichi/program/compile_config.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
Also removes hash in DOT graph, adds `CompileConfig::async_listgen_fast_filtering`, increases `TaskLaunchRecord::id` by one.
----
> [async] Use monospace font for DOT graph

- taichi/runtime/llvm/runtime.cpp
- tests/python/test_custom_type_atomics.py
Related issue = #1905 #2078 #2085 
**Atomic add may crash when adding negative numbers.** It is because we didn't partially set the value to memory using mask after we do the addition. Adding negative numbers may cause the change of the higher bits. 
For example: if we pack `a` (ci3) and `b`(ci5) in a bit_struct(num=8), and set them all zero at beginning(`a` is the lower 3-bits, and `b` is the higher 5-bits). Then we add `-1` to `a`, and we will find that `b` will be changed too.
So, a possible solution might be partially setting value to memory with mask in `runtime.cpp` just like `set_partial_bits_b` which only affects the bits of `a` in the former example .
----
> [type] [bug] Support atomic add negative numbers for custom types

- taichi/codegen/codegen_llvm.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_custom_float.py
> [type] Improve GlobalStoreStmt precision on custom floats

- examples/mpm_lagrangian_forces.py
- python/taichi/lang/__init__.py
- python/taichi/misc/util.py
> [async] Add ti.misc.util.print_async_stats

- taichi/runtime/llvm/runtime.cpp
- tests/python/test_bit_struct.py
Related issue = #1905 #2091 
The current way we create mask in `set_partial_bits_b` may cause the problem of `shift count >= width of type`. For example, we will do a left shifting for 32 times when we want to set a 32-bits `CustomIntType` which is exactly placed in a 32-bits `BitStruct`.
Please refer to the test case in this pr to see more details.
----
> [type] [bug] Correct mask used in setting bits partially

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
Related issue = #1905 #2093 #2085 
The current implementation of atomic add of `CustomFloatType` miss the rounding step which may cause some problems.
Thanks to @yuanming-hu 's implementation of `CustomFloatType` rounding in `GlobalStoreStmt`, I can reuse it here and make code clean.
----
> [type] [bug] Add rounding for atomic adding of CustomFloatType

- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
On my end:
16:
```
...
[I 12/20/20 13:16:02.093] [state_flow_graph.cpp:taichi::lang::StateFlowGraph::benchmark_rebuild_graph@1504] nodes = 1001 total time 866.5100 ms (averaged so far 821.9 ms); per_node 865.6444 ns
[I 12/20/20 13:16:02.184] [state_flow_graph.cpp:taichi::lang::StateFlowGraph::benchmark_rebuild_graph@1504] nodes = 1001 total time 901.1000 ms (averaged so far 822.7 ms); per_node 900.1998 ns
```
8:
```
...
[I 12/20/20 13:16:40.974] [state_flow_graph.cpp:taichi::lang::StateFlowGraph::benchmark_rebuild_graph@1504] nodes = 1001 total time 710.3000 ms (averaged so far 721.0 ms); per_node 709.5904 ns
[I 12/20/20 13:16:41.044] [state_flow_graph.cpp:taichi::lang::StateFlowGraph::benchmark_rebuild_graph@1504] nodes = 1001 total time 701.7100 ms (averaged so far …
```
> [async] Reduce the inlined edges size from 16 to 8

- python/taichi/lang/transformer.py
- taichi/backends/cc/cc_utils.h
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
> [misc] Remove data_type_short_name (use data_type_name instead)

- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/simplify.cpp
- tests/python/test_bit_array.py
- tests/python/test_bit_struct.py
- tests/python/test_custom_float.py
- tests/python/test_custom_type_atomics.py
All the tests passed on my end. I'm not sure in which way will the control-flow graph optimizations incompatible with the new type system?
BTW, in `compile_to_offloads.cpp`, this part may be redundant and may not perform the check it intends to:
https://github.com/taichi-dev/taichi/blob/e251ca7616f28002430e868022ddb861a7c16ba1/taichi/transforms/compile_to_offloads.cpp#L105-L109
-- this is because `cfg_optimization` is already called in `full_simplify` without checking compile config here:
https://github.com/taichi-dev/taichi/blob/e251ca7616f28002430e868022ddb861a7c16ba1/taichi/transforms/simplify.cpp#L616-L618
----
> [test] Enable cfg_optimization in all tests

- taichi/transforms/alg_simp.cpp
- taichi/transforms/check_out_of_bound.cpp
Related issue = #656 https://github.com/taichi-dev/taichi/pull/2106#issuecomment-748805714
New peephole optimizations in this PR:
- a - a -> 0 (fast math)
- a or a -> a
- a xor a -> 0
- a / a -> 1 (fast math)
- a and a -> a
- a == a -> 1 (fast math)
- a >= a -> 1 (fast math)
- a <= a -> 1 (fast math)
- a != a -> 0 (fast math)
- a > a -> 0 (fast math)
- a < a -> 0 (fast math)
Also fixes `check_out_of_bound` not assigning the types to the newly inserted statements.
----
> [Opt] Algebraic simplification for binary operations with two operands having the same value

- cmake/TaichiCXXFlags.cmake
- cmake/TaichiCore.cmake
- docs/dev_install.rst
- taichi/backends/cpu/jit_cpu.cpp
- taichi/llvm/llvm_context.cpp
Related issue = #2097 
Known issues:
- `ti test` doesn't work well when using 8 testing threads. 4 threads are fine.
- Warning message needs to be somehow suppressed: `'vortex' is not a recognized processor for this target (ignoring processor)`
- A few tests fail on Metal:
```
FAILED ../tests/python/test_fuse_dense.py::test_no_fuse_sigs_mismatch[metal]
FAILED ../tests/python/test_runtime.py::test_init_arg[use_unified_memory-values13] - AssertionError: assert False == True
FAILED ../tests/python/test_mpm88.py::test_mpm88_async[metal]
```
----
> [Mac] Experimental Apple Silicon M1 chip support

- taichi/backends/cuda/codegen_cuda.cpp
- tests/python/test_custom_float.py
Related issue = #1905 #2065
Some mistakes were made in global loading on CUDA, which would lead to compilation error. I will point out the bug below.
And also, I added a new test case focusing on this problem in this pr 
----
> [type] [bug] Fix global load of CustomFloatType on CUDA

- taichi/program/ir_bank.cpp
This can reduce the number of uncached IR operations.
----
> [async] Record the kernel's name in the hash only if it has arguments

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/program/context.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/runtime/llvm/runtime.cpp
- taichi/system/threading.cpp
- taichi/system/threading.h
Following the CUDA backend design, on CPUs now we have an independent set of PRNG states.
Implemented by adding a `cpu_thread_id` field to `lang::Context`.
@k-ye Does this affect the Metal backend, given now we have 4 more bytes on the `Context` struct?
----
> [cpu] Fix PRNG thread safety on CPUs

- misc/test_bit_array_vectorization.py
- python/taichi/lang/__init__.py
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/ir/transforms.h
- taichi/python/export_lang.cpp
- taichi/transforms/bit_loop_vectorize.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/test_same_statements.cpp
> [type] [Opt] Bit_array vectorization(Step 1)

- taichi/program/async_engine.cpp
- taichi/program/async_profiler_switch.h
- taichi/program/async_utils.cpp
- taichi/program/state_flow_graph.cpp
- taichi/system/profiler.cpp
It has turned out that the scoped profilers have a huge overhead. E2E time when benchmarking MGPCG at 512 resolution:
1. Before this PR: 0.49s
2. With this PR: **0.27s**
(A slightly off the topic change is to tweak the color, the default blue are green colors are a bit hard to read with Ubuntu's purple background... That said, these stats won't be helpful now, and we should resort to the lower-overhead perf solutions like `perf` and vtune..)
----
> [async] Disable profiler macros in release mode

- taichi/analysis/same_statements.cpp
- taichi/ir/analysis.h
- taichi/program/async_engine.cpp
- taichi/program/async_utils.h
- taichi/program/ir_bank.cpp
- taichi/program/state_flow_graph.cpp
- tests/python/test_bit_array_vectorization.py
Related issue = #742 #656
```C++
bool same_value(
Stmt *stmt1,
Stmt *stmt2,
const AsyncStateSet &possibly_modified_states,
IRBank *ir_bank,
const std::optional<std::unordered_map<int, int>> &id_map = std::nullopt);
```
allows passing in a parameter `possibly_modified_states`, so that we can analyze if two global loads share the same value (same if the value state of the SNode is not modified).
G2P2G running time on my laptop (fusible now, 1.44x faster!):
before:
```
num particles=10086
frame time 0.210 s
substep time 4.047 ms
num particles=10251
frame time 0.341 s
substep time 6.559 ms
num particles=10416
frame time 0.248 s
substep time 4.776 ms
num particles=10581
frame time 0.327 s
substep time 6.291 ms
num particles=10746
frame time 0.294 s
substep time 5.658 ms
num particles=10911 …
```
> [async] [IR] More accurate same_value analysis

- python/taichi/lang/__init__.py
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/compile_config.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
By flushing more frequently, we can have wider CPU-GPU execution overlap. MGPCG (res=512) async E2E execution has been reduced from ~0.25s to ~0.15s when flushing every 50 tasks. 
----
> [async] Add explicit flush API and async_flush_every

- python/taichi/lang/__init__.py
- python/taichi/lang/snode.py
- python/taichi/lang/type_factory.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/llvm/llvm_codegen_utils.h
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- tests/python/test_custom_float.py
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_type_atomics.py
- Add `TypeFactory` Python class
- `CustomFloatType` now supports exponents (`GlobalLoad/Store`)
- `shared_exponent` API (implementation in the next PR)
- LLVM codegen refactorings
- `place(CustomFloatType)` SNodes now has a pointer to its exponent SNode
- Children of `bit_struct` SNode now has `bit_offset`
(This is, unfortunately, a lot of implementation details and "magic" numbers, especially the conversion between `CustomFloatType` and IEEE 754 `f32`).
----
> [type] Support exponents in CustomFloatType

- misc/benchmark_bit_struct_stores.py
- python/taichi/lang/type_factory.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/ir/transforms.h
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/lang_util.cpp
- taichi/llvm/llvm_context.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/loop_vectorize.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
- taichi/transforms/type_check.cpp
- taichi/transforms/vector_split.cpp
- tests/python/test_bit_array.py
- tests/python/test_bit_array_vectorization.py
- tests/python/test_bit_struct.py
- tests/python/test_cast.py
- tests/python/test_custom_int.py
- tests/python/test_custom_type_atomics.py
- tests/python/test_struct_for.py
`benchmark_bit_struct_stores.py`:
- CPU: 805ms -> 271ms
- CUDA: 13.6ms -> 6.73 ms
----
> [type] Add BitStructStoreStmt and corresponding passes

- taichi/transforms/offload.cpp
- tests/python/test_bit_struct.py
> [type] Fix struct-for on bit_struct

- taichi/gui/cocoa.cpp
- taichi/gui/win32.cpp
Related issue = A windows Taichi THREE user reports
----
To reproduce:
```
gui = ti.GUI()
while gui.running:
for e in gui.get_events():
print(e.type, e.key)
gui.show()
```
You should see no `Motion` event when your mouse is moving above the window. (Didn't have a win env to reproduce yet, but I let that win user to help me confirmed that this is reproduced)
But this works fine on X11:
```
EType.Move Motion
EType.Move Motion
EType.Move Motion
EType.Move Motion
EType.Move Motion
...
```
Please merge this fix soon so that windows and mac users could enjoy orbiting camera around in Taichi THREE :smiley: 
@k-ye Would you mind help me confirm the cocoa part works (by using the reproduce code)? Thank in …
> [GUI] Fix ti.GUI.MOVE not working on win32 and cocoa

- python/taichi/lang/matrix.py
- tests/python/test_matrix_different_type.py
This pr aims to support different length of custom digits in one Vector/Matrix. Now one can code like : 
`
x = ti.Vector.field(2, dtype=[float, int])
`
to get a one Vector/Matrix with different types. Also you can set different custom types in one Vector/Matrix.
----
> [Type] Support different element types for Matrix

- python/taichi/lang/snode.py
- python/taichi/tools/video.py
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/snode.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/demote_atomics.cpp
- tests/python/test_cell_size_inspection.py
- tests/python/test_custom_float_exponents.py
> [type] Support SNode.cell_size_bytes

- python/taichi/lang/snode.py
- taichi/program/program.cpp
> [type] Fix arm64 flush to zero

- .github/workflows/release.yml
This PR sets up a GitHub actions workflow upon publishing a new release. Right now it just forks  the "Build and Test (CPU)" job. Later on we can add these:
Related issue = #1580
----
> [misc] Add a Github Action workflow to trigger on publishing a release

- taichi/codegen/codegen_llvm.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/lower_ast.cpp
The changes may seem unrelated but since `offloaded->snode` is changed, in `offload.cpp` the block dim query now happens on the dense node instead of the bit_struct. 
----
> [type] Fix struct-for block dim on bit_structs

- taichi/ir/statements.cpp
- taichi/program/async_utils.cpp
- taichi/program/ir_bank.cpp
Fixes `OffloadedStmt::clone()`, and merges `OffloadedStmt::mem_access_opt`s when fusing.
Off-topic: I'm not sure if two struct-fors with different index offsets can be fused together.
----
> [async] [bug] Fix missing memory access options in async mode

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/alg_simp.cpp
Also adds `DelayedIRModifier::mark_as_modified()` because this pattern (modifying IR, not through DelayedIRModifier, but need to record if the IR is modified) repeats in some other passes.
----
> [opt] Simplify bit_cast of bit_cast

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/snode.h
- taichi/runtime/llvm/runtime.cpp
- taichi/struct/struct.cpp
- taichi/transforms/offload.cpp
Related issue = #2146
Hi,
I'm changing the return type of `SNode::max_num_elements()` to `int64` to avoid overflow in #2146. @TH3CHARLie please let me know if this also fixes your problem, thx!
Note that this is NOT a thorough fix for #2146, as I still prefer that we dump a huge warning when the requested size is impractically large. (WIth this patch, the reproducer still segfaulted without dumping more information.) I will take a look tmr...
----
> [misc] Change SNode max_num_elements to use int64

- taichi/backends/cc/codegen_cc.cpp
----
There were 3 emit operations in this file that emit print operations to the compiled c file when dumping some gradient kernels. These debug messages won't be helpful to developers that works on gradient kernels.
@yuanming-hu
> [misc] Deleted 3 debug messages in codegen_cc.cpp

- taichi/program/ir_bank.cpp
- taichi/program/state_flow_graph.cpp
- taichi/transforms/simplify.cpp
Related issue = #656 #742
This PR enables DSE for non-scalar SNodes, and fixes `full_simplify` so that we can perform `whole_kernel_cse` after `cfg_optimization`.
----
> [opt] [async] Improve full_simplify and optimize_dead_store

- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/cuda_driver.h
- taichi/backends/cuda/jit_cuda.cpp
- taichi/jit/jit_session.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
> [cuda] Add argument "gpu_max_reg" to ti.init

- python/taichi/lang/snode.py
- python/taichi/misc/util.py
- taichi/program/state_flow_graph.cpp
- taichi/python/export_lang.cpp
It's a bit hard to track the SNodes in the dot graphs, so let's expose the ID to python.
----
> [lang] Expose SNode ID to python

- .github/workflows/persubmit.yml
- python/taichi/lang/transformer.py
- requirements.txt
----
The only issue seems to be the deprecated `ast.Index`, fixed in this Pr - now Python 3.9 can pass all the tests!
We may discuss if we should officially release Python 3.9 wheel on PyPI, FYI Arch Linux has officially make Python 3.9 the default version after a full system upgrade, it seems the Blender bundled Python is also 3.9 now.. I know you are busy with a interesting research projects of SIGGRAPH (let me know more details after that!), so please let me take some responsbilities if you'd like to :smile:
> [Misc] Add experimental Python 3.9 support

- .gitignore
- python/taichi/lang/__init__.py
- taichi/backends/cuda/cuda_driver_functions.inc.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/compile_config.h
- taichi/program/kernel_profiler.cpp
- taichi/program/program.cpp
- taichi/program/state_flow_graph.cpp
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/system/timeline.cpp
- taichi/system/timeline.h
- tests/cpp/test_alg_simp.cpp
- tests/cpp/test_parallel_executor.cpp
- tests/cpp/test_simplify.cpp
The generated timeline json can be view via Chrome: https://slack.engineering/chrome-tracing-for-fun-and-profit/#:~:text=Chrome%20Tracing%20lets%20you%20record,is%20waiting%20on%20another%20process.
- C++-side API: `TI_TIMELINE` and `TI_AUTO_TIMELINE`
- Python-side API: `ti.init(timeline=True)`, `ti.timeline_clear()` and `ti.timeline_save(fn)`
There are other tools that do similar things, but they tend to expose too much information.
Demo:
- Parallel compilation:
- Flamechart of `flush`:
- CPU blocking GPU:
----
> [Infra] Support Timelines as a multithreading profiler

- benchmarks/async_advection.py
- benchmarks/async_cases.py
- benchmarks/benchmark_async.py
- benchmarks/utils.py
- python/taichi/lang/__init__.py
- taichi/program/compile_config.h
Related issue = #742 #2123
Also updates async microbenchmarks.
----
> [async] Set the default value of async_flush_every to 50

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/runtime/llvm/runtime.cpp
Test case: (1.66s->0.74s)
```python
ti.init(arch=ti.cpu, kernel_profiler=True, print_ir=True)
quant = True
n = 1024 * 1024 * 256
if quant:
ci8 = ti.quant.int(8, True)
x = ti.field(dtype=ci8)
y = ti.field(dtype=ci8)
z = ti.field(dtype=ci8)
w = ti.field(dtype=ci8)
ti.root.dense(ti.i, n).bit_struct(num_bits=32).place(x, y, z, w)
else:
x = ti.field(dtype=ti.i8)
y = ti.field(dtype=ti.i8)
z = ti.field(dtype=ti.i8)
w = ti.field(dtype=ti.i8)
ti.root.dense(ti.i, n).place(x, y, z, w)
w[0] = 1
@ti.kernel
def foo():
x[i] = i & 127
y[i] = i & 31
z[i] = i & 7
foo()
ti.kernel_profiler_print()
assert w[0] == 1
```
Test case (1.66s->0.84s):
```python
ti.init(arch=ti.cpu, kernel_profiler=True, …
```
> [type] Use a single atomicCAS for BitStructStoreStmt

- taichi/analysis/gather_uniquely_accessed_pointers.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/ir/analysis.h
- taichi/ir/statements.h
- taichi/ir/transforms.h
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
Test case(0.75s -> 0.42s)
```python
ti.init(arch=ti.cpu, kernel_profiler=True, print_ir=True, quant_opt_atomic_demotion=True)
quant = True
n = 1024 * 1024 * 256
if quant:
ci16 = ti.quant.int(16, True)
x = ti.field(dtype=ci16)
y = ti.field(dtype=ci16)
ti.root.dense(ti.i, n).bit_struct(num_bits=32).place(x, y)
else:
x = ti.field(dtype=ti.i16)
y = ti.field(dtype=ti.i16)
ti.root.dense(ti.i, n).place(x, y)
@ti.kernel
def foo():
x[i] = 1
foo()
ti.kernel_profiler_print()
```
----
> [type] Atomic demotion for bit struct stores

- taichi/analysis/gather_uniquely_accessed_pointers.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
Related issue = #1905 #2171 #2174
Test case (there are no atomic operations when either one of the optimizations is enabled):
fusion=False, atomic_demotion=False: 1.171s
fusion=False, atomic_demotion=True: 0.355s
fusion=True, atomic_demotion=False: 0.356s
fusion=True, atomic_demotion=True: 0.358s
```python
ti.init(arch=ti.cpu, kernel_profiler=True, print_ir=False,
quant_opt_store_fusion=True, quant_opt_atomic_demotion=True)
quant = True
n = 1024 * 1024 * 256
if quant:
ci16 = ti.quant.int(16, True)
x = ti.field(dtype=ci16)
y = ti.field(dtype=ci16)
ti.root.dense(ti.i, n).bit_struct(num_bits=32).place(x, y)
else:
x = ti.field(dtype=ti.i16)
y = ti.field(dtype=ti.i16)
ti.root.dense(ti.i, n).place(x, y)
@ti.kernel
def foo():
x[i] = i & 1023
y[i] = i & 15 …
```
> [type] Improve bit struct store fusion and atomic demotion

- taichi/codegen/codegen_llvm_quant.cpp
> [type] Apply quant_opt_atomic_demotion when storing all components

- tests/python/test_dynamic.py
Update 02/03/2021
`CUDA 11.2` didn't fix the bug triggered by our spinlock implementation. I will just skip this test on CUDA, without adding all the runtime version stuff.
---
It seems that lock is just one of the problems. Even if I switch back to https://github.com/taichi-dev/taichi/blob/d1061750485a7f31bb3b0f824182f1c497c70051/taichi/runtime/llvm/locked_task.h#L28-L42, the test is still failing, just no longer reproducible for `n=4`..
<s>I added `cuda_runtime_version` with the original plan to use this to decide which lock impl to go.</s>
----
> [bug] Disable test_dense_dynamic for CUDA

- .github/workflows/release.yml
- python/build.py
Related issue = #2185 
I did some cleanup to `python/build.py`. The change is actually not as large as it appears, because I was mostly grouping lots of the global statements into functions. A new mode, `build`, is added to this script, which only builds the wheels into `python/dist`, but doesn't do the upload. Also added an option `--skip_build`.
The release job now becomes:
1. `python build.py build`: builds the wheels without uploading.
2. `Archive Wheel Artifacts`: make the wheel files the artifacts of this job. (Unfortunately, I haven't found a way to include the release tag in the artifacts.) In case the final PyPI upload step failed, we still have a way to access these wheels and upload them manually.
3. `python build.py try_upload --skip_build`: Try uploading the wheels built from …
> [misc] Refactor release workflow to upload the wheel artifacts

- python/taichi/lang/transformer.py
- tests/python/test_ndrange.py
----
To reproduce:
```py
ti.init(print_preprocessed=True)
a = ti.field(int, ())
b = ti.field(int, ())
@ti.kernel
def func_ok():
for i in range(a[None]):
print(i)
@ti.kernel
def func_err():
for i, j in ti.ndrange(a[None], b[None]):
print(i, j)
a[None] = 3
b[None] = 3
func_err()
```
Running it will raises `AssertionError: __getitem__ cannot be called in Taichi-scope`.
This is because `a[None]` not being transformed into `ti.subscript(a, None)`.
This is an unexpected error introduced since #2081, which generates:
```py
__ndrange = ti.static(ti.ndrange(a[None], b[None]))
```
Here I was mean to assign statically to prevent symbol leakage, but `ti.static` leads to another side effect that …
> [Bug] [lang] Fix AST not being transformed inside ti.ndrange

- tests/python/test_element_wise.py
Three python tests related to floor division in test_element_wise.py fail on my laptop under OpenGL (Ubuntu 20.04, AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx).
In these tests, 3 / 3 gives 0.99999997 and 3 // 3 gives 0.
The difference between 0.99999997 and 1 is acceptable when doing float divisions, but the floor operation makes the answer totally wrong and makes these three tests fail on my laptop. (3 // 3 should be 1 instead of 0)
> [test] [opengl] Avoid floor division cornor cases by adjusting test data

- misc/generate_ir_design_doc.py
- taichi/ir/statements.h
> [ir] Generate yaml documentation for statement classes

- CMakeLists.txt
- cmake/TaichiTests.cmake
- taichi/common/core.cpp
- taichi/common/core.h
- taichi/python/export_lang.cpp
- taichi/system/traceback.h
- tests/cpp_new/common/core_test.cpp
Related issue = #2195 
This PR adds `tests/cpp_new/common/core_test.cpp`. It is just an illustration of how we can write C++ unit tests, with no real valuable test in it. In the future, the directory tree of `tests/cpp_new` can mirror that of `taichi/` (Within Google the tests are usually directly placed along with the source files. Go is also designed like so. But it seems more common to have a separate directory for tests in other places..)
TODO:
Right now we have to manually trigger the test with `./taichi_cpp_tests`. Integrate this into the `ti` CLI.
----
> [test] Add a basic unit test using googletest

- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/snode_rw_accessors_bank.cpp
- taichi/program/snode_rw_accessors_bank.h
- taichi/python/export_lang.cpp
Related issue = #2196 
This is one of the steps to decouple `SNode` from `taichi/program`. Because many files inside `taichi/ir` depend on SNode, they transitively depend on `taichi/program` as well. `taichi/program` is very high level, and almost depends on everything in the codebase. So without breaking the tie, it is very hard for us to separate out IR.
Note that this PR alone is not enough (actually, far from enough) for modularizing the IR. I'm thinking of moving out `SNode::expr` later (we may have to have a similar mapping from `SNode` to `expr`). The reason is similar:
1. `expr` is an `Expr`, which depends on the expression and the frontend IR
2. Frontend IR depends on `taichi/program`.
As a short-term goal, I think it will be good enough if we can make `ir.h/cpp`, …
> [refactor] Separate SNode read/write kernels into a dedicated class

- python/taichi/lang/kernel_arguments.py
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/snode_expr_utils.cpp
- taichi/program/snode_expr_utils.h
- taichi/python/export_lang.cpp
- taichi/struct/struct.cpp
Related issue = #2196 
This PR is still about decoupling `SNode` from `taichi/program`. The major issue here is around its member variable `expr`. Because `Expr` is part of the frontend and relies on `taichi/program`, we have to move it out from `SNode`:
* Moved `place()` and `lazy_grad()` from `SNode` itself to a separate file `taichi/program/snode_expr_utils.h/cpp` (i cannot think of a better file name...). Other functions in `SNode` do not depend on `expr`.
* Created a `SNode::GradInfoProvider` abstract class. This is essentially a wrapper around `GlobalVariableExpression`. From what I can tell, `SNode::expr` is mostly used to provide gradient information, e.g. `is_primal()`, `has_grad()`, etc. The actual implementation, `GradInfoImpl`, is in `taichi/program/snode_expr_utils.cpp`.
* …
> [refactor] Add SNode::GradInfoProvider to isolate SNode from Expr

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
Related issue = #2196 
----
AST stuff and FrontendContext are coupled with python frontend of Taichi, while the goal of #2196 is to decouple Taichi IR and frontend.
This PR moves ASTBuilder and FrontendContext to frontend files.
> [refactor] Move ASTBuilder and FrontendContext to frontend_ir

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/ir/transforms.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/transforms/compile_to_offloads.cpp
This PR adds the following ctor:
```
Kernel(Program &program,
std::unique_ptr<IRNode> &&ir,
const std::string &name = "",
bool grad = false);
```
and lets `compile_to_offloads` and `compile_to_executable` to support compilation from CHI IR.
AutoDiff is not yet supported since `reverse_segments` works on the frontend IR(AST).
Also adds `KernelReturnStmt` to the IR builder.
Again, this PR is not unit-tested, so let me know if anything seems not working...
----
> [ir] Add a constructor for the Kernel class to handle CHI IR

- cmake/TaichiCore.cmake
- cmake/TaichiTests.cmake
- tests/cpp_new/ir/ir_builder_test.cpp
Related issue = #2196, #2193
Note that I've switched from `OBJECT`  to `STATIC` now. It could be too laborious to refactor the whole code base to a point where they are layered nicely. Instead, we should just create a (static) library that is unit testable by excludeing `taichi/python` and being python-free. Most of Taichi's dependencies will be merged into this lib, including LLVM, GLEW, etc. ( `target_link_librariess()` doesn't seem to be effective with an `OBJECT` library)
----
> [test] [ir] Add a simple unit test for IRBuilder

- examples/mgpcg.py
1. Eliminated the intermediate variable "grid" since it's redundant in the current context
2. Added several comments to help beginners to understand the code (hopefully)
3. Use fstring instead of plain print for displaying the residual to improve readability
Related issue = close #2215 
----
> [example] Update mgpcg.py

- .github/workflows/persubmit.yml
Related issue = #2219
* Before this change, @taichi-gardener  won't trigger the *required* "Ubuntu 3.6 Build and Test (CPU)" --> We have to do another push.
* After this change, @taichi-gardener 's CI will be slower (maybe by another 20 minutes). But we can at least merge PRs if there are no other issue.
Long term speaking, I see that TiDB's workflow is to manually trigger the CI by replying some magic keywords (e.g. "/run-all-tests"), which the bots will listen to. Maybe that's a better way to utilize CI resources.
----
> [misc] Make taichi-gardener also run the required CI jobs

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- tests/cpp_new/ir/ir_builder_test.cpp
This PR adds these statements to the IR Builder:
- All UnaryOpStmts
- All BinaryOpStmts
- TernaryOpStmt
- RangeForStmt, StructForStmt, WhileStmt, IfStmt
- WhileControlStmt, ContinueStmt
- AllocaStmt, LocalLoadStmt, LocalStoreStmt
- LoopIndexStmt
And add the following tests:
- PrintStmt test
- RangeFor test
----
> [ir] Add more statements and tests to IR Builder

- python/taichi/core/__init__.py
- python/taichi/core/primitive_types.py
- python/taichi/lang/__init__.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/lang/snode.py
- python/taichi/lang/transformer.py
- python/taichi/lang/util.py
- tests/python/test_kernel_template_mapper.py
> [refactor] Cleanup python imports

- python/taichi/lang/ast_resolver.py
- python/taichi/lang/ops.py
- python/taichi/lang/transformer.py
- tests/python/test_ast_resolver.py
- tests/python/test_syntax_errors.py
Related issue = #2223 
The idea is to consult the `globals()` scope to make sure functions like `ti.static` actually resolve to Taichi functions during AST transformation.
----
> [refactor] Add ASTResolver to properly resolve AST nodes to functions

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- tests/cpp_new/ir/ir_builder_test.cpp
This PR adds `GlobalPtrStmt` and `ExternalPtrStmt` and related statements to IR Builder. It also adds a test of external ptr as an example of using the external ptr. Maybe we should rename stuff like `is_nparray` since it's not related to numpy at this level...
The `SNode` needed by `GlobalPtrStmt` can only be created by hand using APIs provided in snode.h for now.
----
> [ir] Add global variables to IR Builder

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
This PR only renames `RangeForStmt/StructForStmt/FrontendForStmt/DecoratorRecorder::parallelize` to `num_cpu_threads` in the codebase, and doesn't change the frontend API.
----
> [refactor] [ir] Rename "parallelize" to "num_cpu_threads"

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- tests/cpp_new/ir/ir_builder_test.cpp
This PR adds `IRBuilder::LoopGuard` and `IRBuilder::IfGuard` to make writing control flows with IR Builder easier.
These classes' objects automatically set the insertion point in O(1) time if the insertion point is never manually set in their lifetime by other functions.
----
> [ir] Add RAII guards to IR Builder

- taichi/analysis/alias_analysis.cpp
- taichi/analysis/value_diff.cpp
- taichi/ir/analysis.h
- taichi/ir/ir_builder.h
- tests/cpp_new/analysis/value_diff_test.cpp
A preliminary step before adding some tests for alias analysis.
----
> [test] Add tests for value_diff_ptr_index pass

- python/taichi/lang/__init__.py
- python/taichi/lang/core.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/linalg.py
- python/taichi/lang/ops.py
- python/taichi/lang/shell.py
- python/taichi/lang/snode.py
- python/taichi/lang/type_factory_impl.py
- python/taichi/lang/util.py
Issue=#2223
The way we use ti_core is not clear and a bit confusing. Multiple repeat imports can make code redundant and hard to understand. This PR refactor the part in python/taichi/lang by:
Deleted core.py in under python/taichi/lang and replaced all usage of taichi_lang_core with _ti_core imported from taichi.core.util.ti_core. 
@k-ye 
----
> [lang] Replaced usage of taichi.lang.core with taichi.core.util.ti_core.

- taichi/analysis/data_source_analysis.cpp
- taichi/analysis/gather_snode_read_writes.cpp
- taichi/analysis/has_store_or_atomic.cpp
- taichi/analysis/last_store_or_atomic.cpp
- taichi/analysis/same_statements.cpp
- taichi/analysis/verify.cpp
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/control_flow_graph.cpp
- taichi/ir/state_machine.cpp
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/program/async_utils.cpp
- taichi/transforms/auto_diff.cpp
- taichi/transforms/bit_loop_vectorize.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/insert_scratch_pad.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/loop_vectorize.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
- taichi/transforms/variable_optimization.cpp
- taichi/transforms/vector_split.cpp
This PR renames `GlobalLoadStmt/LocalLoadStmt::ptr -> src`, `GlobalStoreStmt/LocalStoreStmt::ptr -> dest`, `GlobalStoreStmt/LocalStoreStmt::data -> val`.
Also renames some local variables using these fields and changes a few comments.
----
> [IR] [refactor] Unify field names in load/store/atomic statements

- taichi/runtime/llvm/runtime.cpp
- tests/python/test_random.py
Related issue = #2251
----
- Added a test as described in #2251 for float64 random numbers.
- Changed `rand_f64(Context *context)` into the implementation similar to `rand_f32()`. 
Now both float32 and float64 uses multiplying the reciprocal of UINT_MAX + 1 method to obtain floating point numbers between 0 and 1 from unsigned integers. If necessary we can also discuss the specific choice of implementation of `rand_f32()` and `rand_f64()`.
> [llvm] Well-behaved float64 random number generator for CPU and CUDA backends

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
Related issue = #1905 #2128
This PR adds support of CustomFloatType with non-shared exponents in BitStructStoreStmt.
Now the codegen workflow of BitStructStoreStmt looks like the follows:
1. Generate the code for all shared-exponent floating type stores (do not generate the code for non-shared exponent floating type stores here).
2. For each other store, generate the code, and bit_or it to `bit_struct_val`. For CustomFloatType with non-shared exponents, we need to generate the code of storing both the exponent and the fraction (code mainly copied from `visit(GlobalStoreStmt *)`).
3. Generate the mask of the bits stored in step 2.
4. If the mask is full, or if the BitStructStoreStmt itself is not atomic (probably because it's the only access to a loop index), generate a masked store; …
> [type] [opt] Use BitStructStoreStmt for CustomFloatType with non-shared exponents

- taichi/analysis/gather_uniquely_accessed_pointers.cpp
- taichi/analysis/gather_uniquely_accessed_pointers.h
- taichi/ir/analysis.h
- taichi/ir/pass.h
- taichi/ir/transforms.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
Related issue = #2193 #2252
It seems that `std::unique_ptr` cannot be `static_cast` in `get_pass_result()` so I cast the raw pointer instead.
----
> [ir] Move uniquely_accessed_bit_structs from compile_to_offloads to AnalysisManager

- taichi/analysis/value_diff.cpp
- taichi/transforms/insert_scratch_pad.cpp
- tests/python/test_bls.py
Related issue = #1394
`generate_block_indices()` generates indices which actually form a cube, so we can use the lower/upper bounds directly without generating the indices.
Also slightly improves value_diff.cpp in the `LoopIndexStmt` case.
----
> [opt] Avoid recursively generating indices twice for BLS

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- tests/cpp/ir/ir_builder_test.cpp
At the CHI level, the name `is_np_array` doesn't make sense since we don't know and don't care if the external array is from numpy. However, at the frontend, the external array is from numpy.
----
> [ir] Rename is_np_array to is_external_array except the frontend

- taichi/ir/statements.h
Related issue = #2193 #2192
This PR adds inline docs to all statements in statements.h.
----
> [IR] Add inline docs to all statements

- taichi/analysis/value_diff.cpp
- tests/python/test_ad_for.py
Related issue = #2272
Reversed loops only appear in AutoDiff for now, and BLS uses `value_diff` to analyze the BLS range, so I write a test for AutoDiff + BLS.
----
> [test] Add a test for range analysis of indices of reversed loops

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- tests/cpp/ir/ir_builder_test.cpp
A continuation of #2277. Also renames `i` to `arg_id` in some function signatures.
----
> [ir] Rename set_arg_nparray to set_arg_external_array

- taichi/analysis/value_diff.cpp
Related issue = #2265
This PR adds support for diffRange multiplication. Which will be needed after changing taichi indices to consecutive. #2248. 
----
> [IR] Support DiffRange multiplication

- docs/matrix.rst
- python/taichi/lang/__init__.py
- python/taichi/lang/linalg.py
- tests/python/test_eig.py
Related issue = #2208, #2293 
----
This PR aims to implement utility functions `ti.eig()` for 2x2 matrices as described in #2293.
> [Lang] Add ti.eig for 2x2 matrices

- taichi/llvm/llvm_context.cpp
Protect against path with space.
e.g. "C:\Users\Cheng Cao\source\repos\taichi" will be interpreted as "C:\Users\Cheng" and "Cao\source\repos\taichi", and causing the runtime bitcode compilation to fail (llvm_context.cpp line 152 `void compile_runtime_bitcode(Arch arch)`)
Related issue = #2317
> [bug] Protect against path with space
