taichi-dev/taichi

- docs/hello.rst
Wrapped "for" (as in for loop) in double ` marks so they render to monospace font. It may be mistaken for the *English word* "for" (as used grammatically). 
I think "range-for loops" can be left as is because they won't lead to confusion.
----
> [doc] Wrap `for` to avoid confusion

- cmake/TaichiTests.cmake
- docs/hello.rst
- taichi/analysis/bls_analyzer.cpp
- taichi/analysis/bls_analyzer.h
- taichi/ir/snode.h
- taichi/transforms/insert_scratch_pad.cpp
- tests/cpp/analysis/bls_analyzer_test.cpp
Related issue = #2177 
Hi @KLozes ,
Sorry this PR might cause more conflicts to your #2248 , but I believe this is a necessary step to allow us to better test the BLS code and make it more robust. Albeit the large change, it simply pulls out the `BLSAnalysis` class so that we can add test around it.
A few issues:
1. We don't see to handle this case correctly: when there are two GlobalPtrs, `BLSAnalyzer` can infer the BLS access pattern for one but not the other. Right now the scratch pads will be partially accessed, which seems wrong?
2. Make the interface of `BLSAnalysis` expose the result of whether BLS pads are initialized.
----
> [ir] Make BLSAnalyzer testable

- docs/hello.rst
@k-ye  **This is a reopen of #2314, merging to master**
Wrapped "for" (as in for loop) in double ` marks so they render to monospace font. It may be mistaken for the *English word* "for" (as used grammatically). 
I think "range-for loops" can be left as is because they won't lead to confusion.
----
> [doc] REOPEN #2314: wrap 'for' to avoid confusion

- taichi/gui/win32.cpp
> [GUI] Use native resolution (client scaling) on WIN32

- docs/dev_install.rst
When setting up Windows Path related environment variables, it may reject forward slash as invalid file path.
> [doc] Windows uses backslash for filepath

- tests/python/test_eig.py
Related issue = #2293
----
This is a potential bug I found when I was dealing with the CI test failure in the commit c4762326007a88e70dfcd5588f5d3aaa62f1a037 of PR #2328. I don't understand why it has passed the test before though, I think it had better be fixed.
> [bug] [test] Fix potential bug in test_eig.py

- taichi/ir/transforms.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/loop_invariant_code_motion.cpp
- taichi/transforms/simplify.cpp
Performance Observations:
Complicated. Check the related issue.
Structural Observations:
1. Many programs contain loops and certainly graphis programs contain a lot of them. It is very often that the loop is going over the same data structure and the same computations, just with different data
2. If the operands of a statement that has no side effects are all not from the current scope, it can only be from all the previous scopes. (If we assume the IR is well formed, and we have access to those operands)
3. Moving a statement in a loop, that does not depend on anything within the loop, one layer up, will result in less redundant computations. The more iterations a loop has, the more redundancy is removed.
4. Doing so may or may not increase register pressure. In the case of all operands …
> [perf] Loop-invariant code motion

- docs/matrix.rst
- python/taichi/lang/__init__.py
- python/taichi/lang/linalg.py
- tests/python/test_eig.py
Related issue = #2208, #2293  
----
This PR aims to add another utility function `ti.sym_eig` as described in #2293 and implement the corresponding solver for 2x2 matrices.
Similar to `np.linalg.eigs`, `ti.sym_eig` solves the eigenvalues and eigenvectors for symmetric matrices. Unlike `ti.eig` which stores the eigenvalue and eigenvector results as complex numbers,  `ti.sym_eig` returns real number results for simplicity. The interface design of `ti.sym_eig` is showed below:
```python
def sym_eig(A, dt=None):
"""Compute the eigenvalues and right eigenvectors of a real symmetric matrix.
Parameters
----------
A: ti.Matrix(n, n)
Symmetric Matrix for which the eigenvalues and right eigenvectors will be computed.
dt: …
```
> [Lang] Add ti.sym_eig for 2x2 matrices

- cmake/TaichiTests.cmake
- taichi/transforms/alg_simp.cpp
- taichi/transforms/binary_op_simplify.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/loop_invariant_code_motion.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
Related issue = #944 #656 #2177
This PR may help with some optimizations after #2327 is merged. When we want to access a leaf (place) SNode and (the same address of) its parent or some ancestor, simple optimizations such as CSE can remove the duplicated part of the access paths after lower_access when nonconsecutive indices are used (now). However, when consecutive indices are used, we may have some code like this:
```python
a = ti.field(ti.i32)
block = root.dense(ti.i, 64)
block.dense(ti.i, 3).place(a)
@ti.kernel
def foo():
for i in ...:
ti.activate(block, i / 8)
a[i]...
```
And we want the common part of  `block[i / 8]` and `a[i]` is reused in the two accesses. After expanding the `BitExtractStmt`, the former one will be `(i / 8) & 63` and the latter one will be `(i >> 3) & 63`. This PR …
> [Opt] Simplify multiplying/dividing POT

- examples/cornell_box.py
Hello ! Was playing around with this and found the second sphere position/radius unused, so thought it can be removed. Let me know if it's still needed however, in which case we don't need to merge.
Cheers,
Aaryaman
> [Example] cornell_box: Remove unused sphere

- taichi/ir/scratch_pad.cpp
- taichi/ir/scratch_pad.h
- taichi/ir/statements.h
- taichi/transforms/make_block_local.cpp
- tests/cpp/analysis/bls_analyzer_test.cpp
Related issue = #2177, #2327 
----
> [opt] Better encapsulate BLS bounds

- taichi/analysis/arithmetic_interpretor.cpp
- taichi/analysis/arithmetic_interpretor.h
- taichi/ir/type_utils.h
Related issue = #2177, #2327
As a start, `ArithmeticInterpretor` is used to evaluate a piece of BLS code. We can gradually make it support more IRs, or even grow it to a  full-blown VM for CHI IR.
----
> [ir] Add ArithmeticInterpretor to evaluate a subset of CHI IR

- tests/cpp/analysis/bls_analyzer_test.cpp
- tests/cpp/struct/fake_struct_compiler.h
- tests/cpp/transforms/make_block_local_test.cpp
Related issue = #2177, #2327
This demonstrates how `ArithmeticInterpretor` in #2342 can be used to test BLS.
----
> [ir] [test] Add tests for make_block_local

- Dockerfile
----
It seems the docker build trigger has been failing on Docker Hub for a couple of weeks... This PR fixes the docker build by using the latest CMake (v3.20.2). A few points I want to flag:
- The `ti test` passed the second time I ran them, while it failed the first time on `test_fuse_dense_x2y2z[x64]` reporting `[snode_types.cpp:snode_type_name@18] Not supported`, I assumed it's transient.
- Ubuntu LTS's `apt` does not ship the latest packages such CMake, which is the root cause of this issue, I switched to use a pinned version of CMake and build fro source, but not sure if the latest (v3.20.2) is too aggressively new?
- I just discovered `python/taichi/core/util.py` has this `in_docker` predicate …
> [Docker] Fix the docker build by bumping CMake version in Dockerfile

- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/ir/statements.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/constant_fold.cpp
- taichi/transforms/inlining.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
Since #2306 uses `KernelReturnStmt` for function returns, I think this statement should be renamed without the word "kernel".
----
> [ir] Rename KernelReturnStmt to ReturnStmt

- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/transforms/alg_simp.cpp
Related issue = a continuation of #2332
`val_cast_to_uint64()` looks cleaner than two if-branches with the same body.
----
> [opt] Slightly simplify algebraic simplification

- taichi/transforms/binary_op_simplify.cpp
Related issue = #944 
Test case:
```python
ti.init(print_ir=True)
@ti.kernel
def func(i: ti.u32):
if i % 2 == 1:
print(i)
func(1)
```
Before:
```
<i32> $1 = const [1]
<u32> $2 = arg[0]
<u32> $3 = const [1]
<u32> $4 = bit_sar $2 $3
<u32> $5 = bit_shl $4 $3
<u32> $6 = sub $2 $5
<i32> $7 = cmp_eq $6 $3
<i32> $8 = bit_and $7 $1
$9 : if $8 {
print $2, "\n"
}
```
After:
```
<i32> $1 = const [1]
<u32> $2 = arg[0]
<u32> $3 = const [1]
<u32> $4 = bit_and $2 $3
<u32> $5 = sub $2 $4
<i32> $6 = cmp_eq $5 $3
<i32> $7 = bit_and $6 $1
$8 : if $7 {
print $2, "\n"
}
```
----
> [opt] Simplify modulo POT (Stage 1)

- .github/workflows/release.yml
- .travis.yml
- README.md
- appveyor.yml
- setup.py
Related issue = #1057
If there exist no compatibility problems like issue #1057, taichi can possibly support python3.9.  
Since the version of the python interpreter of some softwares (like Blender 2.93) has updated to 3.9, it will facilitate the development of taichi-based addons if python3.9 can be officially supported by taichi . For now, given taichi cannot be installed with python3.9 by pip, addon developers have to build and pack taichi with python3.9 by themselves, which blocks the distribution of taichi-based products.
----
> [misc] Support Python 3.9

- taichi/transforms/ir_printer.cpp
Related issue = a continuation of #2349
----
> [ir] Remove "kernel" when printing ReturnStmt

- taichi/common/serialization.h
- tests/cpp/common/serialization_test.cpp
Related issue = Follow up of #2350 
Previous implementation of the serializer's variadic template API:
https://github.com/taichi-dev/taichi/blob/284f75eddd0e172b17b144e4f60d443f32a5520e/taichi/common/serialization.h#L545-L550
https://github.com/taichi-dev/taichi/blob/284f75eddd0e172b17b144e4f60d443f32a5520e/taichi/common/serialization.h#L790-L799
Caused a problems where a struct that doesn't satisfy any of the parameter type known by the serializer *can still be accepted by the serializers*. When none of the known parameter type matches, the C++ compiler will just fallback to this template API. Through a series of template instantiation, this would lead to unterminated recursive calls and stackoverflow at runtime. This is bad as we are supposed to catch such errors at compile time.
This …
> [lang] Remove serializer's variadic template API

- taichi/analysis/bls_analyzer.cpp
- taichi/analysis/bls_analyzer.h
- taichi/transforms/insert_scratch_pad.cpp
- tests/cpp/analysis/bls_analyzer_test.cpp
Related issue = #2327 
Using `ti.block_local` could be hard for new Taichi Users.  So we add an error when `ti.block_local` could not infer the scratch pad range.
----
> [Opt] Add error if bls analysis failed

- taichi/backends/metal/shaders/print.metal.h
stable fluids update
fix metal f32 bug
----
> [metal] Fix metal f32 bug in the print buffer

- taichi/ir/ir_builder.h
This PR warns CHI users when they write `builder.get_loop_guard(loop);` which has no effect. The correct usage is `auto _ = builder.get_loop_guard(loop);`.
----
> [ir] Add nodiscard to get_loop_guard/get_if_guard

- taichi/codegen/codegen_llvm.cpp
Related issue = #1905 #2047 
Bit pointer struct only needs two components (one for byte pointer and one for offset). But somehow another component was added in #2047. I removed it now.
https://github.com/taichi-dev/taichi/blob/6a969901029815434975a3fd9a3aac1d9324776c/taichi/codegen/codegen_llvm.cpp#L1271-L1279
As the comment described, it is not necessary to allocate two int32 components.
----
> [type] [bug] Remove redundant component of bit pointer struct

- taichi/transforms/alg_simp.cpp
Related issue = fix #2375
Test case:
```python
ti.init(print_ir=True)
@ti.func
def low_high_frac(x: float):
low = int(x)
high = low + 1
frac = x - low
return low, high, frac
@ti.func
def sample_volume_trilinear(x: float):
x_low, x_high, x_frac = low_high_frac(x)
return x_frac
@ti.kernel
def get_normal(x: int):
xf = float(x)
dy = sample_volume_trilinear(xf)
print(dy)
get_normal(2)
```
Before:
```
$0 = offloaded
body {
<i32> $1 = arg[0]
<f32> $2 = cast_value<f32> $1
<i32> $3 = cast_value<i32> $2
<f32> $4 = cast_value<f32> $3
<f32> $5 = sub $2 $4
print $5, "\n"
}
```
After:
```
$0 = offloaded  
body {
<f32> $1 = const [0.0]
print $1, "\n"
}
```
----
> [Opt] Optimize nested type casts

- .github/workflows/cancel.yml
- .github/workflows/issue_comment.yml
New commit triggered workflows will cancel previous running/pending workflows.
----
> [CI] Support auto cancel workflows of previous commits

- examples/mass_spring_3d.py
- taichi/ir/ir_builder.h
- taichi/program/program.h
> [Misc] Fixed that mass_spring_3d.py do not exit on import error

- python/taichi/aot/module.py
- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/metal/aot_module_builder_impl.h
- taichi/program/aot_module_builder.h
Make file names dumped from aot configurable
----
> [Metal] Make file names dumped from aot configurable

- taichi/backends/metal/aot_module_builder_impl.cpp
> [lang] Fix filesystem header not found on older GCC

- Jenkinsfile
- examples/mass_spring_3d.py
- python/build.py
> [CI] Configured Jenkinsfile to support nightly test

- taichi/analysis/arithmetic_interpretor.cpp
- taichi/analysis/arithmetic_interpretor.h
- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/transforms/lower_access.cpp
- taichi/transforms/scalar_pointer_lowerer.cpp
- taichi/transforms/scalar_pointer_lowerer.h
- tests/cpp/transforms/scalar_pointer_lowerer_test.cpp
Related issue = #2382
`lower_scalar_pointer()` used to do three difference things:
1. transform the indices into a series of extract_bits and linearized statements 
2. test if the SNode is linear related to the struct_for
3. generate SNode access ops (e.g. GetCh)
This PR pulls out step 1 into a separate class `ScalarPointerLowerer` to make it testable. Later we can also grow the logic around 1 separately (e.g. generate index decomposition statements for non power-of-two SNodes).
Steps 2 and 3 still remain in the original `lower_acesss` pass.
----
> [ir] Make lower_scalar_pointer testable

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/transforms/binary_op_simplify.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
Related issue = #944
A continuation of #2352 and fixes a bug introduced in that PR.
Test case:
```python
ti.init(print_ir=True)
@ti.kernel
def func(i: ti.u32):
if i % 2 == 1:
print(i)
func(1)
```
Before:
```
<i32> $1 = const [1]
<u32> $2 = arg[0]
<u32> $3 = const [1]
<u32> $4 = bit_and $2 $3
<u32> $5 = sub $2 $4
<i32> $6 = cmp_eq $5 $3
<i32> $7 = bit_and $6 $1
$8 : if $7 {
print $2, "\n"
}
```
After:
```
<i32> $1 = const [1]
<u32> $2 = arg[0]
<u32> $3 = const [1]
<u32> $4 = bit_and $2 $3
<i32> $5 = cmp_eq $4 $3
<i32> $6 = bit_and $5 $1
$7 : if $6 {
print $2, "\n"
}
```
----
> [opt] [bug] Simplify modulo POT (Stage 2)

- Jenkinsfile
- docs/dev_install.rst
Related issue = #2417
The download link of llvm-10 in docs has changed to the version without libtinfo.
LLVM installation instruction also changed to disable libtinfo.
> [Doc] Changed llvm-10 link and installation instruction

- taichi/program/program.cpp
- taichi/struct/struct.cpp
- taichi/struct/struct.h
- taichi/struct/struct_llvm.cpp
- taichi/struct/struct_llvm.h
- tests/cpp/codegen/refine_coordinates_test.cpp
- tests/cpp/struct/fake_struct_compiler.h
> [ir] Move infer_snode_properties out from StructCompiler

- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
Related issue = #1174
This PR adds the GC kernels on Metal. It mostly follows the CUDA's three stage GC implementation.
----
> [metal] Add 3-stage GC Metal kernels

- examples/chi_examples/main.cpp
- python/taichi/lang/exception.py
- python/taichi/lang/impl.py
- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/ir/snode.h
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/program/arch.cpp
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/util/testing.h
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/transforms/alg_simp_test.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
- tests/cpp/transforms/inlining_test.cpp
- tests/cpp/transforms/simplify_test.cpp
Related issue = #2418
This PR refactors `Program` so that the LLVM runtime and SNode related initialization are separated into two functions: `initialize_llvm_runtime_system()` and `initialize_llvm_runtime_snodes()`. In the future, we should only call `initialize_llvm_runtime_system()` once globally, but call `initialize_llvm_runtime_snodes()` for each new SNode tree.
Several notes:
* PTX `.entry` vs `.func`: CUDA kernels are marked as `.entry` + `__glb__` in the PTX module. If not properly marked, `cuModuleGetFunction` won't be able to find this kernel. This is done around https://github.com/taichi-dev/taichi/blob/de3b2262de944cbf04e41fe0679e7e18eb242099/taichi/llvm/llvm_context.cpp#L544-L559
* Unified memory: #2427 
Also fully deprecate `ti.layout()` (FYI @yuanming-hu ) .
> [Lang] [refactor] Separate runtime and root initialization

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/struct_metal.cpp
- taichi/backends/metal/struct_metal.h
Related issue = #975, #1174
This kind of reverts #1028. Now that Metal has implemented a dynamic memory allocator, we no longer pre-allocate the runtime that can hold the maximum amount of list elements. Therefore `need_snode_lists_data` can be removed.
> [metal] Always initialize root SNode ListManager

- taichi/analysis/build_cfg.cpp
- tests/python/test_function.py
Related issue = #2193; fix #2442
This PR mainly adds `void visit(FuncCallStmt *stmt) override` to `CFGBuilder`. It also adds `struct CFGFuncKey`: note that the behavior of an inlined function is different when it's parallel executed or not (if not, a top-level range-for in the function will be parallel; otherwise it will be serial).
> [ir] [bug] Make control-flow graph take function call into account

- taichi/gui/win32.cpp
Set process DPI awareness when detecting system version less than 6.3 (Windows 8.1)
Related #2320
> [GUI] Win 32 DPI awareness stuff

- taichi/codegen/codegen_llvm.cpp
Related issue = fix #2446 
The code in the LLVM backend (including CPU and GPU) asserts there are no redundant casts (e.g., casting int32 to int32), but we should allow it when optimizations are not enabled. Other backends do not assert it.
> [bug] Fix assertion failure when there is a redundant cast

- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/metal/codegen_metal.cpp
Related issue = #2439
This should allow us to use the default GCC-7
> [bug] Fix linux detection macro

- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
Fix dumped runtime buffer size. Eliminate memory pool size.
Code clean off in aot module.
> [Metal] Fix dumped runtime buffer size

- taichi/backends/wasm/codegen_wasm.cpp
Related issue = LAN-42
The generated WASM module now ships with a `set_root()` function. This function sets WASM's linear memory so that `LLVMRuntime` and root buffer are placed at the right place.
> [WASM] Add set_root() for each WASM module

- .github/workflows/issue_comment.yml
- taichi/program/arch.h
Related issue = #2369
Intentionally mess up the format of `arch.h` to make sure this still works.
> [ci] Restrict slash-command-dispatch to PR only

- cmake/PythonNumpyPybind11.cmake
generate_commit_hash.py relies on `gitpython` to generate commit hash,
so we should check it in cmake and show the way to install it.
> [misc] Add checking of gitpython in cmake

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/features.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_utils.cpp
- taichi/backends/metal/kernel_utils.h
- taichi/program/extension.cpp
- taichi/program/program.cpp
- tests/python/test_function.py
- tests/python/test_gc.py
- tests/python/test_sparse_basics.py
- tests/python/test_sparse_deactivate.py
- tests/python/test_sparse_parallel.py
- tests/python/test_struct_for.py
- tests/python/test_struct_for_intermediate.py
- tests/python/test_test.py
> [Metal] Support pointer SNode on Metal

- taichi/backends/metal/kernel_manager.cpp
> [metal] [aot] Fix randseedoffset_in_runtime_buffer

- taichi/backends/cuda/codegen_cuda.cpp
Avoid redundant if-elses in `visit(AtomicOpStmt *stmt)` using a look-up table.
> [Refactor] [cuda] Cleanup CUDA AtomicOpStmt codegen

- python/taichi/lang/meta.py
- python/taichi/lang/transformer.py
- python/taichi/torch_io.py
> [misc] Import template and ext_arr and kernel in python code

- README.md
Fix outdated links of examples in README.md
> [doc] Fix outdated links of examples in README.md

- examples/rendering/cornell_box.py
cornell_box is thought to have significant CPU overhead issue. This is true, but only a part of the problem. The larger problem resides in the tonemapping code where a taichi field is transferred to a numpy field, where the mean and tonemapping is computed, and transferred into the GUI to display. Reducing all this chain into a taichi kernel brings significant performance improvement.
On RTX3080 + Ryzen 7 3700X, this specific example improved from 300 samples/s to 1000 samples/s
> [Example] Use Taichi instead of numpy to perform tonemapping & significantly lower CPU's work

- examples/rendering/cornell_box.py
I computed the variance of the accumulation buffer without dividing by the number of frames, causing variance to only grow over time. (This is a very dumb commit, I'm sorry that the last one has this oversight)
> [Example] Fix an oversight on the variance computation

- python/taichi/lang/impl.py
- python/taichi/lang/ops.py
- python/taichi/lang/transformer.py
> [Lang] Support very basic python string.format() now

- setup.py
- [Lang] Support very basic python string.format() now (#2552) (by **Jiasheng Zhang**)
- [vulkan] Add a simple memory allocator (#2556) (by **Ye Kuang**)
- [vulkan] Add Vulkan struct compiler and some helpers (#2550) (by **Ye Kuang**)
- [autodiff] Raise no gradient instead of attribute dim not found (#2542) (by **Mingrui Zhang**)
- [doc] Fix command typo in contributor guide (#2545) (by **Yi Xu**)
- [bug] Fix python detection on windows (#2528) (by **Hoildkv**)
- [Refactor] Use setup.py from root dir. (#2540) (by **Ailing**)
- [test] [bug] Avoid accessing negative indices (#2538) (by **Yi Xu**)
- [lang] Add a name parameter to fields (#2534) (by **ljss**)
- [refactor] Move snode tree maintainance out of python (#2530) (by **Jiasheng Zhang**)
- [Example] Fix an oversight on …
> [release] v0.7.27

- python/taichi/lang/matrix.py
Change the data layout for vector fields with `needs_grad = True`, so that the primal field always occupies a continuous region of memory.
> [Lang] Change the data layout for vector fields with that needs grad

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/common/trait.h
- taichi/ir/transforms.h
- taichi/transforms/detect_read_only.cpp
This is a (sort of) WIP PR.
In the OpenGL backend there are quite some overhead on kernel launch. These overheads can be categorized into two types:
1. Driver overhead
2. Synchronization / copy overhead
For the driver overhead, the main problem is the (unpredictable) cost of GL functions. Currently every frame the code creates a series of buffers, and then populate them with the host side data we want to pass in. This process not only involves C++'s RAII and related allocation overhead, it also calls `glGenBuffers` and `glDeleteBuffers` which do not have a predictable cost. The driver will do a lot of things behind, and therefore it is better to not allocating and reallocating resources every frame. This process should be managed internally since we know the details of these buffers, the …
> [Perf] Reduce GL backend's overhead (driver overhead & copy overhead)

- taichi/backends/opengl/opengl_api.cpp
This avoids a short popup everytime GL is initialized.
Tiny PR, no related issue
> [opengl] Use OpenGL window visible hint instead of hiding after creation.

- python/taichi/lang/impl.py
- python/taichi/lang/snode.py
- python/taichi/snode/fields_builder.py
Related issue = #2579
In addition to the docstring itself, this PR serves as an example for how to do class/method referencing.
> [Doc] Add Python docstring for SNode

- taichi/ir/frontend.h
- taichi/python/export_lang.cpp
Related issue = #2560 
I took another pass and found a few places where we didn't need to rename. Note that `ExprGroup` is indeed a group of indices (aka a coordinate) 
FYI @cruedo
> [refactor] Correct a few indices->axes renamings

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/backends/opengl/shaders/reduction.glsl.h
- Reduces traffic to L2
- (In theory) better performance
- Did not use vendor specific warp/subgroup extensions
- Did not use the subgroup ballot extension
- Used a shared memory implementation (which is in L1)
> [opengl] Work group reduction

- python/taichi/lang/ops.py
Fix return type of Python Docstring in ops.py
> [Doc] Fix return type of Python Docstring in ops.py

- taichi/backends/vulkan/spirv_ir_builder.h
Currently, the vulkan backend is failing sporadically on my Windows machine for all taichi programs that uses `ti.random()` (e.g. `mpm88`, `pbf2d`). This is because the variable `init_rand_` isn't explicitly initialised to be `false`, and thus `init_random_function` isn't always called.
> [vulkan] Fix vulkan rand

- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- taichi/backends/vulkan/spirv_snode_compiler.cpp
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
The current performance issue is entirely from the host/device transfer.
Originally, the `host_visible` memory pool is allocated actually on host & is cached. This means this chunk of memory is very fast when mapping (since no mapping is really there, it's host memory), but GPU has a hard time read / write on it.
Now the arguments and the return buffer are now on the `host_visible` and at the same time `device_local` memory. This is a special memory heap for sending arguments where host can directly write to it (and pay a small cost), and GPU can directly read/write off it. However this memory type is very slow when reading from host since it is not cached. (This is essentially the PCI-E BAR, and recently improved as ReBAR or SAM). So when we read back the return value, the context buffer …
> [vulkan] Use native struct types when supported & fix performance

- .github/workflows/release.yml
- python/build.py
- setup.py
This PR does 2 things: 
- Fix path issues in osx release workflow and stop using `TAICHI_REPO_DIR`
- Install from the wheel and run tests (instead of running tests in dev mode). 
There's a minor followup:
- Our changelog requires installing taichi but building taichi wheel requires making changelog. So currently we keep installing taichi using `python setup.py install` to first build the wheel and then uninstall it. Ideally this can be removed so that we just build a wheel -> install the wheel -> test taichi installed from wheel.
> [Bug] Fix osx release workflow.

- docs/lang/articles/advanced/meta.md
Minor doc fix; I believe intent here was "Size along dimension"
> [doc] meta: s/alone/along/

- examples/simulation/math_utils.py
Related issue = fix #2617
I think we should also update the docs about the restrictions on list comprehensions and dictionary comprehensions but I don't know which page to put them...
> [bug] Fix missing ti.template() in rand_vector(n) in examples

- python/taichi/lang/expr_builder.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/stmt_builder.py
- python/taichi/lang/transformer.py
Changeset:
- Deprecate `maybe_transform_ti_func_call_to_stmt` and split its logic into StmtBuilder and ExprBuilder
- Remove the pass transforming function calls to `maybe_transform_ti_func_call_to_stmt`
- Add a method `insert_expr_stmt_if_ti_func` to check if a function is Taichi function at Python runtime (we cannot check it in StmtBuilder). This method is called only when `experimental_real_function=True` and the Python statement contains only one expression which is the function call. So there will be no redundant calls like `maybe_transform_ti_func_call_to_stmt` before this PR.
- Remove an unused field `is_classfunc`
- Rename `ASTTransformer` to `ASTTransformerTotal`
> [Refactor] Split transformer.py into StmtBuilder and ExprBuilder (Stage 2)

- benchmarks/misc/baseline_fill.py
- benchmarks/misc/baseline_reduction.py
- docs/lang/articles/misc/profiler.md
- examples/algorithm/mgpcg.py
- examples/algorithm/mgpcg_advanced.py
- misc/async_mgpcg.py
- misc/benchmark_bit_struct_stores.py
- misc/benchmark_parallel_compilation.py
- misc/benchmark_reduction.py
- misc/benchmark_scatter_bls.py
- python/taichi/lang/__init__.py
- python/taichi/misc/util.py
- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
- taichi/program/program.h
- taichi/python/export_lang.cpp
- tests/python/bls_test_template.py
Related issue = #2579
Add docstring for:
```
kernel_profiler_print() 
kernel_profiler_clear()
kernel_profiler_total_time()
memory_profiler_print()
query_kernel_profiler()
```
Rename:
```
kernel_profiler_print() >>> print_kernel_profile_info()
kernel_profiler_clear() >>> clear_kernel_profile_info()
memory_profiler_print() >>> print_memory_profile_info()
query_kernel_profiler() >>> query_kernel_profile_info()
```
(and mark old names as deprecated)
misc:
Execute sync() before clear() & query() in kernel_profiler APIs
> [misc] [doc] Rename some profiler APIs and add docstring, mark old names as deprecated

- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- python/build.py
> [ci] Fix mac release and integrate windows release into github

- cmake/TaichiCore.cmake
Related issue = #2298
I got a undefined symbol error on Linux/Vulkan, this change made things working for me and I got taichi demo working on my laptop AMD APU with vk backend!
cc @bobcao3 @k-ye
> [Vulkan] Improved SPIRV-Tools library search on Linux

- taichi/backends/cuda/cuda_driver.h
- taichi/backends/cuda/cuda_driver_functions.inc.h
- taichi/backends/cuda/cuda_types.h
- taichi/common/serialization.h
Related Issue = #2646
This is the 1st of a series of PRs that adds a GPU-based GUI to taichi. This PR adds the necessary cuda structs, enums, and functions.
> [gui] GGUI 1/n: Add necessary cuda structs/enums/functions

- taichi/backends/vulkan/loader.cpp
- taichi/backends/vulkan/loader.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
This is the 2nd of a series of PRs that adds a GPU-based GUI to taichi. This PR adds an optional graphics queue, compute queue, and surface to EmbeddedVulkanDevice.
> [gui] GGUI 2/n: Add optional graphics queue, compute queue, and surface to EmbeddedVulkanDevice

- python/taichi/lang/expr.py
- python/taichi/lang/ext_array.py
- python/taichi/lang/field.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/snode.py
- python/taichi/lang/stmt_builder.py
Previously, things around external arrays are implemented under `Expr` class, which is not intuitive because `Expr` class should represent a scalar supporting `TaichiOperations`. This PR mostly involves slight code migration and internal API changes. After this PR, `Expr` class will become (hopefully) clean.
> [lang] [refactor] Add a ExtArray class for external arrays

- .gitmodules
- cmake/TaichiCore.cmake
- taichi/ui/common/app_config.h
- taichi/ui/common/camera.h
- taichi/ui/common/canvas_base.h
- taichi/ui/common/event.h
- taichi/ui/common/field_info.h
- taichi/ui/common/gui_base.h
- taichi/ui/common/input_handler.h
- taichi/ui/common/renderable_info.h
- taichi/ui/common/scene_base.h
- taichi/ui/common/window_base.cpp
- taichi/ui/common/window_base.h
- taichi/ui/utils/utils.h
This is the 3rd of a series of PRs that adds a GPU-based GUI to taichi. This PR adds dependencies (dear imgui and glm), APIs, and all the non-vulkan-related code.
> [gui] GGUI 3/n: Add dependencies, interfaces, and backend-independent code

- .github/workflows/presubmit.yml
- misc/ci_setup.py
- python/build.py
- requirements_dev.txt
> [ci] Change build method of ci tests

- taichi/transforms/ir_printer.cpp
`ExternalTensorShapeAlongAxisStmt` has explicit return value but has not be shown by IR print yet, which would confuse developers. This PR fixed this.
The previous IR print result:
```
external_tensor_shape_along_axis 0, arg_id 0
```
Now:
```
<i32> $1 = external_tensor_shape_along_axis 0, arg_id 0
```
> [ir] Improve ExternalTensorShapeAlongAxisStmt IR print result

- setup.py
- [ir] Improve ExternalTensorShapeAlongAxisStmt IR print result (#2665) (by **Yu Chang**)
- [ci] Refined release procedures (#2663) (by **Jiasheng Zhang**)
- [vulkan] More capabilities detection and enabling (#2660) (by **Bob Cao**)
- [ci] Change build method of ci tests (#2661) (by **Jiasheng Zhang**)
- [gui] GGUI 3/n: Add dependencies, interfaces, and backend-independent code (#2650) (by **Dunfan Lu**)
- [lang] [refactor] Add a ExtArray class for external arrays (#2651) (by **Yi Xu**)
- [ci] Enable torch tests during CI (#2656) (by **Yi Xu**)
- [ci] Add cuda bin folder to PATH (#2655) (by **Dunfan Lu**)
- [gui] GGUI 2/n: Add optional graphics queue, compute queue, and surface to EmbeddedVulkanDevice (#2648) (by **Dunfan Lu**)
- [vulkan] Build and test Vulkan backend in …
> [release] v0.7.29

- taichi/backends/device.h
- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
- Added the very first initial piece of Device API and moving capability queries to that. (So now the codegen is decoupled from the runtime)
- Query & enable features properly (previously we don't query the feature support within an extension, e.g. a device may support f16 but not i8)
> [vulkan] Querying features like a mad man

- taichi/common/core.cpp
- taichi/common/core.h
- taichi/common/logging.cpp
- taichi/system/threading.cpp
- taichi/system/threading.h
* __->__ #2678
PID struct seems pretty self-contained so let's move it to
core.h/core.cpp in taichi/common/. This ensures no dependency from
taichi/common to taichi/system. This PR also re-enables the developer
feature that automatically attaching when crash happens.
> [Refactor] Re-enable gdb attach on crash.

- taichi/common/core.cpp
- taichi/common/core.h
- taichi/common/logging.cpp
- taichi/system/threading.cpp
- taichi/system/threading.h
* __->__ #2681
PID struct seems pretty self-contained so let's move it to
core.h/core.cpp in taichi/common/. This ensures no dependency from
taichi/common to taichi/system. This PR also re-enables the developer
feature that automatically attaching when crash happens.
> [Refactor] Re-enable gdb attach on crash

- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/ndarray.py
- tests/python/test_get_external_tensor_shape.py
- tests/python/test_ndarray.py
Usage:
```
a = ti.ndarray(ti.i32, shape=(n, m)) // by default torch tensor is used
// arbitrary initialization using numpy arrays and torch tensors is also supported
b = ti.Ndarray(np.empty(shape=(n, m), dtype=np.int32))
c = ti.Ndarray(torch.empty((n, m), dtype=torch.int32))
```
When passing it to Taichi kernels, you need to annotate it as `ti.ext_arr()` for now.
> [Lang] Add a Ndarray class to serve as an alternative to dense scalar fields

- .github/workflows/presubmit.yml
- taichi/gui/gui.h
- taichi/lang_util.cpp
- taichi/lang_util.h
- taichi/llvm/llvm_context.cpp
taichi_cpp_tests used to depend on `TAICHI_REPO_DIR` and thus only runs
in dev mode. This PR decouples them, instead we explicitly ask users to
pass in `TI_LIB_DIR` if they want to run the cpp tests.
Note this PR will unblock `TAICHI_REPO_DIR` and is_release check removal in the codebase.
Also instead of a crash report, we'll properly throw an error
message to remind setting `TI_LIB_DIR` when running cpp tests.
```
[E 08/14/21 14:34:16.990 2077742] [lang_util.cpp:runtime_lib_dir@25]
If you are running the taichi_cpp_tests please set TI_LIB_DIR to
$TAICHI_INSTALL_DIR/lib where TAICHI_INSTALL_DIR can be retrieved from
taichi.__path__ in python
```
> [Refactor] Allow taichi_cpp_tests run in release mode as well.

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/cuda_driver.h
- taichi/backends/cuda/cuda_driver_functions.inc.h
- tests/python/test_torch_io.py
This PR is pretty self contained and came from a discussion with @k-ye. 
I added a new test in test_torch_io.py since we only test cpu arch there, so I want to make sure cuda arch is tested. 
Note to self: I had indeterministic crash when I first tested this PR and crash also happened on master branch. After some time I was no longer able to reproduce the crash so I guess it was due to my GPU in a weird state but not related to this PR. 
Leaving a note here just in case if happens again in the future.
> [CUDA] Save an extra host to device copy if arg_buffer is already on device.

- python/taichi/core/util.py
- python/taichi/diagnose.py
- taichi/common/core.cpp
- taichi/common/core.h
- taichi/python/export_misc.cpp
This PR removes runtime dependency on `TAICHI_REPO_DIR` in the codebase. 
Known followups:
- There's a use of `TAICHI_REPO_DIR` in `python/ti.cpp` which is used by
windows. I'll skip it for now.
- Need to cleanup `TAICHI_REPO_DIR` in docs and examples.
> [Refactor] Make is_release always True and delete runtime dep on TAICHI_REPO_DIR

- setup.py
Our default build of taichi_core.so only has symbol information but not lineno. 
With DEBUG=1 taichi_core.so will keep both debug symbols and line numbers. Now that when we gdb, we can set breakpoints to filename:lineno which is much more convenient. 
Example backtrace: 
```
Thread 1 "python" hit Breakpoint 1, taichi::lang::irpass::compile_to_offloads (ir=0x55555a74bc10, config=..., kernel=0x55555a7a8d70,
verbose=true, vectorize=false, grad=false, ad_use_stack=true, start_from_ast=true)
at /home/ailing/github/taichi/taichi/transforms/compile_to_offloads.cpp:42
42        auto print = make_pass_printer(verbose, kernel->get_name(), ir);
(gdb) bt
#0  taichi::lang::irpass::compile_to_offloads (ir=0x55555a74bc10, config=..., kernel=0x55555a7a8d70, verbose=true, vectorize=false,
grad=false, …
```
> [Misc] Keep debug symbols/line numbers in taichi_core.so by setting DEBUG=1

- setup.py
The first nightly release has failed because the version does not meet the requirement of PyPi.
```
<title>400 '0.7.29.2021-08-17.899707f' is an invalid value for Version. Error: Start and end with a letter or numeral containing only ASCII numeric and '.', '_' and '-'. See https://packaging.python.org/specifications/core-metadata for more information.</title>
```
As PyPi requires versioning of projects meets the PEP440 standards, which does not allow commit hash in project version, I discard adding commit hash in nightly versions and made version meet PEP440 standards.
```
DVCS based version labels
Many build tools integrate with distributed version control systems like Git and Mercurial in order to add an identifying hash to the version identifier. As hashes cannot be ordered reliably …
```
> [ci] Fixed pypi version

- .github/workflows/presubmit.yml
- docs/lang/articles/contribution/contributor_guide.md
- requirements.txt
- requirements_dev.txt
Recently noticed that `yapf` in the code format server no longer pins to 0.29. Changing yapf version is pretty annoying to dev workflow so let's pin it to the current version in the code format server (which is 0.31.0). 
Nit: I'm not sure if yapf should be a dependency for taichi user, maybe we can remove it from requirements.txt.
> [ci] Pin yapf version to 0.31.0.

- .github/workflows/presubmit.yml
- docs/lang/articles/contribution/contributor_guide.md
- python/taichi/code_format.py
We were using system default which is clang-format-10 before. Let's still fix it to 6.0.
> [ci] Fix clang-format version to 10

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/system/snode_tree_buffer_manager.cpp
- taichi/system/snode_tree_buffer_manager.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* __->__ #2742
snode_tree_buffer_manager is only used by LLVM backends so moving it to
LlvmProgramImpl first.
> [Refactor] Move snode_tree_buffer_manager into LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* __->__ #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move print_list_manager_info to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* __->__ #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move print_memory_profiler_info to LlvmProgramImpl.

- python/taichi/core/util.py
- python/taichi/lang/__init__.py
- taichi/llvm/llvm_context.cpp
- taichi/python/export_lang.cpp
Now when you import taichi, we'll only show:
```
>>> import taichi
[Taichi] version 0.7.29, llvm 10.0.0, commit e719c60a, linux, python 3.8.11
```
We'll prepare a sandbox when you initialize only on **cc backend**:
```
>>> ti.init(arch=ti.cc)
[Taichi] preparing sandbox at /tmp/taichi-osr4s9x5
[Taichi] Starting on arch=cc
```
fixes #2714.
> [Refactor] Only prepare sandbox for cc backend.

- taichi/ui/backends/vulkan/app_context.cpp
- taichi/ui/backends/vulkan/app_context.h
- taichi/ui/backends/vulkan/swap_chain.cpp
- taichi/ui/backends/vulkan/swap_chain.h
This is the 6th of a series of PRs that adds a GPU-based GUI to taichi.
This PR adds two classes, both of which are thin wrappers around classes in the device api:
1. Swap Chain, which owns a VulkanSurface object, as well as a DeviceAllocation, which is used as the depth buffer.
2. App Context, which keeps track of the app config, and owns an EmbeddedVulkanDevice object.
side note, look how much smaller this PR is compared to #2700 ! props to our device api
> [gui] GGUI 6/n: App context and swap chain

- python/taichi/__init__.py
- python/taichi/lang/__init__.py
- python/taichi/lang/enums.py
- python/taichi/lang/ext_array.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/matrix.py
- python/taichi/lang/stmt_builder.py
- tests/python/test_matrix.py
- tests/python/test_new_allocator.py
Related issue = #2223
Discussed in #2727 Review
Reasons:
- Make `Layout` an `Enum` class: Using `Enum` is more clear and extensible than using a class with a bool inside.
- Move `Layout` away from `impl.py`: Avoid circular import when we want to set default parameter values to some layout (previously it was hacked with a `None` value); Avoid exposing everything directly under `ti`.
Effects:
- Now users need to use `ti.Layout.AOS/SOA`. `ti.AOS/SOA` is still available but marked as deprecated.
Side Effects:
- A new way to handle deprecated names is implemented. We only need to directly add the mapping to `deprecated_names` in `taichi/__init__.py`.
> [Refactor] Make Layout an Enum class and move it away from impl.py

- taichi/ui/backends/vulkan/renderables/kernels.cu
- taichi/ui/backends/vulkan/renderables/kernels.h
- taichi/ui/backends/vulkan/vertex.h
This is the 7th of a series of PRs that adds a GPU-based GUI to taichi.
This PR adds a `Vertex` class, and the cuda/x64 kernels that will be used to update the VBOs/IBOs/textures created by the rendering api.
> [gui] GGUI 7/n: Vertex class, and kernels for updating VBO/IBO/texture

- setup.py
- [gui] GGUI 7/n: Vertex class, and kernels for updating VBO/IBO/texture (#2797) (by **Dunfan Lu**)
- [Refactor] Make Layout an Enum class and move it away from impl.py (#2774) (by **Yi Xu**)
- app context and swap chain (#2794) (by **Dunfan Lu**)
- [Refactor] Move snode_tree_buffer_manager and llvm_runtime to private. (by **Ailing Zhang**)
- [Refactor] Move llvm_context_host/device to private. (by **Ailing Zhang**)
- [Refactor] Further cleanup Program constructor. (by **Ailing Zhang**)
- [Refactor] Move check_runtime_error to LlvmProgramImpl. (by **Ailing Zhang**)
- [Refactor] Simplify synchronize and materialize_runtime in Program. (by **Ailing Zhang**)
- [gui] GGUI 5/n: remove some stuff (#2793) (by **Dunfan Lu**)
- [ci] Added gpu test timeout (#2791) (by **Jiasheng …
> [release] v0.7.30

- taichi/ui/backends/vulkan/canvas.cpp
- taichi/ui/backends/vulkan/canvas.h
- taichi/ui/backends/vulkan/vulkan_cuda_interop.cpp
- taichi/ui/backends/vulkan/window.cpp
- taichi/ui/backends/vulkan/window.h
This is the 12th of a series of PRs that adds a GPU-based GUI to taichi.
This PR adds a `Window` class which implements the `WindowBase` interface. It owns a renderer, a canvas, and a GUI.
The PR also adds a `Canvas` class which implements `CanvasBase`. The `Canvas` simply forwards calls to `Renderer`.
The PR also includes a small fix for a bug introduced in a previous PR..
> [gui] GGUI 12/n: Window and Canvas

- .github/workflows/release.yml
I used conditional matrix setup to solve this issue.
Another workaround would be cancel workflow when python version is not equal to 3.8. However, this would show up as action failed. Therefore, I choose to use setup matrix with respect to release type.
> [ci] Conditional build matrix on release

- taichi/backends/device.h
- taichi/backends/vulkan/vulkan_device.cpp
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPresentModeKHR.html
```VK_PRESENT_MODE_FIFO_RELAXED_KHR specifies that the presentation engine generally waits for the next vertical blanking period to update the current image. If a vertical blanking period has already passed since the last update of the current image then the presentation engine does not wait for another vertical blanking period for the update, meaning this mode may result in visible tearing in this case. This mode is useful for reducing visual stutter with an application that will mostly present a new image before the next vertical blanking period, but may occasionally be late, and present a new image just after the next vertical blanking period. An internal queue is used to hold pending …
```
> [Vulkan] Add relaxed FIFO presentation mode

- python/taichi/lang/ops.py
Related issue = 
this pr basically let `ti.rescale_index` support `SNode` as input parameter. The reason is that sometimes an `SNode` might not have '**placed**' a `Field` but we want to rescale the cell index based on the `SNode` anyway.
See the [example](https://github.com/Jack12xl/taichi_elements/blob/8c4a16cc0bfb45a667ec0d62e248c445bcea53e2/engine/mpm_solver.py#L321) from the **Taichi_elements**. We need to rescale the index from `pid(ti.root.pointer.pointer.dynamic)` to `block(ti.root.pointer.pointer)`. But `block` did not have a cell placed beneath (but we still need to rescale according to `block`).
> [Lang] Let rescale_index support SNode as input parameter

- examples/ggui_examples/fem128_ggui.py
- examples/ggui_examples/mass_spring_3d_ggui.py
- examples/ggui_examples/mass_spring_game_ggui.py
- examples/ggui_examples/mpm128_ggui.py
- examples/ggui_examples/mpm3d_ggui.py
- examples/ggui_examples/stable_fluid_ggui.py
This is the 16th of a series of PRs that adds a GPU-based GUI to taichi.
This PR adds 6 example applications that uses ggui. 
* `mpm128`, `fem128`, `stable_fluid`, `mass_spring_game`:  These examples demonstrate how existing `ti.gui` 2D apps can be re-written in ggui.
* `mass_spring_3d` demonstrates how to draw 3d meshes using ggui (the existing version of `mass_spring_3d` in taichi uses taichi-THREE for that)
* `mpm3d` demonstrates how to draw 3d particles and how to use IMGUI components.
> [gui] GGUI 16/n: examples

- docs/lang/articles/misc/ggui.md
This is the 17th of a series of PRs that adds a GPU-based GUI to taichi.
This PR adds an article that introduces GGUI APIs.
> [gui] GGUI 17/n: doc

- .github/workflows/presubmit.yml
I've occasionally seen M1 job hanging in some tests and finally timed out. Enabling verbose option here so that we can have more information about the hang.
> [ci] Enable verbose on M1 CI to collect more info on hanging jobs.

- python/taichi/aot/module.py
- python/taichi/lang/any_array.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/stmt_builder.py
Related issue = #2772
Now `ti.any_arr` annotation is added, and `ti.ext_arr` is for backward compatibility and indeed a special case of `ti.any_arr` with no support for element shape. In this PR, I would like to remove all the duplicated code and directly turn a `ti.ext_arr` into a `ti.any_arr` with only default arguments. This aims for better code maintainability.
> [refactor] Make ti.ext_arr a special case of ti.any_arr

- taichi/llvm/llvm_program.cpp
Related issue = #2781
>Previously, I encountered a segfault with a null pointer ( `profiler` ). I will move the code back and try to solve the problem
_Originally posted by @yolo2themoon in https://github.com/taichi-dev/taichi/pull/2848#discussion_r698975565_
run this example
```
ti.init(ti.cuda, kernel_profiler=True)
var = ti.field(ti.f32, shape=1)
@ti.kernel
def compute():
var[0] = 1.0
compute()
ti.print_kernel_profile_info()
```
before this commit
```
CUDA Profiler
=========================================================================
[ % total count | min avg max ] Kernel name
-------------------------------------------------------------------------
[100.00%] Total kernel execution time: 0.000 s number of records: 0 …
```
> [LLVM] [bug] fix typo of PR #2781

- setup.py
- [doc] Remove links from documentation articles to API reference (#2866) (by **Chengchen(Rex) Wang**)
- [Lang] Support struct fors on ti.any_arr (#2857) (by **Yi Xu**)
- [ci] M1 release (#2855) (by **Jiasheng Zhang**)
- [Doc] Update the API reference section. (#2856) (by **Chengchen(Rex) Wang**)
- [LLVM] [Bug] fix typo of PR #2781 (#2854) (by **rocket**)
- [Vulkan] Use reference counting based wrapper layer (#2849) (by **Bob Cao**)
- [gui] Two sided mesh (#2851) (by **Dunfan Lu**)
- [refactor] Make ti.ext_arr a special case of ti.any_arr (#2850) (by **Yi Xu**)
- [Lang] Add ti.Vector.ndarray and ti.Matrix.ndarray (#2808) (by **Yi Xu**)
- [ci] No need to specify arch on M1 CI. (#2845) (by **Ailing**)
- [Lang] Customized struct support (#2627) (by **Andrew Sun**)
- [Lang] …
> [release] v0.7.31

- taichi/transforms/offload.cpp
- tests/python/test_global_buffer_misalined.py
Related repo = [karman_taichi](https://github.com/houkensjtu/karman_taichi)
When trying to run this repo with cuda backend, we encountered
`CUDA Error CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address while calling stream_synchronize (cuStreamSynchronize)`
---
Taichi stores some temporary variables into a global buffer ( memory ),
and the problem is caused by the access address is not aligned.
For example,  we have a 16-byte buffer with 3 elements : `[i32,f64,f32]` = `[4B,8B,4B]` ,  
Although the buffer size is 8-byte aligned , the `address offset of f64` = `sizeof(i32) = 4` is not a multiple of 8.
In this case，the above error is encountered.
If the 16-byte buffer is : `[i32,f32,f64]` = `[4B,4B,8B]` ,
the `address offset of f64` = `sizeof(i32) + sizeof(f32) = 4 + 4 = 8` is a multiple of 8 …
> [CUDA] [bug] Fix CUDA error "allocate_global (DataType type) misaligned address"

- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/ndarray.py
- tests/python/test_matrix.py
- tests/python/test_mpm88.py
- tests/python/test_ndarray.py
Related issue = #2772
Changes:
- For external arrays, we can treat it as a Taichi field with Vector or Matrix elements by specifying element **dim** (instead of **shape**) and layout.
- For Taichi vector/matrix ndarrays, we will **automatically** identify element dim and layout. If they are explicitly specified, we will check compatibility between the actual arguments and the annotation.
> [Lang] Refine semantics of ti.any_arr

- taichi/inc/constants.h
- taichi/program/context.h
This PR aims at increasing the number of arguments allowed in a kernel in the LLVM backend (for user requirements). However, this is a temporary solution which may make the context a bit larger and not fully utilized. A better way for argument passing needs to be utilized in the future.
> [Llvm] Increase the number of arguments allowed in a kernel

- taichi/transforms/offload.cpp
Related issue = close #2884
Previously, `GlobalPtrStmt` is not put into global tmp buffer due to lack of support for pointers to pointers. Same thing should also happen to other pointers including `ExternalPtrStmt` and `ArgLoad` (if the arg is a pointer) so that bug #2884 can be resolved.
> [bug] [opt] Disable putting pointers into global tmp buffer

- conda/conda_env.yaml
Related issue = null
When I follow the comment to create conda env, there's an error like this:
```
EnvironmentFileNotFound: 'taichi/conda/conda-env.yaml' file not found
```
This PR is to fix the typo in conda_env.yaml
> [Misc] Fix the path in conda_env.yaml

- setup.py
- [vulkan] Turn off Vulkan by default and add dev install instructions (#2897) (by **Dunfan Lu**)
- [Misc] Fix the path in conda_env.yaml (#2895) (by **Ce Gao**)
- [ci] Rollback buggy Dockerfile (by **Dunfan Lu**)
- [bug] [opt] Disable putting pointers into global tmp buffer (#2888) (by **Yi Xu**)
- [Llvm] Increase the number of arguments allowed in a kernel (#2886) (by **Yi Xu**)
- [gui] GGUI fix undefined variable (#2885) (by **Mingrui Zhang**)
- [ci] Build and Release Vulkan in CI/CD (#2881) (by **Dunfan Lu**)
- [Lang] Refine semantics of ti.any_arr (#2875) (by **Yi Xu**)
- [refactor] OpenGL program impl (#2878) (by **Dunfan Lu**)
- [refactor] Vulkan program impl (#2876) (by **Dunfan Lu**)
- Clean up sparse matrix (#2872) (by **squarefk**)
- Re-enable sfg test on CUDA …
> [release] v0.7.32

- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_profiler.cpp
- taichi/backends/cuda/cuda_profiler.h
- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
Move the backend-related class `KernelProfilerCUDA` 
from `program/kernelprofiler.cpp` to `backends/cuda/cuda_profiler.cpp` .
Keep back-end features from being exposed to `program/` 
Provide better encapsulation
> [refactor] [CUDA] Move KernelProfilerCUDA from program/kernel_profiler.cpp to backends/cuda/cuda_profiler.cpp

- taichi/backends/cuda/cuda_profiler.cpp
- taichi/backends/cuda/cuda_profiler.h
- taichi/program/kernel_profiler.cpp
- taichi/program/kernel_profiler.h
Related issue = #2902
**Concisely describe the proposed feature**
Taichi counts profiling records and stores the results in `KernelProfileRecord` directly (StatisticalResult).
But didn't allocate space to store raw data (TracedRecord).
Code in `KernelProfilerCUDA::sync()` is somewhat complicated
**Describe the solution you'd like**
Add a new structure, `KernelProfileTracedRecord` to store traced records.
Rename the old structure from `KernelProfileRecord `to `KernelProfileStatisticalResult`
Decouple the code in `KernelProfilerCUDA::sync()` into 5 parts:
-  sync
-  get&store traced kernel_elapsed_time ( new feature )
-  statistics on traced_records_
-  code for Timelines
-  clear temporary records
> [refactor] [CUDA] Add traced_records_ for KernelProfilerBase, refactoring KernelProfilerCUDA::sync()

- netlify.toml
Worked with @rexwangcc together to set this up.
If files under docs are changed, this will build and preview the doc
site. Otherwiise it'll ignore the build.
Note this only covers the articles for now (not the api doc).
> [Doc] Enable deploy preview if changes are detected in docs.

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- tests/python/test_bitmasked.py
- tests/python/test_struct_for_intermediate.py
Related issue = #2804 
I will use a smaller example compared to #2804 , so that the entire runtime information can be analyzed easily.
```py
ti.init(arch=ti.metal, print_ir=True)
some_val = ti.field(dtype=int)
width, height = 2, 3
ptr = ti.root.bitmasked(ti.ij, (width, height))
ptr.place(some_val)
num_active = ti.field(dtype=int, shape=())
@ti.kernel
def init():
num_active[None] = 0
for x, y in ti.ndrange(width, height):
some_val[x, y] = x * 3 + y
num_active[None] += 1
@ti.kernel
def run():
num_active[None] = 0
for x, y in some_val:
print('x=', x, 'y=', y)
num_active[None] += 1
init()
print('num activated', num_active[None])
run()
print("active = ", num_active[None])
```
1. `init() `
`init()` iterates over a 2D range of `(width, height)`. Internally, this gets …
> [metal] Fix upperbound for list-gen and struct-for

- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_profiler.cpp
- taichi/backends/cuda/cuda_profiler.h
- taichi/backends/cuda/cupti_toolkit.cpp
- taichi/backends/cuda/cupti_toolkit.h
- taichi/program/kernel_profiler.h
Related issue = #2909 #2902
The implementation of CuptiToolkit will be added in the next PR.
The code in sync() is now more abstract:
```
void KernelProfilerCUDA::sync() {
// sync
CUDADriver::get_instance().stream_synchronize(nullptr);
// update
if (tool_ == ProfilingToolkit::event) {
event_toolkit_->update_record(traced_records_);
event_toolkit_->update_timeline(traced_records_);
statistics_on_traced_records();
event_toolkit_->clear();
} else if (tool_ == ProfilingToolkit::cupti) {
cupti_toolkit_->calculate_metric_values();
statistics_on_traced_records();
cupti_toolkit_->end_profiling();
cupti_toolkit_->deinit_cupti();  
// reinit is necessary to get accurate  result
cupti_toolkit_->init_cupti();  // data image will be cleared
cupti_toolkit_->begin_profiling();
}
}
```
> [refactor] [CUDA] Wrap the default profiling tool as EventToolkit , add a new class for CUPTI toolkit

- .github/workflows/release.yml
Looks like our nightly release started to fail randomly, this PR automatically creates an ssh session **when it fails** so that we can debug from there.
> [ci] Enable tmate session if release test fails.

- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/backends/opengl/opengl_program.cpp
- taichi/backends/opengl/opengl_program.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program_impl.h
Looks like this is already done in
https://github.com/taichi-dev/taichi/blob/master/taichi/program/snode_expr_utils.cpp#L69
for all backends. So `materialize_snode_expr_attributes` seems
redundant.
> [llvm] Remove duplicated set dim attribute for GlobalVariableExpression in LLVM

- python/taichi/lang/kernel_impl.py
This PR doesn't change program behavior. Instead, it exchanges two variable names which are put in opposite positions which may make people confused while reading the code.
> [refactor] Exchange compiled_grad_functions and compiled_functions in kernel_impl.py

- python/taichi/lang/kernel_impl.py
- python/taichi/lang/stmt_builder.py
- tests/python/test_function.py
According to https://docs.taichi.graphics/docs/lang/articles/basic/syntax#advanced-arguments-1, we can use `ti.template()` as type-hint to force arguments to be passed by reference to `ti.func`. However, current implementation doesn't match this description. This PR aims at fixing this mismatch.
Example:
```python
@ti.func
def my_func(x: ti.template()):
x = x + 1  # will change the original value of x
@ti.kernel
def my_kernel():
x = 233
my_func(x)
print(x)  # 234
```
> [Lang] Fix ti func with template and add corresponding tests

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
`ti.Matrix.__init__` has many arguments which have been deprecated (and should have been obsolete) for a long time. This PR cleans them up.
> [Lang] Remove deprecated usage of ti.Matrix.__init__

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
Related issue = #2736
Move the old GL runtime (opengl_api.cpp) to Device API. This commit did not really change the runtime itself and therefore another PR is needed to decouple GLSL codegen with GL runtime
> [opengl] Move old runtime onto Device API

- taichi/analysis/alias_analysis.cpp
- tests/python/test_reduction.py
Related issue = #2487, #2951
This PR adds conservative alias analysis for `ExternalPtrStmt`, which will unblock potential optimization opportunity such as #2487 for `ti.any_arr` arguments.
Let's try an example illustrating the optimization of #2487:
```python
ti.init(ti.cuda, kernel_profiler=True)
n = 1024 * 1024 * 32
x = ti.ndarray(ti.i32, n)
s = ti.field(ti.i32, ())
@ti.kernel
def reduce(a: ti.any_arr()):
ti.atomic_add(s[None], a[i])
reduce(x)
ti.clear_kernel_profile_info()
for i in range(100):
reduce(x)
ti.print_kernel_profile_info()
```
Profiling result before this PR:
```
CUDA Profiler
=========================================================================
[      %     total   count |      min       avg       max   ] Kernel name
[100.00% …
```
> [opt] Add conservative alias analysis for ExternalPtrStmt

- setup.cfg
- setup.py
* **#2962**
* #2961
```
$ python setup.py clean
running clean
removing '/Users/ailzhang/github/taichi/build' (and everything under it)
removing 'bin' (and everything under it)
removing 'python/taichi/assets' (and everything under it)
removing 'python/taichi/lib' (and everything under it)
removing 'python/taichi/examples' (and everything under it)
removing 'python/taichi/tests' (and everything under it)
removing 'python/taichi.egg-info' (and everything under it)
removing generated file taichi/common/commit_hash.h
removing generated file taichi/common/version.h
removing generated file taichi/runtime/llvm/runtime_arm64.bc
removing generated file taichi/runtime/llvm/runtime_arm64.ll
$ python setup.py clean --dry-run
```
Note this …
> [misc] Support clean command in setup.py.

- taichi/python/export_lang.cpp
> [Bug] Add GIL that was accidentally removed in PR #2939 back

- taichi/ir/type_utils.h
- taichi/transforms/make_thread_local.cpp
- tests/python/test_reduction.py
Related issue = #2487, #2951, #2952
Previously, only atomic add/sub are supported in warp reduction optimization. This PR aims at also supporting atomic min/max.
Thanks @yolo2themoon for providing the following example:
```python
ti.init(kernel_profiler=True, arch=ti.cuda)
n = 2048 * 2048 * 2
a1 = ti.ndarray(ti.f32, n)
a2 = ti.ndarray(ti.f32, n)
f1 = ti.field(ti.f32, n)
f2 = ti.field(ti.f32, n)
temp_add = ti.field(ti.f32, ())
temp_max = ti.field(ti.f32, ())
@ti.kernel
def atomicadd_field():
for P in range(n):
ti.atomic_add(temp_add[None], f1[P])
@ti.kernel
def atomicadd_array(field_in: ti.any_arr()):
for P in range(n):
ti.atomic_add(temp_add[None], field_in[P])
@ti.kernel
def atomicmax_field():
for P in range(n):
ti.atomic_max(temp_max[None], f2[P])
@ti.kernel
def …
```
> [opt] Support atomic min/max in warp reduction optimization

- docs/lang/articles/contribution/doc_writing.md
- docs/lang/articles/get-started.md
- examples/simulation/fractal.py
> [misc] Fix typo in examples/simulation/fractal.py

- python/taichi/lang/ndarray.py
For now (prototyping stage) we are using `torch.Tensor` as storage for Taichi ndarrays. When constructing ndarrays, we will pass device strings `cpu` or `cuda:0` into `torch.zeros`. However, there are some known issues like https://github.com/pytorch/pytorch/issues/50779, https://discuss.pytorch.org/t/std-regex-replace-not-work-with-libtorch-1-7-0/102253, which may prevent users from using Taichi as a part of their software. Therefore I'm getting rid of these device strings in this PR.
> [refactor] Avoid passing device strings into torch

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/codegen_opengl.h
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/opengl_program.cpp
- taichi/backends/opengl/opengl_program.h
- taichi/backends/opengl/shaders/runtime.h
First step of cleaning up GL runtime:
1. Rename GLSLLauncher to OpenGLRuntime, so that it's inline with the other backends' naming
2. Separate materialize runtime & materialize SNode tree in ProgramImpl
> [opengl] Runtime refactor 1/n

- setup.py
Previously in Taichi, all non-power-of-two dimensions of a field were automatically padded to a power of two. For instance, a field of shape `(18, 65)` would have internal shape `(32, 128)`. Although the padding had many benefits such as allowing fast and convenient bitwise operations for coordinate handling, it would consume potentially much more memory than people thought.
For people indeed want smaller memory usage, we now introduce an optional packed mode. In packed mode, no more padding will be applied so a field will not have a larger internal shape when some of its dimensions are not power-of-two. The downside is that the runtime performance will regress slightly.
A switch named `packed` for `ti.init()` decides whether to use packed mode:
```python
ti.init()  # default: …
```
> [release] v0.8.0

- docs/lang/articles/misc/install.md
> [Doc] Installation with mirror source

- python/taichi/lang/kernel_impl.py
- python/taichi/lang/stmt_builder.py
Related issue = #282
The Taichi compiler first translates the AST of a kernel/function into another Python function, and runs that function to generate C++ AST. In order to run that function, the Python context (global vars and non-local vars) needs to be passed in.
Previous way is to use `func.__globals__` for all global vars (not limited to what are used in that `func`) and ad-hoc manipulation for non-local vars. The former may make the Python context too large and the latter might be error-prone.
Use `inspect.getclosurevars(func)` instead. This provides a minimum Python context, which only captures actually used global/non-local variables. This may also serve as a first step towards cleaning up the compilation process.
After AST translation of force-inlined functions, the annotations …
> [refactor] Minimize Python context

- python/taichi/lang/field.py
Related issue = close #2973 
@strongoier fix by simple change.
> [Lang] Add error message for printing an incomplelely-defined field

- .github/workflows/release.yml
fixes #2955
Nightly release have been failing for a few days due to OOM. This is caused by ndarray tests using up all memory when running with -t2. 
Lesson learned: we should really unify release.yml and presubmit.yml to make sure they are aligned, in this example we had ndarray tests running with -t1 in presubmit but -t2 in release.
> [ci] Fix OOM on nightly release.

- python/taichi/core/util.py
When I debugged the nightly release failure I realized that `pip uninstall taichi -y` won't fully delete the `taichi` folder in the python `site-packages`. This happens since we generates a symlinked
`libtaichi_core.so` at runtime that `pip` isn't aware of. So `pip`
leaves it in `site-packages/taichi/lib` during uninstall. This is **BAD** since it means even after
you uninstall taichi, you'll still be able to `import taichi`(altho empty!) due to the
`site-packages/taichi` folder.
Note this only happens when you install taichi from a wheel, `python
setup.py install/develop` works fine.
> [misc] Remove unnecessary symlink step.

- taichi/backends/cuda/cuda_device.cpp
- taichi/backends/cuda/cuda_device.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/system/memory_pool.cpp
- taichi/system/memory_pool.h
- taichi/system/unified_allocator.cpp
- taichi/system/unified_allocator.h
This PR begins the work on CUDA deivce API.
The PR only implements memory allocation and deallocation, and makes use of those methods in LlvmProgram and MemoryPool.
This would be very useful for unifying the memcpy logic used in GGUI, which would facilitate implementing GGUI on other backends.
> [cuda] Cuda Device API 1/n: memory allocation

- .github/workflows/release.yml
This fits release jobs better than presubmit jobs. (in the sense that we
want release builds to finish as many as possible but in presubmit jobs
we want to save minutes.
> [ci] Disable fail-fast matrix on release jobs.

- taichi/backends/cpu/cpu_device.cpp
- taichi/backends/cpu/cpu_device.h
- taichi/llvm/llvm_program.cpp
- taichi/system/unified_allocator.cpp
- taichi/system/unified_allocator.h
related issue = #2736 
This PR starts the work on `CpuDevice`. 
`allocate_memory` and `dealloc_memory` are implemented, and these are used in unified allocator.
The next PR will start moving the memory pool inside `CudeDevice` and `CpuDevice` ([discussion](https://github.com/taichi-dev/taichi/pull/2963#discussion_r713908020))
> [cpu] Cpu device 1/n: memory allocation

- misc/make_changelog.py
Previously, `make_changelog.py` identifies the last commit with `[release]` message as the last version. After this PR, `make_changelog.py` identifies the last commit with a tag as the last version. This allows a more flexible releasing process.
> [misc] Get changelogs via tags instead of commit messages

- taichi/backends/vulkan/embedded_device.cpp
Related issue = #3023
Hey, who doesn't like a +4/-0 PR
As for NDEBUG, ref: https://stackoverflow.com/questions/34302265/does-cmake-build-type-release-imply-dndebug
Unless we have our own flags
> [vulkan] Disable validation layer with release builds

- docs/lang/articles/advanced/differentiable_programming.md
- examples/simulation/ad_gravity.py
This PR mainly improves differentiable programming doc by clarifying global
data access rules and kernel simplicity rule by examples.
There're a few followups wip, e.g. renaming and adding docs for
`complex_kernel`, better error reporting when violating the autodiff
rules etc.
> [Doc] Update differentiable programming doc.

- taichi/runtime/llvm/runtime.cpp
- taichi/system/snode_tree_buffer_manager.cpp
Give the runtime memory allocation function a more generic name.
> [LLVM] Rename runtime memory allocation function

- taichi/backends/vulkan/embedded_device.cpp
- taichi/common/core.h
Related issue = #3028, #3031
Tested on Ubuntu 20.04:
* Removed `vulkan-sdk`, the vulkan backend still worked
* This line is **no longer** printed: `[W 09/29/21 19:18:13.253 54839] [embedded_device.cpp:vk_debug_callback@54] validation layer: loader_icd_scan: Can not find 'ICD' object in ICD JSON file /usr/share/vulkan/icd.d/nvidia_layers.json.  Skipping ICD JSON`
> [vulkan] Disable Vulkan validation layer

- python/taichi/lang/transformer.py
Test case:
```python
ti.init(print_ir=True,print_preprocessed=True)
@ti.kernel
def func():
(a, b) = (1, 2)
print(a, b)
```
There are formatting inconsistencies between `print_ir` and `print_preprocess`. The output before the PR looks like:
```
[Taichi] version 0.8.1, llvm 10.0.0, commit cc2dd342, osx, python 3.7.9
[Taichi] Starting on arch=x64
Initial AST:
def func():
...
Preprocessed:
def func():
...
[I 09/30/21 16:42:14.133 16716489] [compile_to_offloads.cpp:operator()@22] [func_c4_0] Initial IR:
kernel {
...
[I 09/30/21 16:42:14.134 16716489] [compile_to_offloads.cpp:operator()@22] [func_c4_0] Lowered:
...
```
This PR is to make it consistent (with) logic here https://github.com/taichi-dev/taichi/blob/master/taichi/transforms/compile_to_offloads.cpp#L17:
```
[Taichi] version 0.8.1, …
```
> [Lang] Fix python AST print format issues in python/taichi/lang/transformer.py

- python/taichi/lang/__init__.py
- python/taichi/testing.py
- tests/python/test_customized_grad.py
Issue: when running `ti test -vr2 -t4 -a cpu` two tests (asserting
must_throw) failed. But if I ran with `ti test -vr2 -t4` everything
passed.
It turned out that our `ti test -a` doesn't accept `cpu/cuda` as
arguments thus it ran on an empty arch list. When we assert must_throw
tests failed.
This PR fixes two things:
1. Add support for `cpu/cuda` and simplify `supported_arch`.
2. When there's no valid archs, explicitly print out a message and
return instead of running "empty" tests and reporting success.
```
λ ~/github/taichi fix_test_arch ti test test_customized_grad -vr2 -t4 -a metal -s
[Taichi] version 0.8.1, llvm 10.0.0, commit 502d12b3, linux, python 3.8.11
*******************************************
**      Taichi Programming Language      ** …
```
> [Test] Allow ti test to work with specified cpu/gpu arch.

- taichi/analysis/gather_statements.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/cuda_profiler.cpp
- taichi/backends/cuda/cupti_toolkit.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_device.h
- taichi/backends/vulkan/runtime.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/program/program.cpp
- taichi/transforms/bit_loop_vectorize.cpp
Related issue = #3287
Fix some of the compiler warnings in the C++ codebase.
- Explicitly override
- Explicitly hide methods from the base class
- Use virtual destructors for base classes
- Remove unused variables, functions and lambda captures
- Avoid conversion from string literals to char*
- Avoid reordering constructions of class members
- All code paths return a value in non-void functions
> [Refactor] Fix compiler warnings

- taichi/backends/vulkan/embedded_device.cpp
- taichi/ui/backends/vulkan/app_context.cpp
- taichi/ui/backends/vulkan/app_context.h
- taichi/ui/backends/vulkan/renderable.cpp
- taichi/ui/backends/vulkan/renderables/set_image.cpp
fixes #3327 
GGUI started crashing since #3253, but that PR wasn't the issue. The real problem is that the `vk_has_external_memory` flag wasn't set properly.
> [vulkan] Fix GGUI

- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/codegen_opengl.h
- taichi/backends/opengl/opengl_program.cpp
Related issue = #3298
RIght now the users still don't have a way to disable the usage of extensions during JIT. After https://github.com/taichi-dev/taichi/pull/3329, hopefully we only need to disable this in the AOT module.
> [opengl] Provide an option to disable NV extensions during codegen

- taichi/backends/device.h
- taichi/backends/vulkan/embedded_device.cpp
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/python/export_ggui.cpp
- taichi/ui/backends/vulkan/swap_chain.cpp
- taichi/ui/backends/vulkan/swap_chain.h
- taichi/ui/backends/vulkan/window.cpp
- taichi/ui/backends/vulkan/window.h
- taichi/ui/common/window_base.h
This PR adds image IO for GGUI. The implementation is somewhat based on [this](https://github.com/SaschaWillems/Vulkan/blob/master/examples/screenshot/screenshot.cpp).
Notice that this PR alone doesn't enable headlessly running GGUI: it only allows you to dump an image file while the window is also running.
In the next PR, I'll add in headless support. And then we can start adding tests for GGUI.
Not working on MoltenVK on macOS... will try to fix.
And finally, this PR should be merged after #3330, otherwise GGUI won't work at all.
> [gui] GGUI Image IO  (well, it's actually just O...)

- python/taichi/lang/matrix.py
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/expression.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/test_gc.py
- tests/python/test_matrix.py
- tests/python/test_random.py
- tests/python/test_ssa.py
Related issue = #3301
This PR serves as the kickoff of #3301. Type inference for `ConstExpression`, `ArgLoadExpression`, `RandExpression`, `IdExpression`, `BinaryOpExpression` are supported. Furthermore, when `dynamic_index=True`, the `dt` argument is no longer needed in local  `ti.Vector` definition with initial values of these supported expressions.
Note that `PrimitiveType::unknown` is used for now to represent failing or unimplemented type inference. After type inference for all expressions are supported, this will be replaced by detailed error messages.
> [IR] Support frontend type inference in simple cases

- .github/workflows/postsubmit.yml
This matches the number we have in presubmit. We'll probably use a template for presubmit/postsubmit to avoid divergence in the future.
> [ci] Update windows postsubmit job timeout to 90mins.

- python/taichi/aot/module.py
thanks to @squarefk for reporting the issue!
> [opengl] Only run preprocess_kernels when glslc is available.

- taichi/backends/interop/vulkan_cuda_interop.cpp
- taichi/backends/vulkan/vulkan_device.h
GGUI used to have an 128 MB limit on VBO/IBO. This was removed a while ago, but I forgot to update the `vulkan_cuda_interop` procedure to accommodate this.
> [gui] Fix bug where VBO/IBO cannot exceed 128 MB

- taichi/ir/type.h
> [ir] Add missing constructors for TypedConstant

- python/taichi/lang/matrix.py
- taichi/ir/expr.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/test_custom_float.py
- tests/python/test_ssa.py
- tests/python/test_type_check.py
Related issue = #3301
Now for
```python
ti.init()
@ti.kernel
def func():
a = 1
b = ti.ceil(a)
func()
```
The error message is:
```
[Taichi] version 0.8.4, llvm 10.0.0, commit d577b876, linux, python 3.8.10
[Taichi] Starting on arch=x64
[Taichi] Compilation failed
File "type_test.py", line 8, in func
b = ti.ceil(a)
TaichiTypeError: 'ceil' takes real inputs only, however 'i32' is provided
```
> [IR] Add type_check for UnaryOpExpression

- cmake/TaichiCore.cmake
- cmake/external/SPIRV-Cross/gitversion.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_device.cpp
- taichi/backends/opengl/opengl_device.h
Related issue = https://github.com/taichi-dev/taichi/issues/3364
GLES can be enabled by changing the flag in the `opengl_api.cpp`, and due to the need of GLSL preprocessing, it's only available on linux / BSD. (well other platforms don't really support GLES 3.1 anyways)
GLAD2 is introduced so that we can use its EGL loader to create our off-screen context. GLFW will be attempted first, if GLFW can not initialize a window, the code will try EGL. Therefore this does not introduce extra dependencies.
> [opengl] Off-screen context using EGL & Support GLES

- taichi/python/export_lang.cpp
- tests/python/test_basics.py
Signed-off-by: knight42 <anonymousknight96@gmail.com>
fixes #3367
> [Lang] Define __str__ method for DataType

- tests/python/test_ndarray.py
Did not fail before because Torch memory is initialized to zero.
> [Test] Fix uninitialized tests for ndarray

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/test_type_check.py
> [IR] Add type_check for TernaryOpExpression

- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/util.py
- python/taichi/type/primitive_types.py
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/type_utils.cpp
- taichi/llvm/llvm_context.cpp
- taichi/program/kernel.cpp
- tests/cpp/ir/type_test.cpp
- tests/python/test_f16.py
* #3384
* #3374
* __->__ #3373
This PR supports f16 on unary & binary ops, RandStmt and PrintStmt on
CPU & CUDA.
Milestone here is we now support running fractal simulation on f16.
I'll write some documentation for fp16 support in a bit.
Related issue = https://github.com/taichi-dev/taichi/issues/2992
> [llvm] Basic f16 support

- taichi/backends/interop/vulkan_cuda_interop.cpp
- taichi/python/export_ggui.cpp
I have been trying to write tests for GGUI, and one problem I encountered was that I couldn't run GGUI multiple times separated by ti.reset() calls. There were two reasons for this:
1. ti.reset() doesn't release the resources for the GGUI window. This PR adds an explicit destory() method that works around this. (i.e. after each test, I will call destroy() manually)
2. The vulkan_cuda interop function did not consider the fact that the VulkanDevice and CudaDevice could change. This is fixed in this PR.
> [gui] Allowing recreating GGUI windows after ti.reset().

- docs/lang/articles/basic/type.md
Related issue = #3318
This PR puts back content from old `docs/lang/api/arithmetics.md` into our current type system section. The organization structure of the type system section is also refined.
> [Doc] Put back content from old docs/lang/api/arithmetics.md

- taichi/transforms/type_check.cpp
1. Avoid splitting one log into two lines.
2. Use correct atomic operation names in logs.
> [LLVM] Fix logging formats

- .github/workflows/presubmit.yml
> [ci] Skip the full test when the PR just get Docs change

- python/taichi/lang/matrix.py
`Matrix.new` is an internal API which is used only once. This adds unnecessary complexity to the `Matrix` class.
> [refactor] Remove Matrix.new

- taichi/math/scalar.h
Find the largest potence faster.
> [misc] Update "get_largest_pot" in scalar.h + Bug Fix

- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/common/serialization.h
- tests/python/test_aot.py
This PR does two things:
1. It converts `TextSerializer` to output json format instead of a customized format. I tried to not introduce any extra dependency like jsoncpp but just make our output json compliant. (two regex tricks are used :P) 
2. Since Json doesn't support multiple line string, it saves each glsl kernel source code in a `.glsl` file and only saves the filename in json. 
Example generated aot json file: https://gist.github.com/ailzhang/48b6126cabae2e9f2d35da02b210a719 
Currently I only changed opengl backend to json, will change metal later together with enabling its tests.
> [opengl] Save opengl aot data in json format.

- python/taichi/lang/ast_builder_utils.py
- python/taichi/lang/ir_builder.py
- tests/python/test_ast_refactor.py
> [refactor] Add for and while to the new frontend AST builder

- taichi/backends/opengl/aot_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/struct_opengl.cpp
- taichi/program/aot_module_builder.cpp
- taichi/program/aot_module_builder.h
- tests/python/test_aot.py
> [OpenGL] Add mem_offset_in_parent to serialized file in AOT.

- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- .github/workflows/scripts/win_build.ps1
- cmake/PythonNumpyPybind11.cmake
Related issue = #3391 #2715 
1. Fix the cmake file to support in-venv build
2. Add a build script for windows as requested in #3391 that:
a. Usage: `win_build.ps1 [[-libdir] <string>] [-clone] [-installVulkan] [-develop] [-install]`
b. Support rerun, won't download again if already exists
c. build and install python library in a virtual environment to avoid contaminating the system site-packages
d. support install in develop mode(with `-develop` flag), like `python setup.py develop`
e. CMake args and environments are populated automatically, users don't bother to set them.
3. Replace the building steps in postsubmit and presubmit CI jobs with the script.
I've tested on Windows 10, CPU build, both build and install are successful. If you have a Windows PC, please help to test the script. …
> [ci] Add build script for win

- taichi/backends/cpu/cpu_device.cpp
- taichi/backends/cpu/cpu_device.h
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/cuda_device.cpp
- taichi/backends/cuda/cuda_device.h
- taichi/backends/device.cpp
- taichi/backends/device.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/ndarray.cpp
Use the preallocated memory for Ndarray (CPU+CUDA)
> [lang] [refactor] Use preallocated memory via device allocation for Ndarray

- taichi/backends/device.cpp
- taichi/backends/device.h
- taichi/backends/vulkan/embedded_device.cpp
- taichi/backends/vulkan/vulkan_device.cpp
Related issue = #3416 
This is a temporary work around. The right thing to do would be to generate triangles that simulate lines. This is tracked by issue #3431.
> [gui] Fix canvas.lines on macOS

- docs/lang/articles/basic/type.md
Related issue = #3318
This PR puts back content from old `docs/lang/api/atomic.md` into our current type system section. The format and content organization are refined to fit current doc better. `ti.atomic_max/min` is also added into the doc.
> [Doc] Put back content from old docs/lang/api/atomic.md

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- tests/python/test_f16.py
Support atomic add/max/min of `f16` by CAS (`CreateAtomicCmpXchg`) on CPU and CUDA backends. 
CPU: Cast to `i16` pointer.
CUDA: Extend to `i32` pointer in a hacky way because CAS for 16-bit values is not supported. The correctness depends on the memory arrangement.
> [llvm] Support atomic operations of f16

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/bls_test_template.py
- tests/python/test_custom_float_time_integration.py
> [IR] Add type_check for RangeAssumption/LoopUnique/ExternalTensorShapeAlongAxisExpression

- taichi/ir/expr.cpp
- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/ir/frontend_ir.h
- taichi/transforms/lower_ast.cpp
Related issue = #3301 
`EvalExpression` and related functions look like legacy code and have no usage today. This PR aims at cleaning them up.
> [IR] Remove EvalExpression

- taichi/backends/opengl/aot_module_builder_impl.cpp
- tests/python/test_aot.py
> [opengl] Make windows path in saved aot json human readable.

- cmake/TaichiCore.cmake
- examples/rendering/cornell_box.py
- taichi/backends/vulkan/embedded_device.cpp
- taichi/backends/vulkan/embedded_device.h
- taichi/backends/vulkan/loader.cpp
- taichi/backends/vulkan/loader.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_common.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_utils.h
- taichi/ui/utils/utils.h
Related issue = #3416 #2736
On macOS, volk is disabled and direct linking to MoltenVK is used instead so that we can ship Vulkan by default to users without having users to install the Vulkan SDK.
Also changed the cornell_box example to not use atomic reduction. A atomic reduction on a buffer with that size is just asking for trouble with devices that do not support FP atomics.
> [vulkan] Link to MoltenVK on macOS

- taichi/transforms/offload.cpp
- tests/python/test_offload_cross.py
Related issue = fixes #3463
See #3467 for more details.
> [Bug] [ir] Visit RangeForStmt in IdentifyValuesUsedInOtherOffloads

- python/taichi/aot/module.py
- taichi/backends/opengl/aot_module_builder_impl.cpp
- tests/python/test_aot.py
Tested on the windows opengl backend manually.
> [opengl] Unify windows path to posix format in python.

- .github/workflows/release.yml
- python/build.py
Related issue = Close #3451 
Sorry this issue is caused by the change #3410 
I simply checked the status of the command, the situation will improve after the build.py is removed
> [ci] Report error if upload fails

- python/taichi/lang/matrix.py
- taichi/ir/frontend_ir.h
Related issue = #2590, #2880, #2637
This PR rewrites arithmetic operations of matrices so as to simplify the implementation as well as to enable local tensors as arithmetic operation results (`empty_copy()` in the old implementation has `disable_local_tensor=True`).
> [Lang] Enable local tensors as arithmetic operation results

- .github/workflows/presubmit.yml
- .github/workflows/scripts/check_clang_tidy.sh
- scripts/run_clang_tidy.py
> [misc] Enable clang-tidy check in CI

- .github/workflows/presubmit.yml
- python/taichi/aot/module.py
- python/taichi/lang/__init__.py
- python/taichi/lang/expr_builder.py
- python/taichi/lang/impl.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ndrange.py
- python/taichi/lang/stmt_builder.py
- python/taichi/tools/np2ply.py
> [Lang] Fix pylint rule C0200

- .github/workflows/presubmit.yml
- python/taichi/lang/__init__.py
- python/taichi/lang/ir_builder.py
> [Lang] Fix pylint rule W0108

- taichi/ir/expr.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/cpp/ir/frontend_type_inference_test.cpp
Related issue = #3301
This PR adds `type_check` for remaining expressions and removes all `TODO: assert no unknowns after type_check for all expressions are implemented`.
> [IR] Enforce type check for all expressions

- .github/workflows/presubmit.yml
- python/taichi/lang/_ndarray.py
- python/taichi/lang/exception.py
- python/taichi/lang/kernel_impl.py
- python/taichi/ui/scene.py
> [Lang] Fix pylint rule W0235

- .github/workflows/presubmit.yml
- scripts/generate_pylint_tags.py
> [ci] Fix pylint conflicts

- python/taichi/cc_compose.py
- python/taichi/lang/__init__.py
- python/taichi/lang/ast_builder_utils.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_impl.py
- python/taichi/main.py
- scripts/generate_pylint_tags.py
> [Lang] Fix pylint rule W0612 (#3151)

- taichi/backends/cuda/cuda_context.h
- taichi/backends/cuda/jit_cuda.cpp
In the original code, the returned rvalue reference is obviously a dangling reference, and the scoped mutex has no effect (destructed immediately after construction).
> [CUDA] Fix a misuse of std::move: address of stack memory associated with temporary object of type std::lock_guard<std::mutex> returned to caller

- cmake/TaichiCore.cmake
- taichi/backends/interop/vulkan_cpu_interop.cpp
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/jit/jit_session.cpp
- taichi/program/kernel.cpp
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- taichi/struct/struct_llvm.h
- taichi/system/snode_tree_buffer_manager.cpp
- taichi/system/snode_tree_buffer_manager.h
- taichi/system/unified_allocator.cpp
This PR adds a TI_WITH_LLVM option, so that one can optionally disable compiling with LLVM. (For example, I'm trying to emscripten the entire taichi project, and LLVM doesn't like that).
TI_WITH_LLVM is defaulted to ON, so this PR won't affect any of our existing CI/CD/build tools.
> [llvm] Add a TI_WITH_LLVM option

- python/taichi/lang/__init__.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/linalg_impl.py
- tests/python/test_ast_refactor.py
issue = #3038
When fixing pylint R1705 no-else-return, some of the raise statements are moved outside the `else` scope of the static-if, resulting raising errors when traversing to the Raise node. For example:
```python
if ti.static(A.n == 2): 
ret = svd2d(A, dt)
return ret
elif ti.static(A.n == 3):
return svd3d(A, dt)
else:
raise Exception("SVD only supports 2D and 3D matrices.")
```
was changed to 
```python
if ti.static(A.n == 2):
ret = svd2d(A, dt)
return ret
if ti.static(A.n == 3):
return svd3d(A, dt)
raise Exception("SVD only supports 2D and 3D matrices.")
```
and the AST builder will continue to visit the Raise node because it is not in the else branch of static-if.
Immediate termination of traversing when meeting return statement can be supported in the future.
> [refactor] Enable the new ast builder by default

- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
Lessons learned:
* Always prefer `VK_NULL_HANDLE` to `nullptr`
* Always prefer `VkDeviceSize` to `size_t`
> [vulkan] Fix a few errors encountered when building for x86

- python/taichi/lang/matrix.py
Related issue = #2590, #2880, #2637
This PR rewrites `element_wise_writeback_binary` to enable local tensor results. To make it work, `Matrix.__init__` is refactored a little bit to clean the logic and cover missing cases.
> [Lang] Enable local tensors as writeback binary operation results

- python/taichi/lang/matrix.py
Related issue = #2590, #2880, #2637
After this PR, `disable_local_tensor` only appears in `ti.Matrix.empty`. Removing that requires significant refactoring, which will be done in a future PR.
> [Lang] Remove disable_local_tensor in most cases

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- python/taichi/lang/types.py
- taichi/ir/type_utils.h
- taichi/python/export_lang.cpp
There are lots of dependencies of the `ti.Matrix.empty` internal method (#3524). This PR serves as the first step towards cleaning them up.
> [refactor] Remove variable() of Matrix/Struct and empty() of Matrix/StructType

- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/lang/struct.py
- taichi/ir/frontend_ir.h
This is a follow-up PR of #3531.
> [refactor] Remove empty_copy() and copy() from Matrix/Struct

- python/taichi/main.py
- requirements_test.txt
Initial version of checking version for users when using Taichi. The method of getting users' platforms might looks hacky. Welcome any suggestions on how to map users' platform.
> [Lang] Add check version function to taichi main

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ndrange.py
- python/taichi/lang/struct.py
This is a follow-up PR of #3536. Meanwhile, it fixes #2718 by the way.
> [refactor] Remove with_entries() and keep_raw from Matrix

- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_ast_refactor.py
Related issue = #2590, #2880, #2637
After this PR, dynamic index of local tensors are completely supported with `dynamic_index=True`.
> [Lang] Remove disable_local_tensor and empty() from Matrix

- docs/lang/articles/contribution/dev_install.md
fixes #3550.
Currently, this entry point contributors look for is like part of "Installing dependencies". But it's actually building Taichi itself.
> [Doc] Move build Taichi from source one level up

- taichi/backends/metal/kernel_utils.cpp
- tests/python/test_arg_alignment.py
> [Bug] [metal] Fix data type alignment for arguments and return values

- .github/workflows/presubmit.yml
Related issue = #3568
Fix and simplify the logic for skipping CI when there are no non-doc modifications.
> [ci] Fix skipping presubmit checks

- taichi/backends/vulkan/kernel_utils.cpp
- tests/python/test_arg_alignment.py
This is a fix similar to #3564, but for our Vulkan backend.
> [Bug] [vulkan] Fix data type alignment for arguments and return values

- python/taichi/lang/_ndarray.py
- tests/python/test_ndarray.py
Add `get_element_size()` and `get_nelement()` for more convenient access of size in bytes.
> [Lang] Add get_element_size for ndarray

- .github/workflows/release.yml
- misc/upload_release.py
> [ci] Fix release bug

- python/taichi/core/util.py
- python/taichi/main.py
> [Lang] Add time check before performing version check

- taichi/transforms/offload.cpp
- tests/python/test_offload_cross.py
Related issue = #3463, #3467
#3467 didn't point out the accurate root cause of #3463. `RangeForStmt` was indeed visited with https://github.com/taichi-dev/taichi/blob/1ca4c408a69ba7475fd792aadd2e45cebf218615/taichi/ir/basic_stmt_visitor.cpp#L33-L36 instead of https://github.com/taichi-dev/taichi/blob/1ca4c408a69ba7475fd792aadd2e45cebf218615/taichi/transforms/offload.cpp#L374-L380
Having this, the most effective way to fix #3467 is to fill in the `preprocess_container_stmt()` member function common to all container statements, which is done in this PR.
> [Bug] [ir] Fix the IdentifyValuesUsedInOtherOffloads pass

- python/taichi/lang/__init__.py
- taichi/ir/frontend_ir.h
- tests/python/test_mesh.py
Related issue = #3567
Just remember to use `load_if_ptr` for any `Expr` when constructing Taichi frontend IR.
> [mesh] Make ti.Mesh compatible with dynamic index

- python/taichi/aot/module.py
* #3623
* #3622
* __->__ #3621
Using absolute path confuses users so let's get rid of it.
> [refactor] Do not expand to absolute path for saved shaders.

- python/taichi/aot/module.py
- taichi/common/serialization.h
* __->__ #3623
* #3622
* #3621
For vectors, this PR serializes them to json arrays instead of
(key,value) pairs.
For maps, this PR fixes a bug.
Before:
```
{
"key": my_key1,
"value": my_value1,
"key": my_key2,
"value": my_value2
}
```
After:
```
{
"my_key1": my_value1,
"my_key2": my_value2
}
```
Followup: add some unit tests for TextSerializer class.
> [bug] Correctly support serializing maps & vectors to json.

- python/taichi/lang/__init__.py
- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_short_circuit.py
Related issue = Fixes #3572
cc @strongoier 
```python
ti.init(short_circuit_operators=True)
```
> [Lang] Add option short_circuit_operators for short-circuiting boolean ops

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_custom_struct.py
- tests/python/test_matrix.py
Related issue = #3625
A `Matrix/Struct` defined in Python scope is read-only in Taichi scope. To assign it to a local variable in Taichi scope, we have to do explicit copy. After this PR, https://github.com/taichiCourse01/taichi_ray_tracing/blob/master/3_2_whitted_style_ray_tracing.py should work fine.
> [Bug] [lang] Fix copying a Matrix/Struct from Python scope to Taichi scope

- python/taichi/__init__.py
* #3641
* #3640
* __->__ #3639
We only need provide shortcuts to types `u8, f32` etc but not the
`primitive_types` module.
> [refactor] Remove primitive_types module in top level package.

- taichi/backends/opengl/aot_module_builder_impl.cpp
- tests/python/test_aot.py
It seems good enough to use folders here so let's keep the filenames
simple and match kernel names.
> [refactor] Ignore filename prefix in opengl aot files.

- python/taichi/lang/impl.py
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/python/test_custom_struct.py
- tests/python/test_matrix.py
Related issue = #3625
Accidentally, assignments from Matrix/StructField elements to local variables are by reference:
```python
ti.init(debug=True)
a = ti.Vector.field(3, ti.i32, shape=())
a[None] = ti.Vector([1, 2, 3])
@ti.kernel
def test():
b = a[None]
b[0] = 5
b[1] = 9
b[2] = 7
print(a[None][0])  # 5
print(a[None][1])  # 9
print(a[None][2])  # 7
test()
```
However, they are indented to be by value. The PR aims at fixing it. After this PR, https://github.com/taichiCourse01/taichi_ray_tracing/blob/master/4_0_path_tracing.py should work fine.
> [Bug] [lang] Fix copying Matrix/StructField elements in Taichi scope

- python/taichi/lang/kernel_impl.py
When profiling my own application, I found that the `_inside_class()` function of taichi was the bottleneck: https://github.com/taichi-dev/taichi/blob/2166c8fe14e5444dc237d8b343a378a317962877/python/taichi/lang/kernel_impl.py#L649-L660
As we only needed the frame at `level_of_class_stackframe`, getting the whole stack was a waste of time. I accelerated this function by mimicking the implementation of `inspect.stack()`, but only fetching the target frame out.
This PR decreases the running time of my own application from 22.2s to 0.8s. It also decreases the running time of `import taichi as ti` from 1.7s to 0.5s on my machine.
References:
https://github.com/python/cpython/blob/9a5dec4e978f68ab956e979858ce3aa178436fa4/Lib/inspect.py#L1559-L1569 …
> [perf] Accelerate _inside_class()

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
Before the change, any `Ndarray` obj will have an extra ref count due to the introduced `obj.__closure___`. This can be checked by `import gc 
gc.get_referrers`. The problem is that the destructor will not be called until the program finish, due to this extra count. This prevents optimizations such as memory recycling.
After the change, the extra ref count is eliminated and object can be properly recycled when out of scope.
> [Refactor] Reduce reference count introduced by object closure

- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/expression.h
- taichi/program/program.cpp
Signed-off-by: Jun <jun@junz.org>
Related issue = #2684
> [Refactor] Deprecate Expr::operator=

- .github/workflows/cancel.yml
`gh run` needs to checkout the repo code. This part is lacking testing, so sorry for the many fixes.
> [ci] Checkout the repo for cancel

- python/taichi/lang/__init__.py
- python/taichi/testing.py
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- taichi/python/export_misc.cpp
This PR converts use_gles from a constexpr to a static variable set in
`initialize_opengl` so that users can optionally turn it on/off using
`ti.init(use_gles=True)`.
> [opengl] [refactor] Expose use_gles in CompileConfig.

- python/taichi/snode/fields_builder.py
This is a duplicate of #3674.
Now that we support ndarrays for AOT, it's possible/valid to have all
ndarray inputs and no field input as shown in test_mpm88_ndarray. So
let's turn off the warning here to avoid confusion.
> [refactor] Turn off empty root buffer warning for finalize_for_aot.

- python/taichi/aot/module.py
* #3692
* #3691
* #3690
* #3689
* __->__ #3688
* #3687
Now that users have options to either specify `element_shapes &
field_dim` in the kernel argument annotation, or provided a dict of
example any_arr.
> [Lang] Make example_any_arrays optional.

- taichi/backends/opengl/opengl_api.h
* #3692
* #3691
* #3690
* __->__ #3689
* #3688
* #3687
> [refactor] [opengl] Remove dtype & total_size_hint in serialized aot file.

- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
* #3692
* #3691
* __->__ #3690
* #3689
* #3688
* #3687
`CompiledKernel` isn't an accurate name and it conflicts with what we
understand as "taichi kernel". A better name for it is indeed
`CompiledOffloadedTask`.
> [refactor] [opengl] Use CompiledOffloadedTask instead of CompiledKernel.

- taichi/backends/opengl/aot_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
* #3692
* __->__ #3691
* #3690
* #3689
* #3688
* #3687
Nested data structures are confusing... Let's just use an unordered_map with taichi kernel_name as
keys.
> [refactor] [opengl] For each taichi kernel, save a {kernel_name, CompiledProgram} pair instead of a vector.

- cmake/TaichiCore.cmake
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/device.cpp
- taichi/backends/wasm/codegen_wasm.h
- taichi/jit/jit_session.cpp
- taichi/program/program.cpp
- taichi/program/state_flow_graph.h
- taichi/util/file_sequence_writer.cpp
- taichi/util/file_sequence_writer.h
Some components were still referencing LLVM with TI_WITH_LLVM set to
false triggering a build failure.
Related issue = #3679
> [LLVM] Add missing pre-processor macro when LLVM is disabled

- cpp_examples/main.cpp
This PR adds an example of using the C++ API to AOT compile a kernel to SPIRV.
> [example] SPIR-V AOT example in C++

- CMakeLists.txt
- setup.py
This PR makes it more automatic using ccache + ninja. 
Ninja is very fast (i.e., instant) for incremental builds so it fits development need where we need to rebuild for small changes. Here we use it only when it's available to avoid breaking people's workflow.
> [misc] Use ccache & prefer Ninja over Make as cmake generator.

- python/taichi/lang/kernel_impl.py
- tests/python/test_ast_refactor.py
Injecting template arguments into globals is only necessary in kernels, and it should not happen on functions.
> [bug] Fix template arguments of ti.func with default values

- misc/code_format.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_exception.py
Related issue = close #3666
I have to disable code format check on test_exception.py, otherwise it will always turn the tabs to spaces and I cannot disable it even if I disabled yapf.
> [error] Fix tab and long line in error messages

- cpp_examples/main.cpp
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/program/aot_module_builder.h
fixes #3708 
Previously, the SPIRV codegen requires an instance of `VkRuntime`. The runtime is in fact only used to provide a `Device*` and the compiled SNode structs. Moreover, the `Device*` is only used to query device capabilities.
This PR removes the `VkRuntime*` from the codegen. When there isn't a runtime, the `VulkanProgram` will own the compiled structs, and feed them to the codegen. The PR also adds a `AotTargetDevice`, which is used to report device capabilities to the codegen.
The result of this PR is that #3708 is fixed. In other words, we can run Vulkan AOT to generate SPIRV without ever creating a `VulkanDevice` or a `VkRuntime`.
> [vulkan] Further decouple SPIRV codegen from Vulkan runtime

- cmake/TaichiCXXFlags.cmake
> [build] Add /bigobj flag to allow Debug builds on windows

- misc/demo_warning.py
- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
- python/taichi/tools/util.py
- python/taichi/ui/gui.py
- tests/python/bls_test_template.py
- tests/python/test_mpm88.py
- tests/python/test_mpm_particle_list.py
This PR tries to remove all these deprecated Python APIs and it solves #3590. 
Before merging, we need to make sure all these APIs...
- `@deprecated('kernel_profiler_print()', 'print_kernel_profile_info()')`
- `@deprecated('kernel_profiler_clear()', 'clear_kernel_profile_info()')`
- `@deprecated('memory_profiler_print()', 'print_memory_profile_info()')`
- `@deprecated('ti.cache_shared', 'ti.block_local')`
- `@deprecated('ti.var', 'ti.field')`
- `@deprecated("ti.indices", "ti.axes")`
- `@deprecated('ti.Matrix.transposed(a)', 'a.transpose()')`
- `@deprecated('a.T()', 'a.transpose()')`
- `@deprecated('ti.Matrix.var', 'ti.Matrix.field')`
- `@deprecated('ti.Vector.var', 'ti.Vector.field')`
- `@deprecated('x(i, j)', 'x.get_scalar_field(i, j)')`
- `@deprecated('_bit_struct', 'bit_struct')`
- …
> [misc] Remove deprecated Python APIs

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_utils.h
- taichi/codegen/spirv/kernel_utils.h
- taichi/program/aot_module_builder.cpp
- taichi/program/aot_module_builder.h
> [Vulkan] Add support of loading AOT modules and fields

- taichi/backends/metal/kernel_manager.cpp
- tests/python/test_random.py
Signed-off-by: knight42 <anonymousknight96@gmail.com>
Related issue = #2734
/cc @k-ye 
I am not sure if the current implementation is desired since I don't know much about cpp 😢 , any advice is welcome!
> [Metal] Pass random seed to metal backend

- taichi/backends/vulkan/aot_module_builder_impl.cpp
This might be a better fix than reverting in #3744 since it keeps most
of @ghuau-innopeak's loading logic.
@ghuau-innopeak you might only need to properly register it else where
to make it fully functional again. (Since we don't have test coverage
for the load() function, I'll temporarily break it and unblock master.
> [bug] Temporarily remove runtime_ usage in aot_module_builder.

- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/cuda/jit_cuda.h
- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
This also reduces the warnings coming out from the LLVM headers, especially on windows, thus improving caching hit rates.
> [misc] Speed-up builds by removing LLVM includes from llvm_program.h

- CMakeLists.txt
- cmake/TaichiCore.cmake
- docs/lang/articles/contribution/contributor_guide.md
- misc/prtags.json
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_common.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/common/platform_macros.h
- taichi/gui/android.cpp
- taichi/gui/gui.h
- taichi/system/interface_registry.cpp
- taichi/system/traceback.cpp
Related issue = #3679
This is an initial support so a lot of features are not supported yet such as the logging with logcat or traceback.
> [Android] Add initial support of the platform

- taichi/backends/opengl/codegen_opengl.cpp
- tests/python/test_aot.py
> [bug] Enable int32 atomic ops for opengl backend.

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_materialize_check.py
Related issue = #2590
After this PR, the following code snippet:
```py
ti.init()
a = ti.Matrix.field(2, 2, ti.i32)
ti.root.dense(ti.i, 10).place(a.get_scalar_field(0, 0))
ti.root.dense(ti.i, 11).place(a.get_scalar_field(0, 1))
ti.root.dense(ti.i, 10).place(a.get_scalar_field(1, 0))
ti.root.dense(ti.i, 11).place(a.get_scalar_field(1, 1))
@ti.kernel
def func():
pass
func()
```
will give the following error:
```
RuntimeError: Members of the following field have different shapes [(10,), (11,), (10,), (11,)]:
File "test_matrix_field_member_shape.py", line 4, in <module>
a = ti.Matrix.field(2, 2, ti.i32)
```
> [Lang] Enforce members of a matrix field to have same shape

- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/codegen/spirv/spirv_ir_builder.h
We always use integral types for buffer type. This leads to SPIRV with invalid type errors.
For example, looking at the AOTed SPIRV of mpm 99, one can find things like:
```
%575 = OpAccessChain %_ptr_StorageBuffer_int %root_buffer_0 %int_0 %574
%tmp402 = OpAtomicFAddEXT %float %575 %int_1 %int_0 %tmp400
```
This is not valid, because we're treating a int pointer as a float pointer. Tools like `spirv-val` complains about this.
btw, I don't understand why `get_primitive_buffer_type` was introduced in the first place hmm.
> [vulkan] Fix SPIRV types

- misc/demo_warning.py
- python/taichi/__init__.py
- python/taichi/lang/__init__.py
- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
Related issue = close #3590 
This PR further removes more deprecated APIs: 
Also, for other related repos:
After this PR, there should be almost no deprecated APIs in the codebase:
```bash
❯ rg "deprecated" python
python/taichi/main.py
658:            'ti test is deprecated. Please run `python tests/run_tests.py` instead.'
python/taichi/__init__.py
22:deprecated_names = {'SOA': 'Layout.SOA', 'AOS': 'Layout.AOS'}
24:    for name, alter in deprecated_names.items():
29:        if attr in deprecated_names:
31:                f'ti.{attr} is deprecated. Please use ti.{deprecated_names[attr]} instead.',
34:            exec(f'{attr} = {deprecated_names[attr]}')
python/taichi/tools/__init__.py
16:    'deprecated',
python/taichi/tools/util.py
81:def deprecated(old, new, …
```
> [Misc] Remove more deprecated APIs

- python/taichi/aot/module.py
- python/taichi/lang/impl.py
- python/taichi/lang/mesh.py
- python/taichi/main.py
- python/taichi/tools/np2ply.py
- python/taichi/ui/utils.py
- scripts/generate_pylint_tags.py
Related issue = #3151 
C0321: More than one statement on a single line (multiple-statements)
C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
> [Lang] Fix pylint rule C0321 (multiple-statements) and C0325 (superfluous-parens).

- taichi/backends/opengl/shaders/atomics_macro_f32.glsl.h
- taichi/backends/opengl/shaders/atomics_macro_f64.glsl.h
`new` is reserved in Metal shading language so let's avoid using these critical names in general.
> [bug] [opengl] Avoid using new as variable name in generated glsl.

- python/taichi/lang/snode.py
- taichi/ir/snode.h
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/llvm/llvm_fwd.h
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- tests/python/test_snode_layout_inspection.py
Related issue = #2590
Exposing `offset_bytes_in_parent_cell` of a `SNode` is a prerequisite for analyzing memory layouts of different SNodes, which can further unblock the algorithm design of turning dynamic indexing of vector/matrix fields into the form of `pointer + offset`.
For now the functionality is only added in the LLVM backend.
> [ir] [llvm] Add offset_bytes_in_parent_cell to SNode

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
Related issue = fixes #3796
The phenomenon in #3796 appears after #3517. However, #3517 is not the root cause - after #3517, since the initial IR of that example changes, the optimization of `pow` in CHI IR goes into a different path and lets the OpenGL backend to calculate the result, which exposes a bug which already exists.
Let's look at a code snippet:
```py
ti.init(ti.opengl)
@ti.kernel
def test(a: ti.f32, b: ti.f32) -> ti.f32:
return a ** b
print(test(-1.0, 2.0))
```
It will give `nan` as the result because in OpenGL `pow(x, y)` has undefined behavior when `x < 0` (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/pow.xhtml). Therefore, we should avoid doing such calculation.
In that example, `pow()` comes from `norm_sqr()` of the `Matrix` class. To fix …
> [Bug] [opengl] Modify the implementation of norm_sqr()

- python/taichi/tools/__init__.py
- python/taichi/tools/sort.py
- tests/python/test_sort.py
This is an implementation of parallel odd-even merge sort.
related issue = #3764 
References:
https://developer.nvidia.com/gpugems/gpugems2/part-vi-simulation-and-numerical-algorithms/chapter-46-improved-gpu-sorting
https://en.wikipedia.org/wiki/Batcher_odd%E2%80%93even_mergesort
This will be very useful for #3781 as well. We likely won't be having atomics in WebGPU (sadge), but one can always use a sort to simulate atomic operations. To demonstrate this, I will open another PR to add versions of `mpm99.py` and `pbf2d.py` that are atomics-free but uses sorting.
> [lang] Add parallel sort utility

- python/taichi/_lib/utils.py
- python/taichi/lang/__init__.py
Now version check runs silently per 7 days. Nothing will be printed in terminal.
If user's version is outdated, a latest_version file will be written to ~/.taichi and the latest version will be recorded.
After that, no more version check in 7 days. When user use Taichi again, if the current version is lower than the version recorded in the file, the latest version will be printed with the Taichi header. For example:
`[Taichi] version 0.8.7, latest version 0.9.0, llvm 10.0.0, commit abcdef, linux, python 3.8.10`
> [misc] Slient & non-blocking version check

- taichi/backends/cuda/cuda_device.cpp
- taichi/backends/cuda/cuda_device.h
- tests/python/test_ndarray.py
When using preallocated memory, deallocation is handled by LLVMProgramImpl [finalize](https://github.com/taichi-dev/taichi/blob/3818ba3142288752ebdd8c57bd47e92501aafcac/taichi/llvm/llvm_program.cpp#L479) instead of CUDA device.
> [lang] Fix ndarray cuda dealloc when using preallocated memory

- .github/workflows/release.yml
- .github/workflows/testing.yml
- cmake/TaichiCore.cmake
This is a follow-up PR of #3735 to make the release work properly.
> [ci] Enforce using ninja on Windows in both release and normal testing

- python/taichi/lang/__init__.py
- python/taichi/lang/common_ops.py
- python/taichi/lang/impl.py
- python/taichi/lang/ops.py
- python/taichi/lang/snode.py
Related issue = #3782 
In `ops.py`, a snode-related function introduced the dependence of `Matrix` to the file, which caused circular import. So, I moved the snode-related functions to `snode.py`.
> [refactor] Remove import taichi in common_ops.py

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_custom_struct.py
- tests/python/test_matrix.py
Related issue = fixes #3826
Previously we attempt to not enforce evaluating and storing compound type values in `expr_init()` whenever possible to avoid duplicate initialization, which turns out to be buggy because there are cases (#3826) where we cannot automatically make the decision. To fix it, I cancel the checks and stick to the non-optimized version of `expr_init()` in this PR.
> [Bug] [lang] Fix copying a Matrix/Struct in Taichi scope

- python/taichi/lang/meta.py
In #3778, the use of `in` is temporarily removed due to lack of support. After #3792, `in` is supported again so we can add it back.
> [refactor] Recover 'in' operator in vector_to_fast_image()

- taichi/backends/cuda/cuda_device.cpp
This prevents any side effect when read/write to the cached memory returned by ndarray memory allocator.
> [bug] [cuda] Fix memset before reusing cuda cached memory

- taichi/program/compile_config.cpp
- tests/python/test_ndarray.py
This PR disables the usage of torch for ndarray by default, by switching to Taichi's own memory allocator.
> [Lang] Use ndarray own memory allocator by default

- taichi/backends/opengl/opengl_api.cpp
* #3835
* #3834
* #3833
* __->__ #3832
Binding won't change among different offloaded tasks in the same
ti.kernel so we can save some time here.
For my ndarray based mpm88 benchmark, this improves from 12.50 fps to
13.01 fps.
> [opengl] Only bind buffers per ti.kernel.

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/kernel_utils.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/spirv/kernel_utils.cpp
- taichi/program/callable.cpp
- taichi/program/callable.h
- taichi/program/kernel.cpp
- taichi/python/export_lang.cpp
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/transforms/inlining_test.cpp
* #3835
* #3834
* __->__ #3833
* #3832
This PR is a simple massive rename PR which serves as the first step to
separate internal ndarray and external array implementation.
> [refactor] Rename is_external_array -> is_array and arr_bufs_ -> ext_arr_bufs_

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
When reusing one args_buf for different gl kernels we spend a lot of
time on glMapBufferRange() in syncing. But these syncs are indeed not
necessary. Now we just create one args_buf per kernel launch.
This improve mpm88 benchmark from 16.67fps to 33fps.
Thanks to @k-ye and @bobcao3 for helping!
Will try to clean this up (some logic can be shared with vulkan runtime iiuc) in followup PRs. 
> [opengl] Allocate new arg bufs per kernel launch

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
- tests/python/test_matrix.py
- tests/python/test_tensor_reflection.py
Related issue = close #3810
This PR implements the algorithm in #3810, and the result stride is stored in `dynamic_index_stride` of `MatrixField` instances. The tests cover both valid (the example in #3810) and invalid cases. `path_from_root()` is added to the `SNode` class by the way.
> [lang] Calculate dynamic indexing strides of matrix field elements

- tests/python/test_fields_builder.py
Related issue = #2724 
1. Add more compliated test for destroying and building of field builder:
1. test field with shape;
2. test fields builder dense;
3. test_fields builder pointer;
4. test fields builder destroy.
2. Re sort out and rename existing tests.
Please give some advice etc.
> [test] Add more complicated tests for building and destroying SNodeTrees

- python/taichi/lang/ast/ast_transformer.py
Related issue = #3608
``` python
import taichi as ti, argparse
parser = argparse.ArgumentParser()
parser.add_argument('--json')
args = parser.parse_args()
outer = 'faces'
inner = 'edges'
ti.init(arch=ti.cuda)
vecf = ti.types.vector(3, ti.f32)
mesh = ti.TetMesh()
mesh.faces.link(mesh.edges)
mesh.faces.link(mesh.verts)
bunny = mesh.build(ti.Mesh.load_meta(args.json))
faces = bunny.faces
@ti.kernel
def get_off():
for i in faces:
pass
get_off()
```
make `for i in faces:` in `ti.kernel` work.
> [mesh] A small fix for mesh loop syntax in python frontend

- taichi/analysis/alias_analysis.cpp
- tests/cpp/analysis/alias_analysis_test.cpp
This PR is a follow-up of #2952. Making alias analysis more accurate can unblock future optimizations on `ExternalPtrStmt` (many of current optimization passes only focus on `GlobalPtrStmt`).
That said, we can already observe some benefits of this PR. For example, regarding the following code snippet,
```py
@ti.kernel
def test(a: ti.any_arr(element_dim=1)):
a[i][0] = i
a[i][1] = i * 2
a[i][2] = a[i][0]
a = np.zeros((10, 3))
test(a)
```
Before this PR, the final CHI IR is,
```
kernel {
$0 = offloaded range_for(0, 10) grid_dim=0 block_dim=32 
body {
<i32> $1 = loop $0 index 0
<*f64> $2 = arg[0]
<i32> $3 = const [0]
<*f64> $4 = external_ptr <$2>, [$1, $3]
<f64> $5 = cast_value<f64> $1
$6 : global store [$4 <- $5]
<i32> $7 = const [1]
<i32> $8 = bit_shl $1 $7
<*f64> $9 = …
```
> [opt] Add more accurate alias analysis for ExternalPtrStmt

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
Related issue = #2590, #2880
This PR makes one use case of `_IntermediateMatrix` class, an element of a matrix field, more explicit. It can unblock the implementation of enabling dynamic indexing of matrix field elements.
> [refactor] Add _MatrixFieldElement class

- cmake/TaichiCore.cmake
- taichi/ui/backends/vulkan/app_context.cpp
- taichi/ui/backends/vulkan/app_context.h
- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/backends/vulkan/renderable.cpp
- taichi/ui/backends/vulkan/renderer.cpp
- taichi/ui/backends/vulkan/renderer.h
- taichi/ui/backends/vulkan/swap_chain.cpp
- taichi/ui/common/field_info.h
- taichi/ui/utils/utils.h
> [Android] [gui] Add initial support of Android in GGUI

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
- tests/python/test_aot.py
* #3901
* #3900
* __->__ #3884
Note this PR reduces number of generated shaders for mpm88 from 10 to 6.
There's still one gtmp related shader remaining for temporary values
used across multiple shaders. Whether to further remove that shader need
more benchmark so let's just get rid of addtional shaders introduced by
ndarray range_for for now.
> [opengl] Optimize range_for for ndarrays

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
* __->__ #3910
* #3909
This is a part of cprofile result when I profile python launch
overhead for ndarray kernels.  Note how `dtype/n/m/shape` queries takes up a
lot of time in extract_args. These are indeed caused by `property` which
is super slow.  We should just make them normal attributes to speed
things up.
This PR reduces the time we spent at `extract_args` from 1.6s to 1.01s
in my profiled use case.
Reference:
https://stackoverflow.com/questions/21174590/property-speed-overhead-in-python
Note that I didn't get rid of all properties here, there're still some
low hanging fruit like `element_shape`.
```
/home/ailing/github/taichi/python/taichi/lang/kernel_impl.py:252(extract_arg)                                        -> …
```
> [perf] Avoid using property for simple attributes to reduce python overhead.

- python/taichi/lang/impl.py
Related issue = #3906
https://github.com/taichi-dev/taichi/runs/4664728269?check_suite_focus=true shows that #3906 causes performance regression. This PR aims at fixing it by clearing `global_vars`/`matrix_fields` after `materialize()` because they should not be handled in the next `materialize()`.
> [perf] Clear global_vars/matrix_fields after materialize()

- taichi/transforms/offload.cpp
> [opt] [ir] [refactor] Remove exceptions from offload pass

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
- taichi/backends/cpu/cpu_device.cpp
- taichi/backends/cpu/cpu_device.h
- taichi/backends/cuda/cuda_device.cpp
- taichi/backends/cuda/cuda_device.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/ndarray.cpp
- tests/python/test_ndarray.py
Speedup ndarray `fill` using `cuMemset32D` and `std::fill` instead of the kernel-based approach. Measured speedups (using the test script from [PR 3907](https://github.com/taichi-dev/taichi/pull/3907):
`ti.Matrix.ndarray(4, 4, ti.f32, N)`
1. `ti.init(arch=ti.cuda) `
| `iterations` | Master | Head |
| ------------- | ------------- | ------------- |
| 10  | 0.457 s| 0.050 ms  |
| 100  | 4.705 s | 0.475 ms |
| 1000  |  65.971 s | 4.374 ms |
2. `ti.init(arch=ti.cpu) `
| `iterations` | Master | Head |
| ------------- | ------------- | ------------- |
| 10  | 0.407 s| 0.150 s  |
| 100  | 4.144 s | 1.488 s |
| 1000  | 42.127 s  | 14.693 s |
> [refactor] Optimize vector and matrix ndarray fill

- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/exception.py
- tests/python/test_exception.py
Related issue = fixes #3785 
Error message of the program in the issue after this PR:
```
File "/home/lin/tmp/./test.py", line 15, in <module>
foo()
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 715, in wrapped
return primal(*args, **kwargs)
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 643, in __call__
key = self.ensure_compiled(*args)
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 629, in ensure_compiled
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 475, in materialize
taichi_kernel = _ti_core.create_kernel(taichi_ast_generator,
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 465, in …
```
> [Error] Shorten the length of traceback of exceptions thrown by ASTTransformer

- taichi/analysis/data_source_analysis.cpp
- taichi/ir/control_flow_graph.cpp
- taichi/program/compile_config.cpp
Related issue = #2590
Currently, running our `cornell_box` example with `dynamic_index=True` is 21.4x slower than with `dynamic_index=False`, which is intolerable. This PR serves as a first step towards aligning their performance, and makes it only 3.7x slower now.
Technically, this PR is a follow-up of #3237. In fact, #3237 only makes `store_to_load_forwarding` for local tensors work properly within a basic block. And for code snippets like this:
```py
ti.init(print_ir=True, dynamic_index=True)
@ti.kernel
def func(x: ti.i32):
a = ti.Vector([0])
b = 0
if x > 0:
b = 1
print(a[0], b)
func(2)
```
It will generate the following IR:
```
kernel {
$0 = offloaded  
body {
<i32> $1 = const [1]
<i32> $2 = const [0]
<[Tensor (1, 1) i32]> $3 = alloca
<*i32> $4 = shift ptr [$3 + …
```
> [opt] Get store_to_load_forwarding work with local tensors across basic blocks

- python/taichi/lang/ast/ast_transformer_utils.py
- tests/python/test_exception.py
Related issue = fixes #3784 
`max(node.body[0].lineno - 1, node.lineno)` is to deal with circumstances when `node.body[0]` starts on the same line as `node` and ends on another line. It makes sure at least one line can be printed. For example:
```python
for i in range(1, 2, 3):print(
i)
```
> [Error] Do not show body in exceptions in nodes with body

- taichi/aot/module_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/program/aot_module.h
Related issue = #3334
I haven't really switched OpenGL or Vulkan to use these new AOT structs yet, but the migration should be very simple, e.g.,
```cpp
auto ad = AotDataConverter::convert(aot_data_);
TextSerializer ts;
t2.serialize_to_json("aot_data", ad);
t2.print();
```
I've also added/removed/changed a few field names:
* `ScalarArg`
* `offset_in_bytes_in_args_buf` --> `offset_in_args_buf`
* `ogl::CompiledArrayArg` --> `aot::ArrayArg`
* `shape_offset_in_bytes_in_args_buf` --> `shape_offset_in_args_buf`
* Added `bind_index`
* `CompiledTaichiKernel`
* `arg_count` --> `args_count`
* `ret_count` --> `rets_count`
* `args_buf_size` --> `args_buffer_size`
* `ret_buf_size` --> `rets_buffer_size`
* Removed `used.arr_arg_to_bind_idx`
> [aot] Add a generic set of AOT structs

- python/taichi/lang/kernel_impl.py
- tests/python/test_exception.py
Related issue = #3785
For the following program:
```python
ti.init()
@ti.kernel
def foo():
1 in 2
foo()
```
The traceback looks like this after this PR:
```
File "/home/lin/tmp/./test.py", line 8, in <module>
foo()
File "/home/lin/taichi2/python/taichi/lang/kernel_impl.py", line 724, in wrapped
raise type(e)('\n' + str(e)) from None
taichi.lang.exception.TaichiSyntaxError: 
On line 6 of file "/home/lin/tmp/./test.py":
1 in 2
^^^^^^
"In" is only supported inside `ti.static`.
```
> [Error] Shorten the length of traceback of TaichiCompilationError

- python/taichi/examples/ggui_examples/mpm3d_ggui.py
- python/taichi/examples/simulation/fem128.py
- python/taichi/examples/simulation/fem99.py
- python/taichi/examples/simulation/mpm3d.py
- python/taichi/lang/__init__.py
- tests/python/test_bit_array_vectorization.py
Related issue = #3635
In #3635, we determine that the logical operators in Taichi should behave the same as in Python. Therefore, we should no longer misuse logical operators as bitwise operators anymore. This PR aims at fixing these misuses in examples and tests.
> [example] [test] Fix misuse of logical operators in examples and tests

- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
Related issue = #3982
`FrontendExprStmt` and `FrontendEvalStmt` have identical functionalities.
> [refactor] [ir] Use FrontendExprStmt in place of FrontendEvalStmt

- .github/workflows/scripts/check_clang_tidy.sh
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/codegen/spirv/spirv_ir_builder.h
- taichi/transforms/make_mesh_block_local.cpp
- taichi/transforms/make_mesh_block_local.h
Let's enable the `readability-identifier-naming` check to make use of the rules defined in `.clang-tidy`. Currently, checks only enabled for the `taichi/` directory.
Local checks and fixes can be applied with `python scripts/run_clang_tidy.py $PWD/taichi -clang-tidy-binary clang-tidy-10 -clang-apply-replacements-binary clang-apply-replacements-10 -checks=-*,performance-inefficient-string-concatenation,readability-identifier-naming -header-filter=$PWD/taichi -p $PWD/build -j4 -fix`
> [refactor] [ci] Enable identifier naming in clang-tidy

- taichi/analysis/gather_uniquely_accessed_pointers.cpp
- taichi/transforms/demote_atomics.cpp
Related issue = #3608 
It is worth noting that in a mesh-for loop, the attribute of the from-end element should only be accessed in one loop, like the following case:
``` Python
for c in model.cells:
for i in c.cells.size:
c.a += c.cells[i].b
```
The variable `c.a` is a unique address in the whole loop scope so the atomic operation `+=` should be demoted.
Note that we ignore the following case since it's not reasonable for a parallel program.
``` Python
for c in model.cells:
for i in c.cells.size:
c.a += c.cells[i].a
```
> [mesh] Demote from-end element attribute atomic op

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_mesh.py
Related issue = #3608 
Before this PR, do the neighbor query loop in mesh-for must resort to nested range-for, like:
``` Python
for u in model.verts:
for i in u.verts.size:
u.x += u.verts[i].y
```
This PR implemented the nested mesh-for loop, the code above could be rewritten as:
``` Python
for u in model.verts:
for v in u.verts:
u.x += v.y
```
**Note that the nested mesh-for loop would not be un-looped.**
> [mesh] [opt] Support nested mesh-for

- taichi/analysis/alias_analysis.cpp
- tests/cpp/analysis/alias_analysis_test.cpp
This is not likely not 100% safe, how about banning "passing the same ndarray as
different arguments to a taichi kernel"?
It helps eliminating identical `GlobalLoadStmt`s (whose source are`ExternalPtrStmt`s) in mpm88 aot example. 
> [opt] Add more strict alias analysis for ExternalPtrStmt

- python/taichi/lang/kernel_impl.py
Related issue = #3915 
Orientation:
The python code around kernel launch, say `func__`, has a long and verbose section to check `ndarray` and torch related types and build respective contexts. The performance of those if-else clauses, however, is critical for lightweight kernels with multiple ndarrays. The flags are also kinda confusing. In this PR I refactored the clause regarding `any_arr` in order to make it more readable and efficient. 
Briefings of modifications:
1) Pack the torch-related code in a function
2) refactor the if clauses in order to skip `match_ext_arr` for `Ndarray`
Hope the refactored code reads better :)
> [refactor] Refactor func body to reduce python overhead and improve readability

- taichi/analysis/gather_meshfor_relation_types.cpp
- tests/python/test_mesh.py
Related issue = #3608
In the previous design principle, we restrict one mesh-for should only have one major relation, like the following case:
``` Python
for v in model.verts:
for i in range(v.verts.size):
for i in range(v.cells.size): # it's not allowed before this PR because the major relation is Verts-Verts
```
But we found that supporting multiple major relations in one mesh-for loop is necessary for some scenarios. Otherwise, we must define some extra variables, like this:
``` Python
for v in model.verts:
a, b = 0, 0
for i in range(v.verts.size):
a += v.verts[i].id
for i in range(v.cells.size):
b += v.cells[i].id
v.res = a * b
```
Note that defining `a` and `b` as local variables is far optimized than placing them in the global memory. So we deprecate the single-major-relation …
> [mesh] Support multiple major relations in one mesh-for loop

- taichi/aot/module_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- tests/python/test_aot.py
This PR switch opengl backend to dump `ModuleData` instead of its own structure. 
Followup: need to update the deserializer accordingly for bind_index.
> [opengl] [aot] Convert opengl aot to dump ModuleData.

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/transforms/die.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
* #3980
* __->__ #3979
Previously we only make sure `for i in range(x)` (here `x` is ndarray)
don't get their end_range from gtmp on opengl. This PR expands the scope
to all simple calculations involving only ConstStmt and
ExternalTensorShapeAlongAxisStmt as leaves, and it's not limited to the
end_stmt in RangeForStmt as well. In most cases this should save an
additional serial offloaded task which only saves the simple
intermediates into gtmp.
> [opengl] Do not promote simple ExternalTensorShapeAlongAxisStmt into globals.

- taichi/analysis/mesh_bls_analyzer.cpp
- taichi/analysis/mesh_bls_analyzer.h
- taichi/inc/constants.h
- taichi/ir/analysis.h
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/make_mesh_block_local.cpp
- tests/python/test_mesh.py
Related issue = #3608 
This PR implemented the experimental automatic `ti.mesh_local`. The optimization pass will cache all the atomic-add attributes and ignore the read-only attributes in the CPU backend. In the CUDA backend, when the minimal default occupancy is guaranteed, the optimization pass will cache mesh attributes in specific priority order as much as it could.
> [mesh] [opt] Experimental automatic mesh_local

- taichi/common/serialization.h
- tests/python/test_aot.py
This PR fixes a typo in std::optional serialization and enabled field
based aot tests for vulkan backend.
Note our `arch` in `ti.aot.Module(arch)` API is ignored, this API is a bit
misleading so we made it clear in tests.
> [vulkan] [aot] Enable aot tests for vulkan backend.

- taichi/ir/control_flow_graph.cpp
- tests/python/test_matrix.py
Related issue = fixes #3954
We should treat any `PtrOffsetStmt` (previously local tensors are excluded) as if it has already been stored with random values to prevent invalid optimization.
> [bug] [opt] Treat PtrOffsetStmt as random-initialized

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- tests/python/test_aot.py
* #4012
* #4011
* __->__ #4010
related: #3334
I made a mistake in #4000 that vulkan aot doesn't support templated
kernel yet. This PR made it an explicit error and split the tests.
> [vulkan] [aot] Throw error for templated kernels in vulkan aot.

- cmake/TaichiCXXFlags.cmake
Fixes #3939.
I have AppleClang12.0.5 and enabling lto=thin made linking
extremely slow here. Need to check if it's related to my clang version.
But let's disable it first :P.
> [build] Disable LTO for mac.

- taichi/ir/transforms.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/frontend_type_check.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_type_check.py
Related issue = close #3633
Remaining issues:
- `TypeError`s thrown by frontend stmt typechecker are not catched and wrapped into `TaichiCompilationError` for now
> [ir] [refactor] Split stmt typechecking to the frontend

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/codegen/spirv/kernel_utils.h
* #4012
* __->__ #4011
related #3334
This PR implements a converter to convert vulkan aot data structure to
unified taichi::aot::ModuleData.
> [vulkan] [aot] Switch vulkan aot to use taichi::aot::ModuleData.

- taichi/aot/module_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.cpp
* __->__ #4012
* #4039
related #3334
This PR mainly replaces row_num & column_num with `element_shape` so
that it aligns with ndarrays.
> [aot] Use element_shape instead of row_num & column_num for CompiledFieldData.

- taichi/jit/jit_session.cpp
- taichi/jit/jit_session.h
- taichi/program/ndarray.h
Related issue = fix #3999
Taichi isn't at a state that can be built easily without LLVM at all. Currently, the `-DTI_WITH_LLVM=OFF` doesn't mean that Taichi will be built without using LLVM at all. Fixing this problem completely in the future version is that we should consider, which is difficult but necessary.
> [bug] Fix bug that building with TI_WITH_LLVM=OFF will fail

- taichi/backends/opengl/codegen_opengl.cpp
We have reserved bind idx 0~3 for root, gtmp, args and runtime,
so let's force generated bind_idx for array args to be `arg_id + 4`.
> [opengl] Make sure ndarray arg bind indices are sorted.

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/ast/transform.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
> [refactor] Re-export some functions called directly by ASTTransfomer.* as member of ASTBuilder

- benchmarks/microbenchmarks/__init__.py
- benchmarks/microbenchmarks/_items.py
- benchmarks/microbenchmarks/_plan.py
- benchmarks/microbenchmarks/_result.py
- benchmarks/microbenchmarks/_results.py
- benchmarks/microbenchmarks/_utils.py
- benchmarks/microbenchmarks/fill.py
> [misc] Add a minimal example for micro-benchmarks

- taichi/aot/module_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
- tests/python/test_aot.py
* #4071
* __->__ #4070
opengl backend.
For range_for offloaded tasks, we try our best to provide some hints
about the range.
- If the range is known at compile time, it shows as
```
"type": "range_for",
"range_hint": "8192",
```
- If the range is range of a ndarray, it shows as
```
"type": "range_for",
"range_hint": "arg <X>",  # X is ndarray's arg_id
```
For other ranges that's only known at runtime, we currently don't handle
them.
note to self: I actually hacked a version to print out the IR of the
end_stmt of OffloadStmt. Although more accurate, it's not easy to parse
so I just abandoned it. prototype at
https://github.com/taichi-dev/taichi/compare/master...ailzhang:range_hint_aot?expand=1
> [aot] [opengl] Provide range_hint for range_for offloaded tasks in

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_syntax_errors.py
Related issue = close #4075 
The matrix type can be redefined as well, so I also fixed it in this PR.
> [Bug] [lang] Ban redefinition of template and matrix arguments in Taichi kernel

- cmake/TaichiCore.cmake
- cmake/TaichiTests.cmake
- misc/prtags.json
- taichi/backends/dx/dx_api.h
- taichi/backends/dx/dx_device.cpp
- taichi/backends/dx/dx_device.h
- taichi/backends/dx/dx_info_queue.cpp
- taichi/backends/dx/dx_info_queue.h
- tests/cpp/backends/dx11_device_test.cpp
Related issue = #992
This change adds an underlying DX11 device, memory allocation, and some tests.
The tests for the Device functionalities make it easier to confirm the functionalities are working without having to touch the rest of the code base (such as Program) or having to run a .py Taichi program.
I wonder if backend-specific tests are a good approach?
> [dx11] Add underlying DX11 device, memory allocation, and some tests

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/type_check.cpp
Related issue = #4035
`global_thread_idx` is the only expr that can be refactored into a funccall without mass refactoring for now.
> [refactor] [ir] Use InternalFuncCall for retrieving thread index

- taichi/inc/statements.inc.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/frontend_type_check.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
Related issue = #4035 
`ExternalFuncCallExpression`s do not have return values and are always wrapped in `FrontendExprStmt`s. Therefore it'll be better if it is just a stmt by itself.
> [refactor] [ir] Refactor ExternalFuncCallExpression into a frontend stmt

- misc/prtags.json
Related issue = #3781
Having received positive results in my own [experimentations](https://github.com/AmesingFlank/ti.js/blob/master/src/examples/taichi4/main.ts), I'm confident of the feasibility of implementing a version of taichi in pure Javascript. I'd like to start merging PRs that prepare for this project. These PRs don't implement any real functionalities, instead, they only serve the following two purposes:
* Enable the existing Taichi code base to be built into a JS library, via [emscripten](https://emscripten.org/)
* Export the APIs necessary for the js frontend, via [embind](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html)
Once these PRs are merged, one will be able to build a `.js` library of taichi, simply by setting the `TI_EMSCRIPTENED` cmake …
> [javascript] Add Javascript PR tag (JS 0/n)

- cmake/TaichiCore.cmake
- cmake/TaichiExamples.cmake
Related issue = #3781
Having received positive results in my own [experimentations](https://github.com/AmesingFlank/ti.js/blob/master/src/examples/taichi4/main.ts), I'm confident of feasibility of implementing a version of taichi in pure Javascript. I'd like to start merging PRs that prepare for this project. These PRs doesn't implement any real functionalities, instead, they only serve the following two purposes:
* Enable the existing Taichi code base to be built into a JS library, via [emscripten](https://emscripten.org/)
* Export the APIs necessary for the js frontend, via [embind](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html)
Once these PRs are merged, one will be able to build a `.js` library of taichi, simply by setting the `TI_EMSCRIPTENED` cmake …
> [javascript] Add TI_EMSCRIPTENED to cmake options (JS 1/n)

- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/struct_opengl.cpp
- taichi/program/aot_module.cpp
- taichi/program/aot_module.h
- tests/python/test_aot.py
Fixes #4089
Also deduplicated the `get_snode_base_address` between compilation and
aot module builder. We can do it only once when calculating root buffer
size.
> [opengl] Use element_size as alignment in root buffer.

- docs/lang/articles/advanced/meta.md
- docs/lang/articles/basic/difference_between_taichi_and_python_programs.md
- docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
- docs/lang/articles/basic/external.md
- docs/lang/articles/basic/field.md
- docs/lang/articles/basic/type.md
> [doc] Add doc about difference between taichi and python programs

- taichi/transforms/constant_fold.cpp
> [refactor] Remove dependency on lang::current_ast_builder() in lang::ConstantFold

- cmake/TaichiCore.cmake
Empty `TAICHI_EMBIND_SOURCE` works on cmake 3.22 but not 3.19 so let's
just condition on it.
> [build] Handle empty TAICHI_EMBIND_SOURCE

- misc/make_changelog.py
> [misc] Fix the changelog generator to only count current branch commits

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- tests/python/test_abs.py
- tests/python/test_element_wise.py
- tests/python/test_f16.py
- tests/python/test_loops.py
- tests/python/test_matrix.py
- tests/python/test_scalar_op.py
Related issue = #4087, #3782
Renamed `ti.ti_max` and `ti.ti_min` to `ti.max` and `ti.min`, and added deprecate warnings to builtin `max` and `min`.
Deprecated element-wise select operation in conditional expression.
> [Refactor] Remove exposure of internal functions in taichi.lang.ops

- python/taichi/_testing.py
- tests/python/test_gui.py
- tests/python/test_image_io.py
* #4114
* #4113
* #4112
* __->__ #4111
Related: #3782
`make_temp_file` can be easily replaced by native python tempfile so
let's just use tempfile.
> [test] Replace make_temp_file with tempfile

- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/backends/vulkan/vulkan_loader.cpp
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/gui/gui.h
Related issue = #3781
Avoid all usages of glfw/vulkan/volk when TI_EMSCRIPTENED. To build the JS frontend, we will only be using the AOT features in Taichi. However, Taichi's vulkan backend will try to invoke glfw/vulkan/volk stuff even when using AOT. This PR guards that from happening.
> [javascript] Avoid all usages of glfw/vulkan/volk when TI_EMSCRIPTENED (JS 5/n)

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_scalar_op.py
> [bug] Fix starred expression when the value is not a list

- docs/lang/articles/get-started.md
- docs/lang/articles/misc/gui.md
- python/taichi/ui/gui.py
Shrunk GUI doc a lot. This is my first revision. What's everybody else's opinions?
> [doc] Revise doc for GUI system.

- python/taichi/lang/__init__.py
- python/taichi/lang/struct.py
- python/taichi/types/primitive_types.py
> [Refactor] Avoid exposing real and integer types API

- cmake/TaichiCore.cmake
- taichi/backends/cuda/jit_cuda.cpp
- taichi/backends/device.h
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/codegen/spirv/kernel_utils.cpp
- taichi/codegen/spirv/kernel_utils.h
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.h
First step towards ndarray on SPIRV backends.
Also fixed a few small things to speed up compilation a small bit.
cc: @xwang186
> [spirv] Move external arrays into seperate buffers

- python/taichi/__init__.py
- python/taichi/profiler/__init__.py
- python/taichi/profiler/scoped_profiler.py
- python/taichi/tools/__init__.py
- python/taichi/tools/util.py
`ti.print_profile_info` -> `ti.profiler.print_scoped_profiler_info`
`ti.clear_profile_info` -> `ti.profiler.clear_scoped_profiler_info`
The old APIs are marked as deprecated for now. The docs will be updated after the next release.
> [Refactor] Rename and move scoped profiler info under ti.profiler

- cmake/TaichiCore.cmake
- taichi/common/core.h
- taichi/common/interface.h
- taichi/common/serialization.h
- taichi/program/callable.cpp
- taichi/program/callable.h
- taichi/program/kernel.h
- taichi/program/program.h
- taichi/python/exception.cpp
- taichi/system/traceback.cpp
- taichi/system/traceback.h
Related issue = #4097
* Renaming `TI_EXPORT` to `TI_DLL_EXPORT` to make its semantics more obvious.
* Changed cmake files so that it is configurable to use `default` or `hidden` symbol visibility.
* Exported `Program`, `Kernel` and `Callable` as a start.
@ghuau-innopeak @xwang186: Note that this PR still uses the `default` visibility. Once this is merged, could you folks help flip to `hidden`, and see if it still works on Android :-)?
> [refactor] Add TI_DLL_EXPORT to control symbol visibility

- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/math/svd.h
- tests/cpp/ir/frontend_type_inference_test.cpp
> [refactor] Remove dependency on current_ast_builder() in lang::For and cpp_tests

- taichi/backends/opengl/struct_opengl.cpp
- tests/python/examples/autodiff/test_minimization.py
- tests/python/test_aot.py
We need to process `snode.ch` in the order of their
`mem_offset_in_parent` so that the computed alignment is correct.
Also noticed the minimization autodiff test had a too strict `rel` (fails randomly on master) so
relaxing it a bit.
> [bug] [opengl] Process child nodes to compute alignment

- setup.py
Related issue = #3781 
This PR makes it more convenient to turn on TI_EMSCRIPTENED.
Now you can do `TI_EMSCRIPTENED=1 python setup.py develop --user`, so that you won't have to edit the `TAICHI_CMAKE_ARGS` variable.
> [javascript] Support TI_EMSCRIPTENED option as an env var (JS 3/n)

- taichi/program/program.cpp
> [javascript] Avoid using C++ inline asm when TI_EMSCRIPTENED (JS 6/n)

- docs/lang/articles/contribution/utilities.md
- python/taichi/examples/autodiff/regression.py
- python/taichi/lang/__init__.py
- python/taichi/lang/misc.py
- python/taichi/tools/__init__.py
- python/taichi/tools/util.py
- tests/python/test_assert.py
- tests/python/test_debug.py
`set_gdb_trigger` is a redundant API because `gdb_trigger` is already a configuration option in `ti.init`.
> [Refactor] Remove redundant set_gdb_trigger

- python/taichi/tools/__init__.py
- python/taichi/tools/async_utils.py
- tests/python/test_async.py
- tests/python/test_sfg.py
Now all functions in `tools.util` are async-related and need to be hidden.
> [Refactor] Rename tools.util to tools.async_utils and hide functions inside

- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device_creator.cpp
- taichi/backends/vulkan/vulkan_memory_allocator.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
depends on #4205 (due to changes in VMA and the need of loading vk func ptrs through Volk)
Fix support for Vulkan 1.3. All the Vulkan headers and SPIR-V tooling has been updated to support in Vulkan 1.3 and SPIR-V 1.6
FYI: A list of (non-comprehensive) supported devices https://vulkan.gpuinfo.org/listdevices.php
These drivers are shipping Vulkan 1.3:
- Intel Mesa driver (Linux) >= 21.99
- AMD Mesa driver (Linux) >= 22.0
- Nvidia driver >= 497 (new feature) or >= 510 (production)
- AMD proprietary driver >= 2.0.213
> [vulkan] Support Vulkan 1.3

- python/taichi/__init__.py
`__all__` in `taichi/__init__.py` needs to be cleaned to make our api-doc site show top-level APIs properly.
> [refactor] Remove top level __all__

- docs/lang/articles/contribution/dev_install.md
It seems currently when building from source, by default, taichi will not enable Vulkan backend. Only when the cmake flag "TI_WITH_VULKAN" set to `on` will it be enabled. See  https://github.com/taichi-dev/taichi/blob/00183bbe9b966727c2a28fdfadb17286ba90eb17/cmake/TaichiCore.cmake#L8 . 
As a result, I was unable to use Vulkan backend for my custom build of taichi, and finding out this took me a long time. For some strange reasons, the step of setting this cmake flag is shown in the Windows section, but not in the Linux section. This commit adds the missing step of setting cmake flags back to the Linux section.
It seems to be caused by https://github.com/taichi-dev/taichi/commit/31a1f72e72f3e8fdb44e350d29a737085f2ff02a#diff-60d6ef959481bb49f8acf52a43314bd4dbfadedb2341043488620077b32bae93 . …
> [doc] Add the step of setting "TI_WITH_VULKAN" for linux

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_for.py
Refactor the IB identification, remove the abused `gather_statements`.
Optimize the IB checker for global atomics and purely nested loops to avoid stack overflow of `ad_stack`.
> [autodiff] Refactor the IB identification and optimize the checker for global atomics and purely nested loops

- python/taichi/lang/kernel_impl.py
- tests/python/test_torch_io.py
> [Bug] Ban passing torch view tensors into taichi kernel

- python/taichi/__init__.py
- python/taichi/lang/misc.py
- python/taichi/profiler/__init__.py
- python/taichi/profiler/memory_profiler.py
> [Refactor] Rename and move memory profiler info under ti.profiler

- benchmarks/microbenchmarks/__init__.py
- benchmarks/microbenchmarks/memcpy.py
This PR adds a `memcpy` case to the micro-benchmark suites.
> [misc] Add memcpy to micro-benchmarks

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- taichi/ir/expr.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- tests/python/test_binding.py
Fixes #4210
This PR also simplifies the clamping logic by:
1. Make sure constant is valid in range of specified dtype.
2. Always use the widest int64/float64 to communicate between python and C++ and
converts it to the specified dtype in C++. This is just to avoid
handling each dtype on both python and C++ side.
We might consider further improve it by moving this logic from python to C++ in the future and this PR made it a step closer.
> [lang] Annotate constants with dtype without casting.

- taichi/ir/frontend.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
> [refactor] Remove lang::current_ast_builder() and dependencies on it

- .github/workflows/release.yml
OS is too old to install molten-vk. Let's skip it for now.
> [ci] Disable Vulkan backend for mac1014 release.

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/expr.py
- python/taichi/lang/mesh.py
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/expression.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/cpp/ir/frontend_type_inference_test.cpp
> [refactor] Remove dependency on get_current_program() in lang::BinaryOpExpression

- .github/workflows/release.yml
Disabling it since it failed. https://github.com/taichi-dev/taichi/runs/5118967847?check_suite_focus=true#logs 
Also we didn't enable vulkan test on 1015 CI yet, if we want to do a proper release we should enable that first. https://github.com/taichi-dev/taichi/blob/master/.github/workflows/testing.yml#L243
> [ci] Disable Vulkan backend for mac1015 release.

- .github/workflows/release.yml
- .github/workflows/testing.yml
- taichi/backends/vulkan/vulkan_loader.cpp
- taichi/backends/vulkan/vulkan_loader.h
- tests/cpp/aot/aot_save_load_test.cpp
> [vulkan] Test & build macOS 10.15 MoltenVK

- tests/cpp/codegen/refine_coordinates_test.cpp
> [llvm] Add missing pre-processor macro in cpp-tests when LLVM is disabled

- taichi/codegen/spirv/kernel_utils.h
Otherwise we will bind the same buffer over and over again.
> [spirv] Fix buffer info compare to fix external array bind point

- docs/lang/articles/basic/operator.md
- taichi/backends/opengl/codegen_opengl.cpp
> [doc] Improve operators page

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/transforms/compile_to_offloads.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/4266
> [lang] Fix bls_buffer allocation of x64 crashed in py3.10

- python/taichi/lang/matrix.py
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/frontend_ir.cpp
- taichi/program/compile_config.cpp
- tests/python/test_dynamic.py
Related issue = #2590
Using `ptrtoint/inttoptr` for array access prevents LLVM from demoting array alloca into individual allocas, which further prevents mem2reg optimizations. After this PR, with `dynamic_index=True`, we can have the same runtime performance as with `dynamic_index=False` for old code which can only access matrices with constant indices.
> [llvm] Use GEP for array access instead of ptrtoint/inttoptr

- python/taichi/_funcs.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/common_ops.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/matrix.py
- tests/python/test_aot.py
- tests/python/test_atomic.py
- tests/python/test_mpm88.py
- tests/python/test_offload.py
> [lang] Hide internal functions in TaichiOperation

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
> [lang] Hide subscript in Matrix

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
- tests/python/test_matrix.py
- tests/python/test_ssa.py
> [lang] Remove Matrix.value

- python/taichi/lang/field.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
Both of them only apply to leaf SNodes, i.e., fields. So users should get the info from a `Field` instance instead of a `SNode`. After this PR, `dtype` of `SNode` is hidden and `needs_grad` is removed.
> [lang] Hide dtype and needs_grad from SNode

- python/taichi/__init__.py
- python/taichi/lang/misc.py
- tests/python/test_ad_basics.py
- tests/python/test_aot.py
- tests/python/test_dynamic.py
- tests/python/test_global_store_grad.py
- tests/python/test_reduction.py
- tests/python/test_runtime.py
- tests/python/test_svd.py
- tests/python/test_tensor_dimensionality.py
- tests/python/test_test.py
- tests/python/test_unary_ops.py
- tests/test_utils.py
Before this PR we have `ti.cfg` and `ti.lang.impl.current_cfg()` and
they're different objects. It's confusing to have both so let's just
make `ti.cfg` an alias of the other. (it's a bit difficult to hook ti.cfg as function call in python3.6 so let's just skip it for now.)
Note `ti.cfg` used to be default_config before `ti.init()` is called and
now it's `None`. It's safe to change this behavior as nothing can be
done without `ti.init()`.
> [lang] Make ti.cfg an alias of runtime cfg

- docs/lang/articles/basic/overview.md
Preview: https://deploy-preview-4306--docsite-preview.netlify.app/lang/articles/basic/overview
> [Doc] Revise "Why a new programming language"

- setup.py
At the moment setup.py uses DEBUG to set whether build in `Debug` or `Release` mode. This PR adds two other options `RelWithDebInfo` and `MinSizeRel`. Similar to `DEBUG=1`, use `RELWITHDEBINFO=1` to enable the corresponding build option.
> [refactor] Allow more build types from setup.py

- python/taichi/ui/__init__.py
- python/taichi/ui/canvas.py
- python/taichi/ui/scene.py
- python/taichi/ui/ui.py
- python/taichi/ui/utils.py
- python/taichi/ui/window.py
- taichi/python/export_ggui.cpp
- tests/python/test_ggui.py
This PR replaces inheritance with composition to avoid inheriting from a class only available when GGUI is available. Now APIs  exposed from the `ui` subpackage will not depend on whether `GGUI_AVAILABLE=True`. Meanwhile, the error checking for using GGUI when `GGUI_AVAILABLE=False` remains the same.
> [gui] [refactor] Avoid exposing different APIs with different GGUI_AVAILABLE values

- misc/generate_example_videos.py
- tests/python/examples/autodiff/test_minimization.py
`generate_example_videos.py` doesn't throw when the subprocess fails. This PR fixes it.
> [ci] Fix generate_example_videos.py

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- python/taichi/lang/util.py
Split the GPU and Windows tests by per arch to increase parallelism and reduce the total time used. This can reduce our CI from ~40 mins to ~30 mins.
> [ci] Increase ci test parallelism

- docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_ast_refactor.py
- tests/python/test_compare.py
> [lang] Add support for operators "is" and "is not" in static scope and deprecate them

- .github/workflows/testing.yml
There seems to be a discrepancy between testing.yml and release.yml.
For example, my opengl PR #4345 fails at vulkan backend on m1. Also today's
nightly failed. So unifying them here to debug...
> [ci] Use conda python for m1 jobs

- taichi/backends/opengl/struct_opengl.cpp
- taichi/backends/opengl/struct_opengl.h
* __->__ #4345
* #4344
Currently we run 2 passes to generate snode tree layout in opengl
codegen.
1. One pass from leaf to root so that we can calculate the real size &
elem_stride for each snode and sort the children from small to large.
2. Another pass from root to leaf so that we can align as elem_stride.
Note we cannot eliminate the first pass due to
https://github.com/taichi-dev/taichi/blob/master/taichi/backends/opengl/struct_opengl.cpp#L50.
The fix for the alignment issue was simple: we used children_offsets
information in the codegen but didn't update it in the second pass.
This PR fixes the issue and also reorganizes the code a bit to make it
easier to read and understand.
> [bug] Update children_offsets & stride info to align as elem_stride

- python/taichi/lang/kernel_arguments.py
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir_builder.cpp
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
Related issue = #3903
Motivation:
Taichi automatically re-compiles the kernel when element shapes change. Therefore, element shape is compile-time static. This PR embed the element shape information into shader code for OpenGL backend.
Briefings:
* Changed `ExternalTensorExpression` and `ExternalPtrStmt` to get layout and element shape information.
* Changed OpenGL codegen to embed the shapes.
> [opengl] Use element shape as compile information for OpenGL backend

- python/taichi/examples/simulation/implicit_fem.py
An implicit fem example, and also an example to show the usage of dynamic indexing.
Notes for reviewer:
1. Some kernels might be too magic or not fully compatible with Taichi syntax concept.
2. `_ti_core.GGUI_AVAILABLE` is necessary for ggui environment detection, but I am not sure whether it is safe to use it in example for long.
> [example] Add implicit fem example

- cmake/TaichiCore.cmake
- taichi/backends/dx/dx_device.cpp
- taichi/backends/dx/dx_device.h
- taichi/backends/dx/dx_program.cpp
- taichi/backends/dx/dx_program.h
- tests/cpp/backends/dx11_device_test.cpp
Hello!
This change makes the dx11 backend progress to the "map and unmap" step. It also adds a minimal sets of functions needed in the command list.
Tested locally to make sure it builds and passes the unit tests.
> [dx11] Materialize runtime, map and unmap

- python/taichi/lang/misc.py
- taichi/backends/vulkan/vulkan_device_creator.cpp
- taichi/backends/vulkan/vulkan_loader.cpp
Changes made to allow the use of `TI_VISIBLE_DEVICE` to select Vulkan device. Users can use the env var to pick the desired device. 
```
[vulkan_device_creator.cpp:pick_physical_device@340] Found Vulkan Device 0 (Intel(R) Graphics (RKL GT1))
[vulkan_device_creator.cpp:pick_physical_device@340] Found Vulkan Device 1 (NVIDIA GeForce RTX 3080)
[vulkan_device_creator.cpp:pick_physical_device@340] Found Vulkan Device 2 (llvmpipe (LLVM 12.0.0, 256 bits))
```
use export `TI_VISIBLE_DEVICE` to select 0, 1, or 2
> [Vulkan] Enable Vulkan device selection when using cuda

- .github/workflows/release.yml
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
This seem to help fix the random failure in M1 CI. My guess was that vulkan and metal backend using M1 chip simultaneously might cause some weird behavior....
> [ci] Run vulkan and metal separately on M1

- taichi/backends/arch.cpp
- taichi/backends/arch.h
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/lang_util.cpp
- taichi/llvm/llvm_program.cpp
- taichi/program/compile_config.h
- taichi/program/extension.h
- taichi/program/kernel.h
- taichi/program/kernel_profiler.h
- taichi/runtime/runtime.h
- taichi/system/unified_allocator.h
- taichi/ui/common/app_config.h
- tests/cpp/codegen/refine_coordinates_test.cpp
Our AOT module should probably expose Arch as an attribute.
> [refactor] Move arch files

- python/taichi/examples/simulation/implicit_fem.py
Related issue = #4371
Small fix to treat redundant command line arguments.
Before this PR:
```
{15:17}~/playground:master ✗ ➭ ti example implicit_fem
[Taichi] version 0.9.1, llvm 10.0.0, commit 69969997, linux, python 3.8.5
*******************************************
**      Taichi Programming Language      **
*******************************************
Docs:   https://docs.taichi.graphics/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/
Running example implicit_fem ...
usage: implicit_fem.py [-h] [--exp {implicit,explicit}] [--dim DIM] [--gui {auto,ggui,cpu}]
implicit_fem.py: error: unrecognized arguments: example implicit_fem
```
> [example] Fix implicit_fem example command line arguments

- taichi/backends/device.h
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/codegen/spirv/kernel_utils.cpp
- taichi/codegen/spirv/kernel_utils.h
Related issue = #3642
This is needed for NdArray support as well as exporting the DeviceAllocation symbol to external libraries.
> [aot] [vulkan] Output shapes/dims to AOT exported module

- taichi/backends/vulkan/runtime.h
This is requires for AOT module when loaded to create the initial root
buffer otherwise they cannot create the buffer, only the SNodeTreeManager 
class has access to it which is not used in the case of AOT.
Related issue = #3642
> [vulkan] [aot] Move add_root_buffer to public members

- taichi/aot/module_loader.cpp
- taichi/aot/module_loader.h
- taichi/backends/vulkan/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.h
> [aot] [vulkan] Add AotKernel and its Vulkan impl

- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
Lets reduce the test parallelism for m1 to get rid of the flaky test issue. This won't affect our CI build time as m1 is much faster.
> [ci] Reduce test parallelism for m1

- taichi/aot/module_loader.cpp
- taichi/aot/module_loader.h
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.h
Related issue = #3642 
Resolve the following TODO: "Instead of prefixing all classes with "Aot", just put them into the `aot` namespace."
Next step: AotModuleLoader --> aot::Module::load()
> [vulkan] [aot] Add aot namespace Vulkan

- taichi/backends/metal/aot_module_loader_impl.cpp
- taichi/backends/metal/aot_module_loader_impl.h
> [metal] Add AotModuleLoader

- benchmarks/README.md
- benchmarks/deserialize.py
- benchmarks/requirements.txt
- misc/code_format.py
Related issue = #4058
Reads the results of benchmarks from a folder (default: `./results`).
Stores the data as a dictionary, and can be saved as a single file (`results.json`).
> [misc] Add deserialization tool for benchmarks

- docs/lang/articles/basic/external.md
> [Doc] Update PyTorch interface documentation

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/program/kernel.h
- taichi/program/program.cpp
Before: {kernel_name}\_*{**global_counter**}*\_{task_name}{suffix} -> Now: {kernel_name}\_*{**counter_per_kernel**}*\_{task_name}{suffix}
Cascade: ndarry_writer & ndarray_reader 's name should be mangled
Note: Because of async_mode, counter_per_kernel: std::atomic<uint64>
> [refactor] Refactor llvm-offloaded-task-name mangling

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_literal.py
Related issue = #4230
This PR implements the approach 1 in #4230. After this PR, the way to give a type to a literal is `ti.u32(12345678)` instead of
```python
a: ti.u32 = 12345678
```
Of course, you can specify both types of the literal and the variable:
```python
a: ti.u32 = ti.u32(12345678)
```
> [Lang] Support type annotations for literals

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_literal.py
This is a follow-up of #4440 which makes the codebase structure more clear.
> [refactor] Move literal construction to expr module

- python/taichi/lang/expr.py
- tests/python/test_literal.py
Related issue = fixes #4451
In fact, the problem in #4451 is already solved by #4440. This PR further adds error messages under our new type annotation mechanism for literals.
> [Error] Add error messages for wrong type annotations of literals

- taichi/aot/module_loader.cpp
- taichi/aot/module_loader.h
- taichi/backends/metal/aot_module_loader_impl.cpp
- taichi/backends/metal/aot_module_loader_impl.h
- taichi/backends/vulkan/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.h
- tests/cpp/aot/aot_save_load_test.cpp
Towards a simpler AOT runtime API as suggested in issue #3642.
This PR makes the following changes
> [aot] [refactor] Refactor AOT runtime API to use module

- taichi/program/program.cpp
Related issue = #4464
This PR fixes the following linker error 
```
/usr/bin/ld: CMakeFiles/taichi_isolated_core.dir/taichi/program/program.cpp.o: in function `taichi::lang::Program::Program(taichi::Arch)':
program.cpp:(.text+0x561): undefined reference to `taichi::lang::metal::is_metal_api_available()'
/usr/bin/ld: program.cpp:(.text+0x581): undefined reference to `taichi::lang::MetalProgramImpl::MetalProgramImpl(taichi::lang::CompileConfig&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
To reproduce: https://github.com/taichi-dev/taichi/issues/4464#issuecomment-1060295541
> [bug] Fix metal linker error when TI_WITH_METAL=OFF

- taichi/aot/module_loader.h
- taichi/backends/metal/device.cpp
- taichi/backends/metal/device.h
- taichi/backends/metal/runtime_utils.h
> [metal] Support device memory allocation/deallocation

- python/taichi/lang/kernel_impl.py
- tests/python/test_argument.py
Add error message when the number of elements in kernel arguments exceeds.
> [Error] Add error message when the number of elements in kernel arguments exceed

- taichi/llvm/llvm_program.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/system/virtual_memory.h
- tests/python/test_fields_builder.py
- tests/python/test_indices_assert.py
Related issue = #4016 #4334 
MAP_NORESERVE flag for mmap is meaningless if we memset the field to 0 at initialization because memset will visit all the memory, and it will be killed if there's not enough memory.
> [bug] [llvm] Initialize the field to 0 when finalizing a field

- taichi/transforms/simplify.cpp
- tests/python/test_delay_modify.py
> [ir] Fix a bug in simplify pass

- python/taichi/examples/simulation/euler.py
> [bug] Fixing dangling ti.func decorator in euler.py

- ci/Dockerfile.manylinux2014.cuda
> [ci] Add a Dockerfile for building manylinux2014-compatible Taichi wheels with CUDA backend

- .github/workflows/release.yml
> [ci] Fix: don't skip the add_version step for nightly release

- .github/workflows/release.yml
Here is an working example:
https://github.com/taichi-dev/test_actions/actions/runs/1961964091
Tag created by bot: https://github.com/taichi-dev/test_actions/releases/tag/v0.9.4
PR created by bot: taichi-dev/test_actions#142
> [ci] Fix: fill in the pull request body created by bot

- taichi/analysis/build_cfg.cpp
- tests/python/test_cfg_continue.py
Related issue = fix #4494
In current taichi, there is a problem when a loop deals with `continue` stmts after being offloaded. This PR tries to fix this problem.
> [ir] [opt] Fix a bug about 'continue'  stmt in cfg_build

- taichi/transforms/auto_diff.cpp
Reduce the number of ad stack using knowledge of derivative formulas. 
Also, fixed the adjoint of mutable local variables not accumulating inside a loop. (fixes #4412)
Benchmark on the use case of #4226.
- Stack Reduction
Reduce unused stacks from 65% to 13%.
- Compile Time Reduction
Reduce ~50% compile time of `auto_diff` pass, ~20% total compile time.
```
########################################################
---------------------- Before -----------------------
########################################################
1.039  s compile                       [14 x  74.194 ms]
...
163.624 ms 88.10%  full_simplify         [44 x   3.719 ms]
...
4.924 ms  2.65%  auto_diff             [1 x   4.924 ms]
########################################################
---------------------- After …
```
> [autodiff] Reduce the number of ad stack using knowledge of derivative formulas

- external/include/catch.hpp
Related issue = #4515 (4th item)
The current version of `catch.hpp` fails to compile on some modern systems due to `MINSIGSTKSZ` not being a constant expression. This issue is already fixed upstream catchorg/Catch2#2178, so this PR just bumps the version of the library from `2.13.3` to `2.13.8`. You can verify, that the `catch.hpp` in this PR is identical to the official release: https://github.com/catchorg/Catch2/releases/download/v2.13.8/catch.hpp
> [misc] [build] Bump catch external library 2.13.3 -> 2.13.8

- taichi/ir/frontend_ir.h
- taichi/transforms/ir_printer.cpp
Result of `irpass::print` will be used as AST-Key (maybe temporary), which needs more information/details to implement [offline-cache](https://github.com/taichi-dev/taichi/issues/4401#issuecomment-1063559899).
> [misc] Make result of irpass::print hold more information

- python/taichi/lang/matrix.py
After this PR, the only way to use `Matrix.__init__()` is by passing initial values.
Hint for reviewers: the git diff looks a bit messy, but the most modifications (L38-L132) in `Matrix.__init__()` simply cancels the indentation after removing the check of `n`.
> [Lang] [refactor] Remove legacy ways to construct matrices

- CMakeLists.txt
(Seems to have worked on my end)
> [build] Option to use LLD

- tests/python/test_element_wise.py
On my workstation this test failed on vulkan backend due to precision
issue. Let's relax it a bit for now.
> [vulkan] Relax a few test precisions for vulkan

- python/taichi/aot/module.py
- taichi/aot/module_data.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- tests/python/test_aot.py
Adding binding id of root/gtmp/rets/args to the serialized json file. 
Note this PR doesn't handle multiple root buffers in aot yet. 
Also added a test case with both scalar and ndarray args, which fixes #3961.
> [aot] Add binding_id of root/gtmp/rets/args bufs to CompiledOffloadedTask

- tests/python/conftest.py
Related issue = 
Close #3128
Supersede #3983 
```
[gw2] [  0%] PASSED tests/python/test_ad_basics.py::test_size1[arch=cpu] 
tests/python/test_ad_basics.py::test_poly[arch=cpu-<lambda>7] 
[gw0] [  0%] PASSED tests/python/test_abs.py::test_abs[arch=cpu] 
tests/python/test_ad_basics.py::test_poly[arch=cpu-<lambda>5] 
[gw1] [  0%] PASSED tests/python/test_ad_atomic.py::test_ad_reduce[arch=cpu] 
tests/python/test_ad_basics.py::test_poly[arch=cpu-<lambda>6] 
[gw7] [  0%] PASSED tests/python/test_ad_basics.py::test_poly[arch=cpu-<lambda>4]
...
```
If there are no other parameters, will show as `<test_name>[arch=<arch>]`, otherwise the arch info will be combined with other parameters wrapped in the same `[]`.
Let me know if this meets the requirement.
> [test] Show arch info in the verbose test report

- taichi/backends/vulkan/vulkan_api.cpp
This means all of our recycled command buffer is stored into the wrong recycling pool and therefore causing the allocation of new command buffers every time.
TLDR: tiny mistakes can be quite lethal (and hard to find)
> [vulkan] Fix a memory leak caused by a typo

- tests/run_tests.py
Cpp-tests is called by `subprocess.check_call()`, which causes env-variables missing, so calling `std::getenv()` in cpp-test will fail ( See https://github.com/taichi-dev/taichi/runs/5534004071?check_suite_focus=true
The pr fix the bug.
> [bug] Fix bug that calling std::getenv when cpp-tests running will fail

- .github/workflows/scripts/unix_build.sh
- tests/python/conftest.py
- tests/python/test_div.py
- tests/python/test_eig.py
- tests/python/test_linalg.py
- tests/python/test_mod.py
- tests/python/test_struct.py
- tests/python/test_svd.py
- tests/python/test_tensor_dimensionality.py
- tests/python/test_test.py
- tests/python/test_unary_ops.py
- tests/test_utils.py
Related: #3128, #4528
Change the test orchestration by replacing the for-loop in `@test_utils.test()` by `@pytest.mark.parametrize`. 
- By default, each arch matched for a specific test function will be splitted into two test cases(test features). All of the test cases will be collected by pytest and run in parallel.
- As a result, the test cases number is almost doubled, from ~1300 to ~2500. 
- All test funcitons decorated by `@test_utils.test()` MUST be placed in the top level rather than nested in child scope, and the function name MUST NOT start with `_`. 
- We are able to apply other parametrization matrix on the `@test_utils.test()` decorated test functions.
Put `@test_utils.test()` right above the test function, under any other `pytest.mark` decorators:
```python …
```
> [test] Parametrize the test cases with pytest.mark

- .github/workflows/release.yml
- .github/workflows/scripts/unix_build.sh
Related issue = close #4395
The docker image produced by #4491 was uploaded as `registry.taichigraphics.com/taichidev-manylinux2014-cuda:v0.0.0`. Then this PR adds a job in release workflow to build and test the new wheel with CPU and CUDA backends in that image.
The new wheel is named as `taichi-0.9.2-cp38-cp38-manylinux2014_x86_64.whl`, while the original one (with OpenGL/Vulkan support as well) is renamed as `taichi-0.9.2-cp38-cp38-manylinux_2_27_x86_64.whl` (the original name with `manylinux1` is wrong). `pip install` will choose the wheel closest to the user platform.
> [CI] Generate manylinux2014-compatible wheels with CUDA backend in release workflow

- python/taichi/_main.py
This PR fixes some bugs reported by @yuanming-hu when running the `taichi gallery` command. The main changes are:
1. Crop the slide bar on top of the image.
2. Fix the problem that some mouse positions give wrong tiles.
3. Deactivate keyboard input.
4. Fix the problem caused by `readlines()` when printing the code to console, use `shutil.copyfileobj` instead.
5. Add mouse position check to fix the problem that dragging the slide bar also triggers events.
> [CLI] Fix a few bugs in taichi gallery command

- taichi/aot/module_loader.cpp
- taichi/aot/module_loader.h
- taichi/backends/metal/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/4437
We should return a raw pointer, not `unique_ptr`. The module object owns the kernel.
> [aot] Fix get_kernel API semantics

- taichi/gui/cocoa.cpp
Had to use this sleeping-hack to make closing the window work. Not sure if there's an event handler we can register to control this behavior much more accurately.
> [gui] Hack to make GUI.close() work on macOS

- .github/workflows/release.yml
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
> [misc] Add TI_CI env to CI/CD

- .github/workflows/release.yml
- .github/workflows/testing.yml
- pyproject.toml
- python/taichi/_kernels.py
- python/taichi/examples/rendering/cornell_box.py
- python/taichi/examples/simulation/mpm99.py
- tests/python/test_ad_if.py
- tests/python/test_aot.py
- tests/python/test_ast_refactor.py
- tests/python/test_element_wise.py
- tests/python/test_f16.py
- tests/python/test_gui.py
- tests/python/test_image_io.py
- tests/python/test_mpm_particle_list.py
- tests/python/test_native_functions.py
- tests/python/test_parallel_range_for.py
- tests/python/test_simple_matrix_slice.py
There are lots of warnings after test run:
```
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
tests/python/examples/rendering/test_cornell_box.py::test_cornell_box[none]
/home/dev/miniconda/envs/py39/lib/python3.9/site-packages/taichi/examples/rendering/cornell_box.py:303: DeprecationWarning: Calling builtin function "max" in Taichi scope is deprecated. Please use "ti.max" instead.
return max(0.0, n.dot(l)) …
```
> [test] Eliminate the warnings in test suite

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- tests/python/test_function.py
Related issue = #602 
For reviewers:
This PR inserts return instruction when visiting return statement in the codegen.
LLVM requires a basic block to have one and only one terminator instruction (return, branch, etc.) at the end of the block. So, this PR does the following things.
1. Adds a flag `returned` in the codegen, indicating whether the current basic block has inserted a return instruction. 
2. If the current basic block has inserted a return instruction, the codegen stops processing all statements after it in a basic block, and does not add the branch instruction supposed to be added when constructing if/for/while statements. 
3. If the basic block does not have a terminator instruction, insert a return instruction.
4. Restores the `returned` flag to `false` when the current …
> [llvm] [lang] Add support for multiple return statements in real function

- taichi/backends/metal/aot_module_loader_impl.cpp
> [aot] [refactor] Add make_new_field for Metal

- taichi/ir/ir.h
Fixing the build breakage for libtaichi_export_core.so.
> [build] Guard llvm usage inside TI_WITH_LLVM

- tests/python/test_return.py
`test_binary_func_ret` doesn't conform to the new rules for writing tests (#4546) and seems causing troubles in nightly tests (https://github.com/taichi-dev/taichi/runs/5620468486?check_suite_focus=true). This PR fixes it.
> [test] Fix ill-formed test_binary_func_ret

- python/taichi/_version_check.py
To prevent creation of file only happens after success of server response.
Some Taichi program's execution time won't last to listen to server response.
> [misc] Write version info right after creation of uuid

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/runtime.cpp
- taichi/codegen/spirv/kernel_utils.cpp
- taichi/codegen/spirv/kernel_utils.h
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/program/context.h
- tests/cpp/aot/aot_save_load_test.cpp
Vulkan aot return didn't work since it was trying to serialize
`Datatype` which was a raw pointer. This PR fixes the issue by changing
it to a PrimitiveTypeID which is a `int`. Note it's possible that we
limit Kernel args and rets to be primitive types only but leaving that
to a followup PR to avoid making this PR too complicated.
> [aot] Support return in vulkan aot

- python/taichi/_kernels.py
- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
- tests/python/test_ndarray.py
> [lang] Fix vector matrix ndarray to numpy layout

- docs/lang/articles/basic/operator.md
- docs/lang/articles/basic/type.md
- Moved using compound types to create fields to fields. 
- Added one claim: Type casting on vectors and matrices in Taichi is element-wise; **type casting on structs is _not_. **
> [Doc] Refactored Type system.

- taichi/common/core.cpp
XDG is not support on Android and there is no home directory so for now,
we just 'disable' it by returning an empty string.
This is not called/used on Android.
> [android] Disable XDG on non-supported platform

- taichi/backends/vulkan/vulkan_device_creator.cpp
Now we will prefer a discrete GPU, and prefer higher version of Vulkan support when multiple GPUs are detected.
> [vulkan] Choose better devices

- docs/lang/articles/contribution/dev_install.md
Related issue = #4637
The 'examples' directory is changed but the docs missed to update.
> [doc] Examples directory update

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
Add `shfl_up_i32` and `shfl_up_f32` intrinsics for cuda backend. Related issue = #4631 .
> [SIMT] Add shfl_up_i32/f32 warp intrinsics

- taichi/ui/backends/vulkan/renderables/set_image.cpp
- taichi/ui/backends/vulkan/renderables/set_image.h
With AOT modules depending on the device where the kernel is running, we
might support RGBA Float Texture and it's better to pass the data from
the Taichi Compute Kernel directly to the image (normalized between 0
and 1) instead of adding extra step to convert to 0;255
> [gui] Allow to configure the texture data type

- docs/lang/articles/basic/field.md
Please also pay attention to the code snippet. I updated the code (a little bit) and the annotations, and I'm not 100% sure of my explanations of the code. 
> [Doc] Refactored field.md

- docs/lang/articles/reference.md
Related issue = #4602
Subsection "set displays" is removed by the way because it is not supported in Taichi.
> [Doc] Taichi spec: parenthesized forms; expression lists

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cpu/codegen_cpu.h
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen.h
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/kernel.h
- tests/python/test_offline_cache.py
> [refactor] [cuda] Refactor offline-cache and support it on arch=cuda

- tests/python/test_offline_cache.py
https://github.com/taichi-dev/taichi/runs/5750005177?check_suite_focus=true shows that `test_closing_offline_cache` fails on Python 3.10.
> [misc] Temporarily disable a flaky test

- taichi/runtime/llvm/runtime.cpp
Related issue = #4659
The precision promotion in fp32 min/max reduction is caused by the `fmax` func which actually has fp64 type. [Reference](https://en.cppreference.com/w/c/numeric/math/fmax)
Fix by changing fmin / fmax to fminf / fmaxf.
> [CUDA] Fix the fp32 to fp64 promotion due to incorrect fmax/fmin call

- docs/lang/articles/reference.md
Related issue = #4602
The three subsections, `Displays for lists and dictionaries`, `List displays` and `Dictionary displays` in the original plan are merged into one `List and dictionary displays` subsection because we don't have to repeat many parts same as Python.
> [Doc] Taichi spec: list and dictionary displays

- docs/lang/articles/advanced/meta.md
- docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
- docs/lang/articles/get-started/index.md
- docs/lang/articles/gui/gui_system.md
1. fix broken link in https://docs.taichi.graphics/lang/articles/meta#when-to-use-tistatic-with-for-loops
2. fix typo `ti.i31 -> ti.i32`
3. fix duplicated warning (appear twice) in getting start
4. fix broken images in https://docs.taichi.graphics/lang/articles/gui_system#draw-on-a-window
Related PR: https://github.com/taichi-dev/public_files/pull/9
> [Doc] Fix 4 typos in doc

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
Related issue = #4631 
Add shfl_sync_i32/f32 intrinsics for cuda backend.
Broadcast a single value across warps using shfl_sync_i32/f32 intrinsics.
> [SIMT] Add shfl_sync_i32/f32 warp intrinsics

- taichi/codegen/spirv/spirv_codegen.cpp
This was the root cause of a weird issue on qualcomm chips on android.
> [spirv] Ext arr name should include arg id

- benchmarks/microbenchmarks/_metric.py
- docs/lang/articles/misc/profiler.md
- python/taichi/examples/algorithm/mgpcg.py
- python/taichi/examples/algorithm/mgpcg_advanced.py
- tests/python/bls_test_template.py
This is a follow-up PR of #4165 and #4194.
> [doc] Fix deprecated profiler APIs in docs, tests, and examples

- docs/lang/articles/reference.md
Related issue = #4602
Subsection "Identity comparisons" is removed by the way because the usage is deprecated in Taichi.
> [Doc] Taichi spec: boolean operations

- CMakeLists.txt
- tests/python/test_external_func.py
These tests failed on my M1 mac when building from source. It passed CI
machine mainly because the tests were skipped due to
https://github.com/taichi-dev/taichi/blob/master/tests/python/test_external_func.py#L13.
We actually limit external_func to `x64` backend not `cpu`.
(Although I've tried on arm64 and it worked, I'll leave enabling it on
arm64 to a separate PR)
> [mac] Fix external_func test failures on arm backend

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
Related issue = #4632 
Add shfl_xor_i32 warp intrinsics for cuda backend.
> [SIMT] Add shfl_xor_i32 warp intrinsics

- python/taichi/lang/simt/warp.py
Related issue = #4631 
For warp size of 32, correct lane offset is 0 for `shfl_up*` and 31 for `shfl_down*`. 
ref https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#data-movement-and-conversion-instructions-shfl-sync
> [SIMT] [cuda] Use correct source lane offset for warp intrinsics

- python/taichi/lang/impl.py
- tests/python/test_assert.py
> [Error] Raise an error when non-static condition is passed into ti.static_assert

- .github/workflows/release.yml
Since we have switched to our own self-hosted PyPI cloud, Python 3.6 and 3.10 can be enabled to cover more releases in nightly.
> [ci] Add python 3.6 and 3.10 to nightly release

- python/taichi/lang/matrix.py
- python/taichi/lang/simt/warp.py
- python/taichi/math/vectypes.py
- tests/python/test_f16.py
- tests/python/test_math_vectors.py
- tests/python/test_matrix.py
Related issue = close #4741 
[test_f16.py::test_fractal_f16](https://github.com/taichi-dev/taichi/blob/master/tests/python/test_f16.py#L202) fails when dtype of  `z` is f16 as described in #4757 , so I temporarily removed the dtype parameter. When this is fixed, the dtype parameter should be added back.
> [bug] [lang] Let matrix initialize to the target type

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
Related issue = #4631 
Add any_sync intrinsics for cuda backend.
> [SIMT] Add any_sync warp intrinsics

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
Related issue = #4631
Add all_sync intrinsics for cuda backend.
> [SIMT] Add all_sync warp intrinsics

- taichi/transforms/auto_diff.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/4512/
> [autodiff] Fix nullptr during adjoint codegen

- taichi/llvm/llvm_offline_cache.cpp
Remove:
* `simd_width`
* `max_vector_width`
* `serial_schedule`
* `use_llvm`
* `dynamic_index`
* `extra_flags`
> [misc] Remove some unnecessary attributes from offline-cache key of compile-config

- python/taichi/ad.py
- tests/python/test_customized_grad.py
Related issue = #4747
The implementation should be expressive enough, which is to replace the auto grad function with an empty function.
This is my first PR to an open source project! While it's certainly exciting to me, please excuse me if any requirements are missing. 
Another issue when I'm writing tests is that while the contribution guideline requires using `@ti.test` to decorate the test functions, all tests for the Autodiff module is prepended with the `@test_utils.test` decorator. I decided to follow the convention and if that is not recommended, please let me know too.
> [Autodiff] Implement ti.ad.no_grad to skip autograd

- taichi/codegen/spirv/spirv_ir_builder.cpp
- tests/python/test_f16.py
> [spirv] Add 16 bit float immediate number

- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
Related issue = closes #4613
Related issue = #2196
It's interesting that in C++ `i8 + i8 = i32`.
**Type promotion table:**
Format: a + b = old_type -> new_type. Only some are changed.
```
f32 + f32 = f32
f32 + f64 = f64
f32 + i8 = f32
f32 + i16 = f32
f32 + i32 = f32
f32 + i64 = f32
f32 + u8 = f32
f32 + u16 = f32
f32 + u32 = f32
f32 + u64 = f32
f64 + f32 = f64
f64 + f64 = f64
f64 + i8 = f64
f64 + i16 = f64
f64 + i32 = f64
f64 + i64 = f64
f64 + u8 = f64
f64 + u16 = f64
f64 + u32 = f64
f64 + u64 = f64
i8 + f32 = f32
i8 + f64 = f64
i8 + i8 = i32 -> i8
i8 + i16 = i32 -> i16
i8 + i32 = i32
i8 + i64 = i64
i8 + u8 = i32 -> u8
i8 + u16 = i32 -> u16
i8 + u32 = u32
i8 + u64 = u64
i16 + f32 = f32
i16 + f64 = f64
i16 + i8 = i32 -> i16
i16 + i16 = i32 -> i16
i16 + i32 = i32
i16 + i64 = i64
i16 + u8 = …
```
> [Lang] Fix integral type promotion rules (e.g., u8 + u8 now leads to u8 instead of i32)

- python/taichi/lang/common_ops.py
- tests/python/test_matrix.py
> [Lang] Support in-place operator of ti.Matrix in python scope

- python/taichi/math/mathimpl.py
- tests/python/test_api.py
This PR add [mod](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mod.xhtml) function to the `math` module.
> [Lang] Add mod function to math module

- taichi/codegen/codegen_llvm.cpp
- taichi/ir/expression_printer.h
- taichi/ir/transforms.h
- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
- taichi/transforms/ir_printer.cpp
Temporary:
1. Reusing `ExpressionHumanFriendlyPrinter` to impl `ExpressionOfflineCacheKeyGenerator`
2. `get_hashed_offline_cache_key_of_snode` and `get_hashed_offline_cache_key` are declared/defined in `llvm_offline_cache.*`. I will move them to `offline_cache_util.*`
> [misc] Add SNode to offline-cache key

- python/taichi/lang/mesh.py
- python/taichi/lang/misc.py
> [Doc] [mesh] Update docstring for ti.Mesh

- .github/workflows/issue_open.yml
I used an action maintained by the official team though they said the API may be unstable.
> [workflow] Add issues to the project board when opened

- taichi/llvm/llvm_offline_cache.cpp
> [bug] Fix bug that building with gcc9.4 will fail

- taichi/backends/device.h
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device_creator.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
Fixes #4788
The old casting code has a bit of misunderstanding of Spirv's casting operators:
`UConvert` and `SConvert` are for same signed-ness bit extending or truncation. Bitcasts are for same width casts between different signed-ness.
Also fixes a buffer fill command warning about non-multiple of 4 sizes.
> [spirv] Fix int casts

- tests/python/test_offline_cache.py
> [test] Add simple test for offline-cache-key of compile-config

- python/taichi/lang/matrix.py
- python/taichi/lang/swizzle_generator.py
- python/taichi/math/vectypes.py
- tests/python/test_api.py
- tests/python/test_math_vectors.py
- tests/python/test_swizzle_generator.py
Related issue = https://github.com/taichi-dev/taichi/issues/4810
Added a `SwizzleGenerator`, which generates all the combinatory patterns for a given set of accessors (e.g. `xyzw`). The next step would be to cleanup the `vecN` definitions.
> [Lang] Support swizzles on all Matrix/Vector types

- taichi/transforms/type_check.cpp
Related issue = fix #4833
The previous logic is buggy because `dst_value_type != stmt->val->ret_type` can never happen after inserting the implicit type cast.
> [Bug] [ir] Fix implicit cast warning for global stores

- taichi/ir/frontend_ir.cpp
> [Error] Show warning when serialize=True is set on a struct for

- taichi/ir/frontend_ir.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/aot/aot_save_load_test.cpp
Related issue = fix #4250
This PR ends the series of efforts (#4834, #4840, #4843) for providing a systematic solution to warning users about implicit casts during stores.
> [Bug] [ir] Fix and refactor type check for atomic ops

- python/taichi/lang/matrix.py
- tests/python/test_vector_swizzle.py
Related issue = https://github.com/taichi-dev/taichi/issues/4810
> [lang] Add better error detection for swizzle patterens

- taichi/transforms/lower_ast.cpp
Simple example:
```
@ti.kernel
def load_while(c: ti.i32):
while c < 0:
y[0] = c + 1.0 
````
After lowered to CHI IR, note that the highlighted variable "$0" has never been used:
> [bug] Remove redundant AllocStmt when lowering FrontendWhileStmt

- .github/workflows/testing.yml
Related issue = #4871 
@ailzhang Sorry i missed the previous review of #4871 . Lets use the updated docker image for build. ;)
> [ci] Use the updated docker image for libtaichi_export_core

- taichi/ir/frontend_ir.cpp
- taichi/ir/stmt_op_types.h
- taichi/transforms/type_check.cpp
- tests/cpp/ir/ir_type_promotion_test.cpp
- tests/python/test_type_promotion.py
Related issue = fix #4795
bit-shift ops should not follow the same type promotion rule as numerical, for example:
- ops numerical ops: `u8 + i32 = i32`
- shift_ops:                `u8 << i32 = u8` (follow lhs's dtype)
As truncating rhs(i32) to u8 risks an overflow (very unlikely though), we inserted an AssertStmt to warn user of this potential overflow if initialized with debug=True.
Before:
After this patch (with debug=True):
> [bug] Fixed type promotion rule for bit-shift operations

- setup.py
After adoption of skbuild, it can't select Ninja as the generator on Windows, making it not able to use parallel build.
This PR sets the generator explicitly and skips skbuild's generator tests.
> [build] Use Ninja generator on Windows and skip generator test

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- ci/scripts/ubuntu_build_test.sh
- ci/scripts/ubuntu_build_test_cpu.sh
- ci/windows/win_build_test.ps1
- docs/lang/articles/basic/external.md
- docs/lang/articles/misc/global_settings.md
- python/taichi/lang/field.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
- python/taichi/lang/struct.py
- python/taichi/lang/util.py
- tests/python/test_api.py
- tests/python/test_f16.py
- tests/python/test_get_external_tensor_shape.py
- tests/python/test_paddle_io.py
Related issue = [hackathon](https://github.com/taichi-dev/hackathons/issues/3)
`paddle.fluid.core.Tensor()._ptr()` is only avaliable on develop branch. I encounter 2 problems with develop package in build process.
1. I started with CUDA-configured WSL as my development environment. After installing the develop version package on CPU and CUDA. `import paddle` causes an `Illegal Instruction` error and exits the Python environment.  So I gave up using WSL.
2. Then I developed directly on Windows . Firstly, I used the develop version of paddlepaddle-gpu. Although the actual file is less than 2GB. When I `import paddle` I got error `Windows FATAL Exception: access violation`. A .pyd file is too large for the page to load.  My computer has 16GB of memory, and rebooting still doesn't fix the …
> [Lang] [test] Copy-free interaction between Taichi and PaddlePaddle

- misc/sparse_matrix.py
- python/taichi/linalg/sparse_matrix.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/program/sparse_solver.cpp
- taichi/program/sparse_solver.h
- taichi/python/export_lang.cpp
- tests/python/test_sparse_matrix.py
- tests/python/test_spmv.py
Related issue = #2906
This PR seems messy for the reviewer. 
For short, the eigen sparse matrix is warpped using `EigenSparseMatrix` class which is derived from the abstract class `SparseMatrix`. 
The data type and storage format is configured using `SparseMatrixBuilder `interface. The `EigenSparseMatrix` is created and built from triplets in `SparseMatrixBuilder`.
> [Lang] Support sparse matrix datatype and storage format configuration

- docs/lang/articles/basic/type.md
> [doc] Updated documentations for implicit type casting rules

- cmake/TaichiCXXFlags.cmake
Due to limited CI coverage on different types of compiler, we only turned on -Werror for Clang-compiler for now.
> [build] Limit -Werror to Clang-compiler only

- .github/workflows/release.yml
This PR fixes
1. Windows release does not use the `win_test.ps1` script, hence after the removal of requirement_test.txt by #4624. The nightly release has been stuck by missing pytest module. 
2. We add python 3.7 and 3.9 to nightly. As demand seems high.
> [ci] Fix Nightly

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/program/context.h
- taichi/runtime/opengl/opengl_api.cpp
- taichi/runtime/opengl/opengl_api.h
- taichi/runtime/vulkan/runtime.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/4949
> [refactor] Some renamings

- taichi/backends/vulkan/vulkan_utils.h
This PR reopens #4958 as the original branch was removed.
According to the [manual](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkApplicationInfo.html), the `apiVersion` to create a Vulkan instance should be the highest version designed to use.
Let's see if this change could pass all tests in CI.
> [vulkan] Set kApiVersion to VK_API_VERSION_1_3

- python/taichi/lang/simt/subgroup.py
- python/taichi/lang/simt/warp.py
Related issue = #4631, fix #4954
Internal func calls are expressions, and they will not be inserted into Taichi AST if they are not assigned to others. The correct and simpler way to insert these intrinsics is to use the `impl.call_internal()` wrapper which includes forced assignment.
BTW in `subgroup.py`, those `dtype`s are removed because they only apply to constants, which are not feasible here.
> [bug] [simt] Fix the problem that some intrinsics are never called

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
Thanks to @PGZXB 's https://github.com/taichi-dev/taichi/blob/master/taichi/llvm/llvm_offline_cache.h, we can now create a callable `void(RuntimeContext&)` directly from an `llvm::Module`, without going through codegen. This would be useful for LLVM AOT. In this PR, I've extracted this conversion part into a separate interface `ModuleToFunctionConverter`.
```cpp
virtual FunctionType convert(const std::string &kernel_name,
const std::vector<ArgInfo> &args,
std::unique_ptr<llvm::Module> mod,
std::vector<OffloadedTask> &&tasks) const;
```
> [llvm] Create ModuleToFunctionConverter

- taichi/analysis/gen_offline_cache_key.cpp
Related issue = #4401, #4889
Reported by:
* running test_function.py with `offline_cache=True`
> [misc] Add ASTSerializer::visit(ReferenceExpression *)

- taichi/analysis/offline_cache_util.cpp
Fix  bug (reported by:
* running test_custom_float_exponents.py with `offline_cache=True`
> [bug] Fix infinite recursion of get_offline_cache_key_of_snode_impl()

- python/taichi/lang/simt/__init__.py
- python/taichi/lang/simt/block.py
- python/taichi/lang/simt/grid.py
- tests/python/test_simt.py
Add `ti.simt.block.sync()` and `ti.simt.grid.memfence()` instrinsics, which equivalent to `__syncthreads()` and `__threadfence()` in cuda.
Related issue = #4631
> [cuda] Add block and grid level intrinsic for cuda backend

- CMakeLists.txt
- build.ps1
- docs/lang/articles/contribution/dev_install.md
- Supported Visual Studio 2022
- Supported Visual Studio version selection if multiple versions have been installed
- Prebuilt LLVM 10 available at [taichi_assets](https://github.com/taichi-dev/taichi_assets/releases/tag/llvm10_msvc2022)
- Improved documentation
> [Build] Support Visual Studio 2022

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/common/serialization.h
- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
- tests/cpp/llvm/llvm_offline_cache_test.cpp
- tests/python/test_offline_cache.py
@PGZXB FYI, I've switched the LLVM cache writer from the customized solution to Taichi's small serialization library. To see how it works, here are some examples: https://github.com/taichi-dev/taichi/blob/master/tests/cpp/common/serialization_test.cpp
> [llvm] Use serializer for LLVM cache

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- benchmarks/microbenchmarks/_items.py
- build.ps1
- python/taichi/_lib/utils.py
- python/taichi/_logging.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/misc.py
- python/taichi/lang/snode.py
- python/taichi/profiler/kernel_metrics.py
- python/taichi/profiler/kernel_profiler.py
- python/taichi/types/annotations.py
- taichi/analysis/verify.cpp
- taichi/backends/cuda/cupti_toolkit.cpp
- taichi/gui/x11.cpp
- taichi/ir/snode.h
- taichi/system/traceback.cpp
- taichi/transforms/reverse_segments.cpp
- tests/python/test_fields_builder.py
- tests/python/test_simple_matrix_slice.py
> [Doc] Updated URL

- misc/benchmark_bit_struct_stores.py
- misc/visualize_quant_types.py
- python/taichi/__init__.py
- python/taichi/lang/matrix.py
- python/taichi/lang/misc.py
- python/taichi/lang/struct.py
- python/taichi/types/__init__.py
- python/taichi/types/quantized_types.py
- tests/python/test_bit_array.py
- tests/python/test_bit_array_vectorization.py
- tests/python/test_bit_struct.py
- tests/python/test_cast.py
- tests/python/test_custom_float.py
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_shared_exp.py
- tests/python/test_custom_float_time_integration.py
- tests/python/test_custom_int.py
- tests/python/test_custom_type_atomics.py
- tests/python/test_matrix_different_type.py
- tests/python/test_snode_layout_inspection.py
- tests/python/test_struct_for.py
Related issue = https://github.com/taichi-dev/taichi/issues/4857#issuecomment-1122134432
This PR mainly corresponds to Subtask A.1. After this PR, for type definitions of quantized types, we provide public APIs `ti.types.quant.int/fixed/float` and private APIs `ti.types.quant._custom_int/_custom_float`. There are no more `Quant` or `TypeFactory` classes in Python - these APIs are put directly under the `quantized_types` module, which is now imported as `quant`. All usages in the codebase are replaced.
> [Lang] [type] Refactor quantized_types module and make quant APIs public

- python/taichi/lang/_ndarray.py
- taichi/backends/opengl/opengl_program.cpp
- taichi/backends/opengl/opengl_program.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/python/export_lang.cpp
- taichi/runtime/opengl/opengl_api.cpp
- taichi/runtime/opengl/opengl_kernel_launcher.h
- tests/python/test_torch_io.py
* #5004
* #5002
* #4999
* #4998
* #4997
* __->__ #4996
The end goal of this refactor is let Ndarray be a simple wrapper around
(DeviceAllocation, dtype, shape) without having to worry about memory
allocation/deallocation. But its current implementation heavily couples
with Program*, so an intermediate state would be:
- If created from Program, Ndarray handles deviceallocation in
ctor/dtor.
- We'll add another ctor simply constructing Ndarray from
(DeviceAllocation, dtype, shape) and update the codebase to it.
> [refactor] Program owns allocated ndarrays.

- python/taichi/lang/_ndarray.py
- python/taichi/lang/impl.py
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- tests/python/test_ndarray.py
* #5004
* #5002
* __->__ #4999
* #4998
* #4997
* #4996
Previously Program manages lifetime of all allocated ndarrays. So when
you call `del ndarray` in python, its memory was not freed. This PR
changes the behavior that `ndarray` memory gets deallocated when python
GC triggers, or its containing `Program` gets destructed, whichever
happens first. There're some quirks around how we handle the async
python GC and manual `ti.reset()`. Thanks to @k-ye, we now added a
`generation` number to track the containing program instance of ndarrays
so that memory deallocation happens correctly.
> [refactor] Free ndarray's memory when python GC triggers

- README.md
- docs/lang/articles/contribution/contributor_guide.md
> [Doc] Branding updates. Also tests netlify.

- CMakeLists.txt
- cmake/TaichiCXXFlags.cmake
- cmake/TaichiCore.cmake
- Allowed Python not to be built in case of non-Android platforms;
- Skiped byte code generation when `TI_WITH_LLVM=OFF`;
- Fixed include directory path relativity when included as a subdirectory;
- Temporarily disabled warning-as-error on Android.
> [AOT] Supported inclusion of taichi as subdirectory for AOT modules

- taichi/ir/frontend_ir.cpp
- tests/python/test_atomic.py
Related issue = #4986
1. Issue
```
x: ti.uint16 = 1000
y: ti.uint8 = 1
ti.atomic_sub(x, y)
```
The above code gives `x = 1255` instead of 999. 
2. Diagnose
Taichi transforms `atomic_sub(x, y)` into `neg_y = negate(y); atomic_add(x, neg_y)` during `irpass::lower_ast()`, therefore the following type promotion will bit_cast "neg_y" (1's complement of y) into another unsigned integer, which breaks the interpretation of 1's complement.
3. Solution
We should perform the cast before negating rhs's value.
4. Other comments
Frontend IR does not seem to be a good place for transformations. Shall we write a CHI IR pass for `atomic_sub -> atomic_add` to replace the one inside irpass::lower_ast()?
> [bug] Fixed numerical error for Atomic-Sub between unsigned values with different number of bits

- taichi/aot/graph_data.h
- taichi/aot/module_loader.h
- taichi/backends/vulkan/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/program/graph.cpp
- taichi/program/graph.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.h
- taichi/program/program_impl.h
- tests/cpp/aot/aot_save_load_test.cpp
- tests/cpp/program/graph_test.cpp
* #5017
* #5016
* __->__ #5015
* #5014
This PR servces as the base PR with a minimal example of building and
running a Graph. Runtime values for graph arguments can be either
scalars or ndarrays.
For detailed proposal please see #4786.
Things handled in this PR:
- Maximize common code/runtime shared by the two workflows below:
1. build -> compile -> run
2. build -> compile -> serialize -> deserilize -> run
- Graph arguments are annotated with dtype and element shape for ndarray (temporary
until we have vec3 types in C++)
Things that we've discussed but not included in this PR:
- C API: I'll leave that for a unified C API PR in the future.
- bind IValues to graph: easy, will add later.
> [aot] Build and run graph without serialization

- .github/workflows/scripts/unix_test.sh
Nightly has been down for a week. https://github.com/taichi-dev/taichi/runs/6533328301?check_suite_focus=true#step:6:78 due to 
https://github.com/taichi-dev/taichi/blob/963b1c3b001514cf66acefd66d9355be23605e38/.github/workflows/scripts/unix_test.sh#L39
```
.github/workflows/scripts/unix_test.sh: line 39: lscpu: command not found
```
on m1 machines. 
This PR incorporates the fix.
> [ci] Fix nightly macos

- python/taichi/lang/_ndarray.py
- python/taichi/lang/impl.py
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- tests/python/test_ndarray.py
I realized that our implementation of ndarray lifetime is not perfect.
For example, when I run
```
ti.init(ti.vulkan)
def test():
z = ti.ndarray(float, (8192))
test()
```
This works fine but if I do
```
ti.init(ti.vulkan)
z = ti.ndarray(float, (8192))
```
I actually got an error `'NoneType' object is not callable`.
The root cause is python doesn't guarantee destruction order, so it's
possible that
```
def __del__(self):
if impl.get_runtime().prog is not None:
print(impl.get_runtime().prog) # Error! PyTaichi object got destructed
right after the check above!
```
I'm thinking that we might be able to workaround this using weak
reference but want to revert this PR first to make sure master is
healthy.
Related issue = #4999
> [bug] Revert freeing ndarray memory when python GC triggers

- docs/lang/articles/contribution/dev_install.md
It is a bit strange to see `Linux/Unix/Mac`. Since Linux and Mac are both Unix, let's just remove Unix.
> [doc] Update OS names in dev install

- .github/workflows/scripts/win_build_test_cpu.ps1
- .github/workflows/testing.yml
- Disable test in the windows cpu job to reduce total execution time.
> [ci] Disable win cpu docker job test

- python/taichi/types/quantized_types.py
- tests/python/test_custom_float.py
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_shared_exp.py
- tests/python/test_custom_float_time_integration.py
- tests/python/test_custom_type_atomics.py
- tests/python/test_matrix_different_type.py
- tests/python/test_snode_layout_inspection.py
Related issue = https://github.com/taichi-dev/taichi/issues/4857#issuecomment-1130043445
This PR does the following:
- For `ti.types.quant.int`, set the default value of `signed` to `True`.
- Add a `scale` parameter to `ti.types.quant.fixed`.
- Replace all occurrences of `ti.types.quant._custom_float` with `ti.types.quant.float/fixed`.
- Remove redundant logic.
After this PR, users only need to know three public APIs for quant type definition - `ti.types.quant.int/fixed/float`.
> [Lang] [type] Refactor quant type definition APIs

- python/taichi/_kernels.py
- python/taichi/math/mathimpl.py
- tests/python/test_api.py
Purpose: In the [current implementation](https://github.com/taichi-dev/taichi/blob/master/python/taichi/math/mathimpl.py#L13) of vector and matrix types, the type `float` is indeed determined when the module is imported, hence always `ti.f32`. This PR fixes this problem.
Also added two new functions `determinant` and `inverse` to the math module.
> [Lang] Fix potential precision bug when using math vector and matrix types

- .github/workflows/scripts/unix_test.sh
- ci/windows/win_build_test.ps1
- tests/run_tests.py
> [ci] Run cpp tests via run_tests.py

- taichi/backends/opengl/opengl_program.cpp
As discussed ndarrays can be written through calling write kernels, but
it shouldn't support directly map on host and write to it.
> [opengl] Set host_write to false for opengl ndarray

- docs/lang/articles/basic/type.md
- taichi/ir/frontend_ir.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_type_promotion.py
Related issue = fix #3092
Type promotion for `ti.atan2` is slightly different from that for `std::atan2`: https://en.cppreference.com/w/cpp/numeric/math/atan2. While `std::atan2` uses "double" as the default return type, we decided to use "float" as the default promoted type for `ti.atan2`, since some of the backends (Vulkan, etc) doesn't support float64.
> [bug] Added type promotion support for atan2

- python/taichi/aot/utils.py
- python/taichi/examples/graph/mpm88_graph.py
- python/taichi/types/ndarray_type.py
- taichi/aot/graph_data.h
- taichi/python/export_lang.cpp
- tests/cpp/aot/aot_save_load_test.cpp
- tests/cpp/program/graph_test.cpp
- tests/python/test_aot.py
- tests/python/test_graph.py
This PR does three things:
- Switch cgraph `Arg` to take in `ti.f32/i32` instead of string
`f32/i32` as inputs
- Fix a bug that when we produce injected ndarray args for compilation
we only produced f32 ndarrays, which won't work for ndarray of other
primitive dtypes.
- No need to specify `element_shape` if it's scalar arg or scalar
ndarray arg.
Related issue = #4786 
Thanks to @YuCrazing for reporting the bug!
> [bug] Ndarray type should include primitive dtype as well

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/ops.py
- taichi/ir/expression_ops.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/stmt_op_types.cpp
- taichi/ir/stmt_op_types.h
- taichi/python/export_lang.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/test_type_check.py
Related issue = #3572, #3635
This PR introduces a new ternary operator `ifte` at the frontend IR level that supports short-circuit semantics:
```
select(c, x, y) ==> 
eval c, eval x, eval y, 
if c 
then return x 
else return y
ifte(c, x, y) ==>
eval c,
if c
then eval x, return x
else eval y, return y
```
On the python side, `IfExp` now uses this operator instead of directly translating into if statements; this guarantees the return type is consistent.
@strongoier: For now `ifte(c, x, y)` does *not* force `x` and `y` to be the same type. Is this desired semantics?
> [Lang] [ir] Add short-circuit if-then-else operator

- python/taichi/lang/impl.py
- python/taichi/lang/struct.py
- tests/python/test_api.py
- tests/python/test_custom_struct.py
Related issue = #4965
```python
@ti.struct_class
class Sphere:
center: vec3
radius: ti.f32
@ti.func
def area(self):
return 4 * 3.14 * self.radius * self.radius
```
Into a taichi struct (with methods!)
As discussed in the issue, this is a (draft) Pull request to implement `struct_classes`.  
`struct_class` is a decorator that can be attached to a python class definition that allows two things:
1.  Class field annotations are turned into struct fields (inspired by python Dataclasses)
2.  Class methods are attached to the struct and used like class methods.
IMO this allows a better syntax for structs and of course allows the struct methods.  Additionally it might ease much of what people would do with `ti.data_oriented` for complex arrays of structures in classes.  
**NOTE THIS IS A DRAFT …
> [Lang] Struct Classes implementation

- taichi/ir/expr.cpp
- taichi/ir/expr.h
Related issue = fix #4119
There is already `expr_logic_not()` for the `logic_not` operation. Overloading `!` is redundant, and causes trouble in #4119. This PR removes it.
> [bug] Stop overloading operator ! for Expr

- python/taichi/examples/graph/mpm88_graph.py
- python/taichi/graph/_graph.py
- tests/python/test_aot.py
- tests/python/test_graph.py
Related issue = #4786
Splitting `Graph` to two classes as discussed offline
> [refactor] Split GraphBuilder out of Graph class

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/codegen_cuda.h
- taichi/codegen/codegen_llvm.h
`compile_module_to_executable()` was used in LLVM - CUDA backend to perform:
1. Transform llvm::Module into CudaJITModule (CudaModule in essense), to make the compiled functions executable.
2. Prepare the execution entrance: a lambda function that does some additional configurations to the RuntimeContext, then execute the offloaded_tasks iteratively.
In this Patch, we refactored `compile_module_to_executable()` to make it decoupled with `Kernel`. In this way, we dont have to recover the entire `Kernel` at AOT runtime. 
`compile_module_to_executable()` was further replaced by `CUDAModuleToFunctionConverter::convert()` to stay consistent with LLVM - CPU backend.
> [llvm] [aot] CUDA-AOT PR #0: Refactored compile_module_to_executable() to CUDAModuleToFunctionConverter

- python/taichi/lang/_ndarray.py
- python/taichi/lang/enums.py
- python/taichi/lang/matrix.py
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/inc/constants.h
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
* #5073
* __->__ #5066
* #5065
Note we still flatten element_shape in the C++ Ndarray, which is blocked by the accessors and will be fixed
in the following PRs.
> [refactor] Pass element_shape and layout to C++ Ndarray

- python/taichi/lang/_ndarray.py
- python/taichi/lang/kernel_impl.py
- python/taichi/types/ndarray_type.py
> [refactor] Resolve comments from #5065

- python/taichi/math/mathimpl.py
This PR is intended for adding support for glsl style matrix constructions.
Feature added:
1. Use n vectors to initialize a matrix.
```python
x = vec3(1, 0, 0)
y = vec3(1, 1, 0)
z = vec3(1, 1, 1)
m = mat3(x, y, z)
```
2. Use a 1d list, or simple n*n scalars to initialize a matrix:
```python
x = mat2(1, 0, 0, 1)
y = mat2([1, 0, 0, 0])
```
3. The usual way: (without this PR)
```python
x = mat2([[1, 0], [0, 1]])
y = mat2(1)
```
> [Lang] Add more initialization routines for glsl matrix types

- taichi/backends/cpu/aot_module_loader_impl.cpp
- taichi/llvm/llvm_aot_module_loader.cpp
- taichi/llvm/llvm_aot_module_loader.h
For AotModuleImpl, the only difference between CPU and CUDA backend lies in the various ModuleToFunctionConverter they used. Therefore we extracted common methods and members into LLVMAotModule, so that CPUAotModuleImpl and CUDAAotModuleImpl only need to override the `convert_module_to_function()` method.
> [llvm] [aot] CUDA-AOT PR #1: Extracted common logics from CPUAotModuleImpl into LLVMAotModule

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
Related issue = #3382
AtomicOpStmt codegen in CUDA backend was once refactored in #2490. Same thing should also be done for CPU backends and the result code can actually be merged.
> [llvm] [refactor] Merge AtomicOpStmt codegen in CPU and CUDA backends

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
- taichi/program/kernel.cpp
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/ndarray_rw_accessors_bank.cpp
- taichi/program/ndarray_rw_accessors_bank.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- tests/python/test_ndarray.py
#5044 
This PR makes sure Ndarray shape is field shape instead of flattened field shape + element shape. It also got rid of `num_active_indices` in Ndarray class as it's just redundant. 
Now that we have two shapes which may be ordered differently depending on layout, a unified `total_shape` still comes in handy in some implementations. But it shouldn't be used by users directly (if they want they should sum up element_shape and field_shape themselves). 
[Update: this is fixed. We still need to update codegen but at runtime we no longer set element_shape in extra_args] ~Note this PR still need to set element_shape in extra_args in the `set_arg_ndarray`. It's blocked by the fact that predefined kernels like `fill_ndarray_matrix` is supposed to work for all element_shapes. In other words …
> [refactor] Make sure Ndarray shape is field shape

- cpp_examples/autograd.cpp
- python/taichi/lang/field.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/misc.py
- taichi/analysis/gen_offline_cache_key.cpp
- taichi/analysis/offline_cache_util.cpp
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/frontend_ir.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/snode_expr_utils.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/auto_diff.cpp
Related issue = #5055
Decompose the vague grad to adjoint (for reverse mode) and dual (for forward mode). Support allocating both adjoint and dual SNodes as we need both when computing second-order derivatives.
> [autodiff] Allocate dual and adjoint snode

- docs/lang/articles/advanced/odop.md
Related issue = #4989 
Added under the Advanced / Object Data Oriented Programming section
> [Doc] Add documentation of Taichi Struct Classes.

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
This is a follow-up PR of #5086. `FAdd`, `UMin`, `UMax` are actually supported by LLVM, so there is no need to call manually-implemented functions. The code is also refactored in a cleaner way (no more `real_or_unsigned_type_atomic`).
> [llvm] [refactor] Use LLVM native atomic ops if possible

- taichi/aot/graph_data.cpp
Now that ndarray's element_shape is separated from shape, this hack can
be removed.
> [bug] Minor fix for ndarray element_shape in graph mode

- taichi/runtime/gfx/runtime.cpp
Related issue = #5044
The current GFX runtime reads from extra args buffer to calculate the shape of ext arrs. If we simply remove the element shape from extra args, the memory allocator would misbehave.
These information has already been stored in the `host_ctx`. Use the pre-calculated information instead.
> [aot] Use pre-calculated runtime array size for gfx runtime.

- docs/lang/articles/advanced/odop.md
This is a follow-up PR of #5075. There should only be two sections, "Data-oriented classes" and "Python classes as Taichi struct types" in this article. Some other nits are fixed by the way.
> [Doc] Improve ODOP doc structure

- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- tests/cpp/aot/runtime_test.cpp
This constructor is mainly used to construct an Ndarray out of an
existing device allocation. This PR updates the behavior of this
constructor to seprate element_shape out of shape.
> [refactor] Update Ndarray constructor used in AOT runtime.

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/llvm/llvm_codegen_utils.h
Related issue = #4857, #3382
`load_bit_pointer()` is a function paired with `create_bit_ptr_struct()`, which belongs to `CodeGenLLVM` instead of `LLVMModuleBuilder`.
> [llvm] [refactor] Move load_bit_pointer() to CodeGenLLVM

- taichi/transforms/type_check.cpp
When loaded, a custom int is guaranteed to get cast into its compute type. Therefore, the type check for `BinaryOpStmt` here does redundant promotion. This part should be removed to avoid misleading developers.
> [type] [refactor] Remove redundant promotion for custom int in type_check

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
Related issue = #4857, #3382
This is a first pass of fixing the function names in `codegen_llvm_quant.cpp`, with an emphasis on correcting the type names.
The original type names in function names are random to some extent, which makes code hard to read. Now I've figured out what these functions are doing, and enforced consistent use of `quant_int`, `quant_fixed`, `quant_float` or `f32` to refer to different types involved.
|From|To|
|-|-|
|`atomic_add_custom_int`|`atomic_add_quant_int`|
|`atomic_add_custom_float`|`atomic_add_quant_fixed`|
|`float_to_custom_int`|`quant_fixed_to_quant_int`|
|`store_custom_int`|`store_quant_int`|
|`store_floats_with_shared_exponents`|`store_quant_floats_with_shared_exponents`|
|`extract_exponent_from_float`|`extract_exponent_from_f32`| …
> [type] [llvm] [refactor] Fix function names in codegen_llvm_quant

- taichi/llvm/llvm_offline_cache.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
Related issue = #4800 
1. Implemented `FieldCacheData` to serialize necessary compiled information used for field initialization at runtime.
2. Refactored field runtime initialization function "initialize_llvm_runtime_snodes()", so that it only uses compiled information stored in  FieldCacheData.
> [aot] [llvm] LLVM AOT Field #0: Implemented FieldCacheData & refactored initialize_llvm_runtime_snodes()

- python/taichi/examples/graph/stable_fluid_graph.py
- python/taichi/graph/_graph.py
- python/taichi/lang/kernel_impl.py
- taichi/program/graph_builder.cpp
- taichi/program/graph_builder.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
This bug was triggered when we tried to port stable_fluid demo so this
PR also added a cgraph based stable fluid demo.
```
ti example stable_fluid_graph
```
Note it's not ideal to save both `FunctionType compiled_` as well as
`aot::Kernel compiled_aot_kernel_` inside C++ `Kernel` class. But we plan to clean that
up (likely by getting rid of `FunctionType compiled_`) in #5114.
> [aot] [bug] Use cached compiled kernel pointer when it's added to graph multiple times

- docs/lang/articles/reference.md
> [Doc] Editorial update

- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
Using `ti.gpu` as the default arch may cause problems when cuda is not available and `ti.opengl` is chosen.
Change it to `ti.vulkan` as other ggui examples.
> [Example] Fix mass_spring_3d_ggui backend

- python/taichi/lang/matrix.py
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/shaders/snode_bit_pointer.metal.h
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/type_utils.h
- taichi/python/export_lang.cpp
- taichi/transforms/type_check.cpp
Related issue = #4857,  #3382
This PR is split off from another ongoing refactoring to avoid disorder. It basically includes some misc improvements:
- Rename `extract_digits_from_quant_float_with_shared_exponent` to `extract_digits_from_f32_with_shared_exponent`.
- Rename `custom_type_to_bits` to `quant_int_or_quant_fixed_to_bits`.
- Rename function names in metal quant codegen corresponding to #5115.
- Use `is_quant()` instead of `is_custom_type()`.
- Use `tlctx->get_constant()` instead of manually constructing constants.
> [type] [refactor] Misc improvements to quant codegen

- taichi/gui/win32.cpp
> [ui] Properlly fix UTF-8 title string by converting to UTF16

- python/taichi/types/quantized_types.py
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/ir/snode.h
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/ir/type_utils.h
- taichi/program/snode_expr_utils.cpp
- taichi/python/export_lang.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/demote_atomics.cpp
Related issue = #4857, #3382
Previously, `ti.types.quant.fixed` and `ti.types.quant.float` are both represented as `CustomFloatType`. However, they are essentially different things, and indeed handled in almost completely different code paths. The heavy dispatch and misleading names make the code hard to maintain. This PR separates a `CustomFixedType` out for `ti.types.quant.fixed`.
> [type] [refactor] Separate CustomFixedType from CustomFloatType

- cmake/TaichiExportCore.cmake
- cmake/taichi_export_coreConfig.cmake.in
Related issue = #4832 
When using `taichi_export_core` library in Cmake, clients have to manually linking the .so library and providing include paths etc. This PR enables Taichi to generate cmake configuration files. This allows anyone linking the library in just two cmake instructions:
```
find_package(taichi_export_core REQUIRED CONFIG)
target_link_libraries(implicit_fem PUBLIC taichi_export_core::taichi_export_core)
```
An example AOT usage (implicit_fem) can be found at this PR https://github.com/taichi-dev/taichi-aot-demo/pull/21
> [build] Export cmake config to ease clients usage in Cmake

- python/taichi/ad/_ad.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
> [refactor] [autodiff] Clean redundant compiled functions and refactor kernel key

- python/taichi/ui/utils.py
> [gui] Detailed error message when GGUI is not available

- python/taichi/lang/misc.py
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_parallel_range_for.py
Related issue = #3750 #4541
For kernels with `arch=ti.cpu`, users tend to rely on the default `block_dim` settings. The default value is always 32 for CPU backends, which leads to slow execution for simple kernels. This PR adds the option to adaptive select block_dim during codegen. This leads to a 1.4x speedup for a simple kernel as mentioned in #4541:
```
@ti.kernel
def reduce_para()->ti.f32:
n = v1.shape[0]
sum = 0.0
ti.loop_config(block_dim_adaptive=False)
sum += v1[i]*v2[i]
return sum
```
> [refactor] Enable adaptive block_dim selection for CPU backend

- python/taichi/lang/expr.py
- tests/python/test_literal.py
I tried hacking around to be smart about the literal dtypes depending on
backends or passed in python/numpy value. But those cause various
inconsistencies as well so I decided to improve the error message
first...
> [lang] Improve error message when literal val is out of range of default dtype

- taichi/common/core.h
- taichi/system/profiler.h
It should have the exact same behavior as `static_assert`: you need a semicolon after it.
> [misc] Improve TI_STATIC_ASSERT compatibility

- taichi/backends/vulkan/vulkan_device.h
- taichi/ir/type_utils.cpp
- taichi/ir/type_utils.h
> [lang] Export a few types from the share library

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_utils.h
- taichi/llvm/struct_llvm.cpp
Having a `physical_type` in `QuantIntType` is simply wrong - a `QuantIntType` may be placed under different `bit_struct`s. The `physical_type` needs to be manually passed into functions.
> [type] [refactor] Decouple quant from SNode 2/n: Remove physical_type from QuantIntType

- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/backends/vulkan/renderer.cpp
- taichi/ui/backends/vulkan/renderer.h
- taichi/ui/backends/vulkan/window.cpp
* #5227
* __->__ #5226
Tbh it's better to also refactor `Renderer::cleanup()` as well but it's
a bit more involved.
> [gui] Let gui and renderer manage the resource they own
