- include/taichi/common/config.h
- include/taichi/visual/texture.h
- include/taichi/visualization/particle_visualization.cpp
- python/examples/rendering/tube_in_cube.py
- python/examples/rendering/vcm.py
- python/taichi/visual/texture.py
- src/core/bsdf.cpp
- src/python/export_misc.cpp
- src/surface_material/surface_material.cpp
- src/texture/fractals.cpp
- src/texture/perlin.cpp
- src/texture/sources.cpp
- src/texture/texture_op.cpp
> Diag asset expired

- install.py
Hello! I'm using Fedora 28 and wanted to try out taichi, but there was no support for fedora. This seems to work as expected.
Thanks for taichi, its awesome!
> Add support to Fedora on install script

- Pipfile
- Pipfile.lock
- cmake/PythonNumpyPybind11.cmake
- include/taichi/common/util.h
This fixes hardcoded paths. Also adds pipenv files for pythonic virtualenv based install.
> added pipenv files, fixed hardcoded paths

- python/taichi/lang/impl.py
This is all that is needed to make asin and acos callable from taichi kernel in python
> add ti.asin and ti.acos to python frontend  

- taichi/gui/cocoa.cpp
- taichi/visual/gui.h
I can only say that the PR fixes the crash on my local machine. Is it possible to make a release and invite those bug reporters to see if this fixes the problem/doesn't introduce regression?
> Fix GUI crash on Mac likely due to race condition

- taichi/unified_allocator.cpp
Issues #357 Will allocate 4 GB memory if actual physical memory size is not available on windows
> Fix issue#357

- examples/pbf2d.py
A gif is worth a thousands words ;)
> Add position base fluid 2D to examples

- python/taichi/lang/expr.py
- python/taichi/lang/ops.py
- tests/python/test_mod.py
> python-style modulo

- examples/pbf2d.py
> update PBF to use batched circles

- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
Issue #396 
After this, the only big change I have is `codegen_metal`.
> Implement Metal kernel launching in the runtime

- taichi/profiler.cpp
- taichi/profiler.h
Let me make it a bit more fancy ...
> Make Profiler print the arch name in its title

- tests/python/test_sparse_deactivate.py
This test repeatedly copies and deactivates 2 sparse tensors back and forth.
> repeated deactivate test

- taichi/backends/codegen_metal.cpp
- taichi/backends/codegen_metal.h
Issue #396 
I have at least two more PRs to finish the codegen:
1. Generate metal args struct + generate metal kernels from offload tasks
1. All the IR visiting methods
> Add Metal codegen skeleton code

- taichi/backends/codegen_metal.cpp
> Implement Metal kernels and args struct codegen

- README.md
I feel guilty not to mention these before a potential user gets frustrated...
> Update notes to clarify a few takeaways on the Metal backend

- taichi/backends/codegen_metal.cpp
- tests/python/test_atomic.py
- tests/python/test_div.py
Issue #396 
As discussed before, we don't have to repeatedly generate these instructions.
> Encapsulate fatomic_fetch_add and ifloordiv as functions

- taichi/ir.h
Refer to https://github.com/taichi-dev/taichi/issues/456#issuecomment-586637753.
> Fix stmt->parent in Block::push_back.

- taichi/platform/metal/metal_data_types.h
- taichi/tlang_util.cpp
- tests/python/test_pow.py
Issue #468 
I just used the builtin `pow` and didn't do any specialization for integer pows...
> Make Metal support pow()

- python/taichi/lang/expr.py
- taichi/transforms/make_adjoint.cpp
- tests/python/test_ad_basics.py
> implement x ** y gradients for #469

- taichi/platform/metal/metal_runtime.cpp
- taichi/platform/metal/metal_runtime.h
- taichi/program.cpp
Issue #396 
I will skip the review process because this is mostly just code cleanup. :-)
> Refactor Metal runtime to take in a single params struct in its ctor

- python/taichi/core/util.py
> Seperated sandbox for taichi_core.so #501

- python/taichi/lang/impl.py
> Better error message when try to declare tensors after kernel invocation #506

- .travis.yml
- appveyor.yml
> cached build for CI #496

- python/taichi/core/util.py
As mentioned in https://github.com/taichi-dev/taichi/issues/501#issuecomment-589966069
Related issue id = #501
> register atexit callback to remove sandbox tmp_dir (A continue of #503) #501

- docs/hello.rst
> Update doc around how the loops at the outermost scope is parallelized

- docs/hello.rst
> Fix doc format

- taichi/platform/metal/metal_kernel_util.cpp
- taichi/platform/metal/metal_runtime.cpp
- tests/python/test_types.py
> Make Metal support <=32bit args

- tests/python/test_compare.py
Metal doesn't support `dynamic` or any other sparse snodes... :(
> Fix Metal crashes due to the usage of dynamic snode

- taichi/core/logging.cpp
> throw exception instead of SIGABRT to obtain RuntimeError in Python-scope #523

- taichi/backends/codegen_metal.cpp
- taichi/platform/metal/metal_runtime.cpp
- taichi/program.cpp
Related issue id = #396 
Mostly code cleanup..
> Do not instantiate Metal root buffer if it's not used

- taichi/platform/opengl/opengl_api.cpp
> (MERGE ME) emergency fix for non-GL build (1)

- tests/python/test_compare.py
Related pr id = #540
Add tests for unsupported `is, is not, in, not in`.
> Add tests for unsupported "compare" operators

- python/taichi/lang/transformer.py
- tests/python/test_return.py
- tests/python/test_syntax_errors.py
> Frontend kernel/function structure checking

- python/taichi/lang/ast_checker.py
- python/taichi/lang/kernel.py
- tests/python/test_ad_basics.py
> Add a KernelSimplicityASTChecker to ensure grad kernel is compliant

- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/program/kernel.cpp
Related issue id = #542 
See if this PR compiles without me having CUDA...
> [refactor] Move CUDA args buffer logic into the compiled kernel

- taichi/codegen/codegen_llvm.h
- taichi/runtime/llvm/runtime.cpp
> Avoid error message formatting for valid accesses

- examples/mgpcg.py
> reformat example/mgpcg.py

- python/taichi/lang/impl.py
- tests/python/test_ptr_assign.py
This allows ti.static assignment for funcs and classfuncs as well.
> add static ptr assignment for funcs too

- misc/format_server.py
- python/taichi/core/util.py
- python/taichi/main.py
Just for testing if the format server script is working correctly...
> Test format server

- ci_setup.py
> Fix travis

- taichi/codegen/codegen_opengl.cpp
> Fixed non-OpenGL build

- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/struct/struct_llvm.cpp
> Removed unused fields of SNode

- misc/.style.yapf
- misc/baselines/assert.cu
- python/taichi/core/util.py
> Improved `ti format`

- misc/format_server.py
> Format server index page

- .github/pull_request_template.md
- misc/format_server.py
> Link to format server in PR template 

- python/taichi/lang/transformer.py
- tests/python/test_static.py
> Fixed ASTTransformer.visit_For on static ndrange loops

- cmake/TaichiCore.cmake
- taichi/codegen/codegen_opengl.cpp
- tests/python/test_grouped.py
- tests/python/test_syntax_errors.py
Related issue id = #606 
This is a continue of #632 
> Add atomic_bit_or/xor/and for OpenGL

- python/taichi/core/util.py
> Fixed 'ti format' crashing on deleted files

- Jenkinsfile
> Fix Jenkinsfile after testing CLI update

- Jenkinsfile
> Change Jenkins repo URL to taichi-dev

- taichi/codegen/codegen_cpu.cpp
- taichi/codegen/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/statements.h
- taichi/llvm/llvm_codegen_utils.h
- taichi/runtime/llvm/internal_function.h
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/make_adjoint.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_ad_if.py
> Mutable local variable autodiff

- taichi/codegen/codegen_opengl.cpp
> add LineAppender for OpenGL too #643

- .github/pull_request_template.md
- docs/contributor_guide.rst
- docs/cpp_style.rst
> [doc] Updated contributor guideline

- taichi/analysis/gather_statements.cpp
- taichi/ir/ir.h
- taichi/struct/struct_metal.cpp
- taichi/transforms/make_adjoint.cpp
@xumingkuan This might help you performance analysis more easily.
> [ir] Added irpass::gather_statements

- misc/format_server.py
> [misc] Fixed format server file coverage

- misc/format_server.py
Force delete when user reuses branch name
> [misc] Improve format server stability

- examples/mgpcg_advanced.py
- misc/minimal_timed.py
- misc/test_poly_timed.py
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen_cpu.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cpu.cpp
- taichi/jit/jit_arch_cpu.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/program/program.cpp
- taichi/runtime/llvm/node_pointer.h
- taichi/runtime/llvm/runtime.cpp
- taichi/struct/struct_llvm.cpp
> [Infra] 6x faster compilation on CPU backends

- misc/make_changelog.py
> [misc] `misc/make_changelog.py` for automatically generating the changelogs

- .travis.yml
- Jenkinsfile
- appveyor.yml
- python/taichi/main.py
- taichi/llvm/llvm_context.cpp
> [Infra] `ti test` now supports `-t/--threads` for specifying number of testing threads

- taichi/ir/ir.h
- taichi/transforms/make_adjoint.cpp
> [refactor] Removed Stmt::adjoint

- docs/contributor_guide.rst
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/ir/ir.h
> [refactor] Removed `llvm::Value *Stmt::value`

- tests/python/test_ad_basics.py
> [metal][opengl] Fix tests that require 64-bit data

- docs/contributor_guide.rst
- python/taichi/lang/__init__.py
- taichi/codegen/codegen.h
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/ir/ir.h
- taichi/lang_util.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
An intermediate step to make Taichi more async. I'll just merge this in after CI passes. I need these features implemented today so that I can report it to my advisor.
> [async] AsyncEngine infrastructure

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/program/kernel.cpp
> [refactor] Create `taichi/codegen/codegen_llvm.cpp` and outline class member definitions

- taichi/codegen/codegen_opengl.cpp
- tests/python/test_numpy.py
Now we can run `examples/pbf2d.py`.
Related issue = #693 
> [OpenGL] support external array argument > 1

- docs/contributor_guide.rst
- tests/python/test_struct_for.py
> [test] Make test_struct_for_branching run on archs with `pointer`

- taichi/ir/ir.h
- taichi/transforms/type_check.cpp
- tests/python/test_basics.py
> [ir] Fix compilation crash when passing global pointer to if statements

- taichi/ir/expr.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
> [ir] [refactor] Use const& in function parameters to avoid copying

- taichi/system/traceback.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/656#issuecomment-610071336
> [Infra] Windows debugging infrastructure

- appveyor.yml
- docs/contributor_guide.rst
- taichi/codegen/codegen_opengl.cpp
Related issue = #621 
As mentioned in https://github.com/taichi-dev/taichi/issues/621#issuecomment-601998940
> [infra] AppVeyor trigger format server when [format] specified in commit message

- taichi/transforms/make_adjoint.cpp
> [ir] Fix adjoint alloca location in `make_adjoint`

- taichi/analysis/verify.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/fix_block_parents.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_local_atomics.py
Related issue = https://github.com/taichi-dev/taichi/pull/727#issuecomment-611296391
> [ir] [refactor] Add a `verify` pass to find out illegal IRs, and remove OffloadedStmt::begin_stmt/end_stmt

- examples/game_of_life.py
- python/taichi/misc/gui.py
> [misc] add game_of_life example

- taichi/backends/opengl/opengl_api.cpp
Related issue = #693 
Related PR = #694
> [opengl] add check_opengl_error to prevent potential segfault

- misc/test_async.py
- taichi/analysis/count_statements.cpp
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen.h
- taichi/codegen/codegen_cpu.h
- taichi/codegen/codegen_cuda.h
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_cpu.cpp
- taichi/codegen/codegen_llvm_cuda.cpp
- taichi/ir/ir.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/type_check.cpp
- taichi/util/statistics.cpp
- taichi/util/statistics.h
> [async] Benchmark infrastructure

- taichi/analysis/check_fields_registered.cpp
- taichi/analysis/count_statements.cpp
- taichi/analysis/verify.cpp
- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/statements.h
- taichi/ir/visitors.h
Related issue = https://github.com/taichi-dev/taichi/pull/743#discussion_r406840491
> [ir] [refactor] Simplify statement visitors

- docs/syntax.rst
Otherwise people are not aware of these function.
> Update syntax.rst to include sqrt, asin, acos

- taichi/ir/snode.cpp
- taichi/ir/snode.h
- tests/python/test_assert.py
> [misc] Fix dynamic node out-of-bound checker

- taichi/analysis/check_fields_registered.cpp
- taichi/analysis/count_statements.cpp
- taichi/analysis/detect_fors_with_break.cpp
- taichi/analysis/gather_deactivations.cpp
- taichi/analysis/gather_statements.cpp
- taichi/analysis/same_statements.cpp
- taichi/analysis/value_diff.cpp
- taichi/analysis/verify.cpp
- taichi/codegen/codegen.cpp
- taichi/ir/ir.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/insert_scratch_pad.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/make_adjoint.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
- taichi/transforms/whole_kernel_cse.cpp
- tests/cpp/test_same_statements.cpp
> [ir] [refactor] Move all passes that do not change IR into `irpass::analysis`

- examples/fluid.py
- examples/stable_fluid.py
(Probably buggy? ) implementation of http://developer.download.nvidia.com/books/HTML/gpugems/gpugems_ch38.html
> [Example] Add 2D stable fluids example

- examples/regression.py
- taichi/backends/opengl/opengl_api.cpp
- taichi/core/interfaces.cpp
- taichi/jit/jit_arch_cpu.cpp
- taichi/jit/jit_session.cpp
- taichi/python/export.h
- taichi/struct/struct_llvm.cpp
- taichi/system/memory_usage_monitor.cpp
- taichi/util/image_buffer.cpp
- taichi/util/image_io.cpp
> [misc] Unify #include format

- README.md
- docs/contributor_guide.rst
- docs/hello.rst
- python/build.py
> [PyPI] Package name changed from `taichi-nightly` to `taichi`

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
I Implemented the matrix determinant and inverse for 4x4 matrices using the same Adjugate method as for 3x3. I think this is about the biggest we can go before we need to switch to Gauss Jordan, which may have to be done in its own ti.func. 
> [lang] 4x4 matrix inverse and det

- Jenkinsfile
- README.md
- changelog.md
- docs/contributor_guide.rst
- misc/make_changelog.py
Related issue = #740 
More visual demos, and an introduction to the team members will be added later.
> [misc] Simplified README.md

- python/taichi/lang/__init__.py
> [cli] Fix `ti test`

- python/taichi/lang/__init__.py
- taichi/backends/cuda/cuda_driver.cpp
> [cli] add TI_GDB_TRIGGER config var

- python/taichi/main.py
> [CLI] Fix `ti` commands other than `ti test`

- docs/linalg.rst
> [doc] fix typo

- docs/internal.rst
> [doc] Document the Statistics class

- examples/mpm_lagrangian_forces.py
> [example] Improve `mpm_lagrangian_forces.py`

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/codegen/codegen_opengl.cpp
- taichi/struct/struct_opengl.cpp
- taichi/struct/struct_opengl.h
> [OpenGL] fix NVIDIA's GLSL stuck at compile by sorting snodes

- python/build.py
> [CUDA] Fix `slim_libdevice.bc` shipping on Windows

- python/build.py
- python/taichi/__init__.py
- python/taichi/core/__init__.py
- python/taichi/core/unit.py
- python/taichi/core/util.py
- python/taichi/lang/core.py
- python/taichi/misc/util.py
- python/taichi/tools/video.py
- taichi/backends/opengl/opengl_api.cpp
- taichi/common/util.h
- taichi/python/exception.cpp
- taichi/python/exception.h
- taichi/python/export.cpp
- taichi/python/export.h
- taichi/python/export_math.cpp
- taichi/python/export_misc.cpp
- taichi/struct/struct_opengl.cpp
- Re-enforce code format for all files
- Rename `tc_core` to `ti_core`
- Removed some unused functions
- No `libdevice` needed on OS X
- Removed excessive Python bindings of `taichi::Vector`'s
> [refactor] Miscellaneous & mechanical cleanups

- taichi/transforms/alg_simp.cpp
- tests/cpp/test_alg_simp.cpp
> [opt] Algebraic simplification for bitwise operators

- tests/python/test_offload_cross.py
> [test] Add a test for #813

- python/taichi/lang/__init__.py
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- tests/python/test_ad_if.py
I don't know the file name of which we're going to print, so I print the statistics to the screen for now.
> [misc] Add an option to print statistics into files

- taichi/program/program.cpp
- taichi/util/statistics.cpp
- taichi/util/statistics.h
> [misc] Clear stats in the constructor of Program

- taichi/util/statistics.cpp
> [misc] Avoid printing empty logs

- tests/python/test_tensor_reflection.py
> [test] Fix duplicate test name in test_tensor_reflection.py

- taichi/python/export_misc.cpp
- taichi/system/profiler.cpp
- taichi/system/profiler.h
> [misc] `taichi::Profiling` now supports multiple threads

- taichi/transforms/simplify.cpp
> [opt] Lower `linearize` even without advanced optimization

- examples/renderer_utils.py
- examples/sdf2d.py
> [Example] add sdf2d.py

- taichi/transforms/optimize_local_variable.cpp
- tests/python/test_optimization.py
> [Opt] [Bug] Fix the state of the last store after a loop

- examples/pbf2d.py
This is a trivial change, so I'm just gonna wait for the CI to pass before merging it :)
Related issue = #872
> [example] Fix `pbf2d.py`'s initialization to use np.float32

- taichi/analysis/gather_used_atomics.cpp
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/statements.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/system/profiler.cpp
- taichi/system/profiler.h
Note that codegen may change the hash of the statement.
> [async] [refactor] Fix async engine statement not found error

- misc/generate_commit_hash.py
> [misc] Avoid unnecessary linking when git commit hash not changed

- taichi/backends/cpu/jit_cpu.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/ir/ir.h
- taichi/ir/snode.cpp
- taichi/program/async_engine.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/lower_access.cpp
> [async] Fix SNode reading in async mode

- taichi/backends/cpu/jit_cpu.cpp
- taichi/ir/ir.h
- taichi/program/async_engine.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
> [async] No synchronization after kernel launch and postpone lower access

- taichi/transforms/variable_optimization.cpp
> [opt] Use advanced_optimization for #857

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/ir_printer.cpp
I don't see a reason why we need this alias.
> [ir] Remove `Ident` alias

- taichi/ir/ir.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/extract_constant.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/variable_optimization.cpp
Benchmark:
**Before**:
**After**:
mpm99.py: 2875 -> 2868 stmts
> [Opt] Extract constants to top-level

- .travis.yml
- appveyor.yml
- misc/ci_setup.py
- python/taichi/main.py
So that we don't get confused with random failures.
See https://github.com/pytest-dev/pytest-rerunfailures.
> [test] Add an argument -r to rerun failed test

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/lower_ast.cpp
This PR moves one step forward towards removing the global variable `current_block`
https://github.com/taichi-dev/taichi/blob/14094f25004e1052f134885fddd9252e004eb398/taichi/ir/ir.h#L1906-L1908
I'm trying to do some refactoring to make it easier for separating out the frontend stmts/expressions. Knowing the current block could be useful during expression flattening, but it wasn't done properly because of that global variable. As a fix, I added a small `FlattenContext` wrapper, and let the visitors set the current block during AST traversal.
Lots of the changes here are just for adopting the context. The only real change is here
https://github.com/taichi-dev/taichi/blob/14094f25004e1052f134885fddd9252e004eb398/taichi/ir/ir.h#L1923-L1925.
Note that `IdExpression::flatten` no longer needs to …
> [ir][refactor] Pass a context object to `Expression::flatten()`

- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/cuda/jit_cuda.cpp
- taichi/jit/jit_session.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/make_adjoint.cpp
- tests/python/test_ad_if.py
- tests/python/test_element_wise.py
> [CUDA] [AutoDiff] Fix CUDA data layout and stack alignment

- docs/gui.rst
- docs/syntax.rst
- misc/ci_setup.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/main.py
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/transforms/type_check.cpp
> [misc] Enforce format

- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
> [Misc] Add `ti.core.toggle_advanced_optimization(True/False)`

- docs/atomic.rst
- docs/syntax.rst
> [doc] update doc for kernel return in #930

- README.md
> [misc] README.md use shields.io to show latest release

- docs/hello.rst
Related issue = #941  (if any)
I went through 'hello.rst' and fixed some language issues. Most of them are just me being nitpicking, but hope that helps. 😃 
> [doc] improve `hello.rst' (#941)

- docs/gui.rst
- docs/layout.rst
- docs/syntax.rst
- docs/utilities.rst
> [doc] Fix missing language fields in code-blocks

- docs/contributor_guide.rst
- docs/cpp_style.rst
- docs/dev_install.rst
- docs/hello.rst
- docs/utilities.rst
> [doc] Update the "contributing" chapter

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/loop_vectorize.cpp
> [ir] [refactor] Remove operand_bitmap from Stmt

- docs/hello.rst
- docs/index.rst
- docs/install.rst
> [doc] Add install.rst for installation compatability troubleshooting

- taichi/analysis/clone.cpp
- taichi/analysis/same_statements.cpp
- taichi/ir/analysis.h
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/program/kernel.cpp
> [IR] Add an IR cloning pass

- docs/atomic.rst
- docs/external.rst
- docs/tensor_matrix.rst
- docs/type.rst
> [doc] Update basic concepts

- python/taichi/misc/gui.py
> [gui] Use np.clip(_, 0, 1) to fix win display error

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/backends/opengl/struct_opengl.cpp
- taichi/backends/opengl/struct_opengl.h
> [opengl][refactor] refactor stuff into one "SnodeInfo" for better furture sparse support

- examples/cornell_box.py
Added a transformed box, also accidentally found #1004..
> [Example] Make cornell box more authentic

- docs/atomic.rst
- docs/tensor_matrix.rst
- docs/type.rst
> [doc] Minor improvements on basic concepts

- python/taichi/lang/matrix.py
> [Lang] Improve error message for Matrix/Vector accessors

- benchmarks/benchmark_baseline.txt
- benchmarks/fill_dense.py
- benchmarks/fill_sparse.py
- benchmarks/memory_bound.py
- benchmarks/minimal.py
- benchmarks/mpm2d.py
- benchmarks/run.py
- docs/utilities.rst
- python/taichi/lang/__init__.py
- python/taichi/main.py
Related issue = #959 close #999
Now, run `ti benchmark -T` for TPRT.
> [benchmark] Upgrade to Time Performance Regression Test (TPRT)

- .github/workflows/daliy.yml
- .github/workflows/stale.yml
I found that we have many issues-out-of-date there.. and I see you closing some of them, so I think it would be great if we can detect these stale issue and warn us about that, wheather to close.
> [workflow] Add workflows/stale.yml to detect stale issues and PRs

- tests/python/test_bitmasked.py
This just adds a test for `bitmasked` in case we later implement some of the optimizations from #986
Related issue = #709 
> [test] [sparse] Add a test case for bitmasked

- docs/dev_install.rst
`cd` into the repo directory first, then fetch all sub-modules.
> Fix the wrong order of commands

- .github/workflows/persubmit.yml
Related issue = as I promised in #1023 
> [workflow] Test against multiple python versions

- docs/scalar_tensor.rst
> [doc] Fix sample code format

- docs/index.rst
- docs/taichicon.rst
@JusperLee As promised here I briefly document how TaichiCon 0 was organized... I'll update it with more details tomorrow.
> [doc] Document TaichiCon

- python/taichi/core/util.py
> [misc] Improve Windows core loading message

- taichi/backends/metal/codegen_metal.cpp
> [metal] Make the comparison result -1 for true

- python/taichi/lang/matrix.py
> [misc] Fix import warnings when using collections module

- taichi/backends/opengl/codegen_opengl.cpp
> [opengl] Make the comparison result -1 for true

- docs/matrix.rst
- docs/vector.rst
- examples/cornell_box.py
- examples/mpm128.py
- examples/mpm88.py
- examples/mpm99.py
- examples/mpm_lagrangian_forces.py
- examples/particle_renderer.py
- examples/renderer_utils.py
- examples/sdf2d.py
- examples/sdf_renderer.py
- python/taichi/lang/__init__.py
- python/taichi/lang/linalg.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/lang/util.py
- taichi/analysis/build_cfg.cpp
- tests/python/test_linalg.py
- tests/python/test_mpm88.py
- tests/python/test_svd.py
Related issue = https://github.com/taichi-dev/taichi/issues/833#issuecomment-636476353
> [Lang] [refactor] Standardize math API (stage 1)

- python/taichi/core/util.py
> [misc] Set gdb trigger to off by default

- python/taichi/main.py
> [cli] [example] Support running examples with python file extension

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/alg_simp.cpp
> [opt] Add a DelayedIRModifier class

- docs/install.rst
- python/taichi/main.py
Related issue = https://forum.taichi.graphics/t/pip-taichi/224
> [doc] Add version troubleshooting

- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
> [misc] [test] Fix matrix initialization

- .github/ISSUE_TEMPLATE/bug_report.md
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/kernel_util.h
Mostly just renaming `args` to `ctx`
Related issue = #909
WANT_LGTM=any
> [refactor] [metal] Rename some variables from args to ctx

- README.md
> [misc] Update links to point to this repository

- python/taichi/main.py
> [cli] [bug] Fix "unclosed file" in "ti regression"

- README.md
> [misc] Add some links to README.md

- python/taichi/main.py
Related issue = #622 
Just a minor bug fix.
> [cli] Sort video input frames

- taichi/transforms/type_check.cpp
> [Bug] [ir] Fix ti.sqrt/exp/log error with an integral operand

- docs/matrix.rst
- python/taichi/lang/matrix.py
- tests/python/test_linalg.py
> [Lang] [refactor] ti.Matrix initializers

- .github/pull_request_template.md
- .github/workflows/persubmit.yml
- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- docs/contributor_guide.rst
- docs/dev_install.rst
- docs/utilities.rst
- misc/ci_setup.py
- python/taichi/main.py
- python/taichi/tools/messenger.py
- setup.py
Related issue = #1195
Current coverage = 67.03%
See https://codecov.io/gh/taichi-dev/taichi/src/master/python/taichi/lang/util.py, really cool!
> [test] Setup python coverage test

- docs/export_results.rst
- docs/gui.rst
- examples/export_videos.py
Related issue = Close #1176 
Hi all,
This PR tries to offer more examples and explantions in export_results.rst and gui.rst.
I have proofread x5 and think about this topic x5. But I guess there must still be some mistakes and unsatisfied stuff :D. If so, please let me know.
Hopefully this PR can make our docs better!
> [doc] Improve tutorial on exporting results

- python/taichi/main.py
- tests/python/test_cli.py
> [CLI] Add "ti example -s/-p/-P" to save/print/pretty_print example source code

- taichi/transforms/compile_to_offloads.cpp
> [ir] Don't do optimization for JIT evaluator kernels

- taichi/transforms/lower_access.cpp
> [Perf] Improve dynamic SNode performance (stage 2)

- README.md
>  [misc] Fix a typo in README.md: Discourage -> Discourse

- taichi/ir/transforms.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/kernel.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/binary_op_simplify.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/simplify.cpp
> [Opt] Add binary ops optimization pass

- examples/autodiff_minimization.py
- examples/autodiff_regression.py
- examples/mnist.py
- examples/odop_solar.py
- examples/particle_renderer.py
- examples/pbf2d.py
- examples/taichi_autodiff.py
- examples/taichi_dynamic.py
- misc/benchmark_compile.py
- misc/benchmark_tensor_access.py
- misc/test_poly_timed.py
Remove all `ti.layout` and add `odop_solar.py`.
Related issue = #1016 
----
> [example] Refactor examples

- .gitignore
- docs/contributor_guide.rst
- examples/export_mesh.py
- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/cuda/jit_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/struct/struct_llvm.cpp
- taichi/util/file_sequence_writer.cpp
- taichi/util/file_sequence_writer.h
> [misc] Refactor LLVM IR/NVPTX dumping system

- README.md
- python/build.py
- python/taichi/misc/image.py
- tests/python/test_image_io.py
This reverts commit 112f18ebe7709b343895a1f41f83bc2cceda12bc.
Related issue = #1185
----
> [misc] Revert #1185

- docs/index.rst
- docs/versioning_releases.rst
Related issue = close #1198 
Comments are welcome :-)
> [Doc] Standardize versioning and release workflow

- python/build.py
- python/taichi/main.py
> [cli] Add "ti dist" command to test in release mode

- .github/pull_request_template.md
- python/taichi/lang/impl.py
- python/taichi/lang/transformer.py
- tests/python/test_tuple_assign.py
Related issue = close #1237
----
Just a very tiny modification.
> [Bug] [lang] Fix tuple assignment behavior in Taichi-scope

- README.md
---
- Remove the expired changelog link from readme.
- Make the badges be consistent with their text counterparts.
> [doc] Remove changelog link from readme

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/lower_access.cpp
(I'm not sure which SNode operations need activation.)
----
> [perf] Improve dynamic SNode performance (stage 3)

- docs/differentiable_programming.rst
- docs/gui.rst
- examples/odop_solar.py
- python/taichi/lang/impl.py
- tests/python/test_tuple_assign.py
Related issue = #1247 (comment)
----
> [Lang] Support vector unpacking (e.g., "a, b = ti.Vector([1, 2])")

- docs/index.rst
- python/taichi/misc/gui.py
Related issue = close #1260
----
> [GUI] [bug] Fix "gui.set_image" not accept multi-channel scalar tensors

- taichi/transforms/flag_access.cpp
> [perf] [opt] Better weaken_access pass for sparse cases

- taichi/transforms/compile_to_offloads.cpp
> [ir] Make pass names appear in correct positions when print_ir=True

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/transforms.h
- taichi/transforms/demote_atomics.cpp
> [Opt] [ir] [refactor] Remove exceptions from demote_atomics pass

- taichi/transforms/auto_diff.cpp
> [bug] Fix stochastic failure of test_loop_grad on Windows

- taichi/ir/transforms.h
- taichi/transforms/lower_access.cpp
> [Opt] [ir] [refactor] Remove exceptions from lower_access pass

- python/taichi/lang/expr.py
- python/taichi/lang/matrix.py
----
Sample code:
```py
@ti.kernel
def hello():
m = ti.Matrix([[2, 3], [4, 5], [6, 7]])
print(m)
hello()
m = ti.Matrix([[2, 3], [4, 5], [6, 7]])
print(m)
```
Before:
```
[[2, 4, 6], [3, 5, 7]]
[[2 3]
[4 5]
[6 7]]
```
After:
```
[[2, 3], [4, 5], [6, 7]]
[[2 3]
[4 5]
[6 7]]
```
> [bug] [std] Fix matrix print shape in Taichi-scope

- taichi/transforms/re_id.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/1296#discussion_r443263658
----
> [ir] [refactor] Simplify the "re_id" pass

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/statements.h
- taichi/transforms/auto_diff.cpp
- taichi/transforms/demote_dense_struct_fors.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/1278#issuecomment-646285524
The total number of statements of tests is unchanged.
----
> [IR] [refactor] Replace "OffsetAndExtractBitsStmt" with "BitExtractStmt"

- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/simplify.cpp
Related issue = #1367 
It indeed doesn't cause the number of statements to increase too much :)
----
> [Opt] Do not flatten ifs by default

- .github/workflows/persubmit.yml
We probably should turn on the C backend on GitHub actions testing only after all tests pass :-)
----
> [workflow] Fix GitHub workflows

- taichi/ir/expr.cpp
> [bug] Fix master due to compilation error

- README.md
> [CUDA] Taichi now supports CUDA 11

- python/taichi/lang/matrix.py
- taichi/transforms/type_check.cpp
- tests/python/test_linalg.py
> [lang] [bug] Fix Matrix.diag (remove unwanted truncation to int)

- misc/check_pr_title.py
> [workflow] Fix PR title checker "fix fatal: bad revision 'master'" in release PR

- docs/gui.rst
- examples/keyboard.py
- python/taichi/misc/gui.py
- taichi/gui/gui.h
- taichi/gui/win32.cpp
- taichi/python/export_visual.cpp
Related issue = #1150 
[GUI] Support mouse wheel event on Win32
[doc] Update document about GUI event.
[Example] Update keyboard.py example , to show how to handle a wheel event . 
I have exported KeyEvent class and Type enum from taichi_core , and support mouse wheel event message on Win32 . 
1. handle wheel event on X11 
2. handle wheel event on cocoa
> [GUI] Support mouse wheel event on Win32

- taichi/analysis/build_cfg.cpp
- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/basic_stmt_visitor.cpp
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/die.cpp
- taichi/transforms/fix_block_parents.cpp
- taichi/transforms/flag_access.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_access.cpp
- taichi/transforms/make_block_local.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/statement_usage_replace.cpp
- taichi/transforms/type_check.cpp
- taichi/transforms/unreachable_code_elimination.cpp
> [llvm] Separate BLS/TLS and refactor loop code generation

- codecov.yml
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- tests/python/test_linalg.py
Related issue = Core-dev WeChat group, after a talk with @k-ye
----
Will `fix all potential random SSA` iapr :)
> [Bug] [lang] [std] Fix all potential matrix SSA violation by using element_wise_write_binary

- taichi/backends/cuda/codegen_cuda.cpp
> [cuda] [bug] Fix CUDA garbage collection grid dim

- docs/gui.rst
- python/taichi/misc/gui.py
- taichi/python/export_visual.cpp
Related issue = From Wechat
Our classmate in GAMES201 said that, he want to fetch the current image array from the GUI. 
So here is a trivial implmention, please feel free to give me more suggestions.
Btw, do we need more test cases about this func?
> [GUI] Get images from the current GUI using gui.get_image()

- docs/export_results.rst
- docs/faq.rst
- docs/global_settings.rst
- docs/hello.rst
- docs/index.rst
- docs/snode.rst
- examples/revert_image_color.py
Related issue = https://forum.taichi.graphics/t/pilimage-as-input/977
----
> [doc] [example] Update faq.rst, add examples/revert_image_color.py

- docs/dev_install.rst
> [doc] Fix LLVM version in dev_install.rst

- docs/syntax.rst
> [doc] Fix typo at line 113: ..kernel do not..

- taichi/analysis/alias_analysis.cpp
- tests/python/test_optimization.py
Related issue = fix #1469 fix #1471
Local loads of the same alloca can have different values.
----
> [Bug] [opt] Hotfix for wrong parallel assignments

- examples/mpm_lagrangian_forces.py
This PR does not change its behavior.
----
> [example] Update mpm_lagrangian_forces.py to new syntax

- examples/game_of_life.py
- misc/demo_oob_ub.py
- taichi/backends/opengl/codegen_opengl.cpp
> [example] Upgrade game_of_life.py to new GUI system

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/shaders/atomic_stubs.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- tests/python/test_dynamic.py
This has been fixed in #1480. But given it's not ready yet, I will fix it here first.
Related issue = #1480
----
> [metal] Fix active() on dynamic SNode

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
`get_kernel()` wasn't 100% fixed in #1245. This PR takes @xumingkuan 's suggestion in https://github.com/taichi-dev/taichi/pull/1245#pullrequestreview-430242227, by creating a dummy `Block` for each kernel. (We could also link the cloned offloaded task's parent to that of the *clonee*. But then this feels like mixing ASTs up..)
This PR is still not enough to make async work again. We still need these:
* disable constant folding JIT. I got some LLVM errors, and didn't look further. My guess is that right now, we expect JIT kernels to finish synchronously in order to use their result. This no longer holds in async mode.
* disable kernel fusion for `mpm99.py`. 
Related issue = #1243
----
> [async] Put cloned offloaded tasks under a dummy shared block

- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
- taichi/backends/metal/struct_metal.cpp
This PR pulls out some tweaks in #1480 to make it less noisy. It's mostly renaming, reordering or fixing comments.
Related issue = #1480 
----
> [metal] Misc tweaks to make #1480 easier to review

- README.md
> [misc] Update README.md

- misc/baselines/ldg.cu
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
> [CUDA] Use CUDA launch bound to limit register usage

- python/taichi/misc/gui.py
- taichi/gui/gui.cpp
- taichi/gui/gui.h
- taichi/python/export_visual.cpp
----
To test, use `examples/fem128.py` in #1521.
I'd also like to add `gui.lines` and `gui.rects` after this is merged.
I'd also like to refactor the numpy array passing ad-hoc `size_t ptr` iapr.
> [GUI] Support gui.triangles() for batched triangle painting

- examples/nbody_oscillator.py
----
Adding r^6 and r^12 term according to: https://www.zhihu.com/question/38966526
So this is a star simulator now (?)
> [Example] Enhance nbody_oscillator.py with molecular force

- taichi/runtime/llvm/locked_task.h
> [cuda] Fix mutex on Turing GPUs

- examples/ad_gravity.py
- python/taichi/lang/__init__.py
----
I :heart: AutoDiff! But currently our AD examples are only about ML... Let's add a CG-related example now.
> [Example] [autodiff] Add ad_gravity.py (compute gradient from potential energy)

- taichi/backends/opengl/opengl_api.cpp
- tests/python/test_reduction.py
Related issue = as mentioned in WeChat group
----
年久失修的OpenGL backend :)
> [opengl] [test] Fix failed OpenGL tests these days

- taichi/runtime/llvm/locked_task.h
> [cuda] Another mutex fix

- misc/cc_fractal.py
- misc/cc_hello.py
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/opengl/codegen_opengl.cpp
> [cc] Support "range for" and "while" statement on C backend

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/opengl_kernel_util.h
Related issue = depends #1542 depends #1543 
----
@yuanming-hu Could you review my PRs quicker so that I can push my work forward? :thinking:
> [opengl] [refactor] Move local_size evaluation to runtime part; extensions now use UsedFeature

- misc/baselines/ldg.cu
- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_context.h
- taichi/llvm/llvm_context.cpp
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/internal_functions.h
- taichi/runtime/llvm/locked_task.h
- taichi/runtime/llvm/node_pointer.h
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_cuda_internals.py
> [Perf] Improve CUDA runtime performance with warp-level primitives

- examples/mpm88.py
> [example] Upgrade mpm88 to new syntax

- tests/python/bls_test_template.py
> [test] Fix issues in "bls_particle_grid" test caused by float-point errors

- taichi/backends/cuda/codegen_cuda.cpp
> [cuda] [bug] Fix a CUDA codegen bug

- taichi/backends/cc/cc_program.h
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cc/runtime/base.h
- taichi/program/extension.cpp
- tests/python/test_atomic.py
- tests/python/test_bitmasked.py
- tests/python/test_dynamic.py
- tests/python/test_struct_for_dynamic.py
Related issue = #1332 #1142 #439
----
Let's not add cc to GHCI yet.. not sure if GHCI have the same gcc as I've, also longer the precious build time.
I'll merge once CI pass and @FantasyVR released.
> [CC] [test] The C backend is now passing all the tests

- misc/test_grid_stride_loop.py
- python/taichi/lang/__init__.py
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/backends/opengl/shaders/listman.h
- taichi/backends/opengl/shaders/runtime.h
- taichi/python/export_lang.cpp
> [opengl] [refactor] 3 misc refactors for OpenGL

- docs/hello.rst
- docs/internal.rst
- docs/layout.rst
- docs/matrix.rst
- docs/meta.rst
This PR try to replace all `tensor` by `field` in the following files:
----
> [Doc] Replace tensor by field for files beginning with h to m

- docs/vector.rst
> [doc] Fix typo in vector.rst

- docs/gui.rst
- examples/mpm88.py
- examples/mpm_lagrangian_forces.py
- python/taichi/misc/gui.py
- taichi/gui/gui.cpp
- taichi/gui/gui.h
- taichi/python/export_visual.cpp
----
mpm_lag_force: 25 fps -> 37 fps
> [GUI] Support gui.lines for batched line drawing

- docs/contributor_guide.rst
- docs/index.rst
- docs/utilities.rst
- docs/write_test.rst
- misc/prtags.json
Related issue = #1458 depends #1462
----
As I promised to @xumingkuan. Could you take a look? Hope this is helpful.
> [doc] Workflow for writing a Python test for #1462

- python/taichi/misc/gui.py
> [gui] [bug] Fix ti.hex_to_rgb

- python/taichi/lang/ops.py
- tests/python/test_linalg.py
- tests/python/test_ssa.py
Related issue = replace #1439
----
> [Bug] Fix random side-effect causing SSA violation in ti.Vector

- docs/faq.rst
> [doc] Fix typo in faq.rst

- python/taichi/misc/util.py
- python/taichi/testing.py
- taichi/program/program.cpp
Related issue = close #1635
----
> [benchmark] Fix test_test.py benchmark including '<lambda>' in filename

- taichi/codegen/codegen_llvm.cpp
- tests/python/test_struct_for.py
This is just a temporary fix - we should revisit and add more tests after the design of the sparse computation system is fully done.
----
> [bug] [sparse] Fix struct-fors on pointer SNodes

- docs/export_results.rst
- docs/hello.rst
- docs/scalar_tensor.rst
- docs/tensor_matrix.rst
- docs/write_test.rst
----
Some newly added docs didn't catch up with the term change..
> [doc] Fix uncovered while deprecated term 'tensor' occurance

- docs/hello.rst
- examples/ad_gravity.py
- examples/cg_possion.py
- examples/fem128.py
- examples/fem99.py
- examples/fractal.py
- examples/game_of_life.py
- examples/mass_spring_3d.py
- examples/mpm128.py
- examples/mpm88.py
- examples/mpm99.py
- examples/mpm_lagrangian_forces.py
- examples/stable_fluid.py
> [example] [refactor] Upgrade to ti.field syntax for many examples

- docs/vector.rst
> [Doc] Typo and grammatical fixes in vector documentation

- README.md
- examples/tree_gravity.py
Related issue = #1597
----
Preview: https://github.com/archibate/taichi/blob/readme-gallery/README.md
> [misc] Update README.md gallery for the newly added examples during GAMES 201

- tests/python/test_torch_io.py
> [test] Fix Torch IO test

- taichi/backends/metal/api.cpp
- taichi/platform/mac/objc_api.cpp
- taichi/platform/mac/objc_api.h
I guess it will be a lot easier to figure out the failure if we log the errors..
----
> [metal] Log errors if the compute kernel compilation failed

- cmake/TaichiCore.cmake
Related issue = #1644
----
I think it's time for it! Will doc its special features later.
> [CC] Release the C backend on Linux

- python/taichi/lang/ops.py
- python/taichi/lang/shell.py
- python/taichi/lang/transformer.py
- python/taichi/lang/util.py
- python/taichi/misc/util.py
- tests/python/test_linalg.py
> [misc] Rename "fully_deprecated" to "obsolete"

- taichi/backends/cuda/codegen_cuda.cpp
> [cuda] Refactor CUDA kernel launching

- README.md
- misc/examples.md
> [misc] Create misc/examples.md for more examples

- README.md
in LBM ... :Taich to Taichi
----
> [misc] Fix a typo in README.md

- benchmarks/async_cases.py
- benchmarks/benchmark_async.py
- examples/mpm99.py
> [benchmark] [async] Improve AsyncEngine benchmarks

- .github/workflows/persubmit.yml
- .travis.yml
> [workflow] Travis CI only test Python 3.6 unless release tag is used

- docs/compilation.rst
- docs/internal.rst
We should probably standardize the use of terminologies otherwise it's hard to understand each other :-) Please feel free to propose better names. 
> [doc] Document data structure organization

- benchmarks/async_cases.py
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
> [refactor] Rename KernelLaunchRecord to TaskLaunchRecord

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
Mostly a code cleanup. I saw no improvement nor regression on my end...
----
> [refactor] Use promise/future to retrieve the function compiled asynchronously

- benchmarks/async_cases.py
- benchmarks/benchmark_async.py
At least it runs without an error now :-)
----
> [async] [benchmark] Recover autodiff case

- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
> [async] Improve StateFlowGraph

- taichi/backends/cuda/cuda_driver_functions.inc.h
- taichi/program/program.cpp
Related issue = close #1833
A lot of thanks to @littlemine for reporting!
----
> [cuda] Fix CUDA driver API signature

- examples/physarum.py
Code example: A toy model of [Physarum Polycephalum](https://sagejenson.com/physarum).
> [Example] Physarum simulation example

- misc/visualize_state_flow_graph.py
- python/taichi/misc/util.py
- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
Finally the SFG looks correct to me:
----
> [async] Fix missing edges and nodes in SFG

- README.md
> [misc] Update README with SIGGRAPH 2020 Taichi course

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_util.cpp
- taichi/backends/metal/shaders/runtime_kernels.metal.h
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/program/async_engine.cpp
- taichi/program/kernel.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/offload.cpp
> [ir] Add ClearListStmt instead of making clear_list a unique task type

- misc/visualize_state_flow_graph.py
- taichi/ir/ir.h
- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/compile_config.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
- taichi/python/export_lang.cpp
Sorry about the big change. I have to do this to meet a research milestone presentation at MIT (to keep my Ph.D. student status healthy...). I list the items here so that people don't reinvent the wheels. Although there are quite a few different things, each item is not huge:
1. `StateFlowGraph::Node` now has a reference to `TaskMeta` (instead of storing some meta info on its own)
2. List generation elimination (`StateFlowGraph::optimize_listgen`)
3. Dead `ClearListStmt` elimination (`StateFlowGraph::eliminate_dead_store`)
4. Empty task removal (`StateFlowGraph::eliminate_dead_store`)
5. Added `StateFlowGraph::replace_reference`
6. Added `StateFlowGraph::delete_nodes`
7. Added `StateFlowGraph::reid_nodes`
8. Added `StateFlowGraph::topo_sort_nodes`
9. Added …
> [async] Optimizations on StateFlowGraph

- misc/visualize_state_flow_graph.py
- taichi/program/async_engine.cpp
@xumingkuan just in case you need this for making SFG figures...
----
> [Async] Fix ClearListStmt metadata

- docs/debugging.rst
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/offload.cpp
- tests/python/test_serial_execution.py
> [Lang] Support num_thread limitation and serial excution on CPU

- .pylintrc
- Dockerfile
- Jenkinsfile
- docs/dev_install.rst
- python/taichi/main.py
> [cli] Setup pylint: run 'ti lint' to obtain linting results

- CMakeLists.txt
- README.md
- python/LICENSE.txt
Cleaning up some 2016 legacy...
----
> [misc] Update project information

- taichi/backends/metal/shaders/runtime_structs.metal.h
- taichi/backends/metal/shaders/runtime_utils.metal.h
Basically a replica of https://github.com/taichi-dev/taichi/blob/f3fb6d76393633fb463076c1b843eba1b21ad20e/taichi/runtime/llvm/runtime.cpp#L584-L597
Not in use yet, so presumably no risk :)
Related issue = #1174
----
> [metal] Add KernelManagerData in prep for pointer SNode

- taichi/backends/metal/struct_metal.cpp
Trivial change, will merge after CI.
----
> [metal] Fix error message

- examples/mass_spring_3d.py
- python/taichi/lang/kernel.py
Related issue = fix https://github.com/taichi-dev/taichi_three/issues/20
----
We now support smooth shading by interpolation via triangle barycentric coordinates.
> [example] Upgrade mass_spring_3d.py to Taichi THREE v0.0.5

- examples/odop_solar.py
> [example] Update odop_solar

- taichi/backends/cuda/cuda_context.cpp
> [CUDA] Support NVIDIA RTX 3000 series GPUs

- taichi/python/export_lang.cpp
> [misc] Fix compabtility with pybind11 2.6.0

- README.md
- examples/mpm_lagrangian_forces.py
> [misc] Add a link to Chinese video tutorial on Bilibili

- python/taichi/misc/util.py
- taichi/python/export_misc.cpp
- taichi/system/profiler.cpp
- taichi/system/profiler.h
> [misc] Add clear_profile_info()

- examples/mciso_advanced.py
- python/taichi/diagnose.py
----
References: https://www.cnblogs.com/shushen/p/5542131.html
We can even use `taichi_three` for 3D visualization iapr.
Btw, is that possible to avoid re-computing the same vertex shared by four triangles? I.e. skip 'Weld' in Blender?
> [Example] Interpolate vertices for mciso_advanced.py to make it smoother

- taichi/python/export_lang.cpp
> [misc] Fix Type* ownership in Python-scope

- taichi/codegen/codegen_llvm.cpp
- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/transforms/type_check.cpp
- tests/python/test_bit_struct.py
> [type] Refactor bit pointers

- python/taichi/lang/__init__.py
- tests/python/bls_test_template.py
- tests/python/test_bls.py
Related issue = close #2001
----
Hi all,
This is the first time that I have undertaken such a task. Could you please give me some advice?
Thank you!
> [Lang] [refactor] Rename "ti.cache_shared" to "ti.block_local"

- taichi/transforms/alg_simp.cpp
> [opt] Algebraic simplification for sar/shl/shr

- taichi/ir/snode.cpp
- taichi/struct/struct_llvm.cpp
- tests/python/test_struct_for.py
- tests/python/test_struct_for_intermediate.py
> [type] Fix struct-for demotion on bit_struct SNodes

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_data_types.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/opengl_kernel_util.h
- taichi/backends/opengl/shaders/random.glsl.h
- taichi/backends/opengl/struct_opengl.h
- taichi/program/program.h
Related issue = close #1931
----
test_bit_operations now passing on opengl, we can merge #2014 right after this is merged.
> [OpenGL] [refactor] Refactor OpenGL type system to support u32 and u64

- taichi/transforms/type_check.cpp
Related issue = #1905, follow-up of #2028
----
> [type] Refactor bit pointers for SNodeLookupStmt in type check transform

- examples/vortex_rings.py
> [Example] Add vortex_rings.py

- examples/mass_spring_game.py
> [Example] Add mass_spring_game.py

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/common/serialization.h
- taichi/ir/frontend.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/detect_read_only.cpp
- taichi/transforms/insert_scratch_pad.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/lower_ast.cpp
- taichi/transforms/offload.cpp
> [opt] Add an extra demote_atomics pass

- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
This reverts commit af73ddd0008a1954c167e304836d5d337694e31e.
Sorry I messed up the commit message..
----
> Revert "clean up (#2070)"

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/runtime/llvm/runtime.cpp
- taichi/struct/struct_llvm.cpp
- taichi/transforms/make_thread_local.cpp
- taichi/transforms/type_check.cpp
- tests/python/test_custom_float.py
- tests/python/test_custom_type_atomics.py
- tests/python/test_struct_for.py
> [type] Support atomic add on CustomIntType

- taichi/program/async_utils.h
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
> [async] Add customized container for async state to node map (reland #2070)

- python/taichi/lang/transformer.py
- tests/python/test_ndrange.py
Related issue = WeChat group by @Eydcao 
----
> [Lang] Fix ndrange symbol leakage in AST transformer

- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
Related issue = follow up of #2086 
----
> [async] Add bit mask in the SFG node edges container

- misc/benchmark_rebuild_graph.py
- taichi/program/async_engine.h
- taichi/program/state_flow_graph.cpp
- taichi/python/export_lang.cpp
... so that quantitative performance study can be done via `ti.get_runtime().prog.benchmark_rebuild_graph()`.
----
> [misc] Expose "StateFlowGraph::benchmark_rebuild_graph()"

- taichi/program/state_flow_graph.cpp
Related issue = fix #2089 
Rookie mistake x_x
----
> [bug] Fix unsort_edges to use tmp_data

- external/include/catch.hpp
> [test] Upgrade to catch v2.13.3

- python/taichi/core/util.py
- python/taichi/lang/impl.py
- tests/python/test_ptr_assign.py
----
Also add some more information when import failed as oft.
> [Lang] [test] Support dict as expression initializer

- taichi/transforms/type_check.cpp
- tests/python/test_custom_float.py
- tests/python/test_custom_int.py
> [type] Fix implicit cast into custom data types

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_codegen_utils.h
- taichi/program/async_engine.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- tests/python/test_custom_float_exponents.py
Also add `program->config.async_opt_passes` with default value `3`. @xumingkuan not sure if this will change anything on your end regarding fusion.
----
> [misc] Refactor CodeGenLLVM::load_bit_ptr

- taichi/transforms/alg_simp.cpp
> [opt] Algebraic simplification for bit_and with 0

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
> [llvm] Use llvm::AtomicRMWInst::BinOp::FAdd for simplicity

- taichi/codegen/codegen_llvm.cpp
- tests/python/test_bit_struct.py
> [type] Fix struct-for codegen on bit_structs

- python/taichi/main.py
- python/taichi/tools/video.py
- taichi/codegen/codegen_llvm.cpp
> [misc] Add option -c to 'ti video' to specify output quality

- docs/faq.rst
- docs/install.rst
Related issue = #2072
----
FAQs updated in this PR:
* Don't use the name `taichi.py`.
* Use tsinghua mirror if you live in China.
* Always upgrade `pip` for their API breaking change.
* Field creation after materialization not yet.
* Advocate my Taichi-Blend addon as the third solution for Taichi in 3D.
Btw, how is the taichi.graphics translation workflow going on? Will we still update taichi-docs-zh-cn?
> [doc] Troubleshooting circular import

- python/taichi/lang/snode.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/ir/type.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/optimize_bit_struct_stores.cpp
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_shared_exp.py
- tests/python/test_custom_real_shared_exp.py
> [type] Support CustomFloatType with shared exponents

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/ir/type.h
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_shared_exp.py
> [type] More robust CustomFloatType

- taichi/codegen/codegen_llvm.cpp
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_integration.py
- tests/python/test_custom_float_shared_exp.py
- tests/python/test_custom_float_time_integration.py
> [type] More robust CustomFloatType with proper rounding

- python/taichi/lang/matrix.py
- python/taichi/tools/video.py
- taichi/ir/type.cpp
- tests/python/test_custom_float_shared_exp.py
> [misc] Add argument dtype to field.to_numpy()

- taichi/program/program.cpp
- tests/python/test_fp_flush_to_zero.py
> [misc] Force CPU floating-point flush-to-zero (FTZ)

- misc/benchmark_bit_struct_stores.py
- python/taichi/lang/__init__.py
- python/taichi/lang/snode.py
- python/taichi/lang/type_factory.py
- python/taichi/misc/util.py
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/python/export_lang.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/test_type.cpp
- tests/python/test_bit_array.py
- tests/python/test_bit_array_vectorization.py
- tests/python/test_bit_struct.py
- tests/python/test_cast.py
- tests/python/test_cell_size_inspection.py
- tests/python/test_custom_float.py
- tests/python/test_custom_float_exponents.py
- tests/python/test_custom_float_shared_exp.py
- tests/python/test_custom_float_time_integration.py
- tests/python/test_custom_int.py
- tests/python/test_custom_type_atomics.py
- tests/python/test_matrix_different_type.py
- tests/python/test_struct_for.py
> [type] Update custom data type APIs

- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/runtime/llvm/runtime.cpp
Simply allow more trunks for now... Found this issue when debugging the particle renderer.
@TH3CHARLie not sure if this is related to your case though.
----
> [sparse] Make memory allocator more robust

- .github/workflows/release.yml
Related issue = #1989
Let's enable this and see how it goes...
----
> [misc] Enable pypi upload for macOS

- python/taichi/lang/__init__.py
- taichi/analysis/gather_uniquely_accessed_pointers.cpp
- taichi/analysis/same_statements.cpp
- taichi/ir/analysis.h
- taichi/ir/frontend.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.cpp
- taichi/ir/statements.h
- taichi/program/async_utils.cpp
- taichi/program/async_utils.h
- taichi/program/ir_bank.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/whole_kernel_cse.cpp
Also improves `same_value` and `whole_kernel_cse`.
Usage example:
```python
ti.init(arch=ti.cpu, debug=False, async_mode=True, print_preprocessed=False,
print_ir=False)
N = 16
block = ti.root.pointer(ti.i, N)
x = ti.field(ti.i32)
block.place(x)
block2 = ti.root.pointer(ti.i, N)
y = ti.field(ti.i32)
block3 = block2.dense(ti.i, 2)
block3.place(y)
print('x: ', x.snode.id)
print('y: ', y.snode.id)
print('block: ', block.snode.id)
print('block2: ', block2.snode.id)
print('block3: ', block3.snode.id)
@ti.kernel
def test():
for i in x:
p = ti.loop_unique(x[i], covers=block3)  # or ti.loop_unique(x[i], covers=y.parent())
y[p] = i
@ti.kernel
def foo():
x[6] = 3
x[8] = 4
@ti.kernel
def print():
for i in y:
print(i, y[i])
x[0] = 0
x[2] = 1
x[4] = 2
test() …
```
> [async] [lang] [opt] Add ti.loop_unique(covers=...) to improve task dependence analysis

- taichi/program/compile_config.h
- taichi/program/state_flow_graph.cpp
- taichi/python/export_lang.cpp
This allows us to control how many fusions can happen per task.
----
> [async] Add config flag async_max_fuse_per_task

- taichi/program/async_engine.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
> [async] Add option async_opt_fusion_max_iter

- .github/workflows/release.yml
Related issue = #2180
Need to set the necessary env vars: https://github.com/taichi-dev/taichi/runs/1838230678?check_suite_focus=true 
----
> [misc] Fix PyPi upload step with envs

- .github/workflows/persubmit.yml
It seems that for some reason we need to update the display port ID from `:2` to `:1`. This secures the successful creation of the OpenGL context.
----
> [test] Fix GPU testing on zhen

- .gitmodules
> [test] Add googletest as a submodule

- .github/workflows/persubmit.yml
> [test] Enable C++ unit tests on CI

- python/taichi/core/settings.py
- python/taichi/lang/__init__.py
- python/taichi/lang/ast_checker.py
- python/taichi/lang/core.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/ops.py
- python/taichi/lang/runtime_ops.py
- python/taichi/lang/shell.py
- python/taichi/lang/snode.py
- python/taichi/lang/transformer.py
- python/taichi/misc/util.py
> [refactor] Clean up python import statements

- cmake/TaichiTests.cmake
- taichi/ir/ir_builder.cpp
- tests/cpp_new/ir/ir_builder_test.cpp
Related issue = #2225 #2201 #2193
2 minor fixes in 1 PR :)
Reference: https://github.com/google/googletest/blob/master/googletest/README.md
----
> [test] [ir] [bug] Fix googletest on Windows and fix a bug in IR Builder

- docs/internal.rst
- The doc seems to intend to say "do *not*" based on the context.
- correct typo
----
> [Doc] Update doc typo

- docs/install.rst
> [doc] Add installation instructions for Fedora and RHEL

- taichi/analysis/alias_analysis.cpp
- taichi/ir/analysis.h
- tests/cpp_new/analysis/alias_analysis_test.cpp
> [test] [ir] Add tests for the alias_analysis pass

- tests/cpp/ir/algebraic_simplication_test.cpp
Related issue = #2220
IIUC "alg" means algebraic here...
----
> [test] Rename algorithm simplification test to algebraic simp. test

- python/taichi/lang/impl.py
- python/taichi/lang/tape.py
> [refactor] Rename Tape class to TapeImpl

- taichi/analysis/clone.cpp
- taichi/llvm/llvm_context.cpp
Related issue = #2193 #991
A continuation of #2252.
----
> [ir] Remove type_check in clone

- taichi/ir/frontend.h
Related issue = close #2036 
----
> [refactor] Remove legacy C++ frontend macros

- taichi/ir/statements.cpp
- taichi/ir/statements.h
This field was introduced in https://github.com/yuanming-hu/taichi/commit/e64aeb6806b259fc992ed03848484b3fd8cd1a41 in 2019 and it seems unused till now.
----
> [ir] [refactor] Remove OffloadedStmt::step

- taichi/analysis/alias_analysis.cpp
- taichi/analysis/data_source_analysis.cpp
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/metal/codegen_metal.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/statements.inc.h
- taichi/ir/control_flow_graph.cpp
- taichi/ir/statements.h
- taichi/transforms/auto_diff.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/type_check.cpp
"Stack" is a very generic term, so it's better to add "Ad" to denote "AutoDiff" in the statement name.
----
> [ir] [refactor] Rename StackXStmt to AdStackXStmt

- docs/sparse.rst
This part turns out to be very outdated...
----
> [doc] Update sparse computation doc

- docs/hello.rst
Reverts taichi-dev/taichi#2314
> [doc] wrap `for` to avoid confusion (#2314)

- .github/workflows/persubmit.yml
- python/taichi/lang/ops.py
- tests/python/test_rescale.py
Related issue = #2177
Same as the previous one, but CLA should work!
A simple index rescaling API that could be useful once we switch to consecutive indices. #2248
> [lang] Add rescale_index() and test

- taichi/backends/vulkan/data_type_utils.h
- taichi/backends/vulkan/kernel_utils.cpp
- taichi/backends/vulkan/kernel_utils.h
> [vulkan] Add per kernel info structs

- examples/rasterizer.py
A common introductory assignment for computer graphics courses.
Potential improvements:
1. Figure out explicit ways to have the work group size match the tile size so that each work group does not diverge when going through the per tile triangle list
2. Use better culling. Currently it's just a simple bounding box check.
> [example] Colored triangle rasterizer

- taichi/analysis/value_diff.cpp
Related issue = #2327 
test will be in #2327
----
> [IR] Support diffRange bit_shl

- taichi/common/serialization.h
- tests/cpp/common/serialization_test.cpp
> [lang] Support std::optional and enum classes in the serializer

- examples/cornell_box.py
- examples/rasterizer.py
- examples/stable_fluid.py
- python/build.py
- python/taichi/lang/__init__.py
- python/taichi/lang/ops.py
- tests/python/test_callable_template_mapper.py
- tests/python/test_eig.py
Enabled release test by additional flag in build.py.
Other changes are due to python formatter.
@k-ye 
----
> [Misc] Add test flag when releasing taichi

- docs/contributor_guide.rst
- misc/prtags.json
> [misc] Add CI tag

- python/taichi/__init__.py
- python/taichi/aot/__init__.py
- python/taichi/aot/module.py
- python/taichi/lang/kernel_impl.py
- taichi/program/aot_module_builder.cpp
- taichi/program/aot_module_builder.h
- taichi/program/async_engine.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
Related issue = #2355, #1601, #1191,  LAN-3
FYI @BillXu2000 
Possible API usage:
```py
@ti.kernel
def foo():
...
@ti.kernel
def bar_tmpl(a: ti.template(), b: int):
...
foo()
bar_impl()
while True:
foo()
mod = ti.aot.Module()
mod.add_kernel(foo)
mod.add_kernel(bar_tmpl, name='bar_a:True', template_args={'a': True})
mod.save('/path/to/file.tic')  # .tic for "taichi compiled"
```
----
> [lang] Add AOT module interface

- misc/ci_setup.py
> [misc] Remove unnecessary scipy dependency in misc folder

- cmake/TaichiCore.cmake
- misc/prtags.json
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
- taichi/backends/vulkan/vulkan_common.h
Related issue = #2298
This is identical to #2299. (Previously it was merged into `upstream/vulkan`, but the  process is probably easier to merge into `master` directly.) 
----
> [vulkan] Add Vulkan API

- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/metal/aot_module_builder_impl.h
- taichi/backends/metal/codegen_metal.cpp
- taichi/backends/metal/codegen_metal.h
- taichi/backends/metal/kernel_util.h
- taichi/backends/metal/struct_metal.cpp
- taichi/backends/metal/struct_metal.h
- taichi/program/program.cpp
> [metal] Add AOT module builder for metal

- cmake/TaichiCore.cmake
- docs/dev_install.rst
> [Doc] Update developer installation doc regarding LLVM_DIR

- python/taichi/aot/module.py
fix none type error when dumping taichi kernels to metal files
----
> [metal] Fix nonetype error

- docs/gui.rst
> [Doc] Add more documentation regarding fast_gui

- python/build.py
> [CI] Modified build.py to use token for all uploads

- taichi/transforms/type_check.cpp
> [lang] Add override to fix compilation warnings

- examples/mpm_lagrangian_forces.py
> [Bug] Fixed internal lagrangian forces

- cmake/TaichiCore.cmake
- misc/prtags.json
- python/taichi/lang/__init__.py
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/backends/wasm/codegen_wasm.h
- taichi/codegen/codegen.cpp
- taichi/inc/archs.inc.h
- taichi/program/arch.cpp
Related issue = [LAN-43]
[LAN-43]: https://taichi-graphics.atlassian.net/browse/LAN-43
> [wasm] [llvm] Support wasm with single thread

- taichi/ir/snode.h
> [doc] Add documentation for IndexExtractor

- taichi/analysis/alias_analysis.cpp
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/struct/struct.cpp
- taichi/struct/struct.h
- tests/cpp/analysis/alias_analysis_test.cpp
> [IR] Fully deprecate trailing_bits

- taichi/program/async_utils.cpp
[Bug] Fix 'ti.get_addr' failures in async mode.
> [Bug] Fix 'ti.get_addr' failures in async mode

- .github/workflows/presubmit.yml
Related issue = LAN-10
Hopefully this fixes the CI too-slow issue.
> [ci] Trigger Build and Test (CPU) after the required checks

- taichi/runtime/llvm/runtime.cpp
> [CI] Fixed windows build & test

- .github/workflows/presubmit.yml
- python/taichi/diagnose.py
- tests/python/test_indices_assert.py
> [ci] Moved windows build & test to github action

- taichi/analysis/build_cfg.cpp
- taichi/ir/control_flow_graph.h
Hopefully these comments can help others understand how a control-flow graph is built.
----
> [ir] Support BLS in control-flow graph and add docstrings in build_cfg

- taichi/ir/analysis.h
- taichi/ir/control_flow_graph.cpp
- taichi/ir/control_flow_graph.h
> [ir] Add more comments to CFG optimizations and analyses

- taichi/backends/metal/aot_module_builder_impl.h
- taichi/backends/metal/aot_utils.h
- taichi/backends/metal/codegen_metal.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/kernel_utils.cpp
- taichi/backends/metal/kernel_utils.h
- taichi/backends/metal/struct_metal.cpp
> [metal] Separate kernel utils and AOT utils

- tests/python/test_function.py
> [ir] [bug] Skip test_template

- misc/prtags.json
> [misc] Update prtags.json to include aot

- Dockerfile
- Jenkinsfile
- ci/Dockerfile
> [ci] [docker] Build release with docker in ubuntu18.04

- ci/Dockerfile
> [docker] Add twine installation in dockerfile

- taichi/backends/cpu/jit_cpu.cpp
- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/wasm/aot_module_builder_impl.cpp
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/backends/wasm/codegen_wasm.h
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/jit/jit_session.h
- taichi/llvm/llvm_codegen_utils.h
- taichi/program/program.cpp
> [wasm] [aot] Support AOT on webassembly backend.

- taichi/backends/wasm/aot_module_builder_impl.cpp
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/backends/wasm/codegen_wasm.h
> [misc] Fix parameters' type.

- .github/workflows/presubmit.yml
> [ci] Separate Win build and test steps

- ci/Dockerfile
> [ci] Fix docker caching issue

- examples/chi_examples/main.cpp
- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/snode.py
- python/taichi/snode/__init__.py
- python/taichi/snode/fields_builder.py
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/python/snode_registry.cpp
- taichi/python/snode_registry.h
- taichi/runtime/llvm/runtime.cpp
- taichi/struct/snode_tree.cpp
- taichi/struct/snode_tree.h
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/program/test_program.cpp
- tests/cpp/program/test_program.h
- tests/cpp/transforms/alg_simp_test.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
- tests/cpp/transforms/simplify_test.cpp
> [ir] Use SNodeTree to implement root

- taichi/backends/wasm/codegen_wasm.cpp
> [wasm] Recover code

- taichi/backends/opengl/codegen_opengl.cpp
Dump compute shader source code when print_kernel_llvm_ir is true
> [opengl] Dump compute shader source code when print_kernel_llvm_ir is true

- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/wasm/aot_module_builder_impl.cpp
- taichi/system/std_filesystem.h
> [misc] Unify std::filesystem header

- taichi/backends/wasm/codegen_wasm.cpp
- taichi/runtime/llvm/runtime.cpp
Related issue = https://taichi-graphics.atlassian.net/browse/TW-18
> [wasm] Implement materialize() for wasm backend and clean up unused functions

- ci/Dockerfile
> [ci] Fix docker prebuilt binary link

- cmake/TaichiCore.cmake
- python/taichi/lang/__init__.py
- taichi/backends/vulkan/data_type_utils.h
- taichi/backends/vulkan/kernel_utils.cpp
- taichi/backends/vulkan/kernel_utils.h
- taichi/math/arithmetic.h
Related issue = #2298
This should be very similar to Metal's.
> [vulkan] Add kernel metadata and utils

- appveyor.yml
> [ci] Fix appveyor

- python/taichi/lang/snode.py
> [misc] Add needs_grad property for SNode

- python/taichi/lang/impl.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/inc/constants.h
- taichi/inc/statements.inc.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/ir/statements.h
- taichi/program/program.cpp
- taichi/runtime/llvm/runtime.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/scalar_pointer_lowerer.cpp
- tests/python/test_fields_builder.py
- tests/python/test_runtime.py
> [lang] Support ti.FieldsBuilder()

- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/snode/fields_builder.py
- tests/python/test_fields_builder.py
- tests/python/test_tensor_reflection.py
> [lang] Support ti.fields with shape after materialized

- examples/simulation/mpm128.py
- examples/simulation/mpm99.py
- python/taichi/misc/gui.py
> [misc] Added palette in taichi GUI for circles

- taichi/program/kernel.cpp
> [misc] Remove get_current_program() in kernel.cpp

- taichi/runtime/llvm/runtime.cpp
- tests/python/test_reduction.py
> [Bug] Warp reduction bug fix

- taichi/ir/type_utils.cpp
Related issue = probably fix #2522
> [windows] Use %lld as 64-bit integer output format on Windows

- python/taichi/lang/__init__.py
- python/taichi/snode/fields_builder.py
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- tests/python/test_tensor_reflection.py
> [refactor] Move snode tree maintainance out of python

- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
- taichi/ir/frontend_ir.h
- taichi/program/snode_expr_utils.cpp
- taichi/python/export_lang.cpp
- tests/python/test_field.py
> [lang] Add a name parameter to fields

- tests/python/test_mpm_particle_list.py
> [test] [bug] Avoid accessing negative indices

- docs/lang/articles/contribution/contributor_guide.md
> [doc] Fix format command in contributor guide

- taichi/backends/vulkan/snode_struct_compiler.cpp
- taichi/backends/vulkan/snode_struct_compiler.h
- taichi/backends/vulkan/vulkan_utils.cpp
- taichi/backends/vulkan/vulkan_utils.h
* #2549
* **#2548**
Related issue = #2298
> [vulkan] Add Vulkan struct compiler and some helpers

- python/taichi/lang/impl.py
- taichi/python/export_lang.cpp
- tests/python/test_no_grad.py
> [autodiff] Raise no gradient instead of attribute dim not found

- taichi/backends/vulkan/vulkan_simple_memory_pool.cpp
- taichi/backends/vulkan/vulkan_simple_memory_pool.h
> [vulkan] Add a simple memory allocator

- Jenkinsfile
- ci/Dockerfile
> [ci] Allow build specific commit when uploading, used new building procedure.

- python/build.py
> [ci] Quick fix: bugs in upload.py

- CMakeLists.txt
Build issue reported by @strongoier on #2541
> [Bug] Fix racing in llvm bc generation.

- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
> [vulkan] Add Vulkan launcher

- misc/generate_ir_design_doc.py
- python/taichi/core/__init__.py
- python/taichi/core/settings.py
- python/taichi/core/util.py
- python/taichi/main.py
> [refactor] Cleaned taichi/core/settings related import

- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
> [vulkan] Split into managed and reference devices

- cmake/TaichiCore.cmake
- python/taichi/lang/__init__.py
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_utils.cpp
- taichi/backends/vulkan/vulkan_utils.h
- taichi/inc/archs.inc.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_misc.cpp
> [vulkan] Add Vulkan to Taichi

- examples/chi_examples/main.cpp
Update SNode API in CHI example code and fix array of variable length.
> [IR] Update CHI example to match SNode API

- .github/workflows/presubmit.yml
- misc/ci_setup.py
- setup.py
> [ci] Correct windows build and test in CI

- python/taichi/misc/image.py
> [Doc] Add python docstring for misc.image class

- python/taichi/lang/matrix.py
Related issue = #https://github.com/taichi-dev/taichi/issues/2579
> [Doc] Add Python docstring for Matrix class

- python/taichi/lang/ops.py
Related issue = #2579
1. Add Python Docstring in ops.py
> [Doc] Add Python Docstring in ops.py

- appveyor.yml
> [ci] Fix appveyor with new building procedure

- appveyor.yml
> [ci] Fix one tiny bug

- python/taichi/lang/impl.py
> [Refactor] Added axes() function in impl.py

- python/taichi/lang/__init__.py
- python/taichi/lang/expr.py
- python/taichi/lang/linalg.py
> [Docs] Add docs for Expr class and functions in linalg.py

- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_snode_compiler.cpp
- taichi/backends/vulkan/vulkan_utils.h
> [bug] [vulkan] Fix bugs in SPIR-V codegen exposed under Linux

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- python/taichi/lang/util.py
> [Doc] Add Python docstring for functions in matrix.py, impl.py, util.py and ops.py

- python/taichi/misc/gui.py
> [doc] Add python docstring for gui.py

- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/snode.py
> [Doc] Add Python docstrings for several APIs

- python/taichi/lang/common_ops.py
> [Doc] Doc string for common_ops.py

- python/taichi/lang/ops.py
> [Doc] Add Python docstring for some operators

- python/taichi/lang/ops.py
Related issue = #2579 
Fix typo of PR #2586
> [Doc] Fix typo of PR #2586

- python/taichi/misc/util.py
> [Doc] Add python docstring in misc/util.py

- .github/workflows/presubmit.yml
- setup.py
Got a few `clang: error: unable to execute command: Killed`
> [ci] Prevent clang OOM

- .gitmodules
- cmake/TaichiCore.cmake
- taichi/backends/vulkan/spirv_header.h
- taichi/backends/vulkan/vulkan_utils.h
> [vulkan] Add SPIRV-Headers as a submodule

- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
> [vulkan] Detect Vulkan / SPIR-V version & enabling required features

- .gitmodules
- cmake/TaichiCore.cmake
- taichi/backends/vulkan/loader.cpp
- taichi/backends/vulkan/loader.h
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
- taichi/backends/vulkan/vulkan_common.h
- taichi/backends/vulkan/vulkan_simple_memory_pool.h
- taichi/backends/vulkan/vulkan_utils.h
This PR uses [volk](https://github.com/zeux/volk) to dynamically load vulkan functions. This ensures that users who do not have vulkan installed can still use taichi.
> [vulkan] Dynamically load Vulkan

- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
> [vulkan] Move SPIR-V type capabilities into VulkanCapabilities & fix compilation errors

- setup.py
- [Doc] Add docstring for AutoDiff part (#2630) (by **ljcc0930**)
- [vulkan] Move SPIR-V type capabilities into VulkanCapabilities & fix compilation errors (#2628) (by **Yu Chang**)
- [vulkan] Use native struct types when supported & fix performance (#2621) (by **Bob Cao**)
- [vulkan] Dynamically load Vulkan (#2623) (by **Dunfan Lu**)
- [vulkan] Fix vulkan rand (#2622) (by **Dunfan Lu**)
- [benchmark] Add query_kernel_profiler_() and benchmark/misc for performance monitoring (#2601) (by **rocket**)
- [vulkan] Detect Vulkan / SPIR-V version & enabling required features (#2615) (by **Bob Cao**)
- [vulkan] Add SPIRV-Headers as a submodule (#2608) (by **Ye Kuang**)
- [ci] Prevent clang OOM (#2620) (by **Ye Kuang**)
- [IR] Init GlobalTensorElementExpression and PtrOffsetStmt …
> [release] v0.7.28

- .github/workflows/issue_comment.yml
- benchmarks/misc/baseline.py
- benchmarks/misc/run.py
> [ci] Add slash benchmark command for performance monitoring

- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
> [vulkan] Rename ManagedVulkanDevice to EmbeddedVulkanDevice

- .github/workflows/presubmit.yml
Related issue = #2607
This doesn't run vulkan tests, but at least it builds vulkan
TODO:
1. install vulkan on all the self-hosted bots
2. test vulkan in CI
> [vulkan] Build and test Vulkan backend in CI

- .github/workflows/presubmit.yml
Add cuda bin folder to PATH so that we can compiler .cu files.
> [ci] Add cuda bin folder to PATH

- misc/ci_setup.py
> [ci] Enable torch tests during CI

- .github/workflows/release.yml
- ci/Dockerfile
- python/build.py
> [ci] Refined release procedures

- python/taichi/lang/matrix.py
- python/taichi/testing.py
- tests/python/test_constant_func.py
> [Test] Smarter enumerating features and raise exception when not supported

- taichi/ui/backends/vulkan/platform_specific/linux.h
- taichi/ui/backends/vulkan/platform_specific/platform.h
- taichi/ui/backends/vulkan/platform_specific/win.h
- taichi/ui/backends/vulkan/vulkan_cuda_interop.cpp
- taichi/ui/backends/vulkan/vulkan_cuda_interop.h
- taichi/ui/backends/vulkan/vulkan_utils.cpp
- taichi/ui/backends/vulkan/vulkan_utils.h
This is the 4th of a series of PRs that adds a GPU-based GUI to taichi. This PR adds the majority of the Vulkan implementation. This PR mainly utility functions, for creating vulkan objects and for interops.
> [gui] GGUI 4/n: Vulkan GUI backend utils

- python/taichi/core/util.py
- python/taichi/main.py
- taichi/common/core.cpp
- taichi/common/core.h
- taichi/gui/gui.h
- taichi/llvm/llvm_context.cpp
- taichi/python/export_misc.cpp
This PR removes all the logic depending on `is_release` in the codebase. (It already returned True before this PR so it's safe to do so).
> [Refactor] Remove is_release() in the codebase.

- .github/workflows/release.yml
- ci/Dockerfile
- setup.py
Build and release nightly per day!!!
```
PROD_PWD: ${{ secrets.PYPI_PWD_PROD }}
NIGHT_PWD: ${{ secrets.PYPI_PWD_NIGHTLY }}
```
We will need two new secrets in our github repo for these two @k-ye .
> [ci] Added taichi nightly auto release to github action

- taichi/backends/vulkan/runtime.cpp
> [vulkan] Better detect Vulkan availability

- python/taichi/lang/kernel_impl.py
> [Bug] Close the kernel context when failing to compile AST

- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/spirv_ir_builder.cpp
- taichi/backends/vulkan/spirv_ir_builder.h
- tests/python/test_atomic.py
- tests/python/test_local_atomics.py
- tests/python/test_reduction.py
> [vulkan] [test] Support full atomic operations on Vulkan backend

- taichi/program/program.cpp
- taichi/struct/snode_tree.cpp
- taichi/struct/snode_tree.h
> [refactor] [misc] Remove unneccessary constructor argument

- .github/workflows/release.yml
> [ci] Reduce the number of python wheels built nightly

- docs/lang/articles/contribution/dev_install.md
Thanks @yuanming-hu for trying it out!
> [Doc] Fix --user in dev install instruction.

- docs/lang/articles/contribution/dev_install.md
- requirements_dev.txt
Adding a few improvements from installing taichi with Siqi and Libin.
> [Doc] Several dev install doc improvements.

- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- tests/cpp/codegen/refine_coordinates_test.cpp
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* __->__ #2743
* #2742
> [Refactor] Move llvm_context_host to LlvmProgramImpl.

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* __->__ #2744
* #2743
* #2742
> [Refactor] Move llvm_context_device to LlvmProgramImpl.

- taichi/llvm/llvm_program.h
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* __->__ #2745
* #2744
* #2743
* #2742
> [Refactor] Move llvm_runtime to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* __->__ #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move runtime_mem_info into LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* __->__ #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move thread_pool into LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* __->__ #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move preallocated_device_buffer into LlvmProgramImpl.

- taichi/llvm/llvm_program.h
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* __->__ #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move get_llvm_context to LlvmProgramImpl.

- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* __->__ #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move runtime_query to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
* #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* __->__ #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Add get_snode_num_dynamically_allocated to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* #2756
* #2755
* __->__ #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Add maybe_initialize_cuda_llvm_context to LlvmProgramImpl.

- taichi/program/compile_config.h
- taichi/program/program.cpp
* #2759
* #2758
* #2757
* #2756
* __->__ #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move is_cuda_no_unified_memory to CompileConfig.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* #2757
* __->__ #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move clone_struct_compiler_initial_context to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2759
* #2758
* __->__ #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Move initialize_llvm_runtime_snodes to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/struct/struct.h
- taichi/struct/struct_llvm.cpp
- taichi/struct/struct_llvm.h
* #2759
* __->__ #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Add materialize_snode_tree to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/runtime/llvm/runtime.cpp
* __->__ #2759
* #2758
* #2757
* #2756
* #2755
* #2754
* #2753
* #2752
* #2751
* #2750
* #2749
* #2748
* #2747
* #2746
* #2745
* #2744
* #2743
* #2742
> [Refactor] Add initialize_llvm_runtime_system to LlvmProgramImpl.

- taichi/gui/win32.cpp
> [gui] Remove DPI settings

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/snode.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
> [Ir] Clean up frontend ir for global tensor and local tensor

- taichi/backends/cpu/jit_cpu.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_program.h
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
* #2783
* #2782
* #2781
* #2780
* #2779
* #2778
* __->__ #2777
> [Refactor] Cleanup llvm specific apis in program.h

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/system/snode_tree_buffer_manager.cpp
* #2783
* #2782
* #2781
* #2780
* #2779
* __->__ #2778
* #2777
> [Refactor] Move a few helpers in LlvmProgramImpl to private.

- python/build.py
- setup.py
> [ci] Changed nightly tag from pre-release to post-release

- taichi/backends/device.cpp
- taichi/backends/device.h
- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/backends/vulkan/vulkan_api.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/backends/vulkan/vulkan_utils.h
This PR adds API definitions for Graphics device and the vulkan implemention.
credits @bobcao3 who proposed this api and provided the vk impl
> [vulkan] Graphics Device API

- examples/algorithm/laplace.py
- python/taichi/lang/__init__.py
- taichi/backends/vulkan/vulkan_api.cpp
- taichi/program/program.cpp
- tests/python/test_for_break.py
> [Vulkan] [test] Fix Vulkan CI test bug & Enable tests for Vulkan backend

- .github/workflows/presubmit.yml
> [ci] Added gpu test timeout

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2783
* #2782
* #2781
* #2780
* __->__ #2779
> [Refactor] Simplify synchronize and materialize_runtime in Program.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
* #2783
* #2782
* #2781
* __->__ #2780
* #2779
> [Refactor] Move check_runtime_error to LlvmProgramImpl.

- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
* #2783
* #2782
* __->__ #2781
* #2780
* #2779
> [Refactor] Further cleanup Program constructor.

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- tests/cpp/codegen/refine_coordinates_test.cpp
* #2783
* __->__ #2782
* #2781
* #2780
* #2779
> [Refactor] Move llvm_context_host/device to private.

- taichi/llvm/llvm_program.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
* __->__ #2783
* #2782
* #2781
* #2780
* #2779
> [Refactor] Move snode_tree_buffer_manager and llvm_runtime to private.

- taichi/python/export.cpp
- taichi/python/export.h
- taichi/python/export_ggui.cpp
This is the 13th of a series of PRs that adds a GPU-based GUI to taichi.
This PR exports GGUI to python via pybind.
> [gui] GGUI 13/n: Pybind stuff

- taichi/program/program.cpp
- taichi/program/program.h
> [refactor] Minor cleanup in program.cpp.

- .github/workflows/release.yml
> [ci] Fixed bugs of double env in release.yml

- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2839
* #2837
* #2836
* #2835
* #2834
* __->__ #2833
Simply split metal specific bits out of program.cpp for now.
Prepare for refactoring Program class.
> [refactor] Initial MetalProgramImpl implementation.

- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program.h
* #2839
* #2837
* #2836
* #2835
* __->__ #2834
* #2833
> [refactor] Unify compile() for LlvmProgramImpl and MetalProgramImpl.

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/codegen_opengl.h
- taichi/backends/opengl/opengl_kernel_launcher.h
- taichi/backends/opengl/struct_opengl.cpp
- taichi/program/program.cpp
* #2839
* #2837
* #2836
* __->__ #2835
* #2834
* #2833
> [refactor] Decouple opengl codegen compile with Program.

- taichi/program/program.cpp
- taichi/system/memory_pool.cpp
- taichi/system/memory_pool.h
* #2839
* #2837
* __->__ #2836
* #2835
* #2834
* #2833
> [refactor] Decouple MemoryPool with Program.

- taichi/program/async_engine.cpp
- taichi/program/async_engine.h
- taichi/program/program.cpp
- taichi/program/state_flow_graph.cpp
- taichi/program/state_flow_graph.h
* #2839
* __->__ #2837
* #2836
* #2835
* #2834
* #2833
> [refactor] Decouple AsyncEngine with Program.

- taichi/ir/frontend.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/program/callable.h
- taichi/program/function.cpp
- taichi/program/function.h
- taichi/program/kernel.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
* __->__ #2839
* #2837
* #2836
* #2835
* #2834
* #2833
Fixes https://taichi-graphics.atlassian.net/browse/LAN-24
> [refactor] Move FrontendContext from global into Callable class.

- .github/workflows/release.yml
> [ci] Fixed bug of wrong os parameter

- python/taichi/main.py
- python/taichi/testing.py
> [Lang] Fix ti test parameters

- .github/workflows/release.yml
> [ci] M1 release

- python/taichi/lang/ndarray.py
- tests/python/test_mpm88.py
- tests/python/test_ndarray.py
> [Lang] Support fill, from_numpy, to_numpy for ti.ndarray

- .github/workflows/presubmit.yml
Tested on test_actions repo. https://github.com/taichi-dev/test_actions
> [ci] Enable CI on pushing to master.

- taichi/backends/cuda/cuda_context.cpp
- taichi/backends/cuda/cuda_context.h
- taichi/ir/frontend.cpp
- taichi/ir/frontend.h
- taichi/llvm/llvm_program.cpp
- taichi/program/state_flow_graph.cpp
- taichi/python/export_lang.cpp
* #2862
* #2861
* #2860
* __->__ #2859
> [refactor] Get rid of some unnecessary get_current_program().

- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/program/program_impl.cpp
- taichi/program/program_impl.h
* #2862
* #2861
* __->__ #2860
* #2859
> [refactor] Init ProgramImpl from MetalProgramImpl.

- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program_impl.h
- taichi/struct/struct_llvm.cpp
* #2862
* __->__ #2861
* #2860
* #2859
> [refactor] Let LlvmProgramImpl inherit ProgramImpl.

- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
* __->__ #2862
* #2861
* #2860
* #2859
> [refactor] Unify llvm_program_ and metal_program_ in Program class.

- tests/python/test_sfg.py
> [ci] Re-enable sfg test on CUDA

- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
> [Lang] Clean up sparse matrix front-end

- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/program/program.cpp
- taichi/program/program.h
Add a `VulkanProgramImpl` as part of our efforts to cleanup `program.cpp` by making it less backend-dependent.
> [refactor] Vulkan program impl

- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- ci/Dockerfile
- cmake/TaichiCore.cmake
Issue = https://github.com/taichi-dev/taichi/issues/2883
> [ci] Build and Release Vulkan in CI/CD

- python/taichi/ui/camera.py
Fixed an undefined variable in GGUI.
> [gui] GGUI fix undefined variable

- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- cmake/TaichiCore.cmake
- docs/lang/articles/contribution/dev_install.md
> [vulkan] Turn off Vulkan by default and add dev install instructions

- taichi/program/program.cpp
> [wasm] Fix WASM AOT module builder order

- .github/workflows/release.yml
> [ci] Moved linux release to github action

- .github/workflows/release.yml
> [ci] Fix linux release forgot to remove old taichi

- python/taichi/lang/struct.py
- tests/python/test_custom_struct.py
> [bug] Fix the Bug that cannot assign a value to a scalar member in a struct from python scope

- .github/workflows/release.yml
> [ci] Artifact uploading before test in release.yml

- tests/python/test_ad_basics.py
- tests/python/test_clear_all_gradients.py
- tests/python/test_element_wise.py
- tests/python/test_mpm88.py
- tests/python/test_struct.py
Our GPU CI is pretty flaky these days, I happen to see a few failed tests on my linux workstation which I think are pretty relevant. I'm going to disable these first to make sure CI is back to normal state.
> [ci] Disable a few vulkan flaky tests.

- examples/ggui_examples/fractal3d_ggui.py
This is the code for this example:
https://www.bilibili.com/video/BV1pf4y1J7rM?spm_id_from=333.999.0.0
> [example] 3D fratal example

- README.md
> [Doc] Add developer installation to README.md

- taichi/backends/metal/shaders/runtime_utils.metal.h
> [metal] Fix metal codegen to make OSX 10.14 work

- taichi/backends/wasm/codegen_wasm.cpp
- taichi/runtime/llvm/runtime.cpp
> [Lang] Support ti_print for wasm

- README.md
- misc/quantaichi_bibtex.txt
> [doc] Update README.md

- python/taichi/lang/kernel_impl.py
- taichi/program/program.h
- taichi/python/export_lang.cpp
> [refactor] Remove Program::KernelProxy

- misc/spMv_linear_solve.py
- python/taichi/lang/sparse_solver.py
- taichi/program/sparse_matrix.h
- taichi/program/sparse_solver.cpp
- taichi/program/sparse_solver.h
- taichi/python/export_lang.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/2906
> [Lang] Support configure sparse solver ordering
