taichi-dev/taichi

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_device.cpp
- taichi/backends/opengl/opengl_device.h
Related issue = #2736
Adding opengl error checks & improve memory mapping access flags
> [opengl] Device API: Adding GL error checks & correct memory mapping flags

- python/taichi/lang/kernel_impl.py
- python/taichi/tools/patterns.py
- tests/python/test_function.py
> [misc] Throw proper error if real function is not annotated.

- python/taichi/lang/ndarray.py
> [Lang] Add data_handle property to Ndarray

- taichi/backends/device.cpp
- taichi/backends/metal/kernel_manager.cpp
> [misc] Fix some build warnings.

- docs/lang/articles/basic/external.md
- docs/lang/articles/basic/field.md
- docs/lang/articles/basic/type.md
As a first-time user, I am learning Taichi by going through the documents. I found several typos there and fix them in this PR. Please point out if there are any problems with this PR.
> [doc] Fix several typos in doc

- taichi/backends/cc/cc_kernel.h
- taichi/backends/cc/cc_layout.h
- taichi/backends/cc/cc_program.cpp
- taichi/backends/cc/cc_program.h
- taichi/backends/cc/cc_runtime.h
- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/cc/codegen_cc.h
- taichi/backends/cc/struct_cc.cpp
- taichi/backends/cc/struct_cc.h
- taichi/program/program.cpp
- taichi/program/program.h
Related issue = #2736 and #2978
> [refactor] Private field names and function restructure in cc backend.

- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/transforms/extract_constant.cpp
- tests/cpp/transforms/extract_constant_test.cpp
> [Opt] [ir] [refactor] Remove exceptions from IR pass extract_constant

- python/taichi/diagnose.py
> [misc] Add Vulkan as a target for ti diagnose

- docs/lang/articles/contribution/cpp_style.md
- docs/lang/articles/contribution/writing_cpp_tests.md
- taichi/lang_util.cpp
> [Doc] Improve the documentation for C++ style guide

- docs/lang/articles/advanced/layout.md
> [Doc] Update documentation for fields (advanced)

- .github/workflows/release.yml
> [ci] Fix release.yml syntax error

- docs/lang/articles/misc/debugging.md
- docs/lang/articles/misc/ggui.md
> [Doc] Improve the documentation for debugging and GGUI

- docs/lang/articles/advanced/meta.md
> [Doc] Update metaprogramming doc

- docs/lang/articles/advanced/sparse.md
- examples/features/sparse/explicit_activation.py
- examples/features/sparse/taichi_sparse.py
- examples/features/sparse/tutorial.py
- python/taichi/lang/ops.py
- taichi/backends/cpu/cpu_device.h
- taichi/backends/cuda/cuda_device.h
> [Doc] Add documentation for sparse computation

- docs/lang/articles/advanced/meta.md
> [Doc] Fix note format on webpage and code highlights for metaprogramming

- docs/lang/articles/basic/external.md
> [Doc] Update interacting with external arrays

- docs/lang/articles/basic/field.md
> [Doc] Update field

- python/taichi/core/primitive_types.py
- python/taichi/lang/__init__.py
> [Doc] Add docstring for init(), reset() and a few constants

- setup.py
> [misc] Version bump: v0.8.0->v0.8.1

- python/taichi/lang/impl.py
- tests/python/test_non_taichi_types_in_kernel.py
> [Lang] [bug] Fix subscripting user classes in Taichi kernels

- docs/lang/articles/contribution/cpp_style.md
> [Doc] Update cpp_style.md

- docs/lang/articles/basic/syntax.md
> [Doc] Update kernels and functions

- docs/lang/articles/contribution/dev_install.md
> [Doc] Fix Arch Linux building guide clang dependence

- docs/lang/articles/misc/profiler.md
> [Doc] Improve the documentation for profiler

- .github/workflows/presubmit.yml
> [ci] Try fixing windows.

- .github/workflows/presubmit.yml
> [ci] Extend windows timeout.

- docs/lang/articles/contribution/dev_install.md
> [Doc] Update developer installation

- .github/workflows/presubmit.yml
* #3076
* #3075
* #3074
* #3073
* #3072
* __->__ #3079
> [ci] Try moving all torch tests to single thread.

- docs/lang/articles/misc/export_kernels.md
- misc/demo_record_kernel_group.py
- python/taichi/aot/__init__.py
- python/taichi/aot/record.py
- python/taichi/core/__init__.py
- tests/python/test_aot.py
* #3076
* #3075
* #3074
* __->__ #3073
* #3072
* #3079
> [refactor] Move record.py out of ti.core.

- CMakeLists.txt
- cmake/TaichiTests.cmake
- taichi/struct/snode_tree.cpp
- taichi/struct/snode_tree.h
- tests/cpp/struct/snode_tree_test.cpp
Related issue = #3018
Adding this helper to make it easier for us to implement multi-root support
> [lang] Add a method to get all SNodes under a root

- python/taichi/misc/gui.py
[GUI] move the type cast of the environment variable in misc.gui.gui to a function
> [GUI] Extract the type casts of environment variables in misc.gui.gui into a reusable function

- README.md
> [doc] Add Vulkan into README.md

- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/get-started.md
We tried this on @rexwangcc 's M1 + macos11 laptop and it works. :D
> [Doc] Update dev install about m1.

- taichi/backends/opengl/opengl_device.cpp
> [opengl] Fix OpenGL device buffer fill command

- python/taichi/aot/module.py
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/program/aot_module_builder.h
- taichi/program/program.cpp
- taichi/program/program.h
* __->__ #3329
* #3328
I've tested this manually but haven't figured out a good way to put this
in the tests yet, e.g. not sure how to force generate code containing a
macro. Suggestions are welcome!
> [OpenGl] Support preprocessing glsl code in aot.

- docs/lang/articles/get-started.md
> [Doc] Fix the broken get-started page.

- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/opengl/opengl_program.cpp
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
Related issue = https://github.com/taichi-dev/taichi/issues/3298
> [opengl] Expose allow_nv_shader_extension in compileconfig.

- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- .github/workflows/scripts/unix_docker_build.sh
> [CI] Linux CD containerization

- .github/workflows/postsubmit.yml
> [ci] Set GITHUB_CONTEXT for performance monitoring

- python/taichi/lang/ir_builder.py
- tests/python/test_ast_refactor.py
> [refactor] Add compare to the new python frontend ast builder

- python/taichi/lang/ir_builder.py
- tests/python/test_ast_refactor.py
> [Refactor] Python frontend refactor: build_call part, support format print and fstring

- python/taichi/ui/window.py
- taichi/backends/device.h
- taichi/backends/vulkan/embedded_device.cpp
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/python/export_ggui.cpp
- taichi/ui/backends/vulkan/app_context.cpp
- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/swap_chain.cpp
- taichi/ui/backends/vulkan/window.cpp
- taichi/ui/common/app_config.h
- taichi/ui/common/window_base.cpp
This PR enables headlessly running GGUI. I tested it by sshing into my remote linux machine and running a ggui example within the ssh session.
There is a small bug: IMGUI widgets are not shown in the output images when running in headless mode. I will investigate this.
We can now begin to add tests, and I will submit another PR soon to update the docs to include this feature.
> [gui] Headless GGUI

- taichi/ui/backends/vulkan/gui.cpp
> [gui] Fix IMGUI when GGUI is running in headless mode

- python/taichi/aot/module.py
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/program/aot_module_builder.h
- taichi/python/export_lang.cpp
- tests/python/test_aot.py
> [opengl] Remove kernel preprocessing

- taichi/backends/cuda/codegen_cuda.cpp
> [cuda] Perf: Use the min between saturation grid dim and const range-for dim

- taichi/program/kernel.cpp
* __->__ #3384
* #3374
* #3373
> [refactor] Remove handling for real types in set_arg_int.

- python/taichi/lang/util.py
- tests/python/test_f16.py
* #3384
* __->__ #3374
* #3373
> [Lang] Fp16 interacts with pytorch.

- python/taichi/aot/module.py
- python/taichi/snode/fields_builder.py
- taichi/backends/metal/aot_module_builder_impl.cpp
- taichi/backends/metal/aot_module_builder_impl.h
- taichi/backends/metal/kernel_utils.h
- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/backends/opengl/aot_module_builder_impl.cpp
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/wasm/aot_module_builder_impl.cpp
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/program/aot_module_builder.cpp
- taichi/program/aot_module_builder.h
This PR stores the memory offset of each field within the root buffer.
> [metal] Add mem_offset_in_parent to AOT module

- examples/simulation/inital_value_problem.py
Example of gradients. Added an example
> [example] Create inital_value_problem.py

- docs/lang/articles/misc/ggui.md
https://github.com/taichi-dev/taichi/blob/1a19f97883d6fbafdb11c2ece22e251c8b614983/python/taichi/ui/canvas.py#L16
> [Doc] Fix an API typo in GGUI doc

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
Signed-off-by: knight42 <anonymousknight96@gmail.com>
Fixes #3378 
/cc @ailzhang
> [Refactor] Move the cuda codegen part of atan2/pow to codegen_cuda.cpp

- python/taichi/lang/ir_builder.py
- tests/python/test_ast_refactor.py
> [refactor] Add SparseMatrixBuilder and any_array support in kernel argument in the new AST builder

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/document.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
> [misc] Add new issues templates

- taichi/backends/vulkan/codegen_vulkan.cpp
- tests/python/test_f16.py
> [vulkan] Fix non 32bit element external array  & enable f16 tests

- docs/lang/articles/contribution/dev_install.md
> [Doc] Update dev install about m1 prebuilt llvm.

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/llvm/llvm_codegen_utils.h
- taichi/transforms/type_check.cpp
> [Refactor] Use wrapped create_call

- .github/workflows/presubmit.yml
- .github/workflows/title_check.yml
> [CI] Recheck the title format when user updates the title

- docs/lang/articles/misc/gui.md
> [Doc] Update gui.md: comprehend widgets example

- taichi/runtime/llvm/atomic.h
> [Refactor] Simplify runtime function definition

- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
Let's try aws machine with the required cpu test first!
> [ci] Move required cpu check to AWS machine

- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
> [ci] Fix aws machine not removing container

- taichi/backends/cuda/codegen_cuda.cpp
> [LLVM] Fix link

- taichi/ir/frontend_ir.cpp
- tests/python/test_grouped.py
- tests/python/test_mpm88.py
- tests/python/test_tensor_dimensionality.py
> [IR] Add type inference for loop variables

- CMakeLists.txt
> [misc] Version bump: v0.8.4->v0.8.5.

- setup.py
Another version bump to make sure our master branch is always on next release.
> [misc] Version bump: v0.8.5->v0.8.6.

- taichi/common/serialization.h
- tests/python/test_aot.py
Also added mpm88 in aot tests.
> [misc] Remove regex in TextSerializer.

- .github/workflows/presubmit.yml
Failing on master branch, temporarily disable it to unblock other PRs
> [misc] Temporarily disable clang-tidy check.

- misc/code_format.py
- python/taichi/lang/__init__.py
- python/taichi/lang/expr_builder.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_ast_refactor.py
- tests/python/test_expr_dict.py
- tests/python/test_ggui.py
- tests/python/test_lang.py
- tests/python/test_scope_errors.py
- tests/python/test_type_check.py
- tests/python38/test_ast_refactor.py
> [refactor] [bug] Eliminate failing tests on the new AST builder

- .github/workflows/presubmit.yml
- python/taichi/lang/expr_builder.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/stmt_builder.py
- python/taichi/ui/canvas.py
- python/taichi/ui/gui.py
- python/taichi/ui/ui.py
- python/taichi/ui/window.py
> [Lang] Fix pylint rule W0401

- docs/lang/articles/contribution/contributor_guide.md
> [doc] Remove ti format in doc.

- .github/workflows/presubmit.yml
- python/taichi/aot/module.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/ops.py
- python/taichi/lang/shell.py
- python/taichi/lang/snode.py
- python/taichi/lang/source_builder.py
- python/taichi/lang/struct.py
- python/taichi/lang/types.py
- python/taichi/main.py
- python/taichi/misc/error.py
- python/taichi/snode/fields_builder.py
- python/taichi/snode/snode_tree.py
- python/taichi/tools/np2ply.py
- python/taichi/ui/camera.py
- python/taichi/ui/canvas.py
- python/taichi/ui/gui.py
- python/taichi/ui/scene.py
- python/taichi/ui/staging_buffer.py
- python/taichi/ui/ui.py
- python/taichi/ui/utils.py
- python/taichi/ui/window.py
> [Lang] Fix pylint rule W0611

- .github/workflows/presubmit.yml
- python/taichi/lang/kernel_impl.py
- python/taichi/misc/gui.py
> [Lang] Fix pylint rule W0201

- docs/lang/articles/contribution/dev_install.md
> [Doc] Fix wrong example about TAICHI_CMAKE_ARGS

- .github/workflows/presubmit.yml
- python/taichi/__init__.py
> [Lang] Fix pylint rule R0402

- .github/workflows/presubmit.yml
- python/taichi/lang/__init__.py
- python/taichi/lang/ast/transformer.py
- python/taichi/lang/ast_builder_utils.py
> [Lang] Fix pylint rule R0205

- .github/workflows/presubmit.yml
- python/taichi/lang/ast/checkers.py
- python/taichi/lang/stmt_builder.py
> [Lang] Fix pylint rule R1703

- .github/workflows/presubmit.yml
- python/taichi/misc/util.py
> [Lang] Fix pylint rule R1732

- .github/workflows/presubmit.yml
- python/taichi/lang/ast/checkers.py
- python/taichi/lang/common_ops.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/main.py
- python/taichi/misc/gui.py
- python/taichi/profiler/kernelprofiler.py
Signed-off-by: Alex Chi <iskyzh@gmail.com>
Related issue = #3151
> [Lang] Fix pylint rule R0201

- .github/workflows/presubmit.yml
- python/taichi/lang/ast/checkers.py
- python/taichi/lang/snode.py
I noticed that one of the two codes that needed to be fixed has a  `TODO`,
so I just commented on the code after `return` instead of delete
> [Lang] Fix pylint rule W0101

- .github/workflows/presubmit.yml
- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
> [Lang] Fix pylint rule W0404

- .github/workflows/presubmit.yml
- python/taichi/lang/__init__.py
- python/taichi/lang/ast/transformer.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_impl.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/main.py
- python/taichi/profiler/kernelprofiler.py
- scripts/generate_pylint_tags.py
> [Lang] Fix pylint rule R1710

- .github/workflows/presubmit.yml
- python/taichi/__init__.py
- python/taichi/lang/__init__.py
- python/taichi/lang/ast/transformer.py
- python/taichi/lang/ast_builder_utils.py
- python/taichi/lang/field.py
- python/taichi/lang/impl.py
- python/taichi/lang/ir_builder.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/meta.py
- python/taichi/lang/ops.py
- python/taichi/lang/quant_impl.py
- python/taichi/lang/stmt_builder.py
- python/taichi/lang/tape.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/main.py
- python/taichi/misc/gui.py
- python/taichi/misc/util.py
- python/taichi/profiler/kernelmetrics.py
- python/taichi/tools/np2ply.py
- python/taichi/tools/video.py
- scripts/generate_pylint_tags.py
- tests/python/test_bit_struct.py
- tests/python/test_custom_float.py
> [Lang] Fix pylint rule W0622

- .github/workflows/presubmit.yml
- python/taichi/lang/ast/checkers.py
- python/taichi/lang/snode.py
Related issue  #3151. This is a PR to add W0101 rule for the pylint.
> [Lang] Add W0101 rule for pylint

- .github/workflows/release.yml
> [ci] Minor fix for windows release upload.

- .github/workflows/scripts/unix_build.sh
> [vulkan] Update unix_build.sh to install molten

- CONTRIBUTING.md
> [doc] Create CONTRIBUTING.md

- .github/workflows/release.yml
> [ci] Fix release action now being able to be triggered manually

- cmake/TaichiCore.cmake
Add a TI_WITH_METAL option, defaulted to true, so that one can optionally disable building for metal.
> [metal] Add a TI_WITH_METAL option

- .github/workflows/presubmit.yml
1. Separate pylint from check_code_format.
2. Merge pylint and clang-tidy into check_static_analyzer.
> [misc] Reorg CI stages

- taichi/program/program.cpp
- taichi/program/program.h
The fallback-related code in C++ is broken and deprecated, so we should remove it.
> [bug] Remove fallback in C++ code

- python/taichi/lang/kernel_impl.py
- tests/python/test_aot.py
- tests/python/test_ast_refactor.py
- tests/python/test_get_external_tensor_shape.py
- tests/python/test_mpm88.py
- tests/python/test_ndarray.py
- tests/python/test_type_check.py
> [lang] Limit torch based ndarray to cpu/cuda backend.

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
- python/taichi/lang/meta.py
- tests/python/test_ndarray.py
> [Lang] [bug] Fix numpy from and to ndarray matrix

- python/taichi/lang/__init__.py
> [misc] Fix redefined reset function (#3227)

- .github/workflows/release.yml
- misc/save_new_version.py
- python/build.py
- python/taichi/lang/matrix.py
- requirements_dev.txt
In release.yml, we will automatically update version database in every production release. We will need to add two new secrets to the repository though.
> [CI] Add version database update in CD

- taichi/codegen/codegen_llvm.cpp
- tests/python/test_f16.py
> [LLVM] Fix casting f64 to f16

- .github/workflows/postsubmit.yml
Related issue = Postsubmit check of last PR
> [ci] Fix postsubmit mac build failure

- .github/workflows/postsubmit.yml
- .github/workflows/release.yml
> [bug] Fix missing tests/ folder in postsubmit & release workflows.

- .github/workflows/release.yml
> [ci] Turn off vulkan build on macos

- python/taichi/lang/kernel_impl.py
> [perf] Add async_mode restriction to ti.sync() of external_arrays in class Kernel

- .github/workflows/release.yml
- misc/upload_release.py
> [ci] Fix release

- setup.py
> [misc] Version bump: v0.8.6 -> v0.8.7

- tests/python/test_ndarray.py
> [Test] Temporarily disable flaky test

- misc/upload_release.py
> [misc] Fix upload release error handling

- python/taichi/lang/ir_builder.py
- tests/python/test_ast_refactor.py
> [bug] Enable reassignment of scalar arguments

- .github/workflows/release.yml
- taichi/backends/device.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/backends/vulkan/window.cpp
> [gui] Fix vulkan glfw image count

- .github/workflows/scripts/unix_build.sh
> [ci] Fix unix build script for nightly build

- python/taichi/lang/__init__.py
> [misc] Do not let check_version block users

- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- taichi/python/export_misc.cpp
- taichi/system/hacked_signal_handler.cpp
- taichi/system/hacked_signal_handler.h
Related issue = #3165
FYI @Renkai, sorry for taking over your work in #3197. This feature is kind of urgent for us :)
> [lang] Disable signal handlers when TI_DISABLE_SIGNAL_HANDLERS=1

- .github/workflows/presubmit.yml
> [bug] Revert part of #3569 so that tests are not skipped.

- taichi/ui/backends/vulkan/renderer.cpp
- taichi/ui/common/scene_base.h
Respect drawing order specified by user.
> [gui] Respect drawing order specified by user

- taichi/backends/opengl/codegen_opengl.cpp
* #3623
* __->__ #3622
* #3621
Now that we've made `data` buf optional in opengl backend, we should
also optionally add its atomicAdd/Sub/Max/Min functions.
This PR also adds the atomicAdd/Sub/Max/Min_arr<i>_f32 etc functions for arr bufs.
> [bug] [opengl] Only add atomicAdd functions in generated code for arrs when they're used.

- .github/workflows/scripts/unix_docker_build.sh
Related issue = #3617
Apply the same fix to the docker build script to fix a failure of nightly release
> [ci] Fix build script for docker build

- python/taichi/tools/file.py
> [refactor] Get rid of tools/file.py

- python/taichi/lang/__init__.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/exception.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_assert.py
- tests/python/test_ast_refactor.py
- tests/python/test_exception.py
- tests/python/test_for_group_mismatch.py
- tests/python/test_function.py
- tests/python/test_nested_kernel_error.py
- tests/python/test_no_grad.py
- tests/python/test_numpy.py
- tests/python/test_return.py
- tests/python/test_static.py
- tests/python/test_syntax_errors.py
- tests/python/test_tuple_assign.py
- tests/python/test_type_check.py
> [error] Add line number and source code to exception

- python/taichi/lang/kernel_impl.py
- taichi/common/exceptions.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/ir.h
- taichi/ir/ir_modified.h
- taichi/ir/state_machine.cpp
- taichi/lang_util.h
- taichi/python/export_lang.cpp
- taichi/python/py_exception_translator.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/python/test_type_check.py
> [error] Let type_check throw TypeError

- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/contribution/style_guide_en.md
Massive changes made to improve user friendliness of the installation guide.
Related issue = https://github.com/taichi-dev/taichi/issues/3550
cc: @tisonkun @skyzh
> [Doc] Restructured dev_install.md and added one technical documentation style guide

- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/contribution/style_guide_en.md
- python/taichi/lang/kernel_impl.py
> [bug] Fix postsubmit

- .github/workflows/testing.yml
> [ci] Run code format check for doc-only changes as well.

- .github/workflows/cancel.yml
Related issue = 
Fix #2908 
Fix #3663
> [ci] Set token in cancel workfow

- python/taichi/misc/__init__.py
- python/taichi/tools/__init__.py
- python/taichi/tools/image.py
- python/taichi/tools/video.py
> [refactor] Move image.py from misc/ to tools/ and remove it from top level package

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_utils.h
- taichi/backends/vulkan/codegen_vulkan.cpp
- taichi/backends/vulkan/codegen_vulkan.h
- taichi/backends/vulkan/kernel_utils.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
> [Vulkan] Add initial support of AOT

- .github/workflows/cancel.yml
> [ci] Fix cancel workflow to only cancel the same branch

- python/taichi/lang/__init__.py
> [misc] Handle outermost error and change metadata server address to latest

- python/taichi/lang/kernel_impl.py
- python/taichi/type/annotations.py
- tests/python/test_ndarray.py
* #3692
* #3691
* #3690
* #3689
* #3688
* __->__ #3687
> [Lang] Add optional element_shapes & field_dim annotation to ndarray.

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
* __->__ #3692
* #3691
* #3690
* #3689
* #3688
* #3687
> [refactor] [opengl] Properly save both scalar args and array args.

- .github/workflows/scripts/unix_docker_build.sh
- .github/workflows/testing.yml
Related issue = fixes #3682
This PR aims to take over #3680, but I need to do some debugging first.
> [ci] Run cpp tests in unix_docker_test.sh

- CONTRIBUTING.md
- README.md
- docs/lang/articles/contribution/dev_install.md
> [doc] Improve the dev install doc

- .github/workflows/release.yml
The path needs fix since the root has changed.
> [ci] Fix the script path in release workflow

- python/taichi/examples/simulation/euler.py
Raise the performance by reducing the unnecessary checks in ``if`` condition.
Related issue = close #3714
> [Perf] Reduce the unnecessary codes

- misc/save_new_version.py
- misc/upload_release.py
- python/taichi/lang/__init__.py
> [misc] Error handle and TLS

- .github/workflows/release.yml
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
- python/taichi/lang/__init__.py
Let version check be able to be disabled.
> [misc] Add an option to skip version check

- python/taichi/__init__.py
- python/taichi/aot/module.py
- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
- python/taichi/lang/meta.py
- python/taichi/lang/struct.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/linalg/sparse_solver.py
- python/taichi/type/__init__.py
- python/taichi/types/__init__.py
- python/taichi/types/annotations.py
- python/taichi/types/compound_types.py
- python/taichi/types/primitive_types.py
- python/taichi/ui/scene.py
- python/taichi/ui/staging_buffer.py
* #3727
* **#3726**
This PR does two things:
1. Merge taichi.lang.types into taichi.type.
2. Rename taichi.type to taichi.types.
> [refactor] Merge taichi.lang.types into taichi.types.

- setup.py
> [misc] Version bump: v0.8.7 -> v0.8.8

- docs/lang/articles/basic/syntax.md
`Functions` should be a level 2 heading just like `Kernels`.
> [Doc] Fix a heading level in syntax.md

- taichi/backends/opengl/opengl_api.h
> [opengl] Do not serialize ext_arr_access in AOT

- .github/workflows/performance_monitoring.yml
> [ci] Update performance monitoring

- docs/lang/articles/contribution/dev_install.md
`Set-ExecutionPolicy RemoteSigned` did not work out. Used `Set-ExecutionPolicy RemoteSigned` instead.
> [Doc] Update dev_install.md

- python/taichi/ad.py
- python/taichi/lang/__init__.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/ops.py
- python/taichi/main.py
- python/taichi/profiler/kernelprofiler.py
- python/taichi/ui/staging_buffer.py
- scripts/generate_pylint_tags.py
> [Lang] Fix pylint rule W1309 (f-string-without-interpolation)

- tests/python/test_ndarray.py
Let's try to enable these tests, I can no longer reproduce the flaky behavior locally.
> [test] Enable ndarray tests

- python/taichi/ui/staging_buffer.py
fixes #3765 
This bug was introduced when we added support for transparency.
> [gui] Fix ggui canvas.set_image

- docs/lang/articles/misc/gui.md
PS: The examples here are not enough to make people understand.
> [Doc] Fix a misspelling

- python/taichi/ui/gui.py
> [GUI] Fix gui.text crash bug

- taichi/jit/jit_session.cpp
- taichi/jit/jit_session.h
- taichi/llvm/llvm_context.cpp
- taichi/struct/struct_llvm.cpp
> [refactor] Remove get_type_size() from JITSession

- python/taichi/lang/meta.py
Fixes #3675
And thus fixes cornell_box.py
> [gui] Fix vector to fast image

- python/taichi/linalg/sparse_solver.py
- taichi/program/sparse_solver.cpp
- taichi/program/sparse_solver.h
- tests/python/test_sparse_linear_solver.py
> [Lang] Support sparse solver datatype configuration

- docs/lang/articles/contribution/contributor_guide.md
One section shy of completion: which is the "file a good pr" section.
> [Doc] Refactored contribution guidelines

- setup.py
Building taichi from source on master failed in my workstation, this PR should fix it
> [bug] Create core folder if it doesn't exist.

- taichi/program/ndarray.h
- taichi/program/ndarray_rw_accessors_bank.cpp
- taichi/program/ndarray_rw_accessors_bank.h
- taichi/program/program.cpp
- tests/python/test_ndarray.py
Context can be found in the code comments ;)
> [bug] Use NdarrayRwKeys for ndarray host reader & writer caching.

- taichi/backends/opengl/codegen_opengl.cpp
> [bug] Fix typo in opengl codegen.

- README.md
> [docs] Update README.md to include command to install nightly.

- taichi/backends/opengl/aot_data.h
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_utils.h
- taichi/codegen/spirv/kernel_utils.h
- taichi/program/aot_module_builder.h
This is the first step to unify aot related data structures (when applicable).
> [refactor] Move CompiledFieldData to aot namespace.

- benchmarks/async_advection.py
- benchmarks/async_cases.py
- benchmarks/misc/membound.py
- benchmarks/misc/run.py
- benchmarks/misc/utils.py
- benchmarks/run.py
- benchmarks/utils.py
> [misc] [bug] Fix legacy benchmarks/run.py

- python/taichi/aot/module.py
Example layout is broken for now: https://api-docs.taichi.graphics/autoapi/taichi/aot/module/index.html
> [Doc] Tweak API docstrings

- taichi/backends/metal/aot_module_builder_impl.h
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_module_builder_impl.cpp
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.h
- taichi/backends/vulkan/aot_utils.h
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_program.h
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/program/aot_module.cpp
- taichi/program/aot_module.h
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/python/export_lang.cpp
> [Vulkan] Update AOT Loader support to new API

- docs/lang/articles/contribution/contributor_guide.md
Miscellaneous editorial updates.
> [doc] Editorial updates to contributor_guide.md

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_ast_refactor.py
> [bug] Fix static grouped for

- cmake/TaichiCXXFlags.cmake
Emergency fix, seems to be coming from a merge problem
> [build] Fix TaichiCXXFlags.cmake

- python/taichi/lang/kernel_impl.py
> [refactor] Remove import taichi in kernel_impl.py

- README.md
> [misc] Fix postsubmit status in README.md by replacing it with publishing checks

- setup.py
> [misc] Version bump: v0.8.8 -> v0.8.9

- taichi/backends/opengl/opengl_api.cpp
* #3835
* __->__ #3834
* #3833
* #3832
For ndarray based mpm88 we now only sync when we plot on GUI, which is
after 500 substeps in my benchmark. This PR improves from 13.01fps to
16.67fps.
> [opengl] Only sync per ti.kernel when there's external array arg.

- taichi/common/logging.cpp
> [Misc] [android] Support logging on Android platforms

- python/taichi/_funcs.py
- python/taichi/lang/matrix.py
> [refactor] Remove import taichi in matrix.py

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_basics.py
Fixing the first case in #3802.
> [bug] Fix autodiff for ceil.

- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_kernel_launcher.h
> [refactor] Enforce destruction order of OpenGlRuntime.

- taichi/analysis/verify.cpp
> [autodiff] Provide stmt name for auto-diff related assert info

- python/taichi/lang/struct.py
> [refactor] Remove import taichi from struct.py

- python/taichi/lang/mesh.py
> [refactor] Remove import taichi from mesh.py

- python/taichi/lang/field.py
> [refactor] Remove import taichi from field.py

- python/taichi/lang/expr.py
> [refactor] Remove import taichi from expr.py

- taichi/llvm/llvm_program.cpp
> [cuda] Hide debug info

- cmake/TaichiTests.cmake
- tests/cpp/aot/aot_save_load_test.cpp
Only test the basic feature as the API is still under development. Just
make sure we can serialize and de-serialize the data properly for the
kernels.
Related issue = #3642
> [Test][aot] Add initial AOT CPP test

- taichi/backends/opengl/codegen_opengl.cpp
* #3884
* __->__ #3883
Note this change doesn't show any improvemance on desktop (likely due to
caching), but it improves perf on android (a snapdragon device which
might not have L1 cache) from 100ms per
frame to 75ms per frame.  Thanks to @Leonz5288 for profiling!
> [opengl] Reduce repeated read to args buffer.

- python/taichi/lang/util.py
* #3895
* #3894
* #3893
* #3892
* **#3891**
> [refactor] Remove import taichi in taichi/lang/util.py

- python/taichi/lang/quant_impl.py
* #3895
* #3894
* #3893
* **#3892**
* #3891
> [refactor] Remove import taichi in taichi/lang/quant_impl.py

- cmake/TaichiTests.cmake
- tests/cpp/aot/aot_save_load_test.cpp
Only test the basic feature as the API is still under development. Just
make sure we can serialize and de-serialize the data properly for the
kernels.
Related issue = #3642
> [Test] [aot] Add initial AOT CPP test (#3850)

- taichi/backends/opengl/codegen_opengl.cpp
- tests/python/test_aot.py
> [opengl] Respect max_block_dim in ti.init

- docs/lang/articles/contribution/development_tips.md
- docs/lang/articles/misc/global_settings.md
- python/taichi/lang/__init__.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/ast/transform.py
- python/taichi/lang/impl.py
- tests/python/test_global_store_grad.py
- tests/python/test_runtime.py
> [Refactor] Remove all occurrences of print_preprocessed and print_ast

- python/taichi/ui/camera.py
> [gui] Update camera.py

- docs/lang/articles/misc/ggui.md
It seems this is what supposed to be.
> Add example of color_edit_3

- taichi/transforms/lower_ast.cpp
> [opt] [ir] [refactor] Remove exceptions from lower_ast pass

- docs/lang/articles/contribution/contributor_guide.md
- docs/lang/articles/tutorials/_category_.json
- docs/lang/articles/tutorials/ndarray_android.md
> [doc] Add a tutorial: Run Ndarray Taichi program

- taichi/llvm/llvm_program.cpp
> [Bug] [cuda] Query device attribute when using cuda 11 and above

- taichi/gui/gui.h
> [bug] Fix path for font file

- setup.py
> [misc] Version bump: v0.8.9 -> v0.8.10

- python/taichi/lang/__init__.py
- python/taichi/lang/_ndarray.py
- python/taichi/lang/kernel_impl.py
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
Avoid query from pybind to save some host overhead.
> [refactor] Remove ndarray_use_torch from pybind

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_bool_op.py
> [refactor] Support static short circuit bool operations

- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_assign.py
> [refactor] Get global vars by using __globals__

- taichi/aot/module_data.h
- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_api.cpp
- taichi/backends/opengl/opengl_api.h
- taichi/common/serialization.h
- taichi/ir/offloaded_task_type.h
- taichi/program/aot_module.h
Related issue = https://github.com/taichi-dev/taichi/issues/3334
> [aot] Add task_type for OpenGL

- python/taichi/lang/__init__.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/exception.py
- taichi/python/export_lang.cpp
- tests/python/test_type_check.py
> [Error] Add TaichiTypeError

- .github/workflows/issue_comment.yml
> [ci] Support rebase and rerun command in comment for CI bot

- python/taichi/linalg/sparse_matrix.py
- tests/python/test_sparse_matrix.py
> [Lang] Provide sparse matrix shape

- taichi/backends/opengl/codegen_opengl.cpp
* __->__ #3980
* #3979
Reduced p2g shader from 658 lines to 514 lines.
> [refactor] [opengl] Get rid of some no-ops in linear seek

- docs/lang/articles/advanced/meta.md
- docs/lang/articles/basic/syntax.md
> [doc] Add doc for compile-time recursion

- .github/workflows/release.yml
- .github/workflows/testing.yml
> [ci] Keep macOS actions run on macOS-10.15

- misc/generate_example_videos.py
- python/taichi/examples/simulation/mpm99.py
- tests/python/examples/simulation/test_mpm99.py
Related issue = #3580
This PR serves as a sample of adding tests and video generators for examples involving GUI following the guidelines in #3580. A script for running all video generators is added by the way.
> [test] [example] Add a test and a video generator for mpm99

- taichi/ui/backends/vulkan/swap_chain.cpp
> [gui] GGUI imwrite BGRA to RGBA conversion

- docs/lang/articles/basic/external.md
- docs/lang/articles/basic/operation.md
- docs/lang/articles/basic/operator.md
Move the supported operations content out of the type system to a new page. Also add supported matrices operations from old docs. 
related issue #3318
> [doc] Add an operation page

- taichi/codegen/spirv/spirv_ir_builder.cpp
Also can we have a SPIR-V tag?
> [vulkan] Fix gtmp type

- python/taichi/examples/rendering/cornell_box.py
- tests/python/examples/rendering/test_cornell_box.py
Related issue = https://github.com/taichi-dev/taichi/issues/3580
> [test] [example] Add test and video generator for cornell box.

- setup.py
> [misc] Version bump: v0.8.10 -> v0.8.11

- python/taichi/lang/kernel_impl.py
- taichi/codegen/spirv/spirv_ir_builder.cpp
> [Lang] [bug] Stop misusing non-template argument types to determine template reinstantiation

- taichi/transforms/auto_diff.cpp
- taichi/transforms/reverse_segments.cpp
- tests/python/test_ad_for.py
> [autodiff] Fix the local allocas defining in inner loop raising runtime error

- docs/lang/articles/basic/type.md
This PR focuses on refactoring the "primitive types" section of the type system doc. Updates to the "compound types" section will be done in a future PR.
> [doc] Refactor type system doc: primitive types

- python/taichi/lang/_ndrange.py
- tests/python/test_ndrange.py
> [bug] Fix ndrange with star arguments

- taichi/program/program.cpp
- taichi/program/program.h
> [refactor] Reuse SNode tree id

- python/taichi/lang/ast/ast_transformer.py
> [bug] Fix warnings on external functions on windows

- python/taichi/examples/autodiff/minimization.py
- tests/python/examples/autodiff/test_minimization.py
> [test] Add a test for the minimization example

- benchmarks/microbenchmarks/_items.py
- benchmarks/microbenchmarks/_metric.py
- benchmarks/microbenchmarks/_plan.py
- benchmarks/microbenchmarks/_result.py
- benchmarks/microbenchmarks/_utils.py
- benchmarks/microbenchmarks/fill.py
> [misc] Add containers and end-to-end result to micro-benchmarks

- setup.py
> [misc] Version bump: v0.8.11 -> v0.8.12

- python/taichi/_testing.py
- tests/python/test_test.py
* #4114
* #4113
* __->__ #4112
* #4111
Related: #3782
This is internal testing utility.
> [test] Remove get_rel_eps() at top level.

- misc/test_poly_timed.py
- python/taichi/_testing.py
- tests/python/test_ad_atomic.py
- tests/python/test_ad_basics.py
- tests/python/test_ast_refactor.py
- tests/python/test_atomic.py
- tests/python/test_expr_dict.py
- tests/python/test_expr_list.py
- tests/python/test_f16.py
- tests/python/test_image_io.py
- tests/python/test_linalg.py
- tests/python/test_matrix.py
- tests/python/test_mpm88.py
- tests/python/test_random.py
- tests/python/test_return.py
- tests/python/test_sfg.py
- tests/python/test_sparse_linear_solver.py
- tests/python/test_ssa.py
- tests/python/test_svd.py
- tests/python/test_test.py
* #4114
* __->__ #4113
* #4112
* #4111
Related: #3782
`approx` is an internal testing utility.
> [test] Remove approx at top level.

- python/taichi/_testing.py
- tests/python/test_bit_operations.py
- tests/python/test_element_wise.py
- tests/python/test_scalar_op.py
- tests/python/test_test.py
* __->__ #4114
* #4113
* #4112
* #4111
Related: #3782
This is an internal testing utility.
> [test] Remove allclose at top level.

- tests/python/examples/autodiff/test_minimization.py
Fixing broken master.
#3782 didn't catch this since it was on an older master base
commit.
> [ci] Fix approx in autodiff example test

- python/taichi/_logging.py
- python/taichi/main.py
- tests/python/test_runtime.py
- tests/run_tests.py
related #3782 
These are internal logging utilities.
> [refactor] Remove critical/debug/error/trace/warn/info/is_logging_effective from top level

- python/taichi/__init__.py
> [Refactor] Do not expose main to users

- python/taichi/lang/__init__.py
> [Refactor] Do not expose TapeImpl to users

- python/taichi/lang/ops.py
> [refactor] Expose ti.abs and ti.pow

- .github/workflows/testing.yml
Group by issue number instead of head ref
> [ci] Fix concurrent run issue

- python/taichi/tools/util.py
- python/taichi/ui/gui.py
- tests/python/test_mpm88.py
This PR serves as the first step towards putting functions under `tools.util` in correct places.
> [Refactor] Move core_vec(i) to gui and hide

- python/taichi/lang/__init__.py
- python/taichi/lang/runtime_ops.py
- python/taichi/lang/snode.py
> [Refactor] Expose runtime/snode ops properly

- python/taichi/lang/__init__.py
> [Refactor] Remove inspect for modules in lang init

- python/taichi/examples/rendering/taichi_logo.py
- tests/python/examples/rendering/test_taichi_logo.py
> [test] [example] Add a test for taichi_logo example

- python/taichi/lang/misc.py
- tests/python/test_bit_array_vectorization.py
> [refactor] Remove bit_vectorize from top level.

- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/python/export_lang.cpp
> [refactor] Remove dependency on get_current_program() in lang::Ndarray

- python/taichi/lang/__init__.py
> [refactor] Remove locale_encode from top level.

- python/taichi/_version_check.py
- python/taichi/lang/misc.py
> [refactor] Move version_check out of taichi.lang.

- python/taichi/types/__init__.py
- python/taichi/types/primitive_types.py
- python/taichi/types/utils.py
> [refactor] Remove is_signed/is_integral from top level.

- README.md
[Taichi] version 0.8.11, llvm 10.0.0, commit 9d0973e5, osx, python 3.9.5
When I tried to run taichi with the demo in the readme, I found that the demo code in the readme has not been updated for a long time, and this code does not work in the current version.
After prompting I found the code for fractal.py, which is updated in the readme.
> [doc] Update demo code in readme doc

- taichi/backends/dx/dx_info_queue.cpp
This pull request fixes a very small error that prevented building ..
> [dx11] Fix parse_reference_count signature

- docs/lang/articles/advanced/differentiable_programming.md
The PR focuses on refactoring of the `kernel simplicity rule` (KSR) part due to that the KSR has been removed recently by #4041 #3897  .
> [doc] Update the doc for differentiable programming

- taichi/system/traceback.cpp
> [javascript] Disable stack trace logging when TI_EMSCRIPTENED (JS 9/n)

- python/taichi/lang/ast/ast_transformer_utils.py
- tests/python/test_exception.py
> [Error] Add function name to traceback

- python/taichi/lang/__init__.py
- python/taichi/lang/source_builder.py
- python/taichi/lang/struct.py
- tests/python/test_external_func.py
> [Refactor] Do not expose StructField and SourceBuilder to users

- python/taichi/_snode/fields_builder.py
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/program/snode_expr_utils.cpp
- taichi/program/snode_expr_utils.h
- taichi/python/export_lang.cpp
- taichi/python/snode_registry.cpp
- taichi/python/snode_registry.h
> [refactor] Remove dependency on get_current_program() in exported functions of SNode

- netlify.toml
Worked locally, testing on this PR first
> [misc] Test unified doc & api preview.

- taichi/backends/vulkan/aot_module_loader_impl.h
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_device_creator.h
- taichi/common/core.h
- taichi/common/logging.h
- taichi/common/platform_macros.h
- taichi/gui/gui.h
- taichi/ir/type.h
- taichi/program/compile_config.h
- taichi/system/memory_pool.h
- taichi/system/timer.h
- taichi/ui/backends/vulkan/app_context.h
- taichi/ui/backends/vulkan/canvas.h
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/backends/vulkan/renderer.h
- taichi/ui/backends/vulkan/swap_chain.h
> [misc] Export visibility of symbols required for Vulkan AOT execution

- .github/workflows/release.yml
* Ensure release workflow does not run on forks
* Polish the script that sets the matrix
> [CI] Update release workflow

- python/taichi/__init__.py
- python/taichi/tools/__init__.py
- python/taichi/tools/cc_compose.py
- python/taichi/tools/diagnose.py
- python/taichi/tools/image.py
- python/taichi/tools/np2ply.py
- python/taichi/tools/video.py
Docs should be modified accordingly after next release.
> [Refactor] Move public APIs of ti.tools outside top level

- docs/lang/articles/contribution/contributor_guide.md
> [doc] Add instruction to install clang-format-10 on M1 Mac

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/program/function.cpp
- taichi/program/kernel.cpp
- taichi/python/export_lang.cpp
> [refactor] Remove dependency on get_current_program() in lang::FrontendForStmt

- python/taichi/lang/__init__.py
> [Refactor] Avoid exposing ti.tape

- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/backends/vulkan/vulkan_device_creator.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/codegen/spirv/spirv_ir_builder.h
> [vulkan] Disable buffer device address if int64 is not supported

- python/taichi/lang/exception.py
- taichi/common/exceptions.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- tests/python/test_syntax_errors.py
> [Error] Raise an error when breaking the outermost for

- python/taichi/lang/impl.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/misc.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/tools/async_utils.py
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/ui/backends/vulkan/renderable.cpp
> [refactor] Remove get_current_program() and global variable current_program

- setup.py
We plan to do our next release as v0.9.0 so let's make sure master has
the correct version.
> [misc] Update master version to 0.9.0

- .github/workflows/pull_request.yml
> [ci] Run on pull_request_target to access the secrets

- python/taichi/lang/misc.py
- tests/python/test_mesh.py
> [lang] Expose mesh_patch_idx at top level

- taichi/backends/cc/codegen_cc.cpp
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/jit/jit_module.h
- taichi/system/snode_tree_buffer_manager.h
> [misc] Remove some unnecessary #include lines

- python/taichi/lang/__init__.py
- python/taichi/lang/_ndarray.py
- python/taichi/lang/field.py
- python/taichi/lang/matrix.py
- python/taichi/lang/snode.py
- python/taichi/lang/struct.py
Users need to know these classes in order to query usages.
> [refactor] Re-expose important implementation classes

- python/taichi/lang/kernel_impl.py
- python/taichi/types/annotations.py
> [doc] Hide unnessary methods in annotation classes

- python/taichi/aot/record.py
> [lang] Only expose start_recording/stop_recording for now

- python/taichi/lang/kernel_impl.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/linalg/sparse_solver.py
> [lang] Hide get_addr and type_assert in api docs

- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
- python/taichi/lang/struct.py
- python/taichi/types/__init__.py
- python/taichi/types/compound_types.py
> [lang] Remove CompoundType from taichi.types

- python/taichi/lang/_ndarray.py
> [lang] Hide data_handle in Ndarray

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
> [lang] Hide fill_by_kernel in Ndarray

- python/taichi/lang/_ndarray.py
- tests/python/test_ndarray.py
> [lang] Hide get_element_size and get_nelement in Ndarray

- python/taichi/lang/_ndarray.py
> [lang] Hide initialize_host_accessor in Ndarray

- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
- python/taichi/lang/ops.py
- python/taichi/lang/struct.py
- python/taichi/lang/util.py
> [lang] Hide internal functions in Matrix and Struct

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
> [lang] Hide ndarray_from_numpy and ndarray_matrix_from_numpy

- python/taichi/lang/any_array.py
- python/taichi/lang/field.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/mesh.py
- python/taichi/lang/snode.py
- python/taichi/lang/struct.py
- tests/python/test_field.py
- tests/python/test_gc.py
- tests/python/test_indices.py
- tests/python/test_packed_size.py
- tests/python/test_snode_layout_inspection.py
- tests/python/test_tensor_reflection.py
> [lang] Hide internal functions in SNode and _Root

- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
> [lang] Hide pad_key and ndarray*_to_numpy in Ndarray

- taichi/backends/vulkan/runtime.cpp
- taichi/backends/vulkan/runtime.h
- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- taichi/codegen/spirv/spirv_ir_builder.cpp
... and removed an unnecessary barrier
> [vulkan] Reduce runtime host overhead

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
Related issue = https://github.com/taichi-dev/taichi/pull/4254#discussion_r807970030
> [refactor] Refactor ForLoopDecoratorRecorder

- python/taichi/__init__.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_impl.py
- python/taichi/linalg/__init__.py
- python/taichi/linalg/sparse_matrix.py
- python/taichi/types/annotations.py
- tests/python/test_ast_refactor.py
- tests/python/test_sparse_linear_solver.py
- tests/python/test_sparse_matrix.py
- tests/python/test_spmv.py
> [lang] Move sparse_matrix_builder from taichi.linalg to taichi.types

- python/taichi/lang/_ndarray.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/misc.py
- python/taichi/lang/util.py
- tests/python/test_ndarray.py
Related issue = #3988 
tests merge will be followed by a separate PR.
> [refactor] Remove Ndarray torch implementation and tests

- python/taichi/lang/common_ops.py
> [lang] Remove logical_and and logical_or from TaichiOperation

- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
- requirements_test.txt
> [ci] Install requirements and matplotlib for GPU tests

- python/taichi/examples/autodiff/regression.py
- tests/python/examples/autodiff/test_regression.py
- tests/test_utils.py
Related issue = #3580
Add some ut about regression. I observed the values output at each point as well as the original values, and it looks like you can't do simple addition or subtraction less than the threshold. Considering that this is the ut of EXAMPLE, I have directly output the image here to indicate whether it is working properly
> [test] Add a test for autodiff/regression

- python/taichi/__init__.py
- python/taichi/lang/common_ops.py
- python/taichi/lang/misc.py
> [error] Let deprecation warnings display only once

- taichi/backends/opengl/codegen_opengl.cpp
- taichi/backends/opengl/opengl_data_types.h
- taichi/backends/opengl/struct_opengl.cpp
> [opengl] Remove support for dynamic snode

- python/taichi/examples/ggui_examples/fem128_ggui.py
- python/taichi/examples/ggui_examples/fractal3d_ggui.py
- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
- python/taichi/examples/ggui_examples/mass_spring_game_ggui.py
- python/taichi/examples/ggui_examples/mpm128_ggui.py
- python/taichi/examples/ggui_examples/mpm3d_ggui.py
- python/taichi/examples/ggui_examples/stable_fluid_ggui.py
> [gui] Update GGUI examples to use vulkan backend if available

- python/taichi/examples/autodiff/simple_derivative.py
- tests/python/examples/autodiff/test_simple_derivative.py
Related issue = #3580
like ut about autodiff/regression, this is also a UT that outputs images directly
> [test] Add a test for simple_derivative example

- setup.py
> [misc] Version bump: v0.9.0->v0.9.1

- docs/lang/api/index.md
- docs/lang/articles/advanced/_category_.json
- docs/lang/articles/basic/_category_.json
- docs/lang/articles/contribution/_category_.json
- docs/lang/articles/get-started/_category_.json
- docs/lang/articles/get-started/get-started.md
- docs/lang/articles/get-started/index.md
- docs/lang/articles/gui/_category_.json
- docs/lang/articles/gui/ggui.md
- docs/lang/articles/gui/gui.md
- docs/lang/articles/misc/_category_.json
- docs/lang/articles/tutorials/_category_.json
Preview: https://deploy-preview-4360--docsite-preview.netlify.app/
> [Doc] Re-structure the articles: getting-started, gui

- docs/lang/articles/misc/export_results.md
Related issue = https://github.com/taichi-dev/taichi/pull/4360
> [Doc] Fix broken links

- python/taichi/examples/simulation/nbody.py
- tests/python/examples/simulation/test_nbody.py
> [test] Add a test for the nbody example

- python/taichi/examples/simulation/game_of_life.py
- tests/python/examples/simulation/test_game_of_life.py
> [test] Add a test for the game_of_life example

- python/taichi/examples/algorithm/print_offset.py
- tests/python/examples/algorithm/test_print_offset.py
> [test] [example] Add a test for print_offset example

- taichi/aot/module_builder.cpp
- taichi/aot/module_builder.h
- taichi/aot/module_loader.h
- taichi/backends/metal/aot_module_builder_impl.h
- taichi/backends/opengl/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_module_builder_impl.h
- taichi/backends/vulkan/aot_module_loader_impl.h
- taichi/backends/vulkan/aot_utils.h
- taichi/backends/wasm/aot_module_builder_impl.h
- taichi/program/program.h
- taichi/program/program_impl.h
> [refactor] Move aot_module files

- python/taichi/lang/mesh.py
Related issue = #3608
Make it possible to construct mesh directly from data in memory.
> [mesh] Constructing mesh from data in memory

- .github/workflows/performance_monitoring.yml
- .github/workflows/testing.yml
> [CI] Disable serveral workflows on forks

- misc/tag_to_project.json
Keep the tag_to_project mappings up to date
> [ci] Update tag to projects json

- cmake/TaichiCore.cmake
- taichi/common/symbol_version.cpp
Related issue = #4395
This corresponds to option [c] of #4395.
> [build] Enforce compatibility with manylinux2014 when TI_WITH_VULKAN=OFF

- .github/workflows/testing.yml
> [CI] Cleanup workspace before window test

- python/taichi/examples/simulation/ad_gravity.py
- tests/python/examples/simulation/test_ad_gravity.py
> [test] Add a test for the ad_gravity example

- taichi/backends/vulkan/aot_module_builder_impl.cpp
- tests/python/test_aot.py
> [vulkan] Support templated kernel in aot module

- python/taichi/lang/kernel_impl.py
> [Error] Remove the mentioning of ti.pyfunc in the error message

- taichi/backends/device.h
- taichi/backends/metal/device.cpp
- taichi/backends/metal/device.h
- taichi/platform/mac/objc_api.h
Just adding the code, nobody is using it yet.
> [metal] Add Unified Device API skeleton code

- taichi/ir/frontend_ir.h
Related issue = #4032 
I forgot to remove it
> [misc] Remove a unnecessary function

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/impl.py
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/transforms/compile_to_offloads.cpp
- tests/python/test_function.py
Related issue = #602
New TODOs:
1. Determine which passes real functions need.
2. (Maybe) let the function body be a serial offloaded statement to enable optimization passes
3. CFG dies when there are recursions. (Recursion works when we turn off CFG)
> [llvm] Support real function which has scalar arguments

- taichi/ir/frontend_ir.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_loops.py
Related issue = close #4324, close #4238
> [bug] [lang] Enable break in the outermost for not in the outermost scope

- taichi/aot/module_loader.h
- taichi/backends/cuda/cupti_toolkit.cpp
- taichi/backends/cuda/cupti_toolkit.h
- taichi/backends/vulkan/runtime.h
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/ir/statements.cpp
- taichi/jit/jit_session.cpp
- taichi/program/ndarray.cpp
- taichi/transforms/make_mesh_block_local.cpp
- taichi/transforms/offload.cpp
- tests/cpp/aot/aot_save_load_test.cpp
- tests/cpp/transforms/extract_constant_test.cpp
> [misc] Remove some warnings

- python/taichi/_version_check.py
This file was broken due to silent error handling...
Fixed bug and optimized code.
> [misc] Optimize verison check

- taichi/common/exceptions.h
- taichi/ir/snode.cpp
- taichi/python/export_lang.cpp
- tests/python/test_field.py
> [Error] Add error for invalid snode size

- .github/workflows/release.yml
Prepare and test for official release.
> [ci] Add python 3.10 into nightly test and release

- taichi/backends/cpu/cpu_device.h
- taichi/backends/cuda/cuda_caching_allocator.cpp
- taichi/backends/cuda/cuda_caching_allocator.h
- taichi/backends/cuda/cuda_device.h
- taichi/backends/device.cpp
- taichi/backends/device.h
- taichi/llvm/llvm_device.cpp
- taichi/llvm/llvm_device.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
> [refactor] Remove LLVM logic from the generic Device interface

- .github/workflows/release.yml
Prepare for python 3.10 release.
> [ci] Update gpu docker image to test python 3.10

- tests/python/test_function.py
> [test] Add test for recursive real function

- docs/lang/articles/basic/syntax.md
> [Doc] Refactored Kernels and functions.

- taichi/backends/dx/dx_api.h
> [build] Guard dx lib search with TI_WITH_DX11

- .github/workflows/release.yml
- misc/ci_create_pr_card.py
Related issue = https://github.com/taichi-dev/taichi/pull/4428#issuecomment-1064685365
> [ci] Fix the taichi repo name by hardcode

- docs/lang/articles/basic/syntax.md
> [Doc] Minor updates: It is recommended to type hint arguments and return values

- taichi/common/core.cpp
- tests/python/test_runtime.py
> [misc] [linux] Implement XDG Base Directory support

- taichi/analysis/mesh_bls_analyzer.cpp
> [lang] Quick fix for mesh_local analyzer

- python/taichi/lang/kernel_impl.py
- tests/python/test_function.py
> [bug] [lang] Cast the arguments of real function to the desired types

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_for.py
Related issue = #3003
Current autodiff only handles multiple IBs between outermost loops (parallel loops). 
This PR aims to support handling **multiple**, **mixed** IBs within **multi-levels** serial for-loops.
| Cases  | Before  | After |
| ------------- | ------------- | ------------- |
| 1 | ❌   | ✅  |
| 2 | ✅ | ✅ |
| 3 | ✅ | ✅  |
| 4 | ✅  | ✅  |
| 5 | ❌ | ✅  |
| 6 | ✅  | ✅  |
| 7 | ❌  | ✅  |
Here are some examples:
- Multiple IBs with same nested for-loop (Multiple)
```py
for j in range(2):
for i in range(3):
y[None] += x[None]
for i in range(3):
y[None] += x[None]
```
- Multiple IBs with multi-level nested for-loop (Multiple + Multi-level)
```py
for j in range(2):
for i in range(3):
y[None] += x[None]
for i in range(3):
for ii in range(2):
y[None] += x[None]
for i in range(3):
for ii …
```
> [autodiff] Handle multiple, mixed Independent Blocks (IBs) within multi-levels serial for-loops

- python/taichi/_version_check.py
> [misc] Metadata update

- docs/lang/articles/basic/syntax.md
Minor. Cut straight to the point.
> [Doc] Update syntax.md

- python/taichi/aot/module.py
> [refactor] Fix error message

- docs/lang/articles/contribution/writing_cpp_tests.md
- taichi/ir/ir.h
- taichi/lang_util.cpp
- tests/cpp/ir/ir_test.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/4442
> [ir] Add basic tests for Block

- taichi/ir/ir.h
- taichi/ir/snode.h
- taichi/program/async_utils.h
- taichi/program/program.cpp
- taichi/program/program.h
> [misc] Reset counters in Program::finalize()

- CODE_OF_CONDUCT.md
This documents can help create a positive social atmosphere for Taichi community.
> [Doc] Create CODE_OF_CONDUCT

- README.md
The current readme is packed with a bit more details than is required (for example IDE for Windows) but also several references shy of completion. A README should also serve as a hub of information for the community. In that sense, I updated this document to improve scannability and reduce redundancy that the extra details entail. 
If I were given more time, I would consider building a *separate* GitHub repo for hosting these miscellaneous demos. For now we have way too many and, in this doc, we only *cobbled together* these demos. Offtopic: please bear with me.. We have scores of sub-repos under taichi-dev. We could consider sorting out the relationship of these repos. For example, we have a community repo, but it is rarely used. Is this repo international?
> [Doc] Refactored README.md

- taichi/aot/module_loader.cpp
- taichi/aot/module_loader.h
- taichi/backends/metal/aot_module_loader_impl.cpp
- taichi/backends/vulkan/aot_module_loader_impl.cpp
> [aot] Add KernelTemplate interface

- README.md
H1 + H2 cause too many transverse lines. I propose H2 + H3. Your call!
BTW, in technical documents, we also use *italic* to indicate results of steps.
> [Doc] Format updates

- tests/python/test_offline_cache.py
> [test] Add test for offline-cache

- taichi/transforms/demote_mesh_statements.cpp
- taichi/transforms/make_mesh_block_local.cpp
- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/renderer.cpp
> [misc] Fix a few warnings

- docs/lang/articles/basic/differences_between_taichi_and_python_programs.md
> [Doc] Update differences_between_taichi_and_python_programs.md

- ci/scripts/release_test.sh
> [ci] Release script add test for tests/python/examples

- taichi/llvm/llvm_program.cpp
> [bug] Fix bug that caching kernels with same AST will fail

- .github/workflows/release.yml
https://github.com/taichi-dev/taichi/runs/5639141807?check_suite_focus=true
/home/runner/work/_temp/6624e82b-57db-4b24-8b1c-5d3cdf43fdbb.sh: line 1: [: !-z: unary operator expected
> [ci] Fix release script bug

- python/taichi/__init__.py
> [lang] Fix py36 block_dim bug

- python/taichi/__init__.py
> [lang] Replace keywords in python

- README.md
- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/get-started/index.md
- docs/lang/articles/misc/install.md
Related issue = #3985
v0.9.2 has been released with Python 3.10 support. In this PR we update the docs and finalize the steps for Taichi Python 3.10 support.
> [Doc] Update with Python 3.10 support

- taichi/ui/backends/vulkan/renderables/particles.cpp
- taichi/ui/backends/vulkan/renderables/particles.h
> [gui] Make GGUI VBO configurable for particles

- docs/lang/articles/reference.md
Related issue = #4602
This PR sets up the basic architecture of the specification, and includes the content of the preface, the "Introduction" section, and the "Values and types" subsection of the "Basic concepts" section.
> [Doc] Set up the basis of Taichi specification

- taichi/backends/metal/api.cpp
- taichi/backends/metal/api.h
- taichi/backends/metal/device.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/platform/mac/objc_api.h
> [metal] Implement buffer_fill for unified device API

- taichi/ui/backends/vulkan/renderables/set_image.cpp
> [gui] [aot] Allow set_image to use user VBO

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/snode.py
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
> [refactor] Refactor Identifier::id_counter to global and local counter

- docs/lang/articles/advanced/performance.md
- python/taichi/lang/misc.py
Related issue = https://github.com/taichi-dev/taichi/pull/4525#discussion_r826655410
> [doc] Add docstring for ti.loop_config

- taichi/backends/vulkan/vulkan_device_creator.cpp
> [vulkan] Fixes the string comparison when querying extensions

- docs/lang/articles/reference.md
> [Doc] Taichi spec: variables and scope; atoms; names; literals

- docs/lang/articles/basic/field.md
> [Doc] Updated definition of a 0D field.

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_return.py
> [bug] Fix void return

- docs/lang/articles/advanced/sparse.md
> [doc] Editorial updates

- docs/lang/articles/basic/overview.md
> [Doc] Fix gif link

- tests/python/test_offline_cache.py
> [bug] Fix bugs in test_offline_cache.py

- python/taichi/lang/_ndrange.py
- tests/python/test_ndrange.py
> [bug] Fix ndrange when start > end

- python/taichi/_version_check.py
> [misc] Update linux version name

- docs/lang/articles/gui/gui_system.md
> [Doc] Refactored GUI.md

- docs/lang/articles/reference.md
> [doc] Taichi spec: pass, return, break, and continue

- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
> [misc] Add compile-config to offline-cache key

- docs/lang/articles/reference.md
> [Doc] Taichi spec: prims, attributes, subscriptions, slicings

- docs/lang/articles/gui/ggui.md
> [doc] Proofread GGUI.md

- LICENSE
change License from MIT to Apache after the vote
Related issue = close #4607
> [Docs] Change License from MIT to Apache-2.0

- taichi/ui/backends/vulkan/renderable.cpp
- taichi/ui/backends/vulkan/renderables/mesh.cpp
- taichi/ui/backends/vulkan/renderables/mesh.h
> [gui] Make GGUI VBO configurable for mesh

- cmake/TaichiCore.cmake
> [build] Fix non x64 linux builds

- taichi/backends/device.h
- taichi/backends/metal/device.cpp
- taichi/backends/metal/device.h
- taichi/backends/metal/kernel_manager.cpp
- taichi/backends/metal/kernel_manager.h
- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
> [metal] Tweak Device to support Ndarray

- docs/lang/articles/faq.md
- docs/lang/articles/misc/export_results.md
- python/taichi/examples/algorithm/marching_squares.py
- python/taichi/examples/algorithm/mciso_advanced.py
- python/taichi/examples/algorithm/mgpcg_advanced.py
- python/taichi/examples/features/gui/gui_image_io.py
- python/taichi/examples/features/io/export_mesh.py
- python/taichi/examples/features/io/export_ply.py
- python/taichi/examples/features/io/export_videos.py
- python/taichi/examples/simulation/mpm3d.py
- python/taichi/tools/image.py
- tests/python/examples/algorithm/test_print_offset.py
- tests/python/examples/rendering/test_cornell_box.py
- tests/python/examples/rendering/test_taichi_logo.py
- tests/python/examples/simulation/test_mpm99.py
- tests/python/test_ggui.py
This is a follow-up PR of #4218.
> [doc] Fix deprecated tools APIs in docs, tests, and examples

- docs/lang/articles/reference.md
> [Doc] Taichi spec: assignment expressions

- docs/lang/articles/reference.md
> [Doc] Taichi spec: static expressions

- taichi/backends/vulkan/vulkan_device.cpp
> [Android] Fix Android get height issue

- python/taichi/aot/module.py
- tests/python/test_aot.py
> [Aot] Support template args in AOT module add_kernel

- taichi/backends/device.h
- taichi/backends/vulkan/vulkan_device.cpp
> [lang] Add PolygonMode enum for rasterizer

- .github/workflows/release.yml
Fix the wrong multi-line format
> [ci] Fix ci nightly

- docs/lang/articles/reference.md
> [Doc] Taichi spec: conditional expressions and simple statements

- README.md
> [Doc] Fixed a broken link.

- docs/rfcs/20220410-rfc-process.md
- docs/rfcs/yyyymmdd-rfc-template.md
> [Doc] Propose the RFC process

- CONTRIBUTING.md
- README.md
Related PR = #4701 
Related PR = #4564 
Code of conduct and license both belong to the community standard. This PR update statements in contributing and readme.
> [Doc] Update community standard

- docs/lang/articles/reference.md
> [doc] Taichi spec: calls, unary ops, binary ops and comparison

- python/taichi/examples/features/sparse/taichi_dynamic.py
> [example] Fix taichi_dynamic example

- taichi/ui/backends/vulkan/vertex.h
> [gui] Expose VboHelpers class

- README.md
So that people use the latest version :-)
> [doc] Update install instruction with "--upgrade"

- ci/Dockerfile.ubuntu.18.04
- ci/Dockerfile.ubuntu.18.04.cpu
- ci/Dockerfile.ubuntu.20.04
- ci/Dockerfile_generator.py
Related issue = #4776
So that it can be used in GitHub Actions directly, instead of writing docker invocations ourselves.
> [ci] Update ubuntu 18.04 image to use latest git

- docs/lang/articles/get-started/index.md
> [doc] Update julia set example

- .github/workflows/release.yml
- .github/workflows/testing.yml
Related issue = #4785 
Update the image to unblock #4776
> [ci] Update ci images to use latest git

- docs/lang/articles/contribution/dev_install.md
> [Doc] Remove redundant semicolon in path

- taichi/ir/frontend_ir.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
Related issue = https://github.com/taichi-dev/taichi/pull/4622#issuecomment-1080165101
> [lang] Fix frontend type check for sqrt, log, exp

- docs/lang/articles/contribution/writing_cpp_tests.md
> [doc] Fix doc of running C++ tests

- python/taichi/lang/misc.py
> [Lang] Fix vulkan backend changes cwd on imac

- python/taichi/lang/simt/warp.py
- tests/python/test_simt.py
Related issue = #4631
Add shfl_down_f32 warp intrinsic for cuda backend.
> [SIMT] Add shfl_down_f32 intrinsic.

- docs/lang/articles/advanced/layout.md
> [Doc] Editorial review to fields (advanced)

- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/get-started/index.md
> [Doc] Proofread Getting started

- .github/workflows/issue_open.yml
> [ci] Use a new PAT with org permission

- taichi/ui/backends/vulkan/gui.cpp
- tests/python/test_ggui.py
> [gui] Only call ImGui_ImplVulkan_Shutdown if it's initialized

- docs/lang/articles/basic/overview.md
> [doc] Fix doc link

- taichi/transforms/type_check.cpp
Related issue = fix #4678
This PR refactors type check for local stores to make the logic concise and clear. The remaining issue in #4678 is caused by printing a wrong argument, which is fixed by the way.
> [Bug] [ir] Fix and refactor type check for local stores

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
Related issue = https://github.com/taichi-dev/taichi/issues/4837
> [lang] Group related Matrix methods closer

- python/taichi/ui/staging_buffer.py
> [gui] Avoid implicit type casts in staging_buffer

- cmake/TaichiExportCore.cmake
> [build] Install export core library to build dir

- setup.py
> [build] [bug] Fix a bug of skbuild that loses the root package_dir

- docs/lang/articles/advanced/performance.md
Related issue = https://github.com/taichi-dev/taichi/issues/4660
> [Doc] Add limitation about TLS optimization

- cmake/TaichiExportCore.cmake
> [build] Change the library output dir for export core

- taichi/backends/metal/api.cpp
- taichi/backends/metal/api.h
- taichi/backends/metal/device.cpp
- taichi/backends/metal/device.h
> [metal] Complete Device API

- taichi/backends/metal/kernel_manager.cpp
> [metal] Migrate runtime's MTLBuffer allocation to unified device API

- taichi/backends/vulkan/vulkan_device.cpp
> [vulkan] Fix typo for waitSemaphoreCount

- taichi/backends/vulkan/vulkan_device.cpp
> [vulkan] Add new VMA vulkan functions.

- .github/workflows/scripts/win_test.ps1
> [ci] Cancel tests for Paddle on GPU

- python/taichi/lang/mesh.py
> [mesh] Remove debug print in mesh

- .github/workflows/scripts/win_test.ps1
- .github/workflows/testing.yml
Powershell needs `if (-not $?) { exit 1 }` to exit on error immediately. Add this for paddle test.
> [test] Exit on error during Paddle windows test

- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device_creator.cpp
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/program/async_engine.cpp
- taichi/program/state_flow_graph.cpp
- taichi/util/io.h
- tests/cpp/ir/ir_type_promotion_test.cpp
- tests/cpp/transforms/alg_simp_test.cpp
> [build] Warning Suppression PR #2: Fixed codebase warnings

- python/taichi/lang/matrix.py
Related issue = https://github.com/taichi-dev/taichi/issues/4837
> [refactor] Simplify Matrix's initializer

- docs/lang/articles/basic/field.md
- docs/lang/articles/contribution/contributor_guide.md
> [Doc] Updated relative path

- python/taichi/lang/mesh.py
> [lang] Fix type check warnings for ti.Mesh

- python/taichi/lang/simt/warp.py
- taichi/llvm/llvm_context.cpp
- taichi/runtime/llvm/runtime.cpp
- tests/python/test_simt.py
> [SIMT] Add uni_sync warp intrinsics

- cmake/TaichiCXXFlags.cmake
- docs/lang/articles/contribution/contributor_guide.md
Related issue = #3335, #2927
Updated docs for compilation warnings:
https://deploy-preview-4928--docsite-preview.netlify.app/lang/articles/contribution/contributor_guide#compilation-warnings
> [build] Turn on -Werror on Linux and Mac platforms

- taichi/backends/cc/cc_program.cpp
- taichi/backends/cc/cc_program.h
- taichi/backends/dx/dx_program.cpp
- taichi/backends/dx/dx_program.h
- taichi/backends/metal/metal_program.cpp
- taichi/backends/metal/metal_program.h
- taichi/backends/opengl/opengl_program.cpp
- taichi/backends/opengl/opengl_program.h
- taichi/backends/vulkan/vulkan_program.cpp
- taichi/backends/vulkan/vulkan_program.h
- taichi/codegen/codegen_llvm.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/program/program.cpp
- taichi/program/program_impl.cpp
- taichi/program/program_impl.h
> [refactor] Remove unused snode_trees in ProgramImpl interface

- cmake/TaichiCXXFlags.cmake
> [build] Turned off -Werror temporarily for issues with performance-bot

- taichi/codegen/codegen_llvm.cpp
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
- taichi/struct/struct_llvm.h
> [refactor] [llvm] Remove struct_compiler_ as a member variable

- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
- taichi/llvm/llvm_program.cpp
> [llvm] Move cache directory to dump()

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- README.md
- ci/scripts/ubuntu_build_test_cpu.sh
- tests/run_tests.py
Related issue = #4973
**Note:**  this PR may not resolve the problem completely, please check the above issue for diagnose and next steps.
> [build] Fixed Ilegal Instruction Error when importing PaddlePaddle module

- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/program/test_program.cpp
- tests/cpp/program/test_program.h
We only had a test for external array so adding one for ndarray.
> [test] Add an ndarray test in C++.

- taichi/backends/cpu/codegen_cpu.cpp
- taichi/backends/cpu/codegen_cpu.h
- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/wasm/codegen_wasm.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/program/context.h
> [llvm] Make codegen produce static llvm::Module

- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
> [llvm] Make cache writer support BC format

- build.ps1
- Support Python package userspace installtion;
- Support downloading prebuilt LLVM and Clang if absent;
- Powershell functions only, no depedency on environmental software, should work with any Windows 10+.
> [Build] Improve Windows build script

- taichi/common/cleanup.cpp
- taichi/common/cleanup.h
- taichi/common/serialization.h
- tests/cpp/common/serialization_test.cpp
> [refactor] Improve serializer and cleanup utils

- cmake/TaichiTests.cmake
- taichi/jit/jit_session.cpp
- taichi/llvm/llvm_context.cpp
- taichi/llvm/llvm_context.h
- taichi/llvm/llvm_offline_cache.cpp
- taichi/llvm/llvm_offline_cache.h
- tests/cpp/llvm/llvm_offline_cache_test.cpp
> [llvm] Support both BC and LL cache format

- .github/ISSUE_TEMPLATE/bug_report.md
> [Doc] Update trouble shooting URL in bug report template

- tests/python/test_ndarray.py
> [test] Fix a few mis-configured ndarray tests

- tests/cpp/aot/aot_save_load_test.cpp
* #5004
* #5002
* #4999
* #4998
* __->__ #4997
* #4996
> [test] Add test for Ndarray from DeviceAllocation

- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- tests/cpp/aot/aot_save_load_test.cpp
* #5004
* #5002
* #4999
* __->__ #4998
* #4997
* #4996
The end goal is make this the only ctor for Ndarray class.
> [refactor] Construct ndarray from existing DeviceAllocation.

- README.md
add active events and communication
The communication is related to = #4878
> [doc] Update community section

- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
The raw pointer of `ndarray` when building a sparse matrix: https://github.com/taichi-dev/taichi/blob/febbd3d998ba1a87ce3cc30e7cae2019b7381ac2/taichi/program/sparse_matrix.cpp#L169.
> [refactor] Move get ndarray data ptr to program

- .github/workflows/scripts/win_build_test_cpu.ps1
- .github/workflows/testing.yml
> [ci] [build] Enable ccache for windows docker

- tests/cpp/aot/aot_save_load_test.cpp
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/ir/ndarray_kernel.cpp
- tests/cpp/ir/ndarray_kernel.h
* #5017
* #5016
* #5015
* __->__ #5014
We'll reuse these two kernels for cgraph tests as well so let's clean it
up first.
> [test] Unify kernel setup for ndarray related tests

- taichi/aot/module_builder.h
- taichi/backends/cpu/aot_module_builder_impl.cpp
- taichi/backends/cpu/aot_module_builder_impl.h
- taichi/backends/cpu/aot_module_loader_impl.cpp
- taichi/backends/cpu/aot_module_loader_impl.h
- taichi/common/serialization.h
- taichi/llvm/llvm_program.cpp
- taichi/llvm/llvm_program.h
> [Llvm] Add AOT builder and loader

- taichi/backends/vulkan/vulkan_device.cpp
- taichi/backends/vulkan/vulkan_device.h
- Supported importing external Vulkan buffers (useful for game engine integration)
> [AOT] Support importing external Vulkan buffers

- python/taichi/_kernels.py
> [Lang] Fix fast_gui rgba format bug

- taichi/aot/graph_data.cpp
- taichi/aot/graph_data.h
- tests/cpp/aot/aot_save_load_test.cpp
- tests/cpp/program/graph_test.cpp
* #5026
* __->__ #5025
* #5024
Thought this might be more intuitive for users.
> [aot] Move ArgKind as first argument in Arg class

- taichi/backends/vulkan/vulkan_device.h
AOT examples crash after a few frames in Vulkan backend.
> [Vulkan] Fixed vulkan backend crash on AOT examples

- .github/workflows/scripts/win_build.ps1
- .github/workflows/scripts/win_build_test_cpu.ps1
- ci/windows/win_build_test.ps1
Improve log readability for [this case](https://github.com/taichi-dev/taichi/runs/6585423431?check_suite_focus=true).
> [Build] Exit CI builds when download of prebuilt packages fails

- docs/lang/articles/basic/type.md
> [Doc] Updated type system

- setup.py
Related issue = Fix #5051
I use the `build_py` command to do the copy which will be run in both `bdist_wheel` and `develop`.
> [build] [bug] Ensure the assets folder is copied to the project directory

- python/taichi/aot/utils.py
- python/taichi/lang/_ndarray.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/types/compound_types.py
- python/taichi/types/ndarray_type.py
- tests/python/test_aot.py
- tests/python/test_api.py
- tests/python/test_graph.py
* #5073
* #5066
* __->__ #5065
> [refactor] Specialized Ndarray Type is (element_type, shape, layout)

- python/taichi/lang/impl.py
- python/taichi/lang/mesh.py
- taichi/python/export_lang.cpp
- tests/python/test_ndarray.py
* __->__ #5073
* #5066
* #5065
> [Lang] Support constructing vector and matrix ndarray from ti.ndarray()

- README.md
> [doc] Fix broken link for github action status badge

- taichi/codegen/codegen_llvm.cpp
> [llvm] Specialize element shape for LLVM backend

- taichi/transforms/auto_diff.cpp
> [autodiff] Clean hidden override functions

- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
Add checker pattern to the cloth:
> [Example] Update visual effects of mass_spring_3d_ggui.py

- taichi/codegen/codegen_llvm.cpp
- taichi/codegen/codegen_llvm.h
- taichi/codegen/codegen_llvm_quant.cpp
> [llvm] [refactor] Replace cast_int() with LLVM native integer cast

- taichi/backends/cuda/codegen_cuda.cpp
- taichi/backends/metal/kernel_manager.cpp
- taichi/codegen/codegen_llvm.cpp
- taichi/program/context.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/texture.cpp
- taichi/program/texture.h
- taichi/python/export_lang.cpp
- taichi/runtime/gfx/runtime.cpp
- taichi/runtime/opengl/opengl_api.cpp
> [lang] Texture support 1/n (Context & Programs)

- docs/lang/articles/advanced/odop.md
> [Doc] Updated odop.md, removing obsolete information

- python/taichi/_main.py
- requirements_dev.txt
- setup.py
I think this should help users better see the full list of examples
Screenshot:
> [cli] Improve user interface for CLI command ti example

- README.md
> [doc] Add badge on README.md

- docs/lang/articles/contribution/contributor_guide.md
- docs/lang/articles/reference.md
> [Doc] Modify compilation warnings

- README.md
> [Doc] Updated README command lines

- .github/workflows/testing.yml
- ci/Dockerfile.ubuntu.18.04.cpu
> [ci] Slim cpu build image

- README.md
> [doc] Remove stale coverage from README.md

- c_api/include/taichi/taichi_core.h
- c_api/include/taichi/taichi_vulkan.h
- c_api/src/taichi_vulkan_impl.cpp
- c_api/taichi.json
- misc/generate_c_api.py
This PR fixed some defects in the provided Taichi C-APIs.
> [AOT] Fixed C-API provision

- python/taichi/_main.py
Bug fix: `ti gallery` is broken due to PR [#5153](https://github.com/taichi-dev/taichi/pull/5153).
> [CLi] Fix ti gallery command bug

- taichi/system/profiler.cpp
- taichi/system/profiler.h
> [refactor] Move spdlog include to profiler.cpp

- python/taichi/examples/rendering/simple_texture.py
- python/taichi/lang/_texture.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/types/texture_type.py
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/codegen/spirv/spirv_ir_builder.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/program/texture.cpp
- taichi/program/texture.h
- taichi/python/export_lang.cpp
- tests/python/test_api.py
> [lang] 1d/3d texture support

- python/taichi/examples/autodiff/diff_sph/diff_sph.py
> [example] Fix diff_sph example with --train

- c_api/src/taichi_core_impl.cpp
- taichi/llvm/llvm_program.h
- taichi/llvm/llvm_runtime_executor.h
> [bug] Fixed misuse of std::forward

- README.md
Add the awesome taichi link to the chapter Reference in README.md.
> [doc] Add the awesome taichi link to README.md

- python/taichi/examples/simulation/fractal.py
When closing the gui window in `fractal.py` it raises lots of warning messages. This PR fixes this problem.
> [Lang] Fix fractal gui close warning

- python/taichi/examples/rendering/simple_texture.py
- taichi/codegen/spirv/spirv_types.cpp
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
> [opengl] Texture support in OpenGL

- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/program/program.cpp
- tests/cpp/program/graph_test.cpp
- tests/python/test_matrix.py
* #5299
* #5298
* __->__ #5297
ndarray host accesses
> [refactor] Switch to using staging buffer for metal/vulkan/opengl

- taichi/backends/cpu/cpu_device.cpp
- taichi/backends/cpu/cpu_device.h
- taichi/backends/cuda/cuda_device.cpp
- taichi/backends/cuda/cuda_device.h
- taichi/program/ndarray.cpp
- tests/python/test_offline_cache.py
* #5299
* __->__ #5298
* #5297
> [refactor] Use device api for CPU/CUDA ndarray

- misc/prtags.json
> [misc] Add 'gfx' PR tag

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_if_fwd.py
> [autodiff] Fix alloca block and add control flow test case for forward mode

- taichi/runtime/llvm/llvm_offline_cache.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/program_impls/llvm/llvm_program.h
> [llvm] Changed LlvmProgramImpl::cache_data_ from object to unique_ptr

- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/cuda/codegen_cuda.h
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/runtime/cpu/aot_module_loader_impl.cpp
- taichi/runtime/cuda/aot_module_loader_impl.cpp
- taichi/runtime/llvm/llvm_runtime_executor.h
- taichi/runtime/program_impls/llvm/llvm_program.h
> [llvm] [aot] Replaced LlvmProgramImpl with LlvmRuntimeExecutor for ModuleToFunctionConverter

- tests/python/test_ad_for_fwd.py
> [autodiff] [test] Add for-loop tests for forward mode

- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/runtime/cpu/aot_module_loader_impl.cpp
- taichi/runtime/cuda/aot_module_loader_impl.cpp
- taichi/runtime/llvm/llvm_aot_module_builder.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/runtime/llvm/llvm_offline_cache.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/program_impls/llvm/llvm_program.h
- tests/cpp/llvm/llvm_offline_cache_test.cpp
Related issue = #5252 
Decomposition of #5251
> [llvm] [refactor] (Decomp of #5251 3/n) Remove codegen from OffloadedTask and let it replace OffloadedTaskCacheData

- .github/workflows/testing.yml
> [ci] [test] Add retention-days for broken wheels

- taichi/runtime/llvm/llvm_runtime_executor.h
- tests/cpp/aot/llvm/field_aot_test.cpp
- tests/cpp/aot/llvm/kernel_aot_test.cpp
- tests/cpp/aot/llvm/mpm88_graph_aot_test.cpp
> [llvm] [aot] Rewrite LLVM AOT tests with LlvmRuntimeExecutor

- tests/python/test_ggui.py
> [gui] [test] Fix bug in test_ggui.py when some pc env do not surrport ggui

- taichi/runtime/llvm/llvm_aot_module_builder.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- tests/cpp/llvm/llvm_offline_cache_test.cpp
Related issue = #5252
Decomposition of #5251
> [llvm] (Decomp of #5251 7/n) Change the way to record the time of offline cache

- taichi/transforms/auto_diff.cpp
- tests/python/test_abs.py
- tests/python/test_ad_basics.py
> [autodiff] Support unary ops for forward mode

- python/taichi/lang/impl.py
- taichi/ir/type_utils.h
- taichi/program/snode_expr_utils.cpp
- taichi/python/export_lang.cpp
- taichi/transforms/auto_diff.cpp
> [refactor] Rename the confused needs_grad

- python/taichi/graph/_graph.py
- taichi/aot/graph_data.h
- taichi/program/graph_builder.cpp
- taichi/python/export_lang.cpp
- tests/python/test_graph.py
* __->__ #5363
* #5362
* #5361
* #5360
Fixes #5169
> [bug] Cast scalar to right type before converting to uint64

- python/taichi/lang/matrix.py
> [Lang] Add determinant for 1d case

- taichi/analysis/gen_offline_cache_key.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
Fixes bugs on test_stop_grad.py when offline cache is on.
> [llvm] [bug] Add stop grad to ASTSerializer

- requirements_test.txt
- tests/pytest_hardtle.py
- tests/run_tests.py
> [ci] Add per test hard timeout limit

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_basics.py
> [autodiff] Add ternary operators for forward mode

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_matrix.py
> [Lang] Implement assignment by slicing

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_field.py
- tests/python/test_materialize_check.py
> [autodiff] Check not placed field.dual and add needs_dual

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- .github/workflows/testing.yml
- ci/Dockerfile.ubuntu.18.04
- ci/Dockerfile.ubuntu.20.04
- python/taichi/examples/features/sparse/tutorial.py
> [ci] Run release tests

- taichi/analysis/gen_offline_cache_key.cpp
> [misc] Add missing members of XXXExpression and FrontendXXXStmt to result of ASTSerializer

- cmake/TaichiCore.cmake
- cmake/TaichiExamples.cmake
- python/taichi/_main.py
- python/taichi/tools/cc_compose.py
- setup.py
- taichi/gui/gui.h
- taichi/program/program.cpp
- taichi/rhi/vulkan/vulkan_device.cpp
- taichi/rhi/vulkan/vulkan_device.h
- taichi/rhi/vulkan/vulkan_loader.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
- taichi/system/traceback.cpp
Based on [this discussion](https://github.com/taichi-dev/taichi/issues/4832#issuecomment-1188850829). We no longer use emscripten to compile taichi. Hence remove related code.
Related issue = #4832
> [Build] Remove TI_EMSCRIPTENED related code

- docs/lang/articles/contribution/writing_cpp_tests.md
> [doc] Update cpp tests build doc

- taichi/codegen/codegen.cpp
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
> [misc] Add debug logging and TI_AUTO_PROF for offline cache

- taichi/codegen/codegen.cpp
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cpu/codegen_cpu.h
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/cuda/codegen_cuda.h
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/codegen/llvm/codegen_llvm_quant.cpp
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/codegen/wasm/codegen_wasm.h
- taichi/ir/type_utils.cpp
- taichi/runtime/cpu/aot_module_builder_impl.cpp
- taichi/runtime/cuda/aot_module_builder_impl.cpp
- taichi/runtime/wasm/aot_module_builder_impl.cpp
> [refactor] [llvm] Rename CodeGenCPU/CUDA/WASM and CodeGenLLVMCPU/CUDA/WASM

- taichi/rhi/vulkan/vulkan_device.cpp
Fix missing bracket and resume correct function indent by pre-commit.
> [bug] Add missing bracket when build for android

- python/taichi/examples/simulation/implicit_fem.py
> [example] Make implicit_fem fallback to CPU when CUDA is not available

- python/taichi/ui/staging_buffer.py
> [misc] Fix warning at GGUI canvas.circles (#5424)

- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/cuda/codegen_cuda.h
- tests/python/test_offline_cache.py
> [llvm] Add parallel compilation to CUDA backend

- python/taichi/lang/ast/ast_transformer.py
- taichi/transforms/frontend_type_check.cpp
- tests/python/test_compare.py
> [Lang] [bug] Ensure non-i32 compatibility in while statement conditions

- tests/python/test_ad_for_fwd.py
> [autodiff] [test] Add more for-loop tests for forward mode

- .github/workflows/release.yml
> [ci] Fix macOS nightly build

- taichi/transforms/auto_diff.cpp
> [autodiff] Skip ConstStmt when generating alloca for dual

- taichi/rhi/vulkan/vulkan_device.cpp
#5483 accidentally broke android build so this PR fixes it
> [bug] Fix android build for taichi-aot-demo
