taichi/backends/vulkan/vulkan_device.cpp
taichi/codegen/spirv/kernel_utils.cpp
taichi/codegen/spirv/kernel_utils.h
taichi/codegen/spirv/lib_tiny_ir.h
taichi/codegen/spirv/snode_struct_compiler.cpp
taichi/codegen/spirv/snode_struct_compiler.h
taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.h
taichi/codegen/spirv/spirv_types.cpp
taichi/codegen/spirv/spirv_types.h
taichi/runtime/gfx/runtime.cpp
taichi/runtime/gfx/runtime.h
tests/cpp/aot/aot_save_load_test.cpp

Two changes have been made:
1. Introduces a "Type compiler" system, that contains an IR that can be built easily from C++ or translated from Taichi SNodes, and then the type IR can be simplified or transformed, then compiles down to SPIR-V. It automatically handles layouts with the concept of a `LayoutContext`, and it is now used to handle the generation of the argument buffer struct type in the codegen. The next step would be to use this system on the root buffer, and solve the aliasing problem, by using a type transformer that solves the appropriate storage types for root buffers. This also potentially helps the effort of adding sparse fields support into the SPIR-V codegen. This IR is largely inspired by MLIR (but as we can not upgrade our LLVM yet, it would be hard to directly use …

[vulkan] Codegen & runtime improvements

---

taichi/backends/cuda/codegen_cuda.cpp
taichi/codegen/codegen_llvm.cpp
taichi/codegen/codegen_llvm.h
taichi/codegen/codegen_llvm_quant.cpp

The original bit pointer is like:
```cpp
struct bit_pointer {
i8 *byte_ptr;
i32 bit_offset;
};
```
When creating a new bit pointer, the `byte_ptr` is always cast into `i8 *` first. Then a physical type needs to get passed alongside to allow access of its pointee.
As you may have noticed, the `byte_ptr` is not a pointer to a byte, but simply a byte-level pointer, which can point to any primitive type. Therefore, there is actually no need to force `byte_ptr` as `i8 *`. Then info of its physical type can be easily preserved by extending the definition of bit pointers:
```cpp
// X=8/16/32/64
struct bit_pointer_X {
iX *byte_ptr;
i32 bit_offset;
}
```
After this change, logic around bit pointers can get simplified a lot.

[type] [refactor] Decouple quant from SNode 3/n: Extend bit pointers

---

taichi/codegen/spirv/spirv_codegen.cpp
tests/python/test_ad_for.py

[vulkan] Fix OpBranch for reversed RangeForStmt

---

taichi/codegen/metal/shaders/snode_bit_pointer.metal.h
taichi/runtime/llvm/runtime.cpp
tests/python/test_bit_array.py
tests/python/test_bit_array_vectorization.py

https://github.com/taichi-dev/taichi/blob/b1ba4572a1c0fef12fe71b63c8e28b289c77e2ad/taichi/runtime/llvm/runtime.cpp#L1827-L1838
In the above function, the argument `value` is not guaranteed to contain zeros at non-masked positions. This is especially buggy when `value` is originally a negative number. We need to replace `value` with `(value & mask)` to avoid pollute other positions. A related test case is added.

[type] [bug] Refine SNode with quant 1/n: Fix (atomic_)set_mask_b##N

---

python/taichi/lang/_ndrange.py
python/taichi/lang/ast/ast_transformer.py
tests/python/test_ndrange.py

[bug] Throw exceptions when ndrange gets non-integral arguments

---

c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_vulkan_impl.cpp

This PR added safety checks to Taichi C-APIs, so that a call with apparently invalid arguments won't trigger a hard crash. Human readable warning are logged for debugability.

[AOT] Added safety checks to prevent hard crashes on failure

---

taichi/backends/opengl/CMakeLists.txt

After #5246, `opengl_api` is moved to target `opengl_rhi`, which introduces dependency on glfw.  This PR fixes the build error `undefined reference to glfwInit/CreateWindows`.

[build] [bug] Fix dependency for opengl_rhi target

---

taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
taichi/runtime/program_impls/llvm/llvm_program.cpp

[bug] Fix missing old but useful metadata in offline cache

---

taichi/backends/metal/device.cpp

There isn't a standalone test for this yet but will try to add one in
the followup PRs.

[metal] Support memcpy_internal via buffer_copy

---

misc/generate_c_api.py
misc/generate_unity_language_binding.py
misc/taichi_json.py

This PR introduces a common interface for `taichi.json` parsing, so that language binding generator scripts can save some boilerplates and avoid inconsistent JSON property interpretation between versions of scripts. Existing generators for C/C++ headers and C# marshalling & import have been adapted to load module descriptions from `taichi_json.py`.
The file names and hard-coded relative paths are subject to change.

[AOT] Refactor C-API codegen

---

c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_vulkan_impl.cpp
c_api/src/taichi_vulkan_impl.h
c_api/taichi.json
taichi/program/program.cpp
taichi/runtime/gfx/runtime.cpp
taichi/runtime/gfx/runtime.h

This PR introduces a new C-API of, `ti_copy_memory`, to enable on-device memory copy without interrupting sequences of kernel launches to eliminate host-device synchronization. It is especially useful when the user wants to transfer Taichi results to externally allocated device memory (which might not support compute shader write).

[AOT] Added C-API for on-device memory copy

---

taichi/runtime/metal/kernel_manager.cpp

We need this when doing memcpy_internal.

[metal] Turn off only_for_dev_allocation in rhi_device

---

python/taichi/ad/_ad.py

Set default seed only for scalar parameter to avoid silent unexpected results.
The user should specify the `seed` if the `parameter` is not a 0-D field.

[autodiff] Set default seed only for scalar parameter to avoid silent unexpected results

---

tests/python/test_ad_atomic_fwd.py

[autodiff] [test] Add atomic test for forward autodiff

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/program/kernel.h
taichi/runtime/program_impls/llvm/llvm_program.h

LLVM AOT and Compute Graph captures compiled information for serialization and deserialization. 
In a previous PR, we used LlvmProgramImpl::cache_data_ to save the compiled Fields ([PR#5120](https://github.com/taichi-dev/taichi/pull/5120)). In this PR, we further made LlvmProgramImpl::cache_data_ to save compiled Kernel Info for later use in AOT and Compute Graph.

[llvm] Use LlvmProgramImpl::cache_data_ to store compiled kernel info

---

taichi/program/program.cpp
taichi/runtime/program_impls/vulkan/vulkan_program.h
tests/cpp/program/graph_test.cpp

I got tripped over a few times by `sync` flag that calling `prog.synchronize()` didn't really synchronize due to a fake `sync=True`. Having a manual `sync` flag requires us to know exactly every place could potentially submit jobs and set the flag properly. IMHO this is pretty error prone -  when I call `sync` I'd prefer it to be 100% synchronized even though it might cause 1 extra no-op sync compared to the current `sync` flag solution. 
Originally I wanted to get rid of this flag completely but realized that it's used in the async mode so this PR only decouples it with normal mode.

[refactor] Synchronize should always be called in non-async mode

---

python/taichi/aot/module.py
tests/python/test_aot.py

AOT modules atm are saved as a list of files which leads to extra complexity importing to Unity. Unity only allows the user to load one file at a time via its provided Assets APIs for consistent cross-platform behavior; and files of different extensions will be imported as different C# types, making it frustratingly difficult to write glue codes.
This PR provides a (maybe temporary) solution to pack all baked files and metadata to a single zip. You only need to apply a minor change to shift from the existing `save` API to the zip API.
```diff
mod = ti.aot.Module(ti.vulkan)
mod.add_kernel(fractal,
template_args={
'canvas': canvas,
})
- mod.save("Assets/Resources/TaichiModules/module_directory", '')
+ mod.archive("Assets/Resources/TaichiModules/module_file.tcm")
```
In the generated zip …

[AOT] Save AOT module artifacts as zip archive

---

python/taichi/lang/_ndrange.py
tests/python/test_ndrange.py

[bug] Accept numpy integers in ndrange (#5245)

---

taichi/codegen/spirv/lib_tiny_ir.h
taichi/ir/statements.h

[misc] Fix a few compilation warnings

---

c_api/src/taichi_core_impl.cpp
c_api/src/taichi_vulkan_impl.cpp

This PR fixed certain crashes with C-API.
- Initialization call order for imported Vulkan runtime was wrong;
- Named NDArray argument map allocation were not stable.

[AOT] Fixed certain crashes in C-API

---

taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/util/io.h
tests/cpp/llvm/llvm_offline_cache_test.cpp

Related issue = # 
https://github.com/taichi-dev/taichi/runs/7188242854?check_suite_focus=true
missing \<filesystem\> on macOS 10.14

[build] [bug] Fix building on macOS 10.14 failed

---

python/taichi/examples/autodiff/diff_sph/diff_sph.py
python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
python/taichi/examples/ggui_examples/mass_spring_game_ggui.py
python/taichi/examples/ggui_examples/mpm3d_ggui.py
python/taichi/examples/simulation/euler.py

[example] Lower example GUI resolution to fit buildbot display

---

python/taichi/lang/ast/ast_transformer.py

Related issue = fix #5217
The implicit type conversion for RangeFor boundaries is causing confusions especially when users explicitly passed ti.i64 as boundary value. 
Due to the lack of "dtype demotion" at each backend, we performed a temporary fix - adding a warning message to address this type conversion. 
Filed another issue https://github.com/taichi-dev/taichi/issues/5320 to track the real fix for this.

[bug] Added warning messages for implicit type conversion for RangeFor boundaries

---

python/taichi/lang/misc.py

When Taichi program crashes we used to show a `Taichi Compiler Stack
Traceback` (a.k.a purple stack, example shown below) but this stack doesn't have enough symbol for developers, nor
it's readable for normal Taichi python users. So let's turn it off by
default to avoid confusion.
```
***********************************
* Taichi Compiler Stack Traceback *
***********************************
/home/ailing/github/taichi/python/taichi/_lib/core/taichi_core.cpython-38-x86_64-linux-gnu.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/home/ailing/github/taichi/python/taichi/_lib/core/taichi_core.cpython-38-x86_64-linux-gnu.so(+0x503753) [0x7f0d4bd19753]
/home/ailing/github/taichi/python/taichi/_lib/core/taichi_core.cpython-38 …
```

[refactor] Turn off stack traceback info by default

---

python/taichi/ad/_ad.py
tests/python/test_ad_basics_fwd.py

Related issue = #5055 
To handle the case similar to `ti.root.dense(ti.i, 1).place(a, b, a.dual, b.dual)`. In this case, the field shape is one but not none comparing to `a = ti.field(float, shape=())`.

[autodiff] Handle field accessing by zero for forward mode

---

python/taichi/examples/simulation/initial_value_problem.py

[example] Avoid f64 type in simulation/initial_value_problem.py

---

CMakeLists.txt
cmake/TaichiCore.cmake
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/codegen/llvm/llvm_codegen_utils.cpp
taichi/codegen/llvm/llvm_codegen_utils.h
taichi/codegen/llvm/struct_llvm.cpp
taichi/codegen/wasm/codegen_wasm.cpp
taichi/runtime/cpu/jit_cpu.cpp
taichi/runtime/cuda/jit_cuda.cpp
taichi/runtime/cuda/jit_cuda.h
taichi/runtime/llvm/llvm_context.cpp

Still use clang10 for COMPILE_LLVM_RUNTIME.
Most changes are related to the opaque ptr change in llvm 15.
It requires type when create Load and GEP. It would be nice to generate the type from taichi type.
Known issue.
Still some getPointerElementType use which is Deprecated for llvm 15.
Also some cases use hack to get llvm type for Load/GEP.
Only tested python tests/run_tests.py -v -t3 -a cpu -s on windows.
2 crashes.
crashes:
fp16 crash for my hw not support fp16 for vulkan.
element_wise crashed in llvm slp-vectorizer pass on skylake cpu, Already fixed upstream llvm.
Also tested clang15 for COMPILE_LLVM_RUNTIME, same result.

[llvm] Drop code for llvm 15.

---

taichi/program/compile_config.cpp
taichi/program/compile_config.h
taichi/python/export_lang.cpp
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h

Related issue = #5252 
Decomposition of #5251 
We can configure the thread number by `ti.init(compile_thread_num=xxx)`, 0 stands for serial.
It‘s not in use in this PR, but it will be used in the following PRs.

[llvm] (Decomp of #5251 5/n) Add the parallel compilation worker to LlvmProgramImpl

---

taichi/codegen/codegen.cpp
taichi/codegen/codegen.h
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cpu/codegen_cpu.h
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/cuda/codegen_cuda.h
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/runtime/cpu/aot_module_loader_impl.cpp
taichi/runtime/cuda/aot_module_loader_impl.cpp

Related issue = #5252 
Decomposition of #5251
Made ModuleToFunctionConverter an abstract class.
Currently only CPU backend supports multiple modules, the implementation of CUDA backend only supports a single module.

[llvm] [refactor] (Decomp of #5251 6/n) Let ModuleToFunctionConverter support multiple modules

---

taichi/aot/graph_data.h
taichi/program/graph_builder.cpp
taichi/program/graph_builder.h
tests/python/test_graph.py

* #5363
* #5362
* #5361
* __->__ #5360
Arg name should be an unique identifier in the same graph so adding a
test to prevent two different args having the same name.

[test] Check repeated arg names in cgraph

---

python/taichi/aot/utils.py
python/taichi/examples/graph/mpm88_graph.py
python/taichi/examples/graph/stable_fluid_graph.py
python/taichi/graph/_graph.py
taichi/aot/graph_data.cpp
taichi/aot/graph_data.h
taichi/python/export_lang.cpp
tests/cpp/aot/vulkan/aot_save_load_test.cpp
tests/cpp/program/graph_test.cpp
tests/python/test_graph.py

* #5363
* #5362
* __->__ #5361
* #5360
Field_dim of ndarray args must match among (ti kernel annotation, graph
arg, runtime ndarray).

[refactor] Check field_dim mismatch in cgraph compilation and runtime

---

python/taichi/aot/utils.py
python/taichi/types/ndarray_type.py
taichi/aot/graph_data.cpp
tests/python/test_graph.py

* #5363
* __->__ #5362
* #5361
* #5360
Dtype of scalar and ndarray args must match among (kernel annotation,
graph arg, runtime scalar/ndarray).

[refactor] Check dtype mismatch in cgraph compilation and runtime

---

docs/lang/articles/basic/operator.md

[doc] Add simt functions in operators page

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/runtime/cpu/aot_module_loader_impl.cpp
taichi/runtime/cuda/aot_module_loader_impl.cpp
taichi/runtime/llvm/llvm_aot_module_builder.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h
tests/cpp/llvm/llvm_offline_cache_test.cpp

Related issue = #5252
Decomposition of #5251 
Merged `owned_module`, `module` and `offloaded_task_list` to `compiled_data_list`.

[llvm] [refactor] (Decomp of #5251 8/n) Refactor KernelCacheData

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/ir/type.h
tests/python/test_quant_array.py

This PR ends the `bit_array` SNode refinement plan in https://github.com/taichi-dev/taichi/issues/4857#issuecomment-1173647894.

[Lang] [type] Refine SNode with quant 7/n: Support placing QuantFixedType under quant_array

---

taichi/transforms/auto_diff.cpp
tests/python/test_ad_basics.py

[autodiff] Support binary operators for forward mode

---

python/taichi/aot/utils.py
python/taichi/types/ndarray_type.py
tests/python/test_graph.py

[refactor] Default dtype of ndarray type should be None instead of f32

---

tests/python/test_ad_basics.py

Currently, there is no test for ternary operators in reverse mode autodiff. This PR adds a test for it.

[autodiff] Add test for ternary operators in reverse mode autodiff

---

.github/workflows/testing.yml

[ci] Properly detect $DISPLAY

---

c_api/src/taichi_vulkan_impl.cpp
taichi/codegen/cpu/codegen_cpu.h
taichi/runtime/llvm/llvm_offline_cache.h
taichi/runtime/llvm/llvm_runtime_executor.h

This PR fixed Vulkan device capability settings and solved some crashes when AOT module is prepared for a lower version of SPIR-V; and guarded some LLVM codes with `TI_WITH_LLVM` to tolerate Vulkan-only builds.

[AOT] Fixed Vulkan device import capability settings

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/llvm_codegen_utils.cpp
taichi/codegen/llvm/llvm_codegen_utils.h
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/llvm_context.h

Related issue = #5252
Types in modules imported from file/other contexts may be renamed to "original_type.xxx" when the type is imported multiple times. So, we need to insert a pointer cast when the parameter type of a function is renamed.

[llvm] Avoid creating new LLVM contexts when updating struct module

---

taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/ir/snode.h
taichi/ir/type.cpp
taichi/ir/type.h
taichi/ir/type_factory.cpp
taichi/ir/type_factory.h
taichi/ir/type_utils.h
taichi/program/snode_expr_utils.cpp
tests/cpp/ir/type_test.cpp

Previously, `BitStructType` only contained member types and member offsets, which were not enough to handle `QuantFloatType`, making quant codegen rely on SNode info. This PR adds exponent info to `BitStructType` so that it becomes possible to handle `QuantFloatType` (with or without shared exponent) without SNode info.

[type] Decouple quant from SNode 4/n: Add exponent info to BitStructType

---

c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/taichi.json
misc/generate_unity_language_binding.py

The following change breaks the current (type-relaxed) implementation. A primitive data type tag is added to `TiNdArray`.
https://github.com/taichi-dev/taichi/blob/master/taichi/aot/graph_data.cpp#L33-L37

[AOT] Adjusted C-API for nd-array type conformance

---

python/taichi/ui/window.py
taichi/python/export_ggui.cpp
taichi/rhi/device.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/ui/backends/vulkan/swap_chain.cpp
taichi/ui/backends/vulkan/swap_chain.h
taichi/ui/backends/vulkan/window.cpp
taichi/ui/backends/vulkan/window.h
taichi/ui/common/window_base.h

Usage:
``` python
window = ti.ui.Window("Test for getting depth buffer from ggui", (768, 768), vsync=True)
video = ti.tools.VideoManager("OutputDir")
while window.running:
render_scene()
depth = window.get_depth_buffer()
video.write_frame(depth)
window.show()
```

[gui] [vulkan] Surpport for getting depth information for python users.

---

python/taichi/aot/utils.py
python/taichi/graph/_graph.py
taichi/python/export_lang.cpp
tests/python/test_graph.py
tests/python/test_ndarray.py

This PR fixes two issues showed up while porting implicit_fem demo:
- field_dim check can be relaxed, for example when users write `for I in
ti.grouped(arr)` it actually works for ndarrays with different
`field_dim`s.
- passing scalars to c++ shouldn't be seperated based on python
type and it was not correct to do so. For example users can pass a `0`
(python int) to a `ti.f32` graph argument.

[bug] Simplify scalar handling in cgraph and relax field_dim check

---

taichi/codegen/spirv/snode_struct_compiler.cpp

Nvidia GLSL compilers will try to extract statically accessed array elements and place all of them directly, and it is a bit too smart for its own good.
e.g.
```
int arr[];
arr[8000] = 3.0;
```
will be detected as static and the array will be replaced with a sized one: ```int arr[8000]```. This slows down the driver's GLSL compiler as it places all 8000 elements. This PR sorts the fields according to the size so that all the statically accessed fields (mostly matrices and global states) come first and the driver will not place extra elements.

[opengl] Speedup compilation for Nvidia cards

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp

[type] [refactor] Decouple quant from SNode 5/n: Rewrite load_quant_float() without SNode

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/field.py
tests/python/test_dynamic_append_length.py

related issue = #5420
Here is currently how we use `ti.append`:
```python
ti.init(arch=ti.cpu)
x = ti.field(int, shape=None)
q = ti.root.dynamic(ti.i, 5)
q.place(x)
@ti.kernel
def test():
for i in range(5):
ti.append(q, [], i)   # q = x.parent()
print(ti.length(q, []))
test()
```
The `ti.append()` function is a bit confusing in that it requires two more positional arguments compared with the usual `append` method.
We hope to change it to something like `x[i].append(i)`, this is done in the ast part by replacing `x[indices].append(val)` with `ti.append(x.parent(), indices, val)`.

[Lang] Add append attribute to dynamic fields

---

c_api/src/taichi_vulkan_impl.cpp
taichi/program/compile_config.h
taichi/python/export_lang.cpp
taichi/rhi/vulkan/vulkan_device_creator.cpp
taichi/rhi/vulkan/vulkan_device_creator.h
taichi/runtime/program_impls/vulkan/vulkan_program.cpp
taichi/ui/backends/vulkan/app_context.cpp
tests/cpp/aot/mpm88_graph_aot.py
tests/cpp/aot/vulkan/aot_save_load_test.cpp
tests/cpp/aot/vulkan/runtime_test.cpp

Ideally we should specify this in `ti.aot.Module` instead of `ti.init`
but tbh we need more refactor before we can compile to a target other
than the current running one. So let's use this to avoid complicating
other parts of the codebase, e.g. offline cache uses CompileConfig as
part of cache key.

[aot] Support specifying vk_api_version in CompileConfig

---

taichi/codegen/llvm/llvm_codegen_utils.h

Fixing the crash in release tests introduced by a typo in #5381 where we need a deep copy of arglist.

[llvm] [bug] Fix llvm_codegen_utils

---

c_api/include/taichi/taichi_core.h
c_api/include/taichi/taichi_vulkan.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_vulkan_impl.cpp
c_api/src/taichi_vulkan_impl.h
c_api/taichi.json
misc/generate_c_api.py
taichi/rhi/device.h
taichi/rhi/vulkan/vulkan_api.cpp
taichi/rhi/vulkan/vulkan_api.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/runtime/gfx/runtime.cpp
taichi/runtime/gfx/runtime.h

This PR implements an experimental abstraction of on-device event. Event is a type of synchronization primitive available on most modern graphics APIs to synchronize on-device execution. It enables the users to immediately kick off rendering after Taichi kernel launches, without any interaction with the host.
Event is different from semaphore. Event only synchronizes execution flows on device and can be signaled and awaited at any point in the command stream. Semaphores can only be signaled at the end of a stream, and awaited in the beginning. There exists cases that the users don't have the control over command buffer submission, like in Unity, which means that semaphores might not the best primitive to use. So the support for event is considered plausible.

[AOT] Support on-device event

---

taichi/ir/snode.cpp

Fixes wrong answers on `test_mesh.py` when offline cache is on which are caused by getting `snode_tree_id` of non-root SNodes whose `snode_tree_id`s are not set.

[bug] Set SNode tree id to all SNodes

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp

The old `load_quant_float()` can actually be merged into `extract_quant_float()` . To achieve this, related logic has been refactored and (fortunately) greatly simplified.

[type] [refactor] Decouple quant from SNode 6/n: Rewrite extract_quant_float() without SNode

---

python/taichi/lang/kernel_impl.py
tests/python/test_ndarray.py

ti.types.ndarray itself is a template type so let's throw a better error
message when users misuse it.
fixes #5452

[error] Throw proper error message when an Ndarray is passed in via ti.template

---

c_api/src/taichi_llvm_impl.cpp
taichi/aot/module_loader.cpp
taichi/aot/module_loader.h
taichi/runtime/llvm/aot_graph_data.h
taichi/runtime/llvm/llvm_aot_module_loader.cpp
taichi/runtime/llvm/llvm_aot_module_loader.h
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
tests/cpp/aot/llvm/field_aot_test.cpp
tests/cpp/aot/vulkan/aot_save_load_test.cpp

Now that SNodeTreeType isn't ready yet, let's automatically initialize all the serialized SNodeTrees when loading `AotModule`s using C-API.

[llvm] [aot] Add LLVM to CAPI part 6: Handle Field initialization in C-API

---

.gitignore
benchmarks/microbenchmarks/_utils.py
benchmarks/run.py
cmake/TaichiCAPI.cmake
cmake/TaichiCore.cmake
cmake/TaichiExamples.cmake
cmake/TaichiExportCore.cmake
cmake/TaichiTests.cmake
docs/lang/articles/faqs/install.md
python/taichi/_lib/__init__.py
python/taichi/_lib/utils.py
python/taichi/_logging.py
python/taichi/_snode/snode_tree.py
python/taichi/aot/record.py
python/taichi/lang/any_array.py
python/taichi/lang/field.py
python/taichi/lang/matrix.py
python/taichi/lang/misc.py
python/taichi/lang/snode.py
python/taichi/lang/struct.py
python/taichi/types/primitive_types.py
python/taichi/types/quantized_types.py
python/taichi/types/utils.py
setup.py
taichi/codegen/llvm/llvm_codegen_utils.h
taichi/common/core.h
taichi/python/export.cpp
tests/python/test_runtime.py
tests/test_utils.py

Related issue = #4832 
Changes:
- Rename the taichi target that includes frontend AST, IR, Analysis etc to `taichi_core`. The old name was `taichi_isolated_core`.  
- Rename the taichi python target that depends on `taichi_core` to `taichi_python`. The old name was `taichi_core`.
- On the python side, rename `ti_core` to `ti_python_core`.

[build] [refactor] Rename taichi core and taichi python targets

---

taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/transforms/optimize_bit_struct_stores.cpp

[type] [refactor] Decouple quant from SNode 7/n: Rewrite BitStructStoreStmt codegen without SNode

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp

After this PR, no snode appears in `codegen_llvm_quant.cpp`.

[type] [refactor] Decouple quant from SNode 8/n: Remove redundant handling of llvm15 in codegen_llvm_quant

---

taichi/ir/control_flow_graph.cpp
taichi/ir/control_flow_graph.h
taichi/ir/transforms.h
taichi/program/ir_bank.cpp
taichi/transforms/auto_diff.cpp
taichi/transforms/cfg_optimization.cpp
taichi/transforms/compile_to_offloads.cpp
taichi/transforms/simplify.cpp
taichi/transforms/simplify.h
tests/cpp/transforms/inlining_test.cpp
tests/python/test_ad_for.py
tests/python/test_ad_for_fwd.py

[autodiff] Switch off parts of store forwarding optimization for autodiff

---

python/taichi/lang/ast/ast_transformer.py
tests/python/test_compare.py

[Lang] [bug] Make comparisons always return i32

---

cpp_examples/autograd.cpp
docs/lang/articles/advanced/odop.md
docs/lang/articles/differentiable/differentiable_programming.md
misc/demo_record_kernel_group.py
python/taichi/ad/_ad.py
python/taichi/aot/record.py
python/taichi/examples/autodiff/minimization.py
python/taichi/examples/autodiff/regression.py
python/taichi/examples/ggui_examples/fem128_ggui.py
python/taichi/examples/simulation/ad_gravity.py
python/taichi/examples/simulation/fem128.py
python/taichi/examples/simulation/fem99.py
python/taichi/examples/simulation/mpm_lagrangian_forces.py
tests/python/examples/autodiff/test_minimization.py
tests/python/test_ad_basics.py
tests/python/test_ad_for.py
tests/python/test_ad_offload.py
tests/python/test_customized_grad.py
tests/python/test_kernel_templates.py
tests/python/test_no_grad.py
tests/python/test_oop.py
tests/python/test_stop_grad.py

Since `ti.Tape` has been deprecated, we should change the related code in the code base.

[misc] Fix deprecation: ti.Tape -> ti.ad.Tape

---

python/taichi/lang/misc.py
tests/python/test_offline_cache.py

Related issue = #4401, close #5496

[bug] Let the arguments in ti.init override the environment variables

---

taichi/rhi/vulkan/vulkan_device.cpp

This PR fixed a trivial validation error that storage usage of depth image is not allowed.

[Vulkan] Fixed depth texture validation error

---

docs/lang/articles/reference/language_reference.md
python/taichi/lang/ast/ast_transformer.py
tests/python/test_cast.py
tests/python/test_literal.py

Related issue = close #5470
`ti.f32(x)` is now a syntax sugar for `ti.cast(x, ti.f32)` if
1. `x` is not a literal;
2. `x` doesn't have a compound type.

[Lang] Support syntax sugar for ti.cast

---

taichi/transforms/type_check.cpp
tests/python/test_numpy.py

[Bug] [ir] Cast indices of ExternalPtrStmt to ti.i32

---

python/taichi/aot/utils.py
python/taichi/examples/graph/texture_graph.py
python/taichi/graph/_graph.py
taichi/aot/graph_data.cpp
taichi/aot/graph_data.h
taichi/aot/module_data.h
taichi/codegen/spirv/kernel_utils.h
taichi/program/context.h
taichi/python/export_lang.cpp
taichi/rhi/device.h
taichi/runtime/gfx/aot_module_builder_impl.cpp
tests/python/test_graph.py

This PR works as a proof of concept for texture support in cgraph and
there might be a few adjustments and C++ tests to be added in the
followup PRs.
Run `ti example texture_graph` to see an example running cgraph with
texture arguments.
A demo in C++ that loads the saved cgraph module and run it without
python can be found in
https://github.com/ailzhang/taichi-aot-demo/blob/master/texture/desktop/texture.cpp

[aot] Support texture and rwtexture in cgraph

---

taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp

Error: 
```[E 07/26/22 14:57:16.810 42759317] [llvm_program.cpp:make_aot_kernel@107] Assertion failure: cache_data_->kernels.count(kernel_key)```
https://github.com/taichi-dev/taichi/runs/7514449055?check_suite_focus=true

[bug] Fix calling make_aot_kernel failed when offline_cache=True

---

python/taichi/lang/field.py
tests/python/test_field.py

[Error] Raise error when using the struct for in python scope

---

taichi/program/program.cpp

Related issue = #4401, #5524 
* https://github.com/taichi-dev/taichi/runs/7540400411?check_suite_focus=true DeviceAllocation, double deallocated
* https://github.com/taichi-dev/taichi/runs/7539283313?check_suite_focus=true Program::num_instances_ == -1, double finalized
* https://github.com/taichi-dev/taichi/runs/7538198742?check_suite_focus=true MemoryPool, double terminated
(Only when tests are run on **multi-thread** (and with offline_cache=True) is the bug triggered.
cc: @k-ye @strongoier @lin-hitonami

[bug] Fix potential bug of lang::Program that could be double finalized

---

taichi/rhi/opengl/opengl_device.cpp

Without it, `synchronize()` in GfxRuntime cannot work properly: 
https://github.com/taichi-dev/taichi/blob/0c464321e7ff62ce0710162d12188634dad2f50f/taichi/runtime/gfx/runtime.cpp#L582
Log time in Python code after `ti.sync()` yields wrong result. This PR fixes this.

[bug] Add glFinish to wait_idle for opengl device

---

c_api/src/taichi_core_impl.cpp
taichi/aot/graph_data.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/program/context.h
taichi/program/kernel.cpp
taichi/program/ndarray.cpp
taichi/program/ndarray.h
tests/cpp/aot/llvm/kernel_aot_test.cpp
tests/cpp/aot/vulkan/aot_save_load_test.cpp

We have various ways to set ndarray args and this PR aims to unify them
around RuntimeContex.
TODO: cleanup ways to set external array args

[refactor] Unify ways to set ndarray args

---

python/taichi/_snode/fields_builder.py
python/taichi/lang/snode.py
python/taichi/types/quantized_types.py
tests/python/test_bitpacked_fields.py
tests/python/test_matrix_different_type.py
tests/python/test_quant_array.py
tests/python/test_quant_array_vectorization.py
tests/python/test_quant_atomics.py
tests/python/test_quant_fixed.py
tests/python/test_quant_time_integration.py

This PR mainly aims at making parameter names more straightforward to understand.
For `quant_array`: `num_bits` -> `max_num_bits`
For `fixed`: `frac` -> `bits`, `range` -> `max_value`

[Lang] [type] Refine SNode with quant 9/n: Rename some parameters in quant APIs

---

cpp_examples/autograd.cpp
cpp_examples/run_snode.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/program/context.h
taichi/program/kernel.cpp
taichi/program/kernel.h
taichi/python/export_lang.cpp
tests/cpp/ir/ir_builder_test.cpp

Also I introduced a typo in #5559 (`DevAllocType::kNdarray ->
DevAllocType::kNone`) and it's also fixed in this PR.

[refactor] Unify ways to set external array args

---

docs/design/llvm_sparse_runtime.md

[doc] Add introductions to ambient_elements in llvm_sparse_runtime.md

---

docs/lang/articles/contribution/dev_install.md

[doc] Format fix to work around a crowdIn issue

---

python/taichi/lang/field.py
taichi/ir/type.cpp
taichi/ir/type.h
taichi/ir/type_factory.cpp
taichi/ir/type_factory.h
taichi/ir/type_utils.h
tests/cpp/ir/type_test.cpp
tests/python/test_bitpacked_fields.py

This PR enforces that at least 2 fields need to be placed when `shared_exponent=True`, and removes the redundant `member_owns_shared_exponents_` from `BitStructType`.

[type] Refine SNode with quant 10/n: Add validity checks and simplify BitStructType

---

python/taichi/lang/simt/block.py
taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.cpp
taichi/codegen/spirv/spirv_ir_builder.h
taichi/ir/frontend_ir.h
tests/python/test_shared_array.py

closes #5338
This PR enables shared array support for vulkan backend but is only stable with `vk_api_version="1.0"` due to a memory barrier problem.
Will open another issue to fix the problem.

[vulkan] Enable shared array support for vulkan backend

---

python/taichi/profiler/kernel_profiler.py
taichi/program/kernel_profiler.cpp
taichi/program/kernel_profiler.h
taichi/python/export_lang.cpp
taichi/rhi/cuda/cuda_profiler.cpp
taichi/rhi/cuda/cuda_profiler.h

Related issue = #5527 
This PR first decouples `update()` from `sync()` in cuda kernel profiler. The memory usage issue will be followed by a separate PR.

[cuda] Decouple update from sync function in kernel profiler

---

taichi/codegen/codegen.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h
taichi/util/io.h
taichi/util/lock.h

[refactor] Redesign loading, dumping and cleaning of offline cache

---

.github/workflows/release.yml
.github/workflows/scripts/android-build.sh
.github/workflows/scripts/aot-demo.sh
.github/workflows/scripts/libcommon.sh
.github/workflows/scripts/unix_build.sh
.github/workflows/scripts/unix_test.sh
.github/workflows/testing.yml
.gitignore
ci/Dockerfile.android-sdk.18.04

[ci] Build Android export core

---

python/taichi/lang/impl.py
python/taichi/lang/matrix.py
tests/python/test_offset.py
tests/python/test_order.py

Related issue = #5491
This PR adds support for the following syntax as described in #5491:
```python
a = ti.field(ti.i32, shape=(128, 64, 32), order='kij')
b = ti.Vector.field(3, ti.i32, shape=(128, 64), order='ji', layout=ti.Layout.SOA)
```

[Lang] Add parameter 'order' to specify layout for scalar, vector, matrix fields

---

python/taichi/ui/staging_buffer.py

[gui] Eliminate redundant compilation of fill_vbo kernel in GGUI

---

.github/workflows/scripts/unix_build.sh
misc/make_changelog.py

Previously if you have cherry-picked commits in release branches, then the tag commits won't be available in master branch history. This may result in old commits (already released in previous version) being duplicated in the changelog. This PR fixes it by sorting the tags and find out the latest tag and 200 commits before it. 
Example usage:
```
python make_changelog.py --save
```

[misc] Explicitly specify base tag commit when running make_changelog.py

---

python/taichi/lang/impl.py
python/taichi/ui/canvas.py
python/taichi/ui/scene.py

The `ambient_light` example is broken:
```python
scene = ti.ui.Scene()
scene.ambient_light([0.2, 0.2, 0.2])
```
which gives:
```log
ambient_light(): incompatible function arguments. The following argument types are supported:
1. (self: taichi._lib.core.taichi_python.PyScene, arg0: tuple) -> None
Invoked with: <taichi._lib.core.taichi_python.PyScene object at 0x7f7c810ad7b0>, [0.2, 0.2, 0.2]
```
`point_light` has a similar issue.
Also note that if a scene doesn't have any lighting except for the ambient light, no lighting SSBO will be allocated and `Canvas.scene` will crash attempting to map this SSBO. Tried not to map when `point_lights.size() == 0` but it doesn't work. So workaround atm.

[gui] GGUI scene APIs are broken

---

python/taichi/tools/np2ply.py

Support exporting vertices' velocity, the main purpose is for adding motion blurring related effects in rendering.

[misc] Support exporting vertices' velocity to .ply file

---

taichi/analysis/offline_cache_util.cpp
taichi/analysis/offline_cache_util.h
taichi/rhi/cuda/cuda_context.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp

[bug] Fix bug that kernel names are not correctly captured by the profiler

---

taichi/transforms/lower_ast.cpp
tests/python/test_for_break.py

Related issue = fixes #5562
This PR changes `i = begin; while (1) { if (i >= end) break; original body; i += 1; }` to `i = begin - 1; while (1) { i += 1; if (i >= end) break; original body; }` to avoid `continue` inside `original body` skip the last statement `i += 1`
The sample code:
```
ti.init(arch=ti.cuda)
@ti.kernel
def test_kernel():
stop = 0
ti.loop_config(serialize=True)
if i % 2 == 0:
continue
print(i)
if stop:
break
test_kernel()
```
The IR before:
```
kernel {
$0 = offloaded  
body {
<i32> $1 = const [0]
<i32> $2 = const [1]
<i32> $3 = const [2]
<i32> $4 = const [10]
<i32> $5 = alloca
$6 : while true {
<i32> $7 = local load [ [$5[0]]]
<i32> $8 = cmp_lt $7 $4
$9 : while control nullptr, $8
<i32> $10 = local load [ [$5[0]]]
<i32> $11 = div …
```

[bug] [ir] Change the way to convert for-loop with break to while-loop

---

taichi/transforms/alg_simp.cpp
tests/python/test_div.py
tests/python/test_mod.py

Related issue = fix #5635
Obviously `0.5 // 1` is `0` instead of `0.5`.

[Bug] [opt] Remove wrong optimization: Float x // 1 -> x

---

taichi/codegen/spirv/spirv_ir_builder.cpp
tests/python/test_basics.py

Fixes #5555
The root cause for the issue above is the input spirv code is invalid so
it errors out when running condtional constant propagation pass in
spirv_opt.
Running `spirv-val` with the generated spirv gives the following error:
```
line:131: OpPhi's incoming basic block <id> 39[%39] is not a predecessor
of <id> 81[%81].
%tmp11_i32 = OpPhi %int %tmp4_i32 %39 %90 %83
```
The bug happens when a simulated atomic ops is followed by a range-for loop where `curr_label_` isn't set properly.
So when we query `spirv::Label init_label = ir_->current_label();` in
the `RangeForStmt` codegen we get the wrong label to use as incoming
block.
It doesn't error out in vulkan backend since we enable float atomic
extension in vulkan backend when it's available by default so that
simulated atomics …

[spirv] [bug] Fix invalid CFG error when simulated atomic is present

---

python/taichi/lang/matrix.py
python/taichi/types/compound_types.py

This PR makes `Vector` an actual class so that code completion could work. Not sure why it was implemented in such way but it feels better not to look up docs all the time.

[lang] Make vector a real class

---

.github/workflows/scripts/aot-demo.sh
docs/lang/articles/contribution/contributor_guide.md

Preview shortcut: https://deploy-preview-5693--docsite-preview.netlify.app/docs/master/contributor_guide#handle-special-ci-failures

[build] Add commit id to taichi-aot-demo for Build-Andriod-Demos CI pipeline

---

python/taichi/aot/utils.py
tests/cpp/aot/llvm/utils.py
tests/python/test_graph.py

[bug] Fix ndarray arg with shape=(1,) in cgraph

---

.github/workflows/testing.yml

[ci] Confine show_environ task to Linux bots

---

taichi/transforms/auto_diff.cpp
tests/python/test_ad_math_func.py

[autodiff] Fix AdStackAllocaStmt not correctly backup

---

docs/lang/articles/differentiable/differentiable_programming.md

[Doc] Add introduction to forward mode autodiff

---

docs/lang/articles/kernels/syntax.md
python/taichi/lang/kernel_impl.py
taichi/inc/constants.h
tests/python/test_aot.py
tests/python/test_argument.py

fixes #5684
The root cause in #5684 is that we used to have a limit of 64 arguments
in total but only the first 16 can be array args. It turns out it's not
enough for some use cases so let's relax that to 32.
Also just noticed that we used to limit number of args to 8 on opengl
backend. Now that we've move it to uniform storage on spirv codegen it
shouldn't be an issue any more.

[vulkan] Relax number of array args for each kernel

---

python/taichi/lang/field.py
python/taichi/lang/matrix.py
tests/python/test_field.py

This was used in difftaichi. `python examples/diffmpm.py`

[bug] Support indexing via np.integer in field

---

python/taichi/ad/_ad.py
tests/python/test_ad_basics_fwd.py

[autodiff] Clear all dual fields when exiting context manager

---

taichi/codegen/spirv/spirv_codegen.cpp
tests/python/test_shared_array.py

Related issue = #5338 
This PR fixes the problem that Vulkan shared array support requires `vk_api_version=1.0`.

[vulkan] Enable shared array for all Vulkan versions.

---

taichi/codegen/spirv/spirv_codegen.cpp
tests/python/test_shared_array.py

Related issue = #5338 
This PR fixes the problem that Vulkan shared array support requires `vk_api_version=1.0`.
This PR rebase #5722 to rc-v1.1.0

[vulkan] Fix vk shared array for v1.1.0

---

build.ps1
cmake/TaichiCAPI.cmake

This PR introduced a minor change in `build.ps1` to allow users to configure builds without touching `CMakeCache.txt`. #5568

[Build] Improve Windows build script

---

python/taichi/lang/impl.py
taichi/program/compile_config.cpp
taichi/program/compile_config.h
taichi/python/export_lang.cpp
tests/python/test_ad_global_data_access_rule_checker.py

Related issue = #5718 
Move the global data access rule checker to experimental.

[autodiff] Move the global data access rule checker to experimental

---

taichi/analysis/offline_cache_util.cpp

reported by `ti example jacobian`

[bug] Fix incorrect autodiff_mode information in offline cache key

---

taichi/codegen/llvm/codegen_llvm.cpp

ByVal attribute requires type in llvm 15.

[llvm] Fix crash caused on ByVal Attribute when switch to llvm 15.

---

c_api/src/c_api_test_utils.cpp
taichi/python/export_misc.cpp
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device_creator.cpp

This PR fixed a validation issue that query pools are not correctly reset before use (for on-device execution time measurement). Also fixed a bit of compilation issue.

[vulkan] Fixed query pool invalid usage

---

taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/util/io.h

Related issue = #4401, fixes #5743
Taichi now raises a warning when the offline cache path does not exist as below:
```
[W 08/12/22 14:09:20.047 1879239] [llvm_offline_cache.cpp:clean_cache@382] Lock /home/lin/.cache/taichi/ticache/metadata.lock failed
```
This PR removes it if the path does not exist.

[Error] Do not show warning when the offline cache path does not exist

---

.github/workflows/scripts/unix_test.sh
.github/workflows/scripts/win_test.ps1

The release test seems to be using the offline cache of previous jobs on Windows and M1.
Moving the offline cache directory into the repository directory solves this because the repository is deleted after the job finishes.

[ci] Prevent using the offline cache of previous jobs

---

taichi/codegen/llvm/codegen_llvm.cpp

Remove the addr_cast to get the global variable for SharedArray when get ptr type for llvm 15.

[llvm] Support SharedArray global when lower PtrOffsetStmt for llvm15.

---

taichi/ui/backends/vulkan/window.cpp

The current implementation attempts to create ND-array with the Window config shape. But the window config shape is not necesarily the shape of the OS-allocated swapchain image size. Leading to the following assertion failure:
```log
[E 08/15/22 11:09:00.350 4032256] [window.cpp:copy_depth_buffer_to_ndarray@127] Size of Depth-Ndarray not matched with the window!
File "/Users/penguinliong/Repositories/taichi-screen-space/x.py", line 58, in <module>
window.get_depth_buffer(zbuf)
File "/Users/penguinliong/Repositories/taichi/python/taichi/ui/window.py", line 172, in get_depth_buffer
self.window.copy_depth_buffer_to_ndarray(tmp_depth.arr)
RuntimeError: [window.cpp:copy_depth_buffer_to_ndarray@127] Size of Depth-Ndarray not matched with the window!
```

[gui] Fixed GGUI crash fetching depth buffer data

---

taichi/aot/module_loader.h
taichi/codegen/spirv/spirv_codegen.cpp

* #5775
* #5774
* __->__ #5773
Note we used to generate invalid spirv shaders during opengl aot and
failed to run spirv-opt passes. But it only generated a warning instead
of an error so we didn't catch this in tests.
This was the second bug triggered by invalid spirv shaders. We
probably should just throw when spirv-opt fails. Alternatively we can
run spirv-val separately if we really want to ignore spirv-opt failures.
Note we don't properly handle gles target device yet, will do that in a
followup PR.

[opengl] Fix target device for opengl aot

---

cmake/TaichiCAPI.cmake

[aot] Workaround C-API build structure to export GGUI symbols in libtaichi_c_api.so

---

taichi/codegen/cuda/codegen_cuda.cpp

Limit TaskCodeGenCUDA::atomic_op_using_cas to llvm 10 build.

[llvm] Disable f16 atomic hack for llvm 15.

---

.github/workflows/testing.yml

Let's disable this job on all forked repos to save some resources.

[ci] Disable show_env job on forked repo

---

taichi/transforms/auto_diff.cpp
tests/python/test_ad_dynamic_index.py
tests/python/test_ad_math_func.py

[autodiff] Support shift ptr in dynamic index

---

taichi/codegen/llvm/codegen_llvm_quant.cpp
tests/python/test_quant_float.py

Related issue = #4857, fix #5817

[Bug] [type] Fix wrong type cast in codegen of storing quant floats

---

taichi/codegen/spirv/spirv_ir_builder.cpp

[vulkan] Fixed crash in SPIR-V CodeGen when a const is declared twice

---

taichi/analysis/offline_cache_util.cpp
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/transforms/auto_diff.cpp
taichi/util/io.h
tests/python/test_ad_dynamic_index.py
tests/python/test_ad_math_func.py
tests/python/test_quant_float.py

Cherrypicking #5770, #5818, #5747, #5737

[misc] Rc v1.1.1 patch1

---

docs/lang/articles/contribution/contributor_guide.md

Finally find a slot to update it. ~_~

[doc] Updated compilation warnings

---

python/taichi/examples/ggui_examples/stable_fluid_ggui.py

I was just tinkering with the stable_fluid_ggui.py example, and noticed that the `gravity = True` option wasn't being used, so I added it into the apply_impulse kernel. You can test that it works now by setting `gravity = False`.

[example] Making gravity option used in stable_fluid_ggui.py

---

python/taichi/lang/matrix.py
python/taichi/lang/ops.py
tests/python/test_compare.py

[Lang] Make python scope comparison return 1 instead of -1

---

python/taichi/lang/_ndarray.py
python/taichi/lang/matrix.py

[Lang] Add @python_scope decorator for selected MatrixNdarray/VectorNdarray methods

---

misc/test_build_cusm_from_coo.py
python/taichi/linalg/sparse_matrix.py
taichi/program/sparse_matrix.cpp
taichi/program/sparse_matrix.h
taichi/python/export_lang.cpp
taichi/rhi/cuda/cusparse_functions.inc.h
tests/python/test_sparse_matrix.py

Related issue = https://github.com/taichi-dev/taichi/issues/2906
It's more convenient for the users to generate COO format sparse matrix. But it's more efficient for the computer to use CSR format sparse matrix. In this pr, we provide a API to construct a CSR format sparse matrix using COO format input ndarrays.

[Lang] Build csr sparse matrix on GPU using coo format ndarray

---

cpp_examples/autograd.cpp
cpp_examples/run_snode.cpp
python/taichi/lang/kernel_arguments.py
taichi/program/callable.cpp
taichi/program/callable.h
taichi/program/program.cpp
taichi/python/export_lang.cpp
taichi/transforms/constant_fold.cpp
tests/cpp/ir/ir_builder_test.cpp
tests/cpp/ir/ndarray_kernel.cpp
tests/cpp/transforms/inlining_test.cpp

But texture arg declaration is still hacky as it abuses `is_array`.
That should be fixed in the followup PRs.

[refactor] Separate texture args from scalar arg declaration

---

c_api/src/taichi_core_impl.cpp
python/taichi/lang/_ndarray.py
python/taichi/lang/kernel_arguments.py
python/taichi/lang/matrix.py
python/taichi/types/compound_types.py
python/taichi/types/ndarray_type.py
python/taichi/types/utils.py
taichi/aot/graph_data.cpp
taichi/ir/type.cpp
taichi/ir/type.h
taichi/ir/type_utils.cpp
taichi/ir/type_utils.h
taichi/program/ndarray.cpp
taichi/program/ndarray.h
taichi/program/program.cpp
taichi/program/program.h
taichi/python/export_lang.cpp
tests/cpp/aot/gfx_utils.cpp
tests/python/test_ndarray.py

Related issue = #5873, #5819
This PR belongs to "Part ②" in #5873, which also covers Part ①.
[Major change]
1. Refactored python-scope `TensorType` to construct & keep a `ptr` with C++ TensorType.
2. Refactored C++ Ndarray to represent matrix-element with `TensorType` instead of the `PrimitiveType + element_shape` combination.
3. Adjust python-scope class `MatrixNdarray` and `VectorNdarray` to adopt refactored `TensorType` and `Ndarray`

[Lang] MatrixNdarray refactor part0: Support direct TensorType construction in Ndarray and refactor use of element_shape

---

taichi/codegen/llvm/codegen_llvm.cpp

Create GEP manually instead of using builder->CreateGEP to keep element type.
If use builder->CreateGEP, PtrOffset lower function will use array type of the shared array instead of element type.
And cause crash for out of bound access.

[llvm] Fix PtrOffset address for shared array in llvm 15.

---

taichi/analysis/value_diff.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/inc/statements.inc.h
taichi/ir/statements.h
taichi/transforms/auto_diff.cpp
taichi/transforms/demote_operations.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_access.cpp
taichi/transforms/simplify.cpp
taichi/transforms/type_check.cpp

Related issue = #4096
In this PR, `lower_vector_ptr()` is rewritten and renamed to `lower_ptr()` so that the legacy `ElementShuffleStmt` can be fully removed.

[refactor] [ir] Remove legacy ElementShuffleStmt

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/ir/type_utils.cpp
tests/python/test_print.py

Related issue = fix #5842
`i8/u8` will be converted to `i16/u16` during printing because CUDA doesn't support `%hhd`/`%hhu` specifers (https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#format-specifiers).

[Bug] [lang] Fix printing i8/u8

---

taichi/analysis/alias_analysis.cpp
taichi/analysis/bls_analyzer.cpp
taichi/analysis/gather_snode_read_writes.cpp
taichi/analysis/gather_uniquely_accessed_pointers.cpp
taichi/analysis/mesh_bls_analyzer.cpp
taichi/analysis/same_statements.cpp
taichi/codegen/cc/codegen_cc.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/metal/codegen_metal.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/ir/control_flow_graph.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/transforms/auto_diff.cpp
taichi/transforms/bit_loop_vectorize.cpp
taichi/transforms/check_out_of_bound.cpp
taichi/transforms/demote_atomics.cpp
taichi/transforms/detect_read_only.cpp
taichi/transforms/flag_access.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_access.cpp
taichi/transforms/make_block_local.cpp
taichi/transforms/make_mesh_block_local.cpp
taichi/transforms/make_thread_local.cpp
taichi/transforms/scalar_pointer_lowerer.cpp
taichi/transforms/type_check.cpp

[refactor] [ir] Remove legacy LaneAttribute usage from ExternalPtrStmt/GlobalPtrStmt

---

taichi/program/compile_config.cpp

Related issue = #5511 
There are some random failures when parallel compilation is on, like #5517 . So we should disable it before we figure out why.

[misc] Disable parallel compilation

---

taichi/program/kernel.cpp

[autodiff] Fix validate autodiff kernel name lost

---

taichi/analysis/data_source_analysis.cpp
taichi/analysis/verify.cpp
taichi/codegen/cc/codegen_cc.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/metal/codegen_metal.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/ir/control_flow_graph.cpp
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
taichi/ir/ir.cpp
taichi/ir/ir.h
taichi/ir/ir_builder.cpp
taichi/ir/statements.h
taichi/ir/type_factory.cpp
taichi/ir/type_factory.h
taichi/transforms/auto_diff.cpp
taichi/transforms/bit_loop_vectorize.cpp
taichi/transforms/demote_atomics.cpp
taichi/transforms/inlining.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_ast.cpp
taichi/transforms/make_block_local.cpp
taichi/transforms/make_mesh_block_local.cpp
taichi/transforms/make_mesh_thread_local.cpp
taichi/transforms/make_thread_local.cpp
taichi/transforms/offload.cpp
taichi/transforms/simplify.cpp
taichi/transforms/type_check.cpp
tests/cpp/analysis/same_statements_test.cpp
tests/cpp/transforms/alg_simp_test.cpp

Related issue = close #4096
As far as I can see, after this PR, the legacy skeleton code for vectorization is fully removed. There might still be missing pieces but I think the codebase is already much cleaner now.

[refactor] [ir] Remove legacy LocalAddress / VectorElement / create_vector_or_scalar_type()

---

taichi/codegen/codegen.h
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cpu/codegen_cpu.h
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/cuda/codegen_cuda.h
taichi/codegen/wasm/codegen_wasm.cpp
taichi/codegen/wasm/codegen_wasm.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/wasm/aot_module_builder_impl.cpp

Related issue = #5511 
Renamed `codegen` to `compile_to_function`.
Renamed `modulegen` to `compile_task`.

[llvm] [refactor] Rename methods in KernelCodeGen

---

python/taichi/profiler/kernel_metrics.py
python/taichi/profiler/kernel_profiler.py

Related issue = #5627 
About SM Throughput metric, since "sm__throughput" metric cannot be found in the latest CUPTI document, please let me know if the relative modification is correct.

[bug] Fix minor issue for CUPTI kernel profiler

---

taichi/codegen/llvm/llvm_codegen_utils.cpp

Related issue = #5511 
After splitting the modules, both the type names can be `xxx.yyy` where `yyy` are digits.

[llvm] Enhance function is_same_type

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/runtime/llvm/llvm_context.cpp

Related issue = #3382
These functions are repeating each other. Let's only keep one.

[refactor] [llvm] Unify llvm_type() and get_data_type()

---

taichi/transforms/auto_diff.cpp

Make the adjoint checkbit value type consistent to the destination/source field.

[autodiff] Fix adjoint checkbit type in gdar checker

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/llvm_context.h

Related issue = #5511
This PR renames and refactors some functions in TaichiLLVMContext, adds many helper functions which will be used in the future PRs without breaking the current code.
This PR also adds `struct_modules` to `ThreadLocalData` which will replace `struct_module` in the future PRs.

[llvm] [refactor] Refactor and add code about llvm modules

---

CMakeLists.txt

@Morcki  can you help verify if Taichi builds on your Mac with this PR?

[bug] Force CMAKE_OSX_ARCHITECTURES in sync with host processor's architecture to avoid ABI issues on Mac m1

---

taichi/rhi/vulkan/vulkan_device_creator.cpp

This PR temprarily allows extensions to be enabled based on device-capability in the C-API. This workaround should be replaced by a more formal device capability mechanism before the next major release.

[aot] Temporarily allow Vulkan extensions to be automatically enabled in C-API runtimes

---

c_api/include/taichi/taichi.h
c_api/include/taichi/taichi_opengl.h
c_api/src/taichi_opengl_impl.cpp
c_api/src/taichi_opengl_impl.h
cmake/TaichiCAPITests.cmake
taichi/rhi/opengl/opengl_device.cpp
taichi/rhi/opengl/opengl_device.h

See an example usage in:
https://github.com/ailzhang/taichi-aot-demo/blob/gl_demo/mpm88_gl/mpm88.cpp#L158-L159

[aot] [opengl] Add GL interop so that we can export GL memory

---

python/taichi/lang/any_array.py
python/taichi/lang/field.py
python/taichi/lang/impl.py
python/taichi/lang/snode.py
python/taichi/lang/struct.py
taichi/analysis/gen_offline_cache_key.cpp
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
taichi/python/export_lang.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_ast.cpp
tests/cpp/ir/frontend_type_inference_test.cpp

Related issue = #5959
Previously, a `GlobalVariableExpression` serves two purposes:
- representing a field;
- being a wrapper of a (maybe intermediate) SNode so that no matter a `FrontendForStmt` is actually a struct for on a SNode or an external tensor, it can always be constructed by passing an `Expr`.
However, the second purpose doesn't make sense - a struct for on a SNode and a struct for on an external tensor are handled differently everywhere (`lower_ast`, `ir_printer`, ...), so it's natural to split the constructors as well.
This PR clearly and consistently distinguishes different types of `FrontendForStmt`:
- a struct for on a SNode (`snode != nullptr`);
- a struct for on an external tensor (`external_tensor != nullptr`);
- a mesh for (`mesh != nullptr`);
- a range for (other).
As …

[ir] MatrixField refactor 1/n: Make a GlobalVariableExpression solely represent a field

---

taichi/cache/gfx/cache_manager.cpp
taichi/cache/gfx/cache_manager.h
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/program_impls/vulkan/vulkan_program.cpp
taichi/util/offline_cache.h
tests/python/test_offline_cache.py

[vulkan] Implement offline cache cleaning on vulkan

---

taichi/rhi/cuda/cuda_context.cpp
taichi/rhi/cuda/cuda_driver_functions.inc.h
taichi/runtime/llvm/llvm_runtime_executor.cpp

Related issue = #5502
PR #5891 solved the problem but the fix is fragile. Using primary context instead of `cuCtxCreate` could also work with PyTorch and Numba. The context management code are no longer needed and reverted.

[cuda] Use CUDA primary context to work with PyTorch and Numba.

---

taichi/codegen/dx12/CMakeLists.txt
taichi/codegen/dx12/codegen_dx12.cpp
taichi/codegen/dx12/dx12_global_optimize_module.cpp
taichi/codegen/dx12/dx12_llvm_passes.h

Run llvm coden gen for DirectX backend.
No real dxil will output yet.
Need add pass to transform the llvm module into the shape DirectX backend can consume.

[dx12] Drop code for dxil generation.

---

python/taichi/lang/field.py
python/taichi/lang/impl.py
python/taichi/lang/matrix.py

When `x_grad` or `x_dual` is `None`, they should not be used to initialize the `Field` class.

[autodiff] Avoid initializing Field with None

---

taichi/util/offline_cache.h

`KernelMetadata` is recognized by NDK compiler as a nested class in `Metadata`.

[lang] Fixed compilation

---

python/taichi/lang/kernel_impl.py
tests/python/test_torch_ad.py
tests/python/test_torch_io.py

These io are through torch cpu tensors, not really the most efficient solution but should
be working at least.

[refactor] Turn on torch_io tests for opengl, vulkan and dx11 backend

---

tests/python/test_runtime.py

Related PR = #6002
In #6002, `test_init_arg` and `test_init_arch` fails on Windows. The failure is caused by reading outdated offline cache format. However, we have set offline cache to off and set the offline cache directory to a new directory in the environment variables in `run_tests.py`, so this should not happen. Then, I discovered that function `patch_os_environ_helper` which intends to remove only a few specified environment variables (`excludes`) accidentally removes all the environment variables, and replaced them with `custom_environ`. This PR fixes the bug and lets it work as expected.

[bug] [test] Fix patch_os_environ_helper

---

taichi/codegen/cc/runtime/base.h
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/runtime/llvm/runtime_module/runtime.cpp
tests/python/test_abs.py

I found that `abs(i64)` was not supported while fixing #5915. This PR adds support for that.

[Lang] Support abs(i64)

---

c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi_core.h
c_api/include/taichi/taichi_vulkan.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_vulkan_impl.cpp
c_api/src/taichi_vulkan_impl.h
c_api/taichi.json
c_api/tests/c_api_cgraph_test.cpp
c_api/tests/c_api_interface_test.cpp
misc/generate_c_api.py
misc/generate_unity_language_binding.py
misc/taichi_json.py
taichi/inc/address_mode.inc.h
taichi/inc/filter.inc.h
taichi/rhi/vulkan/vulkan_api.cpp
taichi/util/offline_cache.h
tests/cpp/aot/python_scripts/texture_aot_test.py
tests/test_utils.py

This PR improved existing texture interfaces and added related tests. Sampler interfaces are reserved.

[aot] C-API texture support and tests

---

cmake/TaichiCAPITests.cmake
cmake/TaichiExamples.cmake
cmake/TaichiTests.cmake
tests/run_tests.py

Output all exes to build/
> This PR moves it to bin\, which is in the PATH and we can run taichi_cpp_tests everywhere.
>    --from https://github.com/taichi-dev/taichi/pull/2515#issue-941918398
IMO, we should run cpp/capi tests by running `python run_tests.py --cpp` instead of launching `taichi_cpp_tests(.exe)` manually

[bug] [test] Run C-API tests correctly on Windows

---

c_api/include/taichi/cpp/taichi.hpp

Follow up of #5994. Clang follows a strict separation between C++ headers so fundamental utilities like `std::exchange` is not implicitly included in other `std` headers.

[aot] Fixed compilation on Linux distros

---

taichi/cache/gfx/cache_manager.cpp
taichi/runtime/gfx/aot_module_loader_impl.cpp
taichi/runtime/gfx/aot_module_loader_impl.h

ps: The above testing was run in an environment with **100MB+** cache files.
(100MB is the default value of `offline_cache_max_size_of_files`

[misc] Lazy load spirv code from disk during offline cache

---

taichi/codegen/codegen.cpp
taichi/codegen/codegen.h
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cpu/codegen_cpu.h
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/cuda/codegen_cuda.h
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/llvm_compiled_data.h
taichi/codegen/wasm/codegen_wasm.cpp
taichi/codegen/wasm/codegen_wasm.h
taichi/runtime/cpu/aot_module_builder_impl.cpp
taichi/runtime/cpu/aot_module_builder_impl.h
taichi/runtime/cuda/aot_module_builder_impl.cpp
taichi/runtime/cuda/aot_module_builder_impl.h
taichi/runtime/llvm/llvm_aot_module_builder.h
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/llvm_context.h
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h
tests/cpp/codegen/refine_coordinates_test.cpp

Related issue = #5511 
The compiler first compiles every offloaded task to a `LLVMCompiledTask` which contains an LLVM module, the name of the offloaded task function inside the module, and some extra information for linking. Then, The compiler links the modules in the `LLVMCompiledTask`s, the runtime modules and the struct modules used in the kernel together, and creates a `LLVMCompiledKernel` that contain the linked LLVM module and the names of the offloaded tasks.
Both `LLVMCompiledTask` and `LLVMCompiledKernel` need to store the generated LLVM module and the names of the functions of the offloaded tasks inside the module. `LLVMCompiledTask` also stores additional information which will be used when linking like which SNodeTrees are used and the sizes of TLS buffers used in parallel …

[llvm] [refactor] Split LLVMCompiledData of kernels and tasks

---

taichi/util/offline_cache.h

```
/home/yc/taichi/taichi/util/offline_cache.h:59:9: error: declaration of 'using KernelMetadata = struct taichi::lang::offline_cache::KernelMetadata' changes meaning of 'KernelMetadata' [-fpermissive]
59 |   using KernelMetadata = KernelMetadata;
|         ^~~~~~~~~~~~~~
```

[build] Fix compile error on gcc

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/metal/codegen_metal.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/runtime/llvm/runtime_module/runtime.cpp
taichi/runtime/metal/shaders/helpers.metal.h

Related issue = #5915
As `pow()` with integer exponent is already demoted (#6044), there's no need for backends to handle integer pows.

[lang] Remove redundant codegen of integer pow

---

docs/lang/articles/debug/debugging.md
python/taichi/lang/ast/ast_transformer_utils.py
tests/python/test_exception.py

Follow the Python stacktrace convention to support click-jump to the exact line of compiler error in VS Code.

[lang] Reformat source indicator in Python convention

---

.github/workflows/scripts/aot-demo.sh
taichi/aot/module_data.h
taichi/rhi/device.h
taichi/runtime/gfx/aot_module_builder_impl.cpp
taichi/runtime/gfx/aot_utils.h

To enable device capability checks during module loads so that the user won't crash in graph or kernel execution, this PR introduces a map of device capabilities assumed by the compiler, so the C-API can lookup module compatibility with the created runtime in a future PR.

[aot] Dump required device capability in AOT module meta

---

taichi/codegen/dx12/CMakeLists.txt
taichi/codegen/dx12/dx12_global_optimize_module.cpp
taichi/codegen/dx12/dx12_llvm_passes.h
taichi/codegen/dx12/dx12_lower_intrinsic.cpp
taichi/codegen/dx12/dx12_lower_runtime_context.cpp

2 passes are added for DXIL generation.
TaichiIntrinsicLower will translate taichi intrinsic like thread_idx into the form DirectX backend expected.
TaichiRuntimeContextLower will translate the TaichiRuntimeContext parameter for kernel into Buffers/ConstantBuffers. 
TaichiRuntimeContextLower is empty now.
It is added after inline so optimizations reduce the load/store on temp ptr. And it is easier to know a store is on the TaichiRuntimeContext.

[dx12] Drop code for llvm passes which prepare for DXIL generation.

---

.github/workflows/release.yml
.github/workflows/testing.yml
ci/Dockerfile.ubuntu.18.04

[ci] Upgrade conda cudatoolkit version to 11.3

---

.github/workflows/scripts/win_build_test_cpu.ps1
taichi/codegen/dx12/codegen_dx12.cpp
taichi/codegen/dx12/codegen_dx12.h

Fix build fail and enable dx12 build for windows cpu ci to make sure it compiles.

[ci] [dx12] Enable dx12 build for windows cpu ci.

---

taichi/aot/module_builder.cpp

Run `python run_tests.py --cpp --with-offline-cache` failed, reported by https://github.com/taichi-dev/taichi/actions/runs/3055000542. Reason: Generate AST key ([1]) after lowering ([2]).
[1]
https://github.com/taichi-dev/taichi/blob/72804ae992212ddee5357bae8b27d6e3f2148831/taichi/codegen/codegen.cpp#L92
[2]
https://github.com/taichi-dev/taichi/blob/72804ae992212ddee5357bae8b27d6e3f2148831/taichi/aot/module_builder.cpp#L8-L10

[bug] Remove unnecessary lower() in AotModuleBuilder::add

---

taichi/ir/frontend_ir.h
tests/python/test_matrix_different_type.py

Related issue = #5959, #4857
Support for different element types of matrix fields was introduced in #2135 for quant. As discussed in https://github.com/taichi-dev/taichi/issues/4857#issuecomment-1123964395, the only case we need to support is different element types with **same compute type**. This PR adds the validity check and removes test cases which are actually not allowed.

[Lang] MatrixField refactor 4/n: Disallow invalid matrix field definition

---

cmake/TaichiTests.cmake
taichi/cache/gfx/cache_manager.cpp
taichi/common/serialization.h
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/runtime/llvm/llvm_offline_cache.h
taichi/util/io.h
taichi/util/offline_cache.h
tests/cpp/offline_cache/load_metadata_test.cpp

Issue: #4401, fixes #6081
In future, if necessary, we should maintain a version number for offline cache instead of using the Taichi version directly.

[bug] Fix crashing when loading old offline cache files

---

CMakeLists.txt
cmake/TaichiCXXFlags.cmake
setup.py
taichi/program/program.cpp
taichi/system/timer.cpp

This PR enables Taichi to be built into multi-target libraries. Recent releases of macOS supports dynamically linking against x86_64 or arm64 of the same `.dylib` on demand, depending on the arch of the parent process. Previously this was not possible because the CMake script forced a `-march=nehalem` that is not a kind of arm64; and `CMAKE_OSX_ARCHITECTURES` is forced `arm64`.
The multi-target feature is only enabled with `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`. Python builds will select one of the archs, based on the arch of the skbuild Python process.

[aot] Support multi-target builds for Apple M1

---

cmake/TaichiCore.cmake
taichi/rhi/opengl/CMakeLists.txt

Building with `TI_WITH_OPENGL:BOOL=OFF` and `TI_WITH_DX11:BOOL=ON` failed:
```
FAILED: taichi_python.cp37-win_amd64.pyd
cmd.exe /C "cd . && D:\programming_tools_\LLVM14\bin\clang++.exe -fuse-ld=lld-link -nostartfiles -nostdlib -DTI_ISE_NONE -std=c++17 -fsized-deallocation -target x86_64-pc-windows-msvc -DTI_ARCH_x64 -march=nehalem -DTI_PASS_EXCEPTION_TO_PYTHON -DTI_INCLUDED -DTI_WITH_LLVM -DTI_WITH_CUDA -DTI_WITH_METAL -DTI_WITH_DX11 -DTI_WITH_VULKAN  -DTI_ISE_NONE -flto=thin -D_DLL -D_MT -Xclang --dependent-lib=msvcrt   -shared -o taichi_python.cp37-win_amd64.pyd  -Xlinker /MANIFEST:EMBED -Xlinker /implib:taichi_python.lib -Xlinker /pdb:taichi_python.pdb -Xlinker /version:0.0 @CMakeFiles\taichi_python.rsp  && cd ."
lld-link: error: could not open 'spirv-cross-hlsl.lib': no such file or …
```

[build] Fix building with TI_WITH_OPENGL:BOOL=OFF and TI_WITH_DX11:BOOL=ON failed

---

docs/lang/articles/basic/layout.md

In the [discussion](https://github.com/taichi-dev/taichi/issues/5491#issuecomment-1214559018) in issue # 5491, @strongoier pointed out that nested dense statements are different from a plain 2D field layout. Update the description on this topic accordingly.
Related issue = # 5491

[doc] Update explanation on data-layout 

---

c_api/include/taichi/taichi_vulkan.h
c_api/src/taichi_vulkan_impl.cpp
c_api/taichi.json
misc/generate_c_api.py
taichi/rhi/vulkan/vulkan_device.h
taichi/rhi/vulkan/vulkan_loader.cpp
taichi/rhi/vulkan/vulkan_loader.h

In the current implementation, Vulkan instance created by an external MoltenVK cannot be imported via C-API because Taichi would attempt to load `libMoltenVK.dylib` by itself and it leads to a crash if the external MoltenVK is linked to the application. This PR introduce a new (optional) interop entry of `vkGetInstanceProcAddr` so that externally loaded vulkan library can be reused.
This could be an extension to the discussion in #6083 . Statically linking to MoltenVK is potentially saving us from all these hazards.

[aot] Import MoltenVK

---

misc/make_changelog.py

There are more than 200 commits in v1.1.3 (https://github.com/taichi-dev/taichi/releases/tag/v1.1.3) so let's increase the number of commits for changelog generation.

[misc] Allow more commits in changelog generation

---

taichi/rhi/opengl/opengl_api.cpp
taichi/rhi/opengl/opengl_device.cpp
tests/python/test_aot.py

Issue: #5769 
GLES support was broken since the migration to spirv-based codegen and this PR is the first step to bring it back. Also added a bunch of `check_opengl_error` calls to make debugging easier. 
Note thorough testing for GLES backend is currently missing and should be added in followup PRs.

[opengl] Fix GLES support

---

python/taichi/lang/impl.py
taichi/inc/statements.inc.h
taichi/ir/expr.cpp
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/ir/transforms.h
taichi/transforms/compile_to_offloads.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_matrix_ptr.cpp
tests/python/test_matrix.py

Issue: #5959
This PR lowers access of matrix field element into CHI IR. To verify its functionality, this PR also makes the following path of #5959 running end-to-end (currently only enabled when `real_matrix=True`):
Key steps:
- Python: when running into subscript of `MatrixField`, create `IndexExpression` in C++ instead of building `_MatrixFieldElement` in Python
- Frontend IR: allow `IndexExpression` to take `MatrixFieldExpression`
- CHI IR: add `MatrixOfGlobalPtrStmt`; add `lower_matrix_ptr` pass, which demotes `PtrOffsetStmt(MatrixOfGlobalPtrStmt)` into `GlobalPtrStmt` in the case of constant index - this is incomplete and only aims at supporting the above path

[Lang] MatrixField refactor 5/n: Lower access of matrix field element into CHI IR

---

taichi/rhi/vulkan/vulkan_device_creator.cpp

related: #5350
Thanks @turbo0628 and @lin-hitonami for catching this! It turns out codegening non-semantic info spirv code isn't no-op when validation is off. It slows down the program execution so we should properly guard it.

[bug] [vulkan] Only enable non_semantic_info cap when validation layer is on

---

taichi/codegen/llvm/llvm_codegen_utils.cpp
taichi/codegen/llvm/llvm_codegen_utils.h
tests/cpp/llvm/is_same_type_test.cpp

Issue: #5511
is_same_type fails when it encounters comparison between `%struct.PhysicalCoordinates.1` and `%struct.PhysicalCoordinates.11` where `1` is the prefix of `11`.
This bug does not affect 1.1.3 because parallel compilation is turned off in 1.1.3.

[bug] [llvm] Fix is_same_type when the suffix of a type is the prefix of the suffix of the other type

---

taichi/codegen/spirv/spirv_ir_builder.cpp

Reverts taichi-dev/taichi#5212
PR #5212 fixes a warning on Vulkan validation layer, but it introduces performance regression to Vulkan backend.

Revert "[spirv] Fixed OpLoad with physical address"

---

taichi/codegen/spirv/spirv_ir_builder.cpp

Issue: #6072
Ref #6136
We misread the specs, the `aligned` parameter takes a uint literal, not a value. We used to feed in a value, but since SPIR-V wouldn't care, we are actually feeding the value id as an alignment and probably causing performance regression due to that.

[vulkan] Fix SPV physical ptr load alignment

---

c_api/include/taichi/cpp/taichi.hpp
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_loader.cpp

[aot] Improve C++ wrapper implementation

---

.git-blame-ignore-revs
.github/workflows/testing.yml

[ci] Fix build cache problems

---

python/taichi/lang/common_ops.py
taichi/codegen/spirv/spirv_codegen.cpp
taichi/ir/stmt_op_types.h
taichi/transforms/demote_operations.cpp
tests/python/test_bit_operations.py

While I was removing redundant codegen for `shr` (#6134), I found that augmented assign for `sar` was accidentally calling `shr`, so I fixed it by the way.

[Bug] [lang] Fix augmented assign for sar

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/ir/statements.h
taichi/runtime/llvm/llvm_context.cpp

Issue: #5959
This PR enforces that the return value of `AllocaStmt(TensorType)/GlobalTemporaryStmt(TensorType)` is a pointer to a `VectorType/ArrayType` (we no longer use a primitive type ptr for `TensorType`) so that the codegen can be simplified a lot.

[llvm] MatrixField refactor 7/n: Simplify codegen for TensorType allocation and access

---

docs/lang/articles/contribution/doc_writing.md
docs/lang/articles/reference/global_settings.md

[Doc] Fixed broken links

---

taichi/transforms/lower_matrix_ptr.cpp
tests/python/test_matrix.py

Issue: #5959
This PR makes the rightmost path of #5959 running end-to-end.

[Lang] MatrixField refactor 9/n: Allow dynamic index of matrix field when real_matrix=True

---

tests/run_tests.py

Issue: #
After this PR, we're able to run user-specified cpp tests via `python tests/run_tests.py -cpp -k xxx`. 
Supports C-API tests, AOT tests and regular tests.
1. C-API tests: `python3 tests/run_tests.py --cpp -k CapiAotTest.*Field`
2. AOT tests: `python3 tests/run_tests.py --cpp -k LlvmAotTest.Cuda.*`
3. Regular cpp tests: `python3 tests/run_tests.py --cpp -k Scalarize.*`

[build] Support executing manually-specified cpp tests for run_tests.py

---

taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/dx12/codegen_dx12.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/llvm/codegen_llvm_quant.cpp
taichi/codegen/llvm/llvm_codegen_utils.h

Issue: #3382
Currently `create_call` in `TaskCodeGenLLVM` and `call` in `LLVMModuleBuilder` do the same thing so they should be merged.

[llvm] [refactor] Merge create_call and call

---

c_api/src/c_api_test_utils.h
c_api/src/taichi_core_impl.h
c_api/src/taichi_llvm_impl.cpp
c_api/tests/c_api_aot_test.cpp
c_api/tests/c_api_cgraph_test.cpp
c_api/tests/c_api_interface_test.cpp
c_api/tests/c_api_interop_test.cpp
c_api/tests/comet.cpp
c_api/tests/gtest_fixture.h
c_api/tests/mpm88_test.cpp
c_api/tests/sph.cpp
c_api/tests/taichi_sparse_test.cpp
tests/test_config.json

[aot] Apply ti_get_last_error_message() for all C-API test cases

---

taichi/ir/statements.h
taichi/transforms/compile_to_offloads.cpp
taichi/transforms/die.cpp
taichi/transforms/scalarize.cpp
tests/cpp/transforms/scalarize_test.cpp

Related issue = https://github.com/taichi-dev/taichi/issues/5873, https://github.com/taichi-dev/taichi/issues/5819
This PR is working "Part ④" in https://github.com/taichi-dev/taichi/issues/5873.

[Lang] MatrixNdarray refactor part10: Remove redundant MatrixInitStmt generated from scalarization

---

taichi/transforms/auto_diff.cpp
tests/python/test_ad_if.py

Issue: #6204 
Autodiff failed on cases where the condition of a if depends on the for loop index. This PR makes the if condition stored in adstack to handle these cases.

[autodiff] Store if condition in adstack

---

docs/lang/articles/math/math.md
docs/lang/articles/math/math_module.md

[Doc] Update math module

---

docs/lang/articles/reference/global_settings.md

[Doc] Update global settings

---

taichi/program/program.cpp
taichi/util/offline_cache.cpp
taichi/util/offline_cache.h

[misc] Disable the offline cache if printing ir is enabled

---

6186.py
python/taichi/lang/snode.py
tests/python/test_fields_builder.py

[Bug] [lang] Allow numpy int as snode dimension

---

taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.cpp
taichi/codegen/spirv/spirv_ir_builder.h
taichi/transforms/demote_operations.cpp

Issue: https://github.com/taichi-dev/taichi/pull/6141#issuecomment-1255339288, #6134
In SPIR-V there's actually `OpBitFieldUExtract` which does the job of `BitExtractStmt` perfectly, so let's stop demoting `BitExtractStmt` and let codegen handle it with the best instruction(s).

[spirv] Generate OpBitFieldUExtract for BitExtractStmt

---

python/taichi/ad/_ad.py
python/taichi/lang/field.py
tests/python/test_ad_grad_check.py

Currently Taichi uses autodiff as its differentiation system. We compute gradients of variables in a computation procedure through source code transformation, which is to add additional instructions to the IR layer. However, it's hard for users to check whether the autodiff system computes correct results. Thus, we need a grad check system to verify results given by autodiff.
We implement grad check in the python frontend, using finite difference method. Users only need to pass variables they want to check to the autodiff tape scope, and then our grad check system will automatically check whether autodiff gives the correct answer, prompting error messages if not. The API can be used in the following way.
```python
import numpy as np
ti.init(ti.gpu, default_fp=ti.f64)
x …
```

[autodiff] Add grad check feature and related test

---

python/taichi/lang/kernel_impl.py

[bug] Prevent ti.kernel from directly caching the passed-in arguments to avoid memory leak

---

taichi/transforms/type_check.cpp
tests/python/test_indices.py

[bug] Convert non-i32 type indices to i32 for GlobalPtrStmt

---

cmake/TaichiCAPI.cmake

Issue: #
LLVM AOT rely on *.bc files (`runtime_cuda.bc`, ...) at runtime, thus we have to ship those runtime files together with C-API once TI_WITH_LLVM is enabled.
Under installed directory `{install_dir}/taichi-xxxx.egg/c_api/`:
Before:
```
include
lib/libtaichi_c_api.so
lib/cmake
```
After:
```
include
lib/libtaichi_c_api.so
lib/cmake
lib/runtime/*.bc
```

[aot] Ship runtime *.bc files with C-API for LLVM AOT

---

taichi/ir/frontend_ir.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/transforms/lower_access.cpp
taichi/transforms/lower_ast.cpp
taichi/transforms/type_check.cpp
tests/python/test_sparse_basics.py

Issue: fix #6274
`GlobalPtrStmt` actually has two semantics:
- When it is part of an activation-related `SNodeOpStmt` (`ti.activate(), ti.deactivate(), ti.is_active()`) and the SNode is not of type `dynamic`, the indices are actually targeting a SNode **cell**;
- Otherwise, the indices are targeting the SNode **container**.
The original dimension check in the `type_check()` pass only targets the second case, which results in the false alarm in #6274.

[Bug] [lang] Make dimension check for GlobalPtrStmt aware of whether it is a cell access

---

taichi/codegen/metal/codegen_metal.cpp
taichi/runtime/metal/kernel_manager.cpp
taichi/runtime/metal/kernel_utils.cpp
taichi/runtime/metal/kernel_utils.h

Issue: #6263 
Fix bug reported by `TI_WIP_OFFLINE_CACHE=1 python3 run_tests.py -a metal -vr2 --with-offline-cache --rerun-with-offline-cache 1 debug  ast_refactor assert sparse_deactivate sparse_parallel`

[bug] Serialize missing fields of metal::TaichiKernelAttributes and metal::KernelAttributes

---

taichi/ir/frontend_ir.cpp
tests/python/test_matrix.py

Issue: #5819
It is possible that a local matrix is indexed without being assigned to a variable:
```python
@ti.kernel
def local_vector_read(i: ti.i32) -> ti.i32:
return ti.Vector([0, 1, 2])[i]
```
In this case we need to turn it from an r-value to an l-value so that we can successfully construct the index.

[lang] MatrixType bug fix: Allow indexing a matrix r-value

---

.github/workflows/scripts/unix_test.sh
.github/workflows/scripts/win_test.ps1
.github/workflows/testing.yml

[ci] Add more release tests

---

taichi/runtime/metal/kernel_manager.cpp

Issue: #6263 
Ignoring kernels which have been registered is required by `metal::CacheManager`.
Bug reported by `TI_WIP_OFFLINE_CACHE=1 python3 run_tests.py -a metal -vr2 --with-offline-cache --rerun-with-offline-cache 1 compare cast numpy`

[bug] Fix asserting failed when registering kernels with same name on Metal

---

python/taichi/lang/ast/ast_transformer.py
taichi/program/compile_config.cpp
tests/python/test_function.py

Issue: #https://github.com/taichi-dev/taichi/issues/5819

[lang] MatrixType bug fix: Avoid checks for legacy Matrix-class when real_matrix is on

---

taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.cpp
taichi/ir/type_utils.cpp
taichi/runtime/gfx/runtime.cpp
tests/python/test_overflow.py

Issue: #5932 
Added overflow detection of addition, subtraction, multiplication and shift left operators on Vulkan. 
Known bug: 64-bit multiplication overflow detection works on NVIDIA driver 510 with Vulkan version 1.3.194 but does not work on NVIDIA driver 470 with Vulkan version 1.2.175. See https://github.com/taichi-dev/taichi/issues/6303
TODO: Support for OpenGL should be automatically available when the print support of OpenGL is available. Add OpenGL to the test at that time.

[Vulkan] Add overflow detection on vulkan when debug=True

---

.github/workflows/scripts/win_build.ps1
taichi/codegen/spirv/spirv_codegen.cpp
taichi/ir/type_utils.cpp
taichi/ir/type_utils.h
tests/python/test_print.py

[Vulkan] [bug] Change the format string of 64bit unsigned integer type from %llu to %lu

---

docs/lang/articles/performance_tuning/performance.md

[doc] Update the document about offline cache

---

.github/workflows/scripts/unix_test.sh
.github/workflows/testing.yml

Continued from #6310.
Changes of mesh.py in taichi need to be merged before this CI change.

[ci] Add end-to-end CI tests for meshtaichi

---

.clang-tidy
.github/workflows/testing.yml
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/program/kernel.cpp
taichi/program/sparse_matrix.h
taichi/python/export_lang.cpp
taichi/python/export_misc.cpp

* #6335
* #6334
* #6333
* __->__ #6332
* #6331
* #6330
- bugprone-argument-comment
- bugprone-assert-side-effect
- bugprone-dangling-handle
- bugprone-inaccurate-erase
- bugprone-string-integer-assignment
- bugprone-use-after-move
- bugprone-string-constructor
- bugprone-unused-raii

[build] Enable a few bugprone related rules in clang-tidy

---

python/taichi/lang/impl.py
taichi/ir/frontend_ir.cpp
taichi/transforms/scalarize.cpp
tests/python/test_matrix.py

Related issue = https://github.com/taichi-dev/taichi/issues/5873, https://github.com/taichi-dev/taichi/issues/5819
This PR is working "Part ④" in https://github.com/taichi-dev/taichi/issues/5873.
Before scalarization:
```
TensorType<4 x i32> val = AtomicStmt(TensorType<4 x i32>* dest,
TensorType<4 x i32>  val)
```
After scalarization:
```
i32* dest_ptr_0 = MatrixPtrStmt(dest, 0)
i32* dest_ptr_1 = MatrixPtrStmt(dest, 1)
i32* dest_ptr_2 = MatrixPtrStmt(dest, 2)
i32* dest_ptr_3 = MatrixPtrStmt(dest, 3)
i32 dest_val0 = AtomicStmt(dest_ptr_0,
val->cast<MatrixInitStmt>()->val[0])
i32 dest_val1 = AtomicStmt(dest_ptr_1,
val->cast<MatrixInitStmt>()->val[1])
i32 dest_val2 = AtomicStmt(dest_ptr_2,
val->cast<MatrixInitStmt>()->val[2])
i32 dest_val3 = AtomicStmt(dest_ptr_3, …
```

[Lang] MatrixNdarray refactor part12: Add scalarization for AtomicOpStmt

---

tests/python/test_sparse_linear_solver.py

This test fails consistently on my machine as atol is too strict, switching to rtol instead.
Issue: #

[test] Adjust rtol for sparse_linear_solver tests

---

.clang-tidy
taichi/common/exceptions.h
taichi/program/sparse_solver.cpp
taichi/python/exception.h
taichi/runtime/gfx/runtime.cpp
taichi/runtime/metal/shaders/print.metal.h
taichi/system/demangling.cpp
taichi/system/memory_pool.cpp
taichi/system/traceback.cpp
taichi/transforms/lower_matrix_ptr.cpp

* #6345
* #6344
* #6343
* __->__ #6342
- modernize-make-shared
- modernize-make-unique
- modernize-use-bool-literals
- modernize-use-equals-default
- modernize-use-equals-delete
- modernize-use-noexcept
- modernize-use-nullptr
- modernize-use-transparent-functors

[build] Enable a few modernize checks in clang-tidy

---

.clang-tidy
taichi/transforms/alg_simp.cpp
taichi/transforms/binary_op_simplify.cpp
taichi/transforms/check_out_of_bound.cpp
taichi/transforms/constant_fold.cpp
taichi/transforms/demote_atomics.cpp
taichi/transforms/demote_operations.cpp
taichi/transforms/detect_read_only.cpp
taichi/transforms/inlining.cpp

* #6345
* __->__ #6344
* #6343
* #6342

[build] Enable readability-redundant-member-init in clang-tidy check

---

taichi/python/export_misc.cpp

This fixes the following error when opengl build is turned off:
```
Invoked with: False' occurred when detecting opengl, consider adding `TI_ENABLE_OPENGL=0`  to environment variables to suppress this warning message.
[W 10/17/22 21:43:05.396 46857808] TypeError: 'with_opengl(): incompatible function arguments. The following argument types are supported:
1. () -> bool
```
Issue: #

[opengl] Fix with_opengl when TI_WITH_OPENGL is off

---

python/taichi/lang/impl.py
taichi/program/compile_config.cpp
taichi/python/export_lang.cpp
tests/python/test_ad_global_data_access_rule_checker.py

Issue: #6239 
Remove the `validate_autodiff` flag in `ti.init`.

[autodiff] Move autodiff gdar checker to release

---

taichi/transforms/compile_to_offloads.cpp

Issue: #6239 
Skip gradient kernel compilation for validation kernel

[autodiff] Skip gradient kernel compilation for validation kernel

---

python/taichi/examples/simulation/laplace_equation.py

This is a 2D-Simulation of fundamental solutions of Laplace equation
moer details on https://forum.taichi-lang.cn/t/topic/2879

[example] Add example "laplace equation"

---

python/taichi/lang/ast/ast_transformer.py
tests/python/test_ndrange.py

[Error] Add error message when the number of the loop variables does not match the dimension of the ndrange

---

python/taichi/ad/_ad.py
python/taichi/lang/kernel_impl.py
taichi/program/kernel.cpp
tests/python/test_ad_global_data_access_rule_checker.py

Issue: #6240 
Handle cases that there are loops inside the `ti.ad.tape`. In these cases, the `autodiff_mode` has not been recovered to `AutodiffMode.NONE` since `__exit__` of the tape has not been reached.

[autodiff] Fix mode capture for validation kernels

---

python/taichi/lang/kernel_impl.py
tests/python/test_numpy.py

fixes #6305
Taichi kernel assumes input external array are row major / c_contiguous for now so this PR throws an error message when the input numpy array isn't contiguous.
Note that we only supports inplace update for c_contiguous numpy arrays but for historical reason support for f_contiguous array was added via copying (`ascontiguousarray()`) as well, thus this PR tries to preserve the support to avoid breaking old code.
Also the support for f_contiguous numpy array was halfly done since `ascontiguousarray()` may return a new numpy array, Taichi kernels just read/write on the copied array and don't copy the values back to the original numpy array.
This PR fixes the bug mentioned above by adding a callback function to copy values back, although copying behavior isn't efficient it …

[bug] [lang] Fix copyback for fortran contiguous numpy arrays

---

python/taichi/aot/utils.py
python/taichi/examples/graph/texture_graph.py
python/taichi/examples/rendering/simple_texture.py
python/taichi/lang/__init__.py
python/taichi/lang/_texture.py
python/taichi/lang/enums.py
taichi/python/export_lang.cpp
tests/python/test_api.py
tests/python/test_ggui.py
tests/python/test_graph.py
tests/python/test_texture.py

Take texel format and translate the formats into datatype and channel counts internally for better expressiveness (to tolerate formats like `r11_g11_b10`).

[lang] Texture format for better expressiveness

---

python/taichi/examples/simulation/karman_vortex_street.py

[example] Change unnecessary ti.ndrange call to range in Karmal vortex example

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/expr.py
python/taichi/lang/impl.py
python/taichi/lang/matrix.py
tests/python/test_matrix.py
tests/python/test_matrix_slice.py
tests/python/test_vector_swizzle.py

Issue: #4677, #5819
Previous implementation of matrix slice only supports assign. This PR adds support for augmented assign (e.g. +=) by following the implementation of vector swizzle - always getting reference to selected matrix elements.

[Lang] Allow augmented assign on matric slice

---

c_api/docs/taichi/taichi_core.h.md
c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/taichi.json
docs/lang/articles/c-api/taichi_core.md
misc/generate_c_api.py
misc/generate_c_api_docs.py
misc/taichi_json.py

The error code `TI_ERROR_INCOMPLETE` is confusing because it actually means that Taichi has successfully done its work while the data is truncated because the user provided buffer is too short.
Also note that `set_last_error` with >0 error codes ("harmless errors") is allowed by designed. There must be a way to allow users to erase existing errors, otherwise the users can never suppressed those errors even they has successfully recovered from them. The restriction on overriding "hard errors" is thus removed.

[aot] Rename incomplete to truncated

---

c_api/include/taichi/cpp/taichi.hpp
c_api/tests/c_api_aot_test.cpp

fixes #6413 
Note we also changed the way to set vec/matrix args the previous `set` didn't save users from counting index manually. cc: @YuCrazing

[aot] Support push_arg for Kernel in C++ wrapper

---

python/taichi/lang/ast/ast_transformer.py
tests/python/test_ndrange.py

[Error] Deprecate ndrange with number of the loop variables != the dimension of the ndrange

---

python/taichi/lang/impl.py
taichi/analysis/gen_offline_cache_key.cpp
taichi/inc/statements.inc.h
taichi/ir/expression_printer.h
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/python/export_lang.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/lower_matrix_ptr.cpp
tests/python/test_matrix_slice.py

Issue: #5819
A slice actually corresponds to several indices. Let's take a look at the following example:
```python
ti.init(real_matrix=True, real_matrix_scalarize=True, print_ir=True)
@ti.kernel
def foo():
c = ti.Vector([1, 2, 3, 4, 5])
print(c[:4:2])
foo()
```
`c[:4:2]` is a "partially selected vector with length 2" which contains references to `c[0]` and `c[2]`. Let's represent it with `c[(0), (2), shape=2]`.
This PR does the following:
- expands slices into groups of indices in Python;
- extends `IndexExpression` to accept a group of indices;
- creates `MatrixOfMatrixPtrStmt` to represent a "partially selected matrix" in CHI IR;
- eliminates `MatrixOfMatrixPtrStmt` in the `lower_matrix_ptr()` pass.
Frontend IR and CHI IR of the above example:
```
[I 10/25/22 …
```

[Lang] MatrixType refactor: Support matrix slice

---

taichi/transforms/scalar_pointer_lowerer.cpp
tests/cpp/transforms/scalar_pointer_lowerer_test.cpp

Issue: #6219
For the following example,
```python
ti.root.dense(ti.i, 10).dense(ti.i, 30).place(x)
```
Under packed mode, if we want to access `x[105]`, we will calculate `105 mod (10 * 30) div 30 = 3` for the coordinate in the first dense SNode, and `105 mod 30 = 15` for the coordinate in the second dense SNode. We can see that `105 mod (10 * 30)` is unnecessary because user coordinate (`105`) is always less than the total shape (`10 * 30`) of the axis. This PR eliminates such redundant `mod` upon first coordinate extraction on an axis.
On my local machine, the benchmark script in #6219 runs
`0.030s` for `packed=False`,
`0.039s` for `packed=True` before this PR,
`0.007s` for `packed=True` after this PR (even faster than `packed=False` because `packed=False` still generates a …

[opt] Eliminate redundant mod for SNode access under packed mode

---

taichi/rhi/vulkan/vulkan_device.cpp

Issue: https://github.com/taichi-dev/taichi/issues/6448
We need to explicitly destroy the SPIRV module

[Bug] Fix memory leak in SPIRV module

---

.github/workflows/scripts/unix_test.sh

Continued from #6321 
Meshtaichi repo is now public and the tests of which can be easily fetched.

[ci] Add unix end-to-end CI tests for meshtaichi

---

.github/workflows/scripts/unix_test.sh

Reverts taichi-dev/taichi#6453 since it broke nightly, https://github.com/taichi-dev/taichi/actions/workflows/release.yml

Revert "[ci] Add unix end-to-end CI tests for meshtaichi"

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/runtime/cuda/jit_cuda.cpp

Issue: #6447
Previously we inject some cuda kernel metadata after linking, that was problematic since when you modify metadata for a llvm::Function you'll have to use the exactly same LLVMContext it was created in. Thus we failed verifyModule check from LLVM15. And we happened to only TI_WARN there so didn't notice this issue. 
This PR fixes it by moving the mark as CUDA step up to parallel compilation so that it was guaranteed to be in the same LLVMContext.

[llvm] Fix broken llvm module on CUDA backend when TI_LLVM_15 is on

---

taichi/transforms/cache_loop_invariant_global_vars.cpp
tests/python/test_for_break.py

[Bug] Fix cache_loop_invariant_global_vars pass

---

taichi/ir/snode.cpp
taichi/transforms/demote_dense_struct_fors.cpp
tests/python/test_struct_for_non_pot.py

Issue: fix #6258
For the script in #6258, which causes overflow only in non-packed mode, an error will be raised even if `packed=True`. The PR fixes the false alarm.

[bug] Fix false overflow alarm in struct fors under packed mode

---

python/taichi/lang/ast/ast_transformer.py

[Bug] [error] Add argument 'module' to 'warn_explicit' to show the deprecated warning

---

taichi/rhi/vulkan/vulkan_device_creator.cpp

Disabled for now because of multi-platform compatibility issues. Will be recovered when device capability is fully functional.

[aot] Disabled physical storage buffer temporarily

---

python/taichi/lang/ast/ast_transformer.py

Issue: #6472 
Traceback of #6472 before #6474, #6475 and #6477:
```
File "/home/lin/test/ant.py", line 21, in <module>
myclass.do_something()
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 1022, in __call__
return self._primal(self._kernel_owner, *args, **kwargs)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 888, in __call__
key = self.ensure_compiled(*args)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 855, in ensure_compiled
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 566, in materialize
taichi_kernel = impl.get_runtime().prog.create_kernel(
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 556, in …
```

[Error] Return TaichiTypeError in ASTTransformer when a binary op is not supported

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/ops.py
tests/python/test_field.py

Issue: #6472 
Traceback of #6472 before #6474, #6475 and #6477:
```
File "/home/lin/test/ant.py", line 21, in <module>
myclass.do_something()
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 1022, in __call__
return self._primal(self._kernel_owner, *args, **kwargs)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 888, in __call__
key = self.ensure_compiled(*args)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 855, in ensure_compiled
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 566, in materialize
taichi_kernel = impl.get_runtime().prog.create_kernel(
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 556, in …
```

[Error] Return NotImplemented for operations between field and Expr/Matrix/Struct

---

python/taichi/lang/kernel_impl.py

Issue: #6472 
Traceback of #6472 before #6474, #6475 and #6477:
```
File "/home/lin/test/ant.py", line 21, in <module>
myclass.do_something()
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 1022, in __call__
return self._primal(self._kernel_owner, *args, **kwargs)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 888, in __call__
key = self.ensure_compiled(*args)
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 855, in ensure_compiled
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 566, in materialize
taichi_kernel = impl.get_runtime().prog.create_kernel(
File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 556, in …
```

[Error] Shorten traceback for _BoundedDifferentiableMethod

---

taichi/transforms/scalar_pointer_lowerer.cpp
tests/python/test_sparse_activate.py
tests/python/test_sparse_basics.py
tests/python/test_sparse_parallel.py

Issue: #6219
This PR adds optimization similar to #6444 for non-packed mode so that we can conduct fair comparisons regarding performance. After this PR, the benchmark script in #6219 runs `0.007s` on my local machine no matter `packed=True/False`.
The tests are fixed because they are invalid - the out-of-bound access used to be hidden by the always inserted `BitExtractStmt` before this PR.

[opt] Eliminate redundant BitExtractStmt for SNode access under non-packed mode

---

taichi/transforms/scalar_pointer_lowerer.cpp
tests/python/test_sparse_activate.py
tests/python/test_sparse_basics.py
tests/python/test_sparse_parallel.py

This reverts commit 7cdb97fb94d12a9a9357bdfbe87440140c3308d6.
Issue: #

[opt] Revert "Eliminate redundant BitExtractStmt for SNode access under non-packed mode

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h

[llvm] Set the name of the LLVM function of the real function to its name

---

taichi/analysis/data_source_analysis.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/ir/control_flow_graph.cpp
taichi/ir/frontend_ir.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/ir/stmt_op_types.cpp
taichi/ir/stmt_op_types.h
taichi/runtime/llvm/runtime_module/node_dynamic.h
taichi/transforms/type_check.cpp
tests/python/test_compare.py
tests/python/test_dynamic.py
tests/python/test_dynamic_append_length.py
tests/python/test_sparse_deactivate.py
tests/python/test_struct_for_dynamic.py

Issue: #5420
This PR splits `append` operation of Dynamic SNode to two steps:
1. Allocate the space for the new element, increase the length by one, and return the address (void *) to the first byte of the new element.
2. Use `GetChStmt` to get the pointer of the element (of the right type) from the address returned in step 1, and use `GlobalStoreStmt` to store the value into the address.
**This PR breaks Dynamic SNode on Metal**

[llvm] Add support for data types of different sizes on dynamic SNode

---

c_api/src/taichi_vulkan_impl.cpp
taichi/rhi/vulkan/vulkan_device_creator.cpp

The physical storage buffer codegen was disabled but the runtime can still use them. This is an attempt to disable psb at runtime. Will bring it back after devcap.

[aot] Disable physical storage buffer in runtime

---

python/taichi/examples/rendering/rasterizer.py
python/taichi/examples/simulation/comet.py
python/taichi/examples/simulation/game_of_life.py
python/taichi/examples/simulation/mpm_lagrangian_forces.py
python/taichi/examples/simulation/two_stream_instability.py
python/taichi/examples/simulation/waterwave.py

Before #6485 out-of-bound accesses of SNodes were silent - through `BitExtractStmt`  they became in-bound but might not result in expected results. The optimization in #6485 removed the in-bound transition in certain cases so it was likely that an out-of-bound access would behave differently. The CI failure of #6485 (https://github.com/taichi-dev/taichi/actions/runs/3367141462/jobs/5584351541) revealed out-of-bound access in examples, which could be confirmed by turning on `ti.init(debug=True)`. This PR aims at fixing those examples.

[example] Fix out-of-bound access in examples

---

python/taichi/lang/expr.py
python/taichi/lang/kernel_impl.py
tests/python/test_function.py

Issue: #602
We only need to disassemble the arguments and pass them to the real function one by one just as we pass matrix arguments to the kernel.
It does not support local matrix and element of matrix field as argument when real_matrix=True yet.

[lang] Support matrix args on real function

---

taichi/rhi/vulkan/vulkan_device.cpp

Vulkan Validation layer intercepts the function pointer getter and returns nullptr for KHR-suffixed named if such interfaces have been incorporated into a version of Vulkan Core Profile. For example, validation layer returns `nullptr` for `vkGetPhysicalDeviceMemoryProperties2KHR` with a 1.1 instance because the function has been incorporated and is renamed to `vkGetPhysicalDeviceMemoryProperties2`. But this function is required by VMA and is asserted non-null, which leads to sophisticated assertion crash in AOT demos.

[aot] Select any of vkGetPhysicalDeviceMemoryProperties2

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/matrix.py
tests/python/test_vector_swizzle.py

Issue: #5819
This PR only contains the valid case and a corresponding test. More comprehensive tests will be enabled once #6425 is in.

[lang] MatrixType refactor: Support vector swizzle

---

python/taichi/lang/snode.py
taichi/analysis/gen_offline_cache_key.cpp
taichi/ir/expr.cpp
taichi/ir/expr.h
taichi/ir/expression_printer.h
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
tests/python/test_dynamic.py

Issue: #5420
This PR lets `SNodeOpExpression` store `vector<Expr> values` instead of `Expr value`, and enables passing a struct to `ti.append`.

[lang] Add support for struct on Dynamic SNode

---

python/taichi/tools/video.py

[Misc] Improve gif output compression rate

---

taichi/ir/frontend_ir.cpp
taichi/ir/ir.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/transforms/scalarize.cpp
tests/python/test_matrix_slice.py

Issue: #5819
This is to match the old behavior before the existence of `MatrixType`.

[lang] MatrixType refactor: Properly raise error when dynamic_index=False

---

taichi/rhi/vulkan/vulkan_api.cpp

`alloc_info.usage` is the usage of memory allocation, to inform VMA how we gonna use the memory (for example, is it host accessible?) While `image_info.usage` is the one that should be exported.

[aot] Fixed vulkan texture usage export

---

taichi/aot/graph_data.cpp
taichi/aot/graph_data.h
taichi/aot/module_builder.cpp
taichi/aot/module_builder.h
taichi/codegen/spirv/spirv_codegen.cpp
taichi/program/graph_builder.cpp
taichi/program/kernel.cpp
taichi/program/kernel.h
taichi/program/program.h
taichi/program/program_impl.h
taichi/runtime/dx12/aot_module_builder_impl.cpp
taichi/runtime/dx12/aot_module_builder_impl.h
taichi/runtime/gfx/aot_module_builder_impl.cpp
taichi/runtime/gfx/aot_module_builder_impl.h
taichi/runtime/llvm/llvm_aot_module_builder.cpp
taichi/runtime/llvm/llvm_aot_module_builder.h
taichi/runtime/program_impls/dx/dx_program.cpp
taichi/runtime/program_impls/dx/dx_program.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h
taichi/runtime/program_impls/opengl/opengl_program.cpp
taichi/runtime/program_impls/opengl/opengl_program.h
taichi/runtime/program_impls/vulkan/vulkan_program.cpp
taichi/runtime/program_impls/vulkan/vulkan_program.h
tests/python/test_aot.py

Issue: #6508 
This PR fixes #6508 but causes the bug reported in #5699 (only) when enabling the offline cache.
Using `CacheManager` manage the compilation in `AotModuleBuilder` can fix the bug. I will fix it in next PR.

[bug] Fix that the cgraph doesn't respect the caps set by ti.aot.Module()

---

python/taichi/lang/kernel_impl.py
tests/python/test_function.py

[lang] Add support for real matrix args on real function

---

python/taichi/lang/matrix_ops.py
python/taichi/lang/matrix_ops_utils.py

Issue: #5819
The use of atomic ops in #6425 is unnecessary. This PR removes those usage and simplifies logic around reduction ops.

[lang] MatrixType refactor: Simplify reduction ops

---

.github/workflows/notify_on_failure.yml

I found an example of payload in
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
Issue: #

[ci] Update slack message to include workflow_url instead of head commit

---

taichi/analysis/offline_cache_util.cpp
tests/python/test_offline_cache.py

Fixed bug reported by https://github.com/taichi-dev/taichi/actions/runs/3396038407/jobs/5646653663
Repro: `python tests/run_tests.py -v -t1 -a cpu,cuda matrix_slice --with-offline-cache`

[misc] Add dynamic_index to offline cache key

---

python/taichi/_funcs.py
python/taichi/lang/matrix_ops.py

Issue: #5819
This PR enforces that `vector.transpose()` returns a vector while `matrix.transpose()` returns a matrix, which mimics the behavior of numpy.

[Lang] Matrix lib: Stop changing dimension in transpose()

---

taichi/aot/graph_data.cpp
tests/python/test_graph.py

Fixes #6518
We should handle graph args based on their symbolic_arg type instead of runtime type.
Issue: #

[bug] [aot] Fix texture struct for with cgraph

---

.github/workflows/scripts/aot-demo.sh

Issue: #
This PR aims to add tutorial demos in CI. Will refactor the testing logic in a shell script in taichi-aot-demo and send a followup PR to switch as suggested by @jim19930609

[aot] Enable aot tutorial demo in CI

---

python/taichi/aot/module.py
tests/python/test_aot.py
tests/python/test_deprecation.py

Issue: #
`filename` argument in `ti.aot.Module.save()` has been no-op for a long time. This PR deprecates it and annouce that it'll be removed in v1.4.0 release. 
Also added a test file called `test_deprecation.py` which is designed to be the place to check all DeprecationWarnings so that before every release we can just check here to see if we can safely remove any deprecated apis.

[aot] Deprecate filename arg in ti.aot.Module.save()

---

taichi/program/program.cpp
taichi/program/program.h

Issue: fixes #6546 
I've run the test for 1000 times and the flaky test never appear again.

[bug] Rehash compile config map in advance

---

python/taichi/lang/matrix.py
python/taichi/lang/matrix_ops.py
tests/python/test_deprecation.py
tests/python/test_linalg.py

Issue: #5819
This PR includes a deprecation test of `ti.Matrix.rotation2d()` by the way.

[Lang] MatrixType refactor: Support matrix factories

---

python/taichi/lang/matrix_ops.py
taichi/ir/frontend_ir.cpp
taichi/transforms/scalarize.cpp
tests/python/test_mpm88.py

Issue: #5819
This PR contains 3 small fixes to make `test_mpm88` work properly:
1. Support `matrix_type_expr.cast()`;
2. Fix the flatten process of `AtomicOpExpression`;
3. Fix the scalarization process of `UnaryOpStmt`.

[lang] MatrixType bug fix: Make test_mpm88 work properly

---

.github/workflows/release.yml
.github/workflows/testing.yml
cmake/TaichiCore.cmake

Issue: https://github.com/taichi-dev/taichi/issues/6539, https://github.com/taichi-dev/taichi/issues/6451

[build] Downgrade molten-vk version to v1.1.10

---

.github/workflows/scripts/aot-demo.sh

Issue: #6559 
This is a followup PR to revert CI back to use master since https://github.com/taichi-dev/taichi-aot-demo/pull/66 is merged.

[aot] [ci] Change taichi-aot-demo branch back to master

---

python/taichi/aot/module.py
tests/cpp/aot/python_scripts/bitmasked_aot_test.py
tests/cpp/aot/python_scripts/comet_aot.py
tests/cpp/aot/python_scripts/dense_field_aot_test.py
tests/cpp/aot/python_scripts/dynamic_aot_test.py
tests/cpp/aot/python_scripts/field_aot_test.py
tests/cpp/aot/python_scripts/graph_aot_test.py
tests/cpp/aot/python_scripts/kernel_aot_test1.py
tests/cpp/aot/python_scripts/kernel_aot_test2.py
tests/cpp/aot/python_scripts/mpm88_graph_aot.py
tests/cpp/aot/python_scripts/sph_aot.py
tests/cpp/aot/python_scripts/taichi_sparse_test.py
tests/cpp/aot/python_scripts/texture_aot_test.py
tests/python/test_aot.py
tests/python/test_deprecation.py

Fixes #5859
We haven't supported compiling to a target different from the initialized arch and it won't be available in the short term. So let's make this an optional argument and default to the current arch to save users from some typing work.

[aot] Make arch an optional argument in ti.aot.Module

---

taichi/jit/jit_module.h
taichi/runtime/llvm/llvm_runtime_executor.cpp
taichi/runtime/llvm/runtime_module/runtime.cpp

Issue: #
This PR improves `ti.init(arch=ti.cuda)` time, especially in unit test environment.
| Concurrent processes * `ti.init()` count | Master  | With this PR | Speed up |
| --------------------------- | ------- | ------------ | -------- |
| 1 Process * 1                  | 556ms   | 410ms        | 35.6%    |
| 8 Processes * 1                 | 2500ms  | 1000ms       | 150%     |
| 1 Process * 10                 | 5850ms  | 4380ms       | 33.6%    |
| 8 Processes * 10               | 15200ms | 5760ms       | 164%     |
Filling rand states cost a whopping 150ms time during `ti.init(arch=ti.cuda)` because rand states are filled serially by a for loop in `runtime_initialize` by a `<<<1, 1>>>` kernel. This PR try to utilize GPU power to fill the rand states by a  `<<<saturating_grid_dim, …

[cuda] Parallelize random state initialization in ti.init()

---

.github/workflows/testing.yml
tests/python/test_memory.py

Issue: #
related CI failure: 
https://github.com/taichi-dev/taichi/actions/runs/3467496526/jobs/5792421314

[ci] Relax timeout for gpu jobs and memory limit

---

.github/workflows/release.yml

Fixes #6437
Our oncall release process changed and this should be done manually.

[ci] Remove automatic version bump PR

---

python/taichi/ad/_ad.py
taichi/transforms/auto_diff.cpp
tests/python/test_ad_basics.py
tests/python/test_loop_grad.py
tests/python/test_offline_cache.py

To avoid invalid grad accumulation, adjoints of fields on left-hand sides of assignments (GlobalStoreStmt) need to be reset to zero after the corresponding adjoint assignments.

[autodiff] Clear adjoint after global store

---

setup.py

Issue: #
The filter discarded our installed headers by accident, this PR restore them so that nightly users can get both lib/ and include there.

[build] Restore installed c_api headers in the python wheel

---

.github/workflows/testing.yml
docs/lang/articles/contribution/dev_install.md

Issue: #6447 
Updating links in dev install doc. 
Nit: we still depend on clang-10/clang-11 to produce runtime.bc files and that part will be updated once those are cleaned up.

[doc] Update prebuilt llvm15 links in dev install doc

---

.github/workflows/scripts/unix_test.sh
.github/workflows/scripts/win_test.ps1
requirements_test.txt
tests/python/conftest.py
tests/python/test_mpm88.py
tests/python/test_mpm_particle_list.py

Issue: #
Actual `pytest-xdist` fix: https://github.com/taichi-dev/pytest-xdist/commit/e3e1ccf5178ff53e5c9fa01adea18a2019cb764d
nothing is changed compared to last PR except the git commit hash in `requirements_test.txt`

[ci] Adaptively laying off test workers on CUDA OOM, 2nd try

---

.github/workflows/scripts/unix-build.sh

Issue: #6447 
Got the following error message when building manylinux2014 wheel since the base docker image doesn't have `unzip`:
```
2022-11-18T06:14:27.6476325Z + unzip taichi-llvm-15-linux.zip
2022-11-18T06:14:27.6485595Z /home/dev/taichi/.github/workflows/scripts/unix-build.sh: line 13: unzip: command not found
```
reference log: https://pipelines.actions.githubusercontent.com/serviceHosts/ebf0abad-1193-4ff9-9c60-da990d1eacd9/_apis/pipelines/1/runs/56327/signedlogcontent/20?urlExpires=2022-11-18T06%3A42%3A59.6939664Z&urlSigningMethod=HMACV1&urlSignature=pRp%2BtWL7jg6DXBr5bfgq0r5KqUwjrJ6bAM4WAXwP5S0%3D

[ci] Install unzip in manylinux build

---

taichi/rhi/device.h

`enum class` only exists in headers and do not produce a symbol. `TI_DLL_EXPORT` has no meaning in this case...

[misc] Fix warning with TI_DLL_EXPORT

---

taichi/transforms/auto_diff.cpp

Refactor independent block (IB) identification. 
Changes:
- Separate the identification of IB to `is_ib`and `is_smallest_ib`.
- The purpose is to find IBs as smallest as possible. The `MakeAdjoint` only  happens inside the IBs.
1. No load/store to alloca outside the current block makes the block an IB.
2. If it is an IB, either it is an inner most loop or there are global operations required gradient (such as atomics) makes it a smallest IB, i.e., should not dive deeper.

[autodiff] Refactor independent block identification

---

CMakeLists.txt
cmake/TaichiCXXFlags.cmake

Issue: #6447
We can now support any clang version <=15 to compile runtime.cpp into `.bc` files. 
A few notes:
- clang13 and clang15 introduced new diagnostic flags that we have to temporarily disable in Werror until they're fixed. 
- The commit update introduced in SPIRV-Tools was also introduced to mitigate similar issues as shown above. 
- I have tested locally on my linux with clang-12, clang-14, clang-15 and MacBook with clang-10, clang-13.

[build] Support any clang<=15 as CLANG_EXECUTABLE

---

taichi/transforms/auto_diff.cpp
tests/python/test_ad_for.py

Issue: #6666 
Fix missing global load stmt in independent blocks.

[autodiff] Fix missing global load stmt in independent blocks

---

taichi/transforms/auto_diff.cpp

According to the definition of an independent block (IB) in autodiff, i.e., no local load/store to allocas outside the block itself.
An empty block should be a smallest IB.

[autodiff] Enforce an empty block a smallest independent block

---

CMakeLists.txt

Issue: #6447
Tested locally with a clang-15 installed from brew. 
Also updated SPIRV-Tools and SPIRV-Headers to both tag sdk-1.3.224.0 since they've included some compilation fixes.

[build] Support any 13<clang<=15 as CLANG_EXECUTABLE on macOS

---

.github/workflows/scripts/win_build.ps1
CMakeLists.txt
ci/windows/win_build_test.ps1
cmake/TaichiCore.cmake
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/dx12/codegen_dx12.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/llvm_codegen_utils.h
taichi/codegen/llvm/struct_llvm.cpp
taichi/codegen/wasm/codegen_wasm.cpp
taichi/runtime/cpu/jit_cpu.cpp
taichi/runtime/cuda/jit_cuda.cpp
taichi/runtime/cuda/jit_cuda.h
taichi/runtime/llvm/llvm_context.cpp
tests/cpp/llvm/llvm_offline_cache_test.cpp

Issue: #6447
LLVM10 is dead in taichi codebase, long live LLVM15!
I wanna mention that a lot of hard work in this upgrade was done by our OSS contributor @python3kgae , thanks a ton!!!

[build] Delete all llvm10 code and TI_LLVM_15 macro

---

docs/lang/articles/get-started/cloth_simulation.md
docs/lang/articles/visualization/ggui.md

Issue: #
I copied the code from the [document](https://docs.taichi-lang.cn/docs/cloth_simulation) to run, but when running, it output:
```
[Taichi] version 1.2.2, llvm 10.0.0, commit 608e4b57, osx, python 3.10.8
venv/lib/python3.10/site-packages/taichi/ui/ui.py:22: DeprecationWarning: `ti.ui.make_camera()` is deprecated, please use `ti.ui.Camera()` instead
```
After I updated it, running no longer outputs warnings.

[doc] Update deprecated function call "ti.ui.make_camera()" to "ti.ui.Camera()"

---

python/taichi/_kernels.py
python/taichi/aot/utils.py
python/taichi/types/ndarray_type.py
tests/cpp/aot/python_scripts/graph_aot_test.py
tests/python/test_aot.py
tests/python/test_argument.py
tests/python/test_deprecation.py
tests/python/test_function.py
tests/python/test_graph.py
tests/python/test_ndarray.py
tests/python/test_shared_array.py
tests/python/test_texture.py

Issue: #6572 
* Deprecate `field_dim` in ndarray type annotation, replace with `ndim`.
* Change tests accordingly. Examples are left unchanged.

[Lang] Deprecate field_dim in ndarray annotation

---

cpp_examples/aot_save.cpp
cpp_examples/autograd.cpp
cpp_examples/run_snode.cpp
python/taichi/lang/snode.py
taichi/ir/snode.cpp
taichi/ir/snode.h
taichi/program/snode_expr_utils.cpp
taichi/python/export_lang.cpp
tests/cpp/analysis/bls_analyzer_test.cpp
tests/cpp/aot/dx12/aot_save_load_test.cpp
tests/cpp/codegen/refine_coordinates_test.cpp
tests/cpp/struct/snode_tree_test.cpp
tests/cpp/transforms/make_block_local_test.cpp
tests/cpp/transforms/scalar_pointer_lowerer_test.cpp
tests/python/test_bitmasked.py
tests/python/test_field.py
tests/python/test_packed_size.py

[Lang] Limit non-first division of an axis on a SNodeTree path to a power of two

---

taichi/transforms/demote_dense_struct_fors.cpp
taichi/transforms/scalar_pointer_lowerer.cpp
taichi/transforms/utils.cpp
taichi/transforms/utils.h

Issue: #6660
This PR applies the same optimization in #6444 to the `demote_dense_struct_fors` pass.

[opt] Eliminate redundant mod in demote_dense_struct_fors under packed mode

---

taichi/codegen/llvm/struct_llvm.cpp
taichi/transforms/utils.cpp
taichi/transforms/utils.h
tests/cpp/transforms/scalar_pointer_lowerer_test.cpp

Issue: #6660
After this PR, the two main goals in #6660,
> - Make the runtime overhead of SNode access always the same for both modes if the limitation is obeyed.
> - Make the runtime overhead of struct for on a SNode whose path to root contains no non-power-of-two division always the same for both modes.
are both achieved.
See comments in the code for implementation details.

[opt] Turn mod/div into bit_and/bit_shr if possible in packed mode

---

python/taichi/lang/matrix.py
python/taichi/lang/struct.py
taichi/transforms/lower_ast.cpp
tests/python/test_custom_struct.py

1. Modified `Matrix::fill()` to broadcast `val` into VectorType if `ndim == 1`, and to MatrixType if `ndim == 2`
2. Modified `Struct::fill()` to apply `matrix_op.fill()` in case of `Expr` with TensorType

[bug] MatrixType bug fix: Fix error with nested StructType and MatrixType

---

ci/Dockerfile.ubuntu.20.04.amdgpu

Issue: https://github.com/taichi-dev/taichi/issues/6434
This dockerfile refs to Dockerfile.ubuntu.20.04. The differences are following
1. based docker image
2. del python3-pip, mesa-common-dev which are already downloaded in based image.
3. remove vulkan module(amdgpu is not yet adapted to vulkan)
4. add user into video usergroup. (Some Ubuntu-20.04 versions also require render group)

[ci] Add dockerfile.ubuntu-20.04.amdgpu

---

requirements_test.txt
tests/python/test_ipython.ipynb
tests/run_tests.py

This PR adds a Jupiter notebook to the `test/` folder.

[test] Add jupyter notebook to tests

---

.github/workflows/scripts/unix-build.sh

Issue: #6447
LLVM15 build seems to be dependent on my building environement so I had to build a separate one for centos manylinux image. This is just to unblock release and will get rid of it in a followup.

[build] Use a separate prebuilt llvm15 binary for manylinux environment

---

python/taichi/examples/rendering/taichi_ngp.py

Add a file for ti-example: instant ngp renderer.
For more details, please visit [https://github.com/Linyou/taichi-ngp-renderer](https://github.com/Linyou/taichi-ngp-renderer).

[example] Ti-example: instant ngp renderer

---

docs/lang/articles/contribution/dev_install.md

[doc] Update LLVM10 -> LLVM15 in installation guide

---

ci/Dockerfile.ubuntu.18.04.amdgpu
ci/Dockerfile.ubuntu.20.04.amdgpu

Issue: https://github.com/taichi-dev/taichi/issues/6434
This dockerfile refs to Dockerfile.ubuntu.18.04.
It's similar to [PR6711](https://github.com/taichi-dev/taichi/pull/6711). After the ubuntu20 image merged, I unfortunately found our ci is based on the ubuntu18 image.

[ci] Add dockerfile.ubuntu-18.04.amdgpu

---

c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_gfx_impl.cpp
c_api/src/taichi_gfx_impl.h
c_api/taichi.json
c_api/tests/c_api_interface_test.cpp
taichi/common/virtual_dir.cpp
taichi/common/virtual_dir.h
taichi/runtime/gfx/aot_module_loader_impl.cpp
taichi/runtime/gfx/aot_module_loader_impl.h
tests/test_config.json

Reverts taichi-dev/taichi#6704

[aot] Load AOT module from memory (#6692)

---

.github/workflows/release.yml
.github/workflows/testing.yml
.gitmodules
CMakeLists.txt
cmake/TaichiCAPITests.cmake
cmake/TaichiCore.cmake
cmake/TaichiTests.cmake

Issue: #
When building with `-DTI_BUILD_TESTS=ON`, `taichi_cpp_tests`,`taichi_c_api_tests`, `taichi_python.so` will link to an external library: https://github.com/bombela/backward-cpp, which enables C++ stack trace upon test failures.
`python3 test.py`
`./build/taichi_cpp_tests`
`./build/taichi_c_api_tests`

[build] Integrate backward_cpp to test targets for enabling C++ stack trace

---

python/taichi/lang/ast/ast_transformer.py
tests/python/test_dynamic_append_length.py
tests/python/test_dynamic_attributes.py

Issue: #5420
Just noticed that we forgot to enable getting length of dynamic SNode by `x[i].length()` along with `append` and `deactivate`

[lang] Get the length of dynamic SNode by x.length()

---

docs/lang/articles/basic/layout.md

Issue: #6660
We no longer need the concept of packed mode. Now we only have to suggest users using power-of-two block size in hierarchical fields.

[Doc] Stop mentioning packed mode

---

python/taichi/lang/misc.py
taichi/ir/snode.cpp
tests/python/test_deprecation.py

Issue: #6660
Apart from the deprecated warning, the previously added limitation that "non-first division on an axis must be a power of two" is now made purely a warning because it can already let users learn the best practice.

[Lang] Add deprecation warning for the removal of the packed switch

---

.github/workflows/testing.yml
docs/lang/articles/contribution/dev_install.md

Issue: #6447 
Also noticed that CI job `build_android_demo` is not skipped for doc-only PRs, so this PR also change that to save some CI time.

[doc] Update dev install about clang version

---

taichi/transforms/loop_invariant_detector.h
taichi/transforms/make_thread_local.cpp

Issue: fix #3323
As #6759 allows the use of clang >= 12, we need to fix #3323 to pass the tests.

[bug] Fix dereferencing nullptr

---

taichi/transforms/auto_diff.cpp

Separate non-linear operators to an individual class so that can be accessed by other visitors, e.g., the visitors in IB identification will use it in further development.

[autodiff] Separate non-linear operators to an individual class

---

.github/workflows/testing.yml
docs/lang/articles/contribution/dev_install.md

Cherrypicks #6747 and #6759 into v1.3.0 release branch

[doc] Cherrypicks dev install doc changes into v1.3.0 release branch

---

docs/lang/articles/math/sparse_matrix.md

Cherrypicks https://github.com/taichi-dev/taichi/pull/6719 into v1.3.0 release branch

[doc] Cherrypicks sparse matrix doc changes into v1.3.0 release branch

---

c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_gfx_impl.cpp
c_api/src/taichi_opengl_impl.cpp
c_api/src/taichi_vulkan_impl.cpp
c_api/taichi.json
c_api/tests/c_api_interface_test.cpp
taichi/cache/gfx/cache_manager.cpp
taichi/rhi/device.cpp
taichi/rhi/device.h
taichi/rhi/device_capability.cpp
taichi/rhi/device_capability.h
taichi/rhi/dx/dx_device.cpp
taichi/rhi/dx/dx_device.h
taichi/rhi/opengl/opengl_device.cpp
taichi/rhi/opengl/opengl_device.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/rhi/vulkan/vulkan_device_creator.cpp
taichi/runtime/program_impls/dx/dx_program.cpp
taichi/runtime/program_impls/opengl/opengl_program.cpp
taichi/runtime/program_impls/vulkan/vulkan_program.cpp

API adjustments, tests and etc.
This PR improves the user experience issue for C-API users to work with device capability, especially when the `TiRuntime` is imported from an outer context.

[aot] C-API Device capability improvements

---

CMakeLists.txt
cmake/Distributed.cmake

Issue: #6445
This PR addresses quirks in `sccache` distributed compiling:
1.  `sccache` would run preprocessing locally (`clang -E`) first and then send the expanded code to remote build server. This can trigger false warnings not present when compiling locally.
2.  Compile host and target can be different, `--target=` must be send to remote build server.

[build] Initial distributed compiling support

---

c_api/include/taichi/cpp/taichi.hpp
c_api/tests/c_api_interface_test.cpp

We recently introduced a breaking change to `taichi.hpp` that `NdArray<T>::read()` and `NdArray<T>::write()` now consumes number of scalars rather than size-in-bytes. This PR sets the `TI_ERROR_ARGUMENT_OUT_OF_RANGE` error in case of out-of-range access.

[aot] Warn the user about out-of-range access in C++ wrapper

---

taichi/analysis/gen_offline_cache_key.cpp
taichi/ir/expression.h
taichi/ir/frontend_ir.cpp
taichi/ir/frontend_ir.h
taichi/transforms/lower_ast.cpp

Overriding the flattened statement `stmt` of an `Expression` can cause conflicts, for example:
```
@ti.kernel
def test():
x = ti.Vector([1, 2, 3, 4])
tmp = x + x[0] # implicit broadcast
```
In `x + x[0]`, the `x` on the lhs serves as rvalue whereas the `x` in the `x[0]` serves as a lvalue, so the result of `flatten_rvalue()` and `flatten_lvalue()` will override each other.
To avoid such conflicts, this PR refactored the `flatten_values()` functions:
1. Flattened statement `stmt` of an `Expression` will only get modified by `Expression::flatten()`, any other overriding will be forbidden.
2. `flatten_rvalue()` and `flatten_lvalue()` now returns the flattened statement as the result. External users such as `irpass::lower_ast()` will …

[Misc] Refactored flattend_values() to avoid potential conflicts in flattened statements

---

python/taichi/lang/kernel_impl.py
tests/python/test_texture.py

Issue: #
As discussed with @PENGUINLIONG offline, kernel should recompile when `dtype & num_dimension` changes. Note currently `rwtexture` also recompiles if `num_channels` change, I didn't remove that in this PR.

[vulkan] Make sure kernel recompiles when texture dtype changes

---

.github/ISSUE_TEMPLATE/bug_report.md

Issue: #
Unlike other issue templates, bug report issues can be very diverse and `potential bug` label isn't that helpful. We'd rather assign a proper label manually or make it more automatic in the future.

[misc] Remove the default potential_bug label on bug report issues

---

python/taichi/lang/_texture.py
python/taichi/types/texture_type.py
tests/cpp/aot/python_scripts/texture_aot_test.py
tests/python/test_deprecation.py
tests/python/test_ggui.py
tests/python/test_graph.py
tests/python/test_texture.py

Issue: #
#6338 added a way to specify fmt (`ti.Format`) which is more expressive and easier to understand than the combo of `num_channels + channel_format` so let's deprecate them to avoid confuse users.

[vulkan] Deprecate num_channels and channel_format args in rw_texture type annotation

---

taichi/transforms/scalarize.cpp
tests/python/test_quant_atomics.py

Issue: #5819
Quant types are not primitive types, so we should not make assertions that types only contain primitive types and tensor type. We just need to trigger scalarization when all the operands have `TensorType`.

[bug] MatrixType bug fix: Fix error with quant

---

python/taichi/aot/utils.py
python/taichi/types/texture_type.py
tests/python/test_aot.py
tests/python/test_deprecation.py

Issue: #
https://github.com/taichi-dev/taichi/pull/6782 accidentally makes `channel_format/num_channels` optional and this PR fixes it by throwing an error if none of
`channel_format/num_channels/fmt` is specified.
Note `rw_texture` isn't a template type (yet) so it's okay to just compile it directly with its type hint.
TODO: support `ti.types.texture()` in add_kernel

[vulkan] Support rw_texture in aot add_kernel

---

python/taichi/_kernels.py
python/taichi/examples/graph/texture_graph.py
python/taichi/examples/rendering/simple_texture.py

Issue: discovered by #6630, thanks @neozhaoliang !
`num_channels/channel_format` will be deprecated in #6782  so let's remove them in the user facing codebase to suppress warnings.

[misc] Remove usage of deprecated num_channels/channel_format type hint in rw_texture in codebase

---

taichi/program/sparse_matrix.cpp

Issue: #2906 
The `read_int` function of ndarray consumes more than 100M gpu memory. It's better to use `memcpy_device_to_host` function to obtain `num_triplets_`.

[lang] Use less gpu memory when building sparse matrix

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/common_ops.py
python/taichi/lang/impl.py
python/taichi/lang/util.py
python/taichi/types/primitive_types.py
tests/python/test_bool_type.py

Issue: #577 #6036
This PR adds `bool` as an alias to `ti.i32`. Specifically,
- `x: bool` is equivalent to `x: i32`
- `-> bool` is equivalent to `-> i32`
- `bool(x)` is equivalent to `ti.cast(x, i32)`.
This is a temporary solution while we work towards a standalone bool type.

[Lang] [type] Add bool type in python as an alias to i32

---

python/taichi/lang/ast/ast_transformer.py
tests/python/test_tuple_assign.py

[bug] MatrixType bug fix: Add additional restrictions for unpacking a Matrix

---

python/taichi/lang/struct.py
tests/python/test_custom_struct.py

Issue: fix #6652
Properties should be added to a certain `Struct` instance instead of the `Struct` class itself.

[bug] Fix name collision in ti.dataclass

---

python/taichi/aot/utils.py
tests/python/test_aot.py

Issue: #
`ti.types.texture` has been a template type so I didn't change that in this PR. But in the future `TextureType` may support args other than `num_dimensions` so that users can provide all necessary info in the type hint. But that's out of scope for this PR.
This PR just added support for texture type args in aot `add_kernel` so that it can be used in AOT without cgraph, and it worth noticing that you're currently required to provide a template_args for texture type. But since we require enough info in rw_texture type annotation, you don't need to provide any template_args for rw_texture type.

[vulkan] Support texture type args in aot add_kernel

---

python/taichi/lang/matrix_ops.py
python/taichi/lang/matrix_ops_utils.py
tests/python/test_matrix.py

Issue: #5819
The background is that we would like to clearly distinguish vectors from matrices. After #6528, `transpose()` of a vector makes no sense so we'd better raise an error and guide users towards the current practice (`outer_product()`).

[Lang] Raise an error for the semantic change of transpose()

---

tests/python/test_runtime.py

Issue: #
Just noticed these tests always run on x64 during my local runs, even if I'm running on OpenGL backend. 
The reason is mainly due to the missing `test_utils.test()` guard so let's guard them to save some time.

[test] Remove unnecessary duplicated python runtime test runs

---

.github/workflows/scripts/common-utils.sh
.github/workflows/scripts/unix-build.sh
.github/workflows/scripts/unix_test.sh
.github/workflows/testing.yml
ci/Dockerfile.ubuntu.18.04.amdgpu
ci/Dockerfile.ubuntu.20.04.amdgpu

Issue: https://github.com/taichi-dev/taichi/issues/6434
Add the logic of docker for AMDGPU ci
1. The llvm used which only contains AMDGPU and X86 targets is from docker image
2. Using AMDGPU in docker requires that `/dev/kfd` and the directory `/dev/dri` be mounted on. For `dev` user, there is no permission to access these character devices by default.
3. `TI_WITH_CUDA=OFF`
4. `TI_RUN_RELEASE_TESTS=OFF`
5. Currently only run cpu-relected test

[ci] Add AMDGPU relected ci

---

taichi/transforms/offload.cpp
tests/python/test_matrix.py

Issue: fix #6663
In `MatrixPtrStmt`, when `origin` is `GlobalTemporaryStmt`, the semantics of `offset` has changed from the number of bytes to the number of elements. This PR fixes the outdated usage which may overwrite the global tmp buffer.

[Bug] Avoid overwriting global tmp with dynamic_index=True

---

tests/python/test_overflow.py

Issue: #6824
https://github.com/taichi-dev/taichi/actions/runs/3641543203/jobs/6154890343 
We used to depend on the behavior that "no constant folding when debug=True"  in these tests and this PR fixes by avoid constant folding in the tests. 
Tested locally with ` python tests/run_tests.py overflow --with-offline-cache`

[test] Avoid constant folding in overflow tests

---

taichi/program/ndarray.cpp
taichi/program/ndarray.h
tests/python/test_ndarray.py

Issue: fix #6650
The original implementation hardcodes `int`, `uint` and `float`, which only allows reading 32-bit data out. This PR fixes the behavior by leveraging `TypedConstant`.

[Bug] Fix getting 64-bit data from ndarray in Python scope

---

taichi/rhi/vulkan/vulkan_device.h

Mac M1 does not support `wide_line` with Vulkan. However, device capability was initialized to random values which is why some examples are flaky on M1.
Before this PR:

[bug] Fix flaky mass_spring_game_ggui.py on Mac M1 by setting up default values for VulkanCapabilities

---

python/taichi/examples/autodiff/jacobian.py

Issue: #6733 
The the grad field of variable at the left side of the global store will be cleared after #6579. Change to atomic add sort the issue.

[example] Fix jacobian example

---

python/taichi/lang/kernel_impl.py
taichi/program/ndarray.cpp

Issue: fix #6758
This PR adds a boundary check for ndarray similar to https://github.com/taichi-dev/taichi/blob/a87b98fd40fc93dbe1bdf8c4e3932a6078379fa3/taichi/ir/snode.cpp#L89-L93

[Lang] Warn users if ndarray size is out of int32 boundary

---

tests/python/conftest.py
tests/python/examples/rendering/test_cornell_box.py
tests/python/examples/simulation/test_mpm99.py

Issue: #
1. Run `mpm99` and `cornell_box` in serial.
2. Monkey-patching `pytest_rerunfailures` version number checking, force it to treat our forked xdist 'compatible'.

[ci] Python test minor fixes

---

python/taichi/lang/_wrap_inspect.py
python/taichi/lang/ast/checkers.py
python/taichi/lang/kernel_impl.py
python/taichi/lang/shell.py
tests/python/test_deprecation.py

This PR replaces #6630 (now closed)
It deprecates, and also fixes a bug in the sourceinpect module (cannot use cell magics %%time and %%timeit in jupyter notebooks). The dependency on sourceinspect is reserved and will be removed in future releases (if the current fix works fine)
Also added test in `test_deprecation.py`.

[Lang] Deprecate sourceinspect dependency

---

python/taichi/lang/field.py

This PR adds a warning message when the user tries to call the `to_numpy` method of a dynamic snode.
close: #6841

[Lang] Add warning message when converting dynamic snode to numpy

---

docs/lang/articles/get-started/cloth_simulation.md

[doc] Update cloth_simulation.md

---

docs/lang/articles/advanced/dataclass.md

[Doc] Update dataclass.md

---

docs/lang/articles/basic/external.md

[doc] Update external.md

---

docs/lang/articles/internals/internal.md
taichi/inc/constants.h
taichi/runtime/metal/shaders/runtime_structs.metal.h

[IR] Allow a maximum of 12 SNode indices

---

docs/lang/articles/get-started/hello_world.md

[doc] Update hello_world.md

---

docs/lang/articles/contribution/dev_install.md

Built LLVM 15 with Visual Studio 2022. Note that this build has the experimental DXIL target enabled so Taichi's DX12 backend should work. Not tested tho.

[doc] Link to LLVM 15 built for Visual Studio 2022

---

taichi/rhi/device.h
taichi/rhi/impl_support.h
taichi/rhi/opengl/opengl_device.cpp
taichi/rhi/vulkan/vulkan_api.cpp
taichi/rhi/vulkan/vulkan_api.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/rhi/vulkan/vulkan_device_creator.cpp
taichi/runtime/gfx/runtime.cpp
taichi/ui/backends/vulkan/swap_chain.cpp

Also added partial RHI support for Vulkan Dynamic Rendering, but there are some interactions and bugs to figure out between this and ImGUI, so the device creator will not actively enable this feature for now.

[vulkan] Improve Vulkan RHI impl with lower overhead internal implementations

---

python/taichi/examples/algorithm/poisson_disk_sampling.py

This PR adds the code in this repo: https://github.com/taichi-dev/poisson-sampling-homework to the example list

[example] Add poission disk sampling example

---

taichi/cache/gfx/cache_manager.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/util/lock.h
taichi/util/offline_cache.h

Issue: #4401
I found that some users' programs warn the `"[W ... Lock C:/taichi_cache/ticache/llvm/metadata.lock failed"`.
I think the crash when loading old version cache files which were generated by old version taichi-nightly could cause the warning. But I'm not sure.
Temporarily, show a message to suggest the user remove this `.lock` file manually.
And I will provide `python -m taichi clean_ticache` to allow user to clean the cache files manually.

[misc] Show suggestion when locking metadata.lock fails

---

docs/lang/articles/faqs/faq.md

This PR makes the faq page more readable by grouping the questions into subsections.

[Doc] Update faq.md

---

python/taichi/lang/impl.py
python/taichi/lang/matrix_ops.py
tests/python/test_matrix.py

Issue: #5819
1. `+=` should not be used in (single-thread) matrix lib functions. It is an atomic op and will be demoted very late in the optimization passes, which is harmful to the compilation speed. 
2. `__getitem__` should take only one parameter.

[lang] Fix accidental changes during matrix refactor

---

.github/workflows/scripts/aot-demo.sh
.github/workflows/scripts/common-utils.sh
.github/workflows/testing.yml

AMDGPU node is back.
And I couldn't make OpenGL work in container (probably because of mesa version / other user space AMDGPU driver), disabling for now.

[ci] Reenable AMDGPU CI, disable OpenGL tests in AMDGPU task

---

docs/lang/articles/performance_tuning/profiler.md

[doc] Update profiler.md

---

docs/lang/articles/performance_tuning/performance.md

[doc] Update performance.md

---

docs/lang/articles/get-started/glossary.md

[Doc] Glossary

---

python/taichi/lang/matrix.py
taichi/python/export_lang.cpp
tests/python/test_matrix.py

Issue: #5819
Before this PR, matrix type inference directly takes the type of the first element, which is problematic. This PR fixes the inference by calculating the common type of all elements and removes the redundant `_MatrixEntriesInitializer`.

[lang] Fix matrix type inference and remove _MatrixEntriesInitializer

---

python/taichi/lang/_ndrange.py
python/taichi/lang/matrix.py
python/taichi/lang/mesh.py

Issue: #5819
These two intermediate classes are unnecessary now, so let's remove them for simplicity.

[refactor] Remove _IntermediateMatrix and _MatrixFieldElement

---

python/taichi/_main.py
taichi/cache/gfx/cache_manager.cpp
taichi/cache/metal/cache_manager.cpp
taichi/python/export_misc.cpp
taichi/runtime/llvm/llvm_offline_cache.cpp
taichi/util/offline_cache.cpp
taichi/util/offline_cache.h
tests/python/test_cli.py

[CLI] Add "ti cache clean" command to clean the offline cache files manually

---

taichi/codegen/spirv/spirv_ir_builder.cpp
taichi/codegen/spirv/spirv_ir_builder.h

Issue: https://github.com/taichi-dev/taichi/issues/6807
`spv::OpImageFetch` should take `OpImage` instead of `OpSampledImage` as operand. Therefore we extract the underlying `OpImage` during code generation for `TextureOpStmt("fetch")`

[aot] Fix validation warning: OpImageFetch should operate on OpImage instead of OpSampledImage

---

python/taichi/lang/matrix.py
tests/python/test_api.py

Issue: #5819
There is no need to wrap some methods of `Matrix` into a separate class now.

[refactor] Remove _PyScopeMatrixImpl

---

python/taichi/lang/matrix.py
tests/python/test_fill.py

Issue: fix #6950
The change to `fill()` in #6892 (skips turning a `ti.Matrix` into a tuple) accidentally disallows compilation caching when the argument is a `ti.Matrix`, which causes #6950. This PR puts that behavior back.

[bug] Fix recompilation of filling a matrix field with the same matrix

---

.github/workflows/release.yml

Previous hack to add enable capi build in unix-build.sh (#6479) is gone so this PR tries to add it back.
Issue: #

[ci] Fix missing c_api.so in linux nightly

---

python/taichi/aot/utils.py
tests/python/test_aot.py

Currently we take rwtexture as non-template arg so we need to properly initialize it from its annotation for aot.
Issue: #

[aot] Fix rwtexture with template_args

---

python/taichi/lang/kernel_impl.py
tests/python/test_function.py

Issue: fix #6855
Note that this PR is a quick hack to allow the type hint but doesn't check invalid cases. We would like to wait for the upcoming new struct type representation to officially support struct type as kernel/func parameters.

[bug] Allow StructType as type hint to ti.func

---

taichi/transforms/scalarize.cpp

Issue: https://github.com/taichi-dev/taichi/issues/6927

[lang] Fix scalarization for PrintStmt

---

.github/workflows/scripts/aot-demo.sh
c_api/docs/taichi/taichi_core.h.md
c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi.h
c_api/include/taichi/taichi_core.h
c_api/include/taichi/taichi_vulkan.h
c_api/src/taichi_core_impl.cpp
c_api/src/taichi_core_impl.h
c_api/src/taichi_gfx_impl.cpp
c_api/src/taichi_gfx_impl.h
c_api/src/taichi_llvm_impl.cpp
c_api/src/taichi_llvm_impl.h
c_api/src/taichi_vulkan_impl.cpp
c_api/taichi.json
c_api/tests/c_api_behavior_test.cpp
c_api/tests/comet.cpp
docs/lang/articles/c-api/taichi_core.md
docs/lang/articles/c-api/taichi_vulkan.md
taichi/rhi/device.h
taichi/rhi/vulkan/vulkan_api.cpp
taichi/rhi/vulkan/vulkan_api.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/runtime/gfx/runtime.cpp
taichi/runtime/gfx/runtime.h

Issue: #6693, https://github.com/taichi-dev/taichi-aot-demo/pull/101, https://github.com/taichi-dev/taichi-unity2/pull/9
This PR introduced the breaking changes listed in #6693.

[aot] C-API breaking changes!

---

.github/workflows/release.yml

Reverts taichi-dev/taichi#6962
We don't want to add c_api.so to official releases *yet*, so #6969 is a better fix. :D

Revert "[ci] Fix missing c_api.so in linux nightly"

---

python/taichi/examples/rendering/taichi_ngp.py

If you start `ti example` and type `66` (taichi_ngp) it crashes and complains about unknown arg `example`. This PR fixes it.
Issue: #

[bug] Fix taichi_ngp starting from ti example

---

python/taichi/_funcs.py
taichi/math/svd.h

[lang] Migrate TensorType expansion for svd from Python code to Frontend IR

---

.github/workflows/scripts/aot-demo.sh

Issue: https://github.com/taichi-dev/taichi/pull/6955

[aot] Recover AOT CI script

---

taichi/codegen/metal/codegen_metal.cpp
taichi/codegen/metal/struct_metal.cpp
taichi/program/extension.cpp
taichi/transforms/scalarize.cpp
tests/python/test_matrix.py
tests/python/test_matrix_slice.py

Issue: #2590
1. Dynamic indexing in metal is supported by mimicking the implementation of that in LLVM backends.
2. `ret_type` change of `ArgLoadStmt` is moved out of the `ScalarizePointers` pass, which is designed to scalarize `alloca` and will be removed once dynamic indexing becomes default.
3. Configs of dynamic indexing tests are fixed.

[Lang] [metal] Support dynamic indexing in metal

---

taichi/ir/type_factory.cpp
taichi/ir/type_factory.h
taichi/util/hash.h

Issue: fixes #6570 and resolves the TODOs in the code

[ir] Change type maps to unordered maps and add mutexes

---

taichi/codegen/spirv/snode_struct_compiler.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/program/extension.cpp
taichi/rhi/opengl/opengl_api.cpp
tests/python/test_matrix.py

Issue: #2590
This PR supports dynamic indexing in spirv (sister PR: #6985). `_test_local_matrix_non_constant_index()` is modified due to lack of `AssertStmt` support in spirv.

[Lang] [spirv] Support dynamic indexing in spirv

---

taichi/analysis/gather_statement_usages.cpp
taichi/ir/analysis.h
taichi/ir/ir.cpp
taichi/ir/ir.h
taichi/transforms/eliminate_immutable_local_vars.cpp
taichi/transforms/scalarize.cpp

Issue: #6933
`ImmediateIRModifier` aims at replacing `Stmt::replace_usages_with`, which visits the whole tree for a single replacement. `ImmediateIRModifier` is currently associated with a pass, visits the whole tree once at the beginning of that pass, and performs a single replacement with amortized constant time. It is now used in two most recent passes, `eliminate_immutable_local_vars` and `scalarize`. More passes can be modified to leverage it in the future.
After this PR, the profiling result of the script in #6933 shows that the time of `eliminate_immutable_local_vars` reduces from `0.956 s` to `0.162 s`, the time of `scalarize` reduces from `3.510 s` to `0.478 s`, and the total time of `compile` reduces from `8.550 s` to `4.696 s`.

[opt] Add ImmediateIRModifier to provide amortized constant-time replace_usages_with()

---

taichi/rhi/amdgpu/amdgpu_device.h

[amdgpu] Update amdgpu device to new API

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/runtime/llvm/llvm_runtime_executor.cpp
taichi/runtime/llvm/llvm_runtime_executor.h

[bug] Fix device memory allocation for numpy array on CUDA backend

---

docs/lang/articles/reference/global_settings.md

This PR removes the `packed` option in `ti.init` according to the changes in v1.4.0.

[Doc] Remove packed mode in doc

---

.github/workflows/scripts/unix_test.sh

Issue: #
Reland of #7010  with a hack that running gles tests alone. Wanted to enable the tests to prevent regression, will fix the crash that happens when testing vulkan,gles,opengl at the same time.

[opengl] Enable more gles tests in CI

---

misc/prtags.json
taichi/rhi/amdgpu/amdgpu_device.h
taichi/rhi/cpu/cpu_device.h
taichi/rhi/cuda/cuda_device.h
taichi/rhi/device.h
taichi/rhi/dx/dx_device.cpp
taichi/rhi/dx/dx_device.h
taichi/rhi/impl_support.h
taichi/rhi/metal/device.cpp
taichi/rhi/opengl/opengl_device.cpp
taichi/rhi/opengl/opengl_device.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h

Issue: #6832
Compute-only CommandList APIs other than dispatch has been changed to use `noexcept`, and the behavior specifications has been added, and relevant checks are now in place for Vulkan and partially for DX11.

[rhi] Update compute CommandList APIs (except dispatch)

---

python/taichi/ui/canvas.py
python/taichi/ui/gui.py

[Lang] Fix gui docstring

---

taichi/transforms/scalarize.cpp

Issue: #2590
Under pure `dynamic_index` setting, `MatrixPtrStmt`s are not scalarized. It actually produces `2n` more instructions (`n` `ConstStmt`s and n `MatrixPtrStmt`s) than the scalarized setting, where `n` is the number of usages of `MatrixPtrStmt`s. This PR adds `ExtractPointers` pass to eliminate all the redundant instructions. See comments in the code for details.
After this PR, the number of instructions after the `scalarize()` pass of the script in #6933 under dynamic index reduces from 49589 to 26581, and the compilation time reduces from 20.02s to 7.82s.

[opt] Add ExtractPointers pass for dynamic index

---

c_api/docs/taichi/taichi_core.h.md
c_api/include/taichi/taichi_core.h
c_api/include/taichi/taichi_vulkan.h
c_api/src/taichi_core_impl.cpp
c_api/taichi.json
docs/lang/articles/c-api/taichi_core.md
docs/lang/articles/c-api/taichi_vulkan.md
misc/generate_c_api.py
misc/generate_c_api_docs.py
misc/taichi_json.py
python/taichi/aot/module.py

Issue: #5858
This PR introduces a versioning mechanism to the Taichi Runtime C-API. Taichi Runtime has the same version as the Python frontend. The version information can be queried from taichi header definition `TI_C_API_VERSION`, C-API `ti_get_version`, `__version__` in compiled AOT module, and log output when `ti_create_runtime` is called.

[aot] C-API versioning

---

taichi/rhi/amdgpu/amdgpu_device.h
taichi/rhi/cpu/cpu_device.h
taichi/rhi/cuda/cuda_device.h
taichi/rhi/device.h
taichi/rhi/dx/dx_device.cpp
taichi/rhi/dx/dx_device.h
taichi/rhi/metal/device.cpp
taichi/rhi/opengl/opengl_device.cpp
taichi/rhi/opengl/opengl_device.h
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/runtime/gfx/runtime.cpp

[rhi] Update CommandList dispatch API

---

taichi/transforms/scalarize.cpp
tests/python/test_matrix_slice.py

Issue: #2590
Previously `ScalarizePointers` (which is for allocas) takes place only when `dynamic_index=False`. In this PR, we automatically identify those allocas only indexed with constants and get them scalarized, and let the remaining allocas go through the code path for dynamic indexing. In this way, we make old user programs behave the same regardless of the `dynamic_index` option, and provide dynamic indexing support for new user programs at the same time.

[opt] Automatically identify allocas to scalarize

---

python/taichi/examples/simulation/implicit_fem.py
python/taichi/examples/simulation/snow_phaseField.py
python/taichi/lang/matrix.py
python/taichi/lang/misc.py
taichi/program/compile_config.cpp
tests/python/test_ad_dynamic_index.py
tests/python/test_ad_if.py
tests/python/test_ad_math_func.py
tests/python/test_deprecation.py
tests/python/test_matrix.py
tests/python/test_matrix_slice.py
tests/test_utils.py

Issue: #2590
Dynamic indexing is now automatically supported and no switch is needed.

[Lang] Deprecate the dynamic_index switch

---

python/taichi/ui/canvas.py

Issue: https://github.com/taichi-dev/taichi/issues/6999
GGUI's `circles` method does not allow passing NumPy array as radius; this PR fixes this error.

[Doc] Fix docstring

---

docs/lang/articles/type_system/type.md

Since we have made `matrix` and `vector` to be different types in v1.4.0, the documentation needs to be updated.

[Doc] Update type.md

---

taichi/transforms/scalarize.cpp
tests/python/test_matrix.py

Issue: fix #6978
After #7068, The `taichi_ngp` example reports `RuntimeError: [type_factory.cpp:promoted_type@222] Assertion failure: a->is<TensorType>() && b->is<TensorType>()`. The root cause is that `taichi_ngp` uses `atomic_sub` on a value with type different from the destination, which will generate `neg` + `cast`. However, the `ret_type` and `cast_type` of `UnaryOpStmt` produced by `Scalarize` aren't set correctly. This PR fixes the problem.

[Bug] Fix ret_type and cast_type of UnaryOpStmt in Scalarize

---

python/taichi/lang/_wrap_inspect.py
python/taichi/ui/canvas.py
requirements_dev.txt
setup.py
tests/python/test_deprecation.py

This PR removes the deprecation warning message for the `sourceinspect` dependency.

[Lang] Remove sourceinspect deprecation warning message

---

.github/workflows/scripts/aot-demo.sh
python/taichi/aot/module.py
tests/cpp/aot/python_scripts/bitmasked_aot_test.py
tests/cpp/aot/python_scripts/comet_aot.py
tests/cpp/aot/python_scripts/dense_field_aot_test.py
tests/cpp/aot/python_scripts/dynamic_aot_test.py
tests/cpp/aot/python_scripts/field_aot_test.py
tests/cpp/aot/python_scripts/graph_aot_test.py
tests/cpp/aot/python_scripts/kernel_aot_test1.py
tests/cpp/aot/python_scripts/kernel_aot_test2.py
tests/cpp/aot/python_scripts/mpm88_graph_aot.py
tests/cpp/aot/python_scripts/sph_aot.py
tests/cpp/aot/python_scripts/taichi_sparse_test.py
tests/cpp/aot/python_scripts/texture_aot_test.py
tests/python/test_aot.py
tests/python/test_deprecation.py

[Lang] Remove filename kwarg in aot Module save()

---

.github/workflows/release.yml
.github/workflows/testing.yml

Issue: #
Sometimes we can see `filename too long` errors in `actions/checkout` step, with the added `core.longpaths=true` we can (hopefully) solve this.
Still didn't figure out the exact reason why checked-out repos go corrupt, but this seems a reasonable candidate.

[ci] More Windows git hacks

---

python/taichi/math/mathimpl.py

I found this while using ti.math.sign(), the description confused me
>x = ti.Vector([-1.0, 0.0, 1.0])
ti.sign(x)
[0.8, 0.3, 0.3, 0.2]
then found more wrong information in mathimpl.py, there exists three writting styles, and I've unified them.

[doc] Modified some errors in the function examples

---

python/taichi/lang/simt/block.py
taichi/codegen/spirv/spirv_codegen.cpp
taichi/rhi/metal/metal_device.h
taichi/rhi/metal/metal_device.mm

1. Remove most of the `TI_XXX` macros from Metal RHI impl
2. Utilize some features from `impl_support.h`
3. Enable shared array support on all SPIR-V backends

[metal] Update Metal RHI impl & add support for shared arrays

---

taichi/codegen/llvm/codegen_llvm.cpp
tests/python/test_struct_for_non_pot.py

[Bug] Fix num_splits in parallel_struct_for

---

python/taichi/lang/_ndarray.py
taichi/program/program.cpp
taichi/program/program.h
taichi/program/program_impl.h
taichi/python/export_lang.cpp
taichi/runtime/gfx/runtime.cpp
taichi/runtime/gfx/runtime.h
taichi/runtime/program_impls/metal/metal_program.h
taichi/runtime/program_impls/opengl/opengl_program.h
taichi/runtime/program_impls/vulkan/vulkan_program.h
tests/python/test_ndarray.py

Issue: fixes #5048 
Ndarray's memory allocation is managed by Taichi and Python can control this via Taichi indirectly.
For example, when an ndarray is GC-ed in Python, it signals Taichi to free its memory allocation. 
But Taichi will make sure **no pending kernels to be executed needs the ndarray** before it actually 
frees the memory.

[lang] Free ndarray memory when it's GC-ed in Python

---

python/taichi/_snode/fields_builder.py
python/taichi/examples/features/sparse/taichi_bitmasked.py
python/taichi/examples/simulation/comet.py
python/taichi/lang/snode.py
tests/python/test_deprecation.py
tests/python/test_matrix.py

[Error] Raise errors when using metal sparse

---

tests/python/test_ad_external_array.py

This test is flaky. It does not fault out properly and CI detects a success while a worker will be brought down by this crash, making CI impossibly long.
Issue: #

[ci] Temporarily disable ad_external_array on Metal

---

taichi/rhi/cpu/cpu_device.cpp
tests/python/test_ndarray.py

Fixes #7119
It seems unnecessary for CPU to use runtime jit memory allocation for ndarray, let's see if anything breaks...

[cpu] Reuse VirtualMemoryAllocator for CPU ndarray memory allocation

---

taichi/cache/gfx/cache_manager.cpp
taichi/codegen/codegen.cpp
taichi/program/kernel.h

[refactor] Remove useless Kernel::from_cache_

---

.github/workflows/testing.yml

Related Issue: #7140 
On macOS, when test worker hard fails (abort, EXC_BAD_ACCESS, etc.), backward_cpp's signal handler will re-raise the signal and catch it afterwards, make it an infinite loop, at the moment the offending process can't be terminated easily (except a SIGKILL), eat CPU cycles and blocks test runner.
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
* frame #0: 0x00000001a04f0e28 libsystem_kernel.dylib`__pthread_kill + 8
frame #1: 0x00000001a052343c libsystem_pthread.dylib`pthread_kill + 292
frame #2: 0x00000001a0402e10 libsystem_c.dylib`raise + 32
frame #3: 0x00000001283a0848 taichi_python.cpython-38-darwin.so`backward::SignalHandling::sig_handler(int, __siginfo*, void*) + 28
frame #4: 0x00000001a056ec44 …
```

[ci] Disable backward_cpp on macOS

---

.github/workflows/testing.yml

We should directly push the cherry-picks to the rc branches instead of merging it using PRs.

[ci] Run test when pushing to rc branches

---

docs/lang/articles/get-started/accelerate_pytorch.md
python/taichi/lang/_ndarray.py
python/taichi/lang/kernel_impl.py
tests/python/test_ndarray.py
tests/python/test_numpy.py

Issue: #6572 
* Check external ndarray total dim against type annotation
* Error out when element shape mismatch
* Refine error messages

[Misc] Strictly check ndim with external array

---

docs/lang/articles/advanced/meta.md
docs/lang/articles/contribution/write_test.md
docs/lang/articles/reference/global_settings.md
docs/lang/articles/reference/language_reference.md

[Doc] Update doc regarding dynamic index

---

cmake/TaichiCXXFlags.cmake
taichi/rhi/metal/metal_device.h
taichi/rhi/metal/metal_device.mm

Issue: #
Changed the command buffer building to directly retaining a command buffer and encoding commands into it (instead of building up a list of lambda functions)

[metal] Retain Metal commandBuffers & build command buffers directly

---

setup.py

Apple requires any shared library built for Apple Silicon to be codesigned with a local development certificate. This certificate is generated by Xcode automatically.

[lang] Sign python library for Apple M1

---

c_api/src/taichi_core_impl.cpp
c_api/tests/c_api_interface_test.cpp

[bug] Unify error message matching with/without validation layers for CapiTest.FailMapDeviceOnlyMemory

---

.github/workflows/release.yml
misc/make_changelog.py

Issue: #6114
The changelog automatically generated by GitHub only shows the PR list related to the branch, and the cherry-picked commits are not inside the list. So we should use our commit-based `make_changelog.py` to generate the full changelog.

[ci] Use make_changelog.py to generate the full changelog

---

python/taichi/examples/ggui_examples/fractal3d_ggui.py

This PR updates the code in `fractal_3d_ggui.py`.

[example] Update quaternion arithmetics in fractal_3d_ggui

---

docs/lang/articles/basic/ndarray.md

[doc] Add doc ndarray

---

docs/lang/articles/get-started/accelerate_python.md

newer version of ti deprecates `max`
Issue: #

[doc] Update accelerate_python.md to use ti.max

---

c_api/include/taichi/cpp/taichi.hpp
c_api/tests/c_api_interface_test.cpp

Issue: #
Added C++ wrapper for `ti_get_version`.

[aot] C-API get version wrapper

---

taichi/common/logging.cpp

Issue: #
Log to stderr instead of stdout for external projects whose CI depends on stdout content.

[misc] Log to stderr instead of stdout

---

c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/taichi.json
c_api/tests/gtest_fixture.h
docs/lang/articles/c-api/taichi_core.md
taichi/ir/ir.cpp

Issue: #
Initially `ti_get_last_error` returns `TI_EROR_TRUNCATED` to hint the user that the message output is not complete (because the buffer size is insufficient), but this 'non-failing' error code has been removed in later commits. So at this point this API doesn't have a reliable way to know whether the error message is complete. This is considered problematic.

[aot] Fixed ti_get_last_error signature

---

docs/lang/articles/deployment/tutorial.md

This PR fixes the problem that `depolyment/tutorial.md` does not display on the doc site.

[Doc] Fix C++ tutorial does not display on doc site

---

docs/lang/articles/debug/debugging.md

This PR deletes the obsolete note because:
1. Taichi will drop the support for IDLE from v1.4.0.
2. print is now supported in Jupyter notebook.

[Doc] Update debugging.md

---

c_api/docs/taichi/taichi_core.h.md
c_api/include/taichi/cpp/taichi.hpp
c_api/include/taichi/taichi_core.h
c_api/src/taichi_core_impl.cpp
c_api/taichi.json
c_api/tests/c_api_behavior_test.cpp
c_api/tests/c_api_interface_test.cpp
docs/lang/articles/c-api/taichi_core.md
docs/lang/articles/c-api/taichi_vulkan.md

Issue: #
Removed unused archs and added a C++ overload to filter archs in `ti::get_available archs`.

[aot] Removed unused archs in C-API

---

CMakeLists.txt
c_api/cmake/FindTaichi.cmake
cmake/TaichiCAPI.cmake
cmake/TaichiCXXFlags.cmake
cmake/TaichiConfig.cmake.in
cmake/taichi_c_apiConfig.cmake.in

Issue: #
This PR introduces a CMake module `FindTaichi.cmake` to help external project to integrate Taichi Runtime into their applications following the CMake convention to minimize the lines of codes they need in their `CMakeLists.txt`.
The following is the integration CMake snippet:
```cmake
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../cmake)
find_package(taichi REQUIRED)
add_executable(${EXAMPLE_NAME} main.cpp)
target_link_libraries(${EXAMPLE_NAME} PRIVATE taichi::runtime)
add_custom_command(
TARGET ${EXAMPLE_NAME}
PRE_BUILD
COMMENT "-- Copy redistributed libraries to output directory (if different): ${taichi_REDIST_LIBRARIES}"
COMMAND ${CMAKE_COMMAND} -E copy_if_different ${taichi_REDIST_LIBRARIES} "$<TARGET_FILE_DIR:${EXAMPLE_NAME}>")
```

[aot] FindTaichi CMake module to help outside project integration

---

c_api/include/taichi/cpp/taichi.hpp

Issue: #
Just noticed that `std::exchange` doesn't exists in C++11.

[aot] Replace std::exchange with local implementation for C++11

---

docs/lang/articles/deployment/tutorial.md

This PR fixes some possible bugs that may cause the docsite building to fail.

[Doc] Update tutorial.md

---

docs/lang/articles/deployment/ndarray_android.md
docs/lang/articles/get-started/hello_world.md
docs/lang/articles/reference/language_reference.md

The name tutorial is a bit misleading as it's not a tutorial on Taichi but on taichi in C++ apps. Also, we need to use the older name to make our doc deployment bot happy.

[Doc] Rename tutorial doc

---

python/taichi/_main.py

The terminal will report an error when users run the command `ti gallery` but close the window without choosing any example. This PR fixes this problem.

[example] Fix ti gallery close warning

---

python/taichi/_snode/fields_builder.py
python/taichi/lang/snode.py
tests/python/test_deprecation.py
tests/python/test_field.py

[Error] Better error message when creating sparse snodes on backends that do not support sparse

---

taichi/program/program.h

Issue: #
The `Program::jit_evaluator_id` is not used.

[misc] Remove unused Program::jit_evaluator_id

---

.github/workflows/testing.yml
tests/python/test_offline_cache.py

Issue: #6221 
`kernel4` in `test_offline_cache.py` triggers a weird LLVM internal error on metal backend for macos12+. After moving metal runtime to gfxruntime by @PENGUINLIONG  and #7201, this is now the only blocker for us to run full CI on macos ventura. As discussed with @PENGUINLIONG and @feisuzhu offline, let's disable this test to unblock CI and add it back once the issue is fixed.

[metal] Disable a kernel test in offline cache to unblock CI

---

python/taichi/aot/utils.py
python/taichi/lang/matrix.py
tests/cpp/aot/python_scripts/graph_aot_test.py
tests/python/test_aot.py

Issue: fixes #7172 
Ideally we should reconstruct the dtype to the Tensortype from taichi_core instead of python ones but that can be a separate PR.

[aot] Fix ndarray aot with information from type hints

---

python/taichi/lang/common_ops.py
tests/python/test_deprecation.py

[Error] Remove deprecated a.atomic_op(b) in Taichi v1.6.0

---

python/taichi/examples/rendering/taichi_ngp.py

Many backends support half / float16, but in comparison int8 has very pretty bad support in general. This change enables backends like `opengl` and `dx12` to run this demo (assuming the feature-enabling PR is also merged in those)

[examples] Remove dependency on `ti.u8` compute type for ngp

---

cmake/TaichiCore.cmake
taichi/rhi/opengl/opengl_api.cpp
taichi/rhi/window_system.cpp
taichi/rhi/window_system.h
taichi/runtime/program_impls/vulkan/vulkan_program.cpp
taichi/ui/backends/vulkan/window.cpp
taichi/ui/utils/utils.h

Related: #7218
Without this GGUI will mess with the OpenGL backend because both tries to initialize & destroy GLFW.
There is an issue tho with dependency. Which target should `rhi/window_system` belong to? Maybe we need a device API target that collects all the specific backends and generate a static lib with all backends and optional dependencies like GLFW? (Anyways, that will be a TODO for another PR)

[opengl] Fix GLFW global context issue

---

python/taichi/ui/canvas.py
python/taichi/ui/scene.py
python/taichi/ui/staging_buffer.py

Part of https://github.com/taichi-dev/taichi/pull/7218
Related (ndarray meta-programming): #7231
I would certainly like to share this code between the field vesion and NDArray version

[gui] Use templated bulk copy to simplify VBO preperation

---

python/taichi/linalg/sparse_matrix.py
tests/python/test_deprecation.py

[Error] Remove deprecated ti.linalg.sparse_matrix_builder in 1.6.0

---

python/taichi/lang/impl.py
tests/python/test_indices.py

Issue: fix https://github.com/taichi-dev/taichi/issues/7096

[lang] Add validation checks for subscripts to reject negative indices

---

python/taichi/_snode/fields_builder.py

Why this PR:
Currently, when users allocate dynamic SNodes of dimension >=  2**31, the error message is not easy to understand:
```
self.ptr.dynamic(axis[0], dimension, chunk_size, get_traceback()))
TypeError: dynamic(): incompatible function arguments. The following argument types are supported:
1. (self: taichi._lib.core.taichi_python.SNode, arg0: taichi._lib.core.taichi_python.Axis, arg1: int, arg2: int, arg3: str) -> taichi._lib.core.taichi_python.SNode
```
This PR makes the error clear.

[Lang] Add better error message for dynamic snode

---

taichi/runtime/llvm/llvm_runtime_executor.cpp

[bug] Fix the parity of the RNG

---

c_api/src/taichi_llvm_impl.cpp
taichi/codegen/amdgpu/codegen_amdgpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/jit/jit_session.cpp
taichi/jit/jit_session.h
taichi/runtime/amdgpu/jit_amdgpu.cpp
taichi/runtime/amdgpu/jit_amdgpu.h
taichi/runtime/cpu/aot_module_loader_impl.cpp
taichi/runtime/cpu/jit_cpu.cpp
taichi/runtime/cuda/aot_module_loader_impl.cpp
taichi/runtime/cuda/jit_cuda.cpp
taichi/runtime/cuda/jit_cuda.h
taichi/runtime/llvm/llvm_aot_module_loader.cpp
taichi/runtime/llvm/llvm_aot_module_loader.h
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/llvm_context.h
taichi/runtime/llvm/llvm_runtime_executor.cpp
taichi/runtime/llvm/llvm_runtime_executor.h
tests/cpp/backends/amdgpu_device_test.cpp

[refactor] Fix "const CompileConfig *" to "const CompileConfig &" (Part2)

---

python/taichi/__init__.py
python/taichi/_lib/utils.py

[misc] Fix manylinux2014 warning not printing

---

c_api/src/taichi_llvm_impl.cpp
taichi/runtime/cpu/aot_module_loader_impl.cpp
taichi/runtime/cuda/aot_module_loader_impl.cpp
taichi/runtime/llvm/llvm_aot_module_loader.cpp
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/llvm_runtime_executor.cpp
taichi/runtime/llvm/llvm_runtime_executor.h
taichi/runtime/program_impls/llvm/llvm_program.cpp
taichi/runtime/program_impls/llvm/llvm_program.h

Issue: fixes #7251
The` llvm_context_host_` and `llvm_context_device_` are never both used in the same backend, so we can unify them and only use a single `llvm_context_`.

[llvm] Unify the llvm context of host and device

---

taichi/codegen/amdgpu/codegen_amdgpu.cpp
taichi/codegen/codegen.cpp
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/struct_llvm.cpp
taichi/codegen/wasm/codegen_wasm.cpp
taichi/runtime/program_impls/llvm/llvm_program.h
tests/cpp/codegen/refine_coordinates_test.cpp
tests/cpp/llvm/llvm_offline_cache_test.cpp

[llvm] Remove unused argument 'arch' in LlvmProgramImpl::get_llvm_context

---

taichi/transforms/cache_loop_invariant_global_vars.cpp
taichi/transforms/loop_invariant_detector.h
tests/python/test_loops.py

Issue: fixes #7263
The bug is caused by caching a same global variable in two different local vars in two nested loops. To avoid this, for a cache-able global var, we find the outermost loop that it can be moved out of instead of just moving out of the innermost loop.

[Bug] Fix caching same loop invariant global vars inside nested fors

---

.github/workflows/scripts/unix_test.sh
taichi/codegen/amdgpu/codegen_amdgpu.cpp
taichi/program/extension.cpp
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/runtime_module/runtime.cpp
tests/python/test_ad_gdar_diffmpm.py
tests/python/test_ad_if.py
tests/python/test_cfg_continue.py
tests/python/test_cli.py
tests/python/test_debug.py
tests/python/test_internal_func.py
tests/python/test_lang.py
tests/python/test_native_functions.py
tests/python/test_ndarray.py
tests/python/test_ndrange.py
tests/python/test_non_taichi_types_in_kernel.py
tests/python/test_offload_cross.py
tests/python/test_print.py
tests/python/test_struct_for_dynamic.py

Issue: #https://github.com/taichi-dev/taichi/issues/6434
1. fix amdgpu backend bugs:
a. codegen typos
b. add more types support for `sgn`
c. use temporary method to handle `runtime.cpp` error
2. enable amdgpu backend python unit test
a. because of the lack of `print` support, temporarily disable all `print` related tests on amdgpu backend.
b. there is still something wrong in `gdar_mpm` and `ad_if` tests.

[ci] [amdgpu] Enable amdgpu backend python unit tests

---

python/taichi/lang/util.py

Issue: #4543
Changed print statement in `taichi.lang.util.warning` to `warnings.warn` to respect stdlib warnings filters

[refactor] Change print statement to warnings.warn in taichi.lang.util.warning

---

taichi/ui/backends/vulkan/renderer.cpp
taichi/ui/backends/vulkan/renderer.h

Removed all the renderable reusing logic and since we have added the shader factory, we can now make creation of `renderable` immediate (and release them per frame). This allows the next step of immediate data transfer (so that we can remove the host numpy array cache)

[gui] Remove renderable reuse & make renderable immediate

---

taichi/codegen/amdgpu/codegen_amdgpu.cpp
taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/dx12/codegen_dx12.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/codegen_llvm.h
taichi/codegen/wasm/codegen_wasm.cpp

Issue: #7286 
* This PR: Part of removing `TaskCodeGenLLVM::prog`
* removing `TaskCodeGenLLVM::prog`: Part of #7286 
* #7286: Part of #7002

[refactor] Remove dependencies on LlvmProgramImpl::get_llvm_context() in TaskCodeGenLLVM

---

.github/workflows/scripts/unix_test.sh
.github/workflows/scripts/win_test.ps1
python/taichi/examples/rendering/cornell_box.py

Using the updated taichi writing style and a more simplified implementation that includes comments.
It runs fine on: 
- Window11 AMD Ryzen 7 6800H with Radeon Graphics CPUs and GPUs
- macOS 12.5.1 Intel Core i7 and AMD Radeon Pro 5500XT CPUs and GPUs
Performance (updated: `2023/02/10`, https://github.com/taichi-dev/taichi/pull/7252/commits/97da1b398bd46b5270d3dde66bcec8393479979c): 
- AMD 6800H 680M Radeon Graphics about 200 fps
- Intel Core i7&Radeon Pro 5500XT about 250 fps
This requires a change in the test sample, can anyone assist me?
- https://github.com/taichi-dev/taichi-release-tests/pull/6
Results: 
- Look in the forum: https://forum.taichi-lang.cn/t/topic/3837

[example] Re-implement the Cornell Box demo with shorter lines of code

---

c_api/src/taichi_vulkan_impl.cpp
cpp_examples/rhi_examples/common.h
taichi/rhi/device.h
taichi/rhi/vulkan/CMakeLists.txt
taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h
taichi/rhi/vulkan/vulkan_device_creator.cpp
taichi/rhi/vulkan/vulkan_device_creator.h
taichi/rhi/vulkan/vulkan_loader.cpp
taichi/rhi/window_system.cpp
taichi/runtime/program_impls/vulkan/CMakeLists.txt
taichi/runtime/program_impls/vulkan/vulkan_program.cpp
taichi/ui/backends/vulkan/app_context.cpp
taichi/ui/backends/vulkan/app_context.h
taichi/ui/backends/vulkan/swap_chain.cpp
taichi/ui/utils/utils.h

Issue: #
This moves native surface handle construction explicitly out of the Vulkan RHI and is now managed by the user (i.e. GGUI, or example application).

[vulkan] Remove GLFW from Vulkan rhi dependency

---

taichi/analysis/offline_cache_util.cpp
taichi/analysis/offline_cache_util.h
taichi/cache/gfx/cache_manager.cpp
taichi/cache/gfx/cache_manager.h
taichi/codegen/codegen.cpp
taichi/codegen/dx12/codegen_dx12.cpp

Issue: fixes #7381 
| `TI_VISIBLE_DEVICE` (on my PC) | `spirv_has_atomic_float_add` |
| --- | --- |
| 0 | **Y** |
| 1 | **N** |
Example program:
```Python
ti.init(arch=ti.vulkan)
@ti.kernel
def f1() -> ti.f32:
a = 0.0
for i in range(1024):
a += i / ti.f32(100.0)
return a
print(f1())
```
On [master](https://github.com/taichi-dev/taichi/commit/4af54d49b38a40e1035ca36227ddaf342b0b15c0):
On [this branch](https://github.com/PGZXB/taichi/tree/dev-add-dev-caps-to-offline-cache-key):

[bug] Add DeviceCapabilityConfig to offline cache key

---

taichi/rhi/metal/metal_device.mm

Issue: #
It's not supported by iOS and it even doesn't compile.

[aot] Remove support for depth24stencil8 format on Metal

---

taichi/rhi/vulkan/vulkan_device.cpp
taichi/rhi/vulkan/vulkan_device.h

The confusing "failed to submit command buffer" error message has been replaced with a device lost message (which is the typical type of failure that occurs when failing to submit cmdbuf).
In addition, framebuffer caching code is removed, the reason not to do so is addressed in the comments. There are other misc changes / code quality changes included.

[vulkan] Change command list submit error message & misc device API cleanups

---

c_api/tests/c_api_aot_test.cpp
tests/cpp/aot/python_scripts/shared_array_aot_test.py
tests/test_config.json

[aot] Add test for shared array

---

taichi/runtime/amdgpu/jit_amdgpu.cpp

1. Enable the FpOpFusion option. If not, it will cut `saxpy` performance in half
- a. Turn off
performance:
- b. Turn on
performance:
2. Disable AsmVerbose in machine option. Thus we will get pure LLVM-IR after module and function passes. Or there will be some instructions for target in the module.

[amdgpu] Enable llvm FpOpFusion option on AMDGPU backend

---

taichi/analysis/gen_offline_cache_key.cpp
taichi/codegen/codegen.cpp
taichi/codegen/dx12/codegen_dx12.cpp
taichi/transforms/constant_fold.cpp

Issue: #7002 
Disable `ASTSerializer::allow_undefined_visitor`:
1. Enabling `ASTSerializer::allow_undefined_visitor` is dangerous;
2. Prepare for introducing `KernelCompilationManager`.

[refactor] Disable ASTSerializer::allow_undefined_visitor

---

python/taichi/__init__.py

This PR fixes the warning message "xxx is not a known member of None" raised by Pylance, when using the syntax `ti.types.xxx`.

[Lang] Fix pylance types warning

---

taichi/rhi/amdgpu/amdgpu_driver.h

Issue: #
Typos
Previously
Update:

[bug] Fix get_error_string ret type typo

---

python/taichi/lang/ops.py
taichi/ir/frontend_ir.cpp
taichi/python/export_lang.cpp
tests/python/test_atomic.py

Issue: #4455
Currently, the following error message appears when the user uses the constant int as the first operand of the `atomic_*()` series of functions: `AttributeError: 'int' object has no attribute 'ptr'`. To make matters worse, taichi gives an internal assertion failure when the user uses some right value expression, e.g., `-x`. 
This PR adds a helper function exposed in the Expr python class called `is_lvalue()`, which the python AST parser can use to check the validity of operands and throw an error message when a rvalue is used as a write target.

[lang] Add is_lvalue() to Expr to check writeback_binary operand

---

taichi/runtime/gfx/aot_module_loader_impl.cpp
taichi/runtime/gfx/aot_module_loader_impl.h

Issue: #7002 
The member was used by old implementation of offline cache, which is unnecessary now.

[misc] Remove AotModuleParams::enable_lazy_loading

---

taichi/runtime/gfx/aot_module_builder_impl.cpp
taichi/runtime/gfx/aot_module_builder_impl.h

Issue: #7002
The functions were used by old implementation of offline cache, which are unnecessary now.

[misc] Remove unnecessary functions of gfx::AotModuleBuilderImpl

---

python/taichi/lang/ops.py

This PR fixes pylance warnings raised by `ti.random`.

[Lang] Fix pylance warnnings by ti.random

---

taichi/codegen/cc/codegen_cc.cpp

Issue: #7443 
For backends that don't support dynamic indexing, we should raise an explicit error.

[misc] Add an explicit error in cc backend codegen for dynamic indexing

---

python/taichi/_ti_module/cppgen.py

Issue: #
Avoid generating kernels that belongs to a graph in module interface.

[aot] Remove graph kernel interfaces

---

taichi/transforms/check_out_of_bound.cpp
tests/python/test_ndarray.py

Fixes #7430 
Note that this PR only added out of bound check for the following cases: 
- when your index is OOB for field dimension
- or when your flattened index in element is OOB for flattened element dimensions 
Here's a case that is not covered by this PR, e.g 
For an ndarray with element shape `[2, 2]` and field shape `[4, 5]`, if you index it with `[3, 4][0, 2]` if won't throw as element indices are flattened in https://github.com/taichi-dev/taichi/blob/master/taichi/transforms/lower_matrix_ptr.cpp#L56. We should find a better way to throw in that case.

[misc] Add out of bound check for ndarray

---

.github/workflows/testing.yml

There're two `AOT Build and Test Android Headless Demos` in the CI workflow ;)
Issue: #

[ci] Fix duplicated names in aot tests

---

.github/workflows/release.yml
requirements_test.txt
tests/run_tests.py
tests/test_utils.py

1. Update `pytest-xdist` and enable work stealing scheduler
2. Use `build.py` to build Windows wheels in nightly builds
3. Defer obtaining available architectures in `expected_archs` to resolve Windows CPU tests getting stuck issue.

[ci] Fix nightly build failure, and minor improvements

---

python/taichi/lang/impl.py

This PR fixes pylance warnings raised by `ti.static`.

[Lang] Fix pylance warnings raised by ti.static

---

taichi/rhi/metal/metal_device.mm

Issue: #
It leads to a crash when there is an outer `autoreleasepool` attempting to release the command buffer. Note the command buffer is already released in the destructor, and the `autoreleasepool` will attempt to release it again because the command buffer is assigned to it.

[lang] Fixed double release of Metal command buffer

---

docs/lang/articles/contribution/dev_install.md

“We recommend that there is no need” is not grammatical.

[docs] Reword words of warning about building from source

---

python/taichi/examples/algorithm/circle-packing/circle_packing_image.py
requirements_dev.txt

This PR removes the `cv2` and `cairocffi` dependency in `requirements_dev.txt`.

[example] Remove cv2, cairo dependency

---

tests/run_tests.py

Issue: #7002 
```
Error in atexit._run_exitfuncs:
File "tests/run_tests.py", line 233, in print_and_remove
os.listdir(os.path.join(tmp_cache_file_path, subdir)))
NotADirectoryError: [Errno 20] Not a directory: '/var/folders/1r/fk_r0s1d4ss8m19rg11bq1j80000gp/T/tmpcnyh7mz1/Tbdbfefe5b5fe6db167e250d15bb1c4cc797b2beee4fa7a09be9a6cff8c060101-metal.tic'
```
`python run_tests.py -v -t4 -a vulkan,cpu abs --with-offline-cache`
```
...
Error in atexit._run_exitfuncs:
File "..\taichi\tests\run_tests.py", line 233, in print_and_remove
os.listdir(os.path.join(tmp_cache_file_path, subdir)))
NotADirectoryError: [WinError 267] The directory name is invalid. : 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpcs7z9cpq\\T1571a996babd2f9b7a24eeba9d …
```

[bug] Fix run_tests.py --with-offline-cache

---

taichi/aot/graph_data.cpp
taichi/program/callable.h
taichi/program/function.cpp
taichi/program/kernel.cpp
taichi/program/kernel.h
taichi/program/launch_context_builder.cpp
taichi/program/launch_context_builder.h
taichi/program/snode_rw_accessors_bank.cpp
taichi/python/export_lang.cpp

This PR separates `LaunchContextBuilder` from `Kernel`, in order to let `LaunchContextBuilder` able to be used in AOT.
This PR also extracts a class `CallableBase` from `Callable`, and let `Callable` inherit `CallableBase`. `CallableBase` contains information sufficient for the `LaunchContextBuilder` to construct arguments and read return values, and it does not contain any runtime information (like `program`) and things related to compiling (like `ir`). In this way, `CallableBase` will be able to be used in AOT.
* #7441
* #7504
* #7489
* __->__ #7494

[ir] Separate LaunchContextBuilder from Kernel

---

taichi/aot/graph_data.cpp
taichi/aot/graph_data.h
taichi/program/launch_context_builder.cpp
taichi/runtime/gfx/aot_graph_data.h
taichi/runtime/llvm/aot_graph_data.h
taichi/runtime/llvm/llvm_aot_module_loader.cpp
tests/cpp/aot/llvm/dynamic_aot_test.cpp
tests/cpp/aot/llvm/field_aot_test.cpp
tests/cpp/aot/llvm/kernel_aot_test.cpp
tests/cpp/aot/llvm/kernel_return_aot_test.cpp
tests/cpp/aot/python_scripts/kernel_return_aot_test_.py
tests/cpp/cpptests.yaml

After this PR the AOT kernel also have information about the types of the arguments and the return values. 
As a result, AOT kernels of LLVM-based backends can have return values now.
* #7441
* __->__ #7504
* #7489
* #7494

[AOT] [llvm] Let AOT kernel inherit CallableBase and use LaunchContextBuilder

---

docs/lang/articles/visualization/gui_system.md

The examples in `Event handling` are duplicates, I removed one of them.
Fixed duplicate examples in gui_system.md

[Doc] Update gui_system.md, remove unnecessary example

---

c_api/src/taichi_core_impl.cpp

Resolves issue: #7244
Limit the number of arguments that can be pushed into the context.

[aot] Kernel argument count limit

---

taichi/rhi/metal/metal_device.h
taichi/rhi/metal/metal_device.mm

Issue: #
Subgroups are only supported in Metal 2.1 and up, we upgrade the default msl version to 2.1.0 to enable subgroup functionalities, otherwise, metal crashes when launching subgroups-involved kernels.

[metal] Choose the proper msl version according to the device capability

---

docs/lang/articles/faqs/install.md

The docs previously stated to use `python3 -c "print(__import__('sys').version[:3])"` to verify the Python version you were using. This only works if the minor version is 1 digit (like 3.6), but not for two digits (like 3.10 or 3.11). I've modified it to do this correctly regardless of how many digits the minor version is. 
Incidentally, should this page also be updated to mention 3.11 is supported? I don't have a machine with Python 3.11 installed to test.

[doc] Handle 2 digit minor versions correctly

---

taichi/transforms/offload.cpp

Issue: #
It's already fixed in other SPIR-V powered archs tho. Could we come up with a better way than this sequence of arch checks?

[lang] Fixed useless serial shader to blit ExternalTensorShapeAlongAxisStmt on Metal

---

python/taichi/_ti_module/__init__.py
python/taichi/_ti_module/cppgen.py
python/taichi/aot/conventions/gfxruntime140/__init__.py

[aot] Load GfxRuntime140 module from TCM

---

taichi/rhi/cuda/CMakeLists.txt
taichi/rhi/cuda/cuda_caching_allocator.cpp
taichi/rhi/cuda/cuda_caching_allocator.h
taichi/rhi/cuda/cuda_device.cpp
taichi/rhi/cuda/cuda_device.h
taichi/rhi/llvm/CMakeLists.txt
taichi/rhi/llvm/allocator.cpp
taichi/rhi/llvm/allocator.h
tests/python/test_ndarray.py

[lang] Refactor CudaCachingAllocator into a more generic caching allocator

---

requirements_test.txt

This reverts commit 4459881448107f6b737457bc9c05c715fdcfba08.
IPython 8 need python3.8, but we need to support python3.7
Issue: #

[misc] Revert "Security upgrade ipython from 7.34.0 to 8.10.0 (#7341)"

---

python/taichi/lang/struct.py

Issue: #
`python tests/run_tests.py -a cpu` fails on `test_api.py` due to `test_custom_struct`adding new attributes to `StructField` class.

[bug] Fix struct members registered to StructField class

---

python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/expr.py
python/taichi/lang/impl.py
python/taichi/lang/kernel_impl.py
python/taichi/lang/matrix.py
python/taichi/lang/ops.py
python/taichi/math/mathimpl.py
tests/python/test_custom_struct.py
tests/python/test_matrix_slice.py
tests/python/test_offline_cache.py
tests/python/test_scalar_op.py

Issue: #7447
This PR corresponds to step 3 of #7447. The code paths in `matrix.py` and `ops.py` have been significantly simplified:
- The `Matrix` class, which is for Python scope, now only contains two cases, numpy arrays for values and nested lists for host access of `SNode`/`Ndarray`. Redundant internal functions have been removed. `dt` now has effects because numpy arrays have types.
- No more `element_wise_xxx`, `uniform_matrix_inputs` and `@unary, @binary` decorators. The full dispatching logic for ops is in unique entrances `_unary_operation/_binary_operation`.
Note that Python-scope matrix slicing is temporarily disabled in this PR because the feature itself is incomplete - only read is supported. It can be re-supported in a better way in the future. Taichi-scope matrix slicing …

[Lang] Replace internal representation of Python-scope ti.Matrix with numpy arrays

---

taichi/rhi/vulkan/vulkan_device_creator.cpp

Issue: #
Vulkan memory mapping can fail when the memory is not visible. But this is checked by both our RHI and the validation layers. We ignore the validation message in this case to unblock the CI.

[aot] Hide map memory failure

---

c_api/include/taichi/cpp/taichi.hpp
misc/Test-TaichiAotWorkflow.ps1
python/taichi/_ti_module/cppgen.py
python/taichi/aot/conventions/gfxruntime140/dr.py
python/taichi/aot/conventions/gfxruntime140/sr.py
python/taichi/lang/ast/ast_transformer.py
python/taichi/lang/kernel_arguments.py
taichi/codegen/spirv/kernel_utils.cpp
taichi/codegen/spirv/kernel_utils.h
taichi/program/callable.cpp
taichi/program/callable.h

Issue: #
This PR introduces the working version of Taichi AOT module header generator and its corresponding CI script. To allow the argument fillers to assign values with meaningful function names (instead of `set_arg1` etc.), optional debug names are added to kernel arguments. Also there is a CI script to cover `ti module build` and `ti module cppgen` with test. It's written in Powershell so we only need one script to cover all the platforms.

[aot] Header generator completed

---

taichi/codegen/cpu/codegen_cpu.cpp
taichi/ir/transforms.h
taichi/program/compile_config.cpp
taichi/program/compile_config.h
taichi/python/export_lang.cpp
taichi/transforms/compile_to_offloads.cpp
taichi/transforms/make_cpu_multithreaded_range_for.cpp
taichi/transforms/offload.cpp

Issue: #7442 
This PR explicitly breaks a single range-for into two nested loops. The outer one is for CPU multithreading and thus could help LLVM properly auto-vectorize the inner loop.
Would improve memcpy/vecadd case from 8GB/s -> 54GB/s on an Apple M1 chip. Also significantly speedup x86 CPUs.

[cpu] Explicitly make cpu multithreading loop for range-fors.

---

taichi/codegen/spirv/spirv_codegen.cpp
tests/python/test_ndrange.py

[Vulkan] Fix repeated generation of array ranges in spirv codegen.

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/transforms/demote_operations.cpp
tests/cpp/transforms/constant_fold_test.cpp

Issue: #
We used to return -1 for comparison ops which is kinda confusing... This PR makes it return 1 for true. Note this change might have wide numerical impact on programs so we should pay additional attention when reviewing & bisecting for bugs in the future.

[bug] Fix logical comparison returns -1

---

python/taichi/lang/misc.py
tests/python/test_deprecation.py

Issue: #7629 
Adding notice to v1.5 release first to collect user feedback.

[cc] Add deprecation notice for cc backend

---

taichi/program/program.cpp
taichi/runtime/llvm/llvm_runtime_executor.cpp
taichi/runtime/llvm/runtime_module/internal_functions.h
taichi/runtime/llvm/runtime_module/runtime.cpp
taichi/system/memory_pool.cpp
taichi/system/memory_pool.h

Issue: #7599
MemoryPool used to startup a `daemon` thread and takes `MemoryRequest` to allocate for runtime memory allocations. However, this is redundant or even harmful because the runtime process still have to wait util the memory is allocated, plus some overhead preparing for the `MemoryRequest` object:
[Previous] Runtime memory allocation via `MemoryRequest`:
```
auto i = atomic_add_i32(&mem_req_queue->tail, 1);
taichi_assert_runtime(this, i <= taichi_max_num_mem_requests,
"Too many memory allocation requests.");
auto volatile r = &mem_req_queue->requests[i];
atomic_exchange_u64((uint64 *)&r->size, size);
atomic_exchange_u64((uint64 *)&r->alignment, alignment);
// wait for host to allocate
while (r->ptr == nullptr) {
#if defined(ARCH_cuda)
system_memfence();
#endif
};
```
This PR …

[refactor] Remove MemoryPool daemon in LLVM runtime

---

python/taichi/_snode/fields_builder.py
python/taichi/lang/impl.py

Issue: fix #7542
After this PR:
```
import taichi as ti    
ti.init()                                                                                                                                          
@ti.kernel    
def func(x:ti.template()):    
for I in ti.grouped(x):    
x[I] += 1.0    
fb = ti.FieldsBuilder()    
x = ti.field(dtype=ti.f32)    
fb.dense(ti.ij, (5, 5)).place(x)    
func(x)    
```

[lang] Improve error reporting for FieldsBuilder finalization

---

taichi/python/export_ggui.cpp

[build] Fix ssize_t type undefined errors when building with TI_WITH_LLVM=OFF on windows

---

taichi/transforms/demote_atomics.cpp

Issue: #7442
Remove the single thread CPU atomic demotion, so that LLVM could do auto-reduction for better performance.
Performance on Apple M1 CPU, single thread:
1273 -> 5122 MFlops

[cpu] Remove atomics demotion for single-thread CPU targets.

---

tests/python/test_ad_dynamic_index.py
tests/python/test_matrix.py
tests/python/test_matrix_slice.py

Issue: #
I'm still encountering failures in these unit tests and have no idea how to resolve them.
```
FAILED tests/python/test_numpy.py::test_numpy_i32[arch=cc]
FAILED tests/python/test_abs.py::test_abs_fwd[arch=cc]
FAILED tests/python/test_div.py::test_floor_div[arch=cc-arg14--10-arg24-3-arg34--4] - assert -2.0 == -4
FAILED tests/python/test_get_external_tensor_shape.py::test_get_external_tensor_shape_sum_numpy[arch=cc-size0]
FAILED tests/python/test_div.py::test_floor_div[arch=cc-arg18-10-arg28--3-arg38--4] - assert -2.0 == -4
FAILED tests/python/test_matrix.py::test_store_scalarize[arch=cc]
FAILED tests/python/test_random.py::test_random_independent_product[arch=cc]
FAILED tests/python/test_div.py::test_floor_div_pythonic[arch=cc] - assert -2 == (-10 // 3)
FAILED …
```

[test] Exclude the cc backend from tests that involve dynamic indexing

---

README.md

Issue: #
- This PR tried to fix the issue that avatar gallery SVG becomes blank PNG after getting compressed by cairo.
- Note this PR shall be merged only after https://github.com/taichi-dev/public_files/pull/12's getting merged.

[bug] Switch the gallery image used by README.

---

taichi/codegen/spirv/CMakeLists.txt
taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.cpp

Issue: #
After constant folding will fold FP16, CHI-IR passes will now emit FP16 consts. Adding support in codegen & updated SPIRV libraries and vulkan libraries to ensure proper support on the backend

[vulkan] Update SPIR-V codegen to emit FP16 consts

---

docs/lang/articles/contribution/write_test.md

Mention to reader that they need to install dependencies before running tests.

[Doc] Update write_test.md

---

python/taichi/linalg/__init__.py
python/taichi/linalg/taichi_cg.py
tests/python/test_taichi_cg.py

Issue: #7634 
This PR implements a matrix-free CG (Conjugate-Gradient) solver in Taichi. The solver targets to solve the linear equation system:
$$ Ax = b$$
where $A$ is implicitly represented as a `LinearOperator` instead of a explicitly stored matrix, hence the name "matrix-free".

[lang] Implement experimental CG(Conjugate Gradient) solver in Taichi-lang

---

python/taichi/tools/__init__.py
python/taichi/tools/vtk.py
python/taichi/ui/canvas.py
python/taichi/ui/gui.py
requirements_test.txt

Issue: #
This PR implemented several visualization utilities to help simulation users to quickly visualize their Scalar/Vector fields.
1. `gui.contour()`
Show the contour of a 2D scalar field (`ti.field`) on a gui canvas. The main purpose of this function is that it will try to handle the case where user's input scalar field's shape does **NOT** match the window size with a bilinear interpolation. For example, a user might create a scalar field as follows
```python
f = ti.field(dtype=ti.f32, shape=(100,100))
```
but later wants to display this field on a canvas of different size
```python
gui = ti.GUI('Title', res=(512, 512)
```
This function will handle this case well and stretch the image. 
```python
while gui.running:
gui.contour(f)
gui.show()
```
2. `gui.vector_field()`
Similar to …

[gui] Fluid visualization utilities

---

taichi/runtime/gfx/runtime.cpp

Issue: #
This pull request enhances the graphics runtime with better memory synchronization for `buffer` and `image` objects. It uses `buffer_barrier` and `transition_image` functions to ensure correct memory ordering.
* Add buffer barriers to synchronize memory access for buffer copy ([link](https://github.com/taichi-dev/taichi/pull/7781/files?diff=unified&w=0#diff-5de6a93ab8620f5ececa55c3e762efa567d428c85058593ab49bb641f0c4c2fcL579-R581))
* Add image barriers (transitions)  to synchronize imageaccess for buffer copy ([link](https://github.com/taichi-dev/taichi/pull/7781/files?diff=unified&w=0#diff-5de6a93ab8620f5ececa55c3e762efa567d428c85058593ab49bb641f0c4c2fcR592))
^
Generated from copilot, manually corrected a few things

[gfx] Fix runtime buffer/image copy barrier semantics

---

taichi/codegen/cpu/codegen_cpu.cpp
taichi/codegen/llvm/codegen_llvm.cpp

Issue: #7442
In this issue, Numba is a magnitude faster than Taichi due to the absence of automatic vectorization. 
The root cause is the incorrect passage of the `fast_flag`.
To solve this problem, `fast_flag` is now added to the initialization of cpu codegen. Numba and Taichi now reveal comparable performance.
Here's perf comparison:
numba:            13052.542478MFlops
taichi(master): 6544.274409MFlops
taichi(this pr):  12778.240179MFlops

[perf] Fix Taichi CPU backend compile parameter to pair performance with Numba.

---

.github/workflows/scripts/aot-demo.sh
.github/workflows/scripts/ti_build/android.py
.github/workflows/scripts/ti_build/bootstrap.py
.github/workflows/scripts/ti_build/dep.py
setup.py

Issue: #7269 
- Setting a skbuild platform name to ensure the Android build can coexist with the Linux build of the C-API shared library.
- Run ensurepip in bootstraping
- Probe mirror before use

[ci] Polishing build.py, wave 2

---

python/taichi/lang/kernel_impl.py
python/taichi/lang/util.py

Fix #7711 
Reduce import overhead by:
* Don't import pyTorch when importing Taichi. (It will be imported when necessary)
* Don't unconditionally get clangpp executable path.
The former would cutdown Taichi import overhead from ~2s down to 0.7s, while the latter further reduce it from 0.7s to 0.5s.

[misc] Optimize import overhead: pytorch and get_clangpp

---

taichi/analysis/gen_offline_cache_key.cpp

_Routine inspection_
Added missing fields:
* `ArgLoadExpression::create_load`
* `ExternalTensorExpression::is_grad`

[bug] Fix gen_offline_cache_key

---

python/taichi/lang/simt/block.py

[CUDA] Better handling shared array shape check

---

taichi/ir/statements.cpp
taichi/transforms/compile_to_offloads.cpp
taichi/transforms/lower_matrix_ptr.cpp
taichi/transforms/scalarize.cpp

Issue: #
MatrixOfGlobalPtrStmt and MatrixOfMatrixPtrStmt can greatly harm the aliasing analysis, since the semantics of which allows recursively-formed multilayered pointers, such as `MatrixOfMatrixPtrStmt[MatrixPtrStmt(AllocaStmt), ...]`
Therefore we separate out the scalarization logics for `MatrixOfGlobalPtrStmt` and `MatrixOfMatrixPtrStmt`, so that these two IRs will be lowered before going into any optimization passes.

[Lang] Seprate out the scalarization for MatrixOfMatrixPtrStmt and MatrixOfGlobalPtrStmt

---

cpp_examples/autograd.cpp
cpp_examples/run_snode.cpp
python/taichi/lang/kernel_impl.py
taichi/aot/graph_data.cpp
taichi/program/kernel.cpp
taichi/program/kernel.h
taichi/program/program.cpp
taichi/program/program.h
taichi/program/program_impl.cpp
taichi/program/program_impl.h
taichi/program/snode_rw_accessors_bank.cpp
taichi/python/export_lang.cpp
taichi/runtime/program_impls/dx/dx_program.h
taichi/runtime/program_impls/metal/metal_program.h
taichi/runtime/program_impls/opengl/opengl_program.h
taichi/runtime/program_impls/vulkan/vulkan_program.h
tests/cpp/backends/dx11_device_test.cpp
tests/cpp/ir/ir_builder_test.cpp

Issue: #7002
`Program::compile()` => `Program::compile_kernel()` + `Program::launch_kernel()`

[refactor] Split Program::compile()

---

python/taichi/_main.py

When calling  `ti gallery,` the `_exec_python_file` function in `_main.py` simply passes a `pathlib.PosixPath` object to the command. This may cause problems on Windows platforms. This PR fixes this issue by forcing using the absolute string path.

[Lang] Fix a bug on PosixPath

---

docs/conftest.py
docs/cover-in-ci.lst
docs/lang/articles/faqs/faq.md
docs/lang/articles/visualization/ggui.md
docs/lang/articles/visualization/gui_system.md

This PR updates the `bool` section and `fps_limit` for ggui.

[Doc] Update faq and ggui, and add them to CI

---

taichi/program/ndarray.cpp
taichi/program/ndarray.h
tests/python/test_ndarray.py

* #7878
* __->__ #7884
We might be able cleanup the interfaces that `Ndarray` class provides
but will leave that for a separate PR.

[Bug] Fix wrong datatype size when writing to ndarray from Python scope

---

python/taichi/ad/_ad.py
tests/python/test_ad_ndarray.py

* __->__ #7889
* #7888
* #7887
* #7878
Also added a test to show that how ndarray ad can work with PyTorch.

[autodiff] Enfore strict check for ndarrays when used in ti.ad.Tape

---

.github/workflows/scripts/ti_build/bootstrap.py
docs/lang/articles/contribution/dev_install.md

Improved the Linux installation process and the bootstrap script for taichi-dev/taichi. The script now uses the system's `pip` to install dependencies locally and checks for its availability. The documentation reflects these changes and the updated dependencies.

[ci] Build.py: Do not try to bootstrap pip (too many issues)

---

python/taichi/_kernels.py
python/taichi/lang/field.py

Issue: #https://github.com/taichi-dev/taichi/issues/7678
There's one potential hazard: if the user mistakenly filled a ti.field with out-of-scope values (like filling a ti.field(ti.u8) with > 255), it's just gonna overflow silently.

[Lang] Add cast to field.fill() interface

---

python/taichi/math/mathimpl.py

The docstrings of `inf, nan, pi, e` from the math module are missing, this PR fixes this.

[Lang] Fix the api doc search problem

---

docs/lang/articles/math/linear_solver.md

WIP. Don't merge.
Issue: #7837 
Issue: #7921 
Update contents in `linear_solver.md` to reflect the latest changes and development progress on the linear solver.

[doc] Update contents in linear_solver.md

---

python/taichi/lang/_ndarray.py
python/taichi/lang/matrix.py
python/taichi/lang/struct.py
python/taichi/types/compound_types.py
python/taichi/types/ndarray_type.py
tests/python/test_ndarray.py

* #8012
* #8010
* __->__ #8009

[refactor] Remove redundant TensorType class in python scope

---

taichi/runtime/llvm/llvm_offline_cache.cpp

you can run "ti ticache clean -p {dir}"
but ticache is not a valid command
Issue: #8015

[lang] Update ticache to cache

---

python/taichi/lang/matrix.py
python/taichi/types/compound_types.py
tests/python/test_ndarray.py

* __->__ #8012
* #8010
* #8009
TODO: deprecate `element_dim` and `element_shape` in ndarray type annotation

[lang] Support ti.types.vector and matrix as type annotation

---

taichi/codegen/spirv/kernel_utils.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/codegen/spirv/spirv_ir_builder.cpp
taichi/inc/constants.h
taichi/ir/type_utils.cpp
taichi/ir/type_utils.h
taichi/runtime/gfx/runtime.cpp

* #8034
* #8026
* #8021
* #8029
* #8019
* __->__ #8018
* #8008

[spirv] [ir] Support type u1 as arg, in buffer and as return value

---

tests/python/test_sparse_linear_solver.py

Issue: #
During the CI test of PR#8035, @ailzhang discovered that `test_gpu_sparse_solver2` test failed on the GPU backend: https://github.com/taichi-dev/taichi/actions/runs/5005755206/jobs/8978020451?pr=8035
Since PR#8035 has nothing to do with GPU backend, the failed test `test_gpu_sparse_solver2` in `tests/python/test_sparse_linear_solver.py` is considered to be flaky.
This PR disabled the `test_gpu_sparse_solver2` test by making it with `@pytest.mark.skip`. The reason for the test failure is to be investigated.

[test] Temporarily skip tests/python/test_sparse_linear_solver.py.

---

python/taichi/lang/util.py

I forgot to update `cook_dtype` to replace i32 with bool in previous Pull Requests. This new PR fixes it.
* __->__ #8066

[bug] Fix: replaced i32 with bool in cook_dtype

---

.github/workflows/scripts/ti_build/bootstrap.py
.github/workflows/scripts/ti_build/misc.py
.github/workflows/scripts/ti_build/tinysh.py

- More robust bootstrapping on Debian/Ubuntu
- Do not call `sudo` (may be absent) when running with EUID=0
- Pin `psutil` version
- Try enabling long paths on Windows

[ci] Build.py polishing, wave 5

---

taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/spirv/spirv_codegen.cpp
taichi/ir/frontend_ir.cpp
taichi/ir/ir_builder.cpp
taichi/ir/statements.cpp
taichi/ir/statements.h
taichi/transforms/auto_diff.cpp
taichi/transforms/check_out_of_bound.cpp
taichi/transforms/ir_printer.cpp
taichi/transforms/scalarize.cpp

* __->__ #8084
* #8083
* #8081

[refactor] Get rid of unnecessary element_dim in ExternalPtrStmt

---

python/taichi/linalg/sparse_matrix.py
python/taichi/linalg/sparse_solver.py

Issue: #8045 
`SparseMatrix`'s dtype should be determined by the dtype of the `SparseMatrixBuilder` from which it's built. However, it's fixed to `f32` in the current code base. This PR fix this by passing `self.dtype` instead of `dtype` to `SparseMatrix()` in the builder:
```python
def build(self, dtype=f32, _format="CSR"):                                                                                                                                                                                          
"""Create a sparse matrix using the triplets"""                                                                                                                                                                                 
taichi_arch = get_runtime().prog.config().arch …
```

[bug] Fix SparseMatrix's dtype; check for dtype in SparseSolver.

---

python/taichi/linalg/matrixfree_cg.py

Previously, `MatrixFreeCG` inappropriately assume that the intermediate vectors used in CG solver are all two-dimensional `ti.field`. This is incorrect because the dimension of `Ap` `p` and `r` should be consistent with input `b` and `x`.
Instead of simply put `vector_fields_builder.dense(ti.ij, size).place(p, r, Ap)`, now it's based on the length of `size`.
```python
def MatrixFreeCG(A, b, x, tol=1e-6, maxiter=5000, quiet=True):
...                                                                                                                                                                          
vector_fields_builder = ti.FieldsBuilder() …
```

[bug] Fix MatrixFreeCG so it can handle multiple input sizes.

---

tests/python/test_sparse_linear_solver.py

Issue: #8045 
`test_sparse_linear_solver.py` failed randomly before as reported in issue #8045. The reason for the failures was two-fold:
1. `dtype` was not aligned between the `SparseMatrixBuilder` and the `SparseSolver`, that caused 95% of the failures.
2. The randomly generated matrix A_psd is not positive-definite and caused about 5% of the failures.
With this PR fixing both of the issues, `test_sparse_linear_solver.py` should pass robustly enough. 
Note that with this PR, the two tests that were skipped before (`test_gpu_sparse_solver` and `test_gpu_sparse_solver2`) now come back. @ailzhang

[test] Fix previous discovered flaky test_sparse_linear_solver.py.

---

taichi/transforms/auto_diff.cpp

The types of the statements of autodiff are not changed to pointers. Maybe this can be done later.
* #8007
* #8126
* #8125
* #8124
* #8123
* __->__ #8122
* #8115
* #8108
* #8107

[autodiff] Update autodiff for the refactor of Alloca

---

taichi/codegen/cuda/codegen_cuda.cpp
taichi/codegen/llvm/codegen_llvm.cpp
taichi/codegen/llvm/llvm_codegen_utils.h
taichi/codegen/spirv/spirv_codegen.cpp

* #8007
* #8126
* #8125
* __->__ #8124
* #8123
* #8122
* #8115
* #8108
* #8107

[ir] Update the codegen for the refactor of Alloca

---

taichi/ir/control_flow_graph.cpp
taichi/transforms/frontend_type_check.cpp
taichi/transforms/lower_ast.cpp
taichi/transforms/offload.cpp
taichi/transforms/scalarize.cpp
taichi/transforms/type_check.cpp

* #8007
* #8126
* __->__ #8125
* #8124
* #8123
* #8122
* #8115
* #8108
* #8107

[ir] [refactor] Update passes for the refactor of Alloca

---

taichi/codegen/cuda/codegen_cuda.cpp
tests/python/test_struct.py

Issue: #8086 
This pull request adds support for bool types in `TaskCodeGenCUDA::create_intrinsic_load` which solves bit width issue on CUDA runtime. The problem was that `nvvm_ldg_global_i` does not support 1 bit integer. So we cast pointers and values to `i8` to solve this issue.
+ Added value and pointer casting in `TaskCodeGenCUDA::create_intrinsic_load`
+ Added test case

[bug] Fix struct field error on bool on cuda

---

python/taichi/linalg/matrixfree_cg.py
tests/python/test_matrixfree_bicgstab.py

This PR implements a matrix-free BICGSTAB (Biconjugate-Gradient Stabilized) solver in Taichi. The solver targets to solve the linear equation system:
$$ Ax = b$$
where $A$ is implicitly represented as a `LinearOperator` instead of a explicitly stored matrix, hence the name "matrix-free". 
BICGSTAB targets at non-symmetric matrix `A`, while `MatrixFreeCG` targets at symmetric matrix.
Related #PR 7690 (https://github.com/taichi-dev/taichi/pull/7690)

[lang] Add matrixfree BICGSTAB solver

---

taichi/transforms/compile_to_offloads.cpp

* #8219
* #8215
* #8208
* #8210
* __->__ #8207

[ir] Add lower_matrix_ptr pass to compile_function and move scalarize to the end

---

taichi/program/sparse_matrix.cpp

Issue: #
There is an extra white space in the current `mmwrite()` method, which causes reading error:
This PR removes this white space. @chunleili

[bug] Fix mmwrite format.

---

python/taichi/lang/simt/block.py
taichi/inc/internal_ops.inc.h
taichi/ir/type_system.cpp
taichi/runtime/llvm/llvm_context.cpp
taichi/runtime/llvm/runtime_module/runtime.cpp
tests/python/test_simt.py

Issue: #8289 
From the CUDA document:
Devices of compute capability 2.x and higher support three variations of __syncthreads() described below.
```cpp
int __syncthreads_count(int predicate);
```
is identical to __syncthreads() with the additional feature that it evaluates predicate for all threads of the block and returns the number of threads for which predicate evaluates to non-zero.
```cpp
int __syncthreads_and(int predicate);
```
is identical to __syncthreads() with the additional feature that it evaluates predicate for all threads of the block and returns non-zero if and only if predicate evaluates to non-zero for all of them.
```cpp
int __syncthreads_or(int predicate);
```
is identical to __syncthreads() with the additional feature that it evaluates predicate for all threads of the …

[simt] Support "__syncthreads_and", "__syncthreads_or", and "__syncthreads_count" from CUDA.

---

python/taichi/lang/impl.py

the example code comment was missing a "ti." when calling ndrange, in the "with ti.grouped" section

[Doc] Fixing typo in impl.py on ti.grouped function documentation

---

taichi/ir/control_flow_graph.cpp
taichi/transforms/auto_diff.cpp
taichi/transforms/compile_to_offloads.cpp

Issue: fixes #8444
The return type of cmp statements of tensors should be tensors of u1 instead of tensors of i32. 
Sometimes the CFG detects that an AdStackLoadTopStmt and an AdStackLoadTopAdjStmt loading the same address. I don't know if this should happen, but it stops raising error if I don't eliminate the latter statement.

[autodiff] Fix the type of cmp statements in autodiff

---

python/taichi/lang/util.py

pytorch 2.3.0 now has unsigned datatypes, add conversions for those from taichi unsigned types.

[misc] Add conversions for unsigned types, torch > 2.3.0

---

docs/lang/articles/advanced/data_oriented_class.md

This fixes a small typo: 'inheritence' -> 'inheritance'

[doc] Fix typo: 'inheritence' -> 'inheritance'

---

python/taichi/examples/simulation/implicit_fem.py
tests/python/test_implicit_fem.py
tests/python/test_reduction.py

Numpy 2.0 has removed deprecated implicit cast behavior of overflow casting to smaller dtypes. And it has removed .product in favor of .prod

[bug] Fixes for numpy 2.0 (unblocking python 3.12 release build on mac)

---

taichi/common/exceptions.h
taichi/ir/control_flow_graph.cpp
taichi/ir/expression.h
taichi/ir/ir.cpp
taichi/ir/ir.h
taichi/program/program.cpp
taichi/system/demangling.cpp
taichi/transforms/ir_printer.cpp

Does these few things:
1. Removed printing of "No DebugInfo Available". This is simply a lot of spam when printing IR. Don't print when there's nothing to print
2. Improve debug info handling for things that doesn't have source correlation, by first searching the immediate preceding statements for debug info (so the user at least know the ballpark), and when that fails prints the callable name & statement id
3. Fixed the issue within snode_writer that emits `Assign may lose precision: unknown <- f32` like crazy. (The unknown type is caused by a missing `type_check` on the indexing expression)
4. Use our exception system to emit more helpful warnings for load-to-store forwarding, e.g.:
```
[W 06/23/24 19:08:39.945 11791278] TaichiWarning
File …
```

[bug] Fix assign may lose precision warning & improve related logging

---

.github/workflows/build.yaml
.github/workflows/release.yml
.github/workflows/testing.yml

`manylinux2014`  is ancient and the built wheel is feature incomplete, it doesn't make sense to continue supporting it.

[Build] Drop manylinux2014 wheel support

---

python/taichi/ui/scene.py
python/taichi/ui/staging_buffer.py

Currently ggui only accept taichi.Field as some of its input like centers, colors.
I think the reason for this might be that some of these attributes are optional so that we must use taichi.template() to compile accordingly. However, I found no way to achieve the same with ndarray. So I split the writing process into mutiple kernels when it comes to ndarray.

[GUI] Support ndarray input
