- taichi/codegen/cc/codegen_cc.cpp
- taichi/codegen/metal/struct_metal.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/transforms/alg_simp.cpp
- taichi/transforms/auto_diff.cpp
- taichi/transforms/demote_atomics.cpp
- taichi/transforms/inlining.cpp
- taichi/transforms/offload.cpp
- taichi/transforms/type_check.cpp
Related issue = #5563, fix #5460
> [opt] Improved warning messages for statements

- docs/lang/articles/basic/external.md
> [Doc] Update external.md

- python/taichi/ad/_ad.py
- tests/python/test_abs.py
- tests/python/test_ad_atomic_fwd.py
- tests/python/test_ad_basics.py
- tests/python/test_ad_basics_fwd.py
- tests/python/test_ad_for_fwd.py
- tests/python/test_ad_if_fwd.py
> [autodiff] [refactor] Rename the parameters to param for forward mode

- misc/generate_unity_language_binding.py
> [aot] Avoid reserved words when generate C# AOT bindings

- python/taichi/lang/impl.py
- python/taichi/lang/misc.py
- python/taichi/math/mathimpl.py
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/program.cpp
- taichi/python/export_lang.cpp
- tests/python/test_math_module.py
> [Lang] Change vec2/3/4 from function calls to types

- docs/lang/articles/contribution/dev_install.md
> [doc] Removed unnecessary tags to work around a crowdIn issue

- python/taichi/ui/scene.py
> [gui] Fix unexpected type casting in GGUI

- tests/python/test_ad_for_fwd.py
> [autodiff] [test] Add more complex for loop test cases for forward mode

- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/program/texture.cpp
- taichi/rhi/device.h
- taichi/runtime/gfx/snode_tree_manager.cpp
- taichi/runtime/gfx/snode_tree_manager.h
- taichi/runtime/program_impls/dx/dx_program.h
- taichi/runtime/program_impls/llvm/llvm_program.h
- taichi/runtime/program_impls/opengl/opengl_program.h
- taichi/runtime/program_impls/vulkan/vulkan_program.h
- taichi/ui/common/field_info.cpp
> [gui] Fix snode offset (mesh disappearing bug)

- tests/cpp/aot/llvm/bitmasked_aot_test.cpp
- tests/cpp/aot/llvm/bitmasked_aot_test.py
- tests/cpp/aot/llvm/utils.py
- tests/test_utils.py
> [llvm] [aot] Add unit tests for Bitmasked SNodes with LLVM AOT

- misc/make_changelog.py
> [build] Forcing write file encoding in misc/make_changelog.py

- misc/prtags.json
> [ci] Add PR tag for dx12.

- python/taichi/examples/autodiff/jacobian.py
Add an example for computing Jacobian matrix via both forward mode and reverse mode autodiff.
> [autodiff] [example] Add an example for computing Jacobian matrix

- taichi/program/compile_config.h
- tests/run_tests.py
> [misc] Enable offline cache by default

- python/taichi/_kernels.py
- python/taichi/examples/rendering/simple_texture.py
- python/taichi/lang/_texture.py
- requirements_test.txt
- tests/python/test_api.py
- tests/python/test_texture.py
> [Lang] Support from/to_image for textures and add tests

- python/taichi/lang/_texture.py
- python/taichi/types/texture_type.py
- tests/python/test_api.py
> [doc] Add docstrings for texture related apis

- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/program/compile_config.cpp
- tests/python/test_offline_cache.py
> [llvm] Compile serially when num_thread=0

- .github/workflows/release.yml
- .github/workflows/scripts/unix_build.sh
- docs/lang/articles/contribution/dev_install.md
- docs/lang/articles/contribution/development_tips.md
- docs/lang/articles/faqs/faq.md
- docs/lang/articles/faqs/install.md
- docs/lang/articles/get-started/index.md
- misc/make_changelog.py
Cherrypicking #5632 and #5640 into rc branch
> [release] v1.1.0 patch1

- python/taichi/lang/impl.py
- taichi/codegen/spirv/spirv_codegen.cpp
Related issue = close #5660 #5184 
Need some effort to add full support so we better give a warning atm.
> [lang] Give warning about printing in Vulkan

- python/taichi/ad/_ad.py
- python/taichi/lang/impl.py
Improve the seed fill efficiency using `from_numpy` and `fill`.
> [autodiff] Use external array fill to initialize and clear seed

- .github/workflows/release.yml
- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- .github/workflows/testing.yml
- tests/python/examples/algorithm/test_laplace.py
- tests/python/examples/algorithm/test_print_offset.py
- tests/python/examples/autodiff/test_minimization.py
- tests/python/examples/autodiff/test_regression.py
- tests/python/examples/autodiff/test_simple_derivative.py
- tests/python/examples/rendering/test_cornell_box.py
- tests/python/examples/rendering/test_taichi_logo.py
- tests/python/examples/simulation/test_ad_gravity.py
- tests/python/examples/simulation/test_mpm99.py
- tests/python/examples/simulation/test_nbody.py
- tests/test_utils.py
> [ci] Only run portion of tests on PR draft

- taichi/analysis/offline_cache_util.cpp
- taichi/analysis/offline_cache_util.h
- taichi/rhi/cuda/cuda_context.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
Cherrypicking #5651 into rc branch
> [bug] Fix bug that kernel names are not correctly captured by the profiler (#5651)

- tests/python/examples/algorithm/test_laplace.py
- tests/python/examples/algorithm/test_print_offset.py
- tests/python/examples/autodiff/test_minimization.py
- tests/python/examples/autodiff/test_regression.py
- tests/python/examples/autodiff/test_simple_derivative.py
- tests/python/examples/rendering/test_cornell_box.py
- tests/python/examples/rendering/test_taichi_logo.py
- tests/python/examples/simulation/test_ad_gravity.py
- tests/python/examples/simulation/test_mpm99.py
- tests/python/examples/simulation/test_nbody.py
> [ci] Fix python/examples crashes in non-lite test mode

- taichi/runtime/llvm/llvm_offline_cache.cpp
https://github.com/taichi-dev/taichi/runs/7717277044?check_suite_focus=true
> [bug] Fix potential bug of loading of offline cache

- .github/workflows/scripts/unix_test.sh
> [ci] Temporarily disable M1 vulkan tests (bot3 is ill)

- .github/workflows/scripts/aot-demo.sh
> [doc] Add comments to explain the commit Id for Build Andriod Demos CI pipeline

- .github/workflows/scripts/unix_test.sh
- tests/python/test_ad_for_fwd.py
> [ci] Temporarily disable a M1 vulkan test

- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/transforms/alg_simp.cpp
- taichi/transforms/lower_ast.cpp
- tests/python/test_basics.py
- tests/python/test_for_break.py
- tests/python/test_mod.py
> [bug] RC v1.1.0 patch2

- docs/lang/articles/visualization/ggui.md
- python/taichi/examples/autodiff/diff_sph/diff_sph.py
- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
- python/taichi/examples/ggui_examples/mass_spring_game_ggui.py
- python/taichi/examples/ggui_examples/mpm3d_ggui.py
- python/taichi/examples/simulation/implicit_fem.py
- python/taichi/ui/camera.py
- python/taichi/ui/ui.py
- python/taichi/ui/window.py
- tests/python/test_ggui.py
Related issue = #5426 
This PR completed the items in the *Renames* section. Old APIs are kept alive but deprecation warnings will be emitted.
> [gui] GGUI renames

- docs/lang/articles/advanced/odop.md
This should be an follow-up of #5365.
> [doc] Rename ti.struct_class to ti.dataclass

- python/taichi/ui/canvas.py
- python/taichi/ui/staging_buffer.py
- tests/python/test_ggui.py
- x.py
This PR supported `set_image` with textures.
> [gui] Support set_image with texture

- taichi/runtime/llvm/llvm_runtime_executor.cpp
> [bug] Properly delete functions of a SNode Tree in CUDA backend

- .github/workflows/scripts/aot-demo.sh
- docs/lang/articles/advanced/odop.md
- docs/lang/articles/visualization/ggui.md
- python/taichi/examples/autodiff/diff_sph/diff_sph.py
- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
- python/taichi/examples/ggui_examples/mass_spring_game_ggui.py
- python/taichi/examples/ggui_examples/mpm3d_ggui.py
- python/taichi/examples/simulation/implicit_fem.py
- python/taichi/ui/camera.py
- python/taichi/ui/ui.py
- python/taichi/ui/window.py
- taichi/runtime/llvm/llvm_offline_cache.cpp
- tests/python/test_ggui.py
Cherrypicking #5704 #5706 #5682
> [misc] Rc v1.1.0 patch3

- tests/python/test_ad_math_func.py
> [test] Fix autodiff test for unsupported shift ptr

- .github/workflows/scripts/unix_test.sh
- tests/cpp/aot/sph_aot.py
> [ci] Fix TI_SKIP_CPP_TESTS

- .github/workflows/testing.yml
> [ci] Rename lite test CI label, force full test on rc branch

- .github/workflows/testing.yml
- tests/run_tests.py
> [ci] Test the offline cache every day

- tests/python/test_aot.py
- tests/python/test_graph.py
* #5775
* __->__ #5774
* #5773
> [test] Expand python aot test coverage for opengl backend

- docs/lang/articles/basic/external.md
> [Doc] Fix struct to numpy example typo

- .github/workflows/release.yml
> [ci] Skip C++ tests on macOS + CPU

- .github/workflows/release.yml
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
- ci/Dockerfile.ubuntu.18.04
> [ci] Workaround nightly C++ test crash

- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
> [Lang] Improve loop error message and remove the check for real type id

- tests/python/test_graph.py
Note that we don't support passing `ti.types.struct` to `ti.kernel` yet
so the only place you can pass it as `ti.template()` is inside
`ti.func`. Since `ti.func` is inlined this is "naturally" supported.
fixes #5771
> [test] Add a cgraph test with template args in ti.func

- cmake/TaichiExamples.cmake
- taichi/runtime/program_impls/vulkan/CMakeLists.txt
> [build] [bug] Fix Taichi build with vulkan on and opengl off

- python/taichi/graph/_graph.py
- tests/python/test_aot.py
> [bug] Fix: GraphBuilder::Sequential unable to handle Matrix-type arguments

- .github/workflows/scripts/aot-demo.sh
- .github/workflows/scripts/common-utils.sh
- .github/workflows/scripts/unix-build-v2.sh
- .github/workflows/testing.yml
- ci/Dockerfile.android-sdk.18.04
- ci/Dockerfile.ubuntu.18.04
Related issue = #5799 
Prev PR is  'merged' with no changes.
> [ci] Regenerate AOT binaries for every Android smoke test

- python/taichi/lang/impl.py
> [autodiff] Fix global data access rule checker memory allocation

- docs/lang/articles/faqs/faq.md
> [Doc] New FAQs added

- python/taichi/lang/expr.py
- taichi/transforms/frontend_type_check.cpp
- tests/python/test_bool_op.py
> [Lang] Allow implicit conversion of integer types in if conditions

- taichi/analysis/offline_cache_util.cpp
- taichi/analysis/offline_cache_util.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_builder_impl.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.h
- tests/python/test_offline_cache.py
Working in progress: Not multi-thread/process safe now.
I will fix this problem and other potential bugs in next PRs.
Testing on my Win11:
> [vulkan] Support offline cache on Vulkan

- taichi/rhi/device.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_builder_impl.h
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
> [vulkan] Detect and set device-capabilities for aot::TargetDevice used in offline cache

- python/taichi/examples/graph/texture_graph.py
> [aot] Removed Unexpected debug code in repo

- python/taichi/lang/any_array.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_impl.py
- python/taichi/types/ndarray_type.py
- tests/python/test_function.py
> [bug] Enabled NdarrayType & MatrixType annotation parsing for ti.func

- docs/lang/articles/get-started/index.md
> [doc] Updated supported backend DX 11

- taichi/runtime/gfx/CMakeLists.txt
- taichi/runtime/gfx/offline_cache_manager.cpp
- taichi/runtime/gfx/offline_cache_manager.h
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.h
> [gfx] Unify the implementation of offline cache for gfx backends

- taichi/rhi/interop/CMakeLists.txt
- tests/python/test_ggui.py
> [bug] [gui] Fix cpu vulkan interop build and enable ggui cpu tests

- docs/lang/articles/advanced/quant.md
> [doc] Updated Quantized data types

- .github/workflows/scripts/unix-build-v2.sh
- .github/workflows/scripts/unix_build.sh
- .github/workflows/testing.yml
> [bug] Remove mistakenly-added C-API compilation from release pipeline

- taichi/inc/frontend_statements.inc.h
- taichi/transforms/frontend_type_check.cpp
> [misc] Remove FrontendEvalStmt

- docs/lang/articles/differentiable/differentiable_programming.md
> [doc] Updated forward-mode autodiff

- c_api/tests/c_api_aot_test.cpp
- c_api/tests/c_api_cgraph_test.cpp
- tests/test_utils.py
> [aot] [test] Fix c api aot tests for vulkan and opengl backend

- python/taichi/_kernels.py
- python/taichi/ad/_ad.py
- tests/python/test_ad_snode_grad_type.py
> [autodiff] Support clear gradients by type

- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/codegen/llvm/llvm_compiled_data.h
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- tests/cpp/llvm/llvm_offline_cache_test.cpp
Related issue = #5511
The attributes are not yet in use now, but they will be used in PRs afterwards.
> [llvm] Add attributes to LLVMCompiledData

- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/runtime/llvm/llvm_offline_cache.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/util/offline_cache.h
Prepare to implement cache cleaning for gfx backends
> [refactor] Refactor the implementation of cleaning offline cache files

- taichi/codegen/dx12/codegen_dx12.cpp
- taichi/codegen/dx12/codegen_dx12.h
Copy from cpu codegen.
Replaced cpu_parallel_range/mesh_for with gpu_parallel_range/mesh_for.
> [dx12] Drop code for dx12 codegen.

- taichi/python/export_lang.cpp
- tests/python/test_aot.py
- tests/python/test_graph.py
> [aot] Support i8/u8 args in vulkan cgraph

- .github/workflows/scripts/unix_test.sh
> [ci] Temporarily lower CUDA tests parallelism by 1 (4->3)

- docs/lang/articles/reference/global_settings.md
Add a note about the offline cache in the `print_ir` part to help users.
> [doc] Add a note about the offline cache in the print_ir part

- python/taichi/lang/matrix.py
> [autodiff] Fix matrix dual

- docs/lang/articles/get-started/cloth_simulation.md
> [doc] Cloth simulation tutorial

- .github/workflows/testing.yml
> [ci] Adjust Windows GPU task buildbot tag

- tests/run_tests.py
> [bug] Uncomment to run cpp tests correctly

- .github/workflows/scripts/win_test.ps1
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen.h
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cpu/codegen_cpu.h
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/cuda/codegen_cuda.h
- taichi/codegen/llvm/llvm_compiled_data.h
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/codegen/wasm/codegen_wasm.h
- taichi/runtime/cpu/aot_module_builder_impl.cpp
- taichi/runtime/cpu/aot_module_loader_impl.cpp
- taichi/runtime/cuda/aot_module_builder_impl.cpp
- taichi/runtime/cuda/aot_module_loader_impl.cpp
- taichi/runtime/llvm/llvm_aot_module_builder.cpp
- taichi/runtime/llvm/llvm_context.cpp
- taichi/runtime/llvm/llvm_context.h
- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/runtime/llvm/llvm_offline_cache.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/program_impls/llvm/llvm_program.h
- taichi/runtime/wasm/aot_module_builder_impl.cpp
- tests/cpp/codegen/refine_coordinates_test.cpp
- tests/cpp/llvm/llvm_offline_cache_test.cpp
- tests/python/test_runtime.py
> [llvm] [refactor] Remove the use of vector with size=1

- python/taichi/lang/impl.py
- taichi/python/export_lang.cpp
> [lang] Merge ti_core.make_index_expr and ti_core.subscript

- docs/lang/articles/get-started/accelerate_python.md
> [doc] Indenting

- docs/lang/articles/get-started/cloth_simulation.md
> [doc] Fixed a format issue

- README.md
Just a small change to fix spelling of numerical and nightly in README.md
> [Doc] Fix spelling of numerical and nightly in README.md

- README.md
> [doc] Fix a typo in README.md

- ci/scripts/ubuntu_build_test.sh
> [CI] Update torch and cuda version

- python/taichi/lang/ast/ast_transformer.py
> [Mesh] [bug] Fix nested mesh for

- .github/pull_request_template.md
Now that we use PR title & description as commit message let's simplify this template a bit to avoid polluting commit history.
> [misc] Simplify PR template

- python/taichi/_funcs.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_matrix.py
> [lang] Preserve shape info for Vectors

- tests/test_config.json
- tests/test_utils.py
> [build] Refactor test infrastructure for AOT tests

- c_api/include/taichi/cpp/taichi.hpp
> [aot] Pragma once in taichi.cpp

- .github/workflows/scripts/win_build.ps1
- ci/windows/win_build_test.ps1
Build based on release/15.x branch and cherry-picked some patch for DX12.
Issue: #5276
> [ci] Update prebuild binary for llvm 15.

- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/codegen/spirv/spirv_ir_builder.h
Issue: #6075 (followup)
Rename debug_ segment to a more proper name.
> [spirv] [refactor] Rename debug_ segment to names_

- taichi/runtime/llvm/llvm_offline_cache.cpp
- taichi/util/io.h
> [bug] Fix cleaning cache failed

- taichi/analysis/offline_cache_util.cpp
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.h
- tests/python/test_offline_cache.py
> [opengl] Support offline cache on opengl

- docs/lang/articles/get-started/accelerate_pytorch.md
Issue: #
Added one more scenario to Getting Started
> [Doc] Added Accelerate PyTorch

- docs/lang/articles/contribution/developer_utilities.md
- docs/lang/articles/contribution/development_tips.md
- docs/lang/articles/contribution/doc_writing.md
- docs/lang/articles/contribution/style_guide_en.md
- docs/lang/articles/contribution/write_test.md
- docs/lang/articles/contribution/writing_cpp_tests.md
Issue: #
Move "Developer utilities" from "Debugging" to "Contribution".
> [Doc] Move developer utilities to contribution

- docs/lang/articles/type_system/type.md
> [doc] Fixed a broken link

- taichi/rhi/vulkan/vulkan_device_creator.cpp
> [vulkan] Instruct users to install vulkan sdk if they want to use validation layer

- tests/python/test_matrix.py
> [Lang] Fix invalid assertion for matrix values

- taichi/codegen/llvm/codegen_llvm.cpp
- tests/python/test_mod.py
> [Llvm] Fix codegen for div (unsigned)

- docs/lang/articles/basic/field.md
- docs/lang/articles/get-started/accelerate_pytorch.md
- docs/lang/articles/type_system/type.md
Issue: #
Miscellaneous updates
> [doc] Miscellaneous editorial updates

- taichi/codegen/cc/codegen_cc.cpp
- taichi/codegen/cc/runtime/base.h
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/metal/codegen_metal.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/runtime/llvm/runtime_module/runtime.cpp
- taichi/runtime/metal/shaders/helpers.metal.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/demote_operations.cpp
Issue: #6134
`floordiv` is already demoted and should not appear in codegen.
> [refactor] Remove redundant codegen of floordiv

- python/taichi/algorithms/_algorithms.py
Issue: https://forum.taichi.graphics/t/topic/3074
> [lang] Remove print at the end of parallel sort

- taichi/cache/gfx/cache_manager.cpp
> [bug] Fix crashing when loading old offline cache files (for gfx backends)

- requirements_test.txt
> [Test] Add scipy to test GPU sparse solver

- taichi/codegen/codegen.h
> [llvm] Add comment about the structure of the CodeGen

- taichi/rhi/vulkan/vulkan_device.cpp
> [aot] Fixed texture interop

- docs/lang/articles/math/sparse_matrix.md
Issue: #
Position change only.
> [doc] Updated the position of Sparse Matrix

- docs/lang/articles/debug/debugging.md
> [Doc] Refactor debugging

- taichi/codegen/metal/codegen_metal.cpp
- taichi/codegen/metal/codegen_metal.h
- taichi/runtime/metal/aot_module_builder_impl.cpp
- taichi/runtime/metal/aot_module_builder_impl.h
- taichi/runtime/metal/aot_module_loader_impl.cpp
- taichi/runtime/metal/kernel_manager.cpp
- taichi/runtime/metal/kernel_manager.h
- taichi/runtime/metal/kernel_utils.cpp
- taichi/runtime/metal/kernel_utils.h
Issue: #4401 
* Fix a potential bug in metal AOT
* Prepare for implementing offline cache on metal
> [metal] Maintain a print string table per kernel

- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/program/program.h
- taichi/runtime/llvm/llvm_runtime_executor.cpp
- taichi/runtime/llvm/runtime_module/runtime.cpp
- taichi/transforms/alg_simp.cpp
- taichi/transforms/constant_fold.cpp
- tests/python/test_overflow.py
#6166 + #6173 + disable windows test
> [LLVM] Add runtime overflow detection on LLVM-based backends

- python/taichi/lang/_texture.py
- requirements_test.txt
> [bug] Relax dependent Pillow version

- docs/lang/articles/basic/field.md
> [doc] Editorial updates to field.md

- taichi/ir/frontend_ir.cpp
- tests/cpp/ir/ir_builder_test.cpp
Also added a test in ir builder test, not really related to this PR but thought it was good to have more test coverage for it.
Issue: #
> [lang] Set ret_type for AtomicOpStmt

- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
> [vulkan] [opengl] Enable offline cache by default on Vulkan and OpenGL

- docs/lang/articles/contribution/writing_cpp_tests.md
Issue: https://github.com/taichi-dev/taichi/pull/6038#issue-1369553136
> [doc] Update document about building and running Taichi C++ tests

- .github/workflows/testing.yml
Set TI_WITH_DX12 to OFF for CPU only test.
> [dx12] Disable DX12 for cpu only test.

- taichi/runtime/program_impls/opengl/CMakeLists.txt
> [bug] Fix link error with TI_WITH_OPENGL:BOOL=ON but TI_WITH_VULKAN:BOOL=OFF

- .gitmodules
- cmake/TaichiCore.cmake
add DirectX-Headers as a submodule.
Issue: #5276
> [dx12] Add DirectX-Headers as a submodule

- .github/workflows/testing.yml
> [ci] Lift GitHub CI timeout

- taichi/transforms/compile_to_offloads.cpp
Add demote atomics before gdar checker.
> [autodiff] Add demote atomics before gdar checker

- taichi/aot/module_builder.cpp
- taichi/aot/module_builder.h
- taichi/runtime/dx12/aot_module_builder_impl.cpp
- taichi/runtime/dx12/aot_module_builder_impl.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_builder_impl.h
- taichi/runtime/llvm/aot_graph_data.h
- taichi/runtime/llvm/llvm_aot_module_builder.cpp
- taichi/runtime/llvm/llvm_aot_module_builder.h
- taichi/runtime/llvm/llvm_aot_module_loader.cpp
- taichi/runtime/program_impls/llvm/llvm_program.cpp
> [bug] Fix AotModuleBuilder::add_compiled_kernel

- python/taichi/lang/kernel_impl.py
- tests/python/test_ad_global_data_access_rule_checker.py
Skip gdar checking for user defined grad kernel.
> [autodiff] Skip gdar checking for user defined grad kernel

- taichi/transforms/ir_printer.cpp
> [bug] Fix segmentation fault with TextureOpStmt ir_printer

- tests/run_tests.py
- tests/test_utils.py
> [bug] Fix duplicate runs with 'run_tests.py --cpp -k' when selecting AOT tests

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_literal.py
> [lang] MatrixType bug fix: Fix MatrixType validations in build_call_if_is_type()

- c_api/docs/taichi/taichi_core.h.md
- c_api/include/taichi/taichi_core.h
- c_api/include/taichi/taichi_opengl.h
- c_api/include/taichi/taichi_unity.h
- c_api/include/taichi/taichi_vulkan.h
- c_api/taichi.json
- docs/lang/articles/c-api/taichi_core.md
- misc/generate_c_api.py
- misc/generate_c_api_docs.py
- misc/taichi_json.py
Inline documentation in C headers.
> [aot] Inline documentations

- taichi/runtime/program_impls/metal/metal_program.cpp
- taichi/util/offline_cache.cpp
- taichi/util/offline_cache.h
- tests/run_tests.py
> [metal] Enable offline cache by default on Metal

- c_api/include/taichi/taichi.h
> [aot] Include taichi_cpu.h in taich.h

- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
This reverts commit 082b4d0465b97c68c2aba8fc0b4c7d78bc7302b5.
Issue: #
> [ci] Revert "Add end-to-end CI tests for meshtaichi (#6321)"

- c_api/src/taichi_vulkan_impl.cpp
> [aot] Fixed export of get_instance_proc_addr

- .clang-tidy
- taichi/codegen/spirv/lib_tiny_ir.h
- taichi/program/sparse_matrix.h
* #6335
* #6334
* #6333
* #6332
* __->__ #6331
* #6330
> [build] Enable modernize-use-override in clang-tidy

- .clang-tidy
- taichi/rhi/device.cpp
* #6335
* #6334
* __->__ #6333
* #6332
* #6331
* #6330
> [build] Enable google-build-explicit-make-pair check in clang-tidy

- .github/workflows/testing.yml
- taichi/common/ref_counted_pool.h
- taichi/python/export_ggui.cpp
- taichi/rhi/opengl/opengl_device.h
- taichi/rhi/vulkan/vulkan_device.cpp
- taichi/rhi/vulkan/vulkan_device.h
- taichi/rhi/vulkan/vulkan_device_creator.cpp
- taichi/rhi/vulkan/vulkan_loader.cpp
- taichi/rhi/vulkan/vulkan_loader.h
- taichi/rhi/vulkan/vulkan_utils.h
- taichi/runtime/program_impls/vulkan/vulkan_program.h
- taichi/ui/backends/vulkan/canvas.h
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/backends/vulkan/renderables/circles.h
- taichi/ui/backends/vulkan/renderables/lines.h
- taichi/ui/backends/vulkan/renderables/mesh.h
- taichi/ui/backends/vulkan/renderables/particles.h
- taichi/ui/backends/vulkan/renderables/scene_lines.h
- taichi/ui/backends/vulkan/renderables/set_image.cpp
- taichi/ui/backends/vulkan/renderables/set_image.h
- taichi/ui/backends/vulkan/renderables/triangles.h
- taichi/ui/backends/vulkan/renderer.cpp
- taichi/ui/backends/vulkan/swap_chain.cpp
- taichi/ui/backends/vulkan/window.cpp
- taichi/ui/backends/vulkan/window.h
- taichi/ui/common/window_base.cpp
- taichi/ui/common/window_base.h
* #6345
* #6344
* __->__ #6343
* #6342
> [build] Enable TI_WITH_VULKAN and TI_WITH_OPENGL for clang-tidy checks

- docs/lang/articles/contribution/contributor_guide.md
* __->__ #6345
* #6344
* #6343
* #6342
> [Doc] Add instructions about running clang-tidy checks locally

- c_api/src/taichi_core_impl.cpp
> [aot] Removed constraint on same-allocation copy

- .github/workflows/testing.yml
> [ci] Android Demo: leave Docker containers intact for debugging

- docs/lang/articles/debug/debugging.md
> [doc] Update doc about how to use vulkan print

- python/taichi/lang/kernel_impl.py
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- tests/python/test_return.py
> [bug] Fix returning uint64 as signed integer

- taichi/transforms/make_mesh_block_local.cpp
continue from: https://github.com/taichi-dev/taichi/pull/6306
> [mesh] Fix MeshTaichi warnings in CUDA backend

- taichi/program/kernel.cpp
> [bug] Fix potential bug in #6362 (#6363)

- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- tests/python/test_matrix_slice.py
Issue: #4257, #5819
Let's refine the matrix slice feature a bit before supporting it with the new MatrixType.
> [lang] [refactor] Refine implementation and tests for matrix slice

- python/taichi/lang/ast/ast_transformer.py
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- tests/python/test_matrix_return.py
> [lang] MatrixType bug fix: Support returning an Expr with MatrixType

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_impl.py
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- tests/python/test_ndrange.py
- tests/python/test_return.py
> [misc] Rc v1.2.0 c1

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_ndrange.py
> [misc] Revert PR 6360

- docs/lang/articles/debug/debugging.md
- python/taichi/ad/_ad.py
- python/taichi/lang/kernel_impl.py
- taichi/program/kernel.cpp
- tests/python/test_ad_gdar_diffmpm.py
- tests/python/test_ad_global_data_access_rule_checker.py
> [misc] Rc v1.2.0 cherry-pick PR number 2

- python/taichi/lang/matrix.py
- python/taichi/lang/util.py
> [Lang] Replace matrix warning param by current logging level

- python/taichi/lang/kernel_impl.py
- tests/python/test_numpy.py
Reverts taichi-dev/taichi#6376 since it broke examples in release tests https://github.com/taichi-dev/taichi/actions/runs/3286644295/jobs/5416572173
> Revert "[bug] [lang] Fix copyback for fortran contiguous numpy arrays"

- taichi/codegen/spirv/spirv_codegen.cpp
- tests/python/test_ndarray.py
Issue: #
Before this PR the generated spirv shader fails spirv validation.
> [spirv] Fix duplicated interface id for global_tmp buffers

- docs/lang/articles/differentiable/differentiable_programming.md
> [Doc] Update global data access rule checker in doc

- docs/lang/articles/basic/external.md
- python/taichi/lang/_ndarray.py
- python/taichi/lang/field.py
- python/taichi/lang/matrix.py
- tests/python/test_numpy_io.py
> [lang] Fix from_numpy()for vector field with a non-contiguous array

- python/taichi/_kernels.py
- python/taichi/lang/matrix.py
- tests/python/test_field.py
- tests/python/test_fill.py
Issue: #6318
The implementation and tests have been refactored by the way to ease future maintenance efforts.
> [Lang] [bug] Allow filling a field with Expr

- docs/lang/articles/reference/global_settings.md
> [Doc] Update global_settings.md

- c_api/tests/taichi_sparse_test.cpp
> [bug] Fix flaky test with taichi_sparse_test.cpp

- taichi/rhi/vulkan/vulkan_device_creator.cpp
See https://github.com/taichi-dev/taichi/issues/6295#issuecomment-1288522905.
> [vulkan] [bug] Stop using the buffer device address feature on macOS

- python/taichi/_lib/utils.py
- python/taichi/ui/utils.py
> [error] Warn Linux users about manylinux2014 build on startup

- c_api/tests/c_api_interface_test.cpp
- taichi/rhi/vulkan/vulkan_device.cpp
> [aot] Warns the user when mapping device-only memory

- python/taichi/examples/simulation/snow_phaseField.py
> [example] Ti-example: phase field simulation of snow growth

- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/inc/rhi_constants.inc.h
- taichi/rhi/vulkan/vulkan_device_creator.cpp
Issue: #
Here's my guess of source of validation errors in AOT, @dio-exploded would you mind help verify if this fixes your validation error?
> [vulkan] Disable NoSignedWrap decoration on vulkan backend

- .github/workflows/scripts/common-utils.sh
- .github/workflows/scripts/unix-build.sh
- .github/workflows/testing.yml
- tests/cpp/llvm/llvm_offline_cache_test.cpp
Note the `.bc` files are still compiled with clang-10 but this is fine, we can upgrade step by step
Issue: #
> [ci] Swtich CPU jobs to use prebuilt LLVM15

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_ast_refactor.py
- tests/python/test_scalar_op.py
> [lang] MatrixType bug fix: support star & loop operations over matrix-typed Expr

- misc/prtags.json
Issue: # https://github.com/taichi-dev/taichi/issues/6434
Add pr tag for amdgpu
> [ci] Add PR tag for amdgpu.

- .github/workflows/scripts/aot-demo.sh
If we pin on a commit taichi-aot-demo it's hard to catch all the errors.
Let's see if things already exploded... 
Issue: #
> [ci] Move implicit fem android demo to master branch

- .github/workflows/scripts/aot-demo.sh
> [aot] Modify aot-demo.sh to track master branch of taichi-aot-demo

- .github/workflows/testing.yml
> [ci] Switch linux gpu job to use LLVM 15

- taichi/ir/statements.h
- tests/python/test_matrix_slice.py
Issue: #5819
This is a follow-up PR of #6430.
> [test] MatrixType refactor: Add tests for writing to matrix slice

- taichi/transforms/cache_loop_invariant_global_vars.cpp
- taichi/transforms/make_mesh_block_local.cpp
- tests/python/test_for_break.py
> [misc] V1.2.1: cherry-pick 6369, 6462

- .github/workflows/scripts/unix-build.sh
> [ci] Package C-API in nightly builds

- python/taichi/lang/kernel_impl.py
Issue: #5662 
Some cleanup/refactor before implementation.
> [refactor] Remove unused has_external_arrays flag

- c_api/include/taichi/cpp/taichi.hpp
> [aot] Move arch in Runtime wrapper object

- .github/workflows/notify_on_failure.yml
> [ci] Add taichi bot to send message to slack on master failure

- python/taichi/lang/kernel_impl.py
- tests/python/test_kernel_arg_errors.py
> [refactor] Simplify logic in get_function_body.

- .github/workflows/notify_on_failure.yml
> [ci] Fix master bot text format

- tests/python/test_dynamic.py
Issue: #2179
It seems that CUDA has fixed this issue.
> [cuda] Enable test on dense dynamic field

- .github/workflows/notify_on_failure.yml
> [ci] Fix master notification bot json format

- python/taichi/tools/video.py
Reverts taichi-dev/taichi#6289
> Revert "[Misc] Improve gif output compression rate"

- tests/python/test_offline_cache.py
> [test] Test real function on enabling the offline cache

- .github/workflows/testing.yml
> [ci] Raise CPU tasks timeout (temporary workaround)

- .github/workflows/notify_on_failure.yml
> [ci] GitHub Action slack bot message, again :(

- .github/workflows/scripts/aot-demo.sh
- .github/workflows/testing.yml
> [build] Fix error with AOT file generation & reset Android test folder per run

- taichi/ir/frontend_ir.cpp
- tests/python/test_matrix.py
> [lang] MatrixType bug fix: Fix error message mismatch

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/ops.py
- tests/python/test_linalg.py
> [lang] MatrixType bug fix: Allow builtin any() and all()

- python/taichi/_funcs.py
- python/taichi/lang/matrix.py
- python/taichi/lang/matrix_ops.py
- python/taichi/lang/matrix_ops_utils.py
- tests/python/test_linalg.py
> [Lang] MatrixType refactor: Support dot/cross/outer_product

- taichi/program/compile_config.cpp
- taichi/transforms/scalarize.cpp
- tests/python/test_matrix.py
- tests/python/test_scan.py
- tests/python/test_shared_array.py
> [lang] MatrixType bug fix: Fix matrix indexing error with SharedArray

- .github/workflows/scripts/win_build.ps1
- .github/workflows/testing.yml
> [ci] GitHub Actions: Merge CPU & GPU tasks

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- tests/python/conftest.py
- tests/python/test_function.py
> [ci] Marker for running resource intensive tests in serial

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/impl.py
- tests/python/test_bls.py
- tests/python/test_matrix.py
> [lang] MatrixType bug fix: Fix type error with struct-for loop index

- .github/workflows/scripts/aot-demo.sh
Issue: #
Debug in CI since I don't have an android phone ...
> [aot] Switch aot tests to use a script in taichi-aot-demo

- tests/python/conftest.py
> [ci] Terminate (and restart) test worker when test fails

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_print.py
> [bug] Sync after executing kernels which have print inside

- python/taichi/lang/kernel_impl.py
- python/taichi/linalg/sparse_matrix.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime_module/internal_functions.h
- tests/python/test_sparse_linear_solver.py
Reverts taichi-dev/taichi#6563
> Revert "[lang] Build sparse matrix using ndarray"

- .github/workflows/release.yml
> [build] Remove macOS 10.14 from release tests

- tests/python/conftest.py
> [ci] Terminate workers even earlier when test fails

- .github/workflows/release.yml
> [misc] Fix release tests

- .github/workflows/release.yml
> [misc] Fix release tests 

- .github/workflows/release.yml
> [build] Remove macos 10 14

- python/taichi/lang/expr.py
- tests/python/test_math_module.py
> [lang] MatrixType bug fix: Add attributes n & m

- python/taichi/lang/kernel_impl.py
- python/taichi/linalg/sparse_matrix.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/runtime_module/internal_functions.h
- tests/python/test_sparse_linear_solver.py
> [lang] Fix sparse matrix builder segment fault

- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- taichi/program/compile_config.cpp
> [bug] MatrixType bug fix: Fix indexing support for custom vector types

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- requirements_test.txt
- tests/python/conftest.py
- tests/python/test_function.py
- tests/python/test_global_thread_idx.py
- tests/python/test_memory.py
- tests/python/test_mpm88.py
- tests/python/test_ndarray.py
- tests/python/test_simt.py
- tests/run_tests.py
> [ci] CUDA tests speed up

- python/taichi/lang/matrix.py
- tests/python/test_vector_swizzle.py
Reverts taichi-dev/taichi#6568
> Revert "[bug] MatrixType bug fix: Fix indexing support for custom vector types"

- tests/python/test_memory.py
> [bug] Loose memory leak constraint for test_memory

- .github/workflows/scripts/aot-demo.sh
- c_api/docs/taichi/taichi_core.h.md
- c_api/include/taichi/cpp/taichi.hpp
- c_api/include/taichi/taichi_core.h
- c_api/include/taichi/taichi_vulkan.h
- c_api/src/taichi_core_impl.cpp
- c_api/src/taichi_gfx_impl.cpp
- c_api/taichi.json
- c_api/tests/c_api_interface_test.cpp
- docs/lang/articles/c-api/taichi_core.md
- docs/lang/articles/c-api/taichi_vulkan.md
- misc/generate_c_api.py
- misc/generate_c_api_docs.py
- misc/generate_unity_language_binding.py
- taichi/aot/module_loader.h
- taichi/inc/rhi_constants.inc.h
- taichi/rhi/device_capability.h
> [aot] C-API device capability query

- docs/lang/articles/faqs/faq.md
Issue: #6404 
This PR doesn't solve the issue in #6404 but it helps a bit for beginners. 
Our type hint isn't perfect yet, but it should at least work for the python apis. ;) Adding a faq so that users can find them.
> [doc] Add faq about how to use code completion in vscode

- tests/python/test_aot.py
Issue: #6616 
Follow up of #6618.
> [aot] Yet another device capability test

- .github/workflows/release.yml
- tests/python/conftest.py
- tests/python/test_function.py
- tests/python/test_offline_cache.py
Issue: #
Try addressing CUDA OOM during test
> [test] Tuning CUDA tests resource consumption

- .github/workflows/scripts/unix-build.sh
- .github/workflows/testing.yml
- CMakeLists.txt
- taichi/runtime/cpu/jit_cpu.cpp
Issue: #6447 
Just trying my luck in CI since my local mac is on macOS12.
> [ci] Move m1 job to use build with LLVM 15

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- requirements_test.txt
- tests/python/conftest.py
Issue: #
Related `pytest-xdist` patch: https://github.com/taichi-dev/pytest-xdist/commit/c686d0ddb543860cde6d1f130956e7e4ca1d74b3
> [ci] Adaptively laying off test workers on CUDA OOM

- python/taichi/lang/kernel_impl.py
related: #5662
We need runtime arg handling to be more modular to prepare for struct args. Will send a few refactor PRs on top of this one.
> [refactor] Simplify callback logic for torch & paddle args

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- requirements_test.txt
- tests/python/conftest.py
This reverts commit e081dec87d50977f9e2941bef8f42b41513de1ad.
Issue: #
> [ci] Revert "Adaptively laying off test workers on CUDA OOM (#6628)"

- python/taichi/_kernels.py
- python/taichi/lang/kernel_impl.py
- python/taichi/types/ndarray_type.py
- tests/python/test_aot.py
- tests/python/test_ast_refactor.py
- tests/python/test_function.py
- tests/python/test_matrix.py
- tests/python/test_mpm88.py
- tests/python/test_ndarray.py
Reverts taichi-dev/taichi#6620
> [ci] Revert "[Lang] [ci] Remove element shape and element dim in unit tests"

- taichi/rhi/vulkan/vulkan_device.cpp
> [gui] Tolerate swapchain image count

- .github/workflows/scripts/unix-build.sh
- .github/workflows/testing.yml
Issue: #6447 
Getting closer...
> [ci] Move macos10.15 job to build with LLVM 15

- taichi/util/statistics.cpp
- taichi/util/statistics.h
> [bug] Add a mutex to protect counters_map in Statistics

- python/taichi/_funcs.py
- tests/python/test_linalg.py
- tests/python/test_svd.py
> [lang] MatrixType refactor: Support svd(), polar_decompose()

- .github/workflows/scripts/aot-demo.sh
> [aot] Modify Unity CI to track master branch of Taichi-Unity

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
> [ci] Resolve GitHub Actions warnings

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_ast_refactor.py
- tests/python/test_grouped.py
- tests/python/test_ndrange.py
> [bug] MatrixType bug fix: Fix numerical error with grouped ndrange

- .github/workflows/scripts/unix-build.sh
Reverts taichi-dev/taichi#6658
> Revert "[ci] Install unzip in manylinux build"

- .github/workflows/release.yml
- ci/Dockerfile.manylinux2014.cpu
> [ci] Add unzip & sudo to manylinux2014 build image

- docs/lang/articles/contribution/dev_install.md
> [doc] Fix a format issue

- c_api/include/taichi/cpp/taichi.hpp
- c_api/include/taichi/taichi_core.h
- c_api/src/taichi_core_impl.cpp
- c_api/src/taichi_core_impl.h
- c_api/src/taichi_gfx_impl.cpp
- c_api/src/taichi_gfx_impl.h
- c_api/taichi.json
- c_api/tests/c_api_interface_test.cpp
- taichi/cache/gfx/cache_manager.cpp
- taichi/common/virtual_dir.cpp
- taichi/common/virtual_dir.h
- taichi/runtime/gfx/aot_module_loader_impl.cpp
- taichi/runtime/gfx/aot_module_loader_impl.h
- tests/test_config.json
This PR enables loading AOT modules from memory
> [aot] Load AOT module from memory

- python/taichi/examples/simulation/implicit_mass_spring.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/program/sparse_solver.cpp
- taichi/program/sparse_solver.h
- taichi/python/export_lang.cpp
- tests/python/test_sparse_linear_solver.py
- tests/python/test_sparse_matrix.py
This reverts commit bad76a05818c68e6f676aab61876d21e00496a6d.
Issue: #
> [lang] Revert "Add spmv and sparse linear solver using ndarray as vector (#6651)"

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
> [ci] Run release tests in PRs

- taichi/program/program.h
> [bug] Add lock to protect the CompileConfig map

- .github/workflows/scripts/unix-build.sh
Issue: #6447 
Cherrypicking  #6732 into v1.3.0 release branch
> [build] Cherrypicking #6732 into v1.3.0 release branch

- python/taichi/examples/algorithm/mciso_advanced.py
- python/taichi/examples/autodiff/diff_sph/diff_sph.py
- python/taichi/examples/features/sparse/taichi_sparse.py
- python/taichi/examples/ggui_examples/mass_spring_3d_ggui.py
- python/taichi/examples/ggui_examples/mpm128_ggui.py
- python/taichi/examples/ggui_examples/mpm3d_ggui.py
- python/taichi/examples/ggui_examples/stable_fluid_ggui.py
- python/taichi/examples/graph/mpm88_graph.py
- python/taichi/examples/graph/stable_fluid_graph.py
- python/taichi/examples/graph/texture_graph.py
- python/taichi/examples/rendering/sdf_renderer.py
- python/taichi/examples/simulation/euler.py
- python/taichi/examples/simulation/mpm128.py
- python/taichi/examples/simulation/mpm3d.py
- python/taichi/examples/simulation/mpm_lagrangian_forces.py
- python/taichi/examples/simulation/stable_fluid.py
> [misc] Fix warnings of taichi examples

- docs/lang/articles/basic/sparse.md
- python/taichi/_snode/fields_builder.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/snode.py
- tests/python/test_compare.py
- tests/python/test_debug.py
- tests/python/test_deprecation.py
- tests/python/test_dynamic_append_length.py
- tests/python/test_dynamic_attributes.py
- tests/python/test_gc.py
- tests/python/test_no_activate.py
> [Doc] [lang] Cherrypick commits related to dynamic SNode

- docs/lang/articles/basic/layout.md
- python/taichi/lang/misc.py
- taichi/ir/snode.cpp
- tests/python/test_deprecation.py
Cherrypicks #6755 and #6753 into v1.3.0 release branch.
> [Doc] [lang] Cherrypick commits related to packed mode

- docs/lang/articles/math/sparse_matrix.md
> [doc] Update sparse matrix document

- python/taichi/lang/_texture.py
- tests/python/test_texture.py
> [bug] MatrixType bug fix: Fix error with texture

- tests/python/test_ad_gdar_diffmpm.py
Issue: #5819
This PR fixes invalid syntax in the test.
> [bug] MatrixType bug fix: Fix test_ad_gdar_diffmpm

- python/taichi/examples/simulation/implicit_mass_spring.py
- python/taichi/examples/simulation/stable_fluid.py
> [example] Add cuda options for sparse matrix examples

- python/taichi/ad/_ad.py
Update docstring for grad replaced from `ti.grad_replaced` to `ti.ad.grad_replaced`.
> [doc] Update docstring for grad replaced

- .github/workflows/testing.yml
> [ci] Temporarily disable desktop headless tests

- taichi/program/program.cpp
Issue: #6190
This PR removes some redundant code per review comments from #6198.
> [refactor] Remove unnecessary checks in program

- .github/workflows/testing.yml
This reverts commit 2489169c01d465be1ba8a7bc066280f221df6b92.
Issue: #
> [ci] Revert "Temporarily disable desktop headless tests (#6811)"

- c_api/include/taichi/cpp/taichi.hpp
- c_api/include/taichi/taichi_core.h
- c_api/src/taichi_core_impl.cpp
- c_api/src/taichi_gfx_impl.cpp
- c_api/src/taichi_opengl_impl.cpp
- c_api/src/taichi_vulkan_impl.cpp
- c_api/taichi.json
- c_api/tests/c_api_interface_test.cpp
- taichi/cache/gfx/cache_manager.cpp
- taichi/rhi/device.cpp
- taichi/rhi/device.h
- taichi/rhi/device_capability.cpp
- taichi/rhi/device_capability.h
- taichi/rhi/dx/dx_device.cpp
- taichi/rhi/dx/dx_device.h
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
- taichi/rhi/vulkan/vulkan_device.cpp
- taichi/rhi/vulkan/vulkan_device.h
- taichi/rhi/vulkan/vulkan_device_creator.cpp
- taichi/runtime/program_impls/dx/dx_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
> [aot] C-API Device capability improvements

- taichi/ir/frontend_ir.cpp
> [bug] Matrix refactor bug fix: Fix restrictions on BinaryOp/TernaryOp operands' broadcasting

- python/taichi/examples/simulation/implicit_fem.py
The original implicit fem example is actually a projective dynamics simulation. The system matrix could be constructed and factorized before starting the simulation. In this PR, the system matrix is explicitly constructed and factorized. The linear system could be solved using a sparse solver on the CPU/GPU backend.
> [example] Solve implicit fem using sparsee solver

- taichi/program/compile_config.cpp
> [Lang] Enable real_matrix and real_matrix_scalarize by default

- .github/workflows/scripts/aot-demo.sh
The API update has been merged into aot-demo repo
> [misc] Revert back to master after #6843 merged

- python/taichi/_funcs.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/ast/ast_transformer_utils.py
- python/taichi/lang/expr.py
- python/taichi/lang/impl.py
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/ops.py
- taichi/analysis/offline_cache_util.cpp
- taichi/codegen/codegen_utils.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/python/export_lang.cpp
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/simplify.cpp
- taichi/transforms/type_check.cpp
- tests/cpp/ir/ir_type_promotion_test.cpp
- tests/python/test_literal.py
- tests/python/test_matrix.py
Issue: #5819
We no longer need the switch after #6801.
> [Lang] Remove the real_matrix switch

- .github/workflows/scripts/aot-demo.sh
Gather satellite repo URLs together to help reviewers check if a satellite repo PR checker PR has covered clones everywhere
> [aot] Gather satellite repo URLs

- python/taichi/examples/algorithm/marching_squares.py
This PR uses dynamic snode to store the detected edges and renders the result in a new style.
> [example] Update marching squares example

- docs/lang/articles/advanced/odop.md
> [doc] Update odop.md

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_if.py
> [lang] Fix issue of IfExpr with TensorTyped operands

- docs/lang/articles/debug/debugging.md
> [doc] Update debugging.md

- docs/lang/articles/basic/sparse.md
> [doc] Update sparse.md

- .github/workflows/scripts/ci_common/__init__.py
- .github/workflows/scripts/ci_common/dep.py
- .github/workflows/scripts/ci_common/escapes.py
- .github/workflows/scripts/ci_common/misc.py
- .github/workflows/scripts/ci_common/python.py
> [ci] Fix pre-commit errors

- .github/workflows/perf.yml
- .github/workflows/release.yml
> [ci] Fix forgotten build script paths

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
> [ci] Update release test branch, reduce running time

- docs/lang/articles/faqs/faq.md
> [doc] New FAQ added

- .github/workflows/perf.yml
- .github/workflows/release.yml
- .github/workflows/scripts/ci_common/dep.py
- .github/workflows/scripts/ci_common/python.py
- .github/workflows/scripts/ci_common/tinysh.py
- .github/workflows/scripts/common-utils.sh
- .github/workflows/scripts/sync-cache.py
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
> [ci] Auto setup miniforge3 env when build

- .github/workflows/scripts/build.py
- .github/workflows/scripts/ci_common/bootstrap.py
- .github/workflows/scripts/ci_common/python.py
- .github/workflows/scripts/ci_common/tinysh.py
> [ci] Build: auto install vulkan on Linux

- python/taichi/_lib/utils.py
> [misc] Keeping up with new python-wheel implementation

- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/rhi/opengl/opengl_api.cpp
- taichi/rhi/opengl/opengl_api.h
- taichi/rhi/opengl/opengl_device.cpp
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.h
Issue: #
Splitting this out of the GLES PR for easier review.
> [opengl] Reset opengl context when taichi program resets

- README.md
> [misc] Add repography activity stats

- taichi/ir/type.cpp
- taichi/ir/type.h
- taichi/ir/type_factory.cpp
- taichi/ir/type_factory.h
- taichi/python/export_lang.cpp
- taichi/runtime/llvm/llvm_context.cpp
- taichi/util/hash.h
> [ir] Add struct type to CHI-IR

- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
> [lang] Get the CHI-IR struct type in python

- python/taichi/lang/ast/ast_transformer.py
- taichi/program/callable.cpp
- taichi/program/callable.h
- taichi/python/export_lang.cpp
> [ir] Record the return types to a StructType

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
> [ci] Update taichi-release-tests branch (disable QuanTaichi GOL)

- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/kernel.cpp
> [misc] Remove unnecessary CompileConfig::lazy_compilation

- taichi/cache/metal/cache_manager.cpp
> [Error] Do not show warning when the offline cache path does not exist

- taichi/runtime/cuda/jit_cuda.cpp
> [cuda] Fix LLVM15 rsqrt perf regression

- taichi/rhi/amdgpu/amdgpu_caching_allocator.cpp
- taichi/runtime/llvm/llvm_runtime_executor.cpp
> [misc] Add macro to control amdgpu-related header file

- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
> [opengl] Enable more gles tests in CI

- .github/workflows/scripts/aot-demo.sh
- .github/workflows/testing.yml
> [build] Remove libexport_core.so dependency for Android App CI

- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
Reverts taichi-dev/taichi#7010
> Revert "[opengl] Enable more gles tests in CI"

- .pre-commit-config.yaml
- misc/baselines/bandwidth.cu
- taichi/analysis/gen_offline_cache_key.cpp
- taichi/common/interface.h
- taichi/common/json.cpp
- taichi/ir/expression.h
- taichi/ir/expression_ops.h
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/math/sifakis_svd.h
- taichi/program/field_info.h
- taichi/rhi/device.h
- taichi/rhi/dx/dx_device.h
- taichi/runtime/llvm/runtime_module/atomic.h
- taichi/runtime/llvm/runtime_module/runtime.cpp
- taichi/ui/utils/utils.h
- taichi/util/bit.h
> [ci] Update pre-commit app versions

- c_api/include/taichi/taichi_opengl.h
- c_api/src/taichi_opengl_impl.cpp
- c_api/src/taichi_vulkan_impl.cpp
- c_api/taichi.json
- taichi/rhi/opengl/opengl_api.cpp
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
This reverts commit a1485cd8fef92972a91c450b9f703f741c989c9b.
Issue: #
> [aot] Revert "C-API opengl runtime interop (#7014)"

- python/taichi/ui/imgui.py
- taichi/python/export_ggui.cpp
- taichi/ui/backends/vulkan/gui.cpp
- taichi/ui/backends/vulkan/gui.h
- taichi/ui/common/gui_base.h
Issue: #3013
Implementing colored texts:
```py
window = ti.ui.Window('Window', (768, 768),
vsync=True)
canvas = window.get_canvas()
gui = window.get_gui()
while window.running:
with gui.sub_window("Yo", 0.05, 0.05, 0.9, 0.2) as w:
w.text("haha", (1.0,0.2,0.3))
window.show()
```
> [GUI] Support colored texts

- .pre-commit-config.yaml
> [ci] Pin pre-commit python version to 3.10

- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/ir/expression_printer.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/type_check.cpp
> [ir] Let GetElementExpression&Statement support index list

- c_api/include/taichi/taichi_opengl.h
- c_api/src/taichi_opengl_impl.cpp
- c_api/src/taichi_vulkan_impl.cpp
- c_api/taichi.json
- taichi/rhi/opengl/opengl_api.cpp
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
Support exporting OpenGL runtime in C-API.
> [aot] C-API opengl runtime interop

- tests/cpp/transforms/eliminate_immutable_local_vars_test.cpp
> [Lang] Add irpass::eliminate_immutable_local_vars() test cases for TensorType

- taichi/codegen/cc/cc_program.cpp
- taichi/codegen/cc/cc_program.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/runtime/program_impls/dx/dx_program.cpp
- taichi/runtime/program_impls/dx/dx_program.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/program_impls/llvm/llvm_program.h
- taichi/runtime/program_impls/metal/metal_program.cpp
- taichi/runtime/program_impls/metal/metal_program.h
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.h
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.h
- tests/cpp/backends/dx11_device_test.cpp
> [refactor] Remove offloaded parameter of Program::compile()

- taichi/program/program.cpp
- taichi/program/program.h
- taichi/transforms/constant_fold.cpp
> [refactor] Remove dependencies on Program::current_ast_builder() in C++ side

- taichi/codegen/codegen.cpp
- taichi/codegen/codegen.h
- taichi/codegen/cpu/codegen_cpu.h
- taichi/codegen/cuda/codegen_cuda.h
- taichi/codegen/dx12/codegen_dx12.h
- taichi/codegen/wasm/codegen_wasm.h
- taichi/runtime/dx12/aot_module_builder_impl.cpp
- taichi/runtime/program_impls/llvm/llvm_program.cpp
- taichi/runtime/wasm/aot_module_builder_impl.cpp
> [refactor] Remove ir parameter of KernelCodeGen::KernelCodeGen(Kernel *kernel, IRNode *ir)

- setup.py
> [misc] Update python package metadata

- .github/workflows/testing.yml
> Cherry-pick #7078 into rc-v1.4.0

- python/taichi/_main.py
This PR updates the `ti gallery` UI. Must be merged after the gallery image is updated in the assets repo:
https://github.com/taichi-dev/taichi_assets/pull/4
> [example] Update gallery images

- taichi/ir/transforms.h
- taichi/transforms/compile_to_offloads.cpp
- taichi/transforms/scalarize.cpp
- tests/cpp/transforms/scalarize_test.cpp
> [refactor] Remove unnecessary parameter of irpass::scalarize

- taichi/codegen/codegen.cpp
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/runtime/program_impls/llvm/llvm_program.cpp
> [refactor] Remove unnecessary Kernel::arch

- python/taichi/examples/simulation/snow_phaseField.py
This PR removes the warning message of th example `snow_phaseField` caused by closing the GUI.
> [example] Remove gui warning message

- docs/lang/articles/type_system/type.md
- python/taichi/_main.py
- python/taichi/examples/simulation/snow_phaseField.py
- python/taichi/lang/_wrap_inspect.py
- python/taichi/lang/impl.py
- python/taichi/lang/matrix.py
- python/taichi/types/ndarray_type.py
- python/taichi/ui/canvas.py
- requirements_dev.txt
- setup.py
- taichi/transforms/scalarize.cpp
- tests/python/test_deprecation.py
- tests/python/test_matrix.py
- tests/python/test_matrix_slice.py
> [misc] Cherrypick commits into rc-v1.4.0

- taichi/cache/gfx/cache_manager.cpp
- taichi/cache/gfx/cache_manager.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_builder_impl.h
- taichi/runtime/gfx/runtime.cpp
- taichi/runtime/gfx/runtime.h
- taichi/runtime/program_impls/dx/dx_program.cpp
- taichi/runtime/program_impls/metal/metal_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
> [refactor] Remove dependencies on Program::this_thread_config() in gfx::run_codegen

- python/taichi/lang/_ndarray.py
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/python/export_lang.cpp
- taichi/runtime/gfx/runtime.cpp
- taichi/runtime/gfx/runtime.h
- taichi/runtime/program_impls/opengl/opengl_program.h
- taichi/runtime/program_impls/vulkan/vulkan_program.h
- tests/python/test_ndarray.py
Cherrypicking #7072 into rc-v1.4.0 branch
> [misc] Cherry-pick #7072 into rc-v1.4.0

- taichi/ui/backends/vulkan/renderables/scene_lines.cpp
> [gui] Fix scene line renderable

- taichi/cache/gfx/cache_manager.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/spirv/spirv_codegen.h
- taichi/program/compile_config.cpp
- taichi/rhi/arch.cpp
- taichi/rhi/arch.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/program_impls/dx/dx_program.cpp
> [refactor] Remove dependencies on Program::this_thread_config() in spirv::lower

- c_api/src/taichi_core_impl.cpp
- c_api/tests/c_api_aot_test.cpp
- python/taichi/aot/utils.py
- tests/cpp/aot/python_scripts/texture_aot_test.py
- tests/test_config.json
> [aot] Support texture arguments for AOT kernels

- python/taichi/lang/matrix.py
- taichi/ir/frontend_ir.cpp
> [lang] Migrate TensorType expansion in MatrixType/VectorType from Python code to Frontend IR

- python/taichi/lang/ast/ast_transformer.py
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/transforms/type_check.cpp
> [lang] Remove redundant TensorType expansion for function returns

- cpp_examples/aot_save.cpp
- tests/cpp/aot/dx12/aot_save_load_test.cpp
- tests/cpp/backends/dx11_device_test.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
> [refactor] Remove dependencies on Program::this_thread_config() in some tests

- setup.py
Issue: #
Adding these to the built python package. 
cc: @PENGUINLIONG however the built wheels are with LLVM on so we might need to write a separate CI job just to build a c_api.so with desired configuration for release?
> [mac] Add .dylib and .cmake to built wheel

- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
Issue: #
IIUC, the `Program::sync` is useless now.
> [misc] Remove useless Program::sync

- c_api/include/taichi/cpp/taichi.hpp
- c_api/tests/c_api_behavior_test.cpp
> [aot] C++ wrapper for memory slice and memory allocation with host access

- docs/lang/articles/math/math_module.md
This PR adds comments to complex arithmetics examples.
> [Doc] Update math_module.md

- .github/workflows/scripts/ci_common/dep.py
> [ci] Fix near cache urls (missing comma)

- taichi/util/hash.h
> [ir] Fix gcc cannot compile inline template specialization

- c_api/cmake/FindTaichi.cmake
> [aot] Find Taichi in python wheel

- MANIFEST.in
> [bug] Fix example circle-packing

- python/taichi/types/ndarray_type.py
- tests/python/test_function.py
> [bug] Fix check_matched() failure with Ndarray holding TensorType'd element

- taichi/runtime/cpu/jit_cpu.cpp
Issue: #
We sometimes hit `Assertion failed: (isInt<33>(Addend) && "Invalid page reloc value."), function encodeAddend, file RuntimeDyldMachOAArch64.h, line 210.` on m1 ci job and this PR tries to fix it.
Example failed ci jobs: https://github.com/taichi-dev/taichi/actions/runs/3936953922
> [mac] Use ObjectLinkingLayer instead of RTDyldObjectLinkingLayer for aarch64 mac

- c_api/include/taichi/taichi_opengl.h
- c_api/src/taichi_opengl_impl.cpp
- c_api/taichi.json
- misc/generate_c_api.py
- misc/generate_c_api_docs.py
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
Issue: #
Implemented texture and memory interop for OpenGL.
> [aot] More OpenGL interop in C-API

- docs/lang/articles/contribution/windows_debug.md
> [doc] Fix format issues of windows debugging

- cpp_examples/autograd.cpp
- cpp_examples/run_snode.cpp
- taichi/aot/graph_data.cpp
- taichi/ir/expr.cpp
- taichi/ir/expr.h
- taichi/ir/expression.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/program/function.cpp
- taichi/program/kernel.cpp
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/program/snode_rw_accessors_bank.cpp
- taichi/python/export_lang.cpp
- tests/cpp/ir/frontend_type_inference_test.cpp
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/transforms/alg_simp_test.cpp
- tests/cpp/transforms/simplify_test.cpp
Issue: #7002 
Removed multi-thread version `Program::this_thread_config()` (see https://github.com/taichi-dev/taichi/pull/7159#issue-1532269774)
> [refactor] Program::this_thread_config() -> Program::compile_config()

- .github/workflows/release.yml
> [ci] M1 buildbot release tag

- python/taichi/examples/rendering/oit_renderer.py
Issue: #
Update code according to the upcoming article
> [example] Reorganize example oit_renderer

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_if.py
> [Error] Raise error when using deprecated ifexp on matrices

- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
> [opengl] RW image binding & FP16 support

- taichi/codegen/codegen.cpp
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/program/kernel.cpp
- taichi/program/kernel.h
> [refactor] Remove Kernel::offload_to_executable

- taichi/rhi/device.cpp
- taichi/rhi/device.h
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/vulkan/vulkan_device.cpp
> [rhi] Add create_image_unique stub & misc RHI bug fixes

- python/taichi/ui/utils.py
- taichi/program/field_info.h
- taichi/program/ndarray.cpp
- taichi/program/ndarray.h
- taichi/python/export_lang.cpp
> [misc] Export DeviceAllocation into Python & support devalloc in field_info

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_deprecation.py
> [Error] Remove deprecations in ASTTransformer in 1.6.0

- docs/design/llvm_sparse_runtime.md
This PR fixes typos and broken links in the `design/llvm` article.
> [Doc] Update llvm_sparse_runtime.md

- python/taichi/ui/ui.py
- python/taichi/ui/window.py
- tests/python/test_deprecation.py
> [Error] Remove deprecations in ti.ui in 1.6.0

- python/taichi/lang/ast/ast_transformer.py
- tests/python/test_if.py
> [Error] Allow IfExp on matrices when the condition is scalar

- c_api/include/taichi/taichi_unity.h
- c_api/taichi.json
- misc/generate_c_api.py
- misc/generate_c_api_docs.py
- misc/generate_unity_language_binding.py
- misc/taichi_json.py
> [aot] Added third-party render thread task injection for Unity

- .pre-commit-config.yaml
> [ci] Update pre-commit repos version

- taichi/transforms/auto_diff.cpp
- tests/python/test_ad_basics.py
Issue: #
Support rsqrt operator in autodiff
> [autodiff] Support rsqrt operator

- misc/save_new_version.py
> [ci] Tolerate duplicates when registering version

- .github/workflows/scripts/aot-demo.sh
- python/taichi/types/texture_type.py
- tests/python/test_deprecation.py
> [misc] Remove deprecated kwarg in rw_texture type annotations

- .github/workflows/scripts/common-utils.sh
> [ci] Adapt CI to the new Android-phone runner's behavior

- python/taichi/lang/struct.py
- tests/python/test_copy_from.py
> [Bug] Fix copy_from() of StructField

- taichi/analysis/gen_offline_cache_key.cpp
- taichi/analysis/offline_cache_util.cpp
- taichi/analysis/offline_cache_util.h
- taichi/ir/snode.cpp
- taichi/ir/snode.h
- taichi/program/function.cpp
Issue: #7286
* #7286: Part of #7002
> [refactor] Remove dependencies on Callable::program in lang::get_hashed_offline_cache_key

- .github/workflows/scripts/aot-demo.sh
- c_api/cmake/FindTaichi.cmake
- cmake/TaichiCAPI.cmake
- cmake/TaichiConfig.cmake.in
- taichi/rhi/vulkan/vulkan_device.cpp
Issue: https://github.com/taichi-dev/taichi-aot-demo/pull/112
> [aot] Fixed external project inclusion

- taichi/rhi/cpu/cpu_device.cpp
- taichi/rhi/cpu/cpu_device.h
- taichi/rhi/cuda/cuda_device.cpp
- taichi/rhi/cuda/cuda_device.h
- taichi/rhi/device.cpp
- taichi/rhi/device.h
- taichi/rhi/dx/dx_device.cpp
- taichi/rhi/dx/dx_device.h
- taichi/rhi/opengl/opengl_api.h
- taichi/rhi/opengl/opengl_device.cpp
- taichi/rhi/opengl/opengl_device.h
- taichi/rhi/vulkan/vulkan_device.cpp
- taichi/runtime/gfx/runtime.cpp
Issue: #
Add device upload and readback functions, and use backend-specific fast path.
> [rhi] Device upload readback functions

- cmake/TaichiCXXFlags.cmake
- cmake/utils.cmake
Update performance flags & enable LTO on MSVC
> [misc] Update MSVC flags

- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/runtime/llvm/llvm_context.h
Issue: #7311
Prepare to remove `TaichiLLLVMContext::jit`
> [refactor] Remove TaichiLLVMContext::lookup_function_pointer()

- .github/workflows/ghstack_land.yml
- .github/workflows/issue_comment.yml
> [ci] ChatOps: ghstack land

- README.md
> [doc] Replace slack with discord

- python/taichi/types/quant.py
Issue = close #7316
* #7310
* #7262
* #7261
* #7260
* __->__ #7317
> [type] Let the compute type of quant uint be unsigned int

- .github/workflows/ghstack_land.yml
> [ci] Checkout with privileged token when landing ghstack PRs

- c_api/src/taichi_llvm_impl.cpp
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/runtime/llvm/llvm_context.cpp
- taichi/runtime/llvm/llvm_context.h
- taichi/runtime/llvm/llvm_runtime_executor.cpp
- taichi/runtime/llvm/llvm_runtime_executor.h
- tests/cpp/codegen/refine_coordinates_test.cpp
- tests/cpp/llvm/llvm_offline_cache_test.cpp
> [refactor] Move TaichiLLVMContext::runtime_jit_module and TaichiLLVMContext::create_jit_module() to LlvmRuntimeExecutor

- python/taichi/lang/simt/subgroup.py
- taichi/codegen/spirv/spirv_codegen.cpp
Support subgroup broadcast, shuffle, and relative shuffle
> [vulkan] More subgroup operations

- .github/workflows/scripts/unix-test-docs.sh
> [ci] Reduce doc test concurrency

- docs/lang/articles/get-started/hello_world.md
> [Doc] Update hello_world.md

- .github/workflows/scripts/common-utils.sh
- .github/workflows/scripts/unix_aot_compat_test.sh
- .github/workflows/scripts/unix_test.sh
- .github/workflows/testing.yml
Issue: #
Splitted Android and AOT tests to dedicated jobs.
> [aot] AOT CI refactorization

- docs/lang/articles/type_system/type.md
This PR updates the doc type.md
> [Doc] Update type.md

- taichi/codegen/amdgpu/codegen_amdgpu.cpp
- taichi/rhi/amdgpu/amdgpu_context.h
- taichi/runtime/llvm/llvm_runtime_executor.cpp
1. remove redundant device stream_synchronize which will damage performance seriously.
> [amdgpu] Update device memory free

- .github/workflows/scripts/unix-test-docs.sh
> [ci] Add doc snippet CI requirements

- .github/workflows/testing.yml
- c_api/include/taichi/cpp/taichi.hpp
- c_api/include/taichi/taichi.h
- c_api/include/taichi/taichi_core.h
- c_api/include/taichi/taichi_cpu.h
- c_api/include/taichi/taichi_cuda.h
- c_api/include/taichi/taichi_opengl.h
- c_api/include/taichi/taichi_unity.h
- c_api/include/taichi/taichi_vulkan.h
- c_api/src/taichi_core_impl.cpp
- misc/generate_c_api.py
Issue: #
Also notice this PR reveals `ti_copy_image_device_to_device` which was incorrectly named `ti_copy_texture_device_to_device`. Should add a test for it before the release of this feature.
> [aot] Improve Taichi C++ wrapper implementation

- docs/lang/articles/kernels/kernel_function.md
This PR polishes the kernel function doc
> [Doc] Update kernel_function.md

- docs/lang/articles/performance_tuning/profiler.md
> [Doc] Update profiler.md

- python/taichi/lang/matrix.py
- tests/python/test_numpy.py
Issue: fix https://github.com/taichi-dev/taichi/issues/7353
> [bug] Fix matrix initialization error with numpy.floating data

- taichi/codegen/compiled_kernel_data.cpp
- taichi/codegen/compiled_kernel_data.h
- tests/cpp/codegen/compiled_kernel_data_test.cpp
> [refactor] Introduce lang::CompiledKernelData

- docs/lang/articles/advanced/data_oriented_class.md
Issue: fix #6729
The example code of memory recycling is wrong, this PR fixes this.
> [Doc] Update data_oriented_class.md

- taichi/rhi/metal/metal_device.h
- taichi/rhi/metal/metal_device.mm
> [aot] Support texture in Metal

- c_api/src/taichi_vulkan_impl.cpp
- c_api/tests/c_api_numerical_test.cpp
- taichi/rhi/vulkan/vulkan_device_creator.cpp
> [bug] Fix validation erros due to inactive VK_KHR_16bit_storage

- taichi/runtime/program_impls/llvm/llvm_program.h
> [misc] Remove useless semicolon in llvm_program.h

- CMakeLists.txt
- cmake/TaichiCAPI.cmake
- cmake/TaichiCXXFlags.cmake
- cmake/TaichiCore.cmake
- taichi/cache/gfx/cache_manager.cpp
- taichi/codegen/cc/cc_utils.h
- taichi/runtime/gfx/runtime.cpp
- taichi/runtime/gfx/runtime.h
- taichi/runtime/program_impls/dx/dx_program.cpp
- taichi/util/io.h
- taichi/util/lang_util.cpp
- tests/cpp/aot/dx12/aot_save_load_test.cpp
- tests/cpp/llvm/llvm_offline_cache_test.cpp
Issue: #
It seems iOS applications can only consume archives built from XCode.
> [aot] Fix blockers in static library build with XCode

- c_api/include/taichi/taichi.h
- c_api/include/taichi/taichi_metal.h
- c_api/src/taichi_core_impl.cpp
- c_api/src/taichi_core_impl.h
- c_api/src/taichi_metal_impl.h
- c_api/src/taichi_metal_impl.mm
- c_api/taichi.json
- cmake/TaichiCAPI.cmake
Issue: #
Added interop APIs for Metal. Depends on https://github.com/taichi-dev/taichi/pull/7363.
> [aot] Metal interop APIs

- tests/cpp/transforms/alg_simp_test.cpp
- tests/cpp/transforms/simplify_test.cpp
> [refactor] Remove dependencies on Callable::program in cpp tests

- taichi/rhi/vulkan/vulkan_device.cpp
- taichi/ui/backends/vulkan/window.cpp
- taichi/ui/common/input_handler.h
- taichi/ui/common/window_base.cpp
> [gui] Fix ggui & vulkan swapchain sizes on HiDPI displays

- taichi/rhi/arch.cpp
- taichi/util/offline_cache.cpp
> [bug] Fix arch_uses_spirv

- .github/workflows/testing.yml
> [ci] Add 'Needed single revision' workaround to all tasks

- .github/workflows/perf.yml
> [ci] Lock GPU frequency in perf benchmarking

- docs/lang/articles/math/math_module.md
> [Doc] Update math_module

- python/taichi/lang/enums.py
- taichi/program/program.cpp
Issue: #
Avoid case specific processing to devcaps
> [aot] Simplify device capability assignment

- python/taichi/lang/simt/block.py
- taichi/runtime/llvm/llvm_context.cpp
- tests/python/test_shared_array.py
Issue: #https://github.com/taichi-dev/taichi/issues/6434
> [Amdgpu] Enable shared array on amdgpu backend

- python/taichi/examples/graph/texture_graph.py
- python/taichi/graph/_graph.py
- tests/python/test_deprecation.py
Issue: #
Make it clean.
Note that it's intentionally not modifying the tests. Let's ensure the new interface doesn't lead to any breakage over the existing test cases.
> [aot] Reorganize graph argument creation process

- c_api/docs/taichi/taichi_core.h.md
- c_api/include/taichi/taichi_core.h
- docs/lang/articles/c-api/taichi_core.md
- docs/lang/articles/deployment/tutorial.md
- taichi/aot/module_builder.h
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_loader_impl.cpp
Issue: #
Removed TCB in GfxRuntime.
> [aot] Use graphs.json instead of TCB

- .github/workflows/perf.yml
> [ci] Adjust perfmon GPU freq

- taichi/util/offline_cache.cpp
- taichi/util/offline_cache.h
Issue: #7002 
Support cleaning `.tic` files.
> [bug] Fix offline_cache::clean_offline_cache_files (ti cache clean)

- taichi/transforms/auto_diff.cpp
> [autodiff] Handle return statement

- .github/workflows/scripts/unix_test.sh
- tests/cpp/conftest.py
> [ci] Report failure (not throwing exception) when C++ tests fail

- python/taichi/aot/utils.py
- python/taichi/lang/_texture.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- python/taichi/types/texture_type.py
- taichi/analysis/gen_offline_cache_key.cpp
- taichi/aot/module_data.h
- taichi/codegen/spirv/kernel_utils.cpp
- taichi/codegen/spirv/kernel_utils.h
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/ir/statements.h
- taichi/program/callable.cpp
- taichi/program/callable.h
- taichi/program/program.cpp
- taichi/program/program.h
- taichi/python/export_lang.cpp
- taichi/runtime/gfx/aot_module_builder_impl.cpp
- tests/python/test_texture.py
> [aot] Properly handle texture attributes

- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
> [ci] Lower C++ tests concurrency

- c_api/tools/generate_aot_module_cpp_header.py
- python/taichi/aot/__init__.py
- python/taichi/aot/conventions/__init__.py
- python/taichi/aot/conventions/gfxruntime140/__init__.py
- python/taichi/aot/conventions/gfxruntime140/dr.py
- python/taichi/aot/conventions/gfxruntime140/sr.py
- python/taichi/aot/utils.py
Issue: #
Ser/de script for GfxRuntime140 module metadata. Also a module header generator.
> [aot] AOT module convention GfxRuntime140

- python/taichi/_main.py
- python/taichi/_ti_module/__init__.py
- python/taichi/_ti_module/cppgen.py
Issue: #
Fixed module header generator.
> [aot] Fixed header generator

- python/taichi/_kernels.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_texture.py
> [lang] Fixed texture assertions

- python/taichi/lang/struct.py
- tests/python/test_deprecation.py
Issue: #7447
This PR corresponds to step 1 of #7447.
> [Lang] Deprecate arithmetic operations and fill() on ti.Struct

- docs/lang/articles/basic/ndarray.md
> [doc] Fix typo in ndarray.md

- taichi/transforms/frontend_type_check.cpp
- tests/python/test_type_check.py
> [Lang] Type check assignments between tensors

- .github/workflows/ghstack_land.yml
- .github/workflows/scripts/ghstack-perm-check.py
> [ci] Status check of ghstack CI bot

- .github/workflows/testing.yml
> [ci] Switch Android bots lock redis to bot-master

- .github/workflows/ghstack_land.yml
- .github/workflows/scripts/ghstack-perm-check.py
> [ci] Second attempt at permission check for ghstack landing

- .github/workflows/scripts/build.py
> [ci] Fix nightly version number issue

- taichi/rhi/metal/metal_device.h
- taichi/rhi/metal/metal_device.mm
Issue: #
Identified two sources of memory leak by profiling. No other leakage found atm.
> [aot] Fixed memory leak in metal backend

- .github/workflows/scripts/build.py
> [ci] Fix nightly version number, 2nd try

- CMakeLists.txt
> [aot] Build Runtime C-API by default

- python/taichi/types/compound_types.py
> [Doc] Fix typo in API doc

- docs/lang/articles/advanced/data_oriented_class.md
> [Doc] Fix typos and improve example code in data_oriented_class.md

- python/taichi/types/compound_types.py
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/transforms/demote_atomics.cpp
- tests/python/test_shared_array.py
> [ir] Except shared array from demote atomics pass.

- taichi/compilation_manager/kernel_compilation_manager.cpp
- taichi/compilation_manager/kernel_compilation_manager.h
- tests/python/test_offline_cache.py
> [misc] Implement KernelCompialtionManager::clean_offline_cache

- docs/lang/articles/visualization/ggui.md
> [Doc] Update GGUI docs with correct API

- c_api/src/taichi_metal_impl.h
- c_api/src/taichi_metal_impl.mm
- c_api/tests/c_api_aot_test.cpp
- c_api/tests/c_api_cgraph_test.cpp
- c_api/tests/c_api_interface_test.cpp
- c_api/tests/mpm88_test.cpp
- c_api/tests/sph.cpp
- taichi/rhi/metal/metal_device.h
- taichi/rhi/metal/metal_device.mm
- tests/cpp/aot/python_scripts/aot_module_test_.py
- tests/cpp/aot/python_scripts/dense_field_aot_test_.py
- tests/cpp/aot/python_scripts/graph_aot_test_.py
- tests/cpp/aot/python_scripts/kernel_aot_test1.py
- tests/cpp/aot/python_scripts/kernel_aot_test2.py
- tests/cpp/aot/python_scripts/mpm88_graph_aot.py
- tests/cpp/aot/python_scripts/numerical_aot_test_.py
- tests/cpp/aot/python_scripts/shared_array_aot_test_.py
- tests/cpp/aot/python_scripts/sph_aot.py
- tests/cpp/aot/python_scripts/tcm_test_.py
- tests/cpp/aot/python_scripts/texture_aot_test_.py
- tests/cpp/cpptests.yaml
> [aot] Enable Metal AOT test

- cmake/TaichiTests.cmake
> [bug] Fix symbol conflicts with taichi_cpp_tests

- python/taichi/__init__.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_api.py
> [Lang] Keep ti.pyfunc

- python/taichi/linalg/sparse_matrix.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/python/export_lang.cpp
> [Lang] Support writing sparse matrix as matrix market file

- python/taichi/aot/conventions/gfxruntime140/README.md
Issue: #
This PR added detailed documentation about the GfxRuntime140 convention.
> [aot] GfxRuntime140 convention docs

- taichi/ir/frontend_ir.h
> [bug] Implement the missing clone function for FrontendFuncCallStmt

- .github/workflows/scripts/aot-demo.sh
> [aot] Recover AOT CI branch names

- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_return.py
> [bug] Fix returning struct containing vec3

- docs/cover-in-ci.lst
- docs/lang/articles/kernels/kernel_function.md
- python/taichi/lang/kernel_impl.py
- python/taichi/lang/matrix.py
- python/taichi/lang/struct.py
- tests/python/test_return.py
Includes the change set of #7552. Can't use ghstack because I need the doc preview.
See https://github.com/taichi-dev/taichi/pull/7556/commits/de6f0a8b5dc3aa345880a57241703e0ff5893cbe for the real change set of this PR.
Issue: #7555
> [Doc] Add doc about returning struct

- taichi/rhi/vulkan/vulkan_device_creator.cpp
> [aot] Enable Vulkan 8bit storage

- taichi/ir/ir_builder.cpp
- taichi/ir/ir_builder.h
- taichi/transforms/constant_fold.cpp
- tests/cpp/transforms/constant_fold_test.cpp
Issue: #6834 
Note this is only tested on CPU backend and it's mainly to test coverage.
> [test] Add cpp tests for constant folding pass

- .gitignore
- scripts/archive-minimal-static.py
- scripts/build-taichi-android.sh
- scripts/build-taichi-ios.sh
> [aot] Mobile platform AOT build scripts

- python/taichi/math/_complex.py
fixes the error in the docstring of `cexp`.
> [Doc] Fix the cexp docstring

- taichi/ir/frontend_ir.cpp
- tests/python/test_unary_ops.py
> [bug] Type check for bit_not op with real type inputs

- taichi/transforms/constant_fold.cpp
- tests/cpp/transforms/half2_vectorization_test.cpp
Note this PR might cause some precision differences since we used to do constant folding on device while it's now on the host. 
Issue: #
> [opt] Constant folding for unary ops on host

- taichi/runtime/llvm/llvm_context_pass.h
> [lang] Fix issue with llvm opaque pointer

- cmake/TaichiCAPI.cmake
Fix absolute path in generated TaichiTargets.cmake
> [aot] Fix absolute path in generated TaichiTargets.cmake

- ci/Dockerfile.ubuntu.20.04.amdgpu
> [misc] Update docker filer

- python/taichi/linalg/sparse_matrix.py
- taichi/program/sparse_matrix.cpp
- taichi/program/sparse_matrix.h
- taichi/python/export_lang.cpp
> [bug] Improve ndarray creation to fix segmentation fault

- taichi/ir/frontend_ir.cpp
- tests/python/test_type_check.py
- tests/python/test_unary_ops.py
> [bug] Type check for logical not op with real type inputs

- taichi/codegen/amdgpu/codegen_amdgpu.cpp
- taichi/codegen/amdgpu/codegen_amdgpu.h
- taichi/codegen/codegen.cpp
- taichi/codegen/codegen.h
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cpu/codegen_cpu.h
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/codegen/cuda/codegen_cuda.h
- taichi/codegen/dx12/codegen_dx12.cpp
- taichi/codegen/dx12/codegen_dx12.h
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/codegen/wasm/codegen_wasm.h
- taichi/ir/transforms.h
- taichi/program/kernel.h
- taichi/transforms/ast_to_ir.cpp
* #7587
* #7586
* #7585
* #7584
* #7583
* __->__ #7582
* #7581
* #7580
> [refactor] Fix KernelCodeGen::kernel from Kernel * to const Kernel *

- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/codegen_llvm.h
> [bug] Fix compilation error

- python/taichi/_ti_module/cppgen.py
Issue: #
Fix it for now. Will be in CI when I figure out how to put them in CI scripts properly..
> [aot] Fixed generator for compute graph

- python/taichi/lang/kernel_impl.py
Before this PR, if the number of arguments exceeds the maximum number of arguments, it still sets the argument to the array beyond the index. 
* #7622
* #7612
* __->__ #7623
* #7611
* #7610
* #7608
* #7576
> [bug] Fix setting arguments exceeding the max arg num

- taichi/codegen/amdgpu/codegen_amdgpu.cpp
- taichi/codegen/cpu/codegen_cpu.cpp
- taichi/codegen/cuda/codegen_cuda.cpp
- taichi/program/context.h
- taichi/program/launch_context_builder.cpp
- taichi/program/launch_context_builder.h
- taichi/runtime/gfx/runtime.cpp
* #7622
* __->__ #7612
* #7623
* #7611
* #7610
* #7608
* #7576
> [refactor] Migrate members from RuntimeContext to LaunchContextBuilder

- taichi/program/launch_context_builder.cpp
- taichi/program/program.h
- taichi/program/program_impl.h
- taichi/runtime/program_impls/llvm/llvm_program.h
- taichi/util/bit.h
* __->__ #7622
* #7612
* #7623
* #7611
* #7610
* #7608
* #7576
> [refactor] Use f16 function from external lib

- .github/workflows/perf.yml
> [build] Switch to use docker with Android-SDK for performance bot

- docs/lang/articles/contribution/contributor_guide.md
> [doc] Add documentation on using ghstack

- .github/workflows/perf.yml
- .github/workflows/scripts/unix-perf-mon.sh
> [ci] Fix perf mon break

- .github/workflows/perf.yml
> [ci] Update perf mon image

- .github/workflows/release.yml
- .github/workflows/testing.yml
- setup.py
> [ci] Support Python 3.11

- docs/conftest.py
- docs/lang/articles/visualization/gui_system.md
> [doc] Fix gui_system.md tests

- .github/workflows/scripts/common-utils.sh
> [ci] Fix scipy install

- tests/cpp/transforms/constant_fold_test.cpp
> [test] Update C++ constant fold tests to test operator one by one

- taichi/transforms/constant_fold.cpp
> [opt] Move binary jit evaluator to host

- taichi/ir/transforms.h
- taichi/transforms/constant_fold.cpp
- taichi/transforms/simplify.cpp
- tests/cpp/transforms/alg_simp_test.cpp
- tests/cpp/transforms/binary_op_simplify_test.cpp
- tests/cpp/transforms/constant_fold_test.cpp
- tests/cpp/transforms/simplify_test.cpp
> [opt] Cleanup unncessary options in constant fold pass

- tests/python/test_offline_cache.py
> [misc] Simplify test_offline_cache.py

- taichi/program/program.h
> [misc] Remove unused Program::jit_evaluator_cache and Program::jit_evaluator_cache_mut

- taichi/codegen/cc/cc_program.cpp
- taichi/codegen/codegen.cpp
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/llvm/kernel_compiler.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/codegen/wasm/codegen_wasm.cpp
- taichi/compilation_manager/kernel_compilation_manager.cpp
- taichi/program/compile_config.cpp
- taichi/program/compile_config.h
- taichi/program/kernel.cpp
- taichi/program/kernel.h
- taichi/python/export_lang.cpp
- taichi/transforms/ast_to_ir.cpp
- taichi/transforms/compile_to_offloads.cpp
- tests/python/test_runtime.py
> [misc] Remove unused Kernel::is_evaluator

- README.md
This PR adds "AOT" and "Nerf" to the demos section.
> [Doc] Update readme

- .github/workflows/issue_comment.yml
- .github/workflows/perf.yml
- .github/workflows/release.yml
- .github/workflows/scripts/post-benchmark-to-github-pr.py
- .github/workflows/scripts/unix-perf-mon.sh
> [ci] Revive /benchmark

- misc/Test-TaichiAotWorkflow.ps1
- python/taichi/_ti_module/cppgen.py
- python/taichi/_ti_module/module.py
- python/taichi/aot/__init__.py
- python/taichi/aot/_export.py
- python/taichi/types/ndarray_type.py
Issue: #
Introduce the `--bin2c` flag to embed the entire TCM in the generated header by cppgen.
> [aot] Implement bin2c in AOT cppgen

- .github/workflows/release.yml
- .github/workflows/scripts/common-utils.ps1
- .github/workflows/scripts/common-utils.sh
- .github/workflows/testing.yml
> [ci] Git caching proxy in CI

- taichi/program/program.h
> [misc] Remove useless JITEvaluatorId

- python/taichi/ui/camera.py
- python/taichi/ui/utils.py
1. scale movement distance based on frame time
2. support multiple keys pressed at the same time
3. fix conversion between Euler angles and front vector
> [bug] Fix camera controls

- .github/workflows/scripts/unix_test.sh
> [ci] [test] Enable cc test on CI

- python/taichi/_snode/snode_tree.py
- python/taichi/lang/impl.py
- taichi/ir/snode.h
- taichi/program/program.cpp
- taichi/program/snode_rw_accessors_bank.h
- taichi/runtime/program_impls/llvm/llvm_program.h
- tests/python/test_classfunc.py
Issue: [forum issue 3994](https://forum.taichi-lang.cn/t/topic/3994/15)
> [bug] Invalid Field cache, RWAccessors cache, and Kernel cache upon SNodeTree destruction

- docs/lang/articles/performance_tuning/performance.md
> [Doc] Update performance.md

- .github/workflows/release.yml
- .github/workflows/scripts/common-utils.ps1
- .github/workflows/testing.yml
> [ci] Fix git cache quirks

- tests/python/test_offline_cache.py
> [test] Enable test offline cache on amdgpu and dx11

- taichi/system/memory_pool.cpp
Issue: #
It's a bit noisy for now :P
> [misc] Remove TI_WARN for cuda in memory_pool.cpp

- taichi/runtime/gfx/aot_module_builder_impl.cpp
- taichi/runtime/gfx/aot_module_builder_impl.h
- taichi/runtime/program_impls/dx/dx_program.cpp
- taichi/runtime/program_impls/metal/metal_program.cpp
- taichi/runtime/program_impls/opengl/opengl_program.cpp
- taichi/runtime/program_impls/vulkan/vulkan_program.cpp
Issue: #7002, https://github.com/taichi-dev/taichi/pull/6520#issue-1435652209
> [refactor] Let KernelCompilationManager manage kernel compilation in gfx::AotModuleBuilderImpl

- python/taichi/math/_complex.py
- python/taichi/math/mathimpl.py
This PR fixes circular import bugs in the `math` module
> [Lang] Fix math module circular import bugs

- .github/workflows/testing.yml
- docs/conftest.py
- docs/cover-in-ci.lst
Issue: #
- Cover newly modified documents in CI
- Treat `DeprecationWarning` as error, highlight KnownError warnings
> [ci] [doc] Tighten up document testing

- python/taichi/lang/_ndrange.py
This PR fixes the pylance warning by `ndrange`
> [Lang] Fix pylance warning

- .github/workflows/scripts/ti_build/bootstrap.py
> [ci] Fix build.py ensurepip

- .github/workflows/release.yml
- .github/workflows/scripts/ti_build/vulkan.py
- Move `TAICHI_CMAKE_ARGS` env in release.yml to task scope (testing needs it too)
- Specify `VK_LAYER_PATH` on Windows
> [ci] Fix release build failure

- docs/cover-in-ci.lst
- docs/lang/articles/kernels/kernel_sync.md
This  PR adds a new documentation on the sync between taichi and python scope
> [Doc] Add kernel sync doc

- .github/workflows/scripts/aot-demo.sh
- .github/workflows/scripts/ti_build/compiler.py
- .github/workflows/scripts/ti_build/entry.py
- .github/workflows/scripts/ti_build/misc.py
- .github/workflows/scripts/ti_build/ospkg.py
- .github/workflows/scripts/ti_build/tinysh.py
- .github/workflows/scripts/unix-perf-mon.sh
- .github/workflows/scripts/unix-test-docs.sh
- .github/workflows/scripts/unix_aot_compat_test.sh
- .github/workflows/scripts/unix_test.sh
- .github/workflows/scripts/win_test.ps1
- Find clang in Linux & macOS
- Installing required OS level packages on Ubuntu
> [ci] Polishing build.py, wave 3

- tests/run_tests.py
https://github.com/taichi-dev/taichi/pull/7616
> [bug] Fix rerun tests with offline cache

- .github/workflows/scripts/ti_build/entry.py
- .github/workflows/scripts/ti_build/python.py
- .github/workflows/scripts/ti_build/sccache.py
- docs/lang/articles/contribution/dev_install.md
- Update mambaforge && sccache
- Option to use developer managed Python environment
- Update docs about the Python thing, and behaviors considered intrusive
> [ci] Polishing build.py, wave 4

- python/taichi/lang/any_array.py
- taichi/analysis/alias_analysis.cpp
- taichi/analysis/same_statements.cpp
- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/ir_builder.cpp
- taichi/ir/statements.h
- taichi/python/export_lang.cpp
- taichi/transforms/ir_printer.cpp
- taichi/transforms/scalarize.cpp
- tests/cpp/analysis/alias_analysis_test.cpp
- tests/cpp/transforms/half2_vectorization_test.cpp
- tests/cpp/transforms/scalarize_test.cpp
> [refactor] Get rid of unused is_grad in ArgLoadStmt

- taichi/runtime/cuda/kernel_launcher.cpp
- taichi/runtime/cuda/kernel_launcher.h
> [refactor] Improve CUDA kernel launch logic for external arrays and ndarrays

- taichi/runtime/amdgpu/jit_amdgpu.cpp
- taichi/runtime/cuda/jit_cuda.cpp
- taichi/runtime/llvm/llvm_context.cpp
- taichi/runtime/llvm/llvm_context.h
- taichi/runtime/llvm/llvm_runtime_executor.cpp
- taichi/runtime/llvm/llvm_runtime_executor.h
Issue: close #7311 
* Remove dependency on `JITSession::get_data_layout()` in `TaichiLLVMContext::get_data_layout()`
* `TaichiLLVMContext::jit` -> `LlvmRuntimeExecutor::jit_session_`
> [refactor] Replace TaichiLLVMContext::jit with LlvmRuntimeExecutor::jit_session_

- python/taichi/lang/_ndarray.py
- taichi/program/ndarray.cpp
- tests/python/test_ndarray.py
> [lang] Support 0 dim ndarray read & write in python scope

- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/spirv/spirv_codegen.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/type.h
* #7889
* #7888
* __->__ #7887
* #7878
> [refactor] Rename get_num_elements in StructType to get_flattened_num_elements

- .github/workflows/scripts/ti_build/bootstrap.py
- .github/workflows/scripts/ti_build/compiler.py
- .github/workflows/scripts/ti_build/dep.py
Issue: #
This pull request improves the bootstrap process for Windows users and developers by checking and installing pip more robustly.
> [ci] Build.py quirks fix

- python/taichi/lang/struct.py
- tests/python/test_struct.py
Issue: fixes #7908 
Added the methods in the string representation of the class as well.
> [Lang] [bug] Let nested data classes have methods

- python/taichi/_kernels.py
- python/taichi/lang/_ndarray.py
- python/taichi/lang/matrix.py
- tests/python/test_ndarray.py
Issue: https://github.com/taichi-dev/taichi/issues/7844
> [Lang] Fix Ndarray fill with Matrix/Vector typed values

- .github/workflows/scripts/ti_build/bootstrap.py
Issue: #
Try (again) using ensurepip to bootstrap, if possible
> [ci] More robust build.py bootstrapping

- python/taichi/math/mathimpl.py
This PR fixes the wrong description in the docstring of the `mix` function.
> [Doc] Fix docstring of mix function

- misc/make_changelog.py
> [misc] Fix changelog commit extract code

- .github/workflows/scripts/ti_build/alter.py
> [ci] Build.py: Source generated env in new spawned shell

- docs/lang/articles/faqs/faq.md
> [Doc] Fix a bug in faq.md

- misc/make_changelog.py
* #7990
* #7989
* #7988
* #7987
* #7986
* #7985
* #7984
* __->__ #7983
> [misc] Do not print CHANGELOG when specified --save (make_changelog.py)

- .github/workflows/scripts/ti_build/entry.py
- .github/workflows/scripts/ti_build/tinysh.py
* #7990
* #7989
* #7988
* #7987
* #7986
* __->__ #7985
* #7984
* #7983
> [ci] Build.py: Add nice when compiling

- .github/workflows/scripts/ti_build/cmake.py
- .github/workflows/scripts/ti_build/entry.py
- CMakeLists.txt
- cmake/TaichiCore.cmake
* #7990
* #7989
* #7988
* #7987
* __->__ #7986
* #7985
* #7984
* #7983
> [ci] Tag wheel with TI_WITH_xxx tags

- .github/workflows/scripts/ti_build/compiler.py
- .github/workflows/scripts/ti_build/tinysh.py
- taichi/rhi/CMakeLists.txt
* #7990
* #7989
* __->__ #7988
* #7987
* #7986
* #7985
* #7984
* #7983
> [build] Use Ninja and MSVC to build on Windows

- .github/actionlint.yaml
- .github/workflows/build.yaml
- .github/workflows/initiator.yaml
* __->__ #7990
* #7989
* #7988
* #7987
* #7986
* #7985
* #7984
* #7983
> [ci] Add dedicated build pipeline

- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/transforms/scalarize.cpp
- taichi/transforms/type_check.cpp
> [refactor] Let the type of reference arguments be a pointer

- python/taichi/lang/matrix.py
- python/taichi/types/ndarray_type.py
- tests/python/test_ndarray.py
* #8012
* __->__ #8010
* #8009
> [refactor] Simplify ndarray dtype check_match logic

- python/taichi/examples/minimal.py
- taichi/transforms/constant_fold.cpp
* #8034
* #8026
* #8021
* #8029
* __->__ #8019
* #8018
* #8008
> [ir] Constant fold support for u1

- taichi/ir/frontend_ir.cpp
- taichi/transforms/type_check.cpp
* #8034
* #8026
* #8021
* __->__ #8029
* #8019
* #8018
* #8008
> [ir] Fix: Updated type check for logical not

- taichi/codegen/llvm/codegen_llvm.cpp
- taichi/codegen/spirv/spirv_ir_builder.cpp
- taichi/ir/frontend_ir.cpp
- tests/python/test_logical_op.py
* __->__ #8034
* #8026
* #8021
* #8029
* #8019
* #8018
* #8008
> [lang] [test] Fixed logical operation on numeric values and vectors

- taichi/analysis/verify.cpp
- taichi/ir/frontend_ir.cpp
- taichi/ir/ir.cpp
- taichi/ir/ir.h
- taichi/ir/statements.cpp
- taichi/program/kernel.cpp
- taichi/transforms/auto_diff.cpp
- taichi/transforms/demote_dense_struct_fors.cpp
- taichi/transforms/loop_invariant_detector.h
- taichi/transforms/make_block_local.cpp
- taichi/transforms/make_cpu_multithreaded_range_for.cpp
- taichi/transforms/make_mesh_block_local.cpp
- taichi/transforms/make_mesh_thread_local.cpp
- taichi/transforms/make_thread_local.cpp
Issue: #
Test in https://github.com/taichi-dev/taichi/pull/8025
> [lang] Enable Kernel* access from Block in CHI IR

- taichi/runtime/llvm/runtime_module/runtime.cpp
This reverts commit c46010108c8c02141d0ec2277b65f96ee366bedf.
> Revert "[build] Fix build on arm64 (#7978)"

- python/taichi/lang/any_array.py
- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/program/callable.cpp
- taichi/program/callable.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
- tests/cpp/ir/ir_builder_test.cpp
- tests/cpp/ir/ndarray_kernel.cpp
> [refactor] Simplify ndarray impl by separating ndim and element_shape in IR

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- taichi/ir/type.cpp
> [refactor] Simplify ndarray arg declaration

- .github/workflows/perf.yml
- .github/workflows/release.yml
- .github/workflows/testing.yml
- ci/Dockerfile.tpl
Issue: #
Updated the CI Docker images to use a newer version and set the timezone to `Asia/Shanghai`.
> [ci] Fix Linux build image timezone

- taichi/analysis/gen_offline_cache_key.cpp
- taichi/ir/expression_printer.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
- taichi/transforms/lower_ast.cpp
* #8084
* #8083
* __->__ #8081
> [refactor] Rename dim to ndim for consistency in ExternalTensorExpression

- taichi/analysis/gen_offline_cache_key.cpp
- taichi/ir/expression_printer.h
- taichi/ir/frontend_ir.cpp
- taichi/ir/frontend_ir.h
- taichi/python/export_lang.cpp
* #8084
* __->__ #8083
* #8081
> [refactor] Get rid of unnecessary element_dim in ExternalTensorExpression

- taichi/ir/frontend_ir.cpp
- tests/python/test_unary_ops.py
* #8007
* #8126
* #8125
* #8124
* #8123
* #8122
* __->__ #8115
* #8108
* #8107
> [refactor] [ir] Use get_rvalue_type in frontend IR instead of ret_type

- taichi/ir/type_factory.cpp
* #8007
* #8126
* #8125
* #8124
* __->__ #8123
* #8122
* #8115
* #8108
* #8107
> [Error] Let to_primitive_type throw an error if the type is a pointer

- taichi/ir/frontend_ir.cpp
* #8007
* __->__ #8126
* #8125
* #8124
* #8123
* #8122
* #8115
* #8108
* #8107
> [ir] Update ASTBuilder for the refactor of Alloca

- .github/workflows/testing.yml
Issue: NA
Restart xserver before testing
> [ci] Restart xserver before testing

- python/taichi/math/mathimpl.py
This PR updates the docstring for the `inverse` function in mathimpl.py
> [Doc] Update docstring for inverse func

- python/taichi/examples/real_func/algorithm/marching_squares.py
> [example] Add real func version of marching_square

- python/taichi/lang/ast/ast_transformer.py
- python/taichi/lang/kernel_arguments.py
- python/taichi/lang/kernel_impl.py
- tests/python/test_function.py
> [Lang] Support matrix return value for real function

- python/taichi/examples/real_func/algorithm/poisson_disk_sampling.py
***Don't click the merge button after approval. It is created by ghstack, and it should be merged by commenting `/land` instead of clicking the merge button.***
* __->__ #8209
* #8208
* #8210
* #8207
> [example] Add real func version of poisson_disk_sampling

- python/taichi/types/ndarray_type.py
Issue = #8229
* #8232
* #8231
* __->__ #8230
> [Lang] [bug] Fix error on ndarray type check

- python/taichi/examples/real_func/graph/stable_fluid_graph.py
**Real function does not support returning different types so I have to create many functions with different return types in this example. Don't know if there is a better way to write this.**
* __->__ #8232
* #8231
* #8230
> [example] Add real func ver of stable_fluid_graph

- .github/workflows/scripts/ti_build/dep.py
fix new vulkan extension packages
> [build] Add support for extracting .tar.xz archives in dep.py
